package com.github.GTNH2Mega.fromScripts

import com.github.GTNH2Mega.VoltageLevels.EV
import com.github.GTNH2Mega.VoltageLevels.IV
import com.github.GTNH2Mega.VoltageLevels.LUV
import com.github.GTNH2Mega.VoltageLevels.ZPM
import gttweaker.mods.gregtech.machines.Assembler
import minetweaker.MineTweakerAPI
import minetweaker.api.item.IIngredient
import minetweaker.api.item.IItemStack
import minetweaker.mc1710.brackets.ItemBracketHandler
import minetweaker.mc1710.brackets.OreBracketHandler
import minetweaker.mods.nei.NEI

class AdvSolarPanel : Runnable {
    override fun run() {
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("AdvancedSolarPanel:BlockMolecularTransformer", 0) as IIngredient)
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("AdvancedSolarPanel:asp_crafting_items", 0) as IIngredient)
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("AdvancedSolarPanel:asp_crafting_items", 1) as IIngredient)
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("AdvancedSolarPanel:asp_crafting_items", 2) as IIngredient)
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("AdvancedSolarPanel:asp_crafting_items", 3) as IIngredient)
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("AdvancedSolarPanel:asp_crafting_items", 4) as IIngredient)
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("AdvancedSolarPanel:asp_crafting_items", 12) as IIngredient)
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("AdvancedSolarPanel:advanced_solar_helmet", 0) as IIngredient)
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("AdvancedSolarPanel:hybrid_solar_helmet", 0) as IIngredient)
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("AdvancedSolarPanel:ultimate_solar_helmet", 0) as IIngredient)
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("AdvancedSolarPanel:asp_crafting_items", 5) as IIngredient)
        MineTweakerAPI.furnace.remove(ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 11318) as IIngredient, null)
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("AdvancedSolarPanel:asp_crafting_items", 13) as IIngredient)
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("AdvancedSolarPanel:asp_crafting_items", 12), arrayOf(arrayOf<IIngredient>(ItemBracketHandler.getItem("AdvancedSolarPanel:asp_crafting_items", 5), ItemBracketHandler.getItem("IC2:reactorReflectorThick", 32767), ItemBracketHandler.getItem("AdvancedSolarPanel:asp_crafting_items", 5)), arrayOf<IIngredient>(OreBracketHandler.getOre("plateTitanium"), OreBracketHandler.getOre("craftingToolWrench"), OreBracketHandler.getOre("plateTitanium")), arrayOf<IIngredient>(ItemBracketHandler.getItem("AdvancedSolarPanel:asp_crafting_items", 5), ItemBracketHandler.getItem("IC2:reactorReflectorThick", 32767), ItemBracketHandler.getItem("AdvancedSolarPanel:asp_crafting_items", 5))), null)
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("AdvancedSolarPanel:advanced_solar_helmet", 0), arrayOf(arrayOf(OreBracketHandler.getOre("craftingToolWrench"), ItemBracketHandler.getItem("AdvancedSolarPanel:BlockAdvSolarPanel", 0), OreBracketHandler.getOre("craftingToolScrewdriver")), arrayOf(OreBracketHandler.getOre("circuitAdvanced"), ItemBracketHandler.getItem("IC2:itemArmorNanoHelmet", 32767), OreBracketHandler.getOre("circuitAdvanced")), arrayOf(OreBracketHandler.getOre("cableGt04Aluminium"), ItemBracketHandler.getItem("gregtech:gt.blockmachines", 22), OreBracketHandler.getOre("cableGt04Aluminium"))) as Array<Array<IIngredient>>, null)
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("AdvancedSolarPanel:hybrid_solar_helmet", 0), arrayOf(arrayOf(OreBracketHandler.getOre("craftingToolWrench"), ItemBracketHandler.getItem("AdvancedSolarPanel:BlockAdvSolarPanel", 1), OreBracketHandler.getOre("craftingToolScrewdriver")), arrayOf(OreBracketHandler.getOre("circuitMaster"), ItemBracketHandler.getItem("IC2:itemArmorQuantumHelmet", 32767), OreBracketHandler.getOre("circuitMaster")), arrayOf(OreBracketHandler.getOre("cableGt04Platinum"), ItemBracketHandler.getItem("gregtech:gt.blockmachines", 23), OreBracketHandler.getOre("cableGt04Platinum"))) as Array<Array<IIngredient>>, null)
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("AdvancedSolarPanel:ultimate_solar_helmet", 0), arrayOf(arrayOf<IIngredient>(OreBracketHandler.getOre("craftingToolWrench"), OreBracketHandler.getOre("circuitUltimate"), OreBracketHandler.getOre("craftingToolScrewdriver")), arrayOf(OreBracketHandler.getOre("craftingSolarPanelHV"), ItemBracketHandler.getItem("AdvancedSolarPanel:hybrid_solar_helmet", 32767), OreBracketHandler.getOre("craftingSolarPanelHV")), arrayOf(OreBracketHandler.getOre("cableGt04VanadiumGallium"), ItemBracketHandler.getItem("gregtech:gt.blockmachines", 24), OreBracketHandler.getOre("cableGt04VanadiumGallium"))), null)
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("AdvancedSolarPanel:asp_crafting_items", 5).amount(4), arrayOf(arrayOf(OreBracketHandler.getOre("glassReinforced"), ItemBracketHandler.getItem("AdvancedSolarPanel:asp_crafting_items", 2), OreBracketHandler.getOre("glassReinforced")), arrayOf(ItemBracketHandler.getItem("AdvancedSolarPanel:asp_crafting_items", 2), OreBracketHandler.getOre("plateGlowstone"), ItemBracketHandler.getItem("AdvancedSolarPanel:asp_crafting_items", 2)), arrayOf(OreBracketHandler.getOre("glassReinforced"), ItemBracketHandler.getItem("AdvancedSolarPanel:asp_crafting_items", 2), OreBracketHandler.getOre("glassReinforced"))) as Array<Array<IIngredient>>, null)
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("AdvancedSolarPanel:asp_crafting_items", 13), arrayOf(arrayOf(ItemBracketHandler.getItem("AdvancedSolarPanel:asp_crafting_items", 4), OreBracketHandler.getOre("plateNetherStar"), ItemBracketHandler.getItem("AdvancedSolarPanel:asp_crafting_items", 4)), arrayOf(OreBracketHandler.getOre("plateNetherStar"), ItemBracketHandler.getItem("dreamcraft:item.NanoCircuit", 0), OreBracketHandler.getOre("plateNetherStar")), arrayOf(ItemBracketHandler.getItem("AdvancedSolarPanel:asp_crafting_items", 4), OreBracketHandler.getOre("plateNetherStar"), ItemBracketHandler.getItem("AdvancedSolarPanel:asp_crafting_items", 4))) as Array<Array<IIngredient>>, null)
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32752), arrayOf(arrayOf(OreBracketHandler.getOre("craftingToolCrowbar"), ItemBracketHandler.getItem("AdvancedSolarPanel:BlockAdvSolarPanel", 0), OreBracketHandler.getOre("craftingToolScrewdriver")), arrayOf<IIngredient>(OreBracketHandler.getOre("craftingToolWrench"), OreBracketHandler.getOre("craftingToolHardHammer"), OreBracketHandler.getOre("craftingToolFile"))), null)
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32753), arrayOf(arrayOf(OreBracketHandler.getOre("craftingToolCrowbar"), ItemBracketHandler.getItem("AdvancedSolarPanel:BlockAdvSolarPanel", 1), OreBracketHandler.getOre("craftingToolScrewdriver")), arrayOf<IIngredient>(OreBracketHandler.getOre("craftingToolWrench"), OreBracketHandler.getOre("craftingToolHardHammer"), OreBracketHandler.getOre("craftingToolFile"))), null)
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32754), arrayOf(arrayOf(OreBracketHandler.getOre("craftingToolCrowbar"), ItemBracketHandler.getItem("AdvancedSolarPanel:BlockAdvSolarPanel", 2), OreBracketHandler.getOre("craftingToolScrewdriver")), arrayOf<IIngredient>(OreBracketHandler.getOre("craftingToolWrench"), OreBracketHandler.getOre("craftingToolHardHammer"), OreBracketHandler.getOre("craftingToolFile"))), null)
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32755), arrayOf(arrayOf(OreBracketHandler.getOre("craftingToolCrowbar"), ItemBracketHandler.getItem("AdvancedSolarPanel:BlockAdvSolarPanel", 3), OreBracketHandler.getOre("craftingToolScrewdriver")), arrayOf<IIngredient>(OreBracketHandler.getOre("craftingToolWrench"), OreBracketHandler.getOre("craftingToolHardHammer"), OreBracketHandler.getOre("craftingToolFile"))), null)
        Assembler.addRecipe(ItemBracketHandler.getItem("AdvancedSolarPanel:asp_crafting_items", 2) as IItemStack, ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 11098) as IIngredient, ItemBracketHandler.getItem("minecraft:glowstone", 0).amount(4) as IIngredient, 600, EV)
        Assembler.addRecipe(ItemBracketHandler.getItem("AdvancedSolarPanel:asp_crafting_items", 3) as IItemStack, ItemBracketHandler.getItem("AdvancedSolarPanel:asp_crafting_items", 0) as IIngredient, ItemBracketHandler.getItem("AdvancedSolarPanel:asp_crafting_items", 2).amount(8) as IIngredient, 1200, IV)
        Assembler.addRecipe(ItemBracketHandler.getItem("AdvancedSolarPanel:asp_crafting_items", 1) as IItemStack, ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 17318).amount(4) as IIngredient, ItemBracketHandler.getItem("IC2:itemPartIridium", 0).amount(8) as IIngredient, 800, LUV)
        Assembler.addRecipe(ItemBracketHandler.getItem("AdvancedSolarPanel:asp_crafting_items", 4) as IItemStack, ItemBracketHandler.getItem("AdvancedSolarPanel:asp_crafting_items", 1) as IIngredient, ItemBracketHandler.getItem("AdvancedSolarPanel:asp_crafting_items", 3).amount(8) as IIngredient, 1600, ZPM)
        NEI.overrideName(ItemBracketHandler.getItem("AdvancedSolarPanel:asp_crafting_items", 8) as IItemStack, "Irradiant Reinforced Iridium Plate")
    }
}