package com.github.GTNH2Mega.fromScripts

import java.lang.Runnable
import modtweaker2.mods.thaumcraft.handlers.Arcane
import minetweaker.mc1710.brackets.ItemBracketHandler
import minetweaker.MineTweakerAPI
import modtweaker2.mods.thaumcraft.handlers.Infusion
import modtweaker2.mods.thaumcraft.handlers.Research
import minetweaker.api.item.IIngredient
import minetweaker.mc1710.brackets.OreBracketHandler
import modtweaker2.mods.chisel.handlers.Groups
import modtweaker2.mods.thaumcraft.handlers.Crucible

class Automagy : Runnable {
    override fun run() {
        Arcane.removeRecipe(ItemBracketHandler.getItem("Automagy:blockTorchInversion", 0))
        Crucible.removeRecipe(ItemBracketHandler.getItem("Automagy:blockRedcrystal", 0))
        Arcane.removeRecipe(ItemBracketHandler.getItem("Automagy:blockRedcrystalAmp", 0))
        Arcane.removeRecipe(ItemBracketHandler.getItem("Automagy:blockRedcrystalDense", 0))
        Arcane.removeRecipe(ItemBracketHandler.getItem("Automagy:blockRedcrystalDim", 0))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("Automagy:blockHourglass", 0))
        Arcane.removeRecipe(ItemBracketHandler.getItem("Automagy:blockHourglassMagic", 0))
        Arcane.removeRecipe(ItemBracketHandler.getItem("Automagy:shardSliver", 32767))
        Arcane.removeRecipe(ItemBracketHandler.getItem("Thaumcraft:ItemShard", 32767))
        Arcane.removeRecipe(ItemBracketHandler.getItem("Automagy:blockTranslucent", 32767))
        Infusion.removeEnchant(61)
        Infusion.removeEnchant(62)
        Arcane.removeRecipe(ItemBracketHandler.getItem("Automagy:blockRemoteComparator", 0))
        Crucible.removeRecipe(ItemBracketHandler.getItem("Automagy:crystalEye", 0))
        Arcane.removeRecipe(ItemBracketHandler.getItem("Automagy:blockRedcrystalRes", 0))
        Arcane.removeRecipe(ItemBracketHandler.getItem("Automagy:blockRedcrystalMerc", 0))
        Arcane.removeRecipe(ItemBracketHandler.getItem("Automagy:focusCrafting", 0))
        Research.clearPages("REDSTONETHEORY")
        Research.addPage("REDSTONETHEORY", "Automagy.research_page.REDSTONETHEORY.1")
        Research.addPage("REDSTONETHEORY", "Automagy.research_page.REDSTONETHEORY.2")
        Research.addPage("REDSTONETHEORY", "Automagy.research_page.REDSTONETHEORY.3")
        Arcane.addShaped("REDSTONETHEORY", ItemBracketHandler.getItem("Automagy:blockTorchInversion", 0), "ordo 10", arrayOf(arrayOf<IIngredient?>(null, ItemBracketHandler.getItem("Automagy:shardSliver", 4), null), arrayOf<IIngredient?>(ItemBracketHandler.getItem("Automagy:shardSliver", 4), ItemBracketHandler.getItem("minecraft:redstone_torch", 0), ItemBracketHandler.getItem("Automagy:shardSliver", 4)), arrayOf<IIngredient?>(null, ItemBracketHandler.getItem("Automagy:shardSliver", 4), null)))
        Research.addArcanePage("REDSTONETHEORY", ItemBracketHandler.getItem("Automagy:blockTorchInversion", 0))
        Research.addPage("REDSTONETHEORY", "Automagy.research_page.REDSTONETHEORY.4")
        Arcane.addShaped("REDSTONETHEORY", ItemBracketHandler.getItem("Automagy:blockHourglass", 0), "ordo 15, perditio 10", arrayOf(arrayOf(OreBracketHandler.getOre("ringGold"), ItemBracketHandler.getItem("gregtech:gt.metaitem.02", 32470), OreBracketHandler.getOre("screwGold")), arrayOf(ItemBracketHandler.getItem("Genetics:misc", 8), OreBracketHandler.getOre("dustQuartzSand"), ItemBracketHandler.getItem("Genetics:misc", 8)), arrayOf(OreBracketHandler.getOre("screwGold"), ItemBracketHandler.getItem("gregtech:gt.metaitem.02", 32470), OreBracketHandler.getOre("ringGold"))))
        Research.addArcanePage("REDSTONETHEORY", ItemBracketHandler.getItem("Automagy:blockHourglass", 0))
        Research.addPage("REDSTONETHEORY", "Automagy.research_page.REDSTONETHEORY.5")
        Research.setAspects("REDCRYSTAL", "vitreus 12, gelum 9, praecantatio 6")
        Research.setComplexity("REDCRYSTAL", 3)
        Crucible.addRecipe("REDCRYSTAL", ItemBracketHandler.getItem("Automagy:blockRedcrystal", 0), ItemBracketHandler.getItem("minecraft:redstone", 0), "vitreus 5, gelum 5, praecantatio 5")
        Research.setAspects("REDCRYSTAL", "praecantatio 15, machina 12, potentia 9, vitreus 6, ignis 3")
        Research.setComplexity("REDCRYSTAL", 3)
        Arcane.addShaped("REDCRYSTAL_AMP", ItemBracketHandler.getItem("Automagy:blockRedcrystalAmp", 0), "ignis 10", arrayOf(arrayOf<IIngredient>(ItemBracketHandler.getItem("Automagy:shardSliver", 1), ItemBracketHandler.getItem("Automagy:shardSliver", 1), ItemBracketHandler.getItem("Automagy:shardSliver", 1)), arrayOf<IIngredient>(ItemBracketHandler.getItem("Automagy:shardSliver", 1), ItemBracketHandler.getItem("Automagy:blockRedcrystal", 0), ItemBracketHandler.getItem("Automagy:shardSliver", 1)), arrayOf<IIngredient>(ItemBracketHandler.getItem("Automagy:shardSliver", 1), ItemBracketHandler.getItem("Automagy:shardSliver", 1), ItemBracketHandler.getItem("Automagy:shardSliver", 1))))
        Research.setAspects("REDCRYSTAL", "praecantatio 15, machina 12, potentia 9, vitreus 6, terra 3")
        Research.setComplexity("REDCRYSTAL", 3)
        Arcane.addShaped("REDCRYSTAL_AMP", ItemBracketHandler.getItem("Automagy:blockRedcrystalDense", 0), "terra 10", arrayOf(arrayOf<IIngredient>(ItemBracketHandler.getItem("Automagy:shardSliver", 3), ItemBracketHandler.getItem("Automagy:shardSliver", 3), ItemBracketHandler.getItem("Automagy:shardSliver", 3)), arrayOf<IIngredient>(ItemBracketHandler.getItem("Automagy:shardSliver", 3), ItemBracketHandler.getItem("Automagy:blockRedcrystal", 0), ItemBracketHandler.getItem("Automagy:shardSliver", 3)), arrayOf<IIngredient>(ItemBracketHandler.getItem("Automagy:shardSliver", 3), ItemBracketHandler.getItem("Automagy:shardSliver", 3), ItemBracketHandler.getItem("Automagy:shardSliver", 3))))
        Research.setAspects("REDCRYSTAL", "praecantatio 15, machina 12, potentia 9, vitreus 6, perditio 3")
        Research.setComplexity("REDCRYSTAL", 3)
        Arcane.addShaped("REDCRYSTAL_AMP", ItemBracketHandler.getItem("Automagy:blockRedcrystalDim", 0), "perditio 10", arrayOf(arrayOf<IIngredient>(ItemBracketHandler.getItem("Automagy:shardSliver", 5), ItemBracketHandler.getItem("Automagy:shardSliver", 5), ItemBracketHandler.getItem("Automagy:shardSliver", 5)), arrayOf<IIngredient>(ItemBracketHandler.getItem("Automagy:shardSliver", 5), ItemBracketHandler.getItem("Automagy:blockRedcrystal", 0), ItemBracketHandler.getItem("Automagy:shardSliver", 5)), arrayOf<IIngredient>(ItemBracketHandler.getItem("Automagy:shardSliver", 5), ItemBracketHandler.getItem("Automagy:shardSliver", 5), ItemBracketHandler.getItem("Automagy:shardSliver", 5))))
        Research.clearPages("SLIVERS")
        Research.addPage("SLIVERS", "Automagy.research_page.SLIVERS.1")
        Arcane.addShaped("SLIVERS", ItemBracketHandler.getItem("Automagy:shardSliver", 0).amount(4), "perditio 10, aer 5", arrayOf(arrayOf<IIngredient?>(null, OreBracketHandler.getOre("craftingToolHardHammer"), null), arrayOf<IIngredient?>(null, ItemBracketHandler.getItem("Thaumcraft:ItemShard", 0), null), arrayOfNulls(3)))
        Research.addArcanePage("SLIVERS", ItemBracketHandler.getItem("Automagy:shardSliver", 0))
        Arcane.addShaped("SLIVERS", ItemBracketHandler.getItem("Automagy:shardSliver", 1).amount(4), "perditio 10, ignis 5", arrayOf(arrayOf<IIngredient?>(null, OreBracketHandler.getOre("craftingToolHardHammer"), null), arrayOf<IIngredient?>(null, ItemBracketHandler.getItem("Thaumcraft:ItemShard", 1), null), arrayOfNulls(3)))
        Research.addArcanePage("SLIVERS", ItemBracketHandler.getItem("Automagy:shardSliver", 1))
        Arcane.addShaped("SLIVERS", ItemBracketHandler.getItem("Automagy:shardSliver", 2).amount(4), "perditio 10, aqua 5", arrayOf(arrayOf<IIngredient?>(null, OreBracketHandler.getOre("craftingToolHardHammer"), null), arrayOf<IIngredient?>(null, ItemBracketHandler.getItem("Thaumcraft:ItemShard", 2), null), arrayOfNulls(3)))
        Research.addArcanePage("SLIVERS", ItemBracketHandler.getItem("Automagy:shardSliver", 2))
        Arcane.addShaped("SLIVERS", ItemBracketHandler.getItem("Automagy:shardSliver", 3).amount(4), "perditio 10, terra 5", arrayOf(arrayOf<IIngredient?>(null, OreBracketHandler.getOre("craftingToolHardHammer"), null), arrayOf<IIngredient?>(null, ItemBracketHandler.getItem("Thaumcraft:ItemShard", 3), null), arrayOfNulls(3)))
        Research.addArcanePage("SLIVERS", ItemBracketHandler.getItem("Automagy:shardSliver", 3))
        Arcane.addShaped("SLIVERS", ItemBracketHandler.getItem("Automagy:shardSliver", 4).amount(4), "perditio 10, ordo 5", arrayOf(arrayOf<IIngredient?>(null, OreBracketHandler.getOre("craftingToolHardHammer"), null), arrayOf<IIngredient?>(null, ItemBracketHandler.getItem("Thaumcraft:ItemShard", 4), null), arrayOfNulls(3)))
        Research.addArcanePage("SLIVERS", ItemBracketHandler.getItem("Automagy:shardSliver", 4))
        Arcane.addShaped("SLIVERS", ItemBracketHandler.getItem("Automagy:shardSliver", 5).amount(4), "ordo 10, perditio 5", arrayOf(arrayOf<IIngredient?>(null, OreBracketHandler.getOre("craftingToolHardHammer"), null), arrayOf<IIngredient?>(null, ItemBracketHandler.getItem("Thaumcraft:ItemShard", 5), null), arrayOfNulls(3)))
        Research.addArcanePage("SLIVERS", ItemBracketHandler.getItem("Automagy:shardSliver", 5))
        Arcane.addShaped("SLIVERS", ItemBracketHandler.getItem("Thaumcraft:ItemShard", 0), "ordo 10, aer 5", arrayOf(arrayOf<IIngredient?>(null, ItemBracketHandler.getItem("Automagy:shardSliver", 0), null), arrayOf<IIngredient?>(ItemBracketHandler.getItem("Automagy:shardSliver", 0), ItemBracketHandler.getItem("Thaumcraft:ItemResource", 14), ItemBracketHandler.getItem("Automagy:shardSliver", 0)), arrayOf<IIngredient?>(null, ItemBracketHandler.getItem("Automagy:shardSliver", 0), null)))
        Research.addArcanePage("SLIVERS", ItemBracketHandler.getItem("Thaumcraft:ItemShard", 0))
        Arcane.addShaped("SLIVERS", ItemBracketHandler.getItem("Thaumcraft:ItemShard", 1), "ordo 10, ignis 5", arrayOf(arrayOf<IIngredient?>(null, ItemBracketHandler.getItem("Automagy:shardSliver", 1), null), arrayOf<IIngredient?>(ItemBracketHandler.getItem("Automagy:shardSliver", 1), ItemBracketHandler.getItem("Thaumcraft:ItemResource", 14), ItemBracketHandler.getItem("Automagy:shardSliver", 1)), arrayOf<IIngredient?>(null, ItemBracketHandler.getItem("Automagy:shardSliver", 1), null)))
        Research.addArcanePage("SLIVERS", ItemBracketHandler.getItem("Thaumcraft:ItemShard", 1))
        Arcane.addShaped("SLIVERS", ItemBracketHandler.getItem("Thaumcraft:ItemShard", 2), "ordo 10, aqua 5", arrayOf(arrayOf<IIngredient?>(null, ItemBracketHandler.getItem("Automagy:shardSliver", 2), null), arrayOf<IIngredient?>(ItemBracketHandler.getItem("Automagy:shardSliver", 2), ItemBracketHandler.getItem("Thaumcraft:ItemResource", 14), ItemBracketHandler.getItem("Automagy:shardSliver", 2)), arrayOf<IIngredient?>(null, ItemBracketHandler.getItem("Automagy:shardSliver", 2), null)))
        Research.addArcanePage("SLIVERS", ItemBracketHandler.getItem("Thaumcraft:ItemShard", 2))
        Arcane.addShaped("SLIVERS", ItemBracketHandler.getItem("Thaumcraft:ItemShard", 3), "ordo 10, terra 5", arrayOf(arrayOf<IIngredient?>(null, ItemBracketHandler.getItem("Automagy:shardSliver", 3), null), arrayOf<IIngredient?>(ItemBracketHandler.getItem("Automagy:shardSliver", 3), ItemBracketHandler.getItem("Thaumcraft:ItemResource", 14), ItemBracketHandler.getItem("Automagy:shardSliver", 3)), arrayOf<IIngredient?>(null, ItemBracketHandler.getItem("Automagy:shardSliver", 3), null)))
        Research.addArcanePage("SLIVERS", ItemBracketHandler.getItem("Thaumcraft:ItemShard", 3))
        Arcane.addShaped("SLIVERS", ItemBracketHandler.getItem("Thaumcraft:ItemShard", 4), "perditio 10, ordo 5", arrayOf(arrayOf<IIngredient?>(null, ItemBracketHandler.getItem("Automagy:shardSliver", 4), null), arrayOf<IIngredient?>(ItemBracketHandler.getItem("Automagy:shardSliver", 4), ItemBracketHandler.getItem("Thaumcraft:ItemResource", 14), ItemBracketHandler.getItem("Automagy:shardSliver", 4)), arrayOf<IIngredient?>(null, ItemBracketHandler.getItem("Automagy:shardSliver", 4), null)))
        Research.addArcanePage("SLIVERS", ItemBracketHandler.getItem("Thaumcraft:ItemShard", 4))
        Arcane.addShaped("SLIVERS", ItemBracketHandler.getItem("Thaumcraft:ItemShard", 5), "ordo 10, perditio 5", arrayOf(arrayOf<IIngredient?>(null, ItemBracketHandler.getItem("Automagy:shardSliver", 5), null), arrayOf<IIngredient?>(ItemBracketHandler.getItem("Automagy:shardSliver", 5), ItemBracketHandler.getItem("Thaumcraft:ItemResource", 14), ItemBracketHandler.getItem("Automagy:shardSliver", 5)), arrayOf<IIngredient?>(null, ItemBracketHandler.getItem("Automagy:shardSliver", 5), null)))
        Research.addArcanePage("SLIVERS", ItemBracketHandler.getItem("Thaumcraft:ItemShard", 5))
        Research.orphanResearch("SLIVERS_TRAVEL")
        Research.removeResearch("SLIVERS_TRAVEL")
        Research.orphanResearch("SLIVERS_WARDING")
        Research.removeResearch("SLIVERS_WARDING")
        Research.setAspects("REMOTECOMPARATOR", "potentia 15, machina 12, sensus 9, aer 6, praecantatio 3")
        Research.setComplexity("REMOTECOMPARATOR", 3)
        Arcane.addShaped("REMOTECOMPARATOR", ItemBracketHandler.getItem("Automagy:blockRemoteComparator", 0), "aer 15, ordo 15, perditio 15", arrayOf(arrayOf<IIngredient?>(null, ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 0), null), arrayOf<IIngredient?>(ItemBracketHandler.getItem("Automagy:blockRedcrystal", 0), ItemBracketHandler.getItem("Automagy:blockRedcrystal", 0), ItemBracketHandler.getItem("Automagy:blockRedcrystal", 0)), arrayOf<IIngredient?>(ItemBracketHandler.getItem("Thaumcraft:blockCosmeticSolid", 6), ItemBracketHandler.getItem("ProjRed|Integration:projectred.integration.gate", 26), ItemBracketHandler.getItem("Thaumcraft:blockCosmeticSolid", 6))))
        Crucible.addRecipe("REMOTECOMPARATOR", ItemBracketHandler.getItem("Automagy:crystalEye", 0), ItemBracketHandler.getItem("minecraft:spider_eye", 0), "vitreus 15, sensus 10, praecantatio 5")
        Research.setAspects("REDCRYSTAL_RES", "potentia 15, machina 12, vitreus 9, aer 6, praecantatio 3")
        Research.setComplexity("REDCRYSTAL_RES", 3)
        Arcane.addShaped("REDCRYSTAL_RES", ItemBracketHandler.getItem("Automagy:blockRedcrystalRes", 0), "aer 20, ordo 10", arrayOf(arrayOf<IIngredient>(ItemBracketHandler.getItem("Automagy:shardSliver", 0), ItemBracketHandler.getItem("appliedenergistics2:item.ItemMultiMaterial", 11), ItemBracketHandler.getItem("Automagy:shardSliver", 0)), arrayOf<IIngredient>(ItemBracketHandler.getItem("appliedenergistics2:item.ItemMultiMaterial", 11), ItemBracketHandler.getItem("Automagy:blockRedcrystal", 0), ItemBracketHandler.getItem("appliedenergistics2:item.ItemMultiMaterial", 11)), arrayOf<IIngredient>(ItemBracketHandler.getItem("Automagy:shardSliver", 0), ItemBracketHandler.getItem("appliedenergistics2:item.ItemMultiMaterial", 11), ItemBracketHandler.getItem("Automagy:shardSliver", 0))))
        Research.setAspects("REDCRYSTAL_MIRRORBOUND", "iter 15, potentia 12, tenebrae 9, terra 6, praecantatio 3")
        Research.setComplexity("REDCRYSTAL_MIRRORBOUND", 3)
        Arcane.addShaped("REDCRYSTAL_MIRRORBOUND", ItemBracketHandler.getItem("Automagy:blockRedcrystalMerc", 0), "ordo 25, aer 20, perditio 10, ignis 20, terra 15", arrayOf(arrayOf<IIngredient>(ItemBracketHandler.getItem("Automagy:blockRedcrystal", 0), ItemBracketHandler.getItem("Automagy:blockRedcrystalRes", 0), ItemBracketHandler.getItem("Automagy:blockRedcrystal", 0)), arrayOf<IIngredient>(ItemBracketHandler.getItem("Thaumcraft:ItemResource", 10), ItemBracketHandler.getItem("Thaumcraft:ItemResource", 3), ItemBracketHandler.getItem("Thaumcraft:ItemResource", 10)), arrayOf<IIngredient>(ItemBracketHandler.getItem("Thaumcraft:blockCosmeticSolid", 6), ItemBracketHandler.getItem("Thaumcraft:ItemResource", 10), ItemBracketHandler.getItem("Thaumcraft:blockCosmeticSolid", 6))))
        Research.setAspects("FOCUSCRAFTING", "fabrico 15, praecantatio 12, intrumentum 9, terra 6, praecantatio 3")
        Research.setComplexity("FOCUSCRAFTING", 3)
        Arcane.addShaped("FOCUSCRAFTING", ItemBracketHandler.getItem("Automagy:focusCrafting", 0), "ordo 50, terra 40, perditio 30, aer 20, aqua 10", arrayOf(arrayOf<IIngredient>(ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 4), ItemBracketHandler.getItem("Thaumcraft:ItemShard", 6), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 4)), arrayOf<IIngredient>(ItemBracketHandler.getItem("appliedenergistics2:item.ItemMultiMaterial", 11), ItemBracketHandler.getItem("Thaumcraft:blockTable", 15), ItemBracketHandler.getItem("appliedenergistics2:item.ItemMultiMaterial", 11)), arrayOf<IIngredient>(ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 3), ItemBracketHandler.getItem("Thaumcraft:ItemShard", 6), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 3))))
        Research.addResearch("InfusedGoldGTNH", "AUTOMAGY", "lucrum 12, praecantatio 9, aer 6, metallum 3", -5, -2, 3, ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 11323))
        MineTweakerAPI.game.setLocalization("tc.research_name.InfusedGoldGTNH", "Infused Gold")
        MineTweakerAPI.game.setLocalization("tc.research_text.InfusedGoldGTNH", "[AM] Infuse Gold with magic.")
        Research.addPage("InfusedGoldGTNH", "tc.research_page.InfusedGoldGTNH.1")
        MineTweakerAPI.game.setLocalization("tc.research_page.InfusedGoldGTNH.1", "You found a way to fuse gold and thaumium to create a new metal INFUSED GOLD")
        Research.addPrereq("InfusedGoldGTNH", "INFUSION", false)
        Research.addPrereq("InfusedGoldGTNH", "THAUMIUM", false)
        Infusion.addRecipe("InfusedGoldGTNH", ItemBracketHandler.getItem("minecraft:gold_ingot", 0), arrayOf(ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 2330), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 2330), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 2330), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 2330)), "lucrum 16, metallum 12, ordo 8, praecantatio 4, aer 4", ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 11323), 2)
        Research.addInfusionPage("InfusedGoldGTNH", ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 11323))
        Research.clearPrereqs("MAGICHOURGLASS")
        Research.addPrereq("MAGICHOURGLASS", "INFUSION", false)
        Research.addPrereq("MAGICHOURGLASS", "InfusedGoldGTNH", false)
        Research.addPrereq("MAGICHOURGLASS", "REDCRYSTAL", false)
        Research.setAspects("MAGICHOURGLASS", "machina 15, motus 12, potentia 9, aer 6, praecantatio 3")
        Research.setComplexity("MAGICHOURGLASS", 4)
        Arcane.addShaped("MAGICHOURGLASS", ItemBracketHandler.getItem("Automagy:blockHourglassMagic", 0), "ordo 20, perditio 15, aer 10, terra 5", arrayOf(arrayOf(OreBracketHandler.getOre("screwInfusedGold"), ItemBracketHandler.getItem("Automagy:blockRedcrystal", 0), OreBracketHandler.getOre("screwInfusedGold")), arrayOf<IIngredient>(ItemBracketHandler.getItem("Automagy:shardSliver", 0), ItemBracketHandler.getItem("Automagy:blockHourglass", 0), ItemBracketHandler.getItem("Automagy:shardSliver", 4)), arrayOf(OreBracketHandler.getOre("plateInfusedGold"), ItemBracketHandler.getItem("minecraft:light_weighted_pressure_plate", 0), OreBracketHandler.getOre("plateInfusedGold"))))
        Research.clearPages("NITORLIGHT")
        Research.addPage("NITORLIGHT", "Automagy.research_page.REDSTONETHEORY.1")
        Research.setAspects("NITORLIGHT", "lux 12, ignis 9, aer 6")
        Research.setComplexity("NITORLIGHT", 3)
        Arcane.addShaped("NITORLIGHT", ItemBracketHandler.getItem("Automagy:blockTranslucent", 0), "ignis 10, aqua 5, terra 5", arrayOf(arrayOf<IIngredient?>(null, OreBracketHandler.getOre("plateAmber"), null), arrayOf(OreBracketHandler.getOre("plateAmber"), ItemBracketHandler.getItem("Thaumcraft:ItemResource", 1), OreBracketHandler.getOre("plateAmber")), arrayOf<IIngredient?>(null, OreBracketHandler.getOre("plateAmber"), null)))
        Research.addArcanePage("NITORLIGHT", ItemBracketHandler.getItem("Automagy:blockTranslucent", 0))
        Groups.addGroup("nitorLightAutomagy")
        Groups.addVariation("nitorLightAutomagy", ItemBracketHandler.getItem("Automagy:blockTranslucent", 0))
        Groups.addVariation("nitorLightAutomagy", ItemBracketHandler.getItem("Automagy:blockTranslucent", 1))
        Research.clearPages("ENCHANT_FISHING")
        Research.addPage("ENCHANT_FISHING", "Automagy.research_page.ENCHANT_FISHING.1")
        Infusion.addEnchantment("ENCHANT_FISHING", 61, 3, "aqua 15, bestia 15, fames 10, meto 15, praecantatio 10", arrayOf(ItemBracketHandler.getItem("minecraft:carrot_on_a_stick", 0), ItemBracketHandler.getItem("Thaumcraft:ItemResource", 14), ItemBracketHandler.getItem("minecraft:sugar", 0), ItemBracketHandler.getItem("Thaumcraft:ItemResource", 14)))
        Infusion.addEnchantment("ENCHANT_FISHING", 62, 4, "aqua 15, bestia 15, meto 15, lucrum 10, praecantatio 10", arrayOf(ItemBracketHandler.getItem("minecraft:golden_carrot", 0), ItemBracketHandler.getItem("Thaumcraft:ItemResource", 14), ItemBracketHandler.getItem("minecraft:tripwire_hook", 0), ItemBracketHandler.getItem("Thaumcraft:ItemResource", 14)))
        Research.addEnchantmentPage("ENCHANT_FISHING", 61)
        Research.addEnchantmentPage("ENCHANT_FISHING", 62)
        Research.refreshResearchRecipe("REDSTONETHEORY")
        Research.refreshResearchRecipe("REDCRYSTAL")
        Research.refreshResearchRecipe("REDCRYSTAL_AMP")
        Research.refreshResearchRecipe("REDCRYSTAL_DENSE")
        Research.refreshResearchRecipe("REDCRYSTAL_DIM")
        Research.refreshResearchRecipe("MAGICHOURGLASS")
        Research.refreshResearchRecipe("SLIVERS")
        Research.refreshResearchRecipe("NITORLIGHT")
        Research.refreshResearchRecipe("ENCHANT_FISHING")
        Research.refreshResearchRecipe("REMOTECOMPARATOR")
        Research.refreshResearchRecipe("REDCRYSTAL_RES")
        Research.refreshResearchRecipe("REDCRYSTAL_MIRRORBOUND")
        Research.refreshResearchRecipe("FOCUSCRAFTING")
    }
}