package com.github.GTNH2Mega.fromScripts

import com.github.GTNH2Mega.VoltageLevels.HV
import com.github.GTNH2Mega.VoltageLevels.LULV
import com.github.GTNH2Mega.VoltageLevels.MV
import com.github.GTNH2Mega.VoltageLevels.UV
import java.lang.Runnable
import minetweaker.MineTweakerAPI
import minetweaker.mc1710.brackets.ItemBracketHandler
import fox.spiteful.avaritia.compat.minetweaker.ExtremeCrafting
import gttweaker.mods.gregtech.machines.*
import minetweaker.api.item.IItemStack
import minetweaker.api.data.IData
import minetweaker.expand.ExpandString
import minetweaker.expand.ExpandAnyDict
import modtweaker2.mods.thaumcraft.handlers.Infusion
import minetweaker.api.item.IIngredient
import minetweaker.mc1710.brackets.OreBracketHandler
import minetweaker.expand.ExpandShort
import minetweaker.expand.ExpandAnyArray
import minetweaker.expand.ExpandByte
import minetweaker.expand.ExpandInt
import modtweaker2.mods.thaumcraft.handlers.Research
import minetweaker.mods.ic2.machines.Compressor
import minetweaker.mods.ic2.machines.Extractor
import java.util.HashMap

class Avaritia : Runnable {
    override fun run() {
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("Avaritia:Double_Craft", 0))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("Avaritia:Triple_Craft", 0))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("Avaritia:Resource", 0))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("Avaritia:Resource", 1))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("Avaritia:Dire_Crafting", 0))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("Avaritia:Crystal_Matrix", 0))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("Avaritia:Resource_Block", 0))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("Avaritia:Resource_Block", 1))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("Avaritia:Resource", 2))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("Avaritia:Resource", 3))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("Avaritia:Resource", 4))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("Avaritia:Resource", 6))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("Avaritia:Resource", 7))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("eternalsingularity:combined_singularity", 32767))
        ExtremeCrafting.remove(ItemBracketHandler.getItem("Avaritia:Neutron_Collector", 0))
        ExtremeCrafting.remove(ItemBracketHandler.getItem("Avaritia:Neutronium_Compressor", 0))
        ExtremeCrafting.remove(ItemBracketHandler.getItem("eternalsingularity:eternal_singularity", 0))
        ExtremeCrafting.remove(ItemBracketHandler.getItem("Avaritia:Orb_Armok", 0))
        ExtremeCrafting.remove(ItemBracketHandler.getItem("Avaritia:Infinity_Sword", 0))
        ExtremeCrafting.remove(ItemBracketHandler.getItem("Avaritia:Infinity_Pickaxe", 0))
        ExtremeCrafting.remove(ItemBracketHandler.getItem("Avaritia:Infinity_Shovel", 0))
        val iItemStack = ItemBracketHandler.getItem("Thaumcraft:WandCasting", 9000)
        val hashMap = HashMap<String, IData>()
        hashMap["cap"] = ExpandString.asData("matrix")
        hashMap["rod"] = ExpandString.asData("infinity")
        ExtremeCrafting.remove(iItemStack.withTag(ExpandAnyDict.asData(hashMap)))
        ExtremeCrafting.remove(ItemBracketHandler.getItem("Avaritia:Infinity_Axe", 0))
        ExtremeCrafting.remove(ItemBracketHandler.getItem("Avaritia:Infinity_Bow", 0))
        Infusion.removeRecipe(ItemBracketHandler.getItem("Avaritia:Akashic_Record", 0))
        ExtremeCrafting.remove(ItemBracketHandler.getItem("Avaritia:Infinity_Helm", 0))
        ExtremeCrafting.remove(ItemBracketHandler.getItem("Avaritia:Infinity_Chest", 0))
        ExtremeCrafting.remove(ItemBracketHandler.getItem("Avaritia:Infinity_Pants", 0))
        ExtremeCrafting.remove(ItemBracketHandler.getItem("Avaritia:Infinity_Shoes", 0))
        ExtremeCrafting.remove(ItemBracketHandler.getItem("Avaritia:Skull_Sword", 0))
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("Avaritia:Dire_Crafting", 0), arrayOf(arrayOf<IIngredient>(ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32652), ItemBracketHandler.getItem("Avaritia:Triple_Craft", 0), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32652)), arrayOf(OreBracketHandler.getOre("waferAdvanced"), ItemBracketHandler.getItem("Avaritia:Crystal_Matrix", 0), OreBracketHandler.getOre("waferAdvanced")), arrayOf(ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32642), OreBracketHandler.getOre("circuitElite"), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32642))), null)
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("Avaritia:Resource", 0), arrayOf(arrayOf<IIngredient>(OreBracketHandler.getOre("screwDiamond"), OreBracketHandler.getOre("plateDiamond"), OreBracketHandler.getOre("screwDiamond")), arrayOf(OreBracketHandler.getOre("plateDiamond"), ItemBracketHandler.getItem("dreamcraft:item.StainlessSteelBars", 0), OreBracketHandler.getOre("plateDiamond")), arrayOf<IIngredient>(OreBracketHandler.getOre("screwDiamond"), OreBracketHandler.getOre("plateDiamond"), OreBracketHandler.getOre("screwDiamond"))), null)
        ExtremeCrafting.addShaped(ItemBracketHandler.getItem("eternalsingularity:combined_singularity", 0), arrayOf(arrayOfNulls(9), arrayOf<IIngredient?>(null, null, OreBracketHandler.getOre("blockBlackPlutonium"), OreBracketHandler.getOre("blockBlackPlutonium"), null, null, OreBracketHandler.getOre("blockBlackPlutonium"), null, null), arrayOf(null, OreBracketHandler.getOre("blockBlackPlutonium"), null, null, ItemBracketHandler.getItem("Avaritia:Singularity", 2), null, null, OreBracketHandler.getOre("blockBlackPlutonium"), null), arrayOf(null, null, null, ItemBracketHandler.getItem("Avaritia:Singularity", 1), ItemBracketHandler.getItem("ExtraUtilities:block_bedrockium", 0), ItemBracketHandler.getItem("Avaritia:Singularity", 8), null, OreBracketHandler.getOre("blockBlackPlutonium"), null), arrayOf<IIngredient?>(null, null, ItemBracketHandler.getItem("Avaritia:Singularity", 0), ItemBracketHandler.getItem("ExtraUtilities:block_bedrockium", 0), ItemBracketHandler.getItem("Avaritia:Singularity", 3), ItemBracketHandler.getItem("ExtraUtilities:block_bedrockium", 0), ItemBracketHandler.getItem("Avaritia:Singularity", 6), null, null), arrayOf(null, OreBracketHandler.getOre("blockBlackPlutonium"), null, ItemBracketHandler.getItem("Avaritia:Singularity", 7), ItemBracketHandler.getItem("ExtraUtilities:block_bedrockium", 0), ItemBracketHandler.getItem("Avaritia:Singularity", 5), null, null, null), arrayOf(null, OreBracketHandler.getOre("blockBlackPlutonium"), null, null, ItemBracketHandler.getItem("Avaritia:Singularity", 4), null, null, OreBracketHandler.getOre("blockBlackPlutonium"), null), arrayOf<IIngredient?>(null, null, OreBracketHandler.getOre("blockBlackPlutonium"), null, null, OreBracketHandler.getOre("blockBlackPlutonium"), OreBracketHandler.getOre("blockBlackPlutonium"), null, null), arrayOfNulls(9)))
        ExtremeCrafting.addShaped(ItemBracketHandler.getItem("eternalsingularity:combined_singularity", 1), arrayOf(arrayOfNulls(9), arrayOf<IIngredient?>(null, null, OreBracketHandler.getOre("blockBlackPlutonium"), OreBracketHandler.getOre("blockBlackPlutonium"), null, null, OreBracketHandler.getOre("blockBlackPlutonium"), null, null), arrayOf(null, OreBracketHandler.getOre("blockBlackPlutonium"), null, null, ItemBracketHandler.getItem("Avaritia:Singularity", 9), null, null, OreBracketHandler.getOre("blockBlackPlutonium"), null), arrayOf(null, null, null, ItemBracketHandler.getItem("Avaritia:Singularity", 10), ItemBracketHandler.getItem("ExtraUtilities:block_bedrockium", 0), ItemBracketHandler.getItem("universalsingularities:universal.vanilla.singularity", 0), null, OreBracketHandler.getOre("blockBlackPlutonium"), null), arrayOf<IIngredient?>(null, null, ItemBracketHandler.getItem("universalsingularities:universal.vanilla.singularity", 2), ItemBracketHandler.getItem("ExtraUtilities:block_bedrockium", 0), ItemBracketHandler.getItem("universalsingularities:universal.vanilla.singularity", 1), ItemBracketHandler.getItem("ExtraUtilities:block_bedrockium", 0), ItemBracketHandler.getItem("universalsingularities:universal.general.singularity", 3), null, null), arrayOf(null, OreBracketHandler.getOre("blockBlackPlutonium"), null, ItemBracketHandler.getItem("universalsingularities:universal.general.singularity", 0), ItemBracketHandler.getItem("ExtraUtilities:block_bedrockium", 0), ItemBracketHandler.getItem("universalsingularities:universal.general.singularity", 1), null, null, null), arrayOf(null, OreBracketHandler.getOre("blockBlackPlutonium"), null, null, ItemBracketHandler.getItem("universalsingularities:universal.general.singularity", 2), null, null, OreBracketHandler.getOre("blockBlackPlutonium"), null), arrayOf<IIngredient?>(null, null, OreBracketHandler.getOre("blockBlackPlutonium"), null, null, OreBracketHandler.getOre("blockBlackPlutonium"), OreBracketHandler.getOre("blockBlackPlutonium"), null, null), arrayOfNulls(9)))
        ExtremeCrafting.addShaped(ItemBracketHandler.getItem("eternalsingularity:combined_singularity", 2), arrayOf(arrayOfNulls(9), arrayOf<IIngredient?>(null, null, OreBracketHandler.getOre("blockBlackPlutonium"), OreBracketHandler.getOre("blockBlackPlutonium"), null, null, OreBracketHandler.getOre("blockBlackPlutonium"), null, null), arrayOf(null, OreBracketHandler.getOre("blockBlackPlutonium"), null, null, ItemBracketHandler.getItem("universalsingularities:universal.general.singularity", 4), null, null, OreBracketHandler.getOre("blockBlackPlutonium"), null), arrayOf(null, null, null, ItemBracketHandler.getItem("universalsingularities:universal.general.singularity", 5), ItemBracketHandler.getItem("ExtraUtilities:block_bedrockium", 0), ItemBracketHandler.getItem("universalsingularities:universal.general.singularity", 6), null, OreBracketHandler.getOre("blockBlackPlutonium"), null), arrayOf<IIngredient?>(null, null, ItemBracketHandler.getItem("universalsingularities:universal.general.singularity", 7), ItemBracketHandler.getItem("ExtraUtilities:block_bedrockium", 0), ItemBracketHandler.getItem("universalsingularities:universal.general.singularity", 8), ItemBracketHandler.getItem("ExtraUtilities:block_bedrockium", 0), ItemBracketHandler.getItem("universalsingularities:universal.general.singularity", 9), null, null), arrayOf(null, OreBracketHandler.getOre("blockBlackPlutonium"), null, ItemBracketHandler.getItem("universalsingularities:universal.general.singularity", 10), ItemBracketHandler.getItem("ExtraUtilities:block_bedrockium", 0), ItemBracketHandler.getItem("universalsingularities:universal.general.singularity", 11), null, null, null), arrayOf(null, OreBracketHandler.getOre("blockBlackPlutonium"), null, null, ItemBracketHandler.getItem("universalsingularities:universal.general.singularity", 12), null, null, OreBracketHandler.getOre("blockBlackPlutonium"), null), arrayOf<IIngredient?>(null, null, OreBracketHandler.getOre("blockBlackPlutonium"), null, null, OreBracketHandler.getOre("blockBlackPlutonium"), OreBracketHandler.getOre("blockBlackPlutonium"), null, null), arrayOfNulls(9)))
        ExtremeCrafting.addShaped(ItemBracketHandler.getItem("eternalsingularity:combined_singularity", 3), arrayOf(arrayOfNulls(9), arrayOf<IIngredient?>(null, null, OreBracketHandler.getOre("blockBlackPlutonium"), OreBracketHandler.getOre("blockBlackPlutonium"), null, null, OreBracketHandler.getOre("blockBlackPlutonium"), null, null), arrayOf(null, OreBracketHandler.getOre("blockBlackPlutonium"), null, null, ItemBracketHandler.getItem("universalsingularities:universal.general.singularity", 13), null, null, OreBracketHandler.getOre("blockBlackPlutonium"), null), arrayOf(null, null, null, ItemBracketHandler.getItem("universalsingularities:universal.general.singularity", 14), ItemBracketHandler.getItem("ExtraUtilities:block_bedrockium", 0), ItemBracketHandler.getItem("universalsingularities:universal.general.singularity", 15), null, OreBracketHandler.getOre("blockBlackPlutonium"), null), arrayOf<IIngredient?>(null, null, ItemBracketHandler.getItem("universalsingularities:universal.general.singularity", 16), ItemBracketHandler.getItem("ExtraUtilities:block_bedrockium", 0), ItemBracketHandler.getItem("universalsingularities:universal.general.singularity", 17), ItemBracketHandler.getItem("ExtraUtilities:block_bedrockium", 0), ItemBracketHandler.getItem("universalsingularities:universal.general.singularity", 18), null, null), arrayOf(null, OreBracketHandler.getOre("blockBlackPlutonium"), null, ItemBracketHandler.getItem("universalsingularities:universal.general.singularity", 19), ItemBracketHandler.getItem("ExtraUtilities:block_bedrockium", 0), ItemBracketHandler.getItem("universalsingularities:universal.general.singularity", 20), null, null, null), arrayOf(null, OreBracketHandler.getOre("blockBlackPlutonium"), null, null, ItemBracketHandler.getItem("universalsingularities:universal.general.singularity", 21), null, null, OreBracketHandler.getOre("blockBlackPlutonium"), null), arrayOf<IIngredient?>(null, null, OreBracketHandler.getOre("blockBlackPlutonium"), null, null, OreBracketHandler.getOre("blockBlackPlutonium"), OreBracketHandler.getOre("blockBlackPlutonium"), null, null), arrayOfNulls(9)))
        ExtremeCrafting.addShaped(ItemBracketHandler.getItem("eternalsingularity:combined_singularity", 4), arrayOf(arrayOfNulls(9), arrayOf<IIngredient?>(null, null, OreBracketHandler.getOre("blockBlackPlutonium"), OreBracketHandler.getOre("blockBlackPlutonium"), null, null, OreBracketHandler.getOre("blockBlackPlutonium"), null, null), arrayOf(null, OreBracketHandler.getOre("blockBlackPlutonium"), null, null, ItemBracketHandler.getItem("universalsingularities:universal.general.singularity", 22), null, null, OreBracketHandler.getOre("blockBlackPlutonium"), null), arrayOf(null, null, null, ItemBracketHandler.getItem("universalsingularities:universal.general.singularity", 23), ItemBracketHandler.getItem("ExtraUtilities:block_bedrockium", 0), ItemBracketHandler.getItem("universalsingularities:universal.general.singularity", 24), null, OreBracketHandler.getOre("blockBlackPlutonium"), null), arrayOf<IIngredient?>(null, null, ItemBracketHandler.getItem("universalsingularities:universal.general.singularity", 25), ItemBracketHandler.getItem("ExtraUtilities:block_bedrockium", 0), ItemBracketHandler.getItem("universalsingularities:universal.general.singularity", 26), ItemBracketHandler.getItem("ExtraUtilities:block_bedrockium", 0), ItemBracketHandler.getItem("universalsingularities:universal.general.singularity", 27), null, null), arrayOf(null, OreBracketHandler.getOre("blockBlackPlutonium"), null, ItemBracketHandler.getItem("universalsingularities:universal.general.singularity", 28), ItemBracketHandler.getItem("ExtraUtilities:block_bedrockium", 0), ItemBracketHandler.getItem("universalsingularities:universal.general.singularity", 29), null, null, null), arrayOf(null, OreBracketHandler.getOre("blockBlackPlutonium"), null, null, ItemBracketHandler.getItem("universalsingularities:universal.general.singularity", 30), null, null, OreBracketHandler.getOre("blockBlackPlutonium"), null), arrayOf<IIngredient?>(null, null, OreBracketHandler.getOre("blockBlackPlutonium"), null, null, OreBracketHandler.getOre("blockBlackPlutonium"), OreBracketHandler.getOre("blockBlackPlutonium"), null, null), arrayOfNulls(9)))
        ExtremeCrafting.addShaped(ItemBracketHandler.getItem("eternalsingularity:combined_singularity", 5), arrayOf(arrayOfNulls(9), arrayOf<IIngredient?>(null, null, OreBracketHandler.getOre("blockBlackPlutonium"), OreBracketHandler.getOre("blockBlackPlutonium"), null, null, OreBracketHandler.getOre("blockBlackPlutonium"), null, null), arrayOf(null, OreBracketHandler.getOre("blockBlackPlutonium"), null, null, ItemBracketHandler.getItem("universalsingularities:universal.draconicEvolution.singularity", 0), null, null, OreBracketHandler.getOre("blockBlackPlutonium"), null), arrayOf(null, null, null, ItemBracketHandler.getItem("universalsingularities:universal.draconicEvolution.singularity", 1), ItemBracketHandler.getItem("ExtraUtilities:block_bedrockium", 0), ItemBracketHandler.getItem("universalsingularities:universal.enderIO.singularity", 0), null, OreBracketHandler.getOre("blockBlackPlutonium"), null), arrayOf<IIngredient?>(null, null, ItemBracketHandler.getItem("universalsingularities:universal.enderIO.singularity", 1), ItemBracketHandler.getItem("ExtraUtilities:block_bedrockium", 0), ItemBracketHandler.getItem("universalsingularities:universal.enderIO.singularity", 2), ItemBracketHandler.getItem("ExtraUtilities:block_bedrockium", 0), ItemBracketHandler.getItem("universalsingularities:universal.enderIO.singularity", 3), null, null), arrayOf(null, OreBracketHandler.getOre("blockBlackPlutonium"), null, ItemBracketHandler.getItem("universalsingularities:universal.enderIO.singularity", 4), ItemBracketHandler.getItem("ExtraUtilities:block_bedrockium", 0), ItemBracketHandler.getItem("universalsingularities:universal.enderIO.singularity", 5), null, null, null), arrayOf(null, OreBracketHandler.getOre("blockBlackPlutonium"), null, null, ItemBracketHandler.getItem("universalsingularities:universal.enderIO.singularity", 6), null, null, OreBracketHandler.getOre("blockBlackPlutonium"), null), arrayOf<IIngredient?>(null, null, OreBracketHandler.getOre("blockBlackPlutonium"), null, null, OreBracketHandler.getOre("blockBlackPlutonium"), OreBracketHandler.getOre("blockBlackPlutonium"), null, null), arrayOfNulls(9)))
        ExtremeCrafting.addShaped(ItemBracketHandler.getItem("eternalsingularity:combined_singularity", 6), arrayOf(arrayOfNulls(9), arrayOf<IIngredient?>(null, null, OreBracketHandler.getOre("blockBlackPlutonium"), OreBracketHandler.getOre("blockBlackPlutonium"), null, null, OreBracketHandler.getOre("blockBlackPlutonium"), null, null), arrayOf(null, OreBracketHandler.getOre("blockBlackPlutonium"), null, null, ItemBracketHandler.getItem("universalsingularities:universal.enderIO.singularity", 7), null, null, OreBracketHandler.getOre("blockBlackPlutonium"), null), arrayOf(null, null, null, ItemBracketHandler.getItem("universalsingularities:universal.extraUtilities.singularity", 0), ItemBracketHandler.getItem("ExtraUtilities:block_bedrockium", 0), ItemBracketHandler.getItem("universalsingularities:universal.projectRed.singularity", 0), null, OreBracketHandler.getOre("blockBlackPlutonium"), null), arrayOf<IIngredient?>(null, null, ItemBracketHandler.getItem("universalsingularities:universal.tinkersConstruct.singularity", 0), ItemBracketHandler.getItem("ExtraUtilities:block_bedrockium", 0), ItemBracketHandler.getItem("universalsingularities:universal.tinkersConstruct.singularity", 1), ItemBracketHandler.getItem("ExtraUtilities:block_bedrockium", 0), ItemBracketHandler.getItem("universalsingularities:universal.tinkersConstruct.singularity", 2), null, null), arrayOf(null, OreBracketHandler.getOre("blockBlackPlutonium"), null, ItemBracketHandler.getItem("universalsingularities:universal.tinkersConstruct.singularity", 3), ItemBracketHandler.getItem("ExtraUtilities:block_bedrockium", 0), ItemBracketHandler.getItem("universalsingularities:universal.tinkersConstruct.singularity", 4), null, null, null), arrayOf(null, OreBracketHandler.getOre("blockBlackPlutonium"), null, null, ItemBracketHandler.getItem("universalsingularities:universal.tinkersConstruct.singularity", 6), null, null, OreBracketHandler.getOre("blockBlackPlutonium"), null), arrayOf<IIngredient?>(null, null, OreBracketHandler.getOre("blockBlackPlutonium"), null, null, OreBracketHandler.getOre("blockBlackPlutonium"), OreBracketHandler.getOre("blockBlackPlutonium"), null, null), arrayOfNulls(9)))
        ExtremeCrafting.addShaped(ItemBracketHandler.getItem("eternalsingularity:eternal_singularity", 0), arrayOf(arrayOf<IIngredient?>(null, null, null, null, null, ItemBracketHandler.getItem("Avaritia:Resource_Block", 0), null, null, null), arrayOf<IIngredient?>(null, null, OreBracketHandler.getOre("blockBlackPlutonium"), OreBracketHandler.getOre("blockBlackPlutonium"), null, null, OreBracketHandler.getOre("blockBlackPlutonium"), null, null), arrayOf(null, OreBracketHandler.getOre("blockBlackPlutonium"), null, null, ItemBracketHandler.getItem("eternalsingularity:combined_singularity", 0), null, null, OreBracketHandler.getOre("blockBlackPlutonium"), null), arrayOf(ItemBracketHandler.getItem("Avaritia:Resource_Block", 0), null, null, ItemBracketHandler.getItem("eternalsingularity:combined_singularity", 1), ItemBracketHandler.getItem("Avaritia:Resource_Block", 0), ItemBracketHandler.getItem("eternalsingularity:combined_singularity", 2), null, OreBracketHandler.getOre("blockBlackPlutonium"), null), arrayOf<IIngredient?>(null, null, ItemBracketHandler.getItem("Avaritia:Resource_Block", 0), ItemBracketHandler.getItem("Avaritia:Resource_Block", 0), ItemBracketHandler.getItem("eternalsingularity:combined_singularity", 3), ItemBracketHandler.getItem("Avaritia:Resource_Block", 0), ItemBracketHandler.getItem("Avaritia:Resource_Block", 0), null, null), arrayOf(null, OreBracketHandler.getOre("blockBlackPlutonium"), null, ItemBracketHandler.getItem("eternalsingularity:combined_singularity", 4), ItemBracketHandler.getItem("Avaritia:Resource_Block", 0), ItemBracketHandler.getItem("eternalsingularity:combined_singularity", 5), null, null, ItemBracketHandler.getItem("Avaritia:Resource_Block", 0)), arrayOf(null, OreBracketHandler.getOre("blockBlackPlutonium"), null, null, ItemBracketHandler.getItem("eternalsingularity:combined_singularity", 6), null, null, OreBracketHandler.getOre("blockBlackPlutonium"), null), arrayOf<IIngredient?>(null, null, OreBracketHandler.getOre("blockBlackPlutonium"), null, null, OreBracketHandler.getOre("blockBlackPlutonium"), OreBracketHandler.getOre("blockBlackPlutonium"), null, null), arrayOf<IIngredient?>(null, null, null, ItemBracketHandler.getItem("Avaritia:Resource_Block", 0), null, null, null, null, null)))
        ExtremeCrafting.addShaped(ItemBracketHandler.getItem("Avaritia:Orb_Armok", 0), arrayOf(arrayOf<IIngredient?>(null, null, null, OreBracketHandler.getOre("plateInfinity"), OreBracketHandler.getOre("plateInfinity"), OreBracketHandler.getOre("plateInfinity"), null, null, null), arrayOf(null, null, OreBracketHandler.getOre("plateInfinity"), ItemBracketHandler.getItem("ForbiddenMagic:EldritchOrb", 0), OreBracketHandler.getOre("plateInfinity"), ItemBracketHandler.getItem("ForbiddenMagic:EldritchOrb", 0), OreBracketHandler.getOre("plateInfinity"), null, null), arrayOf(null, null, OreBracketHandler.getOre("plateInfinity"), OreBracketHandler.getOre("plateInfinity"), ItemBracketHandler.getItem("BloodArsenal:blood_infused_diamond_block", 0), OreBracketHandler.getOre("plateInfinity"), OreBracketHandler.getOre("plateInfinity"), null, null), arrayOf(null, OreBracketHandler.getOre("plateCosmicNeutronium"), OreBracketHandler.getOre("plateInfinity"), ItemBracketHandler.getItem("ForbiddenMagic:EldritchOrb", 0), OreBracketHandler.getOre("plateInfinity"), ItemBracketHandler.getItem("ForbiddenMagic:EldritchOrb", 0), OreBracketHandler.getOre("plateInfinity"), OreBracketHandler.getOre("plateCosmicNeutronium"), null), arrayOf(OreBracketHandler.getOre("plateCosmicNeutronium"), OreBracketHandler.getOre("plateCosmicNeutronium"), ItemBracketHandler.getItem("TaintedMagic:ItemFocusTime", 0), OreBracketHandler.getOre("plateInfinity"), ItemBracketHandler.getItem("Avaritia:Resource", 5), OreBracketHandler.getOre("plateInfinity"), ItemBracketHandler.getItem("TaintedMagic:ItemFocusEldritch", 0), OreBracketHandler.getOre("plateCosmicNeutronium"), OreBracketHandler.getOre("plateCosmicNeutronium")), arrayOf(null, OreBracketHandler.getOre("plateCosmicNeutronium"), OreBracketHandler.getOre("plateCosmicNeutronium"), OreBracketHandler.getOre("plateCosmicNeutronium"), ItemBracketHandler.getItem("TConstruct:heavyPlate", 500), OreBracketHandler.getOre("plateCosmicNeutronium"), OreBracketHandler.getOre("plateCosmicNeutronium"), OreBracketHandler.getOre("plateCosmicNeutronium"), null), arrayOf<IIngredient?>(null, null, null, OreBracketHandler.getOre("plateCosmicNeutronium"), OreBracketHandler.getOre("plateCosmicNeutronium"), OreBracketHandler.getOre("plateCosmicNeutronium"), null, null, null), arrayOfNulls(9), arrayOfNulls(9)))
        val iItemStack2 = ItemBracketHandler.getItem("Avaritia:Infinity_Sword", 0)
        val arrarriIngredient:  Array<Array<IIngredient?>?> = arrayOfNulls(9)
        val arriIngredient = arrayOfNulls<IIngredient>(9)
        arriIngredient[0] = null
        arriIngredient[1] = null
        arriIngredient[2] = null
        arriIngredient[3] = null
        arriIngredient[4] = null
        arriIngredient[5] = null
        arriIngredient[6] = null
        arriIngredient[7] = OreBracketHandler.getOre("plateInfinity")
        val iItemStack3 = ItemBracketHandler.getItem("TGregworks:tGregToolPartLargeSwordBlade", 1511)
        val hashMap2 = HashMap<String, IData>()
        hashMap2["material"] = ExpandString.asData("Neutronium")
        arriIngredient[8] = iItemStack3.withTag(ExpandAnyDict.asData(hashMap2))
        arrarriIngredient[0] = arriIngredient
        arrarriIngredient[1] = arrayOf(null, null, null, null, null, null, OreBracketHandler.getOre("plateInfinity"), ItemBracketHandler.getItem("TaintedMagic:ItemPrimordialEdge", 0), OreBracketHandler.getOre("plateInfinity"))
        arrarriIngredient[2] = arrayOf(null, null, null, null, null, OreBracketHandler.getOre("plateInfinity"), ItemBracketHandler.getItem("IC2:itemNanoSaber", 32767), OreBracketHandler.getOre("plateInfinity"), null)
        arrarriIngredient[3] = arrayOf(null, null, null, null, OreBracketHandler.getOre("plateInfinity"), ItemBracketHandler.getItem("ThaumicTinkerer:ichorSwordGem", 32767), OreBracketHandler.getOre("plateInfinity"), null, null)
        arrarriIngredient[4] = arrayOf(null, ItemBracketHandler.getItem("TaintedMagic:ItemMaterial", 5), null, OreBracketHandler.getOre("plateInfinity"), ItemBracketHandler.getItem("Avaritia:Skull_Sword", 0), OreBracketHandler.getOre("plateInfinity"), null, null, null)
        arrarriIngredient[5] = arrayOf(null, null, ItemBracketHandler.getItem("TaintedMagic:ItemMaterial", 5), ItemBracketHandler.getItem("DraconicEvolution:draconicDistructionStaff", 32767), OreBracketHandler.getOre("plateInfinity"), null, null, null, null)
        arrarriIngredient[6] = arrayOf(null, null, OreBracketHandler.getOre("blockCosmicNeutronium"), ItemBracketHandler.getItem("TaintedMagic:ItemMaterial", 5), null, null, null, null, null)
        arrarriIngredient[7] = arrayOf(null, OreBracketHandler.getOre("blockCosmicNeutronium"), null, null, ItemBracketHandler.getItem("TaintedMagic:ItemMaterial", 5), null, null, null, null)
        arrarriIngredient[8] = arrayOf(ItemBracketHandler.getItem("Avaritia:Resource", 5), null, null, null, null, null, null, null, null)
        ExtremeCrafting.addShaped(iItemStack2, arrarriIngredient)
        val iItemStack4 = ItemBracketHandler.getItem("Avaritia:Infinity_Pickaxe", 0)
        val hashMap3 = HashMap<String, IData>()
        val arriData = arrayOfNulls<IData>(1)
        val hashMap4 = HashMap<String, IData>()
        hashMap4["lvl"] = ExpandShort.asNBT(10.toShort())
        hashMap4["id"] = ExpandShort.asNBT(35.toShort())
        arriData[0] = ExpandAnyDict.asData(hashMap4)
        hashMap3["ench"] = ExpandAnyArray.asData(arriData)
        hashMap3["hammer"] = ExpandByte.asData(0.toByte())
        val iItemStack5 = iItemStack4.withTag(ExpandAnyDict.asData(hashMap3))
        val arrarriIngredient2:  Array<Array<IIngredient?>?> = arrayOfNulls(9)
        arrarriIngredient2[0] = arrayOf(null, OreBracketHandler.getOre("plateInfinity"), OreBracketHandler.getOre("plateInfinity"), OreBracketHandler.getOre("plateInfinity"), OreBracketHandler.getOre("plateInfinity"), OreBracketHandler.getOre("plateInfinity"), OreBracketHandler.getOre("plateInfinity"), OreBracketHandler.getOre("plateInfinity"), null)
        val arriIngredient2 = arrayOfNulls<IIngredient>(9)
        arriIngredient2[0] = OreBracketHandler.getOre("plateInfinity")
        val iItemStack6 = ItemBracketHandler.getItem("TGregworks:tGregToolPartLargePlate", 1511)
        val hashMap5 = HashMap<String, IData>()
        hashMap5["material"] = ExpandString.asData("Neutronium")
        arriIngredient2[1] = iItemStack6.withTag(ExpandAnyDict.asData(hashMap5))
        val iItemStack7 = ItemBracketHandler.getItem("TGregworks:tGregToolPartLargePlate", 1511)
        val hashMap6 = HashMap<String, IData>()
        hashMap6["material"] = ExpandString.asData("Neutronium")
        arriIngredient2[2] = iItemStack7.withTag(ExpandAnyDict.asData(hashMap6))
        arriIngredient2[3] = ItemBracketHandler.getItem("BloodArsenal:blood_infused_pickaxe_diamond", 32767)
        arriIngredient2[4] = ItemBracketHandler.getItem("DraconicEvolution:draconicPickaxe", 0)
        arriIngredient2[5] = ItemBracketHandler.getItem("GraviSuite:advDDrill", 1)
        val iItemStack8 = ItemBracketHandler.getItem("TGregworks:tGregToolPartLargePlate", 1511)
        val hashMap7 = HashMap<String, IData>()
        hashMap7["material"] = ExpandString.asData("Neutronium")
        arriIngredient2[6] = iItemStack8.withTag(ExpandAnyDict.asData(hashMap7))
        val iItemStack9 = ItemBracketHandler.getItem("TGregworks:tGregToolPartLargePlate", 1511)
        val hashMap8 = HashMap<String, IData>()
        hashMap8["material"] = ExpandString.asData("Neutronium")
        arriIngredient2[7] = iItemStack9.withTag(ExpandAnyDict.asData(hashMap8))
        arriIngredient2[8] = OreBracketHandler.getOre("plateInfinity")
        arrarriIngredient2[1] = arriIngredient2
        arrarriIngredient2[2] = arrayOf(OreBracketHandler.getOre("plateInfinity"), OreBracketHandler.getOre("plateInfinity"), null, ItemBracketHandler.getItem("TaintedMagic:ItemFocusEldritch", 0), ItemBracketHandler.getItem("ThaumicTinkerer:ichorPickGem", 32767), ItemBracketHandler.getItem("TaintedMagic:ItemFocusTime", 0), null, OreBracketHandler.getOre("plateInfinity"), OreBracketHandler.getOre("plateInfinity"))
        arrarriIngredient2[3] = arrayOf(null, null, null, null, OreBracketHandler.getOre("blockCosmicNeutronium"), null, null, null, null)
        arrarriIngredient2[4] = arrayOf(null, null, null, null, OreBracketHandler.getOre("blockCosmicNeutronium"), null, null, null, null)
        arrarriIngredient2[5] = arrayOf(null, null, null, null, OreBracketHandler.getOre("blockCosmicNeutronium"), null, null, null, null)
        arrarriIngredient2[6] = arrayOf(null, null, null, null, OreBracketHandler.getOre("blockCosmicNeutronium"), null, null, null, null)
        arrarriIngredient2[7] = arrayOf(null, null, null, null, OreBracketHandler.getOre("blockCosmicNeutronium"), null, null, null, null)
        arrarriIngredient2[8] = arrayOf(null, null, null, ItemBracketHandler.getItem("Avaritia:big_pearl", 0), ItemBracketHandler.getItem("Avaritia:Resource", 5), ItemBracketHandler.getItem("Avaritia:big_pearl", 0), null, null, null)
        ExtremeCrafting.addShaped(iItemStack5, arrarriIngredient2)
        val iItemStack10 = ItemBracketHandler.getItem("Avaritia:Infinity_Shovel", 0)
        val hashMap9 = HashMap<String, IData>()
        hashMap9["destroyer"] = ExpandByte.asData(0.toByte())
        ExtremeCrafting.addShaped(iItemStack10.withTag(ExpandAnyDict.asData(hashMap9)), arrayOf(arrayOf<IIngredient?>(null, null, null, null, null, null, OreBracketHandler.getOre("plateInfinity"), OreBracketHandler.getOre("plateInfinity"), OreBracketHandler.getOre("plateInfinity")), arrayOf(null, null, null, null, null, OreBracketHandler.getOre("plateInfinity"), ItemBracketHandler.getItem("GraviSuite:advDDrill", 1), ItemBracketHandler.getItem("DraconicEvolution:draconicShovel", 0), OreBracketHandler.getOre("plateInfinity")), arrayOf(null, null, null, null, null, null, ItemBracketHandler.getItem("ThaumicTinkerer:ichorShovelGem", 32767), ItemBracketHandler.getItem("BloodArsenal:blood_infused_shovel_diamond", 0), OreBracketHandler.getOre("plateInfinity")), arrayOf<IIngredient?>(null, null, null, null, null, OreBracketHandler.getOre("blockCosmicNeutronium"), null, OreBracketHandler.getOre("plateInfinity"), null), arrayOf<IIngredient?>(null, null, null, null, OreBracketHandler.getOre("blockCosmicNeutronium"), null, null, null, null), arrayOf<IIngredient?>(null, null, null, OreBracketHandler.getOre("blockCosmicNeutronium"), null, null, null, null, null), arrayOf(null, ItemBracketHandler.getItem("TaintedMagic:ItemFocusEldritch", 0), OreBracketHandler.getOre("blockCosmicNeutronium"), null, null, null, null, null, null), arrayOf(ItemBracketHandler.getItem("Avaritia:big_pearl", 0), OreBracketHandler.getOre("blockCosmicNeutronium"), ItemBracketHandler.getItem("TaintedMagic:ItemFocusTime", 0), null, null, null, null, null, null), arrayOf<IIngredient?>(ItemBracketHandler.getItem("Avaritia:Resource", 5), ItemBracketHandler.getItem("Avaritia:big_pearl", 0), null, null, null, null, null, null, null)))
        val iItemStack11 = ItemBracketHandler.getItem("Thaumcraft:WandCasting", 9000)
        val hashMap10 = HashMap<String, IData>()
        hashMap10["cap"] = ExpandString.asData("matrix")
        hashMap10["rod"] = ExpandString.asData("infinity")
        val iItemStack12 = iItemStack11.withTag(ExpandAnyDict.asData(hashMap10))
        val arrarriIngredient3:  Array<Array<IIngredient?>?> = arrayOfNulls(9)
        arrarriIngredient3[0] = arrayOf(null, null, OreBracketHandler.getOre("plateInfinity"), null, null, null, null, null, null)
        arrarriIngredient3[1] = arrayOf(null, OreBracketHandler.getOre("plateInfinity"), ItemBracketHandler.getItem("ThaumicTinkerer:blockTalisman", 0), OreBracketHandler.getOre("plateInfinity"), null, null, null, null, null)
        arrarriIngredient3[2] = arrayOf(OreBracketHandler.getOre("plateInfinity"), ItemBracketHandler.getItem("TaintedMagic:ItemFocusEldritch", 0), ItemBracketHandler.getItem("Avaritia:Resource", 5), OreBracketHandler.getOre("plateCosmicNeutronium"), ItemBracketHandler.getItem("AWWayofTime:dawnScribeTool", 0), null, null, null, null)
        val arriIngredient3 = arrayOfNulls<IIngredient>(9)
        arriIngredient3[0] = null
        arriIngredient3[1] = OreBracketHandler.getOre("plateInfinity")
        arriIngredient3[2] = OreBracketHandler.getOre("plateCosmicNeutronium")
        val iItemStack13 = ItemBracketHandler.getItem("Thaumcraft:WandCasting", 540)
        val hashMap11 = HashMap<String, IData>()
        hashMap11["cap"] = ExpandString.asData("ICHOR")
        hashMap11["rod"] = ExpandString.asData("ICHORCLOTH")
        hashMap11["sceptre"] = ExpandInt.toData(1)
        arriIngredient3[3] = iItemStack13.withTag(ExpandAnyDict.asData(hashMap11))
        arriIngredient3[4] = OreBracketHandler.getOre("plateCosmicNeutronium")
        arriIngredient3[5] = ItemBracketHandler.getItem("AWWayofTime:waterScribeTool", 0)
        arriIngredient3[6] = null
        arriIngredient3[7] = null
        arriIngredient3[8] = null
        arrarriIngredient3[3] = arriIngredient3
        val arriIngredient4 = arrayOfNulls<IIngredient>(9)
        arriIngredient4[0] = null
        arriIngredient4[1] = null
        arriIngredient4[2] = ItemBracketHandler.getItem("AWWayofTime:duskScribeTool", 0)
        arriIngredient4[3] = OreBracketHandler.getOre("plateCosmicNeutronium")
        val iItemStack14 = ItemBracketHandler.getItem("Thaumcraft:WandCasting", 540)
        val hashMap12 = HashMap<String, IData>()
        hashMap12["cap"] = ExpandString.asData("ICHOR")
        hashMap12["rod"] = ExpandString.asData("ICHORCLOTH")
        hashMap12["sceptre"] = ExpandInt.toData(1)
        arriIngredient4[4] = iItemStack14.withTag(ExpandAnyDict.asData(hashMap12))
        arriIngredient4[5] = OreBracketHandler.getOre("plateCosmicNeutronium")
        arriIngredient4[6] = ItemBracketHandler.getItem("AWWayofTime:airScribeTool", 0)
        arriIngredient4[7] = null
        arriIngredient4[8] = null
        arrarriIngredient3[4] = arriIngredient4
        val arriIngredient5 = arrayOfNulls<IIngredient>(9)
        arriIngredient5[0] = null
        arriIngredient5[1] = null
        arriIngredient5[2] = null
        arriIngredient5[3] = ItemBracketHandler.getItem("AWWayofTime:fireScribeTool", 0)
        arriIngredient5[4] = OreBracketHandler.getOre("plateCosmicNeutronium")
        val iItemStack15 = ItemBracketHandler.getItem("Thaumcraft:WandCasting", 540)
        val hashMap13 = HashMap<String, IData>()
        hashMap13["cap"] = ExpandString.asData("ICHOR")
        hashMap13["rod"] = ExpandString.asData("ICHORCLOTH")
        hashMap13["sceptre"] = ExpandInt.toData(1)
        arriIngredient5[5] = iItemStack15.withTag(ExpandAnyDict.asData(hashMap13))
        arriIngredient5[6] = OreBracketHandler.getOre("plateCosmicNeutronium")
        arriIngredient5[7] = OreBracketHandler.getOre("plateInfinity")
        arriIngredient5[8] = null
        arrarriIngredient3[5] = arriIngredient5
        arrarriIngredient3[6] = arrayOf(null, null, null, null, ItemBracketHandler.getItem("AWWayofTime:earthScribeTool", 0), OreBracketHandler.getOre("plateCosmicNeutronium"), ItemBracketHandler.getItem("Avaritia:Resource", 5), ItemBracketHandler.getItem("TaintedMagic:ItemFocusTime", 0), OreBracketHandler.getOre("plateInfinity"))
        arrarriIngredient3[7] = arrayOf(null, null, null, null, null, OreBracketHandler.getOre("plateInfinity"), ItemBracketHandler.getItem("ThaumicTinkerer:blockTalisman", 0), OreBracketHandler.getOre("plateInfinity"), null)
        arrarriIngredient3[8] = arrayOf(null, null, null, null, null, null, OreBracketHandler.getOre("plateInfinity"), null, null)
        ExtremeCrafting.addShaped(iItemStack12, arrarriIngredient3)
        ExtremeCrafting.addShaped(ItemBracketHandler.getItem("Avaritia:Infinity_Axe", 0), arrayOf(arrayOf<IIngredient?>(null, OreBracketHandler.getOre("plateInfinity"), null, null, null, null, null, null, null), arrayOf(OreBracketHandler.getOre("plateInfinity"), ItemBracketHandler.getItem("GraviSuite:advChainsaw", 1), OreBracketHandler.getOre("plateInfinity"), OreBracketHandler.getOre("plateInfinity"), OreBracketHandler.getOre("plateInfinity"), null, null, null, null), arrayOf(OreBracketHandler.getOre("plateInfinity"), ItemBracketHandler.getItem("ThaumicTinkerer:ichorAxeGem", 32767), ItemBracketHandler.getItem("DraconicEvolution:draconicAxe", 0), OreBracketHandler.getOre("plateInfinity"), null, null, null, null, null), arrayOf<IIngredient?>(null, OreBracketHandler.getOre("plateInfinity"), OreBracketHandler.getOre("blockCosmicNeutronium"), null, null, null, null, null, null), arrayOf<IIngredient?>(null, null, OreBracketHandler.getOre("blockCosmicNeutronium"), null, null, null, null, null, null), arrayOf<IIngredient?>(null, null, OreBracketHandler.getOre("blockCosmicNeutronium"), null, null, null, null, null, null), arrayOf<IIngredient?>(null, null, OreBracketHandler.getOre("blockCosmicNeutronium"), null, null, null, null, null, null), arrayOf<IIngredient?>(null, null, OreBracketHandler.getOre("blockCosmicNeutronium"), null, null, null, null, null, null), arrayOf<IIngredient?>(null, ItemBracketHandler.getItem("TaintedMagic:ItemFocusEldritch", 0), ItemBracketHandler.getItem("Avaritia:Resource", 5), ItemBracketHandler.getItem("TaintedMagic:ItemFocusTime", 0), null, null, null, null, null)))
        ExtremeCrafting.addShaped(ItemBracketHandler.getItem("Avaritia:Infinity_Bow", 0), arrayOf(arrayOf(null, null, null, OreBracketHandler.getOre("plateInfinity"), OreBracketHandler.getOre("plateInfinity"), ItemBracketHandler.getItem("TaintedMagic:ItemFocusMeteorology", 0), null, null, null), arrayOf(null, null, OreBracketHandler.getOre("plateInfinity"), null, ItemBracketHandler.getItem("ThaumicTinkerer:kamiResource", 1), null, null, null, null), arrayOf(null, OreBracketHandler.getOre("plateInfinity"), null, null, ItemBracketHandler.getItem("ThaumicTinkerer:kamiResource", 1), null, null, null, null), arrayOf(OreBracketHandler.getOre("plateInfinity"), null, null, null, ItemBracketHandler.getItem("ThaumicTinkerer:kamiResource", 1), null, null, null, null), arrayOf<IIngredient?>(ItemBracketHandler.getItem("Avaritia:Resource", 5), null, null, null, ItemBracketHandler.getItem("DraconicEvolution:draconicBow", 0), ItemBracketHandler.getItem("TaintedMagic:ItemFocusTime", 0), null, null, null), arrayOf(OreBracketHandler.getOre("plateInfinity"), null, null, null, ItemBracketHandler.getItem("ThaumicTinkerer:kamiResource", 1), null, null, null, null), arrayOf(null, OreBracketHandler.getOre("plateInfinity"), null, null, ItemBracketHandler.getItem("ThaumicTinkerer:kamiResource", 1), null, null, null, null), arrayOf(null, null, OreBracketHandler.getOre("plateInfinity"), null, ItemBracketHandler.getItem("ThaumicTinkerer:kamiResource", 1), null, null, null, null), arrayOf(null, null, null, OreBracketHandler.getOre("plateInfinity"), OreBracketHandler.getOre("plateInfinity"), ItemBracketHandler.getItem("TaintedMagic:ItemFocusMeteorology", 0), null, null, null)))
        Infusion.addRecipe("AKASHIC", ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 17397), arrayOf(ItemBracketHandler.getItem("TaintedMagic:ItemFocusTime", 0), ItemBracketHandler.getItem("thaumicbases:knoseFragment", 6), ItemBracketHandler.getItem("thaumicbases:knoseFragment", 6), ItemBracketHandler.getItem("thaumicbases:knoseFragment", 6), ItemBracketHandler.getItem("thaumicbases:knoseFragment", 6), ItemBracketHandler.getItem("Avaritia:big_pearl", 0), ItemBracketHandler.getItem("gadomancy:BlockKnowledgeBook", 0), ItemBracketHandler.getItem("Thaumcraft:ItemThaumonomicon", 0), ItemBracketHandler.getItem("TaintedMagic:ItemFocusMeteorology", 0), ItemBracketHandler.getItem("Thaumcraft:ItemEldritchObject", 1), ItemBracketHandler.getItem("gadomancy:BlockKnowledgeBook", 0), ItemBracketHandler.getItem("Avaritia:big_pearl", 0), ItemBracketHandler.getItem("thaumicbases:knoseFragment", 6), ItemBracketHandler.getItem("thaumicbases:knoseFragment", 6), ItemBracketHandler.getItem("thaumicbases:knoseFragment", 6), ItemBracketHandler.getItem("thaumicbases:knoseFragment", 6)), "praecantatio 512, cognitio 128, sensus 96, luxuria 96, tempus 64, terminus 128", ItemBracketHandler.getItem("Avaritia:Akashic_Record", 0), 24)
        Research.refreshResearchRecipe("AKASHIC")
        val iItemStack16 = ItemBracketHandler.getItem("Avaritia:Infinity_Helm", 0)
        val arrarriIngredient4:  Array<Array<IIngredient?>?> = arrayOfNulls(9)
        arrarriIngredient4[0] = arrayOf(null, null, OreBracketHandler.getOre("plateCosmicNeutronium"), OreBracketHandler.getOre("plateCosmicNeutronium"), OreBracketHandler.getOre("plateCosmicNeutronium"), OreBracketHandler.getOre("plateCosmicNeutronium"), OreBracketHandler.getOre("plateCosmicNeutronium"), null, null)
        arrarriIngredient4[1] = arrayOf(null, OreBracketHandler.getOre("plateCosmicNeutronium"), OreBracketHandler.getOre("plateInfinity"), OreBracketHandler.getOre("plateInfinity"), ItemBracketHandler.getItem("AdvancedSolarPanel:ultimate_solar_helmet", 32767), OreBracketHandler.getOre("plateInfinity"), OreBracketHandler.getOre("plateInfinity"), OreBracketHandler.getOre("plateCosmicNeutronium"), null)
        arrarriIngredient4[2] = arrayOf(null, OreBracketHandler.getOre("plateCosmicNeutronium"), null, ItemBracketHandler.getItem("Avaritia:Resource", 5), ItemBracketHandler.getItem("ThaumicTinkerer:ichorclothHelmGem", 32767), ItemBracketHandler.getItem("Avaritia:Resource", 5), null, OreBracketHandler.getOre("plateCosmicNeutronium"), null)
        val arriIngredient6 = arrayOfNulls<IIngredient>(9)
        arriIngredient6[0] = null
        arriIngredient6[1] = OreBracketHandler.getOre("plateCosmicNeutronium")
        arriIngredient6[2] = OreBracketHandler.getOre("plateInfinity")
        val iItemStack17 = ItemBracketHandler.getItem("BloodArsenal:life_imbued_helmet", 0)
        val hashMap14 = HashMap<String, IData>()
        hashMap14["LPStored"] = ExpandInt.toData(0)
        arriIngredient6[3] = iItemStack17.withTag(ExpandAnyDict.asData(hashMap14))
        arriIngredient6[4] = ItemBracketHandler.getItem("DraconicEvolution:draconicHelm", 0)
        arriIngredient6[5] = ItemBracketHandler.getItem("AWWayofTime:sanguineHelmet", 0)
        arriIngredient6[6] = OreBracketHandler.getOre("plateInfinity")
        arriIngredient6[7] = OreBracketHandler.getOre("plateCosmicNeutronium")
        arriIngredient6[8] = null
        arrarriIngredient4[3] = arriIngredient6
        arrarriIngredient4[4] = arrayOf(null, OreBracketHandler.getOre("plateCosmicNeutronium"), OreBracketHandler.getOre("plateInfinity"), OreBracketHandler.getOre("plateInfinity"), ItemBracketHandler.getItem("GalaxySpace:item.spacesuit_helmetglasses", 0), OreBracketHandler.getOre("plateInfinity"), OreBracketHandler.getOre("plateInfinity"), OreBracketHandler.getOre("plateCosmicNeutronium"), null)
        arrarriIngredient4[5] = arrayOf(null, OreBracketHandler.getOre("plateCosmicNeutronium"), OreBracketHandler.getOre("plateInfinity"), ItemBracketHandler.getItem("TaintedMagic:ItemFocusTime", 0), ItemBracketHandler.getItem("BloodArsenal:sigil_of_divinity", 0), ItemBracketHandler.getItem("EMT:ShieldFocus", 0), OreBracketHandler.getOre("plateInfinity"), OreBracketHandler.getOre("plateCosmicNeutronium"), null)
        arrarriIngredient4[6] = arrayOfNulls(9)
        arrarriIngredient4[7] = arrayOfNulls(9)
        arrarriIngredient4[8] = arrayOfNulls(9)
        ExtremeCrafting.addShaped(iItemStack16, arrarriIngredient4)
        val iItemStack18 = ItemBracketHandler.getItem("Avaritia:Infinity_Chest", 0)
        val arrarriIngredient5:  Array<Array<IIngredient?>?> = arrayOfNulls(9)
        arrarriIngredient5[0] = arrayOf(null, OreBracketHandler.getOre("plateCosmicNeutronium"), OreBracketHandler.getOre("plateCosmicNeutronium"), null, null, null, OreBracketHandler.getOre("plateCosmicNeutronium"), OreBracketHandler.getOre("plateCosmicNeutronium"), null)
        arrarriIngredient5[1] = arrayOf(OreBracketHandler.getOre("plateCosmicNeutronium"), OreBracketHandler.getOre("plateInfinity"), OreBracketHandler.getOre("plateCosmicNeutronium"), null, null, null, OreBracketHandler.getOre("plateCosmicNeutronium"), OreBracketHandler.getOre("plateInfinity"), OreBracketHandler.getOre("plateCosmicNeutronium"))
        arrarriIngredient5[2] = arrayOf(OreBracketHandler.getOre("plateCosmicNeutronium"), OreBracketHandler.getOre("plateInfinity"), OreBracketHandler.getOre("plateInfinity"), OreBracketHandler.getOre("plateCosmicNeutronium"), null, OreBracketHandler.getOre("plateCosmicNeutronium"), OreBracketHandler.getOre("plateInfinity"), OreBracketHandler.getOre("plateInfinity"), OreBracketHandler.getOre("plateCosmicNeutronium"))
        arrarriIngredient5[3] = arrayOf(null, OreBracketHandler.getOre("plateCosmicNeutronium"), OreBracketHandler.getOre("plateInfinity"), OreBracketHandler.getOre("plateInfinity"), ItemBracketHandler.getItem("GraviSuite:graviChestPlate", 32767), OreBracketHandler.getOre("plateInfinity"), OreBracketHandler.getOre("plateInfinity"), OreBracketHandler.getOre("plateCosmicNeutronium"), null)
        val arriIngredient7 = arrayOfNulls<IIngredient>(9)
        arriIngredient7[0] = null
        arriIngredient7[1] = OreBracketHandler.getOre("plateCosmicNeutronium")
        arriIngredient7[2] = OreBracketHandler.getOre("plateInfinity")
        val iItemStack19 = ItemBracketHandler.getItem("BloodArsenal:life_imbued_chestplate", 0)
        val hashMap15 = HashMap<String, IData>()
        hashMap15["LPStored"] = ExpandInt.toData(0)
        arriIngredient7[3] = iItemStack19.withTag(ExpandAnyDict.asData(hashMap15))
        arriIngredient7[4] = ItemBracketHandler.getItem("ThaumicTinkerer:ichorclothChestGem", 32767)
        arriIngredient7[5] = ItemBracketHandler.getItem("AWWayofTime:sanguineRobe", 0)
        arriIngredient7[6] = OreBracketHandler.getOre("plateInfinity")
        arriIngredient7[7] = OreBracketHandler.getOre("plateCosmicNeutronium")
        arriIngredient7[8] = null
        arrarriIngredient5[4] = arriIngredient7
        arrarriIngredient5[5] = arrayOf(null, OreBracketHandler.getOre("plateCosmicNeutronium"), OreBracketHandler.getOre("plateInfinity"), ItemBracketHandler.getItem("GalaxySpace:item.spacesuit_jetplate", 0), ItemBracketHandler.getItem("Avaritia:Resource", 5), ItemBracketHandler.getItem("DraconicEvolution:draconicChest", 0), OreBracketHandler.getOre("plateInfinity"), OreBracketHandler.getOre("plateCosmicNeutronium"), null)
        arrarriIngredient5[6] = arrayOf(null, OreBracketHandler.getOre("plateCosmicNeutronium"), OreBracketHandler.getOre("plateInfinity"), ItemBracketHandler.getItem("EMT:ShieldFocus", 0), ItemBracketHandler.getItem("BloodArsenal:sigil_of_divinity", 0), ItemBracketHandler.getItem("TaintedMagic:ItemFocusTime", 0), OreBracketHandler.getOre("plateInfinity"), OreBracketHandler.getOre("plateCosmicNeutronium"), null)
        arrarriIngredient5[7] = arrayOf(null, OreBracketHandler.getOre("plateCosmicNeutronium"), OreBracketHandler.getOre("plateInfinity"), OreBracketHandler.getOre("plateInfinity"), OreBracketHandler.getOre("plateInfinity"), OreBracketHandler.getOre("plateInfinity"), OreBracketHandler.getOre("plateInfinity"), OreBracketHandler.getOre("plateCosmicNeutronium"), null)
        arrarriIngredient5[8] = arrayOf(null, null, OreBracketHandler.getOre("plateCosmicNeutronium"), OreBracketHandler.getOre("plateCosmicNeutronium"), OreBracketHandler.getOre("plateCosmicNeutronium"), OreBracketHandler.getOre("plateCosmicNeutronium"), OreBracketHandler.getOre("plateCosmicNeutronium"), null, null)
        ExtremeCrafting.addShaped(iItemStack18, arrarriIngredient5)
        val iItemStack20 = ItemBracketHandler.getItem("Avaritia:Infinity_Pants", 0)
        val arrarriIngredient6:  Array<Array<IIngredient?>?> = arrayOfNulls(9)
        arrarriIngredient6[0] = arrayOf(OreBracketHandler.getOre("plateCosmicNeutronium"), OreBracketHandler.getOre("plateCosmicNeutronium"), OreBracketHandler.getOre("plateCosmicNeutronium"), OreBracketHandler.getOre("plateCosmicNeutronium"), OreBracketHandler.getOre("plateCosmicNeutronium"), OreBracketHandler.getOre("plateCosmicNeutronium"), OreBracketHandler.getOre("plateCosmicNeutronium"), OreBracketHandler.getOre("plateCosmicNeutronium"), OreBracketHandler.getOre("plateCosmicNeutronium"))
        val arriIngredient8 = arrayOfNulls<IIngredient>(9)
        arriIngredient8[0] = OreBracketHandler.getOre("plateCosmicNeutronium")
        arriIngredient8[1] = ItemBracketHandler.getItem("TaintedMagic:ItemFocusTime", 0)
        arriIngredient8[2] = ItemBracketHandler.getItem("GalaxySpace:item.spacesuit_leg", 0)
        val iItemStack21 = ItemBracketHandler.getItem("BloodArsenal:life_imbued_leggings", 0)
        val hashMap16 = HashMap<String, IData>()
        hashMap16["LPStored"] = ExpandInt.toData(0)
        arriIngredient8[3] = iItemStack21.withTag(ExpandAnyDict.asData(hashMap16))
        arriIngredient8[4] = ItemBracketHandler.getItem("BloodArsenal:sigil_of_divinity", 0)
        arriIngredient8[5] = ItemBracketHandler.getItem("ThaumicTinkerer:ichorclothLegsGem", 32767)
        arriIngredient8[6] = ItemBracketHandler.getItem("IC2:itemArmorQuantumLegs", 32767)
        arriIngredient8[7] = ItemBracketHandler.getItem("EMT:ShieldFocus", 0)
        arriIngredient8[8] = OreBracketHandler.getOre("plateCosmicNeutronium")
        arrarriIngredient6[1] = arriIngredient8
        arrarriIngredient6[2] = arrayOf(OreBracketHandler.getOre("plateCosmicNeutronium"), OreBracketHandler.getOre("plateInfinity"), OreBracketHandler.getOre("plateInfinity"), OreBracketHandler.getOre("plateInfinity"), ItemBracketHandler.getItem("DraconicEvolution:draconicLeggs", 0), OreBracketHandler.getOre("plateInfinity"), OreBracketHandler.getOre("plateInfinity"), OreBracketHandler.getOre("plateInfinity"), OreBracketHandler.getOre("plateCosmicNeutronium"))
        arrarriIngredient6[3] = arrayOf(OreBracketHandler.getOre("plateCosmicNeutronium"), OreBracketHandler.getOre("plateInfinity"), OreBracketHandler.getOre("plateCosmicNeutronium"), OreBracketHandler.getOre("plateCosmicNeutronium"), ItemBracketHandler.getItem("Avaritia:Resource", 5), OreBracketHandler.getOre("plateCosmicNeutronium"), OreBracketHandler.getOre("plateCosmicNeutronium"), OreBracketHandler.getOre("plateInfinity"), OreBracketHandler.getOre("plateCosmicNeutronium"))
        arrarriIngredient6[4] = arrayOf(OreBracketHandler.getOre("plateCosmicNeutronium"), OreBracketHandler.getOre("plateInfinity"), OreBracketHandler.getOre("plateCosmicNeutronium"), null, null, null, OreBracketHandler.getOre("plateCosmicNeutronium"), OreBracketHandler.getOre("plateInfinity"), OreBracketHandler.getOre("plateCosmicNeutronium"))
        arrarriIngredient6[5] = arrayOf(OreBracketHandler.getOre("plateCosmicNeutronium"), ItemBracketHandler.getItem("Avaritia:big_pearl", 0), OreBracketHandler.getOre("plateCosmicNeutronium"), null, null, null, OreBracketHandler.getOre("plateCosmicNeutronium"), ItemBracketHandler.getItem("Avaritia:big_pearl", 0), OreBracketHandler.getOre("plateCosmicNeutronium"))
        arrarriIngredient6[6] = arrayOf(OreBracketHandler.getOre("plateCosmicNeutronium"), OreBracketHandler.getOre("plateInfinity"), OreBracketHandler.getOre("plateCosmicNeutronium"), null, null, null, OreBracketHandler.getOre("plateCosmicNeutronium"), OreBracketHandler.getOre("plateInfinity"), OreBracketHandler.getOre("plateCosmicNeutronium"))
        arrarriIngredient6[7] = arrayOf(OreBracketHandler.getOre("plateCosmicNeutronium"), OreBracketHandler.getOre("plateInfinity"), OreBracketHandler.getOre("plateCosmicNeutronium"), null, null, null, OreBracketHandler.getOre("plateCosmicNeutronium"), OreBracketHandler.getOre("plateInfinity"), OreBracketHandler.getOre("plateCosmicNeutronium"))
        arrarriIngredient6[8] = arrayOf(OreBracketHandler.getOre("plateCosmicNeutronium"), OreBracketHandler.getOre("plateCosmicNeutronium"), OreBracketHandler.getOre("plateCosmicNeutronium"), null, null, null, OreBracketHandler.getOre("plateCosmicNeutronium"), OreBracketHandler.getOre("plateCosmicNeutronium"), OreBracketHandler.getOre("plateCosmicNeutronium"))
        ExtremeCrafting.addShaped(iItemStack20, arrarriIngredient6)
        val iItemStack22 = ItemBracketHandler.getItem("Avaritia:Infinity_Shoes", 0)
        val arrarriIngredient7:  Array<Array<IIngredient?>?> = arrayOfNulls(9)
        arrarriIngredient7[0] = arrayOfNulls(9)
        arrarriIngredient7[1] = arrayOfNulls(9)
        arrarriIngredient7[2] = arrayOf(null, OreBracketHandler.getOre("plateCosmicNeutronium"), OreBracketHandler.getOre("plateCosmicNeutronium"), OreBracketHandler.getOre("plateCosmicNeutronium"), null, OreBracketHandler.getOre("plateCosmicNeutronium"), OreBracketHandler.getOre("plateCosmicNeutronium"), OreBracketHandler.getOre("plateCosmicNeutronium"), null)
        arrarriIngredient7[3] = arrayOf(null, OreBracketHandler.getOre("plateCosmicNeutronium"), OreBracketHandler.getOre("plateInfinity"), OreBracketHandler.getOre("plateCosmicNeutronium"), null, OreBracketHandler.getOre("plateCosmicNeutronium"), OreBracketHandler.getOre("plateInfinity"), OreBracketHandler.getOre("plateCosmicNeutronium"), null)
        arrarriIngredient7[4] = arrayOf(null, OreBracketHandler.getOre("plateCosmicNeutronium"), OreBracketHandler.getOre("plateInfinity"), OreBracketHandler.getOre("plateCosmicNeutronium"), null, OreBracketHandler.getOre("plateCosmicNeutronium"), OreBracketHandler.getOre("plateInfinity"), OreBracketHandler.getOre("plateCosmicNeutronium"), null)
        arrarriIngredient7[5] = arrayOf(OreBracketHandler.getOre("plateCosmicNeutronium"), OreBracketHandler.getOre("plateCosmicNeutronium"), OreBracketHandler.getOre("plateInfinity"), OreBracketHandler.getOre("plateCosmicNeutronium"), null, OreBracketHandler.getOre("plateCosmicNeutronium"), OreBracketHandler.getOre("plateInfinity"), OreBracketHandler.getOre("plateCosmicNeutronium"), OreBracketHandler.getOre("plateCosmicNeutronium"))
        val arriIngredient9 = arrayOfNulls<IIngredient>(9)
        arriIngredient9[0] = OreBracketHandler.getOre("plateCosmicNeutronium")
        arriIngredient9[1] = ItemBracketHandler.getItem("ThaumicTinkerer:ichorclothBootsGem", 32767)
        arriIngredient9[2] = ItemBracketHandler.getItem("DraconicEvolution:draconicBoots", 0)
        arriIngredient9[3] = OreBracketHandler.getOre("plateCosmicNeutronium")
        arriIngredient9[4] = null
        arriIngredient9[5] = OreBracketHandler.getOre("plateCosmicNeutronium")
        arriIngredient9[6] = ItemBracketHandler.getItem("IC2:itemArmorQuantumBoots", 32767)
        val iItemStack23 = ItemBracketHandler.getItem("BloodArsenal:life_imbued_boots", 0)
        val hashMap17 = HashMap<String, IData>()
        hashMap17["LPStored"] = ExpandInt.toData(0)
        arriIngredient9[7] = iItemStack23.withTag(ExpandAnyDict.asData(hashMap17))
        arriIngredient9[8] = OreBracketHandler.getOre("plateCosmicNeutronium")
        arrarriIngredient7[6] = arriIngredient9
        arrarriIngredient7[7] = arrayOf(OreBracketHandler.getOre("plateCosmicNeutronium"), ItemBracketHandler.getItem("TaintedMagic:ItemFocusTime", 0), ItemBracketHandler.getItem("AWWayofTime:sanguineBoots", 0), OreBracketHandler.getOre("plateCosmicNeutronium"), null, OreBracketHandler.getOre("plateCosmicNeutronium"), ItemBracketHandler.getItem("GalaxySpace:item.spacesuit_gravityboots", 0), ItemBracketHandler.getItem("EMT:ShieldFocus", 0), OreBracketHandler.getOre("plateCosmicNeutronium"))
        arrarriIngredient7[8] = arrayOf(OreBracketHandler.getOre("plateInfinity"), OreBracketHandler.getOre("plateInfinity"), OreBracketHandler.getOre("plateInfinity"), OreBracketHandler.getOre("plateInfinity"), ItemBracketHandler.getItem("BloodArsenal:sigil_of_divinity", 0), OreBracketHandler.getOre("plateInfinity"), OreBracketHandler.getOre("plateInfinity"), OreBracketHandler.getOre("plateInfinity"), OreBracketHandler.getOre("plateInfinity"))
        ExtremeCrafting.addShaped(iItemStack22, arrarriIngredient7)
        ExtremeCrafting.addShaped(ItemBracketHandler.getItem("Avaritia:Neutron_Collector", 0), arrayOf(arrayOf(OreBracketHandler.getOre("blockBlackPlutonium"), ItemBracketHandler.getItem("Avaritia:Resource_Block", 0), ItemBracketHandler.getItem("TConstruct:heavyPlate", 315), ItemBracketHandler.getItem("TConstruct:heavyPlate", 500), ItemBracketHandler.getItem("Avaritia:Crystal_Matrix", 0), ItemBracketHandler.getItem("TConstruct:heavyPlate", 500), ItemBracketHandler.getItem("TConstruct:heavyPlate", 315), ItemBracketHandler.getItem("Avaritia:Resource_Block", 0), OreBracketHandler.getOre("blockBlackPlutonium")), arrayOf<IIngredient?>(ItemBracketHandler.getItem("Avaritia:Resource_Block", 0), null, null, null, ItemBracketHandler.getItem("TConstruct:heavyPlate", 315), null, null, null, ItemBracketHandler.getItem("Avaritia:Resource_Block", 0)), arrayOf(ItemBracketHandler.getItem("TConstruct:heavyPlate", 315), null, ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32697), null, OreBracketHandler.getOre("circuitInfinite"), null, ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32697), null, ItemBracketHandler.getItem("TConstruct:heavyPlate", 315)), arrayOf(ItemBracketHandler.getItem("TConstruct:heavyPlate", 500), null, ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32687), null, OreBracketHandler.getOre("circuitInfinite"), null, ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32687), null, ItemBracketHandler.getItem("TConstruct:heavyPlate", 500)), arrayOf(ItemBracketHandler.getItem("Avaritia:Crystal_Matrix", 0), OreBracketHandler.getOre("plateInfinity"), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32608), OreBracketHandler.getOre("plateInfinity"), ItemBracketHandler.getItem("Avaritia:Resource", 5), OreBracketHandler.getOre("plateInfinity"), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32608), OreBracketHandler.getOre("plateInfinity"), ItemBracketHandler.getItem("Avaritia:Crystal_Matrix", 0)), arrayOf(ItemBracketHandler.getItem("TConstruct:heavyPlate", 500), null, ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32687), null, OreBracketHandler.getOre("circuitInfinite"), null, ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32687), null, ItemBracketHandler.getItem("TConstruct:heavyPlate", 500)), arrayOf(ItemBracketHandler.getItem("TConstruct:heavyPlate", 315), null, ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32697), null, OreBracketHandler.getOre("circuitInfinite"), null, ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32697), null, ItemBracketHandler.getItem("TConstruct:heavyPlate", 315)), arrayOf<IIngredient?>(ItemBracketHandler.getItem("Avaritia:Resource_Block", 0), null, null, null, ItemBracketHandler.getItem("TConstruct:heavyPlate", 315), null, null, null, ItemBracketHandler.getItem("Avaritia:Resource_Block", 0)), arrayOf(OreBracketHandler.getOre("blockBlackPlutonium"), ItemBracketHandler.getItem("Avaritia:Resource_Block", 0), ItemBracketHandler.getItem("TConstruct:heavyPlate", 315), ItemBracketHandler.getItem("TConstruct:heavyPlate", 500), ItemBracketHandler.getItem("Avaritia:Crystal_Matrix", 0), ItemBracketHandler.getItem("TConstruct:heavyPlate", 500), ItemBracketHandler.getItem("TConstruct:heavyPlate", 315), ItemBracketHandler.getItem("Avaritia:Resource_Block", 0), OreBracketHandler.getOre("blockBlackPlutonium"))))
        val iItemStack24 = ItemBracketHandler.getItem("Avaritia:Neutronium_Compressor", 0)
        val arrarriIngredient8:  Array<Array<IIngredient?>?> = arrayOfNulls(9)
        arrarriIngredient8[0] = arrayOf(ItemBracketHandler.getItem("Avaritia:Resource_Block", 0), ItemBracketHandler.getItem("TConstruct:heavyPlate", 500), ItemBracketHandler.getItem("Avaritia:Resource_Block", 0), ItemBracketHandler.getItem("Avaritia:Resource", 1), ItemBracketHandler.getItem("TConstruct:heavyPlate", 315), ItemBracketHandler.getItem("Avaritia:Resource", 1), ItemBracketHandler.getItem("Avaritia:Resource_Block", 0), ItemBracketHandler.getItem("TConstruct:heavyPlate", 500), ItemBracketHandler.getItem("Avaritia:Resource_Block", 0))
        val arriIngredient10 = arrayOfNulls<IIngredient>(9)
        arriIngredient10[0] = ItemBracketHandler.getItem("Avaritia:Resource", 1)
        arriIngredient10[1] = null
        arriIngredient10[2] = ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32647)
        arriIngredient10[3] = null
        val iItemStack25 = ItemBracketHandler.getItem("TGregworks:tGregToolPartLargePlate", 1657)
        val hashMap18 = HashMap<String, IData>()
        hashMap18["material"] = ExpandString.asData("BlackPlutonium")
        arriIngredient10[4] = iItemStack25.withTag(ExpandAnyDict.asData(hashMap18))
        arriIngredient10[5] = null
        arriIngredient10[6] = ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32647)
        arriIngredient10[7] = null
        arriIngredient10[8] = ItemBracketHandler.getItem("Avaritia:Resource", 1)
        arrarriIngredient8[1] = arriIngredient10
        val arriIngredient11 = arrayOfNulls<IIngredient>(9)
        arriIngredient11[0] = ItemBracketHandler.getItem("TConstruct:heavyPlate", 315)
        arriIngredient11[1] = ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32637)
        arriIngredient11[2] = ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32608)
        arriIngredient11[3] = ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32637)
        val iItemStack26 = ItemBracketHandler.getItem("TGregworks:tGregToolPartLargePlate", 1657)
        val hashMap19 = HashMap<String, IData>()
        hashMap19["material"] = ExpandString.asData("BlackPlutonium")
        arriIngredient11[4] = iItemStack26.withTag(ExpandAnyDict.asData(hashMap19))
        arriIngredient11[5] = ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32637)
        arriIngredient11[6] = ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32608)
        arriIngredient11[7] = ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32637)
        arriIngredient11[8] = ItemBracketHandler.getItem("TConstruct:heavyPlate", 315)
        arrarriIngredient8[2] = arriIngredient11
        arrarriIngredient8[3] = arrayOf(ItemBracketHandler.getItem("TConstruct:heavyPlate", 500), null, ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32647), OreBracketHandler.getOre("circuitInfinite"), OreBracketHandler.getOre("plateNeutronium"), OreBracketHandler.getOre("circuitInfinite"), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32647), null, ItemBracketHandler.getItem("TConstruct:heavyPlate", 500))
        val arriIngredient12 = arrayOfNulls<IIngredient>(9)
        arriIngredient12[0] = ItemBracketHandler.getItem("TConstruct:heavyPlate", 500)
        val iItemStack27 = ItemBracketHandler.getItem("TGregworks:tGregToolPartLargePlate", 1657)
        val hashMap20 = HashMap<String, IData>()
        hashMap20["material"] = ExpandString.asData("BlackPlutonium")
        arriIngredient12[1] = iItemStack27.withTag(ExpandAnyDict.asData(hashMap20))
        val iItemStack28 = ItemBracketHandler.getItem("TGregworks:tGregToolPartLargePlate", 1657)
        val hashMap21 = HashMap<String, IData>()
        hashMap21["material"] = ExpandString.asData("BlackPlutonium")
        arriIngredient12[2] = iItemStack28.withTag(ExpandAnyDict.asData(hashMap21))
        arriIngredient12[3] = OreBracketHandler.getOre("plateNeutronium")
        arriIngredient12[4] = ItemBracketHandler.getItem("gregtech:gt.blockmachines", 10812)
        arriIngredient12[5] = OreBracketHandler.getOre("plateNeutronium")
        val iItemStack29 = ItemBracketHandler.getItem("TGregworks:tGregToolPartLargePlate", 1657)
        val hashMap22 = HashMap<String, IData>()
        hashMap22["material"] = ExpandString.asData("BlackPlutonium")
        arriIngredient12[6] = iItemStack29.withTag(ExpandAnyDict.asData(hashMap22))
        val iItemStack30 = ItemBracketHandler.getItem("TGregworks:tGregToolPartLargePlate", 1657)
        val hashMap23 = HashMap<String, IData>()
        hashMap23["material"] = ExpandString.asData("BlackPlutonium")
        arriIngredient12[7] = iItemStack30.withTag(ExpandAnyDict.asData(hashMap23))
        arriIngredient12[8] = ItemBracketHandler.getItem("TConstruct:heavyPlate", 500)
        arrarriIngredient8[4] = arriIngredient12
        arrarriIngredient8[5] = arrayOf(ItemBracketHandler.getItem("TConstruct:heavyPlate", 500), null, ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32647), OreBracketHandler.getOre("circuitInfinite"), OreBracketHandler.getOre("plateNeutronium"), OreBracketHandler.getOre("circuitInfinite"), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32647), null, ItemBracketHandler.getItem("TConstruct:heavyPlate", 500))
        val arriIngredient13 = arrayOfNulls<IIngredient>(9)
        arriIngredient13[0] = ItemBracketHandler.getItem("TConstruct:heavyPlate", 315)
        arriIngredient13[1] = ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32637)
        arriIngredient13[2] = ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32608)
        arriIngredient13[3] = ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32637)
        val iItemStack31 = ItemBracketHandler.getItem("TGregworks:tGregToolPartLargePlate", 1657)
        val hashMap24 = HashMap<String, IData>()
        hashMap24["material"] = ExpandString.asData("BlackPlutonium")
        arriIngredient13[4] = iItemStack31.withTag(ExpandAnyDict.asData(hashMap24))
        arriIngredient13[5] = ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32637)
        arriIngredient13[6] = ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32608)
        arriIngredient13[7] = ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32637)
        arriIngredient13[8] = ItemBracketHandler.getItem("TConstruct:heavyPlate", 315)
        arrarriIngredient8[6] = arriIngredient13
        val arriIngredient14 = arrayOfNulls<IIngredient>(9)
        arriIngredient14[0] = ItemBracketHandler.getItem("Avaritia:Resource", 1)
        arriIngredient14[1] = null
        arriIngredient14[2] = ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32647)
        arriIngredient14[3] = null
        val iItemStack32 = ItemBracketHandler.getItem("TGregworks:tGregToolPartLargePlate", 1657)
        val hashMap25 = HashMap<String, IData>()
        hashMap25["material"] = ExpandString.asData("BlackPlutonium")
        arriIngredient14[4] = iItemStack32.withTag(ExpandAnyDict.asData(hashMap25))
        arriIngredient14[5] = null
        arriIngredient14[6] = ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32647)
        arriIngredient14[7] = null
        arriIngredient14[8] = ItemBracketHandler.getItem("Avaritia:Resource", 1)
        arrarriIngredient8[7] = arriIngredient14
        arrarriIngredient8[8] = arrayOf(ItemBracketHandler.getItem("Avaritia:Resource_Block", 0), ItemBracketHandler.getItem("TConstruct:heavyPlate", 500), ItemBracketHandler.getItem("Avaritia:Resource_Block", 0), ItemBracketHandler.getItem("Avaritia:Resource", 1), ItemBracketHandler.getItem("TConstruct:heavyPlate", 315), ItemBracketHandler.getItem("Avaritia:Resource", 1), ItemBracketHandler.getItem("Avaritia:Resource_Block", 0), ItemBracketHandler.getItem("TConstruct:heavyPlate", 500), ItemBracketHandler.getItem("Avaritia:Resource_Block", 0))
        ExtremeCrafting.addShaped(iItemStack24, arrarriIngredient8)
        AlloySmelter.addRecipe(ItemBracketHandler.getItem("Avaritia:Resource", 3).amount(9), ItemBracketHandler.getItem("Avaritia:Resource", 4), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32309).amount(0), 2400, HV)
        AlloySmelter.addRecipe(ItemBracketHandler.getItem("Avaritia:Resource", 4).amount(9), ItemBracketHandler.getItem("Avaritia:Resource_Block", 0), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32306).amount(0), 4800, HV)
        Assembler.addRecipe(ItemBracketHandler.getItem("Avaritia:Resource", 1), ItemBracketHandler.getItem("Avaritia:Resource", 0).amount(4), ItemBracketHandler.getItem("minecraft:nether_star", 0).amount(2), 1200, HV)
        Compressor.addRecipe(ItemBracketHandler.getItem("Avaritia:Double_Craft", 0), ItemBracketHandler.getItem("minecraft:crafting_table", 0).amount(9))
        Compressor.addRecipe(ItemBracketHandler.getItem("Avaritia:Triple_Craft", 0), ItemBracketHandler.getItem("Avaritia:Double_Craft", 0).amount(9))
        Compressor.addRecipe(ItemBracketHandler.getItem("Avaritia:Crystal_Matrix", 0), ItemBracketHandler.getItem("Avaritia:Resource", 1).amount(9))
        Extractor.addRecipe(ItemBracketHandler.getItem("minecraft:crafting_table", 0).amount(9), ItemBracketHandler.getItem("Avaritia:Double_Craft", 0))
        Extractor.addRecipe(ItemBracketHandler.getItem("Avaritia:Double_Craft", 0).amount(9), ItemBracketHandler.getItem("Avaritia:Triple_Craft", 0))
        Extractor.addRecipe(ItemBracketHandler.getItem("Avaritia:Resource", 1).amount(9), ItemBracketHandler.getItem("Avaritia:Crystal_Matrix", 0))
        Extruder.addRecipe(ItemBracketHandler.getItem("Avaritia:Resource", 4).amount(9), ItemBracketHandler.getItem("Avaritia:Resource_Block", 0), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32355).amount(0), 1000, UV)
        Extruder.addRecipe(ItemBracketHandler.getItem("Avaritia:Resource", 6).amount(9), ItemBracketHandler.getItem("Avaritia:Resource_Block", 1), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32355).amount(0), 1200, UV)
        Extruder.addRecipe(ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 17397), ItemBracketHandler.getItem("Avaritia:Resource", 6), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32350).amount(0), 4000, UV)
        Extruder.addRecipe(ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 17397), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 11397), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32350).amount(0), 4000, UV)
        Extruder.addRecipe(ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 17982), ItemBracketHandler.getItem("Avaritia:Resource", 4), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32350).amount(0), 3000, UV)
        Extruder.addRecipe(ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 17982), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 11982), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32350).amount(0), 3000, UV)
        FormingPress.addRecipe(ItemBracketHandler.getItem("Avaritia:Resource", 0), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 17500).amount(4), ItemBracketHandler.getItem("dreamcraft:item.StainlessSteelBars", 0), 200, MV)
        Pulverizer.addRecipe(arrayOf(ItemBracketHandler.getItem("Avaritia:Resource", 2).amount(9)), ItemBracketHandler.getItem("Avaritia:Resource", 3), intArrayOf(10000), 300, LULV)
        fox.spiteful.avaritia.compat.minetweaker.Compressor.add(ItemBracketHandler.getItem("Avaritia:Resource", 5), 64, ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 2394))
    }
}