package com.github.GTNH2Mega.fromScripts

import buildcraft.compat.minetweaker.AssemblyTable
import com.github.GTNH2Mega.VoltageLevels.HV
import com.github.GTNH2Mega.VoltageLevels.LHV
import com.github.GTNH2Mega.VoltageLevels.LMV
import com.github.GTNH2Mega.VoltageLevels.LV
import com.github.GTNH2Mega.VoltageLevels.MV
import com.github.GTNH2Mega.VoltageLevels.ULV
import java.lang.Runnable
import minetweaker.api.item.IItemStack
import minetweaker.mc1710.brackets.ItemBracketHandler
import minetweaker.api.oredict.IOreDictEntry
import minetweaker.mc1710.brackets.OreBracketHandler
import minetweaker.MineTweakerAPI
import minetweaker.api.item.IIngredient
import gttweaker.mods.gregtech.machines.Assembler
import minetweaker.mc1710.brackets.LiquidBracketHandler
import gttweaker.mods.gregtech.machines.FormingPress
import gttweaker.mods.gregtech.machines.PrecisionLaser
import minetweaker.mods.nei.NEI

class BuildCraft : Runnable {
    override fun run() {
        val iItemStack = ItemBracketHandler.getItem("BuildCraft|Core:diamondGearItem", 0)
        val iItemStack2 = ItemBracketHandler.getItem("BuildCraft|Core:goldGearItem", 0)
        val iItemStack3 = ItemBracketHandler.getItem("BuildCraft|Core:ironGearItem", 0)
        val iItemStack4 = ItemBracketHandler.getItem("BuildCraft|Core:stoneGearItem", 0)
        val iItemStack5 = ItemBracketHandler.getItem("BuildCraft|Core:woodenGearItem", 0)
        val iItemStack6 = ItemBracketHandler.getItem("BuildCraft|Factory:miningWellBlock", 0)
        val iItemStack7 = ItemBracketHandler.getItem("BuildCraft|Transport:pipeWaterproof", 0)
        val iItemStack9 = ItemBracketHandler.getItem("BuildCraft|Transport:item.buildcraftPipe.pipepowerwood", 0)
        val iItemStack10 = ItemBracketHandler.getItem("BuildCraft|Transport:item.buildcraftPipe.pipeitemscobblestone", 0)
        val iItemStack11 = ItemBracketHandler.getItem("BuildCraft|Transport:item.buildcraftPipe.pipepowercobblestone", 0)
        val iItemStack12 = ItemBracketHandler.getItem("BuildCraft|Transport:item.buildcraftPipe.pipeitemsstone", 0)
        val iItemStack13 = ItemBracketHandler.getItem("BuildCraft|Transport:item.buildcraftPipe.pipepowerstone", 0)
        val iItemStack14 = ItemBracketHandler.getItem("BuildCraft|Transport:item.buildcraftPipe.pipeitemssandstone", 0)
        val iItemStack15 = ItemBracketHandler.getItem("BuildCraft|Transport:item.buildcraftPipe.pipepowersandstone", 0)
        val iItemStack16 = ItemBracketHandler.getItem("BuildCraft|Transport:item.buildcraftPipe.pipeitemsiron", 0)
        val iItemStack17 = ItemBracketHandler.getItem("BuildCraft|Transport:item.buildcraftPipe.pipepoweriron", 0)
        val iItemStack18 = ItemBracketHandler.getItem("BuildCraft|Transport:item.buildcraftPipe.pipeitemsquartz", 0)
        val iItemStack19 = ItemBracketHandler.getItem("BuildCraft|Transport:item.buildcraftPipe.pipepowerquartz", 0)
        val iItemStack21 = ItemBracketHandler.getItem("BuildCraft|Transport:item.buildcraftPipe.pipepowergold", 0)
        val iItemStack25 = ItemBracketHandler.getItem("BuildCraft|Transport:item.buildcraftPipe.pipepowerdiamond", 0)
        val iItemStack27 = ItemBracketHandler.getItem("BuildCraft|Transport:item.buildcraftPipe.pipepoweremerald", 0)
        val iItemStack34 = ItemBracketHandler.getItem("BuildCraft|Silicon:laserBlock", 0)
        val iItemStack35 = ItemBracketHandler.getItem("BuildCraft|Factory:tankBlock", 0)
        val iItemStack36 = ItemBracketHandler.getItem("ForgeMicroblock:stoneRod", 0)
        val iOreDictEntry = OreBracketHandler.getOre("stickWood")
        val iOreDictEntry2 = OreBracketHandler.getOre("ringIron")
        val iOreDictEntry3 = OreBracketHandler.getOre("stickNetherQuartz")
        val iOreDictEntry4 = OreBracketHandler.getOre("stickIron")
        val iOreDictEntry5 = OreBracketHandler.getOre("screwIron")
        val iOreDictEntry6 = OreBracketHandler.getOre("stickGold")
        val iOreDictEntry7 = OreBracketHandler.getOre("stickEmerald")
        val iOreDictEntry8 = OreBracketHandler.getOre("stickDiamond")
        val iItemStack37 = ItemBracketHandler.getItem("dreamcraft:item.SandStoneRod", 0)
        val iItemStack38 = ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 23299)
        val iItemStack39 = ItemBracketHandler.getItem("TConstruct:GlassPane", 0)
        val iOreDictEntry12 = OreBracketHandler.getOre("wireGt01Tin")
        val iOreDictEntry13 = OreBracketHandler.getOre("wireGt01Nickel")
        val iOreDictEntry14 = OreBracketHandler.getOre("wireGt01Copper")
        val iOreDictEntry15 = OreBracketHandler.getOre("wireGt01Cupronickel")
        val iOreDictEntry16 = OreBracketHandler.getOre("wireGt01Silver")
        val iOreDictEntry17 = OreBracketHandler.getOre("wireGt01Aluminium")
        val iOreDictEntry18 = OreBracketHandler.getOre("wireGt01Electrum")
        val iOreDictEntry21 = OreBracketHandler.getOre("wireGt01Platinum")
        val iOreDictEntry22 = OreBracketHandler.getOre("wireGt01Nichrome")
        val iItemStack40 = ItemBracketHandler.getItem("BuildCraft|Silicon:redstoneCrystal", 0)
        val iItemStack41 = ItemBracketHandler.getItem("BuildCraft|Core:pathMarkerBlock", 0)
        val iItemStack42 = ItemBracketHandler.getItem("BuildCraft|Core:markerBlock", 0)
        val iItemStack44 = ItemBracketHandler.getItem("BuildCraft|Transport:pipeGate", 32767)
        val iItemStack46 = ItemBracketHandler.getItem("BuildCraft|Transport:pipePlug", 0)
        val iItemStack47 = ItemBracketHandler.getItem("BuildCraft|Transport:gateCopier", 0)
        val iItemStack48 = ItemBracketHandler.getItem("BuildCraft|Robotics:robotStation", 0)
        val iItemStack49 = ItemBracketHandler.getItem("BuildCraft|Builders:fillerBlock", 0)
        val iItemStack50 = ItemBracketHandler.getItem("BuildCraft|Builders:builderBlock", 0)
        val iItemStack51 = ItemBracketHandler.getItem("BuildCraft|Builders:architectBlock", 0)
        val iItemStack52 = ItemBracketHandler.getItem("BuildCraft|Builders:libraryBlock", 0)
        val iItemStack53 = ItemBracketHandler.getItem("BuildCraft|Factory:autoWorkbenchBlock", 0)
        val iItemStack54 = ItemBracketHandler.getItem("BuildCraft|Factory:floodGateBlock", 0)
        val iItemStack55 = ItemBracketHandler.getItem("BuildCraft|Robotics:zonePlan", 0)
        val iItemStack56 = ItemBracketHandler.getItem("BuildCraft|Robotics:requester", 0)
        val iItemStack57 = ItemBracketHandler.getItem("BuildCraft|Robotics:robot", 0)
        val iItemStack58 = ItemBracketHandler.getItem("BuildCraft|Transport:filteredBufferBlock", 0)
        val iItemStack59 = ItemBracketHandler.getItem("Railcraft:glass", 0)
        val iOreDictEntry25 = OreBracketHandler.getOre("craftingToolWrench")
        val iOreDictEntry26 = OreBracketHandler.getOre("craftingToolScrewdriver")
        MineTweakerAPI.recipes.remove(iItemStack6)
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("BuildCraft|Builders:machineBlock", 0))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("BuildCraft|Factory:pumpBlock", 0))
        MineTweakerAPI.recipes.remove(iItemStack34)
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("BuildCraft|Silicon:laserTableBlock", 0))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("BuildCraft|Factory:refineryBlock", 0))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("BuildCraft|Factory:blockHopper", 0))
        MineTweakerAPI.recipes.remove(iItemStack35)
        MineTweakerAPI.recipes.remove(iItemStack49)
        MineTweakerAPI.recipes.remove(iItemStack50)
        MineTweakerAPI.recipes.remove(iItemStack51)
        MineTweakerAPI.recipes.remove(iItemStack52)
        MineTweakerAPI.recipes.remove(iItemStack53)
        MineTweakerAPI.recipes.remove(iItemStack54)
        MineTweakerAPI.recipes.remove(iItemStack55)
        MineTweakerAPI.recipes.remove(iItemStack56)
        MineTweakerAPI.recipes.remove(iItemStack58)
        MineTweakerAPI.recipes.remove(iItemStack48)
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("BuildCraft|Silicon:laserTableBlock", 2))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("BuildCraft|Silicon:laserTableBlock", 3))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("BuildCraft|Silicon:laserTableBlock", 4))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("BuildCraft|Silicon:laserTableBlock", 5))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("BuildCraft|Silicon:packagerBlock", 0))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("BuildCraft|Core:engineBlock", 0))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("BuildCraft|Core:engineBlock", 1))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("BuildCraft|Core:engineBlock", 2))
        MineTweakerAPI.recipes.remove(iItemStack)
        MineTweakerAPI.recipes.remove(iItemStack2)
        MineTweakerAPI.recipes.remove(iItemStack3)
        MineTweakerAPI.recipes.remove(iItemStack4)
        MineTweakerAPI.recipes.remove(iItemStack5)
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("BuildCraft|Transport:item.buildcraftPipe.pipefluidsclay", 0))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("BuildCraft|Transport:pipePowerAdapter", 0))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("BuildCraft|Transport:item.buildcraftPipe.pipeitemswood", 32767))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("BuildCraft|Transport:item.buildcraftPipe.pipefluidswood", 32767))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("BuildCraft|Transport:item.buildcraftPipe.pipepowerwood", 32767))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("BuildCraft|Transport:item.buildcraftPipe.pipeitemscobblestone", 32767))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("BuildCraft|Transport:item.buildcraftPipe.pipefluidscobblestone", 32767))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("BuildCraft|Transport:item.buildcraftPipe.pipepowercobblestone", 32767))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("BuildCraft|Transport:item.buildcraftPipe.pipeitemsstone", 32767))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("BuildCraft|Transport:item.buildcraftPipe.pipefluidsstone", 32767))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("BuildCraft|Transport:item.buildcraftPipe.pipepowerstone", 32767))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("BuildCraft|Transport:item.buildcraftPipe.pipeitemssandstone", 32767))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("BuildCraft|Transport:item.buildcraftPipe.pipefluidssandstone", 32767))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("BuildCraft|Transport:item.buildcraftPipe.pipepowersandstone", 32767))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("BuildCraft|Transport:item.buildcraftPipe.pipeitemsiron", 32767))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("BuildCraft|Transport:item.buildcraftPipe.pipefluidsiron", 32767))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("BuildCraft|Transport:item.buildcraftPipe.pipepoweriron", 32767))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("BuildCraft|Transport:item.buildcraftPipe.pipeitemsquartz", 32767))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("BuildCraft|Transport:item.buildcraftPipe.pipefluidsquartz", 32767))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("BuildCraft|Transport:item.buildcraftPipe.pipepowerquartz", 32767))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("BuildCraft|Transport:item.buildcraftPipe.pipeitemsgold", 32767))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("BuildCraft|Transport:item.buildcraftPipe.pipefluidsgold", 32767))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("BuildCraft|Transport:item.buildcraftPipe.pipepowergold", 32767))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("BuildCraft|Transport:item.buildcraftPipe.pipeitemslapis", 32767))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("BuildCraft|Transport:item.buildcraftPipe.pipeitemsobsidian", 32767))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("BuildCraft|Transport:item.buildcraftPipe.pipeitemsdiamond", 32767))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("BuildCraft|Transport:item.buildcraftPipe.pipepowerdiamond", 32767))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("BuildCraft|Transport:item.buildcraftPipe.pipefluidsdiamond", 32767))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("BuildCraft|Transport:item.buildcraftPipe.pipeitemsemerald", 32767))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("BuildCraft|Transport:item.buildcraftPipe.pipefluidsemerald", 32767))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("BuildCraft|Transport:item.buildcraftPipe.pipepoweremerald", 32767))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("BuildCraft|Transport:item.buildcraftPipe.pipeitemsdaizuli", 32767))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("BuildCraft|Transport:item.buildcraftPipe.pipeitemsemzuli", 32767))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("BuildCraft|Transport:item.buildcraftPipe.pipeitemsstripes", 32767))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("BuildCraft|Transport:item.buildcraftPipe.pipeitemsvoid", 32767))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("BuildCraft|Transport:item.buildcraftPipe.pipefluidsvoid", 32767))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("BuildCraft|Transport:item.buildcraftPipe.pipeitemsclay", 32767))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("BuildCraft|Transport:item.buildcraftPipe.pipestructurecobblestone", 32767))
        MineTweakerAPI.recipes.remove(iItemStack57)
        MineTweakerAPI.recipes.remove(iItemStack44)
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("BuildCraft|Builders:constructionMarkerBlock", 0))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("BuildCraft|Builders:templateItem", 0))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("BuildCraft|Builders:blueprintItem", 0))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("BuildCraft|Robotics:redstone_board", 0))
        MineTweakerAPI.recipes.remove(iItemStack42)
        MineTweakerAPI.recipes.remove(iItemStack41)
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("BuildCraft|Core:wrenchItem", 0))
        MineTweakerAPI.recipes.remove(iItemStack40)
        MineTweakerAPI.recipes.remove(iItemStack7)
        MineTweakerAPI.recipes.remove(iItemStack46)
        MineTweakerAPI.recipes.remove(iItemStack47)
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("BuildCraft|Core:mapLocation", 0))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("BuildCraft|Compat:item.buildcraftPipe.pipeitemspropolis", 0))
        AssemblyTable.removeRecipe(ItemBracketHandler.getItem("BuildCraft|Silicon:redstoneCrystal", 0), null, false)
        AssemblyTable.removeRecipe(ItemBracketHandler.getItem("BuildCraft|Silicon:redstoneChipset", 32767), null, false)
        AssemblyTable.removeRecipe(ItemBracketHandler.getItem("gendustry:GeneticsProcessor", 0), null, false)
        AssemblyTable.removeRecipe(ItemBracketHandler.getItem("gendustry:EnvProcessor", 0), null, false)
        MineTweakerAPI.recipes.addShapeless(iItemStack, arrayOf<IIngredient>(OreBracketHandler.getOre("gearGtDiamond")), null)
        MineTweakerAPI.recipes.addShapeless(iItemStack2, arrayOf<IIngredient>(OreBracketHandler.getOre("gearGtGold")), null)
        MineTweakerAPI.recipes.addShapeless(iItemStack3, arrayOf<IIngredient>(OreBracketHandler.getOre("gearGtIron")), null)
        MineTweakerAPI.recipes.addShapeless(iItemStack4, arrayOf<IIngredient>(OreBracketHandler.getOre("gearGtStone")), null)
        MineTweakerAPI.recipes.addShapeless(iItemStack5, arrayOf<IIngredient>(OreBracketHandler.getOre("gearGtWood")), null)
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("BuildCraft|Core:engineBlock", 2), arrayOf(arrayOf<IIngredient>(OreBracketHandler.getOre("plateInvar"), OreBracketHandler.getOre("plateLapis"), OreBracketHandler.getOre("plateInvar")), arrayOf(OreBracketHandler.getOre("springInvar"), ItemBracketHandler.getItem("minecraft:piston", 0), OreBracketHandler.getOre("springInvar")), arrayOf(OreBracketHandler.getOre("gearInvar"), ItemBracketHandler.getItem("Forestry:sturdyMachine", 0), OreBracketHandler.getOre("gearInvar"))), null)
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("BuildCraft|Transport:item.buildcraftPipe.pipestructurecobblestone", 0), arrayOf(arrayOf<IIngredient>(iItemStack38, iItemStack39, iItemStack38), arrayOf<IIngredient>(iItemStack39, ItemBracketHandler.getItem("minecraft:gravel", 0), iItemStack39), arrayOf<IIngredient>(iItemStack38, iItemStack39, iItemStack38)), null)
        MineTweakerAPI.recipes.addShaped(iItemStack11, arrayOf(arrayOf<IIngredient>(iItemStack38, iItemStack39, iItemStack38), arrayOf(iItemStack39, iOreDictEntry12, iItemStack39), arrayOf<IIngredient>(iItemStack38, iItemStack39, iItemStack38)), null)
        MineTweakerAPI.recipes.addShaped(iItemStack13, arrayOf(arrayOf<IIngredient>(iItemStack36, iItemStack39, iItemStack36), arrayOf(iItemStack39, iOreDictEntry13, iItemStack39), arrayOf<IIngredient>(iItemStack36, iItemStack39, iItemStack36)), null)
        MineTweakerAPI.recipes.addShaped(iItemStack9, arrayOf(arrayOf(iOreDictEntry, iItemStack39, iOreDictEntry), arrayOf(iItemStack39, iOreDictEntry14, iItemStack39), arrayOf(iOreDictEntry, iItemStack39, iOreDictEntry)), null)
        MineTweakerAPI.recipes.addShaped(iItemStack15, arrayOf(arrayOf<IIngredient>(iItemStack37, iItemStack39, iItemStack37), arrayOf(iItemStack39, iOreDictEntry15, iItemStack39), arrayOf<IIngredient>(iItemStack37, iItemStack39, iItemStack37)), null)
        MineTweakerAPI.recipes.addShaped(iItemStack19, arrayOf(arrayOf(iOreDictEntry3, iItemStack39, iOreDictEntry3), arrayOf(iItemStack39, iOreDictEntry16, iItemStack39), arrayOf(iOreDictEntry3, iItemStack39, iOreDictEntry3)), null)
        MineTweakerAPI.recipes.addShaped(iItemStack17, arrayOf(arrayOf(iOreDictEntry4, iItemStack39, iOreDictEntry4), arrayOf(iItemStack39, iOreDictEntry18, iItemStack39), arrayOf(iOreDictEntry4, iItemStack39, iOreDictEntry4)), null)
        MineTweakerAPI.recipes.addShaped(iItemStack21, arrayOf(arrayOf(iOreDictEntry6, iItemStack39, iOreDictEntry6), arrayOf(iItemStack39, iOreDictEntry17, iItemStack39), arrayOf(iOreDictEntry6, iItemStack39, iOreDictEntry6)), null)
        MineTweakerAPI.recipes.addShaped(iItemStack27, arrayOf(arrayOf(iOreDictEntry7, iItemStack39, iOreDictEntry7), arrayOf(iItemStack39, iOreDictEntry22, iItemStack39), arrayOf(iOreDictEntry7, iItemStack39, iOreDictEntry7)), null)
        MineTweakerAPI.recipes.addShaped(iItemStack25, arrayOf(arrayOf(iOreDictEntry8, iItemStack39, iOreDictEntry8), arrayOf(iItemStack39, iOreDictEntry21, iItemStack39), arrayOf(iOreDictEntry8, iItemStack39, iOreDictEntry8)), null)
        MineTweakerAPI.recipes.addShaped(iItemStack35, arrayOf(arrayOf<IIngredient>(iOreDictEntry5, iOreDictEntry2, iOreDictEntry5), arrayOf(iOreDictEntry25, iItemStack59, iOreDictEntry26), arrayOf<IIngredient>(iOreDictEntry5, iOreDictEntry2, iOreDictEntry5)), null)
        MineTweakerAPI.recipes.addShaped(iItemStack35, arrayOf(arrayOf<IIngredient>(OreBracketHandler.getOre("screwIron"), OreBracketHandler.getOre("ringIron"), OreBracketHandler.getOre("screwIron")), arrayOf(OreBracketHandler.getOre("craftingToolWrench"), ItemBracketHandler.getItem("ExtraUtilities:decorativeBlock2", 5), OreBracketHandler.getOre("craftingToolScrewdriver")), arrayOf<IIngredient>(OreBracketHandler.getOre("screwIron"), OreBracketHandler.getOre("ringIron"), OreBracketHandler.getOre("screwIron"))), null)
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("BuildCraft|Transport:item.buildcraftPipe.pipeitemsvoid", 0), arrayOf(arrayOf<IIngredient>(ItemBracketHandler.getItem("RandomThings:ingredient", 1), iItemStack39, ItemBracketHandler.getItem("RandomThings:ingredient", 1)), arrayOf(iItemStack39, OreBracketHandler.getOre("gemEnderPearl"), iItemStack39), arrayOf<IIngredient>(ItemBracketHandler.getItem("RandomThings:ingredient", 1), iItemStack39, ItemBracketHandler.getItem("RandomThings:ingredient", 1))), null)
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("BuildCraft|Transport:item.buildcraftPipe.pipefluidsvoid", 0), arrayOf(arrayOf(OreBracketHandler.getOre("stickAnyRubber"), iItemStack39, OreBracketHandler.getOre("stickAnyRubber")), arrayOf(iItemStack39, OreBracketHandler.getOre("gemEnderPearl"), iItemStack39), arrayOf(OreBracketHandler.getOre("stickAnyRubber"), iItemStack39, OreBracketHandler.getOre("stickAnyRubber"))), null)
        MineTweakerAPI.recipes.addShaped(iItemStack53, arrayOf(arrayOf<IIngredient>(OreBracketHandler.getOre("itemCasingAnyIron"), OreBracketHandler.getOre("gearGtSmallAnyIron"), OreBracketHandler.getOre("itemCasingAnyIron")), arrayOf(OreBracketHandler.getOre("gearGtSmallAnyIron"), ItemBracketHandler.getItem("Forestry:factory2", 2), OreBracketHandler.getOre("gearGtSmallAnyIron")), arrayOf(OreBracketHandler.getOre("itemCasingAnyIron"), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32600), OreBracketHandler.getOre("itemCasingAnyIron"))), null)
        MineTweakerAPI.recipes.addShapeless(ItemBracketHandler.getItem("BuildCraft|Core:paintbrush", 0), arrayOf<IIngredient>(ItemBracketHandler.getItem("OpenBlocks:paintBrush", 0)), null)
        MineTweakerAPI.recipes.addShapeless(ItemBracketHandler.getItem("BuildCraft|Factory:autoWorkbenchBlock", 0), arrayOf<IIngredient>(ItemBracketHandler.getItem("ProjRed|Expansion:projectred.expansion.machine2", 11)), null)
        MineTweakerAPI.recipes.addShaped(iItemStack49, arrayOf(arrayOf(ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32651), OreBracketHandler.getOre("crystalRedstone"), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32651)), arrayOf(OreBracketHandler.getOre("circuitGood"), ItemBracketHandler.getItem("gregtech:gt.blockmachines", 12), OreBracketHandler.getOre("circuitGood")), arrayOf(OreBracketHandler.getOre("gearGtSmallAluminium"), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32601), OreBracketHandler.getOre("gearGtSmallAluminium"))), null)
        MineTweakerAPI.recipes.addShaped(iItemStack50, arrayOf(arrayOf(ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32652), OreBracketHandler.getOre("crystalRedstone"), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32652)), arrayOf(OreBracketHandler.getOre("circuitAdvanced"), ItemBracketHandler.getItem("gregtech:gt.blockmachines", 13), OreBracketHandler.getOre("circuitAdvanced")), arrayOf(OreBracketHandler.getOre("gearGtSmallStainlessSteel"), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32602), OreBracketHandler.getOre("gearGtSmallStainlessSteel"))), null)
        MineTweakerAPI.recipes.addShaped(iItemStack51, arrayOf(arrayOf<IIngredient>(ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32652), ItemBracketHandler.getItem("BuildCraft|Builders:templateItem", 0), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32652)), arrayOf(OreBracketHandler.getOre("circuitAdvanced"), ItemBracketHandler.getItem("gregtech:gt.blockmachines", 13), OreBracketHandler.getOre("circuitAdvanced")), arrayOf(OreBracketHandler.getOre("gearGtDiamond"), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32602), OreBracketHandler.getOre("gearGtDiamond"))), null)
        MineTweakerAPI.recipes.addShaped(iItemStack52, arrayOf(arrayOf<IIngredient>(OreBracketHandler.getOre("itemCasingStainlessSteel"), OreBracketHandler.getOre("crystalRedstone"), OreBracketHandler.getOre("itemCasingStainlessSteel")), arrayOf(OreBracketHandler.getOre("circuitData"), ItemBracketHandler.getItem("dreamcraft:item.Display", 0), OreBracketHandler.getOre("circuitData")), arrayOf<IIngredient>(OreBracketHandler.getOre("itemCasingStainlessSteel"), OreBracketHandler.getOre("plateSteel"), OreBracketHandler.getOre("itemCasingStainlessSteel"))), null)
        MineTweakerAPI.recipes.addShaped(iItemStack54, arrayOf(arrayOf(OreBracketHandler.getOre("itemCasingSteel"), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32610), OreBracketHandler.getOre("itemCasingSteel")), arrayOf<IIngredient>(ItemBracketHandler.getItem("dreamcraft:item.SteelBars", 0), ItemBracketHandler.getItem("BuildCraft|Factory:tankBlock", 0), ItemBracketHandler.getItem("dreamcraft:item.SteelBars", 0)), arrayOf(OreBracketHandler.getOre("itemCasingSteel"), ItemBracketHandler.getItem("dreamcraft:item.SteelBars", 0), OreBracketHandler.getOre("itemCasingSteel"))), null)
        MineTweakerAPI.recipes.addShaped(iItemStack34, arrayOf(arrayOf<IIngredient>(OreBracketHandler.getOre("screwStainlessSteel"), OreBracketHandler.getOre("blockRedstone"), OreBracketHandler.getOre("screwStainlessSteel")), arrayOf<IIngredient>(OreBracketHandler.getOre("lensDiamond"), OreBracketHandler.getOre("circuitAdvanced"), OreBracketHandler.getOre("lensDiamond")), arrayOf(OreBracketHandler.getOre("plateDenseObsidian"), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32682), OreBracketHandler.getOre("plateDenseObsidian"))), null)
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("BuildCraft|Silicon:laserTableBlock", 0), arrayOf(arrayOf(ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32652), OreBracketHandler.getOre("blockRedstone"), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32652)), arrayOf<IIngredient>(OreBracketHandler.getOre("plateDiamond"), OreBracketHandler.getOre("circuitAdvanced"), OreBracketHandler.getOre("plateDiamond")), arrayOf(OreBracketHandler.getOre("plateDenseObsidian"), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32692), OreBracketHandler.getOre("plateDenseObsidian"))), null)
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("BuildCraft|Silicon:laserTableBlock", 3), arrayOf(arrayOf<IIngredient>(OreBracketHandler.getOre("circuitAdvanced"), OreBracketHandler.getOre("blockRedstone"), OreBracketHandler.getOre("circuitAdvanced")), arrayOf<IIngredient>(OreBracketHandler.getOre("chipsetRed"), OreBracketHandler.getOre("crystalRedstone"), OreBracketHandler.getOre("chipsetRed")), arrayOf<IIngredient>(OreBracketHandler.getOre("plateDenseObsidian"), OreBracketHandler.getOre("chipsetRed"), OreBracketHandler.getOre("plateDenseObsidian"))), null)
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("BuildCraft|Silicon:laserTableBlock", 2), arrayOf(arrayOf(ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32652), OreBracketHandler.getOre("blockRedstone"), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32652)), arrayOf(ItemBracketHandler.getItem("BuildCraft|Silicon:redstoneChipset", 3), OreBracketHandler.getOre("circuitAdvanced"), ItemBracketHandler.getItem("BuildCraft|Silicon:redstoneChipset", 3)), arrayOf(OreBracketHandler.getOre("plateDenseObsidian"), ItemBracketHandler.getItem("BuildCraft|Silicon:redstoneChipset", 0), OreBracketHandler.getOre("plateDenseObsidian"))), null)
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("BuildCraft|Silicon:laserTableBlock", 4), arrayOf(arrayOf<IIngredient>(OreBracketHandler.getOre("circuitAdvanced"), OreBracketHandler.getOre("blockRedstone"), OreBracketHandler.getOre("circuitAdvanced")), arrayOf<IIngredient>(ItemBracketHandler.getItem("BuildCraft|Silicon:redstoneChipset", 6), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32652), ItemBracketHandler.getItem("BuildCraft|Silicon:redstoneChipset", 6)), arrayOf(OreBracketHandler.getOre("plateDenseObsidian"), ItemBracketHandler.getItem("BuildCraft|Silicon:redstoneChipset", 0), OreBracketHandler.getOre("plateDenseObsidian"))), null)
        MineTweakerAPI.recipes.addShaped(iItemStack55, arrayOf(arrayOf(ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32652), OreBracketHandler.getOre("circuitAdvanced"), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32652)), arrayOf(OreBracketHandler.getOre("gearGtDiamond"), ItemBracketHandler.getItem("minecraft:map", 0), OreBracketHandler.getOre("gearGtDiamond")), arrayOf<IIngredient>(ItemBracketHandler.getItem("BuildCraft|Silicon:redstoneChipset", 7), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32602), ItemBracketHandler.getItem("BuildCraft|Silicon:redstoneChipset", 7))), null)
        MineTweakerAPI.recipes.addShaped(iItemStack57, arrayOf(arrayOf<IIngredient>(OreBracketHandler.getOre("plateStainlessSteel"), OreBracketHandler.getOre("plateStainlessSteel"), OreBracketHandler.getOre("plateStainlessSteel")), arrayOf<IIngredient>(ItemBracketHandler.getItem("BuildCraft|Silicon:redstoneChipset", 3), ItemBracketHandler.getItem("BuildCraft|Silicon:redstoneCrystal", 0), ItemBracketHandler.getItem("BuildCraft|Silicon:redstoneChipset", 3)), arrayOf<IIngredient>(OreBracketHandler.getOre("circuitAdvanced"), OreBracketHandler.getOre("plateStainlessSteel"), OreBracketHandler.getOre("circuitAdvanced"))), null)
        MineTweakerAPI.recipes.addShaped(iItemStack56, arrayOf(arrayOf(OreBracketHandler.getOre("plateStainlessSteel"), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32642), OreBracketHandler.getOre("plateStainlessSteel")), arrayOf<IIngredient>(OreBracketHandler.getOre("gearGtSteel"), OreBracketHandler.getOre("chestSteel"), OreBracketHandler.getOre("gearGtSteel")), arrayOf(OreBracketHandler.getOre("plateStainlessSteel"), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32692), OreBracketHandler.getOre("plateStainlessSteel"))), null)
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("BuildCraft|Core:wrenchItem", 0), arrayOf(arrayOf<IIngredient?>(null, OreBracketHandler.getOre("ingotStainlessSteel"), null), arrayOf<IIngredient?>(OreBracketHandler.getOre("ingotStainlessSteel"), OreBracketHandler.getOre("ingotStainlessSteel"), OreBracketHandler.getOre("ingotStainlessSteel")), arrayOf<IIngredient?>(OreBracketHandler.getOre("ingotStainlessSteel"), OreBracketHandler.getOre("craftingToolHardHammer"), OreBracketHandler.getOre("ingotStainlessSteel"))), null)
        Assembler.addRecipe(ItemBracketHandler.getItem("BuildCraft|Core:engineBlock", 2), ItemBracketHandler.getItem("dreamcraft:item.EngineCore", 0), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 17302).amount(10), 800, LHV)
        Assembler.addRecipe(ItemBracketHandler.getItem("BuildCraft|Compat:item.buildcraftPipe.pipeitemspropolis", 0), ItemBracketHandler.getItem("ProjRed|Transportation:projectred.transportation.pipe", 1), ItemBracketHandler.getItem("Forestry:propolis", 0).amount(2), LiquidBracketHandler.getLiquid("for.honey").withAmount(400), 300, LMV)
        Assembler.addRecipe(ItemBracketHandler.getItem("BuildCraft|Compat:item.buildcraftPipe.pipeitemspropolis", 0), ItemBracketHandler.getItem("ProjRed|Transportation:projectred.transportation.pipe", 1), ItemBracketHandler.getItem("Forestry:propolis", 0).amount(2), LiquidBracketHandler.getLiquid("honey").withAmount(400), 300, LMV)
        Assembler.addRecipe(iItemStack42, ItemBracketHandler.getItem("minecraft:redstone_torch", 0), ItemBracketHandler.getItem("ProjRed|Core:projectred.core.part", 30), 100, MV)
        Assembler.addRecipe(iItemStack41, ItemBracketHandler.getItem("minecraft:redstone_torch", 0), ItemBracketHandler.getItem("ProjRed|Core:projectred.core.part", 24), 100, MV)
        Assembler.addRecipe(ItemBracketHandler.getItem("BuildCraft|Builders:templateItem", 0), ItemBracketHandler.getItem("minecraft:paper", 0), ItemBracketHandler.getItem("minecraft:redstone", 0), LiquidBracketHandler.getLiquid("squidink").withAmount(144), 100, LV)
        Assembler.addRecipe(ItemBracketHandler.getItem("BuildCraft|Builders:blueprintItem", 0), ItemBracketHandler.getItem("minecraft:paper", 0), ItemBracketHandler.getItem("minecraft:redstone", 0), LiquidBracketHandler.getLiquid("dye.watermixed.dyeblue").withAmount(144), 100, LV)
        Assembler.addRecipe(ItemBracketHandler.getItem("BuildCraft|Factory:tankBlock", 0), ItemBracketHandler.getItem("Railcraft:glass", 0), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 28032).amount(2), 100, ULV)
        Assembler.addRecipe(ItemBracketHandler.getItem("BuildCraft|Factory:tankBlock", 0), ItemBracketHandler.getItem("ExtraUtilities:decorativeBlock2", 5), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 28032).amount(2), 100, ULV)
        Assembler.addRecipe(ItemBracketHandler.getItem("BuildCraft|Robotics:redstone_board", 0), ItemBracketHandler.getItem("minecraft:paper", 0).amount(8), ItemBracketHandler.getItem("gregtech:gt.integrated_circuit", 8).amount(0), LiquidBracketHandler.getLiquid("molten.redstone").withAmount(144), 200, HV)
        Assembler.addRecipe(iItemStack48, ItemBracketHandler.getItem("BuildCraft|Silicon:redstoneChipset", 2), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 17306).amount(4), 300, HV)
        Assembler.addRecipe(ItemBracketHandler.getItem("BuildCraft|Core:mapLocation", 0), ItemBracketHandler.getItem("minecraft:paper", 0).amount(8), ItemBracketHandler.getItem("gregtech:gt.metaitem.02", 32425), 200, HV)
        Assembler.addRecipe(ItemBracketHandler.getItem("BuildCraft|Core:mapLocation", 0), ItemBracketHandler.getItem("minecraft:paper", 0).amount(8), ItemBracketHandler.getItem("minecraft:dye", 11), 200, HV)
        Assembler.addRecipe(ItemBracketHandler.getItem("BuildCraft|Core:mapLocation", 0), ItemBracketHandler.getItem("minecraft:paper", 0).amount(8), ItemBracketHandler.getItem("Botany:pigment", 78), 200, HV)
        Assembler.addRecipe(ItemBracketHandler.getItem("BuildCraft|Core:mapLocation", 0), ItemBracketHandler.getItem("minecraft:paper", 0).amount(8), ItemBracketHandler.getItem("ExtraBees:misc", 20), 200, HV)
        Assembler.addRecipe(iItemStack47, ItemBracketHandler.getItem("BuildCraft|Core:wrenchItem", 0), ItemBracketHandler.getItem("BuildCraft|Silicon:redstoneChipset", 0), 100, HV)
        Assembler.addRecipe(ItemBracketHandler.getItem("BuildCraft|Transport:item.buildcraftPipe.pipeitemswood", 0).amount(16), ItemBracketHandler.getItem("ProjRed|Transportation:projectred.transportation.pipe", 0).amount(16), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32632), 400, HV)
        Assembler.addRecipe(ItemBracketHandler.getItem("BuildCraft|Transport:item.buildcraftPipe.pipeitemsiron", 0).amount(16), ItemBracketHandler.getItem("ProjRed|Transportation:projectred.transportation.pipe", 0).amount(16), ItemBracketHandler.getItem("ProjRed|Transportation:projectred.transportation.pipe", 1), 400, HV)
        Assembler.addRecipe(ItemBracketHandler.getItem("BuildCraft|Transport:item.buildcraftPipe.pipeitemsgold", 0).amount(16), ItemBracketHandler.getItem("ProjRed|Transportation:projectred.transportation.pipe", 0).amount(16), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32602), 400, HV)
        Assembler.addRecipe(ItemBracketHandler.getItem("BuildCraft|Transport:item.buildcraftPipe.pipeitemsdiamond", 0).amount(8), ItemBracketHandler.getItem("ProjRed|Transportation:projectred.transportation.pipe", 0).amount(8), ItemBracketHandler.getItem("ProjRed|Transportation:projectred.transportation.pipe", 4), 400, HV)
        Assembler.addRecipe(ItemBracketHandler.getItem("BuildCraft|Transport:item.buildcraftPipe.pipeitemsobsidian", 0).amount(16), ItemBracketHandler.getItem("ProjRed|Transportation:projectred.transportation.pipe", 0).amount(16), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32652), 400, HV)
        Assembler.addRecipe(ItemBracketHandler.getItem("BuildCraft|Transport:item.buildcraftPipe.pipeitemsemerald", 0).amount(8), ItemBracketHandler.getItem("ProjRed|Transportation:projectred.transportation.pipe", 0).amount(8), ItemBracketHandler.getItem("IC2:itemPartCircuitAdv", 0), 400, HV)
        Assembler.addRecipe(ItemBracketHandler.getItem("BuildCraft|Transport:item.buildcraftPipe.pipeitemsemerald", 0).amount(8), ItemBracketHandler.getItem("ProjRed|Transportation:projectred.transportation.pipe", 0).amount(8), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32703), 400, HV)
        Assembler.addRecipe(ItemBracketHandler.getItem("BuildCraft|Transport:item.buildcraftPipe.pipeitemsemerald", 0).amount(8), ItemBracketHandler.getItem("ProjRed|Transportation:projectred.transportation.pipe", 0).amount(8), ItemBracketHandler.getItem("gregtech:gt.metaitem.03", 32082), 400, HV)
        FormingPress.addRecipe(ItemBracketHandler.getItem("BuildCraft|Silicon:redstoneChipset", 7), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 17501), ItemBracketHandler.getItem("BuildCraft|Silicon:redstoneChipset", 0), 200, HV)
        PrecisionLaser.addRecipe(ItemBracketHandler.getItem("BuildCraft|Silicon:redstoneCrystal", 0), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 24347).amount(0), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 17347).amount(4), 600, MV)
        NEI.overrideName(iItemStack9, "Wood-Covered Kinesis Pipe")
        NEI.overrideName(iItemStack10, "Cobblestone-Covered Pipe")
        NEI.overrideName(iItemStack11, "Cobblestone-Covered Kinesis Pipe")
        NEI.overrideName(iItemStack12, "Stone-Covered Pipe")
        NEI.overrideName(iItemStack13, "Stone-Covered Kinesis Pipe")
        NEI.overrideName(iItemStack14, "Sandstone-Covered Pipe")
        NEI.overrideName(iItemStack15, "Sandstone-Covered Kinesis Pipe")
        NEI.overrideName(iItemStack16, "Iron-Covered Pipe")
        NEI.overrideName(iItemStack17, "Iron-Covered Kinesis Pipe")
        NEI.overrideName(iItemStack18, "Quartz-Covered Pipe")
        NEI.overrideName(iItemStack19, "Quartz-Covered Kinesis Pipe")
        NEI.overrideName(iItemStack21, "Gold-Covered Kinesis Pipe")
        NEI.overrideName(iItemStack25, "Diamond-Covered Kinesis Pipe")
        NEI.overrideName(iItemStack27, "Emerald-Covered Kinesis Pipe")
        NEI.overrideName(ItemBracketHandler.getItem("BuildCraft|Silicon:redstoneCrystal", 0), "Firestone Crystal")
    }
}