package com.github.GTNH2Mega.fromScripts

import com.github.GTNH2Mega.VoltageLevels.LLV
import com.github.GTNH2Mega.VoltageLevels.LMV
import com.github.GTNH2Mega.VoltageLevels.LV
import com.github.GTNH2Mega.VoltageLevels.ULV
import java.lang.Runnable
import minetweaker.api.item.IItemStack
import minetweaker.mc1710.brackets.ItemBracketHandler
import minetweaker.api.oredict.IOreDictEntry
import minetweaker.mc1710.brackets.OreBracketHandler
import minetweaker.MineTweakerAPI
import minetweaker.api.item.IIngredient
import gttweaker.mods.gregtech.machines.Assembler
import gttweaker.mods.gregtech.machines.CuttingSaw
import minetweaker.mc1710.brackets.LiquidBracketHandler

class CarpentersBlocks : Runnable {
    override fun run() {
        val iItemStack = ItemBracketHandler.getItem("CarpentersBlocks:blockCarpentersBlock", 0)
        val iItemStack2 = ItemBracketHandler.getItem("CarpentersBlocks:blockCarpentersCollapsibleBlock", 0)
        val iOreDictEntry2 = OreBracketHandler.getOre("craftingToolSaw")
        val iOreDictEntry3 = OreBracketHandler.getOre("craftingToolScrewdriver")
        val iItemStack3 = ItemBracketHandler.getItem("CarpentersBlocks:blockCarpentersSafe", 0)
        val iItemStack4 = ItemBracketHandler.getItem("IC2:blockPersonal", 0)
        val iOreDictEntry4 = OreBracketHandler.getOre("craftingToolHardHammer")
        val iItemStack6 = ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 27809)
        val iItemStack7 = ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 27032)
        val iItemStack8 = ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 27305)
        val iItemStack9 = ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 27019)
        val iItemStack10 = ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 27306)
        val iItemStack11 = ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 27028)
        val iOreDictEntry5 = OreBracketHandler.getOre("frameGtWood")
        val iItemStack12 = ItemBracketHandler.getItem("CarpentersBlocks:itemCarpentersChisel", 0)
        val iItemStack13 = ItemBracketHandler.getItem("CarpentersBlocks:itemCarpentersHammer", 0)
        val iItemStack14 = ItemBracketHandler.getItem("CarpentersBlocks:blockCarpentersDaylightSensor", 0)
        val iItemStack15 = ItemBracketHandler.getItem("minecraft:daylight_detector", 0)
        val iOreDictEntry8 = OreBracketHandler.getOre("dustRedstone")
        MineTweakerAPI.recipes.remove(iItemStack)
        MineTweakerAPI.recipes.remove(iItemStack2)
        MineTweakerAPI.recipes.remove(iItemStack12)
        MineTweakerAPI.recipes.remove(iItemStack13)
        MineTweakerAPI.recipes.remove(iItemStack3)
        MineTweakerAPI.recipes.remove(iItemStack14)
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("CarpentersBlocks:itemCarpentersBed", 0))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("CarpentersBlocks:blockCarpentersTorch", 0))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("CarpentersBlocks:blockCarpentersGarageDoor", 0))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("CarpentersBlocks:blockCarpentersLadder", 0))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("CarpentersBlocks:blockCarpentersBarrier", 0))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("CarpentersBlocks:blockCarpentersPressurePlate", 0))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("CarpentersBlocks:blockCarpentersButton", 0))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("CarpentersBlocks:blockCarpentersFlowerPot", 0))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("CarpentersBlocks:blockCarpentersGate", 0))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("CarpentersBlocks:blockCarpentersHatch", 0))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("CarpentersBlocks:blockCarpentersLever", 0))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("CarpentersBlocks:blockCarpentersSlope", 0))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("CarpentersBlocks:blockCarpentersStairs", 0))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("CarpentersBlocks:itemCarpentersTile", 0))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("CarpentersBlocks:itemCarpentersDoor", 0))
        MineTweakerAPI.recipes.addShaped(iItemStack.amount(2), arrayOf(arrayOf(iOreDictEntry5, iItemStack6, iOreDictEntry5), arrayOf(iItemStack6, iOreDictEntry3, iItemStack6), arrayOf(iOreDictEntry5, iItemStack6, iOreDictEntry5)), null)
        MineTweakerAPI.recipes.addShaped(iItemStack.amount(8), arrayOf(arrayOf(iOreDictEntry5, iItemStack7, iOreDictEntry5), arrayOf<IIngredient>(iOreDictEntry5, iOreDictEntry3, iOreDictEntry5), arrayOf(iOreDictEntry5, iItemStack7, iOreDictEntry5)), null)
        MineTweakerAPI.recipes.addShaped(iItemStack.amount(12), arrayOf(arrayOf(iOreDictEntry5, iItemStack8, iOreDictEntry5), arrayOf<IIngredient>(iOreDictEntry5, iOreDictEntry3, iOreDictEntry5), arrayOf(iOreDictEntry5, iItemStack8, iOreDictEntry5)), null)
        MineTweakerAPI.recipes.addShaped(iItemStack.amount(16), arrayOf(arrayOf(iOreDictEntry5, iItemStack9, iOreDictEntry5), arrayOf<IIngredient>(iOreDictEntry5, iOreDictEntry3, iOreDictEntry5), arrayOf(iOreDictEntry5, iItemStack9, iOreDictEntry5)), null)
        MineTweakerAPI.recipes.addShaped(iItemStack.amount(20), arrayOf(arrayOf(iOreDictEntry5, iItemStack10, iOreDictEntry5), arrayOf<IIngredient>(iOreDictEntry5, iOreDictEntry3, iOreDictEntry5), arrayOf(iOreDictEntry5, iItemStack10, iOreDictEntry5)), null)
        MineTweakerAPI.recipes.addShaped(iItemStack.amount(24), arrayOf(arrayOf(iOreDictEntry5, iItemStack11, iOreDictEntry5), arrayOf<IIngredient>(iOreDictEntry5, iOreDictEntry3, iOreDictEntry5), arrayOf(iOreDictEntry5, iItemStack11, iOreDictEntry5)), null)
        MineTweakerAPI.recipes.addShaped(iItemStack2, arrayOf(arrayOf(iItemStack6, iOreDictEntry3, iItemStack6), arrayOf<IIngredient>(ItemBracketHandler.getItem("gregtech:gt.metaitem.02", 32470), ItemBracketHandler.getItem("gregtech:gt.metaitem.02", 32470), ItemBracketHandler.getItem("gregtech:gt.metaitem.02", 32470)), arrayOf<IIngredient>(iItemStack6, iItemStack, iItemStack6)), null)
        MineTweakerAPI.recipes.addShaped(iItemStack12, arrayOf(arrayOf(iOreDictEntry3, ItemBracketHandler.getItem("TConstruct:chiselHead", 2), iOreDictEntry2), arrayOf(iItemStack7, OreBracketHandler.getOre("stickAnyIron"), iItemStack7), arrayOf(iItemStack, OreBracketHandler.getOre("stickAnyIron"), iItemStack)), null)
        MineTweakerAPI.recipes.addShaped(iItemStack13, arrayOf(arrayOf(iOreDictEntry3, ItemBracketHandler.getItem("gregtech:gt.metaitem.02", 5032), iOreDictEntry2), arrayOf(iItemStack7, OreBracketHandler.getOre("stickAnyIron"), iItemStack7), arrayOf(iItemStack, OreBracketHandler.getOre("stickAnyIron"), iItemStack)), null)
        MineTweakerAPI.recipes.addShaped(iItemStack3, arrayOf(arrayOf<IIngredient>(iItemStack7, iItemStack2, iItemStack7), arrayOf<IIngredient>(iItemStack2, iItemStack4, iItemStack2), arrayOf(iItemStack7, iOreDictEntry3, iItemStack7)), null)
        MineTweakerAPI.recipes.addShaped(iItemStack14, arrayOf(arrayOf(iItemStack7, iOreDictEntry3, iItemStack7), arrayOf<IIngredient>(iItemStack, iItemStack15, iItemStack), arrayOf(iItemStack, iOreDictEntry8, iItemStack)), null)
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("CarpentersBlocks:itemCarpentersBed", 0), arrayOf(arrayOf<IIngredient>(ItemBracketHandler.getItem("minecraft:carpet", 32767), ItemBracketHandler.getItem("minecraft:carpet", 32767), ItemBracketHandler.getItem("minecraft:carpet", 32767)), arrayOf<IIngredient>(iItemStack, iItemStack, iItemStack), arrayOf(ItemBracketHandler.getItem("CarpentersBlocks:blockCarpentersBarrier", 0), OreBracketHandler.getOre("craftingToolSoftHammer"), ItemBracketHandler.getItem("CarpentersBlocks:blockCarpentersBarrier", 0))), null)
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("CarpentersBlocks:blockCarpentersTorch", 0).amount(2), arrayOf(arrayOf<IIngredient>(ItemBracketHandler.getItem("minecraft:torch", 0), iItemStack, ItemBracketHandler.getItem("minecraft:torch", 0))), null)
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("CarpentersBlocks:blockCarpentersGarageDoor", 0).amount(5), arrayOf(arrayOf(iItemStack, OreBracketHandler.getOre("ringIron"), iItemStack), arrayOf(OreBracketHandler.getOre("ringIron"), iItemStack, OreBracketHandler.getOre("ringIron")), arrayOf(iItemStack, OreBracketHandler.getOre("ringIron"), iItemStack)), null)
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("CarpentersBlocks:blockCarpentersLadder", 0), arrayOf(arrayOf<IIngredient>(iItemStack, ItemBracketHandler.getItem("minecraft:ladder", 0), iItemStack), arrayOf(iItemStack6, iOreDictEntry3, iItemStack6)), null)
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("CarpentersBlocks:blockCarpentersBarrier", 0), arrayOf(arrayOf(iItemStack, OreBracketHandler.getOre("fenceWood"), iItemStack), arrayOf(iItemStack6, iOreDictEntry3, iItemStack6)), null)
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("CarpentersBlocks:blockCarpentersPressurePlate", 0).amount(2), arrayOf(arrayOf(iItemStack6, iOreDictEntry4, iItemStack6), arrayOf(iItemStack, OreBracketHandler.getOre("springAnyIron"), iItemStack), arrayOf(iItemStack6, iOreDictEntry3, iItemStack6)), null)
        MineTweakerAPI.recipes.addShapeless(ItemBracketHandler.getItem("CarpentersBlocks:blockCarpentersButton", 0), arrayOf(iOreDictEntry2, ItemBracketHandler.getItem("CarpentersBlocks:blockCarpentersPressurePlate", 0)), null)
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("CarpentersBlocks:blockCarpentersFlowerPot", 0), arrayOf(arrayOf<IIngredient?>(iItemStack, ItemBracketHandler.getItem("minecraft:flower_pot", 0), iItemStack), arrayOf<IIngredient?>(null, iItemStack, null)), null)
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("CarpentersBlocks:blockCarpentersGate", 0), arrayOf(arrayOf<IIngredient>(iItemStack, ItemBracketHandler.getItem("minecraft:fence_gate", 0), iItemStack), arrayOf(iItemStack6, iOreDictEntry3, iItemStack6)), null)
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("CarpentersBlocks:blockCarpentersHatch", 0), arrayOf(arrayOf<IIngredient>(iItemStack, ItemBracketHandler.getItem("minecraft:trapdoor", 0), iItemStack), arrayOf(iItemStack6, iOreDictEntry3, iItemStack6)), null)
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("CarpentersBlocks:blockCarpentersLever", 0), arrayOf(arrayOf<IIngredient?>(iItemStack, ItemBracketHandler.getItem("minecraft:lever", 0), iItemStack6), arrayOf<IIngredient?>(null, iOreDictEntry3, null)), null)
        MineTweakerAPI.recipes.addShapeless(ItemBracketHandler.getItem("CarpentersBlocks:blockCarpentersSlope", 0).amount(2), arrayOf(ItemBracketHandler.getItem("CarpentersBlocks:blockCarpentersBlock", 0), iOreDictEntry2), null)
        MineTweakerAPI.recipes.addShapeless(ItemBracketHandler.getItem("CarpentersBlocks:blockCarpentersStairs", 0), arrayOf(iOreDictEntry2, ItemBracketHandler.getItem("CarpentersBlocks:blockCarpentersSlope", 0)), null)
        MineTweakerAPI.recipes.addShapeless(ItemBracketHandler.getItem("CarpentersBlocks:itemCarpentersTile", 0), arrayOf(ItemBracketHandler.getItem("CarpentersBlocks:blockCarpentersPressurePlate", 0), OreBracketHandler.getOre("craftingToolRollingPin"), OreBracketHandler.getOre("itemClay")), null)
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("CarpentersBlocks:itemCarpentersDoor", 0), arrayOf(arrayOf<IIngredient>(iItemStack, ItemBracketHandler.getItem("minecraft:wooden_door", 0), iItemStack), arrayOf(iItemStack6, iOreDictEntry3, iItemStack6)), null)
        Assembler.addRecipe(iItemStack.amount(4), ItemBracketHandler.getItem("gregtech:gt.blockmachines", 4905).amount(2), iItemStack6.amount(2), 100, LLV)
        Assembler.addRecipe(iItemStack.amount(8), ItemBracketHandler.getItem("gregtech:gt.blockmachines", 4905).amount(3), iItemStack7, 100, LV)
        Assembler.addRecipe(iItemStack.amount(12), ItemBracketHandler.getItem("gregtech:gt.blockmachines", 4905).amount(3), iItemStack8, 100, LMV)
        Assembler.addRecipe(iItemStack.amount(16), ItemBracketHandler.getItem("gregtech:gt.blockmachines", 4905).amount(3), iItemStack9, 100, LMV)
        Assembler.addRecipe(iItemStack.amount(20), ItemBracketHandler.getItem("gregtech:gt.blockmachines", 4905).amount(3), iItemStack10, 100, LMV)
        Assembler.addRecipe(iItemStack.amount(24), ItemBracketHandler.getItem("gregtech:gt.blockmachines", 4905).amount(3), iItemStack11, 100, LMV)
        Assembler.addRecipe(ItemBracketHandler.getItem("CarpentersBlocks:blockCarpentersBarrier", 0).amount(2), ItemBracketHandler.getItem("minecraft:fence", 0), iItemStack, 200, LLV)
        Assembler.addRecipe(iItemStack2, iItemStack, ItemBracketHandler.getItem("gregtech:gt.metaitem.02", 32470), 100, LLV)
        Assembler.addRecipe(ItemBracketHandler.getItem("CarpentersBlocks:blockCarpentersFlowerPot", 0), iItemStack, ItemBracketHandler.getItem("minecraft:flower_pot", 0), 100, LLV)
        Assembler.addRecipe(ItemBracketHandler.getItem("CarpentersBlocks:blockCarpentersGarageDoor", 0).amount(2), iItemStack, ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 28032), 150, LLV)
        Assembler.addRecipe(ItemBracketHandler.getItem("CarpentersBlocks:blockCarpentersGarageDoor", 0).amount(4), iItemStack, ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 28305), 300, LLV)
        Assembler.addRecipe(ItemBracketHandler.getItem("CarpentersBlocks:blockCarpentersGate", 0), ItemBracketHandler.getItem("minecraft:fence_gate", 0), iItemStack, 100, LLV)
        Assembler.addRecipe(ItemBracketHandler.getItem("CarpentersBlocks:blockCarpentersHatch", 0), iItemStack, ItemBracketHandler.getItem("minecraft:trapdoor", 0), 100, LLV)
        Assembler.addRecipe(ItemBracketHandler.getItem("CarpentersBlocks:blockCarpentersLadder", 0), iItemStack, ItemBracketHandler.getItem("minecraft:ladder", 0), 100, LLV)
        Assembler.addRecipe(ItemBracketHandler.getItem("CarpentersBlocks:blockCarpentersLever", 0), iItemStack, ItemBracketHandler.getItem("minecraft:lever", 0), 50, LLV)
        Assembler.addRecipe(iItemStack3, iItemStack2.amount(3), iItemStack4, 300, LV)
        Assembler.addRecipe(ItemBracketHandler.getItem("CarpentersBlocks:blockCarpentersTorch", 0).amount(10), iItemStack, ItemBracketHandler.getItem("minecraft:torch", 0).amount(10), 100, LLV)
        Assembler.addRecipe(iItemStack12, iItemStack, ItemBracketHandler.getItem("TConstruct:chiselHead", 2), 200, LV)
        Assembler.addRecipe(iItemStack13, iItemStack, ItemBracketHandler.getItem("gregtech:gt.metaitem.02", 5032), 200, LV)
        Assembler.addRecipe(ItemBracketHandler.getItem("CarpentersBlocks:itemCarpentersTile", 0).amount(2), ItemBracketHandler.getItem("CarpentersBlocks:blockCarpentersPressurePlate", 0), ItemBracketHandler.getItem("minecraft:clay_ball", 0), 50, LLV)
        Assembler.addRecipe(ItemBracketHandler.getItem("CarpentersBlocks:itemCarpentersDoor", 0), iItemStack, ItemBracketHandler.getItem("minecraft:wooden_door", 0), 150, LLV)
        Assembler.addRecipe(ItemBracketHandler.getItem("CarpentersBlocks:blockCarpentersPressurePlate", 0).amount(2), iItemStack.amount(2), ItemBracketHandler.getItem("gregtech:gt.metaitem.02", 24032), 100, ULV)
        Assembler.addRecipe(ItemBracketHandler.getItem("CarpentersBlocks:blockCarpentersPressurePlate", 0).amount(2), iItemStack.amount(2), ItemBracketHandler.getItem("gregtech:gt.metaitem.02", 24304), 100, ULV)
        CuttingSaw.addRecipe(ItemBracketHandler.getItem("CarpentersBlocks:blockCarpentersButton", 0).amount(4), null, ItemBracketHandler.getItem("CarpentersBlocks:blockCarpentersPressurePlate", 0), LiquidBracketHandler.getLiquid("water").withAmount(20), 100, LV)
        CuttingSaw.addRecipe(ItemBracketHandler.getItem("CarpentersBlocks:blockCarpentersButton", 0).amount(4), null, ItemBracketHandler.getItem("CarpentersBlocks:blockCarpentersPressurePlate", 0), LiquidBracketHandler.getLiquid("ic2distilledwater").withAmount(10), 100, LV)
        CuttingSaw.addRecipe(ItemBracketHandler.getItem("CarpentersBlocks:blockCarpentersButton", 0).amount(4), null, ItemBracketHandler.getItem("CarpentersBlocks:blockCarpentersPressurePlate", 0), LiquidBracketHandler.getLiquid("lubricant").withAmount(2), 50, LV)
        CuttingSaw.addRecipe(ItemBracketHandler.getItem("CarpentersBlocks:blockCarpentersStairs", 0).amount(4), null, ItemBracketHandler.getItem("CarpentersBlocks:blockCarpentersSlope", 0), LiquidBracketHandler.getLiquid("water").withAmount(20), 100, LV)
        CuttingSaw.addRecipe(ItemBracketHandler.getItem("CarpentersBlocks:blockCarpentersStairs", 0).amount(4), null, ItemBracketHandler.getItem("CarpentersBlocks:blockCarpentersSlope", 0), LiquidBracketHandler.getLiquid("ic2distilledwater").withAmount(10), 100, LV)
        CuttingSaw.addRecipe(ItemBracketHandler.getItem("CarpentersBlocks:blockCarpentersStairs", 0).amount(4), null, ItemBracketHandler.getItem("CarpentersBlocks:blockCarpentersSlope", 0), LiquidBracketHandler.getLiquid("lubricant").withAmount(2), 50, LV)
        CuttingSaw.addRecipe(ItemBracketHandler.getItem("CarpentersBlocks:blockCarpentersSlope", 0).amount(4), null, ItemBracketHandler.getItem("CarpentersBlocks:blockCarpentersBlock", 0), LiquidBracketHandler.getLiquid("water").withAmount(20), 100, LLV)
        CuttingSaw.addRecipe(ItemBracketHandler.getItem("CarpentersBlocks:blockCarpentersSlope", 0).amount(4), null, ItemBracketHandler.getItem("CarpentersBlocks:blockCarpentersBlock", 0), LiquidBracketHandler.getLiquid("ic2distilledwater").withAmount(10), 100, LLV)
        CuttingSaw.addRecipe(ItemBracketHandler.getItem("CarpentersBlocks:blockCarpentersSlope", 0).amount(4), null, ItemBracketHandler.getItem("CarpentersBlocks:blockCarpentersBlock", 0), LiquidBracketHandler.getLiquid("lubricant").withAmount(2), 50, LLV)
    }
}