package com.github.GTNH2Mega.fromScripts

import com.github.GTNH2Mega.VoltageLevels.HV
import com.github.GTNH2Mega.VoltageLevels.LV
import java.lang.Runnable
import minetweaker.api.item.IItemStack
import minetweaker.mc1710.brackets.ItemBracketHandler
import minetweaker.api.oredict.IOreDictEntry
import minetweaker.mc1710.brackets.OreBracketHandler
import minetweaker.MineTweakerAPI
import minetweaker.api.item.IIngredient
import gttweaker.mods.gregtech.machines.Assembler
import modtweaker2.mods.chisel.handlers.Groups

class Chisel : Runnable {
    override fun run() {
        Groups.addGroup("glasswork")
        val iItemStack = ItemBracketHandler.getItem("chisel:chisel", 0)
        val iItemStack2 = ItemBracketHandler.getItem("chisel:obsidianChisel", 0)
        val iItemStack3 = ItemBracketHandler.getItem("chisel:diamondChisel", 0)
        val iItemStack4 = ItemBracketHandler.getItem("chisel:netherStarChisel", 0)
        val iItemStack5 = ItemBracketHandler.getItem("chisel:cloudinabottle", 0)
        val iOreDictEntry2 = OreBracketHandler.getOre("plateAnyIron")
        val iOreDictEntry4 = OreBracketHandler.getOre("plateObsidian")
        val iOreDictEntry6 = OreBracketHandler.getOre("screwAnyIron")
        val iOreDictEntry7 = OreBracketHandler.getOre("screwWroughtIron")
        val iOreDictEntry8 = OreBracketHandler.getOre("screwSteel")
        val iOreDictEntry10 = OreBracketHandler.getOre("stickSteel")
        val iOreDictEntry11 = OreBracketHandler.getOre("stickWood")
        val iOreDictEntry12 = OreBracketHandler.getOre("stickWroughtIron")
        val iOreDictEntry15 = OreBracketHandler.getOre("craftingToolHardHammer")
        val iOreDictEntry16 = OreBracketHandler.getOre("craftingToolScrewdriver")
        MineTweakerAPI.recipes.remove(iItemStack)
        MineTweakerAPI.recipes.remove(iItemStack2)
        MineTweakerAPI.recipes.remove(iItemStack3)
        MineTweakerAPI.recipes.remove(iItemStack4)
        MineTweakerAPI.recipes.remove(iItemStack5)
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("chisel:ballomoss", 0))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("chisel:smashingrock", 0))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("chisel:autoChisel", 0))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("chisel:upgrade", 0))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("chisel:upgrade", 1))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("chisel:upgrade", 2))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("chisel:upgrade", 3))
        Groups.removeGroup("cobblestone")
        Groups.removeGroup("glowstone")
        Groups.removeVariation(ItemBracketHandler.getItem("minecraft:stonebrick", 1))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("chisel:voidstone2", 0))
        MineTweakerAPI.furnace.remove(ItemBracketHandler.getItem("chisel:concrete", 0), null)
        Groups.removeVariation(ItemBracketHandler.getItem("minecraft:torch", 0))
        MineTweakerAPI.recipes.addShaped(iItemStack, arrayOf(arrayOf<IIngredient>(iOreDictEntry15, iOreDictEntry2, iOreDictEntry2), arrayOf<IIngredient>(iOreDictEntry6, iOreDictEntry11, iOreDictEntry2), arrayOf<IIngredient>(iOreDictEntry11, iOreDictEntry6, iOreDictEntry16)), null)
        MineTweakerAPI.recipes.addShaped(iItemStack, arrayOf(arrayOf<IIngredient>(iOreDictEntry16, iOreDictEntry2, iOreDictEntry2), arrayOf<IIngredient>(iOreDictEntry6, iOreDictEntry11, iOreDictEntry2), arrayOf<IIngredient>(iOreDictEntry11, iOreDictEntry6, iOreDictEntry15)), null)
        MineTweakerAPI.recipes.addShaped(iItemStack2, arrayOf(arrayOf<IIngredient>(iOreDictEntry15, iOreDictEntry4, iOreDictEntry4), arrayOf<IIngredient>(iOreDictEntry7, iOreDictEntry12, iOreDictEntry4), arrayOf<IIngredient>(iOreDictEntry12, iOreDictEntry7, iOreDictEntry16)), null)
        MineTweakerAPI.recipes.addShaped(iItemStack2, arrayOf(arrayOf<IIngredient>(iOreDictEntry16, iOreDictEntry4, iOreDictEntry4), arrayOf<IIngredient>(iOreDictEntry7, iOreDictEntry12, iOreDictEntry4), arrayOf<IIngredient>(iOreDictEntry12, iOreDictEntry7, iOreDictEntry15)), null)
        MineTweakerAPI.recipes.addShaped(iItemStack3, arrayOf(arrayOf<IIngredient>(iOreDictEntry15, OreBracketHandler.getOre("plateDiamond"), OreBracketHandler.getOre("plateDiamond")), arrayOf<IIngredient>(iOreDictEntry8, iOreDictEntry10, OreBracketHandler.getOre("plateDiamond")), arrayOf<IIngredient>(iOreDictEntry10, iOreDictEntry8, iOreDictEntry16)), null)
        MineTweakerAPI.recipes.addShaped(iItemStack3, arrayOf(arrayOf<IIngredient>(iOreDictEntry16, OreBracketHandler.getOre("plateDiamond"), OreBracketHandler.getOre("plateDiamond")), arrayOf<IIngredient>(iOreDictEntry8, iOreDictEntry10, OreBracketHandler.getOre("plateDiamond")), arrayOf<IIngredient>(iOreDictEntry10, iOreDictEntry8, iOreDictEntry15)), null)
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("chisel:autoChisel", 0), arrayOf(arrayOf<IIngredient>(iOreDictEntry8, OreBracketHandler.getOre("ringWoodSealed"), iOreDictEntry8), arrayOf<IIngredient>(ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32630), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32744), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32650)), arrayOf(iOreDictEntry16, ItemBracketHandler.getItem("IronChest:BlockIronChest", 0), iOreDictEntry15)), null)
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("chisel:upgrade", 0), arrayOf(arrayOf<IIngredient>(iOreDictEntry8, OreBracketHandler.getOre("plateEmerald"), iOreDictEntry8), arrayOf<IIngredient>(OreBracketHandler.getOre("plateEmerald"), OreBracketHandler.getOre("circuitBasic"), OreBracketHandler.getOre("plateEmerald")), arrayOf(OreBracketHandler.getOre("wireGt01RedAlloy"), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32630), OreBracketHandler.getOre("wireGt01RedAlloy"))), null)
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("chisel:upgrade", 1), arrayOf(arrayOf<IIngredient>(iOreDictEntry8, OreBracketHandler.getOre("plateEmerald"), iOreDictEntry8), arrayOf<IIngredient>(OreBracketHandler.getOre("plateEmerald"), OreBracketHandler.getOre("circuitBasic"), OreBracketHandler.getOre("plateEmerald")), arrayOf(OreBracketHandler.getOre("wireGt01RedAlloy"), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32650), OreBracketHandler.getOre("wireGt01RedAlloy"))), null)
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("chisel:upgrade", 2), arrayOf(arrayOf<IIngredient>(iOreDictEntry8, OreBracketHandler.getOre("plateEmerald"), iOreDictEntry8), arrayOf<IIngredient>(OreBracketHandler.getOre("plateEmerald"), OreBracketHandler.getOre("circuitBasic"), OreBracketHandler.getOre("plateEmerald")), arrayOf(OreBracketHandler.getOre("wireGt01RedAlloy"), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32744), OreBracketHandler.getOre("wireGt01RedAlloy"))), null)
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("chisel:upgrade", 3), arrayOf(arrayOf<IIngredient>(iOreDictEntry8, OreBracketHandler.getOre("plateEmerald"), iOreDictEntry8), arrayOf<IIngredient>(OreBracketHandler.getOre("plateEmerald"), OreBracketHandler.getOre("circuitBasic"), OreBracketHandler.getOre("plateEmerald")), arrayOf(OreBracketHandler.getOre("wireGt01RedAlloy"), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32600), OreBracketHandler.getOre("wireGt01RedAlloy"))), null)
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("chisel:mossy_templeblock", 0), arrayOf(arrayOf<IIngredient>(ItemBracketHandler.getItem("BiomesOPlenty:moss", 0), ItemBracketHandler.getItem("BiomesOPlenty:moss", 0), ItemBracketHandler.getItem("BiomesOPlenty:moss", 0)), arrayOf<IIngredient>(ItemBracketHandler.getItem("BiomesOPlenty:moss", 0), ItemBracketHandler.getItem("chisel:templeblock", 0), ItemBracketHandler.getItem("BiomesOPlenty:moss", 0)), arrayOf<IIngredient>(ItemBracketHandler.getItem("BiomesOPlenty:moss", 0), ItemBracketHandler.getItem("BiomesOPlenty:moss", 0), ItemBracketHandler.getItem("BiomesOPlenty:moss", 0))), null)
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("chisel:voidstone2", 0).amount(8), arrayOf(arrayOf<IIngredient>(ItemBracketHandler.getItem("chisel:voidstone", 0), ItemBracketHandler.getItem("chisel:voidstone", 0), ItemBracketHandler.getItem("chisel:voidstone", 0)), arrayOf(ItemBracketHandler.getItem("chisel:voidstone", 0), OreBracketHandler.getOre("dustGlowstone"), ItemBracketHandler.getItem("chisel:voidstone", 0)), arrayOf<IIngredient>(ItemBracketHandler.getItem("chisel:voidstone", 0), ItemBracketHandler.getItem("chisel:voidstone", 0), ItemBracketHandler.getItem("chisel:voidstone", 0))), null)
        Assembler.addRecipe(iItemStack, ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 17032).amount(2), ItemBracketHandler.getItem("minecraft:stick", 0).amount(2), 300, LV)
        Assembler.addRecipe(iItemStack2, ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 17804).amount(2), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 23304).amount(2), 400, LV)
        Assembler.addRecipe(iItemStack3, ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 17500).amount(2), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 23305).amount(2), 600, LV)
        Assembler.addRecipe(iItemStack4, ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 22395).amount(2), ItemBracketHandler.getItem("gregtech:gt.metaitem.02", 22371).amount(2), 24000, HV)
        Groups.addGroup("CobblestoneBricks")
        Groups.addVariation("CobblestoneBricks", ItemBracketHandler.getItem("minecraft:cobblestone", 0))
        Groups.addVariation("CobblestoneBricks", ItemBracketHandler.getItem("chisel:cobblestone", 1))
        Groups.addVariation("CobblestoneBricks", ItemBracketHandler.getItem("chisel:cobblestone", 2))
        Groups.addVariation("CobblestoneBricks", ItemBracketHandler.getItem("chisel:cobblestone", 3))
        Groups.addVariation("CobblestoneBricks", ItemBracketHandler.getItem("chisel:cobblestone", 4))
        Groups.addVariation("CobblestoneBricks", ItemBracketHandler.getItem("chisel:cobblestone", 5))
        Groups.addVariation("CobblestoneBricks", ItemBracketHandler.getItem("chisel:cobblestone", 6))
        Groups.addVariation("CobblestoneBricks", ItemBracketHandler.getItem("chisel:cobblestone", 7))
        Groups.addVariation("CobblestoneBricks", ItemBracketHandler.getItem("chisel:cobblestone", 8))
        Groups.addVariation("CobblestoneBricks", ItemBracketHandler.getItem("chisel:cobblestone", 9))
        Groups.addVariation("CobblestoneBricks", ItemBracketHandler.getItem("chisel:cobblestone", 10))
        Groups.addVariation("CobblestoneBricks", ItemBracketHandler.getItem("chisel:cobblestone", 11))
        Groups.addVariation("CobblestoneBricks", ItemBracketHandler.getItem("chisel:cobblestone", 12))
        Groups.addVariation("CobblestoneBricks", ItemBracketHandler.getItem("chisel:cobblestone", 13))
        Groups.addVariation("CobblestoneBricks", ItemBracketHandler.getItem("chisel:cobblestone", 14))
        Groups.addVariation("CobblestoneBricks", ItemBracketHandler.getItem("chisel:cobblestone", 15))
        Groups.addVariation("glasswork", ItemBracketHandler.getItem("minecraft:glass", 0))
        Groups.addVariation("glasswork", ItemBracketHandler.getItem("chisel:glass", 1))
        Groups.addVariation("glasswork", ItemBracketHandler.getItem("chisel:glass", 2))
        Groups.addVariation("glasswork", ItemBracketHandler.getItem("chisel:glass", 3))
        Groups.addVariation("glasswork", ItemBracketHandler.getItem("chisel:glass", 4))
        Groups.addVariation("glasswork", ItemBracketHandler.getItem("chisel:glass", 5))
        Groups.addVariation("glasswork", ItemBracketHandler.getItem("chisel:glass", 6))
        Groups.addVariation("glasswork", ItemBracketHandler.getItem("chisel:glass", 7))
        Groups.addVariation("glasswork", ItemBracketHandler.getItem("chisel:glass", 8))
        Groups.addVariation("glasswork", ItemBracketHandler.getItem("chisel:glass", 9))
        Groups.addVariation("glasswork", ItemBracketHandler.getItem("chisel:glass", 10))
        Groups.addVariation("glasswork", ItemBracketHandler.getItem("chisel:glass", 11))
        Groups.addVariation("glasswork", ItemBracketHandler.getItem("chisel:glass", 12))
        Groups.addVariation("glasswork", ItemBracketHandler.getItem("chisel:glass", 13))
        Groups.addVariation("glasswork", ItemBracketHandler.getItem("chisel:glass", 14))
        Groups.addVariation("glasswork", ItemBracketHandler.getItem("chisel:glass", 15))
        Groups.addVariation("glasswork", ItemBracketHandler.getItem("chisel:glass2", 0))
        Groups.addVariation("glasswork", ItemBracketHandler.getItem("TConstruct:GlassBlock", 0))
        Groups.addVariation("glasswork", ItemBracketHandler.getItem("EnderIO:blockFusedQuartz", 1))
        Groups.addVariation("glass", ItemBracketHandler.getItem("TConstruct:GlassBlock", 0))
        Groups.addVariation("cloud", ItemBracketHandler.getItem("Natura:Cloud", 0))
        Groups.addVariation("marble", ItemBracketHandler.getItem("Railcraft:cube", 7))
        Groups.addVariation("marble", ItemBracketHandler.getItem("gregtech:gt.blockstones", 0))
        Groups.addVariation("marble", ItemBracketHandler.getItem("gregtech:gt.blockstones", 1))
        Groups.addVariation("marble", ItemBracketHandler.getItem("gregtech:gt.blockstones", 2))
        Groups.addVariation("marble", ItemBracketHandler.getItem("gregtech:gt.blockstones", 3))
        Groups.addVariation("marble", ItemBracketHandler.getItem("gregtech:gt.blockstones", 4))
        Groups.addVariation("marble", ItemBracketHandler.getItem("gregtech:gt.blockstones", 5))
        Groups.addVariation("marble", ItemBracketHandler.getItem("gregtech:gt.blockstones", 6))
        Groups.addVariation("marble", ItemBracketHandler.getItem("gregtech:gt.blockstones", 7))
        Groups.addVariation("RCAbyssalBlock", ItemBracketHandler.getItem("Railcraft:cube", 6))
        Groups.addVariation("RCAbyssalBlock", ItemBracketHandler.getItem("gregtech:gt.blockgranites", 0))
        Groups.addVariation("RCAbyssalBlock", ItemBracketHandler.getItem("gregtech:gt.blockgranites", 1))
        Groups.addVariation("RCAbyssalBlock", ItemBracketHandler.getItem("gregtech:gt.blockgranites", 2))
        Groups.addVariation("RCAbyssalBlock", ItemBracketHandler.getItem("gregtech:gt.blockgranites", 3))
        Groups.addVariation("RCAbyssalBlock", ItemBracketHandler.getItem("gregtech:gt.blockgranites", 4))
        Groups.addVariation("RCAbyssalBlock", ItemBracketHandler.getItem("gregtech:gt.blockgranites", 5))
        Groups.addVariation("RCAbyssalBlock", ItemBracketHandler.getItem("gregtech:gt.blockgranites", 6))
        Groups.addVariation("RCAbyssalBlock", ItemBracketHandler.getItem("gregtech:gt.blockgranites", 7))
        Groups.addGroup("basalt")
        Groups.addVariation("basalt", ItemBracketHandler.getItem("gregtech:gt.blockstones", 8))
        Groups.addVariation("basalt", ItemBracketHandler.getItem("gregtech:gt.blockstones", 9))
        Groups.addVariation("basalt", ItemBracketHandler.getItem("gregtech:gt.blockstones", 10))
        Groups.addVariation("basalt", ItemBracketHandler.getItem("gregtech:gt.blockstones", 11))
        Groups.addVariation("basalt", ItemBracketHandler.getItem("gregtech:gt.blockstones", 12))
        Groups.addVariation("basalt", ItemBracketHandler.getItem("gregtech:gt.blockstones", 13))
        Groups.addVariation("basalt", ItemBracketHandler.getItem("gregtech:gt.blockstones", 14))
        Groups.addVariation("basalt", ItemBracketHandler.getItem("gregtech:gt.blockstones", 15))
        Groups.addVariation("basalt", ItemBracketHandler.getItem("ProjRed|Exploration:projectred.exploration.stone", 2))
        Groups.addVariation("basalt", ItemBracketHandler.getItem("ProjRed|Exploration:projectred.exploration.stone", 3))
        Groups.addVariation("basalt", ItemBracketHandler.getItem("ProjRed|Exploration:projectred.exploration.stone", 4))
        Groups.addGroup("redgranite")
        Groups.addVariation("redgranite", ItemBracketHandler.getItem("gregtech:gt.blockgranites", 8))
        Groups.addVariation("redgranite", ItemBracketHandler.getItem("gregtech:gt.blockgranites", 9))
        Groups.addVariation("redgranite", ItemBracketHandler.getItem("gregtech:gt.blockgranites", 10))
        Groups.addVariation("redgranite", ItemBracketHandler.getItem("gregtech:gt.blockgranites", 11))
        Groups.addVariation("redgranite", ItemBracketHandler.getItem("gregtech:gt.blockgranites", 12))
        Groups.addVariation("redgranite", ItemBracketHandler.getItem("gregtech:gt.blockgranites", 13))
        Groups.addVariation("redgranite", ItemBracketHandler.getItem("gregtech:gt.blockgranites", 14))
        Groups.addVariation("redgranite", ItemBracketHandler.getItem("gregtech:gt.blockgranites", 15))
        Groups.addVariation("limestone", ItemBracketHandler.getItem("BiomesOPlenty:rocks", 0))
        Groups.addVariation("amber", ItemBracketHandler.getItem("gregtech:gt.blockgem1", 1))
        Groups.addVariation("amber", ItemBracketHandler.getItem("BiomesOPlenty:gemOre", 15))
        Groups.addGroup("endstone")
        Groups.addVariation("endstone", ItemBracketHandler.getItem("minecraft:end_stone", 0))
        Groups.addVariation("endstone", ItemBracketHandler.getItem("chisel:end_Stone", 1))
        Groups.addVariation("endstone", ItemBracketHandler.getItem("chisel:end_Stone", 2))
        Groups.addVariation("endstone", ItemBracketHandler.getItem("chisel:end_Stone", 3))
        Groups.addVariation("endstone", ItemBracketHandler.getItem("chisel:end_Stone", 4))
        Groups.addVariation("endstone", ItemBracketHandler.getItem("chisel:end_Stone", 5))
        Groups.addVariation("endstone", ItemBracketHandler.getItem("chisel:end_Stone", 6))
        Groups.addVariation("endstone", ItemBracketHandler.getItem("chisel:end_Stone", 7))
        Groups.addVariation("endstone", ItemBracketHandler.getItem("chisel:end_Stone", 8))
        Groups.addVariation("endstone", ItemBracketHandler.getItem("chisel:end_Stone", 9))
        Groups.addVariation("endstone", ItemBracketHandler.getItem("chisel:end_Stone", 10))
        Groups.addVariation("endstone", ItemBracketHandler.getItem("chisel:end_Stone", 11))
        Groups.addVariation("endstone", ItemBracketHandler.getItem("chisel:end_Stone", 12))
        Groups.addVariation("endstone", ItemBracketHandler.getItem("chisel:end_Stone", 13))
        Groups.addVariation("endstone", ItemBracketHandler.getItem("TConstruct:decoration.multibrick", 12))
        Groups.addVariation("endstone", ItemBracketHandler.getItem("TConstruct:decoration.multibrickfancy", 12))
        Groups.addVariation("concrete", ItemBracketHandler.getItem("gregtech:gt.blockconcretes", 8))
        Groups.addGroup("glowstoneGTNH")
        Groups.addVariation("glowstoneGTNH", ItemBracketHandler.getItem("minecraft:glowstone", 0))
        Groups.addVariation("glowstoneGTNH", ItemBracketHandler.getItem("chisel:glowstone", 1))
        Groups.addVariation("glowstoneGTNH", ItemBracketHandler.getItem("chisel:glowstone", 2))
        Groups.addVariation("glowstoneGTNH", ItemBracketHandler.getItem("chisel:glowstone", 3))
        Groups.addVariation("glowstoneGTNH", ItemBracketHandler.getItem("chisel:glowstone", 4))
        Groups.addVariation("glowstoneGTNH", ItemBracketHandler.getItem("chisel:glowstone", 5))
        Groups.addVariation("glowstoneGTNH", ItemBracketHandler.getItem("chisel:glowstone", 6))
        Groups.addVariation("glowstoneGTNH", ItemBracketHandler.getItem("chisel:glowstone", 7))
        Groups.addVariation("glowstoneGTNH", ItemBracketHandler.getItem("chisel:glowstone", 8))
        Groups.addVariation("glowstoneGTNH", ItemBracketHandler.getItem("chisel:glowstone", 9))
        Groups.addVariation("glowstoneGTNH", ItemBracketHandler.getItem("chisel:glowstone", 10))
        Groups.addVariation("glowstoneGTNH", ItemBracketHandler.getItem("chisel:glowstone", 11))
        Groups.addVariation("glowstoneGTNH", ItemBracketHandler.getItem("chisel:glowstone", 12))
        Groups.addVariation("glowstoneGTNH", ItemBracketHandler.getItem("chisel:glowstone", 13))
        Groups.addVariation("glowstoneGTNH", ItemBracketHandler.getItem("chisel:glowstone", 14))
        Groups.addVariation("glowstoneGTNH", ItemBracketHandler.getItem("chisel:glowstone", 15))
        Groups.addVariation("torch", ItemBracketHandler.getItem("GalacticraftCore:tile.glowstoneTorch", 0))
        Groups.addVariation("aluminumblock", ItemBracketHandler.getItem("gregtech:gt.blockmetal1", 1))
        Groups.addGroup("searedStoneTCon")
        Groups.addVariation("searedStoneTCon", ItemBracketHandler.getItem("TConstruct:Smeltery", 4))
        Groups.addVariation("searedStoneTCon", ItemBracketHandler.getItem("TConstruct:Smeltery", 6))
        Groups.addVariation("searedStoneTCon", ItemBracketHandler.getItem("TConstruct:Smeltery", 11))
        Groups.addGroup("searedStoneNetherTCon")
        Groups.addVariation("searedStoneNetherTCon", ItemBracketHandler.getItem("TConstruct:SmelteryNether", 4))
        Groups.addVariation("searedStoneNetherTCon", ItemBracketHandler.getItem("TConstruct:SmelteryNether", 6))
        Groups.addVariation("searedStoneNetherTCon", ItemBracketHandler.getItem("TConstruct:SmelteryNether", 11))
        Groups.addGroup("searedBricksTCon")
        Groups.addVariation("searedBricksTCon", ItemBracketHandler.getItem("TConstruct:Smeltery", 2))
        Groups.addVariation("searedBricksTCon", ItemBracketHandler.getItem("TConstruct:Smeltery", 8))
        Groups.addVariation("searedBricksTCon", ItemBracketHandler.getItem("TConstruct:Smeltery", 9))
        Groups.addGroup("searedBricksNetherTCon")
        Groups.addVariation("searedBricksNetherTCon", ItemBracketHandler.getItem("TConstruct:SmelteryNether", 2))
        Groups.addVariation("searedBricksNetherTCon", ItemBracketHandler.getItem("TConstruct:SmelteryNether", 8))
        Groups.addVariation("searedBricksNetherTCon", ItemBracketHandler.getItem("TConstruct:SmelteryNether", 9))
        Groups.addGroup("speedBlockTCon")
        Groups.addVariation("speedBlockTCon", ItemBracketHandler.getItem("TConstruct:SpeedBlock", 0))
        Groups.addVariation("speedBlockTCon", ItemBracketHandler.getItem("TConstruct:SpeedBlock", 1))
        Groups.addGroup("brownStoneTCon")
        Groups.addVariation("brownStoneTCon", ItemBracketHandler.getItem("TConstruct:SpeedBlock", 2))
        Groups.addVariation("brownStoneTCon", ItemBracketHandler.getItem("TConstruct:SpeedBlock", 3))
        Groups.addVariation("brownStoneTCon", ItemBracketHandler.getItem("TConstruct:SpeedBlock", 4))
        Groups.addVariation("brownStoneTCon", ItemBracketHandler.getItem("TConstruct:SpeedBlock", 5))
        Groups.addVariation("brownStoneTCon", ItemBracketHandler.getItem("TConstruct:SpeedBlock", 6))
        Groups.addGroup("ironBricksTCon")
        Groups.addVariation("ironBricksTCon", ItemBracketHandler.getItem("TConstruct:decoration.multibrick", 4))
        Groups.addVariation("ironBricksTCon", ItemBracketHandler.getItem("TConstruct:decoration.multibrickfancy", 4))
        Groups.addGroup("goldBricksTCon")
        Groups.addVariation("goldBricksTCon", ItemBracketHandler.getItem("TConstruct:decoration.multibrick", 5))
        Groups.addVariation("goldBricksTCon", ItemBracketHandler.getItem("TConstruct:decoration.multibrickfancy", 5))
        Groups.addGroup("lapisBricksTCon")
        Groups.addVariation("lapisBricksTCon", ItemBracketHandler.getItem("TConstruct:decoration.multibrick", 6))
        Groups.addVariation("lapisBricksTCon", ItemBracketHandler.getItem("TConstruct:decoration.multibrickfancy", 6))
        Groups.addGroup("diamondBricksTCon")
        Groups.addVariation("diamondBricksTCon", ItemBracketHandler.getItem("TConstruct:decoration.multibrick", 7))
        Groups.addVariation("diamondBricksTCon", ItemBracketHandler.getItem("TConstruct:decoration.multibrickfancy", 7))
        Groups.addGroup("redstoneBricksTCon")
        Groups.addVariation("redstoneBricksTCon", ItemBracketHandler.getItem("TConstruct:decoration.multibrick", 8))
        Groups.addVariation("redstoneBricksTCon", ItemBracketHandler.getItem("TConstruct:decoration.multibrickfancy", 8))
        Groups.addGroup("boneBricksTCon")
        Groups.addVariation("boneBricksTCon", ItemBracketHandler.getItem("TConstruct:decoration.multibrick", 9))
        Groups.addVariation("boneBricksTCon", ItemBracketHandler.getItem("TConstruct:decoration.multibrickfancy", 9))
        Groups.addGroup("greenSlimeBricksTCon")
        Groups.addVariation("greenSlimeBricksTCon", ItemBracketHandler.getItem("TConstruct:decoration.multibrick", 10))
        Groups.addVariation("greenSlimeBricksTCon", ItemBracketHandler.getItem("TConstruct:decoration.multibrickfancy", 10))
        Groups.addGroup("blueSlimeBricksTCon")
        Groups.addVariation("blueSlimeBricksTCon", ItemBracketHandler.getItem("TConstruct:decoration.multibrick", 11))
        Groups.addVariation("blueSlimeBricksTCon", ItemBracketHandler.getItem("TConstruct:decoration.multibrickfancy", 11))
        Groups.addGroup("obsidianBricksTCon")
        Groups.addVariation("obsidianBricksTCon", ItemBracketHandler.getItem("TConstruct:decoration.multibrick", 13))
        Groups.addVariation("obsidianBricksTCon", ItemBracketHandler.getItem("TConstruct:decoration.multibrickfancy", 13))
        Groups.addGroup("alumiteBricksTCon")
        Groups.addVariation("alumiteBricksTCon", ItemBracketHandler.getItem("TConstruct:MetalBlock", 8))
        Groups.addVariation("alumiteBricksTCon", ItemBracketHandler.getItem("TConstruct:decoration.multibrickmetal", 0))
        Groups.addVariation("alumiteBricksTCon", ItemBracketHandler.getItem("TConstruct:decoration.multibrickmetal", 4))
        Groups.addGroup("arditeBricksTCon")
        Groups.addVariation("arditeBricksTCon", ItemBracketHandler.getItem("TConstruct:MetalBlock", 1))
        Groups.addVariation("arditeBricksTCon", ItemBracketHandler.getItem("TConstruct:decoration.multibrickmetal", 1))
        Groups.addVariation("arditeBricksTCon", ItemBracketHandler.getItem("TConstruct:decoration.multibrickmetal", 5))
        Groups.addGroup("cobaltBricksTCon")
        Groups.addVariation("cobaltBricksTCon", ItemBracketHandler.getItem("TConstruct:MetalBlock", 0))
        Groups.addVariation("cobaltBricksTCon", ItemBracketHandler.getItem("TConstruct:decoration.multibrickmetal", 2))
        Groups.addVariation("cobaltBricksTCon", ItemBracketHandler.getItem("TConstruct:decoration.multibrickmetal", 6))
        Groups.addGroup("manyullynBricksTCon")
        Groups.addVariation("manyullynBricksTCon", ItemBracketHandler.getItem("TConstruct:MetalBlock", 2))
        Groups.addVariation("manyullynBricksTCon", ItemBracketHandler.getItem("TConstruct:decoration.multibrickmetal", 3))
        Groups.addVariation("manyullynBricksTCon", ItemBracketHandler.getItem("TConstruct:decoration.multibrickmetal", 7))
        Groups.addGroup("brown_mushroom")
        Groups.addGroup("red_mushroom")
        for (i in 0..15) {
            Groups.addVariation("brown_mushroom", ItemBracketHandler.getItem("minecraft:brown_mushroom_block", 0).definition.makeStack(i))
            Groups.addVariation("red_mushroom", ItemBracketHandler.getItem("minecraft:red_mushroom_block", 0).definition.makeStack(i))
        }
    }
}