package com.github.GTNH2Mega.fromScripts;
import java.util.HashMap;
import minetweaker.MineTweakerAPI;
import minetweaker.api.data.IData;
import minetweaker.api.item.IIngredient;
import minetweaker.api.item.IItemStack;
import minetweaker.api.item.IngredientCondition;
import minetweaker.expand.ExpandAnyArray;
import minetweaker.expand.ExpandAnyDict;
import minetweaker.expand.ExpandInt;
import minetweaker.expand.ExpandShort;
import minetweaker.expand.ExpandString;
import minetweaker.mc1710.brackets.ItemBracketHandler;
import static com.github.GTNH2Mega.VoltageLevels.*;
public class EnhancedLoot_Bags
implements Runnable {
    public void run() {
        IItemStack iItemStack = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)1);
        HashMap<String, IData> hashMap = new HashMap<String, IData>();
        IData[] arriData = new IData[1];
        HashMap<String, IData> hashMap2 = new HashMap<String, IData>();
        hashMap2.put("lvl", ExpandShort.asNBT((short)3));
        hashMap2.put("id", ExpandShort.asNBT((short)35));
        arriData[0] = ExpandAnyDict.asData(hashMap2);
        hashMap.put("ench", ExpandAnyArray.asData((IData[])arriData));
        hashMap.put("RepairCost", ExpandInt.toData((int)2));
        IItemStack iItemStack2 = iItemStack.withTag(ExpandAnyDict.asData(hashMap));
        IIngredient[] arriIngredient = new IIngredient[3];
        arriIngredient[0] = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)1);
        IItemStack iItemStack3 = ItemBracketHandler.getItem((String)"minecraft:enchanted_book", (int)0);
        HashMap<String, IData> hashMap3 = new HashMap<String, IData>();
        IData[] arriData2 = new IData[1];
        HashMap<String, IData> hashMap4 = new HashMap<String, IData>();
        hashMap4.put("lvl", ExpandShort.asNBT((short)3));
        hashMap4.put("id", ExpandShort.asNBT((short)35));
        arriData2[0] = ExpandAnyDict.asData(hashMap4);
        hashMap3.put("StoredEnchantments", ExpandAnyArray.asData((IData[])arriData2));
        arriIngredient[1] = IngredientCondition.onlyWithTag((IIngredient)iItemStack3, (IData)ExpandAnyDict.asData(hashMap3));
        arriIngredient[2] = ItemBracketHandler.getItem((String)"minecraft:clay_ball", (int)0);
        MineTweakerAPI.recipes.addShapeless(iItemStack2, arriIngredient, null);
        IItemStack iItemStack4 = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)2);
        HashMap<String, IData> hashMap5 = new HashMap<String, IData>();
        IData[] arriData3 = new IData[1];
        HashMap<String, IData> hashMap6 = new HashMap<String, IData>();
        hashMap6.put("lvl", ExpandShort.asNBT((short)3));
        hashMap6.put("id", ExpandShort.asNBT((short)35));
        arriData3[0] = ExpandAnyDict.asData(hashMap6);
        hashMap5.put("ench", ExpandAnyArray.asData((IData[])arriData3));
        hashMap5.put("RepairCost", ExpandInt.toData((int)2));
        IItemStack iItemStack5 = iItemStack4.withTag(ExpandAnyDict.asData(hashMap5));
        IIngredient[] arriIngredient2 = new IIngredient[3];
        arriIngredient2[0] = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)2);
        IItemStack iItemStack6 = ItemBracketHandler.getItem((String)"minecraft:enchanted_book", (int)0);
        HashMap<String, IData> hashMap7 = new HashMap<String, IData>();
        IData[] arriData4 = new IData[1];
        HashMap<String, IData> hashMap8 = new HashMap<String, IData>();
        hashMap8.put("lvl", ExpandShort.asNBT((short)3));
        hashMap8.put("id", ExpandShort.asNBT((short)35));
        arriData4[0] = ExpandAnyDict.asData(hashMap8);
        hashMap7.put("StoredEnchantments", ExpandAnyArray.asData((IData[])arriData4));
        arriIngredient2[1] = IngredientCondition.onlyWithTag((IIngredient)iItemStack6, (IData)ExpandAnyDict.asData(hashMap7));
        arriIngredient2[2] = ItemBracketHandler.getItem((String)"IC2:itemHarz", (int)0);
        MineTweakerAPI.recipes.addShapeless(iItemStack5, arriIngredient2, null);
        IItemStack iItemStack7 = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)4);
        HashMap<String, IData> hashMap9 = new HashMap<String, IData>();
        IData[] arriData5 = new IData[1];
        HashMap<String, IData> hashMap10 = new HashMap<String, IData>();
        hashMap10.put("lvl", ExpandShort.asNBT((short)3));
        hashMap10.put("id", ExpandShort.asNBT((short)35));
        arriData5[0] = ExpandAnyDict.asData(hashMap10);
        hashMap9.put("ench", ExpandAnyArray.asData((IData[])arriData5));
        hashMap9.put("RepairCost", ExpandInt.toData((int)2));
        IItemStack iItemStack8 = iItemStack7.withTag(ExpandAnyDict.asData(hashMap9));
        IIngredient[] arriIngredient3 = new IIngredient[3];
        arriIngredient3[0] = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)4);
        IItemStack iItemStack9 = ItemBracketHandler.getItem((String)"minecraft:enchanted_book", (int)0);
        HashMap<String, IData> hashMap11 = new HashMap<String, IData>();
        IData[] arriData6 = new IData[1];
        HashMap<String, IData> hashMap12 = new HashMap<String, IData>();
        hashMap12.put("lvl", ExpandShort.asNBT((short)3));
        hashMap12.put("id", ExpandShort.asNBT((short)35));
        arriData6[0] = ExpandAnyDict.asData(hashMap12);
        hashMap11.put("StoredEnchantments", ExpandAnyArray.asData((IData[])arriData6));
        arriIngredient3[1] = IngredientCondition.onlyWithTag((IIngredient)iItemStack9, (IData)ExpandAnyDict.asData(hashMap11));
        arriIngredient3[2] = ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)32610);
        MineTweakerAPI.recipes.addShapeless(iItemStack8, arriIngredient3, null);
        IItemStack iItemStack10 = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)5);
        HashMap<String, IData> hashMap13 = new HashMap<String, IData>();
        IData[] arriData7 = new IData[1];
        HashMap<String, IData> hashMap14 = new HashMap<String, IData>();
        hashMap14.put("lvl", ExpandShort.asNBT((short)3));
        hashMap14.put("id", ExpandShort.asNBT((short)35));
        arriData7[0] = ExpandAnyDict.asData(hashMap14);
        hashMap13.put("ench", ExpandAnyArray.asData((IData[])arriData7));
        hashMap13.put("RepairCost", ExpandInt.toData((int)2));
        IItemStack iItemStack11 = iItemStack10.withTag(ExpandAnyDict.asData(hashMap13));
        IIngredient[] arriIngredient4 = new IIngredient[3];
        arriIngredient4[0] = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)5);
        IItemStack iItemStack12 = ItemBracketHandler.getItem((String)"minecraft:enchanted_book", (int)0);
        HashMap<String, IData> hashMap15 = new HashMap<String, IData>();
        IData[] arriData8 = new IData[1];
        HashMap<String, IData> hashMap16 = new HashMap<String, IData>();
        hashMap16.put("lvl", ExpandShort.asNBT((short)3));
        hashMap16.put("id", ExpandShort.asNBT((short)35));
        arriData8[0] = ExpandAnyDict.asData(hashMap16);
        hashMap15.put("StoredEnchantments", ExpandAnyArray.asData((IData[])arriData8));
        arriIngredient4[1] = IngredientCondition.onlyWithTag((IIngredient)iItemStack12, (IData)ExpandAnyDict.asData(hashMap15));
        arriIngredient4[2] = ItemBracketHandler.getItem((String)"IC2:itemPartIndustrialDiamond", (int)0);
        MineTweakerAPI.recipes.addShapeless(iItemStack11, arriIngredient4, null);
        IItemStack iItemStack13 = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)6);
        HashMap<String, IData> hashMap17 = new HashMap<String, IData>();
        IData[] arriData9 = new IData[1];
        HashMap<String, IData> hashMap18 = new HashMap<String, IData>();
        hashMap18.put("lvl", ExpandShort.asNBT((short)3));
        hashMap18.put("id", ExpandShort.asNBT((short)35));
        arriData9[0] = ExpandAnyDict.asData(hashMap18);
        hashMap17.put("ench", ExpandAnyArray.asData((IData[])arriData9));
        hashMap17.put("RepairCost", ExpandInt.toData((int)2));
        IItemStack iItemStack14 = iItemStack13.withTag(ExpandAnyDict.asData(hashMap17));
        IIngredient[] arriIngredient5 = new IIngredient[3];
        arriIngredient5[0] = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)6);
        IItemStack iItemStack15 = ItemBracketHandler.getItem((String)"minecraft:enchanted_book", (int)0);
        HashMap<String, IData> hashMap19 = new HashMap<String, IData>();
        IData[] arriData10 = new IData[1];
        HashMap<String, IData> hashMap20 = new HashMap<String, IData>();
        hashMap20.put("lvl", ExpandShort.asNBT((short)3));
        hashMap20.put("id", ExpandShort.asNBT((short)35));
        arriData10[0] = ExpandAnyDict.asData(hashMap20);
        hashMap19.put("StoredEnchantments", ExpandAnyArray.asData((IData[])arriData10));
        arriIngredient5[1] = IngredientCondition.onlyWithTag((IIngredient)iItemStack15, (IData)ExpandAnyDict.asData(hashMap19));
        arriIngredient5[2] = ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)32602);
        MineTweakerAPI.recipes.addShapeless(iItemStack14, arriIngredient5, null);
        IItemStack iItemStack16 = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)7);
        HashMap<String, IData> hashMap21 = new HashMap<String, IData>();
        IData[] arriData11 = new IData[1];
        HashMap<String, IData> hashMap22 = new HashMap<String, IData>();
        hashMap22.put("lvl", ExpandShort.asNBT((short)3));
        hashMap22.put("id", ExpandShort.asNBT((short)35));
        arriData11[0] = ExpandAnyDict.asData(hashMap22);
        hashMap21.put("ench", ExpandAnyArray.asData((IData[])arriData11));
        hashMap21.put("RepairCost", ExpandInt.toData((int)2));
        IItemStack iItemStack17 = iItemStack16.withTag(ExpandAnyDict.asData(hashMap21));
        IIngredient[] arriIngredient6 = new IIngredient[3];
        arriIngredient6[0] = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)7);
        IItemStack iItemStack18 = ItemBracketHandler.getItem((String)"minecraft:enchanted_book", (int)0);
        HashMap<String, IData> hashMap23 = new HashMap<String, IData>();
        IData[] arriData12 = new IData[1];
        HashMap<String, IData> hashMap24 = new HashMap<String, IData>();
        hashMap24.put("lvl", ExpandShort.asNBT((short)3));
        hashMap24.put("id", ExpandShort.asNBT((short)35));
        arriData12[0] = ExpandAnyDict.asData(hashMap24);
        hashMap23.put("StoredEnchantments", ExpandAnyArray.asData((IData[])arriData12));
        arriIngredient6[1] = IngredientCondition.onlyWithTag((IIngredient)iItemStack18, (IData)ExpandAnyDict.asData(hashMap23));
        arriIngredient6[2] = ItemBracketHandler.getItem((String)"IC2:itemBatLamaCrystal", (int)32767);
        MineTweakerAPI.recipes.addShapeless(iItemStack17, arriIngredient6, null);
        IItemStack iItemStack19 = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)8);
        HashMap<String, IData> hashMap25 = new HashMap<String, IData>();
        IData[] arriData13 = new IData[1];
        HashMap<String, IData> hashMap26 = new HashMap<String, IData>();
        hashMap26.put("lvl", ExpandShort.asNBT((short)3));
        hashMap26.put("id", ExpandShort.asNBT((short)35));
        arriData13[0] = ExpandAnyDict.asData(hashMap26);
        hashMap25.put("ench", ExpandAnyArray.asData((IData[])arriData13));
        hashMap25.put("RepairCost", ExpandInt.toData((int)2));
        IItemStack iItemStack20 = iItemStack19.withTag(ExpandAnyDict.asData(hashMap25));
        IIngredient[] arriIngredient7 = new IIngredient[3];
        arriIngredient7[0] = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)8);
        IItemStack iItemStack21 = ItemBracketHandler.getItem((String)"minecraft:enchanted_book", (int)0);
        HashMap<String, IData> hashMap27 = new HashMap<String, IData>();
        IData[] arriData14 = new IData[1];
        HashMap<String, IData> hashMap28 = new HashMap<String, IData>();
        hashMap28.put("lvl", ExpandShort.asNBT((short)3));
        hashMap28.put("id", ExpandShort.asNBT((short)35));
        arriData14[0] = ExpandAnyDict.asData(hashMap28);
        hashMap27.put("StoredEnchantments", ExpandAnyArray.asData((IData[])arriData14));
        arriIngredient7[1] = IngredientCondition.onlyWithTag((IIngredient)iItemStack21, (IData)ExpandAnyDict.asData(hashMap27));
        arriIngredient7[2] = ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)32706);
        MineTweakerAPI.recipes.addShapeless(iItemStack20, arriIngredient7, null);
        IItemStack iItemStack22 = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)9);
        HashMap<String, IData> hashMap29 = new HashMap<String, IData>();
        IData[] arriData15 = new IData[1];
        HashMap<String, IData> hashMap30 = new HashMap<String, IData>();
        hashMap30.put("lvl", ExpandShort.asNBT((short)3));
        hashMap30.put("id", ExpandShort.asNBT((short)35));
        arriData15[0] = ExpandAnyDict.asData(hashMap30);
        hashMap29.put("ench", ExpandAnyArray.asData((IData[])arriData15));
        hashMap29.put("RepairCost", ExpandInt.toData((int)2));
        IItemStack iItemStack23 = iItemStack22.withTag(ExpandAnyDict.asData(hashMap29));
        IIngredient[] arriIngredient8 = new IIngredient[3];
        arriIngredient8[0] = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)9);
        IItemStack iItemStack24 = ItemBracketHandler.getItem((String)"minecraft:enchanted_book", (int)0);
        HashMap<String, IData> hashMap31 = new HashMap<String, IData>();
        IData[] arriData16 = new IData[1];
        HashMap<String, IData> hashMap32 = new HashMap<String, IData>();
        hashMap32.put("lvl", ExpandShort.asNBT((short)3));
        hashMap32.put("id", ExpandShort.asNBT((short)35));
        arriData16[0] = ExpandAnyDict.asData(hashMap32);
        hashMap31.put("StoredEnchantments", ExpandAnyArray.asData((IData[])arriData16));
        arriIngredient8[1] = IngredientCondition.onlyWithTag((IIngredient)iItemStack24, (IData)ExpandAnyDict.asData(hashMap31));
        arriIngredient8[2] = ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)1);
        MineTweakerAPI.recipes.addShapeless(iItemStack23, arriIngredient8, null);
        IItemStack iItemStack25 = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)10);
        HashMap<String, IData> hashMap33 = new HashMap<String, IData>();
        IData[] arriData17 = new IData[1];
        HashMap<String, IData> hashMap34 = new HashMap<String, IData>();
        hashMap34.put("lvl", ExpandShort.asNBT((short)3));
        hashMap34.put("id", ExpandShort.asNBT((short)35));
        arriData17[0] = ExpandAnyDict.asData(hashMap34);
        hashMap33.put("ench", ExpandAnyArray.asData((IData[])arriData17));
        hashMap33.put("RepairCost", ExpandInt.toData((int)2));
        IItemStack iItemStack26 = iItemStack25.withTag(ExpandAnyDict.asData(hashMap33));
        IIngredient[] arriIngredient9 = new IIngredient[3];
        arriIngredient9[0] = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)10);
        IItemStack iItemStack27 = ItemBracketHandler.getItem((String)"minecraft:enchanted_book", (int)0);
        HashMap<String, IData> hashMap35 = new HashMap<String, IData>();
        IData[] arriData18 = new IData[1];
        HashMap<String, IData> hashMap36 = new HashMap<String, IData>();
        hashMap36.put("lvl", ExpandShort.asNBT((short)3));
        hashMap36.put("id", ExpandShort.asNBT((short)35));
        arriData18[0] = ExpandAnyDict.asData(hashMap36);
        hashMap35.put("StoredEnchantments", ExpandAnyArray.asData((IData[])arriData18));
        arriIngredient9[1] = IngredientCondition.onlyWithTag((IIngredient)iItemStack27, (IData)ExpandAnyDict.asData(hashMap35));
        arriIngredient9[2] = ItemBracketHandler.getItem((String)"Thaumcraft:ItemBathSalts", (int)0);
        MineTweakerAPI.recipes.addShapeless(iItemStack26, arriIngredient9, null);
        IItemStack iItemStack28 = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)12);
        HashMap<String, IData> hashMap37 = new HashMap<String, IData>();
        IData[] arriData19 = new IData[1];
        HashMap<String, IData> hashMap38 = new HashMap<String, IData>();
        hashMap38.put("lvl", ExpandShort.asNBT((short)3));
        hashMap38.put("id", ExpandShort.asNBT((short)35));
        arriData19[0] = ExpandAnyDict.asData(hashMap38);
        hashMap37.put("ench", ExpandAnyArray.asData((IData[])arriData19));
        hashMap37.put("RepairCost", ExpandInt.toData((int)2));
        IItemStack iItemStack29 = iItemStack28.withTag(ExpandAnyDict.asData(hashMap37));
        IIngredient[] arriIngredient10 = new IIngredient[3];
        arriIngredient10[0] = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)12);
        IItemStack iItemStack30 = ItemBracketHandler.getItem((String)"minecraft:enchanted_book", (int)0);
        HashMap<String, IData> hashMap39 = new HashMap<String, IData>();
        IData[] arriData20 = new IData[1];
        HashMap<String, IData> hashMap40 = new HashMap<String, IData>();
        hashMap40.put("lvl", ExpandShort.asNBT((short)3));
        hashMap40.put("id", ExpandShort.asNBT((short)35));
        arriData20[0] = ExpandAnyDict.asData(hashMap40);
        hashMap39.put("StoredEnchantments", ExpandAnyArray.asData((IData[])arriData20));
        arriIngredient10[1] = IngredientCondition.onlyWithTag((IIngredient)iItemStack30, (IData)ExpandAnyDict.asData(hashMap39));
        arriIngredient10[2] = ItemBracketHandler.getItem((String)"Thaumcraft:WandCap", (int)2);
        MineTweakerAPI.recipes.addShapeless(iItemStack29, arriIngredient10, null);
        IItemStack iItemStack31 = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)13);
        HashMap<String, IData> hashMap41 = new HashMap<String, IData>();
        IData[] arriData21 = new IData[1];
        HashMap<String, IData> hashMap42 = new HashMap<String, IData>();
        hashMap42.put("lvl", ExpandShort.asNBT((short)3));
        hashMap42.put("id", ExpandShort.asNBT((short)35));
        arriData21[0] = ExpandAnyDict.asData(hashMap42);
        hashMap41.put("ench", ExpandAnyArray.asData((IData[])arriData21));
        hashMap41.put("RepairCost", ExpandInt.toData((int)2));
        IItemStack iItemStack32 = iItemStack31.withTag(ExpandAnyDict.asData(hashMap41));
        IIngredient[] arriIngredient11 = new IIngredient[3];
        arriIngredient11[0] = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)13);
        IItemStack iItemStack33 = ItemBracketHandler.getItem((String)"minecraft:enchanted_book", (int)0);
        HashMap<String, IData> hashMap43 = new HashMap<String, IData>();
        IData[] arriData22 = new IData[1];
        HashMap<String, IData> hashMap44 = new HashMap<String, IData>();
        hashMap44.put("lvl", ExpandShort.asNBT((short)3));
        hashMap44.put("id", ExpandShort.asNBT((short)35));
        arriData22[0] = ExpandAnyDict.asData(hashMap44);
        hashMap43.put("StoredEnchantments", ExpandAnyArray.asData((IData[])arriData22));
        arriIngredient11[1] = IngredientCondition.onlyWithTag((IIngredient)iItemStack33, (IData)ExpandAnyDict.asData(hashMap43));
        arriIngredient11[2] = ItemBracketHandler.getItem((String)"ThaumicTinkerer:warpGate", (int)0);
        MineTweakerAPI.recipes.addShapeless(iItemStack32, arriIngredient11, null);
        IItemStack iItemStack34 = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)14);
        HashMap<String, IData> hashMap45 = new HashMap<String, IData>();
        IData[] arriData23 = new IData[1];
        HashMap<String, IData> hashMap46 = new HashMap<String, IData>();
        hashMap46.put("lvl", ExpandShort.asNBT((short)3));
        hashMap46.put("id", ExpandShort.asNBT((short)35));
        arriData23[0] = ExpandAnyDict.asData(hashMap46);
        hashMap45.put("ench", ExpandAnyArray.asData((IData[])arriData23));
        hashMap45.put("RepairCost", ExpandInt.toData((int)2));
        IItemStack iItemStack35 = iItemStack34.withTag(ExpandAnyDict.asData(hashMap45));
        IIngredient[] arriIngredient12 = new IIngredient[3];
        arriIngredient12[0] = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)14);
        IItemStack iItemStack36 = ItemBracketHandler.getItem((String)"minecraft:enchanted_book", (int)0);
        HashMap<String, IData> hashMap47 = new HashMap<String, IData>();
        IData[] arriData24 = new IData[1];
        HashMap<String, IData> hashMap48 = new HashMap<String, IData>();
        hashMap48.put("lvl", ExpandShort.asNBT((short)3));
        hashMap48.put("id", ExpandShort.asNBT((short)35));
        arriData24[0] = ExpandAnyDict.asData(hashMap48);
        hashMap47.put("StoredEnchantments", ExpandAnyArray.asData((IData[])arriData24));
        arriIngredient12[1] = IngredientCondition.onlyWithTag((IIngredient)iItemStack36, (IData)ExpandAnyDict.asData(hashMap47));
        arriIngredient12[2] = ItemBracketHandler.getItem((String)"DraconicEvolution:draconicCore", (int)0);
        MineTweakerAPI.recipes.addShapeless(iItemStack35, arriIngredient12, null);
        IItemStack iItemStack37 = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)15);
        HashMap<String, IData> hashMap49 = new HashMap<String, IData>();
        IData[] arriData25 = new IData[1];
        HashMap<String, IData> hashMap50 = new HashMap<String, IData>();
        hashMap50.put("lvl", ExpandShort.asNBT((short)3));
        hashMap50.put("id", ExpandShort.asNBT((short)35));
        arriData25[0] = ExpandAnyDict.asData(hashMap50);
        hashMap49.put("ench", ExpandAnyArray.asData((IData[])arriData25));
        hashMap49.put("RepairCost", ExpandInt.toData((int)2));
        IItemStack iItemStack38 = iItemStack37.withTag(ExpandAnyDict.asData(hashMap49));
        IIngredient[] arriIngredient13 = new IIngredient[3];
        arriIngredient13[0] = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)15);
        IItemStack iItemStack39 = ItemBracketHandler.getItem((String)"minecraft:enchanted_book", (int)0);
        HashMap<String, IData> hashMap51 = new HashMap<String, IData>();
        IData[] arriData26 = new IData[1];
        HashMap<String, IData> hashMap52 = new HashMap<String, IData>();
        hashMap52.put("lvl", ExpandShort.asNBT((short)3));
        hashMap52.put("id", ExpandShort.asNBT((short)35));
        arriData26[0] = ExpandAnyDict.asData(hashMap52);
        hashMap51.put("StoredEnchantments", ExpandAnyArray.asData((IData[])arriData26));
        arriIngredient13[1] = IngredientCondition.onlyWithTag((IIngredient)iItemStack39, (IData)ExpandAnyDict.asData(hashMap51));
        arriIngredient13[2] = ItemBracketHandler.getItem((String)"minecraft:dragon_egg", (int)0);
        MineTweakerAPI.recipes.addShapeless(iItemStack38, arriIngredient13, null);
        IItemStack iItemStack40 = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)16);
        HashMap<String, IData> hashMap53 = new HashMap<String, IData>();
        IData[] arriData27 = new IData[1];
        HashMap<String, IData> hashMap54 = new HashMap<String, IData>();
        hashMap54.put("lvl", ExpandShort.asNBT((short)3));
        hashMap54.put("id", ExpandShort.asNBT((short)35));
        arriData27[0] = ExpandAnyDict.asData(hashMap54);
        hashMap53.put("ench", ExpandAnyArray.asData((IData[])arriData27));
        hashMap53.put("RepairCost", ExpandInt.toData((int)2));
        IItemStack iItemStack41 = iItemStack40.withTag(ExpandAnyDict.asData(hashMap53));
        IIngredient[] arriIngredient14 = new IIngredient[3];
        arriIngredient14[0] = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)16);
        IItemStack iItemStack42 = ItemBracketHandler.getItem((String)"minecraft:enchanted_book", (int)0);
        HashMap<String, IData> hashMap55 = new HashMap<String, IData>();
        IData[] arriData28 = new IData[1];
        HashMap<String, IData> hashMap56 = new HashMap<String, IData>();
        hashMap56.put("lvl", ExpandShort.asNBT((short)3));
        hashMap56.put("id", ExpandShort.asNBT((short)35));
        arriData28[0] = ExpandAnyDict.asData(hashMap56);
        hashMap55.put("StoredEnchantments", ExpandAnyArray.asData((IData[])arriData28));
        arriIngredient14[1] = IngredientCondition.onlyWithTag((IIngredient)iItemStack42, (IData)ExpandAnyDict.asData(hashMap55));
        arriIngredient14[2] = ItemBracketHandler.getItem((String)"AWWayofTime:simpleCatalyst", (int)0);
        MineTweakerAPI.recipes.addShapeless(iItemStack41, arriIngredient14, null);
        IItemStack iItemStack43 = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)17);
        HashMap<String, IData> hashMap57 = new HashMap<String, IData>();
        IData[] arriData29 = new IData[1];
        HashMap<String, IData> hashMap58 = new HashMap<String, IData>();
        hashMap58.put("lvl", ExpandShort.asNBT((short)3));
        hashMap58.put("id", ExpandShort.asNBT((short)35));
        arriData29[0] = ExpandAnyDict.asData(hashMap58);
        hashMap57.put("ench", ExpandAnyArray.asData((IData[])arriData29));
        hashMap57.put("RepairCost", ExpandInt.toData((int)2));
        IItemStack iItemStack44 = iItemStack43.withTag(ExpandAnyDict.asData(hashMap57));
        IIngredient[] arriIngredient15 = new IIngredient[3];
        arriIngredient15[0] = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)17);
        IItemStack iItemStack45 = ItemBracketHandler.getItem((String)"minecraft:enchanted_book", (int)0);
        HashMap<String, IData> hashMap59 = new HashMap<String, IData>();
        IData[] arriData30 = new IData[1];
        HashMap<String, IData> hashMap60 = new HashMap<String, IData>();
        hashMap60.put("lvl", ExpandShort.asNBT((short)3));
        hashMap60.put("id", ExpandShort.asNBT((short)35));
        arriData30[0] = ExpandAnyDict.asData(hashMap60);
        hashMap59.put("StoredEnchantments", ExpandAnyArray.asData((IData[])arriData30));
        arriIngredient15[1] = IngredientCondition.onlyWithTag((IIngredient)iItemStack45, (IData)ExpandAnyDict.asData(hashMap59));
        arriIngredient15[2] = ItemBracketHandler.getItem((String)"AWWayofTime:imbuedSlate", (int)0);
        MineTweakerAPI.recipes.addShapeless(iItemStack44, arriIngredient15, null);
        IItemStack iItemStack46 = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)18);
        HashMap<String, IData> hashMap61 = new HashMap<String, IData>();
        IData[] arriData31 = new IData[1];
        HashMap<String, IData> hashMap62 = new HashMap<String, IData>();
        hashMap62.put("lvl", ExpandShort.asNBT((short)3));
        hashMap62.put("id", ExpandShort.asNBT((short)35));
        arriData31[0] = ExpandAnyDict.asData(hashMap62);
        hashMap61.put("ench", ExpandAnyArray.asData((IData[])arriData31));
        hashMap61.put("RepairCost", ExpandInt.toData((int)2));
        IItemStack iItemStack47 = iItemStack46.withTag(ExpandAnyDict.asData(hashMap61));
        IIngredient[] arriIngredient16 = new IIngredient[3];
        arriIngredient16[0] = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)18);
        IItemStack iItemStack48 = ItemBracketHandler.getItem((String)"minecraft:enchanted_book", (int)0);
        HashMap<String, IData> hashMap63 = new HashMap<String, IData>();
        IData[] arriData32 = new IData[1];
        HashMap<String, IData> hashMap64 = new HashMap<String, IData>();
        hashMap64.put("lvl", ExpandShort.asNBT((short)3));
        hashMap64.put("id", ExpandShort.asNBT((short)35));
        arriData32[0] = ExpandAnyDict.asData(hashMap64);
        hashMap63.put("StoredEnchantments", ExpandAnyArray.asData((IData[])arriData32));
        arriIngredient16[1] = IngredientCondition.onlyWithTag((IIngredient)iItemStack48, (IData)ExpandAnyDict.asData(hashMap63));
        arriIngredient16[2] = ItemBracketHandler.getItem((String)"AWWayofTime:blockTeleposer", (int)0);
        MineTweakerAPI.recipes.addShapeless(iItemStack47, arriIngredient16, null);
        IItemStack iItemStack49 = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)19);
        HashMap<String, IData> hashMap65 = new HashMap<String, IData>();
        IData[] arriData33 = new IData[1];
        HashMap<String, IData> hashMap66 = new HashMap<String, IData>();
        hashMap66.put("lvl", ExpandShort.asNBT((short)3));
        hashMap66.put("id", ExpandShort.asNBT((short)35));
        arriData33[0] = ExpandAnyDict.asData(hashMap66);
        hashMap65.put("ench", ExpandAnyArray.asData((IData[])arriData33));
        hashMap65.put("RepairCost", ExpandInt.toData((int)2));
        IItemStack iItemStack50 = iItemStack49.withTag(ExpandAnyDict.asData(hashMap65));
        IIngredient[] arriIngredient17 = new IIngredient[3];
        arriIngredient17[0] = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)19);
        IItemStack iItemStack51 = ItemBracketHandler.getItem((String)"minecraft:enchanted_book", (int)0);
        HashMap<String, IData> hashMap67 = new HashMap<String, IData>();
        IData[] arriData34 = new IData[1];
        HashMap<String, IData> hashMap68 = new HashMap<String, IData>();
        hashMap68.put("lvl", ExpandShort.asNBT((short)3));
        hashMap68.put("id", ExpandShort.asNBT((short)35));
        arriData34[0] = ExpandAnyDict.asData(hashMap68);
        hashMap67.put("StoredEnchantments", ExpandAnyArray.asData((IData[])arriData34));
        arriIngredient17[1] = IngredientCondition.onlyWithTag((IIngredient)iItemStack51, (IData)ExpandAnyDict.asData(hashMap67));
        arriIngredient17[2] = ItemBracketHandler.getItem((String)"Forestry:waxCapsule", (int)0);
        MineTweakerAPI.recipes.addShapeless(iItemStack50, arriIngredient17, null);
        IItemStack iItemStack52 = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)20);
        HashMap<String, IData> hashMap69 = new HashMap<String, IData>();
        IData[] arriData35 = new IData[1];
        HashMap<String, IData> hashMap70 = new HashMap<String, IData>();
        hashMap70.put("lvl", ExpandShort.asNBT((short)3));
        hashMap70.put("id", ExpandShort.asNBT((short)35));
        arriData35[0] = ExpandAnyDict.asData(hashMap70);
        hashMap69.put("ench", ExpandAnyArray.asData((IData[])arriData35));
        hashMap69.put("RepairCost", ExpandInt.toData((int)2));
        IItemStack iItemStack53 = iItemStack52.withTag(ExpandAnyDict.asData(hashMap69));
        IIngredient[] arriIngredient18 = new IIngredient[3];
        arriIngredient18[0] = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)20);
        IItemStack iItemStack54 = ItemBracketHandler.getItem((String)"minecraft:enchanted_book", (int)0);
        HashMap<String, IData> hashMap71 = new HashMap<String, IData>();
        IData[] arriData36 = new IData[1];
        HashMap<String, IData> hashMap72 = new HashMap<String, IData>();
        hashMap72.put("lvl", ExpandShort.asNBT((short)3));
        hashMap72.put("id", ExpandShort.asNBT((short)35));
        arriData36[0] = ExpandAnyDict.asData(hashMap72);
        hashMap71.put("StoredEnchantments", ExpandAnyArray.asData((IData[])arriData36));
        arriIngredient18[1] = IngredientCondition.onlyWithTag((IIngredient)iItemStack54, (IData)ExpandAnyDict.asData(hashMap71));
        arriIngredient18[2] = ItemBracketHandler.getItem((String)"Forestry:craftingMaterial", (int)6);
        MineTweakerAPI.recipes.addShapeless(iItemStack53, arriIngredient18, null);
        IItemStack iItemStack55 = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)21);
        HashMap<String, IData> hashMap73 = new HashMap<String, IData>();
        IData[] arriData37 = new IData[1];
        HashMap<String, IData> hashMap74 = new HashMap<String, IData>();
        hashMap74.put("lvl", ExpandShort.asNBT((short)3));
        hashMap74.put("id", ExpandShort.asNBT((short)35));
        arriData37[0] = ExpandAnyDict.asData(hashMap74);
        hashMap73.put("ench", ExpandAnyArray.asData((IData[])arriData37));
        hashMap73.put("RepairCost", ExpandInt.toData((int)2));
        IItemStack iItemStack56 = iItemStack55.withTag(ExpandAnyDict.asData(hashMap73));
        IIngredient[] arriIngredient19 = new IIngredient[3];
        arriIngredient19[0] = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)21);
        IItemStack iItemStack57 = ItemBracketHandler.getItem((String)"minecraft:enchanted_book", (int)0);
        HashMap<String, IData> hashMap75 = new HashMap<String, IData>();
        IData[] arriData38 = new IData[1];
        HashMap<String, IData> hashMap76 = new HashMap<String, IData>();
        hashMap76.put("lvl", ExpandShort.asNBT((short)3));
        hashMap76.put("id", ExpandShort.asNBT((short)35));
        arriData38[0] = ExpandAnyDict.asData(hashMap76);
        hashMap75.put("StoredEnchantments", ExpandAnyArray.asData((IData[])arriData38));
        arriIngredient19[1] = IngredientCondition.onlyWithTag((IIngredient)iItemStack57, (IData)ExpandAnyDict.asData(hashMap75));
        arriIngredient19[2] = ItemBracketHandler.getItem((String)"Forestry:hardenedMachine", (int)0);
        MineTweakerAPI.recipes.addShapeless(iItemStack56, arriIngredient19, null);
        IItemStack iItemStack58 = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)22);
        HashMap<String, IData> hashMap77 = new HashMap<String, IData>();
        IData[] arriData39 = new IData[1];
        HashMap<String, IData> hashMap78 = new HashMap<String, IData>();
        hashMap78.put("lvl", ExpandShort.asNBT((short)3));
        hashMap78.put("id", ExpandShort.asNBT((short)35));
        arriData39[0] = ExpandAnyDict.asData(hashMap78);
        hashMap77.put("ench", ExpandAnyArray.asData((IData[])arriData39));
        hashMap77.put("RepairCost", ExpandInt.toData((int)2));
        IItemStack iItemStack59 = iItemStack58.withTag(ExpandAnyDict.asData(hashMap77));
        IIngredient[] arriIngredient20 = new IIngredient[3];
        arriIngredient20[0] = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)22);
        IItemStack iItemStack60 = ItemBracketHandler.getItem((String)"minecraft:enchanted_book", (int)0);
        HashMap<String, IData> hashMap79 = new HashMap<String, IData>();
        IData[] arriData40 = new IData[1];
        HashMap<String, IData> hashMap80 = new HashMap<String, IData>();
        hashMap80.put("lvl", ExpandShort.asNBT((short)3));
        hashMap80.put("id", ExpandShort.asNBT((short)35));
        arriData40[0] = ExpandAnyDict.asData(hashMap80);
        hashMap79.put("StoredEnchantments", ExpandAnyArray.asData((IData[])arriData40));
        arriIngredient20[1] = IngredientCondition.onlyWithTag((IIngredient)iItemStack60, (IData)ExpandAnyDict.asData(hashMap79));
        arriIngredient20[2] = ItemBracketHandler.getItem((String)"GalacticraftCore:item.airFan", (int)0);
        MineTweakerAPI.recipes.addShapeless(iItemStack59, arriIngredient20, null);
        IItemStack iItemStack61 = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)23);
        HashMap<String, IData> hashMap81 = new HashMap<String, IData>();
        IData[] arriData41 = new IData[1];
        HashMap<String, IData> hashMap82 = new HashMap<String, IData>();
        hashMap82.put("lvl", ExpandShort.asNBT((short)3));
        hashMap82.put("id", ExpandShort.asNBT((short)35));
        arriData41[0] = ExpandAnyDict.asData(hashMap82);
        hashMap81.put("ench", ExpandAnyArray.asData((IData[])arriData41));
        hashMap81.put("RepairCost", ExpandInt.toData((int)2));
        IItemStack iItemStack62 = iItemStack61.withTag(ExpandAnyDict.asData(hashMap81));
        IIngredient[] arriIngredient21 = new IIngredient[3];
        arriIngredient21[0] = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)23);
        IItemStack iItemStack63 = ItemBracketHandler.getItem((String)"minecraft:enchanted_book", (int)0);
        HashMap<String, IData> hashMap83 = new HashMap<String, IData>();
        IData[] arriData42 = new IData[1];
        HashMap<String, IData> hashMap84 = new HashMap<String, IData>();
        hashMap84.put("lvl", ExpandShort.asNBT((short)3));
        hashMap84.put("id", ExpandShort.asNBT((short)35));
        arriData42[0] = ExpandAnyDict.asData(hashMap84);
        hashMap83.put("StoredEnchantments", ExpandAnyArray.asData((IData[])arriData42));
        arriIngredient21[1] = IngredientCondition.onlyWithTag((IIngredient)iItemStack63, (IData)ExpandAnyDict.asData(hashMap83));
        arriIngredient21[2] = ItemBracketHandler.getItem((String)"GalacticraftMars:item.itemBasicAsteroids", (int)7);
        MineTweakerAPI.recipes.addShapeless(iItemStack62, arriIngredient21, null);
        IItemStack iItemStack64 = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)24);
        HashMap<String, IData> hashMap85 = new HashMap<String, IData>();
        IData[] arriData43 = new IData[1];
        HashMap<String, IData> hashMap86 = new HashMap<String, IData>();
        hashMap86.put("lvl", ExpandShort.asNBT((short)3));
        hashMap86.put("id", ExpandShort.asNBT((short)35));
        arriData43[0] = ExpandAnyDict.asData(hashMap86);
        hashMap85.put("ench", ExpandAnyArray.asData((IData[])arriData43));
        hashMap85.put("RepairCost", ExpandInt.toData((int)2));
        IItemStack iItemStack65 = iItemStack64.withTag(ExpandAnyDict.asData(hashMap85));
        IIngredient[] arriIngredient22 = new IIngredient[3];
        arriIngredient22[0] = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)24);
        IItemStack iItemStack66 = ItemBracketHandler.getItem((String)"minecraft:enchanted_book", (int)0);
        HashMap<String, IData> hashMap87 = new HashMap<String, IData>();
        IData[] arriData44 = new IData[1];
        HashMap<String, IData> hashMap88 = new HashMap<String, IData>();
        hashMap88.put("lvl", ExpandShort.asNBT((short)3));
        hashMap88.put("id", ExpandShort.asNBT((short)35));
        arriData44[0] = ExpandAnyDict.asData(hashMap88);
        hashMap87.put("StoredEnchantments", ExpandAnyArray.asData((IData[])arriData44));
        arriIngredient22[1] = IngredientCondition.onlyWithTag((IIngredient)iItemStack66, (IData)ExpandAnyDict.asData(hashMap87));
        arriIngredient22[2] = ItemBracketHandler.getItem((String)"dreamcraft:item.WaferTier3", (int)0);
        MineTweakerAPI.recipes.addShapeless(iItemStack65, arriIngredient22, null);
        IItemStack iItemStack67 = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)25);
        HashMap<String, IData> hashMap89 = new HashMap<String, IData>();
        IData[] arriData45 = new IData[1];
        HashMap<String, IData> hashMap90 = new HashMap<String, IData>();
        hashMap90.put("lvl", ExpandShort.asNBT((short)3));
        hashMap90.put("id", ExpandShort.asNBT((short)35));
        arriData45[0] = ExpandAnyDict.asData(hashMap90);
        hashMap89.put("ench", ExpandAnyArray.asData((IData[])arriData45));
        hashMap89.put("RepairCost", ExpandInt.toData((int)2));
        IItemStack iItemStack68 = iItemStack67.withTag(ExpandAnyDict.asData(hashMap89));
        IIngredient[] arriIngredient23 = new IIngredient[3];
        arriIngredient23[0] = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)25);
        IItemStack iItemStack69 = ItemBracketHandler.getItem((String)"minecraft:enchanted_book", (int)0);
        HashMap<String, IData> hashMap91 = new HashMap<String, IData>();
        IData[] arriData46 = new IData[1];
        HashMap<String, IData> hashMap92 = new HashMap<String, IData>();
        hashMap92.put("lvl", ExpandShort.asNBT((short)3));
        hashMap92.put("id", ExpandShort.asNBT((short)35));
        arriData46[0] = ExpandAnyDict.asData(hashMap92);
        hashMap91.put("StoredEnchantments", ExpandAnyArray.asData((IData[])arriData46));
        arriIngredient23[1] = IngredientCondition.onlyWithTag((IIngredient)iItemStack69, (IData)ExpandAnyDict.asData(hashMap91));
        arriIngredient23[2] = ItemBracketHandler.getItem((String)"Forestry:propolis", (int)3);
        MineTweakerAPI.recipes.addShapeless(iItemStack68, arriIngredient23, null);
        IItemStack iItemStack70 = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)26);
        HashMap<String, IData> hashMap93 = new HashMap<String, IData>();
        IData[] arriData47 = new IData[1];
        HashMap<String, IData> hashMap94 = new HashMap<String, IData>();
        hashMap94.put("lvl", ExpandShort.asNBT((short)3));
        hashMap94.put("id", ExpandShort.asNBT((short)35));
        arriData47[0] = ExpandAnyDict.asData(hashMap94);
        hashMap93.put("ench", ExpandAnyArray.asData((IData[])arriData47));
        hashMap93.put("RepairCost", ExpandInt.toData((int)2));
        IItemStack iItemStack71 = iItemStack70.withTag(ExpandAnyDict.asData(hashMap93));
        IIngredient[] arriIngredient24 = new IIngredient[3];
        arriIngredient24[0] = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)26);
        IItemStack iItemStack72 = ItemBracketHandler.getItem((String)"minecraft:enchanted_book", (int)0);
        HashMap<String, IData> hashMap95 = new HashMap<String, IData>();
        IData[] arriData48 = new IData[1];
        HashMap<String, IData> hashMap96 = new HashMap<String, IData>();
        hashMap96.put("lvl", ExpandShort.asNBT((short)3));
        hashMap96.put("id", ExpandShort.asNBT((short)35));
        arriData48[0] = ExpandAnyDict.asData(hashMap96);
        hashMap95.put("StoredEnchantments", ExpandAnyArray.asData((IData[])arriData48));
        arriIngredient24[1] = IngredientCondition.onlyWithTag((IIngredient)iItemStack72, (IData)ExpandAnyDict.asData(hashMap95));
        arriIngredient24[2] = ItemBracketHandler.getItem((String)"Forestry:royalJelly", (int)0);
        MineTweakerAPI.recipes.addShapeless(iItemStack71, arriIngredient24, null);
        IItemStack iItemStack73 = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)27);
        HashMap<String, IData> hashMap97 = new HashMap<String, IData>();
        IData[] arriData49 = new IData[1];
        HashMap<String, IData> hashMap98 = new HashMap<String, IData>();
        hashMap98.put("lvl", ExpandShort.asNBT((short)3));
        hashMap98.put("id", ExpandShort.asNBT((short)35));
        arriData49[0] = ExpandAnyDict.asData(hashMap98);
        hashMap97.put("ench", ExpandAnyArray.asData((IData[])arriData49));
        hashMap97.put("RepairCost", ExpandInt.toData((int)2));
        IItemStack iItemStack74 = iItemStack73.withTag(ExpandAnyDict.asData(hashMap97));
        IIngredient[] arriIngredient25 = new IIngredient[3];
        arriIngredient25[0] = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)27);
        IItemStack iItemStack75 = ItemBracketHandler.getItem((String)"minecraft:enchanted_book", (int)0);
        HashMap<String, IData> hashMap99 = new HashMap<String, IData>();
        IData[] arriData50 = new IData[1];
        HashMap<String, IData> hashMap100 = new HashMap<String, IData>();
        hashMap100.put("lvl", ExpandShort.asNBT((short)3));
        hashMap100.put("id", ExpandShort.asNBT((short)35));
        arriData50[0] = ExpandAnyDict.asData(hashMap100);
        hashMap99.put("StoredEnchantments", ExpandAnyArray.asData((IData[])arriData50));
        arriIngredient25[1] = IngredientCondition.onlyWithTag((IIngredient)iItemStack75, (IData)ExpandAnyDict.asData(hashMap99));
        arriIngredient25[2] = ItemBracketHandler.getItem((String)"gendustry:MutagenBucket", (int)0);
        MineTweakerAPI.recipes.addShapeless(iItemStack74, arriIngredient25, null);
        IItemStack iItemStack76 = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)28);
        HashMap<String, IData> hashMap101 = new HashMap<String, IData>();
        IData[] arriData51 = new IData[1];
        HashMap<String, IData> hashMap102 = new HashMap<String, IData>();
        hashMap102.put("lvl", ExpandShort.asNBT((short)3));
        hashMap102.put("id", ExpandShort.asNBT((short)35));
        arriData51[0] = ExpandAnyDict.asData(hashMap102);
        hashMap101.put("ench", ExpandAnyArray.asData((IData[])arriData51));
        hashMap101.put("RepairCost", ExpandInt.toData((int)2));
        IItemStack iItemStack77 = iItemStack76.withTag(ExpandAnyDict.asData(hashMap101));
        IIngredient[] arriIngredient26 = new IIngredient[3];
        arriIngredient26[0] = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)28);
        IItemStack iItemStack78 = ItemBracketHandler.getItem((String)"minecraft:enchanted_book", (int)0);
        HashMap<String, IData> hashMap103 = new HashMap<String, IData>();
        IData[] arriData52 = new IData[1];
        HashMap<String, IData> hashMap104 = new HashMap<String, IData>();
        hashMap104.put("lvl", ExpandShort.asNBT((short)3));
        hashMap104.put("id", ExpandShort.asNBT((short)35));
        arriData52[0] = ExpandAnyDict.asData(hashMap104);
        hashMap103.put("StoredEnchantments", ExpandAnyArray.asData((IData[])arriData52));
        arriIngredient26[1] = IngredientCondition.onlyWithTag((IIngredient)iItemStack78, (IData)ExpandAnyDict.asData(hashMap103));
        arriIngredient26[2] = ItemBracketHandler.getItem((String)"minecraft:cake", (int)0);
        MineTweakerAPI.recipes.addShapeless(iItemStack77, arriIngredient26, null);
        IItemStack iItemStack79 = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)29);
        HashMap<String, IData> hashMap105 = new HashMap<String, IData>();
        IData[] arriData53 = new IData[1];
        HashMap<String, IData> hashMap106 = new HashMap<String, IData>();
        hashMap106.put("lvl", ExpandShort.asNBT((short)3));
        hashMap106.put("id", ExpandShort.asNBT((short)35));
        arriData53[0] = ExpandAnyDict.asData(hashMap106);
        hashMap105.put("ench", ExpandAnyArray.asData((IData[])arriData53));
        hashMap105.put("RepairCost", ExpandInt.toData((int)2));
        IItemStack iItemStack80 = iItemStack79.withTag(ExpandAnyDict.asData(hashMap105));
        IIngredient[] arriIngredient27 = new IIngredient[3];
        arriIngredient27[0] = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)29);
        IItemStack iItemStack81 = ItemBracketHandler.getItem((String)"minecraft:enchanted_book", (int)0);
        HashMap<String, IData> hashMap107 = new HashMap<String, IData>();
        IData[] arriData54 = new IData[1];
        HashMap<String, IData> hashMap108 = new HashMap<String, IData>();
        hashMap108.put("lvl", ExpandShort.asNBT((short)3));
        hashMap108.put("id", ExpandShort.asNBT((short)35));
        arriData54[0] = ExpandAnyDict.asData(hashMap108);
        hashMap107.put("StoredEnchantments", ExpandAnyArray.asData((IData[])arriData54));
        arriIngredient27[1] = IngredientCondition.onlyWithTag((IIngredient)iItemStack81, (IData)ExpandAnyDict.asData(hashMap107));
        arriIngredient27[2] = ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.02", (int)32243);
        MineTweakerAPI.recipes.addShapeless(iItemStack80, arriIngredient27, null);
        IItemStack iItemStack82 = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)30);
        HashMap<String, IData> hashMap109 = new HashMap<String, IData>();
        IData[] arriData55 = new IData[1];
        HashMap<String, IData> hashMap110 = new HashMap<String, IData>();
        hashMap110.put("lvl", ExpandShort.asNBT((short)3));
        hashMap110.put("id", ExpandShort.asNBT((short)35));
        arriData55[0] = ExpandAnyDict.asData(hashMap110);
        hashMap109.put("ench", ExpandAnyArray.asData((IData[])arriData55));
        hashMap109.put("RepairCost", ExpandInt.toData((int)2));
        IItemStack iItemStack83 = iItemStack82.withTag(ExpandAnyDict.asData(hashMap109));
        IIngredient[] arriIngredient28 = new IIngredient[3];
        arriIngredient28[0] = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)30);
        IItemStack iItemStack84 = ItemBracketHandler.getItem((String)"minecraft:enchanted_book", (int)0);
        HashMap<String, IData> hashMap111 = new HashMap<String, IData>();
        IData[] arriData56 = new IData[1];
        HashMap<String, IData> hashMap112 = new HashMap<String, IData>();
        hashMap112.put("lvl", ExpandShort.asNBT((short)3));
        hashMap112.put("id", ExpandShort.asNBT((short)35));
        arriData56[0] = ExpandAnyDict.asData(hashMap112);
        hashMap111.put("StoredEnchantments", ExpandAnyArray.asData((IData[])arriData56));
        arriIngredient28[1] = IngredientCondition.onlyWithTag((IIngredient)iItemStack84, (IData)ExpandAnyDict.asData(hashMap111));
        arriIngredient28[2] = ItemBracketHandler.getItem((String)"harvestcraft:delightedmealItem", (int)0);
        MineTweakerAPI.recipes.addShapeless(iItemStack83, arriIngredient28, null);
        IItemStack iItemStack85 = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)31);
        HashMap<String, IData> hashMap113 = new HashMap<String, IData>();
        IData[] arriData57 = new IData[1];
        HashMap<String, IData> hashMap114 = new HashMap<String, IData>();
        hashMap114.put("lvl", ExpandShort.asNBT((short)3));
        hashMap114.put("id", ExpandShort.asNBT((short)35));
        arriData57[0] = ExpandAnyDict.asData(hashMap114);
        hashMap113.put("ench", ExpandAnyArray.asData((IData[])arriData57));
        hashMap113.put("RepairCost", ExpandInt.toData((int)2));
        IItemStack iItemStack86 = iItemStack85.withTag(ExpandAnyDict.asData(hashMap113));
        IIngredient[] arriIngredient29 = new IIngredient[3];
        arriIngredient29[0] = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)31);
        IItemStack iItemStack87 = ItemBracketHandler.getItem((String)"minecraft:enchanted_book", (int)0);
        HashMap<String, IData> hashMap115 = new HashMap<String, IData>();
        IData[] arriData58 = new IData[1];
        HashMap<String, IData> hashMap116 = new HashMap<String, IData>();
        hashMap116.put("lvl", ExpandShort.asNBT((short)3));
        hashMap116.put("id", ExpandShort.asNBT((short)35));
        arriData58[0] = ExpandAnyDict.asData(hashMap116);
        hashMap115.put("StoredEnchantments", ExpandAnyArray.asData((IData[])arriData58));
        arriIngredient29[1] = IngredientCondition.onlyWithTag((IIngredient)iItemStack87, (IData)ExpandAnyDict.asData(hashMap115));
        arriIngredient29[2] = ItemBracketHandler.getItem((String)"DraconicEvolution:dezilsMarshmallow", (int)0);
        MineTweakerAPI.recipes.addShapeless(iItemStack86, arriIngredient29, null);
        IItemStack iItemStack88 = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)32);
        HashMap<String, IData> hashMap117 = new HashMap<String, IData>();
        IData[] arriData59 = new IData[1];
        HashMap<String, IData> hashMap118 = new HashMap<String, IData>();
        hashMap118.put("lvl", ExpandShort.asNBT((short)3));
        hashMap118.put("id", ExpandShort.asNBT((short)35));
        arriData59[0] = ExpandAnyDict.asData(hashMap118);
        hashMap117.put("ench", ExpandAnyArray.asData((IData[])arriData59));
        hashMap117.put("RepairCost", ExpandInt.toData((int)2));
        IItemStack iItemStack89 = iItemStack88.withTag(ExpandAnyDict.asData(hashMap117));
        IIngredient[] arriIngredient30 = new IIngredient[3];
        arriIngredient30[0] = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)32);
        IItemStack iItemStack90 = ItemBracketHandler.getItem((String)"minecraft:enchanted_book", (int)0);
        HashMap<String, IData> hashMap119 = new HashMap<String, IData>();
        IData[] arriData60 = new IData[1];
        HashMap<String, IData> hashMap120 = new HashMap<String, IData>();
        hashMap120.put("lvl", ExpandShort.asNBT((short)3));
        hashMap120.put("id", ExpandShort.asNBT((short)35));
        arriData60[0] = ExpandAnyDict.asData(hashMap120);
        hashMap119.put("StoredEnchantments", ExpandAnyArray.asData((IData[])arriData60));
        arriIngredient30[1] = IngredientCondition.onlyWithTag((IIngredient)iItemStack90, (IData)ExpandAnyDict.asData(hashMap119));
        arriIngredient30[2] = ItemBracketHandler.getItem((String)"minecraft:minecart", (int)0);
        MineTweakerAPI.recipes.addShapeless(iItemStack89, arriIngredient30, null);
        IItemStack iItemStack91 = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)33);
        HashMap<String, IData> hashMap121 = new HashMap<String, IData>();
        IData[] arriData61 = new IData[1];
        HashMap<String, IData> hashMap122 = new HashMap<String, IData>();
        hashMap122.put("lvl", ExpandShort.asNBT((short)3));
        hashMap122.put("id", ExpandShort.asNBT((short)35));
        arriData61[0] = ExpandAnyDict.asData(hashMap122);
        hashMap121.put("ench", ExpandAnyArray.asData((IData[])arriData61));
        hashMap121.put("RepairCost", ExpandInt.toData((int)2));
        IItemStack iItemStack92 = iItemStack91.withTag(ExpandAnyDict.asData(hashMap121));
        IIngredient[] arriIngredient31 = new IIngredient[3];
        arriIngredient31[0] = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)33);
        IItemStack iItemStack93 = ItemBracketHandler.getItem((String)"minecraft:enchanted_book", (int)0);
        HashMap<String, IData> hashMap123 = new HashMap<String, IData>();
        IData[] arriData62 = new IData[1];
        HashMap<String, IData> hashMap124 = new HashMap<String, IData>();
        hashMap124.put("lvl", ExpandShort.asNBT((short)3));
        hashMap124.put("id", ExpandShort.asNBT((short)35));
        arriData62[0] = ExpandAnyDict.asData(hashMap124);
        hashMap123.put("StoredEnchantments", ExpandAnyArray.asData((IData[])arriData62));
        arriIngredient31[1] = IngredientCondition.onlyWithTag((IIngredient)iItemStack93, (IData)ExpandAnyDict.asData(hashMap123));
        IItemStack iItemStack94 = ItemBracketHandler.getItem((String)"Railcraft:track", (int)816);
        HashMap<String, IData> hashMap125 = new HashMap<String, IData>();
        hashMap125.put("track", ExpandString.asData((String)"railcraft:track.speed"));
        arriIngredient31[2] = iItemStack94.withTag(ExpandAnyDict.asData(hashMap125));
        MineTweakerAPI.recipes.addShapeless(iItemStack92, arriIngredient31, null);
        IItemStack iItemStack95 = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)34);
        HashMap<String, IData> hashMap126 = new HashMap<String, IData>();
        IData[] arriData63 = new IData[1];
        HashMap<String, IData> hashMap127 = new HashMap<String, IData>();
        hashMap127.put("lvl", ExpandShort.asNBT((short)3));
        hashMap127.put("id", ExpandShort.asNBT((short)35));
        arriData63[0] = ExpandAnyDict.asData(hashMap127);
        hashMap126.put("ench", ExpandAnyArray.asData((IData[])arriData63));
        hashMap126.put("RepairCost", ExpandInt.toData((int)2));
        IItemStack iItemStack96 = iItemStack95.withTag(ExpandAnyDict.asData(hashMap126));
        IIngredient[] arriIngredient32 = new IIngredient[3];
        arriIngredient32[0] = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)34);
        IItemStack iItemStack97 = ItemBracketHandler.getItem((String)"minecraft:enchanted_book", (int)0);
        HashMap<String, IData> hashMap128 = new HashMap<String, IData>();
        IData[] arriData64 = new IData[1];
        HashMap<String, IData> hashMap129 = new HashMap<String, IData>();
        hashMap129.put("lvl", ExpandShort.asNBT((short)3));
        hashMap129.put("id", ExpandShort.asNBT((short)35));
        arriData64[0] = ExpandAnyDict.asData(hashMap129);
        hashMap128.put("StoredEnchantments", ExpandAnyArray.asData((IData[])arriData64));
        arriIngredient32[1] = IngredientCondition.onlyWithTag((IIngredient)iItemStack97, (IData)ExpandAnyDict.asData(hashMap128));
        IItemStack iItemStack98 = ItemBracketHandler.getItem((String)"Railcraft:cart.loco.electric", (int)0);
        HashMap<String, IData> hashMap130 = new HashMap<String, IData>();
        hashMap130.put("model", ExpandString.asData((String)"railcraft:default"));
        arriIngredient32[2] = iItemStack98.withTag(ExpandAnyDict.asData(hashMap130));
        MineTweakerAPI.recipes.addShapeless(iItemStack96, arriIngredient32, null);
        IItemStack iItemStack99 = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)35);
        HashMap<String, IData> hashMap131 = new HashMap<String, IData>();
        IData[] arriData65 = new IData[1];
        HashMap<String, IData> hashMap132 = new HashMap<String, IData>();
        hashMap132.put("lvl", ExpandShort.asNBT((short)3));
        hashMap132.put("id", ExpandShort.asNBT((short)35));
        arriData65[0] = ExpandAnyDict.asData(hashMap132);
        hashMap131.put("ench", ExpandAnyArray.asData((IData[])arriData65));
        hashMap131.put("RepairCost", ExpandInt.toData((int)2));
        IItemStack iItemStack100 = iItemStack99.withTag(ExpandAnyDict.asData(hashMap131));
        IIngredient[] arriIngredient33 = new IIngredient[3];
        arriIngredient33[0] = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)35);
        IItemStack iItemStack101 = ItemBracketHandler.getItem((String)"minecraft:enchanted_book", (int)0);
        HashMap<String, IData> hashMap133 = new HashMap<String, IData>();
        IData[] arriData66 = new IData[1];
        HashMap<String, IData> hashMap134 = new HashMap<String, IData>();
        hashMap134.put("lvl", ExpandShort.asNBT((short)3));
        hashMap134.put("id", ExpandShort.asNBT((short)35));
        arriData66[0] = ExpandAnyDict.asData(hashMap134);
        hashMap133.put("StoredEnchantments", ExpandAnyArray.asData((IData[])arriData66));
        arriIngredient33[1] = IngredientCondition.onlyWithTag((IIngredient)iItemStack101, (IData)ExpandAnyDict.asData(hashMap133));
        arriIngredient33[2] = ItemBracketHandler.getItem((String)"harvestcraft:epicbaconItem", (int)0);
        MineTweakerAPI.recipes.addShapeless(iItemStack100, arriIngredient33, null);
        IItemStack iItemStack102 = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)36);
        HashMap<String, IData> hashMap135 = new HashMap<String, IData>();
        IData[] arriData67 = new IData[1];
        HashMap<String, IData> hashMap136 = new HashMap<String, IData>();
        hashMap136.put("lvl", ExpandShort.asNBT((short)3));
        hashMap136.put("id", ExpandShort.asNBT((short)35));
        arriData67[0] = ExpandAnyDict.asData(hashMap136);
        hashMap135.put("ench", ExpandAnyArray.asData((IData[])arriData67));
        hashMap135.put("RepairCost", ExpandInt.toData((int)2));
        IItemStack iItemStack103 = iItemStack102.withTag(ExpandAnyDict.asData(hashMap135));
        IIngredient[] arriIngredient34 = new IIngredient[3];
        arriIngredient34[0] = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)36);
        IItemStack iItemStack104 = ItemBracketHandler.getItem((String)"minecraft:enchanted_book", (int)0);
        HashMap<String, IData> hashMap137 = new HashMap<String, IData>();
        IData[] arriData68 = new IData[1];
        HashMap<String, IData> hashMap138 = new HashMap<String, IData>();
        hashMap138.put("lvl", ExpandShort.asNBT((short)3));
        hashMap138.put("id", ExpandShort.asNBT((short)35));
        arriData68[0] = ExpandAnyDict.asData(hashMap138);
        hashMap137.put("StoredEnchantments", ExpandAnyArray.asData((IData[])arriData68));
        arriIngredient34[1] = IngredientCondition.onlyWithTag((IIngredient)iItemStack104, (IData)ExpandAnyDict.asData(hashMap137));
        arriIngredient34[2] = ItemBracketHandler.getItem((String)"harvestcraft:beefwellingtonItem", (int)0);
        MineTweakerAPI.recipes.addShapeless(iItemStack103, arriIngredient34, null);
        IItemStack iItemStack105 = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)37);
        HashMap<String, IData> hashMap139 = new HashMap<String, IData>();
        IData[] arriData69 = new IData[1];
        HashMap<String, IData> hashMap140 = new HashMap<String, IData>();
        hashMap140.put("lvl", ExpandShort.asNBT((short)3));
        hashMap140.put("id", ExpandShort.asNBT((short)35));
        arriData69[0] = ExpandAnyDict.asData(hashMap140);
        hashMap139.put("ench", ExpandAnyArray.asData((IData[])arriData69));
        hashMap139.put("RepairCost", ExpandInt.toData((int)2));
        IItemStack iItemStack106 = iItemStack105.withTag(ExpandAnyDict.asData(hashMap139));
        IIngredient[] arriIngredient35 = new IIngredient[3];
        arriIngredient35[0] = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)37);
        IItemStack iItemStack107 = ItemBracketHandler.getItem((String)"minecraft:enchanted_book", (int)0);
        HashMap<String, IData> hashMap141 = new HashMap<String, IData>();
        IData[] arriData70 = new IData[1];
        HashMap<String, IData> hashMap142 = new HashMap<String, IData>();
        hashMap142.put("lvl", ExpandShort.asNBT((short)3));
        hashMap142.put("id", ExpandShort.asNBT((short)35));
        arriData70[0] = ExpandAnyDict.asData(hashMap142);
        hashMap141.put("StoredEnchantments", ExpandAnyArray.asData((IData[])arriData70));
        arriIngredient35[1] = IngredientCondition.onlyWithTag((IIngredient)iItemStack107, (IData)ExpandAnyDict.asData(hashMap141));
        arriIngredient35[2] = ItemBracketHandler.getItem((String)"appliedenergistics2:item.ItemMultiMaterial", (int)22);
        MineTweakerAPI.recipes.addShapeless(iItemStack106, arriIngredient35, null);
        IItemStack iItemStack108 = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)38);
        HashMap<String, IData> hashMap143 = new HashMap<String, IData>();
        IData[] arriData71 = new IData[1];
        HashMap<String, IData> hashMap144 = new HashMap<String, IData>();
        hashMap144.put("lvl", ExpandShort.asNBT((short)3));
        hashMap144.put("id", ExpandShort.asNBT((short)35));
        arriData71[0] = ExpandAnyDict.asData(hashMap144);
        hashMap143.put("ench", ExpandAnyArray.asData((IData[])arriData71));
        hashMap143.put("RepairCost", ExpandInt.toData((int)2));
        IItemStack iItemStack109 = iItemStack108.withTag(ExpandAnyDict.asData(hashMap143));
        IIngredient[] arriIngredient36 = new IIngredient[3];
        arriIngredient36[0] = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)38);
        IItemStack iItemStack110 = ItemBracketHandler.getItem((String)"minecraft:enchanted_book", (int)0);
        HashMap<String, IData> hashMap145 = new HashMap<String, IData>();
        IData[] arriData72 = new IData[1];
        HashMap<String, IData> hashMap146 = new HashMap<String, IData>();
        hashMap146.put("lvl", ExpandShort.asNBT((short)3));
        hashMap146.put("id", ExpandShort.asNBT((short)35));
        arriData72[0] = ExpandAnyDict.asData(hashMap146);
        hashMap145.put("StoredEnchantments", ExpandAnyArray.asData((IData[])arriData72));
        arriIngredient36[1] = IngredientCondition.onlyWithTag((IIngredient)iItemStack110, (IData)ExpandAnyDict.asData(hashMap145));
        arriIngredient36[2] = ItemBracketHandler.getItem((String)"appliedenergistics2:item.ItemMultiMaterial", (int)30);
        MineTweakerAPI.recipes.addShapeless(iItemStack109, arriIngredient36, null);
        IItemStack iItemStack111 = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)41);
        HashMap<String, IData> hashMap147 = new HashMap<String, IData>();
        IData[] arriData73 = new IData[1];
        HashMap<String, IData> hashMap148 = new HashMap<String, IData>();
        hashMap148.put("lvl", ExpandShort.asNBT((short)3));
        hashMap148.put("id", ExpandShort.asNBT((short)35));
        arriData73[0] = ExpandAnyDict.asData(hashMap148);
        hashMap147.put("ench", ExpandAnyArray.asData((IData[])arriData73));
        hashMap147.put("RepairCost", ExpandInt.toData((int)2));
        IItemStack iItemStack112 = iItemStack111.withTag(ExpandAnyDict.asData(hashMap147));
        IIngredient[] arriIngredient37 = new IIngredient[3];
        arriIngredient37[0] = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)41);
        IItemStack iItemStack113 = ItemBracketHandler.getItem((String)"minecraft:enchanted_book", (int)0);
        HashMap<String, IData> hashMap149 = new HashMap<String, IData>();
        IData[] arriData74 = new IData[1];
        HashMap<String, IData> hashMap150 = new HashMap<String, IData>();
        hashMap150.put("lvl", ExpandShort.asNBT((short)3));
        hashMap150.put("id", ExpandShort.asNBT((short)35));
        arriData74[0] = ExpandAnyDict.asData(hashMap150);
        hashMap149.put("StoredEnchantments", ExpandAnyArray.asData((IData[])arriData74));
        arriIngredient37[1] = IngredientCondition.onlyWithTag((IIngredient)iItemStack113, (IData)ExpandAnyDict.asData(hashMap149));
        arriIngredient37[2] = ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)17070);
        MineTweakerAPI.recipes.addShapeless(iItemStack112, arriIngredient37, null);
        IItemStack iItemStack114 = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)45);
        HashMap<String, IData> hashMap151 = new HashMap<String, IData>();
        IData[] arriData75 = new IData[1];
        HashMap<String, IData> hashMap152 = new HashMap<String, IData>();
        hashMap152.put("lvl", ExpandShort.asNBT((short)3));
        hashMap152.put("id", ExpandShort.asNBT((short)35));
        arriData75[0] = ExpandAnyDict.asData(hashMap152);
        hashMap151.put("ench", ExpandAnyArray.asData((IData[])arriData75));
        hashMap151.put("RepairCost", ExpandInt.toData((int)2));
        IItemStack iItemStack115 = iItemStack114.withTag(ExpandAnyDict.asData(hashMap151));
        IIngredient[] arriIngredient38 = new IIngredient[3];
        arriIngredient38[0] = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)45);
        IItemStack iItemStack116 = ItemBracketHandler.getItem((String)"minecraft:enchanted_book", (int)0);
        HashMap<String, IData> hashMap153 = new HashMap<String, IData>();
        IData[] arriData76 = new IData[1];
        HashMap<String, IData> hashMap154 = new HashMap<String, IData>();
        hashMap154.put("lvl", ExpandShort.asNBT((short)3));
        hashMap154.put("id", ExpandShort.asNBT((short)35));
        arriData76[0] = ExpandAnyDict.asData(hashMap154);
        hashMap153.put("StoredEnchantments", ExpandAnyArray.asData((IData[])arriData76));
        arriIngredient38[1] = IngredientCondition.onlyWithTag((IIngredient)iItemStack116, (IData)ExpandAnyDict.asData(hashMap153));
        arriIngredient38[2] = ItemBracketHandler.getItem((String)"OpenComputers:eeprom", (int)0);
        MineTweakerAPI.recipes.addShapeless(iItemStack115, arriIngredient38, null);
        IItemStack iItemStack117 = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)46);
        HashMap<String, IData> hashMap155 = new HashMap<String, IData>();
        IData[] arriData77 = new IData[1];
        HashMap<String, IData> hashMap156 = new HashMap<String, IData>();
        hashMap156.put("lvl", ExpandShort.asNBT((short)3));
        hashMap156.put("id", ExpandShort.asNBT((short)35));
        arriData77[0] = ExpandAnyDict.asData(hashMap156);
        hashMap155.put("ench", ExpandAnyArray.asData((IData[])arriData77));
        hashMap155.put("RepairCost", ExpandInt.toData((int)2));
        IItemStack iItemStack118 = iItemStack117.withTag(ExpandAnyDict.asData(hashMap155));
        IIngredient[] arriIngredient39 = new IIngredient[3];
        arriIngredient39[0] = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)46);
        IItemStack iItemStack119 = ItemBracketHandler.getItem((String)"minecraft:enchanted_book", (int)0);
        HashMap<String, IData> hashMap157 = new HashMap<String, IData>();
        IData[] arriData78 = new IData[1];
        HashMap<String, IData> hashMap158 = new HashMap<String, IData>();
        hashMap158.put("lvl", ExpandShort.asNBT((short)3));
        hashMap158.put("id", ExpandShort.asNBT((short)35));
        arriData78[0] = ExpandAnyDict.asData(hashMap158);
        hashMap157.put("StoredEnchantments", ExpandAnyArray.asData((IData[])arriData78));
        arriIngredient39[1] = IngredientCondition.onlyWithTag((IIngredient)iItemStack119, (IData)ExpandAnyDict.asData(hashMap157));
        arriIngredient39[2] = ItemBracketHandler.getItem((String)"OpenComputers:item", (int)1);
        MineTweakerAPI.recipes.addShapeless(iItemStack118, arriIngredient39, null);
        IItemStack iItemStack120 = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)47);
        HashMap<String, IData> hashMap159 = new HashMap<String, IData>();
        IData[] arriData79 = new IData[1];
        HashMap<String, IData> hashMap160 = new HashMap<String, IData>();
        hashMap160.put("lvl", ExpandShort.asNBT((short)3));
        hashMap160.put("id", ExpandShort.asNBT((short)35));
        arriData79[0] = ExpandAnyDict.asData(hashMap160);
        hashMap159.put("ench", ExpandAnyArray.asData((IData[])arriData79));
        hashMap159.put("RepairCost", ExpandInt.toData((int)2));
        IItemStack iItemStack121 = iItemStack120.withTag(ExpandAnyDict.asData(hashMap159));
        IIngredient[] arriIngredient40 = new IIngredient[3];
        arriIngredient40[0] = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)47);
        IItemStack iItemStack122 = ItemBracketHandler.getItem((String)"minecraft:enchanted_book", (int)0);
        HashMap<String, IData> hashMap161 = new HashMap<String, IData>();
        IData[] arriData80 = new IData[1];
        HashMap<String, IData> hashMap162 = new HashMap<String, IData>();
        hashMap162.put("lvl", ExpandShort.asNBT((short)3));
        hashMap162.put("id", ExpandShort.asNBT((short)35));
        arriData80[0] = ExpandAnyDict.asData(hashMap162);
        hashMap161.put("StoredEnchantments", ExpandAnyArray.asData((IData[])arriData80));
        arriIngredient40[1] = IngredientCondition.onlyWithTag((IIngredient)iItemStack122, (IData)ExpandAnyDict.asData(hashMap161));
        arriIngredient40[2] = ItemBracketHandler.getItem((String)"OpenComputers:item", (int)2);
        MineTweakerAPI.recipes.addShapeless(iItemStack121, arriIngredient40, null);
        IItemStack iItemStack123 = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)48);
        HashMap<String, IData> hashMap163 = new HashMap<String, IData>();
        IData[] arriData81 = new IData[1];
        HashMap<String, IData> hashMap164 = new HashMap<String, IData>();
        hashMap164.put("lvl", ExpandShort.asNBT((short)3));
        hashMap164.put("id", ExpandShort.asNBT((short)35));
        arriData81[0] = ExpandAnyDict.asData(hashMap164);
        hashMap163.put("ench", ExpandAnyArray.asData((IData[])arriData81));
        hashMap163.put("RepairCost", ExpandInt.toData((int)2));
        IItemStack iItemStack124 = iItemStack123.withTag(ExpandAnyDict.asData(hashMap163));
        IIngredient[] arriIngredient41 = new IIngredient[3];
        arriIngredient41[0] = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)48);
        IItemStack iItemStack125 = ItemBracketHandler.getItem((String)"minecraft:enchanted_book", (int)0);
        HashMap<String, IData> hashMap165 = new HashMap<String, IData>();
        IData[] arriData82 = new IData[1];
        HashMap<String, IData> hashMap166 = new HashMap<String, IData>();
        hashMap166.put("lvl", ExpandShort.asNBT((short)3));
        hashMap166.put("id", ExpandShort.asNBT((short)35));
        arriData82[0] = ExpandAnyDict.asData(hashMap166);
        hashMap165.put("StoredEnchantments", ExpandAnyArray.asData((IData[])arriData82));
        arriIngredient41[1] = IngredientCondition.onlyWithTag((IIngredient)iItemStack125, (IData)ExpandAnyDict.asData(hashMap165));
        arriIngredient41[2] = ItemBracketHandler.getItem((String)"OpenComputers:item", (int)38);
        MineTweakerAPI.recipes.addShapeless(iItemStack124, arriIngredient41, null);
        IItemStack iItemStack126 = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)49);
        HashMap<String, IData> hashMap167 = new HashMap<String, IData>();
        IData[] arriData83 = new IData[1];
        HashMap<String, IData> hashMap168 = new HashMap<String, IData>();
        hashMap168.put("lvl", ExpandShort.asNBT((short)3));
        hashMap168.put("id", ExpandShort.asNBT((short)35));
        arriData83[0] = ExpandAnyDict.asData(hashMap168);
        hashMap167.put("ench", ExpandAnyArray.asData((IData[])arriData83));
        hashMap167.put("RepairCost", ExpandInt.toData((int)2));
        IItemStack iItemStack127 = iItemStack126.withTag(ExpandAnyDict.asData(hashMap167));
        IIngredient[] arriIngredient42 = new IIngredient[3];
        arriIngredient42[0] = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)49);
        IItemStack iItemStack128 = ItemBracketHandler.getItem((String)"minecraft:enchanted_book", (int)0);
        HashMap<String, IData> hashMap169 = new HashMap<String, IData>();
        IData[] arriData84 = new IData[1];
        HashMap<String, IData> hashMap170 = new HashMap<String, IData>();
        hashMap170.put("lvl", ExpandShort.asNBT((short)3));
        hashMap170.put("id", ExpandShort.asNBT((short)35));
        arriData84[0] = ExpandAnyDict.asData(hashMap170);
        hashMap169.put("StoredEnchantments", ExpandAnyArray.asData((IData[])arriData84));
        arriIngredient42[1] = IngredientCondition.onlyWithTag((IIngredient)iItemStack128, (IData)ExpandAnyDict.asData(hashMap169));
        arriIngredient42[2] = ItemBracketHandler.getItem((String)"OpenComputers:item", (int)39);
        MineTweakerAPI.recipes.addShapeless(iItemStack127, arriIngredient42, null);
        IItemStack iItemStack129 = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)50);
        HashMap<String, IData> hashMap171 = new HashMap<String, IData>();
        IData[] arriData85 = new IData[1];
        HashMap<String, IData> hashMap172 = new HashMap<String, IData>();
        hashMap172.put("lvl", ExpandShort.asNBT((short)3));
        hashMap172.put("id", ExpandShort.asNBT((short)35));
        arriData85[0] = ExpandAnyDict.asData(hashMap172);
        hashMap171.put("ench", ExpandAnyArray.asData((IData[])arriData85));
        hashMap171.put("RepairCost", ExpandInt.toData((int)2));
        IItemStack iItemStack130 = iItemStack129.withTag(ExpandAnyDict.asData(hashMap171));
        IIngredient[] arriIngredient43 = new IIngredient[3];
        arriIngredient43[0] = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)50);
        IItemStack iItemStack131 = ItemBracketHandler.getItem((String)"minecraft:enchanted_book", (int)0);
        HashMap<String, IData> hashMap173 = new HashMap<String, IData>();
        IData[] arriData86 = new IData[1];
        HashMap<String, IData> hashMap174 = new HashMap<String, IData>();
        hashMap174.put("lvl", ExpandShort.asNBT((short)3));
        hashMap174.put("id", ExpandShort.asNBT((short)35));
        arriData86[0] = ExpandAnyDict.asData(hashMap174);
        hashMap173.put("StoredEnchantments", ExpandAnyArray.asData((IData[])arriData86));
        arriIngredient43[1] = IngredientCondition.onlyWithTag((IIngredient)iItemStack131, (IData)ExpandAnyDict.asData(hashMap173));
        arriIngredient43[2] = ItemBracketHandler.getItem((String)"OpenComputers:item", (int)69);
        MineTweakerAPI.recipes.addShapeless(iItemStack130, arriIngredient43, null);
        IItemStack iItemStack132 = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)51);
        HashMap<String, IData> hashMap175 = new HashMap<String, IData>();
        IData[] arriData87 = new IData[1];
        HashMap<String, IData> hashMap176 = new HashMap<String, IData>();
        hashMap176.put("lvl", ExpandShort.asNBT((short)3));
        hashMap176.put("id", ExpandShort.asNBT((short)35));
        arriData87[0] = ExpandAnyDict.asData(hashMap176);
        hashMap175.put("ench", ExpandAnyArray.asData((IData[])arriData87));
        hashMap175.put("RepairCost", ExpandInt.toData((int)2));
        IItemStack iItemStack133 = iItemStack132.withTag(ExpandAnyDict.asData(hashMap175));
        IIngredient[] arriIngredient44 = new IIngredient[3];
        arriIngredient44[0] = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)51);
        IItemStack iItemStack134 = ItemBracketHandler.getItem((String)"minecraft:enchanted_book", (int)0);
        HashMap<String, IData> hashMap177 = new HashMap<String, IData>();
        IData[] arriData88 = new IData[1];
        HashMap<String, IData> hashMap178 = new HashMap<String, IData>();
        hashMap178.put("lvl", ExpandShort.asNBT((short)3));
        hashMap178.put("id", ExpandShort.asNBT((short)35));
        arriData88[0] = ExpandAnyDict.asData(hashMap178);
        hashMap177.put("StoredEnchantments", ExpandAnyArray.asData((IData[])arriData88));
        arriIngredient44[1] = IngredientCondition.onlyWithTag((IIngredient)iItemStack134, (IData)ExpandAnyDict.asData(hashMap177));
        arriIngredient44[2] = ItemBracketHandler.getItem((String)"gregtech:gt.blockmachines", (int)341);
        MineTweakerAPI.recipes.addShapeless(iItemStack133, arriIngredient44, null);
        IItemStack iItemStack135 = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)52);
        HashMap<String, IData> hashMap179 = new HashMap<String, IData>();
        IData[] arriData89 = new IData[1];
        HashMap<String, IData> hashMap180 = new HashMap<String, IData>();
        hashMap180.put("lvl", ExpandShort.asNBT((short)3));
        hashMap180.put("id", ExpandShort.asNBT((short)35));
        arriData89[0] = ExpandAnyDict.asData(hashMap180);
        hashMap179.put("ench", ExpandAnyArray.asData((IData[])arriData89));
        hashMap179.put("RepairCost", ExpandInt.toData((int)2));
        IItemStack iItemStack136 = iItemStack135.withTag(ExpandAnyDict.asData(hashMap179));
        IIngredient[] arriIngredient45 = new IIngredient[3];
        arriIngredient45[0] = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)52);
        IItemStack iItemStack137 = ItemBracketHandler.getItem((String)"minecraft:enchanted_book", (int)0);
        HashMap<String, IData> hashMap181 = new HashMap<String, IData>();
        IData[] arriData90 = new IData[1];
        HashMap<String, IData> hashMap182 = new HashMap<String, IData>();
        hashMap182.put("lvl", ExpandShort.asNBT((short)3));
        hashMap182.put("id", ExpandShort.asNBT((short)35));
        arriData90[0] = ExpandAnyDict.asData(hashMap182);
        hashMap181.put("StoredEnchantments", ExpandAnyArray.asData((IData[])arriData90));
        arriIngredient45[1] = IngredientCondition.onlyWithTag((IIngredient)iItemStack137, (IData)ExpandAnyDict.asData(hashMap181));
        arriIngredient45[2] = ItemBracketHandler.getItem((String)"witchery:witchleaves", (int)0);
        MineTweakerAPI.recipes.addShapeless(iItemStack136, arriIngredient45, null);
        IItemStack iItemStack138 = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)53);
        HashMap<String, IData> hashMap183 = new HashMap<String, IData>();
        IData[] arriData91 = new IData[1];
        HashMap<String, IData> hashMap184 = new HashMap<String, IData>();
        hashMap184.put("lvl", ExpandShort.asNBT((short)3));
        hashMap184.put("id", ExpandShort.asNBT((short)35));
        arriData91[0] = ExpandAnyDict.asData(hashMap184);
        hashMap183.put("ench", ExpandAnyArray.asData((IData[])arriData91));
        hashMap183.put("RepairCost", ExpandInt.toData((int)2));
        IItemStack iItemStack139 = iItemStack138.withTag(ExpandAnyDict.asData(hashMap183));
        IIngredient[] arriIngredient46 = new IIngredient[3];
        arriIngredient46[0] = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)53);
        IItemStack iItemStack140 = ItemBracketHandler.getItem((String)"minecraft:enchanted_book", (int)0);
        HashMap<String, IData> hashMap185 = new HashMap<String, IData>();
        IData[] arriData92 = new IData[1];
        HashMap<String, IData> hashMap186 = new HashMap<String, IData>();
        hashMap186.put("lvl", ExpandShort.asNBT((short)3));
        hashMap186.put("id", ExpandShort.asNBT((short)35));
        arriData92[0] = ExpandAnyDict.asData(hashMap186);
        hashMap185.put("StoredEnchantments", ExpandAnyArray.asData((IData[])arriData92));
        arriIngredient46[1] = IngredientCondition.onlyWithTag((IIngredient)iItemStack140, (IData)ExpandAnyDict.asData(hashMap185));
        arriIngredient46[2] = ItemBracketHandler.getItem((String)"witchery:ingredient", (int)95);
        MineTweakerAPI.recipes.addShapeless(iItemStack139, arriIngredient46, null);
        IItemStack iItemStack141 = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)54);
        HashMap<String, IData> hashMap187 = new HashMap<String, IData>();
        IData[] arriData93 = new IData[1];
        HashMap<String, IData> hashMap188 = new HashMap<String, IData>();
        hashMap188.put("lvl", ExpandShort.asNBT((short)3));
        hashMap188.put("id", ExpandShort.asNBT((short)35));
        arriData93[0] = ExpandAnyDict.asData(hashMap188);
        hashMap187.put("ench", ExpandAnyArray.asData((IData[])arriData93));
        hashMap187.put("RepairCost", ExpandInt.toData((int)2));
        IItemStack iItemStack142 = iItemStack141.withTag(ExpandAnyDict.asData(hashMap187));
        IIngredient[] arriIngredient47 = new IIngredient[3];
        arriIngredient47[0] = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)54);
        IItemStack iItemStack143 = ItemBracketHandler.getItem((String)"minecraft:enchanted_book", (int)0);
        HashMap<String, IData> hashMap189 = new HashMap<String, IData>();
        IData[] arriData94 = new IData[1];
        HashMap<String, IData> hashMap190 = new HashMap<String, IData>();
        hashMap190.put("lvl", ExpandShort.asNBT((short)3));
        hashMap190.put("id", ExpandShort.asNBT((short)35));
        arriData94[0] = ExpandAnyDict.asData(hashMap190);
        hashMap189.put("StoredEnchantments", ExpandAnyArray.asData((IData[])arriData94));
        arriIngredient47[1] = IngredientCondition.onlyWithTag((IIngredient)iItemStack143, (IData)ExpandAnyDict.asData(hashMap189));
        arriIngredient47[2] = ItemBracketHandler.getItem((String)"witchery:ingredient", (int)11);
        MineTweakerAPI.recipes.addShapeless(iItemStack142, arriIngredient47, null);
        IItemStack iItemStack144 = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)55);
        HashMap<String, IData> hashMap191 = new HashMap<String, IData>();
        IData[] arriData95 = new IData[1];
        HashMap<String, IData> hashMap192 = new HashMap<String, IData>();
        hashMap192.put("lvl", ExpandShort.asNBT((short)3));
        hashMap192.put("id", ExpandShort.asNBT((short)35));
        arriData95[0] = ExpandAnyDict.asData(hashMap192);
        hashMap191.put("ench", ExpandAnyArray.asData((IData[])arriData95));
        hashMap191.put("RepairCost", ExpandInt.toData((int)2));
        IItemStack iItemStack145 = iItemStack144.withTag(ExpandAnyDict.asData(hashMap191));
        IIngredient[] arriIngredient48 = new IIngredient[3];
        arriIngredient48[0] = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)55);
        IItemStack iItemStack146 = ItemBracketHandler.getItem((String)"minecraft:enchanted_book", (int)0);
        HashMap<String, IData> hashMap193 = new HashMap<String, IData>();
        IData[] arriData96 = new IData[1];
        HashMap<String, IData> hashMap194 = new HashMap<String, IData>();
        hashMap194.put("lvl", ExpandShort.asNBT((short)3));
        hashMap194.put("id", ExpandShort.asNBT((short)35));
        arriData96[0] = ExpandAnyDict.asData(hashMap194);
        hashMap193.put("StoredEnchantments", ExpandAnyArray.asData((IData[])arriData96));
        arriIngredient48[1] = IngredientCondition.onlyWithTag((IIngredient)iItemStack146, (IData)ExpandAnyDict.asData(hashMap193));
        arriIngredient48[2] = ItemBracketHandler.getItem((String)"witchery:ingredient", (int)96);
        MineTweakerAPI.recipes.addShapeless(iItemStack145, arriIngredient48, null);
        IItemStack iItemStack147 = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)56);
        HashMap<String, IData> hashMap195 = new HashMap<String, IData>();
        IData[] arriData97 = new IData[1];
        HashMap<String, IData> hashMap196 = new HashMap<String, IData>();
        hashMap196.put("lvl", ExpandShort.asNBT((short)3));
        hashMap196.put("id", ExpandShort.asNBT((short)35));
        arriData97[0] = ExpandAnyDict.asData(hashMap196);
        hashMap195.put("ench", ExpandAnyArray.asData((IData[])arriData97));
        hashMap195.put("RepairCost", ExpandInt.toData((int)2));
        IItemStack iItemStack148 = iItemStack147.withTag(ExpandAnyDict.asData(hashMap195));
        IIngredient[] arriIngredient49 = new IIngredient[3];
        arriIngredient49[0] = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)56);
        IItemStack iItemStack149 = ItemBracketHandler.getItem((String)"minecraft:enchanted_book", (int)0);
        HashMap<String, IData> hashMap197 = new HashMap<String, IData>();
        IData[] arriData98 = new IData[1];
        HashMap<String, IData> hashMap198 = new HashMap<String, IData>();
        hashMap198.put("lvl", ExpandShort.asNBT((short)3));
        hashMap198.put("id", ExpandShort.asNBT((short)35));
        arriData98[0] = ExpandAnyDict.asData(hashMap198);
        hashMap197.put("StoredEnchantments", ExpandAnyArray.asData((IData[])arriData98));
        arriIngredient49[1] = IngredientCondition.onlyWithTag((IIngredient)iItemStack149, (IData)ExpandAnyDict.asData(hashMap197));
        arriIngredient49[2] = ItemBracketHandler.getItem((String)"witchery:leonardsurn", (int)3);
        MineTweakerAPI.recipes.addShapeless(iItemStack148, arriIngredient49, null);
        IItemStack iItemStack150 = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)57);
        HashMap<String, IData> hashMap199 = new HashMap<String, IData>();
        IData[] arriData99 = new IData[1];
        HashMap<String, IData> hashMap200 = new HashMap<String, IData>();
        hashMap200.put("lvl", ExpandShort.asNBT((short)3));
        hashMap200.put("id", ExpandShort.asNBT((short)35));
        arriData99[0] = ExpandAnyDict.asData(hashMap200);
        hashMap199.put("ench", ExpandAnyArray.asData((IData[])arriData99));
        hashMap199.put("RepairCost", ExpandInt.toData((int)2));
        IItemStack iItemStack151 = iItemStack150.withTag(ExpandAnyDict.asData(hashMap199));
        IIngredient[] arriIngredient50 = new IIngredient[3];
        arriIngredient50[0] = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)57);
        IItemStack iItemStack152 = ItemBracketHandler.getItem((String)"minecraft:enchanted_book", (int)0);
        HashMap<String, IData> hashMap201 = new HashMap<String, IData>();
        IData[] arriData100 = new IData[1];
        HashMap<String, IData> hashMap202 = new HashMap<String, IData>();
        hashMap202.put("lvl", ExpandShort.asNBT((short)3));
        hashMap202.put("id", ExpandShort.asNBT((short)35));
        arriData100[0] = ExpandAnyDict.asData(hashMap202);
        hashMap201.put("StoredEnchantments", ExpandAnyArray.asData((IData[])arriData100));
        arriIngredient50[1] = IngredientCondition.onlyWithTag((IIngredient)iItemStack152, (IData)ExpandAnyDict.asData(hashMap201));
        arriIngredient50[2] = ItemBracketHandler.getItem((String)"HardcoreEnderExpansion:enderman_head", (int)0);
        MineTweakerAPI.recipes.addShapeless(iItemStack151, arriIngredient50, null);
        IItemStack iItemStack153 = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)58);
        HashMap<String, IData> hashMap203 = new HashMap<String, IData>();
        IData[] arriData101 = new IData[1];
        HashMap<String, IData> hashMap204 = new HashMap<String, IData>();
        hashMap204.put("lvl", ExpandShort.asNBT((short)3));
        hashMap204.put("id", ExpandShort.asNBT((short)35));
        arriData101[0] = ExpandAnyDict.asData(hashMap204);
        hashMap203.put("ench", ExpandAnyArray.asData((IData[])arriData101));
        hashMap203.put("RepairCost", ExpandInt.toData((int)2));
        IItemStack iItemStack154 = iItemStack153.withTag(ExpandAnyDict.asData(hashMap203));
        IIngredient[] arriIngredient51 = new IIngredient[3];
        arriIngredient51[0] = ItemBracketHandler.getItem((String)"enhancedlootbags:lootbag", (int)58);
        IItemStack iItemStack155 = ItemBracketHandler.getItem((String)"minecraft:enchanted_book", (int)0);
        HashMap<String, IData> hashMap205 = new HashMap<String, IData>();
        IData[] arriData102 = new IData[1];
        HashMap<String, IData> hashMap206 = new HashMap<String, IData>();
        hashMap206.put("lvl", ExpandShort.asNBT((short)3));
        hashMap206.put("id", ExpandShort.asNBT((short)35));
        arriData102[0] = ExpandAnyDict.asData(hashMap206);
        hashMap205.put("StoredEnchantments", ExpandAnyArray.asData((IData[])arriData102));
        arriIngredient51[1] = IngredientCondition.onlyWithTag((IIngredient)iItemStack155, (IData)ExpandAnyDict.asData(hashMap205));
        arriIngredient51[2] = ItemBracketHandler.getItem((String)"HardcoreEnderExpansion:rune", (int)5);
        MineTweakerAPI.recipes.addShapeless(iItemStack154, arriIngredient51, null);
    }
}

