package com.github.GTNH2Mega.fromScripts

import minetweaker.MineTweakerAPI
import minetweaker.api.data.IData
import minetweaker.api.item.IIngredient
import minetweaker.expand.ExpandAnyDict
import minetweaker.expand.ExpandInt
import minetweaker.mc1710.brackets.ItemBracketHandler
import minetweaker.mc1710.brackets.OreBracketHandler
import java.util.*

class ExtraTrees3 : Runnable {
    override fun run() {
        val ore = OreBracketHandler.getOre("craftingToolScrewdriver")
        val ore2 = OreBracketHandler.getOre("screwIron")
        val ore3 = OreBracketHandler.getOre("screwSteel")
        val recipes = MineTweakerAPI.recipes
        val item = ItemBracketHandler.getItem("ExtraTrees:fence", 57)
        val hashMap = HashMap<String, IData>()
        hashMap["meta"] = ExpandInt.toData(57)
        val withTag = item.withTag(ExpandAnyDict.asData(hashMap))
        val array: Array<Array<IIngredient?>?> = arrayOfNulls(3)
        val n = 0
        val array2 = arrayOf<IIngredient?>(OreBracketHandler.getOre("stickWood"), null, null)
        val n2 = 1
        val item2 = ItemBracketHandler.getItem("ExtraTrees:planks", 25)
        val hashMap2 = HashMap<String, IData>()
        hashMap2["meta"] = ExpandInt.toData(25)
        array2[n2] = item2.withTag(ExpandAnyDict.asData(hashMap2))
        array2[2] = OreBracketHandler.getOre("stickWood")
        array[n] = array2
        val n3 = 1
        val array3 = arrayOf<IIngredient?>(OreBracketHandler.getOre("stickWood"), null, null)
        val n4 = 1
        val item3 = ItemBracketHandler.getItem("ExtraTrees:planks", 25)
        val hashMap3 = HashMap<String, IData>()
        hashMap3["meta"] = ExpandInt.toData(25)
        array3[n4] = item3.withTag(ExpandAnyDict.asData(hashMap3))
        array3[2] = OreBracketHandler.getOre("stickWood")
        array[n3] = array3
        val n5 = 2
        val array4 = arrayOf<IIngredient?>(OreBracketHandler.getOre("stickWood"), null, null)
        val n6 = 1
        val item4 = ItemBracketHandler.getItem("ExtraTrees:planks", 25)
        val hashMap4 = HashMap<String, IData>()
        hashMap4["meta"] = ExpandInt.toData(25)
        array4[n6] = item4.withTag(ExpandAnyDict.asData(hashMap4))
        array4[2] = OreBracketHandler.getOre("stickWood")
        array[n5] = array4
        recipes.addShaped(withTag, array, null)
        val recipes2 = MineTweakerAPI.recipes
        val item5 = ItemBracketHandler.getItem("ExtraTrees:fence", 57)
        val hashMap5 = HashMap<String, IData>()
        hashMap5["meta"] = ExpandInt.toData(57)
        val amount = item5.withTag(ExpandAnyDict.asData(hashMap5)).amount(2)
        val array5 = arrayOf(arrayOf<IIngredient?>(ore2, ore, ore2), null, null)
        val n7 = 1
        val array6 = arrayOf<IIngredient?>(OreBracketHandler.getOre("stickWood"), null, null)
        val n8 = 1
        val item6 = ItemBracketHandler.getItem("ExtraTrees:planks", 25)
        val hashMap6 = HashMap<String, IData>()
        hashMap6["meta"] = ExpandInt.toData(25)
        array6[n8] = item6.withTag(ExpandAnyDict.asData(hashMap6))
        array6[2] = OreBracketHandler.getOre("stickWood")
        array5[n7] = array6
        val n9 = 2
        val array7 = arrayOf<IIngredient?>(OreBracketHandler.getOre("stickWood"), null, null)
        val n10 = 1
        val item7 = ItemBracketHandler.getItem("ExtraTrees:planks", 25)
        val hashMap7 = HashMap<String, IData>()
        hashMap7["meta"] = ExpandInt.toData(25)
        array7[n10] = item7.withTag(ExpandAnyDict.asData(hashMap7))
        array7[2] = OreBracketHandler.getOre("stickWood")
        array5[n9] = array7
        recipes2.addShaped(amount, array5, null)
        val recipes3 = MineTweakerAPI.recipes
        val item8 = ItemBracketHandler.getItem("ExtraTrees:fence", 57)
        val hashMap8 = HashMap<String, IData>()
        hashMap8["meta"] = ExpandInt.toData(57)
        val amount2 = item8.withTag(ExpandAnyDict.asData(hashMap8)).amount(4)
        val array8 = arrayOf(arrayOf<IIngredient?>(ore3, ore, ore3), null, null)
        val n11 = 1
        val array9 = arrayOf<IIngredient?>(OreBracketHandler.getOre("stickWood"), null, null)
        val n12 = 1
        val item9 = ItemBracketHandler.getItem("ExtraTrees:planks", 25)
        val hashMap9 = HashMap<String, IData>()
        hashMap9["meta"] = ExpandInt.toData(25)
        array9[n12] = item9.withTag(ExpandAnyDict.asData(hashMap9))
        array9[2] = OreBracketHandler.getOre("stickWood")
        array8[n11] = array9
        val n13 = 2
        val array10 = arrayOf<IIngredient?>(OreBracketHandler.getOre("stickWood"), null, null)
        val n14 = 1
        val item10 = ItemBracketHandler.getItem("ExtraTrees:planks", 25)
        val hashMap10 = HashMap<String, IData>()
        hashMap10["meta"] = ExpandInt.toData(25)
        array10[n14] = item10.withTag(ExpandAnyDict.asData(hashMap10))
        array10[2] = OreBracketHandler.getOre("stickWood")
        array8[n13] = array10
        recipes3.addShaped(amount2, array8, null)
        val recipes4 = MineTweakerAPI.recipes
        val item11 = ItemBracketHandler.getItem("ExtraTrees:fence", 58)
        val hashMap11 = HashMap<String, IData>()
        hashMap11["meta"] = ExpandInt.toData(58)
        val withTag2 = item11.withTag(ExpandAnyDict.asData(hashMap11))
        val array11: Array<Array<IIngredient?>?> = arrayOfNulls(3)
        val n15 = 0
        val array12 = arrayOf<IIngredient?>(OreBracketHandler.getOre("stickWood"), null, null)
        val n16 = 1
        val item12 = ItemBracketHandler.getItem("ExtraTrees:planks", 26)
        val hashMap12 = HashMap<String, IData>()
        hashMap12["meta"] = ExpandInt.toData(26)
        array12[n16] = item12.withTag(ExpandAnyDict.asData(hashMap12))
        array12[2] = OreBracketHandler.getOre("stickWood")
        array11[n15] = array12
        val n17 = 1
        val array13 = arrayOf<IIngredient?>(OreBracketHandler.getOre("stickWood"), null, null)
        val n18 = 1
        val item13 = ItemBracketHandler.getItem("ExtraTrees:planks", 26)
        val hashMap13 = HashMap<String, IData>()
        hashMap13["meta"] = ExpandInt.toData(26)
        array13[n18] = item13.withTag(ExpandAnyDict.asData(hashMap13))
        array13[2] = OreBracketHandler.getOre("stickWood")
        array11[n17] = array13
        val n19 = 2
        val array14 = arrayOf<IIngredient?>(OreBracketHandler.getOre("stickWood"), null, null)
        val n20 = 1
        val item14 = ItemBracketHandler.getItem("ExtraTrees:planks", 26)
        val hashMap14 = HashMap<String, IData>()
        hashMap14["meta"] = ExpandInt.toData(26)
        array14[n20] = item14.withTag(ExpandAnyDict.asData(hashMap14))
        array14[2] = OreBracketHandler.getOre("stickWood")
        array11[n19] = array14
        recipes4.addShaped(withTag2, array11, null)
        val recipes5 = MineTweakerAPI.recipes
        val item15 = ItemBracketHandler.getItem("ExtraTrees:fence", 58)
        val hashMap15 = HashMap<String, IData>()
        hashMap15["meta"] = ExpandInt.toData(58)
        val amount3 = item15.withTag(ExpandAnyDict.asData(hashMap15)).amount(2)
        val array15 = arrayOf(arrayOf<IIngredient?>(ore2, ore, ore2), null, null)
        val n21 = 1
        val array16 = arrayOf<IIngredient?>(OreBracketHandler.getOre("stickWood"), null, null)
        val n22 = 1
        val item16 = ItemBracketHandler.getItem("ExtraTrees:planks", 26)
        val hashMap16 = HashMap<String, IData>()
        hashMap16["meta"] = ExpandInt.toData(26)
        array16[n22] = item16.withTag(ExpandAnyDict.asData(hashMap16))
        array16[2] = OreBracketHandler.getOre("stickWood")
        array15[n21] = array16
        val n23 = 2
        val array17 = arrayOf<IIngredient?>(OreBracketHandler.getOre("stickWood"), null, null)
        val n24 = 1
        val item17 = ItemBracketHandler.getItem("ExtraTrees:planks", 26)
        val hashMap17 = HashMap<String, IData>()
        hashMap17["meta"] = ExpandInt.toData(26)
        array17[n24] = item17.withTag(ExpandAnyDict.asData(hashMap17))
        array17[2] = OreBracketHandler.getOre("stickWood")
        array15[n23] = array17
        recipes5.addShaped(amount3, array15, null)
        val recipes6 = MineTweakerAPI.recipes
        val item18 = ItemBracketHandler.getItem("ExtraTrees:fence", 58)
        val hashMap18 = HashMap<String, IData>()
        hashMap18["meta"] = ExpandInt.toData(58)
        val amount4 = item18.withTag(ExpandAnyDict.asData(hashMap18)).amount(4)
        val array18 = arrayOf(arrayOf<IIngredient?>(ore3, ore, ore3), null, null)
        val n25 = 1
        val array19 = arrayOf<IIngredient?>(OreBracketHandler.getOre("stickWood"), null, null)
        val n26 = 1
        val item19 = ItemBracketHandler.getItem("ExtraTrees:planks", 26)
        val hashMap19 = HashMap<String, IData>()
        hashMap19["meta"] = ExpandInt.toData(26)
        array19[n26] = item19.withTag(ExpandAnyDict.asData(hashMap19))
        array19[2] = OreBracketHandler.getOre("stickWood")
        array18[n25] = array19
        val n27 = 2
        val array20 = arrayOf<IIngredient?>(OreBracketHandler.getOre("stickWood"), null, null)
        val n28 = 1
        val item20 = ItemBracketHandler.getItem("ExtraTrees:planks", 26)
        val hashMap20 = HashMap<String, IData>()
        hashMap20["meta"] = ExpandInt.toData(26)
        array20[n28] = item20.withTag(ExpandAnyDict.asData(hashMap20))
        array20[2] = OreBracketHandler.getOre("stickWood")
        array18[n27] = array20
        recipes6.addShaped(amount4, array18, null)
        val recipes7 = MineTweakerAPI.recipes
        val item21 = ItemBracketHandler.getItem("ExtraTrees:fence", 59)
        val hashMap21 = HashMap<String, IData>()
        hashMap21["meta"] = ExpandInt.toData(59)
        val withTag3 = item21.withTag(ExpandAnyDict.asData(hashMap21))
        val array21: Array<Array<IIngredient?>?> = arrayOfNulls(3)
        val n29 = 0
        val array22 = arrayOf<IIngredient?>(OreBracketHandler.getOre("stickWood"), null, null)
        val n30 = 1
        val item22 = ItemBracketHandler.getItem("ExtraTrees:planks", 27)
        val hashMap22 = HashMap<String, IData>()
        hashMap22["meta"] = ExpandInt.toData(27)
        array22[n30] = item22.withTag(ExpandAnyDict.asData(hashMap22))
        array22[2] = OreBracketHandler.getOre("stickWood")
        array21[n29] = array22
        val n31 = 1
        val array23 = arrayOf<IIngredient?>(OreBracketHandler.getOre("stickWood"), null, null)
        val n32 = 1
        val item23 = ItemBracketHandler.getItem("ExtraTrees:planks", 27)
        val hashMap23 = HashMap<String, IData>()
        hashMap23["meta"] = ExpandInt.toData(27)
        array23[n32] = item23.withTag(ExpandAnyDict.asData(hashMap23))
        array23[2] = OreBracketHandler.getOre("stickWood")
        array21[n31] = array23
        val n33 = 2
        val array24 = arrayOf<IIngredient?>(OreBracketHandler.getOre("stickWood"), null, null)
        val n34 = 1
        val item24 = ItemBracketHandler.getItem("ExtraTrees:planks", 27)
        val hashMap24 = HashMap<String, IData>()
        hashMap24["meta"] = ExpandInt.toData(27)
        array24[n34] = item24.withTag(ExpandAnyDict.asData(hashMap24))
        array24[2] = OreBracketHandler.getOre("stickWood")
        array21[n33] = array24
        recipes7.addShaped(withTag3, array21, null)
        val recipes8 = MineTweakerAPI.recipes
        val item25 = ItemBracketHandler.getItem("ExtraTrees:fence", 59)
        val hashMap25 = HashMap<String, IData>()
        hashMap25["meta"] = ExpandInt.toData(59)
        val amount5 = item25.withTag(ExpandAnyDict.asData(hashMap25)).amount(2)
        val array25 = arrayOf(arrayOf<IIngredient?>(ore2, ore, ore2), null, null)
        val n35 = 1
        val array26 = arrayOf<IIngredient?>(OreBracketHandler.getOre("stickWood"), null, null)
        val n36 = 1
        val item26 = ItemBracketHandler.getItem("ExtraTrees:planks", 27)
        val hashMap26 = HashMap<String, IData>()
        hashMap26["meta"] = ExpandInt.toData(27)
        array26[n36] = item26.withTag(ExpandAnyDict.asData(hashMap26))
        array26[2] = OreBracketHandler.getOre("stickWood")
        array25[n35] = array26
        val n37 = 2
        val array27 = arrayOf<IIngredient?>(OreBracketHandler.getOre("stickWood"), null, null)
        val n38 = 1
        val item27 = ItemBracketHandler.getItem("ExtraTrees:planks", 27)
        val hashMap27 = HashMap<String, IData>()
        hashMap27["meta"] = ExpandInt.toData(27)
        array27[n38] = item27.withTag(ExpandAnyDict.asData(hashMap27))
        array27[2] = OreBracketHandler.getOre("stickWood")
        array25[n37] = array27
        recipes8.addShaped(amount5, array25, null)
        val recipes9 = MineTweakerAPI.recipes
        val item28 = ItemBracketHandler.getItem("ExtraTrees:fence", 59)
        val hashMap28 = HashMap<String, IData>()
        hashMap28["meta"] = ExpandInt.toData(59)
        val amount6 = item28.withTag(ExpandAnyDict.asData(hashMap28)).amount(4)
        val array28 = arrayOf(arrayOf<IIngredient?>(ore3, ore, ore3), null, null)
        val n39 = 1
        val array29 = arrayOf<IIngredient?>(OreBracketHandler.getOre("stickWood"), null, null)
        val n40 = 1
        val item29 = ItemBracketHandler.getItem("ExtraTrees:planks", 27)
        val hashMap29 = HashMap<String, IData>()
        hashMap29["meta"] = ExpandInt.toData(27)
        array29[n40] = item29.withTag(ExpandAnyDict.asData(hashMap29))
        array29[2] = OreBracketHandler.getOre("stickWood")
        array28[n39] = array29
        val n41 = 2
        val array30 = arrayOf<IIngredient?>(OreBracketHandler.getOre("stickWood"), null, null)
        val n42 = 1
        val item30 = ItemBracketHandler.getItem("ExtraTrees:planks", 27)
        val hashMap30 = HashMap<String, IData>()
        hashMap30["meta"] = ExpandInt.toData(27)
        array30[n42] = item30.withTag(ExpandAnyDict.asData(hashMap30))
        array30[2] = OreBracketHandler.getOre("stickWood")
        array28[n41] = array30
        recipes9.addShaped(amount6, array28, null)
        val recipes10 = MineTweakerAPI.recipes
        val item31 = ItemBracketHandler.getItem("ExtraTrees:fence", 60)
        val hashMap31 = HashMap<String, IData>()
        hashMap31["meta"] = ExpandInt.toData(60)
        val withTag4 = item31.withTag(ExpandAnyDict.asData(hashMap31))
        val array31: Array<Array<IIngredient?>?> = arrayOfNulls(3)
        val n43 = 0
        val array32 = arrayOf<IIngredient?>(OreBracketHandler.getOre("stickWood"), null, null)
        val n44 = 1
        val item32 = ItemBracketHandler.getItem("ExtraTrees:planks", 28)
        val hashMap32 = HashMap<String, IData>()
        hashMap32["meta"] = ExpandInt.toData(28)
        array32[n44] = item32.withTag(ExpandAnyDict.asData(hashMap32))
        array32[2] = OreBracketHandler.getOre("stickWood")
        array31[n43] = array32
        val n45 = 1
        val array33 = arrayOf<IIngredient?>(OreBracketHandler.getOre("stickWood"), null, null)
        val n46 = 1
        val item33 = ItemBracketHandler.getItem("ExtraTrees:planks", 28)
        val hashMap33 = HashMap<String, IData>()
        hashMap33["meta"] = ExpandInt.toData(28)
        array33[n46] = item33.withTag(ExpandAnyDict.asData(hashMap33))
        array33[2] = OreBracketHandler.getOre("stickWood")
        array31[n45] = array33
        val n47 = 2
        val array34 = arrayOf<IIngredient?>(OreBracketHandler.getOre("stickWood"), null, null)
        val n48 = 1
        val item34 = ItemBracketHandler.getItem("ExtraTrees:planks", 28)
        val hashMap34 = HashMap<String, IData>()
        hashMap34["meta"] = ExpandInt.toData(28)
        array34[n48] = item34.withTag(ExpandAnyDict.asData(hashMap34))
        array34[2] = OreBracketHandler.getOre("stickWood")
        array31[n47] = array34
        recipes10.addShaped(withTag4, array31, null)
        val recipes11 = MineTweakerAPI.recipes
        val item35 = ItemBracketHandler.getItem("ExtraTrees:fence", 60)
        val hashMap35 = HashMap<String, IData>()
        hashMap35["meta"] = ExpandInt.toData(60)
        val amount7 = item35.withTag(ExpandAnyDict.asData(hashMap35)).amount(2)
        val array35 = arrayOf(arrayOf<IIngredient?>(ore2, ore, ore2), null, null)
        val n49 = 1
        val array36 = arrayOf<IIngredient?>(OreBracketHandler.getOre("stickWood"), null, null)
        val n50 = 1
        val item36 = ItemBracketHandler.getItem("ExtraTrees:planks", 28)
        val hashMap36 = HashMap<String, IData>()
        hashMap36["meta"] = ExpandInt.toData(28)
        array36[n50] = item36.withTag(ExpandAnyDict.asData(hashMap36))
        array36[2] = OreBracketHandler.getOre("stickWood")
        array35[n49] = array36
        val n51 = 2
        val array37 = arrayOf<IIngredient?>(OreBracketHandler.getOre("stickWood"), null, null)
        val n52 = 1
        val item37 = ItemBracketHandler.getItem("ExtraTrees:planks", 28)
        val hashMap37 = HashMap<String, IData>()
        hashMap37["meta"] = ExpandInt.toData(28)
        array37[n52] = item37.withTag(ExpandAnyDict.asData(hashMap37))
        array37[2] = OreBracketHandler.getOre("stickWood")
        array35[n51] = array37
        recipes11.addShaped(amount7, array35, null)
        val recipes12 = MineTweakerAPI.recipes
        val item38 = ItemBracketHandler.getItem("ExtraTrees:fence", 60)
        val hashMap38 = HashMap<String, IData>()
        hashMap38["meta"] = ExpandInt.toData(60)
        val amount8 = item38.withTag(ExpandAnyDict.asData(hashMap38)).amount(4)
        val array38 = arrayOf(arrayOf<IIngredient?>(ore3, ore, ore3), null, null)
        val n53 = 1
        val array39 = arrayOf<IIngredient?>(OreBracketHandler.getOre("stickWood"), null, null)
        val n54 = 1
        val item39 = ItemBracketHandler.getItem("ExtraTrees:planks", 28)
        val hashMap39 = HashMap<String, IData>()
        hashMap39["meta"] = ExpandInt.toData(28)
        array39[n54] = item39.withTag(ExpandAnyDict.asData(hashMap39))
        array39[2] = OreBracketHandler.getOre("stickWood")
        array38[n53] = array39
        val n55 = 2
        val array40 = arrayOf<IIngredient?>(OreBracketHandler.getOre("stickWood"), null, null)
        val n56 = 1
        val item40 = ItemBracketHandler.getItem("ExtraTrees:planks", 28)
        val hashMap40 = HashMap<String, IData>()
        hashMap40["meta"] = ExpandInt.toData(28)
        array40[n56] = item40.withTag(ExpandAnyDict.asData(hashMap40))
        array40[2] = OreBracketHandler.getOre("stickWood")
        array38[n55] = array40
        recipes12.addShaped(amount8, array38, null)
        val recipes13 = MineTweakerAPI.recipes
        val item41 = ItemBracketHandler.getItem("ExtraTrees:fence", 61)
        val hashMap41 = HashMap<String, IData>()
        hashMap41["meta"] = ExpandInt.toData(61)
        val withTag5 = item41.withTag(ExpandAnyDict.asData(hashMap41))
        val array41: Array<Array<IIngredient?>?> = arrayOfNulls(3)
        val n57 = 0
        val array42 = arrayOf<IIngredient?>(OreBracketHandler.getOre("stickWood"), null, null)
        val n58 = 1
        val item42 = ItemBracketHandler.getItem("ExtraTrees:planks", 29)
        val hashMap42 = HashMap<String, IData>()
        hashMap42["meta"] = ExpandInt.toData(29)
        array42[n58] = item42.withTag(ExpandAnyDict.asData(hashMap42))
        array42[2] = OreBracketHandler.getOre("stickWood")
        array41[n57] = array42
        val n59 = 1
        val array43 = arrayOf<IIngredient?>(OreBracketHandler.getOre("stickWood"), null, null)
        val n60 = 1
        val item43 = ItemBracketHandler.getItem("ExtraTrees:planks", 29)
        val hashMap43 = HashMap<String, IData>()
        hashMap43["meta"] = ExpandInt.toData(29)
        array43[n60] = item43.withTag(ExpandAnyDict.asData(hashMap43))
        array43[2] = OreBracketHandler.getOre("stickWood")
        array41[n59] = array43
        val n61 = 2
        val array44 = arrayOf<IIngredient?>(OreBracketHandler.getOre("stickWood"), null, null)
        val n62 = 1
        val item44 = ItemBracketHandler.getItem("ExtraTrees:planks", 29)
        val hashMap44 = HashMap<String, IData>()
        hashMap44["meta"] = ExpandInt.toData(29)
        array44[n62] = item44.withTag(ExpandAnyDict.asData(hashMap44))
        array44[2] = OreBracketHandler.getOre("stickWood")
        array41[n61] = array44
        recipes13.addShaped(withTag5, array41, null)
        val recipes14 = MineTweakerAPI.recipes
        val item45 = ItemBracketHandler.getItem("ExtraTrees:fence", 61)
        val hashMap45 = HashMap<String, IData>()
        hashMap45["meta"] = ExpandInt.toData(61)
        val amount9 = item45.withTag(ExpandAnyDict.asData(hashMap45)).amount(2)
        val array45 = arrayOf(arrayOf<IIngredient?>(ore2, ore, ore2), null, null)
        val n63 = 1
        val array46 = arrayOf<IIngredient?>(OreBracketHandler.getOre("stickWood"), null, null)
        val n64 = 1
        val item46 = ItemBracketHandler.getItem("ExtraTrees:planks", 29)
        val hashMap46 = HashMap<String, IData>()
        hashMap46["meta"] = ExpandInt.toData(29)
        array46[n64] = item46.withTag(ExpandAnyDict.asData(hashMap46))
        array46[2] = OreBracketHandler.getOre("stickWood")
        array45[n63] = array46
        val n65 = 2
        val array47 = arrayOf<IIngredient?>(OreBracketHandler.getOre("stickWood"), null, null)
        val n66 = 1
        val item47 = ItemBracketHandler.getItem("ExtraTrees:planks", 29)
        val hashMap47 = HashMap<String, IData>()
        hashMap47["meta"] = ExpandInt.toData(29)
        array47[n66] = item47.withTag(ExpandAnyDict.asData(hashMap47))
        array47[2] = OreBracketHandler.getOre("stickWood")
        array45[n65] = array47
        recipes14.addShaped(amount9, array45, null)
        val recipes15 = MineTweakerAPI.recipes
        val item48 = ItemBracketHandler.getItem("ExtraTrees:fence", 61)
        val hashMap48 = HashMap<String, IData>()
        hashMap48["meta"] = ExpandInt.toData(61)
        val amount10 = item48.withTag(ExpandAnyDict.asData(hashMap48)).amount(4)
        val array48 = arrayOf(arrayOf<IIngredient?>(ore3, ore, ore3), null, null)
        val n67 = 1
        val array49 = arrayOf<IIngredient?>(OreBracketHandler.getOre("stickWood"), null, null)
        val n68 = 1
        val item49 = ItemBracketHandler.getItem("ExtraTrees:planks", 29)
        val hashMap49 = HashMap<String, IData>()
        hashMap49["meta"] = ExpandInt.toData(29)
        array49[n68] = item49.withTag(ExpandAnyDict.asData(hashMap49))
        array49[2] = OreBracketHandler.getOre("stickWood")
        array48[n67] = array49
        val n69 = 2
        val array50 = arrayOf<IIngredient?>(OreBracketHandler.getOre("stickWood"), null, null)
        val n70 = 1
        val item50 = ItemBracketHandler.getItem("ExtraTrees:planks", 29)
        val hashMap50 = HashMap<String, IData>()
        hashMap50["meta"] = ExpandInt.toData(29)
        array50[n70] = item50.withTag(ExpandAnyDict.asData(hashMap50))
        array50[2] = OreBracketHandler.getOre("stickWood")
        array48[n69] = array50
        recipes15.addShaped(amount10, array48, null)
        val recipes16 = MineTweakerAPI.recipes
        val item51 = ItemBracketHandler.getItem("ExtraTrees:fence", 62)
        val hashMap51 = HashMap<String, IData>()
        hashMap51["meta"] = ExpandInt.toData(62)
        val withTag6 = item51.withTag(ExpandAnyDict.asData(hashMap51))
        val array51: Array<Array<IIngredient?>?> = arrayOfNulls(3)
        val n71 = 0
        val array52 = arrayOf<IIngredient?>(OreBracketHandler.getOre("stickWood"), null, null)
        val n72 = 1
        val item52 = ItemBracketHandler.getItem("ExtraTrees:planks", 30)
        val hashMap52 = HashMap<String, IData>()
        hashMap52["meta"] = ExpandInt.toData(30)
        array52[n72] = item52.withTag(ExpandAnyDict.asData(hashMap52))
        array52[2] = OreBracketHandler.getOre("stickWood")
        array51[n71] = array52
        val n73 = 1
        val array53 = arrayOf<IIngredient?>(OreBracketHandler.getOre("stickWood"), null, null)
        val n74 = 1
        val item53 = ItemBracketHandler.getItem("ExtraTrees:planks", 30)
        val hashMap53 = HashMap<String, IData>()
        hashMap53["meta"] = ExpandInt.toData(30)
        array53[n74] = item53.withTag(ExpandAnyDict.asData(hashMap53))
        array53[2] = OreBracketHandler.getOre("stickWood")
        array51[n73] = array53
        val n75 = 2
        val array54 = arrayOf<IIngredient?>(OreBracketHandler.getOre("stickWood"), null, null)
        val n76 = 1
        val item54 = ItemBracketHandler.getItem("ExtraTrees:planks", 30)
        val hashMap54 = HashMap<String, IData>()
        hashMap54["meta"] = ExpandInt.toData(30)
        array54[n76] = item54.withTag(ExpandAnyDict.asData(hashMap54))
        array54[2] = OreBracketHandler.getOre("stickWood")
        array51[n75] = array54
        recipes16.addShaped(withTag6, array51, null)
        val recipes17 = MineTweakerAPI.recipes
        val item55 = ItemBracketHandler.getItem("ExtraTrees:fence", 62)
        val hashMap55 = HashMap<String, IData>()
        hashMap55["meta"] = ExpandInt.toData(62)
        val amount11 = item55.withTag(ExpandAnyDict.asData(hashMap55)).amount(2)
        val array55 = arrayOf(arrayOf<IIngredient?>(ore2, ore, ore2), null, null)
        val n77 = 1
        val array56 = arrayOf<IIngredient?>(OreBracketHandler.getOre("stickWood"), null, null)
        val n78 = 1
        val item56 = ItemBracketHandler.getItem("ExtraTrees:planks", 30)
        val hashMap56 = HashMap<String, IData>()
        hashMap56["meta"] = ExpandInt.toData(30)
        array56[n78] = item56.withTag(ExpandAnyDict.asData(hashMap56))
        array56[2] = OreBracketHandler.getOre("stickWood")
        array55[n77] = array56
        val n79 = 2
        val array57 = arrayOf<IIngredient?>(OreBracketHandler.getOre("stickWood"), null, null)
        val n80 = 1
        val item57 = ItemBracketHandler.getItem("ExtraTrees:planks", 30)
        val hashMap57 = HashMap<String, IData>()
        hashMap57["meta"] = ExpandInt.toData(30)
        array57[n80] = item57.withTag(ExpandAnyDict.asData(hashMap57))
        array57[2] = OreBracketHandler.getOre("stickWood")
        array55[n79] = array57
        recipes17.addShaped(amount11, array55, null)
    }
}