package com.github.GTNH2Mega.fromScripts;
import gttweaker.mods.gregtech.machines.AlloySmelter;
import gttweaker.mods.gregtech.machines.Assembler;
import minetweaker.MineTweakerAPI;
import minetweaker.api.item.IIngredient;
import minetweaker.api.item.IItemStack;
import minetweaker.api.item.IngredientAny;
import minetweaker.api.liquid.ILiquidStack;
import minetweaker.api.oredict.IOreDictEntry;
import minetweaker.api.recipes.IRecipeFunction;
import minetweaker.mc1710.brackets.ItemBracketHandler;
import minetweaker.mc1710.brackets.LiquidBracketHandler;
import minetweaker.mc1710.brackets.OreBracketHandler;
import minetweaker.mods.ic2.machines.Compressor;
import minetweaker.mods.ic2.machines.Extractor;
import modtweaker2.mods.extraUtils.handlers.QED;
import modtweaker2.mods.tconstruct.handlers.Casting;
import static com.github.GTNH2Mega.VoltageLevels.*;
public class ExtraUtilities
implements Runnable {
    public void run() {
        IItemStack iItemStack = ItemBracketHandler.getItem((String)"ExtraUtilities:enderThermicPump", (int)0);
        IItemStack iItemStack2 = ItemBracketHandler.getItem((String)"ExtraUtilities:decorativeBlock1", (int)1);
        IItemStack iItemStack3 = ItemBracketHandler.getItem((String)"ExtraUtilities:decorativeBlock1", (int)11);
        IItemStack iItemStack4 = ItemBracketHandler.getItem((String)"ExtraUtilities:decorativeBlock1", (int)8);
        IItemStack iItemStack5 = ItemBracketHandler.getItem((String)"ExtraUtilities:decorativeBlock1", (int)12);
        IItemStack iItemStack6 = ItemBracketHandler.getItem((String)"ExtraUtilities:decorativeBlock1", (int)2);
        IOreDictEntry iOreDictEntry = OreBracketHandler.getOre((String)"stickTungstenSteel");
        IItemStack iItemStack7 = ItemBracketHandler.getItem((String)"ExtraUtilities:enderQuarryUpgrade", (int)0);
        IItemStack iItemStack8 = ItemBracketHandler.getItem((String)"ExtraUtilities:cobblestone_compressed", (int)6);
        IItemStack iItemStack9 = ItemBracketHandler.getItem((String)"ExtraUtilities:cobblestone_compressed", (int)11);
        IOreDictEntry iOreDictEntry2 = OreBracketHandler.getOre((String)"plankWood");
        IOreDictEntry iOreDictEntry3 = OreBracketHandler.getOre((String)"pipeSmallStainlessSteel");
        IItemStack iItemStack10 = ItemBracketHandler.getItem((String)"ExtraUtilities:paintbrush", (int)0);
        IItemStack iItemStack11 = ItemBracketHandler.getItem((String)"harvestcraft:wovencottonItem", (int)0);
        IItemStack iItemStack12 = ItemBracketHandler.getItem((String)"TConstruct:materials", (int)26);
        IItemStack iItemStack13 = ItemBracketHandler.getItem((String)"ExtraUtilities:timer", (int)0);
        IItemStack iItemStack14 = ItemBracketHandler.getItem((String)"minecraft:clock", (int)0);
        IItemStack iItemStack15 = ItemBracketHandler.getItem((String)"ExtraUtilities:drum", (int)0);
        IItemStack iItemStack16 = ItemBracketHandler.getItem((String)"ExtraUtilities:drum", (int)1);
        IItemStack iItemStack17 = ItemBracketHandler.getItem((String)"minecraft:cauldron", (int)0);
        IItemStack iItemStack18 = ItemBracketHandler.getItem((String)"ExtraUtilities:bedrockiumIngot", (int)0);
        IItemStack iItemStack19 = ItemBracketHandler.getItem((String)"ExtraUtilities:block_bedrockium", (int)0);
        IItemStack iItemStack20 = ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)2816);
        IItemStack iItemStack21 = ItemBracketHandler.getItem((String)"ExtraUtilities:angelBlock", (int)0);
        IItemStack iItemStack22 = ItemBracketHandler.getItem((String)"ExtraUtilities:conveyor", (int)0);
        IItemStack iItemStack23 = ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)32631);
        IItemStack iItemStack24 = ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)32601);
        IItemStack iItemStack25 = ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)32641);
        IItemStack iItemStack26 = ItemBracketHandler.getItem((String)"minecraft:iron_bars", (int)0);
        IItemStack iItemStack27 = ItemBracketHandler.getItem((String)"dreamcraft:item.SteelBars", (int)0);
        IItemStack iItemStack28 = ItemBracketHandler.getItem((String)"ExtraUtilities:filing", (int)0);
        IItemStack iItemStack29 = ItemBracketHandler.getItem((String)"ExtraUtilities:filing", (int)1);
        IItemStack iItemStack30 = ItemBracketHandler.getItem((String)"ExtraUtilities:watering_can", (int)1);
        IItemStack iItemStack31 = ItemBracketHandler.getItem((String)"IC2:blockMachine2", (int)11);
        IItemStack iItemStack32 = ItemBracketHandler.getItem((String)"IC2:blockMachine", (int)7);
        IOreDictEntry iOreDictEntry4 = OreBracketHandler.getOre((String)"gearStainlessSteel");
        IItemStack iItemStack33 = ItemBracketHandler.getItem((String)"TwilightForest:tile.TFTowerDevice", (int)12);
        IItemStack iItemStack34 = ItemBracketHandler.getItem((String)"TConstruct:ore.berries.two", (int)9);
        IItemStack iItemStack35 = ItemBracketHandler.getItem((String)"ExtraUtilities:sound_muffler", (int)0);
        IItemStack iItemStack36 = ItemBracketHandler.getItem((String)"ExtraUtilities:sound_muffler", (int)1);
        IOreDictEntry iOreDictEntry5 = OreBracketHandler.getOre((String)"blockWool");
        IItemStack iItemStack37 = ItemBracketHandler.getItem((String)"minecraft:noteblock", (int)0);
        IItemStack iItemStack38 = ItemBracketHandler.getItem((String)"ExtraUtilities:budoff", (int)0);
        IItemStack iItemStack39 = ItemBracketHandler.getItem((String)"minecraft:water_bucket", (int)0);
        IItemStack iItemStack40 = ItemBracketHandler.getItem((String)"gregtech:gt.blockmachines", (int)9271);
        IItemStack iItemStack41 = ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)32675);
        IItemStack iItemStack42 = ItemBracketHandler.getItem((String)"gregtech:gt.blockmachines", (int)11102);
        IItemStack iItemStack43 = ItemBracketHandler.getItem((String)"gregtech:gt.blockmachines", (int)11103);
        IItemStack iItemStack44 = ItemBracketHandler.getItem((String)"gregtech:gt.blockmachines", (int)11104);
        IItemStack iItemStack45 = ItemBracketHandler.getItem((String)"ExtraUtilities:nodeUpgrade", (int)0);
        IItemStack iItemStack46 = ItemBracketHandler.getItem((String)"ExtraUtilities:nodeUpgrade", (int)1);
        IItemStack iItemStack47 = ItemBracketHandler.getItem((String)"ExtraUtilities:nodeUpgrade", (int)2);
        IItemStack iItemStack48 = ItemBracketHandler.getItem((String)"ExtraUtilities:nodeUpgrade", (int)3);
        IItemStack iItemStack49 = ItemBracketHandler.getItem((String)"ExtraUtilities:nodeUpgrade", (int)5);
        IItemStack iItemStack50 = ItemBracketHandler.getItem((String)"ExtraUtilities:nodeUpgrade", (int)6);
        IItemStack iItemStack51 = ItemBracketHandler.getItem((String)"ExtraUtilities:nodeUpgrade", (int)7);
        IItemStack iItemStack52 = ItemBracketHandler.getItem((String)"ExtraUtilities:nodeUpgrade", (int)8);
        IItemStack iItemStack53 = ItemBracketHandler.getItem((String)"ExtraUtilities:nodeUpgrade", (int)9);
        IOreDictEntry iOreDictEntry6 = OreBracketHandler.getOre((String)"stickRedAlloy");
        IOreDictEntry iOreDictEntry7 = OreBracketHandler.getOre((String)"gearBronze");
        IOreDictEntry iOreDictEntry8 = OreBracketHandler.getOre((String)"plateWood");
        IOreDictEntry iOreDictEntry9 = OreBracketHandler.getOre((String)"plateAnyIron");
        IOreDictEntry iOreDictEntry10 = OreBracketHandler.getOre((String)"plateGold");
        IOreDictEntry iOreDictEntry11 = OreBracketHandler.getOre((String)"plateDiamond");
        IOreDictEntry iOreDictEntry12 = OreBracketHandler.getOre((String)"ringSteel");
        IOreDictEntry iOreDictEntry13 = OreBracketHandler.getOre((String)"gearStainlessSteel");
        IOreDictEntry iOreDictEntry14 = OreBracketHandler.getOre((String)"stickAnyIron");
        IOreDictEntry iOreDictEntry15 = OreBracketHandler.getOre((String)"plateSteel");
        IOreDictEntry iOreDictEntry16 = OreBracketHandler.getOre((String)"plateAluminium");
        IOreDictEntry iOreDictEntry17 = OreBracketHandler.getOre((String)"gearDiamond");
        IItemStack iItemStack54 = ItemBracketHandler.getItem((String)"minecraft:heavy_weighted_pressure_plate", (int)0);
        IOreDictEntry iOreDictEntry18 = OreBracketHandler.getOre((String)"plateStainlessSteel");
        IOreDictEntry iOreDictEntry19 = OreBracketHandler.getOre((String)"foilSteel");
        IOreDictEntry iOreDictEntry20 = OreBracketHandler.getOre((String)"screwSteel");
        IOreDictEntry iOreDictEntry21 = OreBracketHandler.getOre((String)"plateRedAlloy");
        IOreDictEntry iOreDictEntry22 = OreBracketHandler.getOre((String)"foilRedAlloy");
        IOreDictEntry iOreDictEntry23 = OreBracketHandler.getOre((String)"plateElectrum");
        IOreDictEntry iOreDictEntry24 = OreBracketHandler.getOre((String)"plateEuropium");
        IOreDictEntry iOreDictEntry25 = OreBracketHandler.getOre((String)"foilElectrum");
        IOreDictEntry iOreDictEntry26 = OreBracketHandler.getOre((String)"plateEnderPearl");
        IOreDictEntry iOreDictEntry27 = OreBracketHandler.getOre((String)"plateEnderEye");
        IOreDictEntry iOreDictEntry28 = OreBracketHandler.getOre((String)"plateNetherStar");
        IOreDictEntry iOreDictEntry29 = OreBracketHandler.getOre((String)"gearSteel");
        IOreDictEntry iOreDictEntry30 = OreBracketHandler.getOre((String)"gearTitanium");
        IOreDictEntry iOreDictEntry31 = OreBracketHandler.getOre((String)"plateTitanium");
        IOreDictEntry iOreDictEntry32 = OreBracketHandler.getOre((String)"plateChrome");
        IOreDictEntry iOreDictEntry33 = OreBracketHandler.getOre((String)"circuitBasic");
        IOreDictEntry iOreDictEntry34 = OreBracketHandler.getOre((String)"circuitGood");
        IOreDictEntry iOreDictEntry35 = OreBracketHandler.getOre((String)"circuitAdvanced");
        IOreDictEntry iOreDictEntry36 = OreBracketHandler.getOre((String)"circuitData");
        IItemStack iItemStack55 = ItemBracketHandler.getItem((String)"gregtech:gt.blockmachines", (int)9231);
        IItemStack iItemStack56 = ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)32610);
        IItemStack iItemStack57 = ItemBracketHandler.getItem((String)"gregtech:gt.blockmachines", (int)171);
        IItemStack iItemStack58 = ItemBracketHandler.getItem((String)"gregtech:gt.blockmachines", (int)173);
        IOreDictEntry iOreDictEntry37 = OreBracketHandler.getOre((String)"cableGt12Copper");
        IOreDictEntry iOreDictEntry38 = OreBracketHandler.getOre((String)"cableGt12Electrum");
        IOreDictEntry iOreDictEntry39 = OreBracketHandler.getOre((String)"pipeMediumBrass");
        IItemStack iItemStack59 = ItemBracketHandler.getItem((String)"BuildCraft|Factory:tankBlock", (int)0);
        IOreDictEntry iOreDictEntry40 = OreBracketHandler.getOre((String)"foilRoseGold");
        IItemStack iItemStack60 = ItemBracketHandler.getItem((String)"minecraft:diamond_pickaxe", (int)0);
        IItemStack iItemStack61 = ItemBracketHandler.getItem((String)"minecraft:iron_pickaxe", (int)0);
        IOreDictEntry iOreDictEntry41 = OreBracketHandler.getOre((String)"plateDenseLapis");
        IOreDictEntry iOreDictEntry42 = OreBracketHandler.getOre((String)"plateDenseObsidian");
        IOreDictEntry iOreDictEntry43 = OreBracketHandler.getOre((String)"cellHelium_3");
        IItemStack iItemStack62 = ItemBracketHandler.getItem((String)"IronChest:BlockIronChest", (int)0);
        IOreDictEntry iOreDictEntry44 = OreBracketHandler.getOre((String)"gearWood");
        IOreDictEntry iOreDictEntry45 = OreBracketHandler.getOre((String)"stone");
        IOreDictEntry iOreDictEntry46 = OreBracketHandler.getOre((String)"ringRedAlloy");
        IOreDictEntry iOreDictEntry47 = OreBracketHandler.getOre((String)"plateLapis");
        IItemStack iItemStack63 = ItemBracketHandler.getItem((String)"ExtraUtilities:pipes", (int)0);
        IItemStack iItemStack64 = ItemBracketHandler.getItem((String)"ExtraUtilities:pipes", (int)8);
        IItemStack iItemStack65 = ItemBracketHandler.getItem((String)"ExtraUtilities:pipes", (int)9);
        IItemStack iItemStack66 = ItemBracketHandler.getItem((String)"ExtraUtilities:pipes", (int)10);
        IItemStack iItemStack67 = ItemBracketHandler.getItem((String)"ExtraUtilities:pipes.1", (int)0);
        IItemStack iItemStack68 = ItemBracketHandler.getItem((String)"ExtraUtilities:pipes", (int)11);
        IItemStack iItemStack69 = ItemBracketHandler.getItem((String)"ExtraUtilities:pipes", (int)12);
        IItemStack iItemStack70 = ItemBracketHandler.getItem((String)"ExtraUtilities:pipes", (int)13);
        IItemStack iItemStack71 = ItemBracketHandler.getItem((String)"ExtraUtilities:pipes", (int)14);
        IItemStack iItemStack72 = ItemBracketHandler.getItem((String)"ExtraUtilities:pipes", (int)32767);
        IItemStack iItemStack73 = ItemBracketHandler.getItem((String)"ExtraUtilities:extractor_base_remote", (int)0);
        IItemStack iItemStack74 = ItemBracketHandler.getItem((String)"ExtraUtilities:extractor_base_remote", (int)6);
        IItemStack iItemStack75 = ItemBracketHandler.getItem((String)"ExtraUtilities:extractor_base", (int)0);
        IItemStack iItemStack76 = ItemBracketHandler.getItem((String)"ExtraUtilities:extractor_base", (int)6);
        IItemStack iItemStack77 = ItemBracketHandler.getItem((String)"ExtraUtilities:extractor_base", (int)12);
        IItemStack iItemStack78 = ItemBracketHandler.getItem((String)"ExtraUtilities:extractor_base", (int)13);
        IItemStack iItemStack79 = ItemBracketHandler.getItem((String)"ExtraUtilities:magnumTorch", (int)0);
        IItemStack iItemStack80 = ItemBracketHandler.getItem((String)"ExtraUtilities:chandelier", (int)0);
        IItemStack iItemStack81 = ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)1);
        IOreDictEntry iOreDictEntry48 = OreBracketHandler.getOre((String)"stickStainlessSteel");
        IOreDictEntry iOreDictEntry49 = OreBracketHandler.getOre((String)"plateThaumium");
        IItemStack iItemStack82 = ItemBracketHandler.getItem((String)"Thaumcraft:blockMagicalLog", (int)1);
        IItemStack iItemStack83 = ItemBracketHandler.getItem((String)"Thaumcraft:blockMagicalLog", (int)0);
        IItemStack iItemStack84 = ItemBracketHandler.getItem((String)"gregtech:gt.blockmachines", (int)5132);
        IItemStack iItemStack85 = ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.02", (int)20305);
        IItemStack iItemStack86 = ItemBracketHandler.getItem((String)"BuildCraft|Transport:item.buildcraftPipe.pipepowerdiamond", (int)0);
        IOreDictEntry iOreDictEntry50 = OreBracketHandler.getOre((String)"logWood");
        IOreDictEntry iOreDictEntry51 = OreBracketHandler.getOre((String)"plankWood");
        IOreDictEntry iOreDictEntry52 = OreBracketHandler.getOre((String)"screwWood");
        IOreDictEntry iOreDictEntry53 = OreBracketHandler.getOre((String)"blockIron");
        IOreDictEntry iOreDictEntry54 = OreBracketHandler.getOre((String)"ingotIron");
        IOreDictEntry iOreDictEntry55 = OreBracketHandler.getOre((String)"screwIron");
        IOreDictEntry iOreDictEntry56 = OreBracketHandler.getOre((String)"blockGold");
        IOreDictEntry iOreDictEntry57 = OreBracketHandler.getOre((String)"ingotGold");
        IOreDictEntry iOreDictEntry58 = OreBracketHandler.getOre((String)"screwGold");
        IOreDictEntry iOreDictEntry59 = OreBracketHandler.getOre((String)"blockDiamond");
        IOreDictEntry iOreDictEntry60 = OreBracketHandler.getOre((String)"gemDiamond");
        IOreDictEntry iOreDictEntry61 = OreBracketHandler.getOre((String)"screwDiamond");
        IOreDictEntry iOreDictEntry62 = OreBracketHandler.getOre((String)"craftingToolHardHammer");
        IOreDictEntry iOreDictEntry63 = OreBracketHandler.getOre((String)"craftingToolWrench");
        IOreDictEntry iOreDictEntry64 = OreBracketHandler.getOre((String)"craftingToolScrewdriver");
        IOreDictEntry iOreDictEntry65 = OreBracketHandler.getOre((String)"craftingToolSaw");
        IItemStack iItemStack87 = ItemBracketHandler.getItem((String)"minecraft:shears", (int)0);
        QED.removeRecipe((IIngredient)IngredientAny.INSTANCE);
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:enderQuarry", (int)0));
        MineTweakerAPI.recipes.remove((IIngredient)iItemStack);
        MineTweakerAPI.furnace.remove((IIngredient)iItemStack6, null);
        MineTweakerAPI.recipes.remove((IIngredient)iItemStack2);
        MineTweakerAPI.recipes.remove((IIngredient)iItemStack4);
        MineTweakerAPI.recipes.remove((IIngredient)iItemStack3);
        MineTweakerAPI.recipes.remove((IIngredient)iItemStack5);
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:curtains", (int)0));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:timer", (int)0));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:decorativeBlock2", (int)7));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:decorativeBlock2", (int)5));
        MineTweakerAPI.recipes.remove((IIngredient)iItemStack7);
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:enderQuarryUpgrade", (int)1));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:enderQuarryUpgrade", (int)2));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:enderQuarryUpgrade", (int)3));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:enderQuarryUpgrade", (int)4));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:enderQuarryUpgrade", (int)5));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:enderQuarryUpgrade", (int)6));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:enderQuarryUpgrade", (int)7));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:enderQuarryUpgrade", (int)8));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:enderQuarryUpgrade", (int)9));
        MineTweakerAPI.recipes.remove((IIngredient)iItemStack45);
        MineTweakerAPI.recipes.remove((IIngredient)iItemStack46);
        MineTweakerAPI.recipes.remove((IIngredient)iItemStack47);
        MineTweakerAPI.recipes.remove((IIngredient)iItemStack48);
        MineTweakerAPI.recipes.remove((IIngredient)iItemStack49);
        MineTweakerAPI.recipes.remove((IIngredient)iItemStack50);
        MineTweakerAPI.recipes.remove((IIngredient)iItemStack51);
        MineTweakerAPI.recipes.remove((IIngredient)iItemStack52);
        MineTweakerAPI.recipes.remove((IIngredient)iItemStack53);
        MineTweakerAPI.recipes.remove((IIngredient)iItemStack10);
        MineTweakerAPI.recipes.remove((IIngredient)iItemStack15);
        MineTweakerAPI.recipes.remove((IIngredient)iItemStack16);
        MineTweakerAPI.recipes.remove((IIngredient)iItemStack18);
        Casting.removeTableRecipe((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:bedrockiumIngot", (int)0), null, null);
        MineTweakerAPI.recipes.remove((IIngredient)iItemStack19);
        MineTweakerAPI.furnace.remove((IIngredient)iItemStack19, null);
        Casting.removeBasinRecipe((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:block_bedrockium", (int)0), null, null);
        MineTweakerAPI.recipes.remove((IIngredient)iItemStack21);
        MineTweakerAPI.recipes.remove((IIngredient)iItemStack22);
        MineTweakerAPI.recipes.remove((IIngredient)iItemStack28);
        MineTweakerAPI.recipes.remove((IIngredient)iItemStack29);
        MineTweakerAPI.recipes.remove((IIngredient)iItemStack30);
        MineTweakerAPI.recipes.remove((IIngredient)iItemStack79);
        MineTweakerAPI.recipes.remove((IIngredient)iItemStack35);
        MineTweakerAPI.recipes.remove((IIngredient)iItemStack36);
        MineTweakerAPI.recipes.remove((IIngredient)iItemStack63);
        MineTweakerAPI.recipes.remove((IIngredient)iItemStack64);
        MineTweakerAPI.recipes.remove((IIngredient)iItemStack65);
        MineTweakerAPI.recipes.remove((IIngredient)iItemStack66);
        MineTweakerAPI.recipes.remove((IIngredient)iItemStack67);
        MineTweakerAPI.recipes.remove((IIngredient)iItemStack68);
        MineTweakerAPI.recipes.remove((IIngredient)iItemStack69);
        MineTweakerAPI.recipes.remove((IIngredient)iItemStack70);
        MineTweakerAPI.recipes.remove((IIngredient)iItemStack71);
        MineTweakerAPI.recipes.remove((IIngredient)iItemStack73);
        MineTweakerAPI.recipes.remove((IIngredient)iItemStack74);
        MineTweakerAPI.recipes.remove((IIngredient)iItemStack75);
        MineTweakerAPI.recipes.remove((IIngredient)iItemStack76);
        MineTweakerAPI.recipes.remove((IIngredient)iItemStack77);
        MineTweakerAPI.recipes.remove((IIngredient)iItemStack78);
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:cobblestone_compressed", (int)0));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:cobblestone_compressed", (int)1));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:cobblestone_compressed", (int)2));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:cobblestone_compressed", (int)3));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:cobblestone_compressed", (int)4));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:cobblestone_compressed", (int)5));
        MineTweakerAPI.recipes.remove((IIngredient)iItemStack8);
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:cobblestone_compressed", (int)7));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:cobblestone_compressed", (int)8));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:cobblestone_compressed", (int)9));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:cobblestone_compressed", (int)10));
        MineTweakerAPI.recipes.remove((IIngredient)iItemStack9);
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:cobblestone_compressed", (int)12));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:cobblestone_compressed", (int)13));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:cobblestone_compressed", (int)14));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:cobblestone_compressed", (int)15));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:trashcan", (int)0));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:trashcan", (int)1));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:trashcan", (int)2));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:decorativeBlock2", (int)0));
        MineTweakerAPI.furnace.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:decorativeBlock2", (int)0), null);
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:decorativeBlock1", (int)9));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:decorativeBlock2", (int)4));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:decorativeBlock2", (int)1));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:decorativeBlock2", (int)2));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:decorativeBlock2", (int)3));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:decorativeBlock2", (int)6));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:decorativeBlock2", (int)8));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:decorativeBlock2", (int)9));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:decorativeBlock2", (int)10));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:decorativeBlock2", (int)11));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:decorativeBlock1", (int)14));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:dark_portal", (int)2));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:dark_portal", (int)0));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:chestFull", (int)0));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:chestMini", (int)0));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:enderCollector", (int)0));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:endConstructor", (int)0));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:endConstructor", (int)2));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:budoff", (int)0));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:budoff", (int)3));
        MineTweakerAPI.recipes.remove((IIngredient)iItemStack80);
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:decorativeBlock1", (int)0));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:decorativeBlock1", (int)4));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:decorativeBlock1", (int)7));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:decorativeBlock1", (int)6));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:decorativeBlock1", (int)3));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:decorativeBlock1", (int)13));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:decorativeBlock1", (int)10));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:trading_post", (int)0));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:spike_base_wood", (int)0));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:spike_base", (int)0));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:spike_base_gold", (int)0));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:spike_base_diamond", (int)0));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:generator", (int)32767));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:generator.8", (int)32767));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:generator.64", (int)32767));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:heatingElement", (int)0));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:nodeUpgrade", (int)10));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:golden_lasso", (int)0));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:scanner", (int)0));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:builderswand", (int)0));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:creativebuilderswand", (int)0));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:shears", (int)0));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:ethericsword", (int)0));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:lawSword", (int)0));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:erosionShovel", (int)0));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:destructionpickaxe", (int)0));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:defoliageAxe", (int)0));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:temporalHoe", (int)0));
        Casting.removeBasinRecipe((IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:decorativeBlock1", (int)5), null, null);
        QED.addShapedRecipe((IItemStack)ItemBracketHandler.getItem((String)"AdvancedSolarPanel:BlockMolecularTransformer", (int)0), (IIngredient[][])new IIngredient[][]{{ItemBracketHandler.getItem((String)"IC2:blockMachine", (int)12), ItemBracketHandler.getItem((String)"IC2:blockElectric", (int)5), ItemBracketHandler.getItem((String)"IC2:blockMachine", (int)12)}, {OreBracketHandler.getOre((String)"circuitAdvanced"), ItemBracketHandler.getItem((String)"AdvancedSolarPanel:asp_crafting_items", (int)12), OreBracketHandler.getOre((String)"circuitAdvanced")}, {ItemBracketHandler.getItem((String)"IC2:blockMachine", (int)12), ItemBracketHandler.getItem((String)"IC2:blockElectric", (int)5), ItemBracketHandler.getItem((String)"IC2:blockMachine", (int)12)}});
        QED.addShapedRecipe((IItemStack)ItemBracketHandler.getItem((String)"ExtraUtilities:enderQuarry", (int)0), (IIngredient[][])new IIngredient[][]{{iOreDictEntry24, iItemStack41, iOreDictEntry24}, {iItemStack, iItemStack5, iItemStack}, {iItemStack3, iItemStack31, iItemStack3}});
        QED.addShapedRecipe((IItemStack)iItemStack, (IIngredient[][])new IIngredient[][]{{iItemStack2, OreBracketHandler.getOre((String)"circuitData"), iItemStack2}, {ItemBracketHandler.getItem((String)"BuildCraft|Factory:tankBlock", (int)0), iItemStack3, ItemBracketHandler.getItem((String)"BuildCraft|Factory:tankBlock", (int)0)}, {iItemStack2, ItemBracketHandler.getItem((String)"gregtech:gt.blockmachines", (int)1143), iItemStack2}});
        MineTweakerAPI.recipes.addShaped(iItemStack5, (IIngredient[][])new IIngredient[][]{{iItemStack3, OreBracketHandler.getOre((String)"plateDiamond"), iItemStack3}, {OreBracketHandler.getOre((String)"plateTitanium"), OreBracketHandler.getOre((String)"circuitData"), OreBracketHandler.getOre((String)"plateTitanium")}, {iItemStack3, OreBracketHandler.getOre((String)"plateDiamond"), iItemStack3}}, null);
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem((String)"ExtraUtilities:curtains", (int)0), (IIngredient[][])new IIngredient[][]{{ItemBracketHandler.getItem((String)"minecraft:carpet", (int)15), ItemBracketHandler.getItem((String)"minecraft:carpet", (int)15), null}, {ItemBracketHandler.getItem((String)"minecraft:carpet", (int)15), ItemBracketHandler.getItem((String)"minecraft:carpet", (int)15), null}, {ItemBracketHandler.getItem((String)"minecraft:carpet", (int)15), ItemBracketHandler.getItem((String)"minecraft:carpet", (int)15), null}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack13, (IIngredient[][])new IIngredient[][]{{iOreDictEntry21, iOreDictEntry44, iOreDictEntry21}, {iOreDictEntry44, iItemStack14, iOreDictEntry44}, {iOreDictEntry21, iOreDictEntry6, iOreDictEntry21}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack7, (IIngredient[][])new IIngredient[][]{{iItemStack2, OreBracketHandler.getOre((String)"plateStainlessSteel"), iItemStack2}, {OreBracketHandler.getOre((String)"plateStainlessSteel"), OreBracketHandler.getOre((String)"gemEnderEye"), OreBracketHandler.getOre((String)"plateStainlessSteel")}, {iItemStack2, OreBracketHandler.getOre((String)"plateStainlessSteel"), iItemStack2}}, null);
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem((String)"ExtraUtilities:enderQuarryUpgrade", (int)1), (IIngredient[][])new IIngredient[][]{{iItemStack7, ItemBracketHandler.getItem((String)"ExtraUtilities:cobblestone_compressed", (int)4), iItemStack7}, {iItemStack9, iOreDictEntry17, iItemStack9}, {iItemStack7, ItemBracketHandler.getItem((String)"ExtraUtilities:cobblestone_compressed", (int)4), iItemStack7}}, null);
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem((String)"ExtraUtilities:enderQuarryUpgrade", (int)2), (IIngredient[][])new IIngredient[][]{{iItemStack7, iItemStack12, iItemStack7}, {OreBracketHandler.getOre((String)"plateTitanium"), iOreDictEntry17, OreBracketHandler.getOre((String)"plateTitanium")}, {iItemStack7, iItemStack12, iItemStack7}}, null);
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem((String)"ExtraUtilities:enderQuarryUpgrade", (int)3), (IIngredient[][])new IIngredient[][]{{iItemStack7, OreBracketHandler.getOre((String)"plateTitanium"), iItemStack7}, {OreBracketHandler.getOre((String)"plateTitanium"), iOreDictEntry17, OreBracketHandler.getOre((String)"plateTitanium")}, {iItemStack7, OreBracketHandler.getOre((String)"plateTitanium"), iItemStack7}}, null);
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem((String)"ExtraUtilities:enderQuarryUpgrade", (int)4), (IIngredient[][])new IIngredient[][]{{iItemStack7, OreBracketHandler.getOre((String)"plateTungstenSteel"), iItemStack7}, {OreBracketHandler.getOre((String)"plateTungstenSteel"), ItemBracketHandler.getItem((String)"ExtraUtilities:enderQuarryUpgrade", (int)3), OreBracketHandler.getOre((String)"plateTungstenSteel")}, {iItemStack7, OreBracketHandler.getOre((String)"plateTungstenSteel"), iItemStack7}}, null);
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem((String)"ExtraUtilities:enderQuarryUpgrade", (int)5), (IIngredient[][])new IIngredient[][]{{iItemStack7, OreBracketHandler.getOre((String)"plateChrome"), iItemStack7}, {OreBracketHandler.getOre((String)"plateChrome"), ItemBracketHandler.getItem((String)"ExtraUtilities:enderQuarryUpgrade", (int)4), OreBracketHandler.getOre((String)"plateChrome")}, {iItemStack7, OreBracketHandler.getOre((String)"plateChrome"), iItemStack7}}, null);
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem((String)"ExtraUtilities:enderQuarryUpgrade", (int)6), (IIngredient[][])new IIngredient[][]{{iItemStack42, OreBracketHandler.getOre((String)"gearTitanium"), iItemStack42}, {iItemStack45, OreBracketHandler.getOre((String)"gearDiamond"), iItemStack45}, {iItemStack42, OreBracketHandler.getOre((String)"gearTitanium"), iItemStack42}}, null);
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem((String)"ExtraUtilities:enderQuarryUpgrade", (int)7), (IIngredient[][])new IIngredient[][]{{iItemStack43, OreBracketHandler.getOre((String)"gearTungstenSteel"), iItemStack43}, {OreBracketHandler.getOre((String)"gearTungstenSteel"), ItemBracketHandler.getItem((String)"ExtraUtilities:enderQuarryUpgrade", (int)6), OreBracketHandler.getOre((String)"gearTungstenSteel")}, {iItemStack43, OreBracketHandler.getOre((String)"gearTungstenSteel"), iItemStack43}}, null);
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem((String)"ExtraUtilities:enderQuarryUpgrade", (int)8), (IIngredient[][])new IIngredient[][]{{iItemStack44, OreBracketHandler.getOre((String)"gearChrome"), iItemStack44}, {OreBracketHandler.getOre((String)"gearChrome"), ItemBracketHandler.getItem((String)"ExtraUtilities:enderQuarryUpgrade", (int)7), OreBracketHandler.getOre((String)"gearChrome")}, {iItemStack44, OreBracketHandler.getOre((String)"gearChrome"), iItemStack44}}, null);
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem((String)"ExtraUtilities:enderQuarryUpgrade", (int)9), (IIngredient[][])new IIngredient[][]{{iItemStack7, iItemStack, iItemStack7}, {OreBracketHandler.getOre((String)"pipeLargeTungstenSteel"), iOreDictEntry3, OreBracketHandler.getOre((String)"pipeLargeTungstenSteel")}, {iItemStack7, iItemStack, iItemStack7}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack45, (IIngredient[][])new IIngredient[][]{{iOreDictEntry21, iOreDictEntry11, iOreDictEntry21}, {iOreDictEntry11, iOreDictEntry4, iOreDictEntry11}, {iOreDictEntry21, iOreDictEntry11, iOreDictEntry21}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack46, (IIngredient[][])new IIngredient[][]{{iOreDictEntry21, iItemStack26, iOreDictEntry21}, {iItemStack26, iOreDictEntry13, iItemStack26}, {iOreDictEntry21, iItemStack26, iOreDictEntry21}}, null);
        MineTweakerAPI.recipes.addShapeless(iItemStack46, new IIngredient[]{iItemStack46}, null);
        MineTweakerAPI.recipes.addShapeless(iItemStack46, new IIngredient[]{iItemStack46.marked("ItemFilterUp"), OreBracketHandler.getOre((String)"craftingRedstoneTorch")}, (IRecipeFunction)new ZenClass0());
        MineTweakerAPI.recipes.addShapeless(iItemStack46, new IIngredient[]{iItemStack46.marked("ItemFilterUp"), OreBracketHandler.getOre((String)"blockWool")}, (IRecipeFunction)new ZenClass1());
        MineTweakerAPI.recipes.addShapeless(iItemStack46, new IIngredient[]{iItemStack46.marked("ItemFilterUp"), OreBracketHandler.getOre((String)"stickWood")}, (IRecipeFunction)new ZenClass2());
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem((String)"ExtraUtilities:nodeUpgrade", (int)10), (IIngredient[][])new IIngredient[][]{{iOreDictEntry47, iItemStack27, iOreDictEntry47}, {iItemStack27, iItemStack46, iItemStack27}, {iOreDictEntry47, iItemStack27, iOreDictEntry47}}, null);
        MineTweakerAPI.recipes.addShapeless(ItemBracketHandler.getItem((String)"ExtraUtilities:nodeUpgrade", (int)10), new IIngredient[]{ItemBracketHandler.getItem((String)"ExtraUtilities:nodeUpgrade", (int)10)}, null);
        MineTweakerAPI.recipes.addShapeless(ItemBracketHandler.getItem((String)"ExtraUtilities:nodeUpgrade", (int)10), new IIngredient[]{ItemBracketHandler.getItem((String)"ExtraUtilities:nodeUpgrade", (int)10).marked("AdvItemFilterUp"), OreBracketHandler.getOre((String)"craftingRedstoneTorch")}, (IRecipeFunction)new ZenClass3());
        MineTweakerAPI.recipes.addShaped(iItemStack47, (IIngredient[][])new IIngredient[][]{{iOreDictEntry47, iItemStack60, iOreDictEntry47}, {iItemStack61, iOreDictEntry17, iItemStack61}, {iOreDictEntry47, iItemStack60, iOreDictEntry47}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack49, (IIngredient[][])new IIngredient[][]{{iOreDictEntry27, iItemStack47, iOreDictEntry27}, {OreBracketHandler.getOre((String)"gearIridium"), ItemBracketHandler.getItem((String)"WR-CBE|Logic:wirelessLogic", (int)0), OreBracketHandler.getOre((String)"gearIridium")}, {iOreDictEntry27, iOreDictEntry28, iOreDictEntry27}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack50, (IIngredient[][])new IIngredient[][]{{iOreDictEntry27, iItemStack47, iOreDictEntry27}, {OreBracketHandler.getOre((String)"gearIridium"), ItemBracketHandler.getItem((String)"WR-CBE|Core:recieverDish", (int)0), OreBracketHandler.getOre((String)"gearIridium")}, {iOreDictEntry27, iOreDictEntry28, iOreDictEntry27}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack51, (IIngredient[][])new IIngredient[][]{{iOreDictEntry21, iItemStack45, iOreDictEntry21}, {iOreDictEntry63, iOreDictEntry17, iItemStack45}, {iOreDictEntry21, iItemStack45, iOreDictEntry21}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack52, (IIngredient[][])new IIngredient[][]{{iOreDictEntry21, iOreDictEntry63, iOreDictEntry21}, {iItemStack45, iOreDictEntry17, iItemStack45}, {iOreDictEntry21, null, iOreDictEntry21}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack52, (IIngredient[][])new IIngredient[][]{{iOreDictEntry21, null, iOreDictEntry21}, {iItemStack45, iOreDictEntry17, iItemStack45}, {iOreDictEntry21, iOreDictEntry63, iOreDictEntry21}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack53, (IIngredient[][])new IIngredient[][]{{iOreDictEntry21, iItemStack45, iOreDictEntry21}, {iItemStack45, iOreDictEntry17, iOreDictEntry63}, {iOreDictEntry21, iItemStack45, iOreDictEntry21}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack48, (IIngredient[][])new IIngredient[][]{{iOreDictEntry21, iItemStack45, iOreDictEntry21}, {iOreDictEntry63, iOreDictEntry17, iItemStack25}, {iOreDictEntry21, iItemStack45, iOreDictEntry21}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack10, (IIngredient[][])new IIngredient[][]{{null, iItemStack11, iItemStack11}, {null, OreBracketHandler.getOre((String)"stickWood"), iItemStack11}, {OreBracketHandler.getOre((String)"stickWood"), null, null}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack15, (IIngredient[][])new IIngredient[][]{{iOreDictEntry15, OreBracketHandler.getOre((String)"ringMeteoricSteel"), iOreDictEntry15}, {iOreDictEntry15, OreBracketHandler.getOre((String)"pipeHugeSteel"), iOreDictEntry15}, {iOreDictEntry15, OreBracketHandler.getOre((String)"ringMeteoricSteel"), iOreDictEntry15}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack16, (IIngredient[][])new IIngredient[][]{{OreBracketHandler.getOre((String)"plateBedrockium"), OreBracketHandler.getOre((String)"ringTungstenSteel"), OreBracketHandler.getOre((String)"plateBedrockium")}, {OreBracketHandler.getOre((String)"plateBedrockium"), ItemBracketHandler.getItem((String)"ExtraUtilities:drum", (int)0), OreBracketHandler.getOre((String)"plateBedrockium")}, {OreBracketHandler.getOre((String)"plateBedrockium"), OreBracketHandler.getOre((String)"ringTungstenSteel"), OreBracketHandler.getOre((String)"plateBedrockium")}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack22, (IIngredient[][])new IIngredient[][]{{iOreDictEntry62, ItemBracketHandler.getItem((String)"minecraft:rail", (int)0), iOreDictEntry63}, {ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)32630), OreBracketHandler.getOre((String)"frameGtSteel"), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)32630)}, {OreBracketHandler.getOre((String)"gearGtSmallSteel"), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)32600), OreBracketHandler.getOre((String)"gearGtSmallSteel")}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack28, (IIngredient[][])new IIngredient[][]{{iOreDictEntry15, OreBracketHandler.getOre((String)"chestWood"), iOreDictEntry15}, {iOreDictEntry20, iItemStack62, iOreDictEntry20}, {iOreDictEntry15, OreBracketHandler.getOre((String)"chestWood"), iOreDictEntry15}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack29, (IIngredient[][])new IIngredient[][]{{iItemStack4, iItemStack28, iItemStack4}, {iOreDictEntry20, iItemStack28, iOreDictEntry20}, {iItemStack4, iItemStack28, iItemStack4}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack30, (IIngredient[][])new IIngredient[][]{{iOreDictEntry62, iOreDictEntry12, iOreDictEntry64}, {iOreDictEntry9, iOreDictEntry9, iOreDictEntry14}, {iOreDictEntry9, iOreDictEntry9, iOreDictEntry20}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack30, (IIngredient[][])new IIngredient[][]{{iOreDictEntry64, iOreDictEntry12, iOreDictEntry62}, {iOreDictEntry9, iOreDictEntry9, iOreDictEntry14}, {iOreDictEntry9, iOreDictEntry9, iOreDictEntry20}}, null);
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem((String)"ExtraUtilities:watering_can", (int)3), (IIngredient[][])new IIngredient[][]{{iOreDictEntry62, OreBracketHandler.getOre((String)"ringNeutronium"), iOreDictEntry64}, {OreBracketHandler.getOre((String)"plateBedrockium"), OreBracketHandler.getOre((String)"plateBedrockium"), OreBracketHandler.getOre((String)"plateBedrockium")}, {OreBracketHandler.getOre((String)"plateBedrockium"), OreBracketHandler.getOre((String)"plateBedrockium"), OreBracketHandler.getOre((String)"screwNeutronium")}}, null);
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem((String)"ExtraUtilities:watering_can", (int)3), (IIngredient[][])new IIngredient[][]{{iOreDictEntry64, OreBracketHandler.getOre((String)"ringNeutronium"), iOreDictEntry62}, {OreBracketHandler.getOre((String)"plateBedrockium"), OreBracketHandler.getOre((String)"plateBedrockium"), OreBracketHandler.getOre((String)"plateBedrockium")}, {OreBracketHandler.getOre((String)"plateBedrockium"), OreBracketHandler.getOre((String)"plateBedrockium"), OreBracketHandler.getOre((String)"screwNeutronium")}}, null);
        QED.addShapedRecipe((IItemStack)iItemStack79, (IIngredient[][])new IIngredient[][]{{ItemBracketHandler.getItem((String)"minecraft:potion", (int)8225), iItemStack81, ItemBracketHandler.getItem((String)"minecraft:potion", (int)8229)}, {iItemStack80, ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)23306), iItemStack80}, {iItemStack80, ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)23306), iItemStack80}});
        MineTweakerAPI.recipes.addShaped(iItemStack35, (IIngredient[][])new IIngredient[][]{{iOreDictEntry5, iOreDictEntry5, iOreDictEntry5}, {iOreDictEntry5, iItemStack37, iOreDictEntry5}, {iOreDictEntry5, iItemStack38, iOreDictEntry5}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack36, (IIngredient[][])new IIngredient[][]{{iOreDictEntry5, iItemStack35, iOreDictEntry5}, {iItemStack35, iItemStack39, iItemStack35}, {iItemStack35, iItemStack38, iItemStack35}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack63, (IIngredient[][])new IIngredient[][]{{iOreDictEntry19, iOreDictEntry15, iOreDictEntry19}, {iOreDictEntry63, iOreDictEntry6, iOreDictEntry62}, {iOreDictEntry19, iOreDictEntry15, iOreDictEntry19}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack64, (IIngredient[][])new IIngredient[][]{{iOreDictEntry19, iOreDictEntry33, iOreDictEntry19}, {iOreDictEntry63, iItemStack63, iOreDictEntry62}, {iOreDictEntry19, iOreDictEntry33, iOreDictEntry19}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack65, (IIngredient[][])new IIngredient[][]{{iOreDictEntry19, iOreDictEntry34, iOreDictEntry19}, {iOreDictEntry63, iItemStack63, iOreDictEntry62}, {iOreDictEntry19, iOreDictEntry34, iOreDictEntry19}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack66, (IIngredient[][])new IIngredient[][]{{iOreDictEntry19, iOreDictEntry35, iOreDictEntry19}, {iOreDictEntry63, iItemStack64, iOreDictEntry62}, {iOreDictEntry19, iOreDictEntry35, iOreDictEntry19}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack67, (IIngredient[][])new IIngredient[][]{{iOreDictEntry19, iOreDictEntry36, iOreDictEntry19}, {iOreDictEntry63, iItemStack66, iOreDictEntry62}, {iOreDictEntry19, iOreDictEntry36, iOreDictEntry19}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack68, (IIngredient[][])new IIngredient[][]{{iOreDictEntry22, iOreDictEntry21, iOreDictEntry22}, {iOreDictEntry63, iItemStack63, iOreDictEntry62}, {iOreDictEntry22, iOreDictEntry21, iOreDictEntry22}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack69, (IIngredient[][])new IIngredient[][]{{iOreDictEntry62, iItemStack63, iOreDictEntry20}, {iItemStack63, iItemStack63, iItemStack63}, {iOreDictEntry20, iItemStack63, iOreDictEntry64}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack69, (IIngredient[][])new IIngredient[][]{{iOreDictEntry64, iItemStack63, iOreDictEntry20}, {iItemStack63, iItemStack63, iItemStack63}, {iOreDictEntry20, iItemStack63, iOreDictEntry62}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack70, (IIngredient[][])new IIngredient[][]{{iOreDictEntry19, iOreDictEntry33, iOreDictEntry19}, {iOreDictEntry63, iItemStack64, iOreDictEntry62}, {iOreDictEntry19, iOreDictEntry33, iOreDictEntry19}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack71, (IIngredient[][])new IIngredient[][]{{iOreDictEntry25, iOreDictEntry23, iOreDictEntry25}, {iOreDictEntry63, iItemStack68, iOreDictEntry62}, {iOreDictEntry25, iOreDictEntry23, iOreDictEntry25}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack73, (IIngredient[][])new IIngredient[][]{{iOreDictEntry63, iItemStack72, iOreDictEntry62}, {iOreDictEntry26, iItemStack40, iOreDictEntry26}, {iItemStack75, iItemStack75, iItemStack75}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack73, (IIngredient[][])new IIngredient[][]{{iOreDictEntry62, iItemStack72, iOreDictEntry63}, {iOreDictEntry26, iItemStack40, iOreDictEntry26}, {iItemStack75, iItemStack75, iItemStack75}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack74, (IIngredient[][])new IIngredient[][]{{iOreDictEntry63, iItemStack72, iOreDictEntry62}, {iOreDictEntry26, iItemStack40, iOreDictEntry26}, {iItemStack76, iItemStack76, iItemStack76}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack74, (IIngredient[][])new IIngredient[][]{{iOreDictEntry62, iItemStack72, iOreDictEntry63}, {iOreDictEntry26, iItemStack40, iOreDictEntry26}, {iItemStack76, iItemStack76, iItemStack76}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack75, (IIngredient[][])new IIngredient[][]{{iOreDictEntry62, iItemStack72, iOreDictEntry63}, {iOreDictEntry26, iItemStack55, iOreDictEntry26}, {iItemStack85, iOreDictEntry39, iItemStack85}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack75, (IIngredient[][])new IIngredient[][]{{iOreDictEntry63, iItemStack72, iOreDictEntry62}, {iOreDictEntry26, iItemStack55, iOreDictEntry26}, {iItemStack85, iOreDictEntry39, iItemStack85}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack76, (IIngredient[][])new IIngredient[][]{{iOreDictEntry62, iItemStack72, iOreDictEntry63}, {iOreDictEntry26, iItemStack59, iOreDictEntry26}, {iItemStack84, iItemStack56, iItemStack84}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack76, (IIngredient[][])new IIngredient[][]{{iOreDictEntry63, iItemStack72, iOreDictEntry62}, {iOreDictEntry26, iItemStack59, iOreDictEntry26}, {iItemStack84, iItemStack56, iItemStack84}}, null);
        QED.addShapedRecipe((IItemStack)iItemStack77, (IIngredient[][])new IIngredient[][]{{iItemStack75, iItemStack86, iItemStack75}, {ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)17533), ItemBracketHandler.getItem((String)"ExtraUtilities:nodeUpgrade", (int)8), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)17533)}, {iItemStack75, iItemStack86, iItemStack75}});
        QED.addShapedRecipe((IItemStack)iItemStack78, (IIngredient[][])new IIngredient[][]{{iItemStack77, ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)17533), iItemStack77}, {ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)17533), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)11395), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)17533)}, {iItemStack77, iItemStack77, iItemStack77}});
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem((String)"ExtraUtilities:trashcan", (int)0), (IIngredient[][])new IIngredient[][]{{OreBracketHandler.getOre((String)"plateIron"), OreBracketHandler.getOre((String)"craftingToolHardHammer"), OreBracketHandler.getOre((String)"plateIron")}, {OreBracketHandler.getOre((String)"plateIron"), OreBracketHandler.getOre((String)"gemEnderPearl"), OreBracketHandler.getOre((String)"plateIron")}, {OreBracketHandler.getOre((String)"plateIron"), OreBracketHandler.getOre((String)"plateIron"), OreBracketHandler.getOre((String)"plateIron")}}, null);
        MineTweakerAPI.recipes.addShapeless(ItemBracketHandler.getItem((String)"ExtraUtilities:decorativeBlock2", (int)0), new IIngredient[]{ItemBracketHandler.getItem((String)"TConstruct:GlassBlock", (int)0)}, null);
        MineTweakerAPI.recipes.addShapeless(ItemBracketHandler.getItem((String)"ExtraUtilities:unstableingot", (int)0), new IIngredient[]{ItemBracketHandler.getItem((String)"ExtraUtilities:unstableingot", (int)2)}, null);
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem((String)"ExtraUtilities:chestFull", (int)0), (IIngredient[][])new IIngredient[][]{{OreBracketHandler.getOre((String)"craftingToolHardHammer"), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)17809), OreBracketHandler.getOre((String)"craftingToolSaw")}, {ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)17809), OreBracketHandler.getOre((String)"chestWood"), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)17809)}, {null, ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)17809), null}}, null);
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem((String)"ExtraUtilities:chestMini", (int)0), (IIngredient[][])new IIngredient[][]{{OreBracketHandler.getOre((String)"craftingToolHardHammer"), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)17809), OreBracketHandler.getOre((String)"craftingToolSaw")}, {ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)17809), OreBracketHandler.getOre((String)"itemFlint"), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)17809)}, {null, ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)17809), null}}, null);
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem((String)"ExtraUtilities:enderCollector", (int)0), (IIngredient[][])new IIngredient[][]{{OreBracketHandler.getOre((String)"lensEnderPearl"), OreBracketHandler.getOre((String)"blockEnderObsidian"), OreBracketHandler.getOre((String)"lensEnderPearl")}, {OreBracketHandler.getOre((String)"craftingToolHardHammer"), OreBracketHandler.getOre((String)"blockEnderObsidian"), OreBracketHandler.getOre((String)"craftingToolWrench")}, {OreBracketHandler.getOre((String)"stoneObsidian"), OreBracketHandler.getOre((String)"stoneObsidian"), OreBracketHandler.getOre((String)"stoneObsidian")}}, null);
        MineTweakerAPI.recipes.addShapeless(ItemBracketHandler.getItem((String)"ExtraUtilities:enderCollector", (int)0), new IIngredient[]{ItemBracketHandler.getItem((String)"RandomThings:advancedItemCollector", (int)0)}, null);
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem((String)"ExtraUtilities:endConstructor", (int)0), (IIngredient[][])new IIngredient[][]{{OreBracketHandler.getOre((String)"plateEnderEye"), ItemBracketHandler.getItem((String)"HardcoreEnderExpansion:altar_nexus", (int)0), OreBracketHandler.getOre((String)"plateEnderEye")}, {OreBracketHandler.getOre((String)"blockEnderObsidian"), ItemBracketHandler.getItem((String)"Thaumcraft:blockStoneDevice", (int)2), OreBracketHandler.getOre((String)"blockEnderObsidian")}, {OreBracketHandler.getOre((String)"plateTitanium"), ItemBracketHandler.getItem((String)"ExtraUtilities:decorativeBlock1", (int)12), OreBracketHandler.getOre((String)"plateTitanium")}}, null);
        QED.addShapedRecipe((IItemStack)ItemBracketHandler.getItem((String)"ExtraUtilities:endMarker", (int)0), (IIngredient[][])new IIngredient[][]{{null, ItemBracketHandler.getItem((String)"minecraft:ender_eye", (int)0), null}, {null, ItemBracketHandler.getItem((String)"ExtraUtilities:decorativeBlock1", (int)1), null}, {null, ItemBracketHandler.getItem((String)"ExtraUtilities:decorativeBlock1", (int)1), null}});
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem((String)"ExtraUtilities:spike_base_wood", (int)0).amount(2), (IIngredient[][])new IIngredient[][]{{iOreDictEntry65, ItemBracketHandler.getItem((String)"minecraft:wooden_sword", (int)0), iOreDictEntry64}, {iOreDictEntry52, iOreDictEntry8, iOreDictEntry52}, {iOreDictEntry8, iOreDictEntry50, iOreDictEntry8}}, null);
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem((String)"ExtraUtilities:spike_base", (int)0).amount(2), (IIngredient[][])new IIngredient[][]{{iOreDictEntry65, ItemBracketHandler.getItem((String)"minecraft:iron_sword", (int)0), iOreDictEntry64}, {iOreDictEntry55, iOreDictEntry9, iOreDictEntry55}, {iOreDictEntry9, iOreDictEntry53, iOreDictEntry9}}, null);
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem((String)"ExtraUtilities:spike_base_gold", (int)0).amount(2), (IIngredient[][])new IIngredient[][]{{iOreDictEntry65, ItemBracketHandler.getItem((String)"minecraft:golden_sword", (int)0), iOreDictEntry64}, {iOreDictEntry58, iOreDictEntry10, iOreDictEntry58}, {iOreDictEntry10, iOreDictEntry56, iOreDictEntry10}}, null);
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem((String)"ExtraUtilities:spike_base_diamond", (int)0).amount(2), (IIngredient[][])new IIngredient[][]{{iOreDictEntry65, ItemBracketHandler.getItem((String)"minecraft:diamond_sword", (int)0), iOreDictEntry64}, {iOreDictEntry61, iOreDictEntry11, iOreDictEntry61}, {iOreDictEntry11, iOreDictEntry59, iOreDictEntry11}}, null);
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem((String)"ExtraUtilities:builderswand", (int)0), (IIngredient[][])new IIngredient[][]{{null, null, OreBracketHandler.getOre((String)"ingotUnstable")}, {null, OreBracketHandler.getOre((String)"ingotUnstable"), null}, {ItemBracketHandler.getItem((String)"RandomThings:ingredient", (int)1), null, null}}, null);
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem((String)"ExtraUtilities:creativebuilderswand", (int)0), (IIngredient[][])new IIngredient[][]{{null, OreBracketHandler.getOre((String)"ingotUnstable"), OreBracketHandler.getOre((String)"ingotUnstable")}, {null, OreBracketHandler.getOre((String)"ingotUnstable"), OreBracketHandler.getOre((String)"ingotUnstable")}, {ItemBracketHandler.getItem((String)"RandomThings:ingredient", (int)1), null, null}}, null);
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem((String)"ExtraUtilities:shears", (int)0), (IIngredient[][])new IIngredient[][]{{OreBracketHandler.getOre((String)"ingotUnstable"), null, OreBracketHandler.getOre((String)"ingotUnstable")}, {iItemStack21, iItemStack87, iItemStack21}}, null);
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem((String)"ExtraUtilities:ethericsword", (int)0), (IIngredient[][])new IIngredient[][]{{null, OreBracketHandler.getOre((String)"ingotUnstable"), null}, {null, OreBracketHandler.getOre((String)"ingotUnstable"), null}, {null, ItemBracketHandler.getItem((String)"RandomThings:ingredient", (int)1), null}}, null);
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem((String)"ExtraUtilities:lawSword", (int)0), (IIngredient[][])new IIngredient[][]{{null, ItemBracketHandler.getItem((String)"TConstruct:largeSwordBlade", (int)314), null}, {null, OreBracketHandler.getOre((String)"ingotUnstable"), null}, {null, ItemBracketHandler.getItem((String)"RandomThings:ingredient", (int)1), null}}, null);
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem((String)"ExtraUtilities:erosionShovel", (int)0), (IIngredient[][])new IIngredient[][]{{null, OreBracketHandler.getOre((String)"ingotUnstable"), null}, {null, ItemBracketHandler.getItem((String)"RandomThings:ingredient", (int)1), null}, {null, ItemBracketHandler.getItem((String)"RandomThings:ingredient", (int)1), null}}, null);
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem((String)"ExtraUtilities:destructionpickaxe", (int)0), (IIngredient[][])new IIngredient[][]{{OreBracketHandler.getOre((String)"ingotUnstable"), OreBracketHandler.getOre((String)"ingotUnstable"), OreBracketHandler.getOre((String)"ingotUnstable")}, {null, ItemBracketHandler.getItem((String)"RandomThings:ingredient", (int)1), null}, {null, ItemBracketHandler.getItem((String)"RandomThings:ingredient", (int)1), null}}, null);
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem((String)"ExtraUtilities:defoliageAxe", (int)0), (IIngredient[][])new IIngredient[][]{{OreBracketHandler.getOre((String)"ingotUnstable"), OreBracketHandler.getOre((String)"ingotUnstable"), null}, {OreBracketHandler.getOre((String)"ingotUnstable"), ItemBracketHandler.getItem((String)"RandomThings:ingredient", (int)1), null}, {null, ItemBracketHandler.getItem((String)"RandomThings:ingredient", (int)1), null}}, null);
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem((String)"ExtraUtilities:temporalHoe", (int)0), (IIngredient[][])new IIngredient[][]{{OreBracketHandler.getOre((String)"ingotUnstable"), OreBracketHandler.getOre((String)"ingotUnstable"), null}, {null, ItemBracketHandler.getItem((String)"RandomThings:ingredient", (int)1), null}, {null, ItemBracketHandler.getItem((String)"RandomThings:ingredient", (int)1), null}}, null);
        AlloySmelter.addRecipe((IItemStack)iItemStack6, (IIngredient)ItemBracketHandler.getItem((String)"minecraft:quartz_block", (int)0), (IIngredient)ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)2816), (int)80, (int)64);
        AlloySmelter.addRecipe((IItemStack)ItemBracketHandler.getItem((String)"ExtraUtilities:decorativeBlock2", (int)5), (IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:decorativeBlock2", (int)0), (IIngredient)ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)2804).amount(4), (int)200, (int)8);
        AlloySmelter.addRecipe((IItemStack)ItemBracketHandler.getItem((String)"ExtraUtilities:decorativeBlock2", (int)4), (IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:decorativeBlock2", (int)0), (IIngredient)ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)2086), (int)200, (int)8);
        AlloySmelter.addRecipe((IItemStack)ItemBracketHandler.getItem((String)"ExtraUtilities:decorativeBlock2", (int)3), (IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:decorativeBlock2", (int)0), (IIngredient)ItemBracketHandler.getItem((String)"minecraft:gunpowder", (int)0), (int)200, (int)8);
        AlloySmelter.addRecipe((IItemStack)ItemBracketHandler.getItem((String)"ExtraUtilities:decorativeBlock2", (int)7), (IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:decorativeBlock2", (int)0), (IIngredient)ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)17811).amount(4), (int)400, (int)16);
        AlloySmelter.addRecipe((IItemStack)ItemBracketHandler.getItem((String)"ExtraUtilities:decorativeBlock2", (int)8), (IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:decorativeBlock2", (int)0), (IIngredient)ItemBracketHandler.getItem((String)"minecraft:dye", (int)9), (int)200, (int)8);
        Assembler.addRecipe((IItemStack)iItemStack18, (IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:cobblestone_compressed", (int)3).amount(4), (IIngredient)ItemBracketHandler.getItem((String)"minecraft:diamond_block", (int)0), (int)600, (int)256);
        Assembler.addRecipe((IItemStack)ItemBracketHandler.getItem((String)"ExtraUtilities:decorativeBlock2", (int)1), (IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:decorativeBlock2", (int)0), (IIngredient)ItemBracketHandler.getItem((String)"gregtech:gt.integrated_circuit", (int)1).amount(0), (int)100, (int)8);
        Assembler.addRecipe((IItemStack)ItemBracketHandler.getItem((String)"ExtraUtilities:decorativeBlock2", (int)2), (IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:decorativeBlock2", (int)0), (IIngredient)ItemBracketHandler.getItem((String)"gregtech:gt.integrated_circuit", (int)4).amount(0), (int)100, (int)8);
        Assembler.addRecipe((IItemStack)ItemBracketHandler.getItem((String)"ExtraUtilities:decorativeBlock2", (int)6), (IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:decorativeBlock2", (int)0), (IIngredient)ItemBracketHandler.getItem((String)"gregtech:gt.integrated_circuit", (int)5).amount(0), (int)100, (int)8);
        Assembler.addRecipe((IItemStack)ItemBracketHandler.getItem((String)"ExtraUtilities:decorativeBlock2", (int)9), (IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:decorativeBlock2", (int)0), (IIngredient)ItemBracketHandler.getItem((String)"gregtech:gt.integrated_circuit", (int)2).amount(0), (int)100, (int)8);
        Assembler.addRecipe((IItemStack)ItemBracketHandler.getItem((String)"ExtraUtilities:decorativeBlock2", (int)10), (IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:decorativeBlock2", (int)0), (IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:curtains", (int)0), (int)200, (int)16);
        Assembler.addRecipe((IItemStack)ItemBracketHandler.getItem((String)"ExtraUtilities:decorativeBlock2", (int)11), (IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:decorativeBlock2", (int)10), (IIngredient)ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)2804).amount(4), (int)400, (int)30);
        Assembler.addRecipe((IItemStack)ItemBracketHandler.getItem((String)"ExtraUtilities:chestFull", (int)0), (IIngredient)ItemBracketHandler.getItem((String)"minecraft:chest", (int)0), (IIngredient)ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)17809).amount(2), (int)100, (int)30);
        Assembler.addRecipe((IItemStack)ItemBracketHandler.getItem((String)"ExtraUtilities:chestMini", (int)0), (IIngredient)ItemBracketHandler.getItem((String)"minecraft:flint", (int)0), (IIngredient)ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)17809).amount(2), (int)50, (int)30);
        Assembler.addRecipe((IItemStack)iItemStack2, (IIngredient)iItemStack6.amount(4), (IIngredient)ItemBracketHandler.getItem((String)"IC2:itemDensePlates", (int)7).amount(4), (ILiquidStack)LiquidBracketHandler.getLiquid((String)"ender").withAmount(500), (int)600, (int)120);
        Assembler.addRecipe((IItemStack)ItemBracketHandler.getItem((String)"ExtraUtilities:endConstructor", (int)2), (IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:decorativeBlock1", (int)1).amount(4), (IIngredient)ItemBracketHandler.getItem((String)"minecraft:ender_eye", (int)0).amount(3), (ILiquidStack)LiquidBracketHandler.getLiquid((String)"ender").withAmount(1000), (int)400, (int)120);
        Assembler.addRecipe((IItemStack)ItemBracketHandler.getItem((String)"ExtraUtilities:budoff", (int)0), (IIngredient)ItemBracketHandler.getItem((String)"Railcraft:detector", (int)2), (IIngredient)ItemBracketHandler.getItem((String)"minecraft:sticky_piston", (int)0), (int)200, (int)30);
        Assembler.addRecipe((IItemStack)ItemBracketHandler.getItem((String)"ExtraUtilities:budoff", (int)3), (IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:budoff", (int)0), (IIngredient)ItemBracketHandler.getItem((String)"minecraft:redstone_block", (int)0).amount(4), (int)200, (int)120);
        Assembler.addRecipe((IItemStack)iItemStack80, (IIngredient)ItemBracketHandler.getItem((String)"minecraft:torch", (int)0).amount(5), (IIngredient)ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.02", (int)28500), (ILiquidStack)LiquidBracketHandler.getLiquid((String)"molten.tin").withAmount(1440), (int)600, (int)30);
        Assembler.addRecipe((IItemStack)ItemBracketHandler.getItem((String)"ExtraUtilities:decorativeBlock1", (int)0).amount(9), (IIngredient)ItemBracketHandler.getItem((String)"minecraft:stone", (int)0).amount(4), (IIngredient)ItemBracketHandler.getItem((String)"minecraft:stonebrick", (int)0).amount(5), (int)180, (int)4);
        Assembler.addRecipe((IItemStack)ItemBracketHandler.getItem((String)"ExtraUtilities:decorativeBlock1", (int)4), (IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:decorativeBlock1", (int)0), (IIngredient)ItemBracketHandler.getItem((String)"gregtech:gt.integrated_circuit", (int)4).amount(0), (int)20, (int)4);
        Assembler.addRecipe((IItemStack)ItemBracketHandler.getItem((String)"ExtraUtilities:decorativeBlock1", (int)7), (IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:decorativeBlock1", (int)4), (IIngredient)ItemBracketHandler.getItem((String)"gregtech:gt.integrated_circuit", (int)4).amount(0), (int)20, (int)4);
        Assembler.addRecipe((IItemStack)ItemBracketHandler.getItem((String)"ExtraUtilities:decorativeBlock1", (int)6), (IIngredient)ItemBracketHandler.getItem((String)"minecraft:gravel", (int)0), (IIngredient)ItemBracketHandler.getItem((String)"gregtech:gt.integrated_circuit", (int)2).amount(0), (int)20, (int)4);
        Assembler.addRecipe((IItemStack)ItemBracketHandler.getItem((String)"ExtraUtilities:decorativeBlock1", (int)3).amount(4), (IIngredient)ItemBracketHandler.getItem((String)"minecraft:stone", (int)0), (IIngredient)ItemBracketHandler.getItem((String)"minecraft:ice", (int)0).amount(4), (int)80, (int)4);
        Assembler.addRecipe((IItemStack)ItemBracketHandler.getItem((String)"ExtraUtilities:decorativeBlock1", (int)9).amount(2), (IIngredient)ItemBracketHandler.getItem((String)"minecraft:sand", (int)0), (IIngredient)ItemBracketHandler.getItem((String)"minecraft:glass", (int)0), (int)40, (int)4);
        Assembler.addRecipe((IItemStack)ItemBracketHandler.getItem((String)"ExtraUtilities:decorativeBlock1", (int)13).amount(2), (IIngredient)ItemBracketHandler.getItem((String)"minecraft:sandstone", (int)0), (IIngredient)ItemBracketHandler.getItem((String)"minecraft:end_stone", (int)0), (int)40, (int)4);
        Assembler.addRecipe((IItemStack)ItemBracketHandler.getItem((String)"ExtraUtilities:decorativeBlock1", (int)10).amount(5), (IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:decorativeBlock1", (int)6).amount(5), (IIngredient)ItemBracketHandler.getItem((String)"minecraft:stone_slab", (int)5).amount(5), (int)100, (int)4);
        Assembler.addRecipe((IItemStack)iItemStack3, (IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:decorativeBlock1", (int)1).amount(4), (IIngredient)iItemStack4.amount(4), (ILiquidStack)LiquidBracketHandler.getLiquid((String)"ender").withAmount(1000), (int)1200, (int)120);
        Assembler.addRecipe((IItemStack)ItemBracketHandler.getItem((String)"ExtraUtilities:trading_post", (int)0), (IIngredient)ItemBracketHandler.getItem((String)"Railcraft:machine.alpha", (int)6), (IIngredient)ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.02", (int)32470).amount(4), (int)300, (int)30);
        Assembler.addRecipe((IItemStack)iItemStack63, (IIngredient)ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)17305).amount(2), (IIngredient)ItemBracketHandler.getItem((String)"gregtech:gt.integrated_circuit", (int)2).amount(0), (ILiquidStack)LiquidBracketHandler.getLiquid((String)"molten.redalloy").withAmount(36), (int)100, (int)64);
        Assembler.addRecipe((IItemStack)iItemStack64, (IIngredient)iItemStack63, (IIngredient)ItemBracketHandler.getItem((String)"IC2:itemPartCircuit", (int)0), (int)200, (int)64);
        Assembler.addRecipe((IItemStack)iItemStack68, (IIngredient)iItemStack63, (IIngredient)ItemBracketHandler.getItem((String)"gregtech:gt.integrated_circuit", (int)1).amount(0), (ILiquidStack)LiquidBracketHandler.getLiquid((String)"molten.redalloy").withAmount(216), (int)200, (int)64);
        Assembler.addRecipe((IItemStack)iItemStack69, (IIngredient)iItemStack63.amount(4), (IIngredient)ItemBracketHandler.getItem((String)"gregtech:gt.integrated_circuit", (int)4).amount(0), (int)200, (int)64);
        Assembler.addRecipe((IItemStack)iItemStack70, (IIngredient)iItemStack64, (IIngredient)ItemBracketHandler.getItem((String)"IC2:itemPartCircuit", (int)0), (int)300, (int)64);
        Assembler.addRecipe((IItemStack)iItemStack65, (IIngredient)iItemStack63, (IIngredient)ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)32702), (int)200, (int)64);
        Assembler.addRecipe((IItemStack)iItemStack65, (IIngredient)iItemStack63, (IIngredient)ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.03", (int)32079), (int)200, (int)64);
        Assembler.addRecipe((IItemStack)iItemStack65, (IIngredient)iItemStack63, (IIngredient)ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.03", (int)32080), (int)200, (int)64);
        Assembler.addRecipe((IItemStack)iItemStack66, (IIngredient)iItemStack64, (IIngredient)ItemBracketHandler.getItem((String)"IC2:itemPartCircuitAdv", (int)0), (int)300, (int)64);
        Assembler.addRecipe((IItemStack)iItemStack71, (IIngredient)ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)17303).amount(2), (IIngredient)iItemStack68, (int)300, (int)64);
        Assembler.addRecipe((IItemStack)iItemStack67, (IIngredient)iItemStack66, (IIngredient)ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)32708), (int)400, (int)64);
        Assembler.addRecipe((IItemStack)iItemStack67, (IIngredient)iItemStack66, (IIngredient)ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)32704), (int)200, (int)64);
        Assembler.addRecipe((IItemStack)ItemBracketHandler.getItem((String)"ExtraUtilities:trashcan", (int)0), (IIngredient)ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)17032).amount(4), (IIngredient)ItemBracketHandler.getItem((String)"minecraft:ender_pearl", (int)0), (int)200, (int)30);
        Assembler.addRecipe((IItemStack)ItemBracketHandler.getItem((String)"ExtraUtilities:trashcan", (int)1), (IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:trashcan", (int)0), (IIngredient)ItemBracketHandler.getItem((String)"BuildCraft|Factory:tankBlock", (int)0), (int)200, (int)30);
        Assembler.addRecipe((IItemStack)ItemBracketHandler.getItem((String)"ExtraUtilities:trashcan", (int)2), (IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:trashcan", (int)0), (IIngredient)ItemBracketHandler.getItem((String)"BuildCraft|Transport:item.buildcraftPipe.pipepowergold", (int)0), (int)200, (int)30);
        Assembler.addRecipe((IItemStack)ItemBracketHandler.getItem((String)"ExtraUtilities:heatingElement", (int)0), (IIngredient)ItemBracketHandler.getItem((String)"IC2:itemRecipePart", (int)0).amount(2), (IIngredient)ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.02", (int)19032).amount(4), (ILiquidStack)LiquidBracketHandler.getLiquid((String)"molten.tin").withAmount(144), (int)400, (int)30);
        Assembler.addRecipe((IItemStack)ItemBracketHandler.getItem((String)"ExtraUtilities:heatingElement", (int)0), (IIngredient)ItemBracketHandler.getItem((String)"IC2:itemRecipePart", (int)0).amount(2), (IIngredient)ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.02", (int)19032).amount(4), (ILiquidStack)LiquidBracketHandler.getLiquid((String)"molten.lead").withAmount(288), (int)400, (int)30);
        Assembler.addRecipe((IItemStack)ItemBracketHandler.getItem((String)"ExtraUtilities:heatingElement", (int)0), (IIngredient)ItemBracketHandler.getItem((String)"IC2:itemRecipePart", (int)0).amount(2), (IIngredient)ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.02", (int)19032).amount(4), (ILiquidStack)LiquidBracketHandler.getLiquid((String)"molten.solderingalloy").withAmount(72), (int)400, (int)30);
        Assembler.addRecipe((IItemStack)ItemBracketHandler.getItem((String)"ExtraUtilities:golden_lasso", (int)0), (IIngredient)ItemBracketHandler.getItem((String)"minecraft:ender_pearl", (int)0), (IIngredient)ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.02", (int)19086).amount(4), (int)200, (int)30);
        Assembler.addRecipe((IItemStack)ItemBracketHandler.getItem((String)"ExtraUtilities:scanner", (int)0), (IIngredient)ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)32762), (IIngredient)ItemBracketHandler.getItem((String)"minecraft:ender_eye", (int)0), (int)600, (int)120);
        Assembler.addRecipe((IItemStack)ItemBracketHandler.getItem((String)"ExtraUtilities:cobblestone_compressed", (int)0), (IIngredient)ItemBracketHandler.getItem((String)"gregtech:gt.integrated_circuit", (int)1).amount(0), (IIngredient)ItemBracketHandler.getItem((String)"minecraft:cobblestone", (int)0).amount(9), (int)100, (int)16);
        Assembler.addRecipe((IItemStack)ItemBracketHandler.getItem((String)"ExtraUtilities:cobblestone_compressed", (int)8), (IIngredient)ItemBracketHandler.getItem((String)"minecraft:dirt", (int)0).amount(9), (IIngredient)ItemBracketHandler.getItem((String)"gregtech:gt.integrated_circuit", (int)1).amount(0), (int)100, (int)16);
        Assembler.addRecipe((IItemStack)ItemBracketHandler.getItem((String)"ExtraUtilities:cobblestone_compressed", (int)12), (IIngredient)ItemBracketHandler.getItem((String)"minecraft:gravel", (int)0).amount(9), (IIngredient)ItemBracketHandler.getItem((String)"gregtech:gt.integrated_circuit", (int)1).amount(0), (int)100, (int)16);
        Assembler.addRecipe((IItemStack)ItemBracketHandler.getItem((String)"ExtraUtilities:cobblestone_compressed", (int)14), (IIngredient)ItemBracketHandler.getItem((String)"minecraft:sand", (int)0).amount(9), (IIngredient)ItemBracketHandler.getItem((String)"gregtech:gt.integrated_circuit", (int)1).amount(0), (int)100, (int)16);
        Compressor.addRecipe((IItemStack)ItemBracketHandler.getItem((String)"ExtraUtilities:decorativeBlock1", (int)5), (IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:unstableingot", (int)2).amount(9));
        Compressor.addRecipe((IItemStack)ItemBracketHandler.getItem((String)"ExtraUtilities:decorativeBlock1", (int)5), (IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:unstableingot", (int)0).amount(9));
        Extractor.addRecipe((IItemStack)ItemBracketHandler.getItem((String)"minecraft:cobblestone", (int)0).amount(9), (IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:cobblestone_compressed", (int)0));
        Extractor.addRecipe((IItemStack)ItemBracketHandler.getItem((String)"ExtraUtilities:cobblestone_compressed", (int)0).amount(9), (IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:cobblestone_compressed", (int)1));
        Extractor.addRecipe((IItemStack)ItemBracketHandler.getItem((String)"ExtraUtilities:cobblestone_compressed", (int)1).amount(9), (IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:cobblestone_compressed", (int)2));
        Extractor.addRecipe((IItemStack)ItemBracketHandler.getItem((String)"ExtraUtilities:cobblestone_compressed", (int)2).amount(9), (IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:cobblestone_compressed", (int)3));
        Extractor.addRecipe((IItemStack)ItemBracketHandler.getItem((String)"ExtraUtilities:cobblestone_compressed", (int)3).amount(9), (IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:cobblestone_compressed", (int)4));
        Extractor.addRecipe((IItemStack)ItemBracketHandler.getItem((String)"ExtraUtilities:cobblestone_compressed", (int)4).amount(9), (IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:cobblestone_compressed", (int)5));
        Extractor.addRecipe((IItemStack)ItemBracketHandler.getItem((String)"ExtraUtilities:cobblestone_compressed", (int)5).amount(9), (IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:cobblestone_compressed", (int)6));
        Extractor.addRecipe((IItemStack)ItemBracketHandler.getItem((String)"ExtraUtilities:cobblestone_compressed", (int)6).amount(9), (IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:cobblestone_compressed", (int)7));
        Extractor.addRecipe((IItemStack)ItemBracketHandler.getItem((String)"minecraft:dirt", (int)0).amount(9), (IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:cobblestone_compressed", (int)8));
        Extractor.addRecipe((IItemStack)ItemBracketHandler.getItem((String)"ExtraUtilities:cobblestone_compressed", (int)8).amount(9), (IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:cobblestone_compressed", (int)9));
        Extractor.addRecipe((IItemStack)ItemBracketHandler.getItem((String)"ExtraUtilities:cobblestone_compressed", (int)9).amount(9), (IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:cobblestone_compressed", (int)10));
        Extractor.addRecipe((IItemStack)ItemBracketHandler.getItem((String)"ExtraUtilities:cobblestone_compressed", (int)10).amount(9), (IIngredient)iItemStack9);
        Extractor.addRecipe((IItemStack)ItemBracketHandler.getItem((String)"minecraft:gravel", (int)0).amount(9), (IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:cobblestone_compressed", (int)12));
        Extractor.addRecipe((IItemStack)ItemBracketHandler.getItem((String)"ExtraUtilities:cobblestone_compressed", (int)12).amount(9), (IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:cobblestone_compressed", (int)13));
        Extractor.addRecipe((IItemStack)ItemBracketHandler.getItem((String)"minecraft:sand", (int)0).amount(9), (IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:cobblestone_compressed", (int)14));
        Extractor.addRecipe((IItemStack)ItemBracketHandler.getItem((String)"ExtraUtilities:cobblestone_compressed", (int)14).amount(9), (IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:cobblestone_compressed", (int)15));
    }
}

