package com.github.GTNH2Mega.fromScripts;
import gttweaker.mods.gregtech.machines.Assembler;
import minetweaker.MineTweakerAPI;
import minetweaker.api.item.IIngredient;
import minetweaker.api.item.IItemStack;
import minetweaker.api.oredict.IOreDictEntry;
import minetweaker.mc1710.brackets.ItemBracketHandler;
import minetweaker.mc1710.brackets.OreBracketHandler;
import static com.github.GTNH2Mega.VoltageLevels.*;
public class ExtraCells
implements Runnable {
    public void run() {
        IItemStack iItemStack4 = ItemBracketHandler.getItem("appliedenergistics2:item.ItemMultiMaterial", 38);
        IItemStack iItemStack5 = ItemBracketHandler.getItem("extracells:storage.component", 0);
        IItemStack iItemStack6 = ItemBracketHandler.getItem("extracells:storage.component", 1);
        IItemStack iItemStack7 = ItemBracketHandler.getItem("extracells:storage.component", 2);
        IItemStack iItemStack8 = ItemBracketHandler.getItem("extracells:storage.component", 3);
        IItemStack iItemStack9 = ItemBracketHandler.getItem("extracells:storage.component", 4);
        IItemStack iItemStack10 = ItemBracketHandler.getItem("extracells:storage.component", 5);
        IItemStack iItemStack11 = ItemBracketHandler.getItem("extracells:storage.component", 6);
        IItemStack iItemStack12 = ItemBracketHandler.getItem("extracells:storage.component", 7);
        IItemStack iItemStack13 = ItemBracketHandler.getItem("extracells:storage.component", 8);
        IItemStack iItemStack14 = ItemBracketHandler.getItem("extracells:storage.component", 9);
        IItemStack iItemStack15 = ItemBracketHandler.getItem("extracells:storage.component", 10);
        IItemStack iItemStack16 = ItemBracketHandler.getItem("extracells:storage.physical", 0);
        IItemStack iItemStack17 = ItemBracketHandler.getItem("extracells:storage.physical", 1);
        IItemStack iItemStack18 = ItemBracketHandler.getItem("extracells:storage.physical", 2);
        IItemStack iItemStack19 = ItemBracketHandler.getItem("extracells:storage.physical", 3);
        IItemStack iItemStack20 = ItemBracketHandler.getItem("extracells:storage.fluid", 0);
        IItemStack iItemStack21 = ItemBracketHandler.getItem("extracells:storage.fluid", 1);
        IItemStack iItemStack22 = ItemBracketHandler.getItem("extracells:storage.fluid", 2);
        IItemStack iItemStack23 = ItemBracketHandler.getItem("extracells:storage.fluid", 3);
        IItemStack iItemStack24 = ItemBracketHandler.getItem("extracells:storage.fluid", 4);
        IItemStack iItemStack25 = ItemBracketHandler.getItem("extracells:storage.fluid", 5);
        IItemStack iItemStack26 = ItemBracketHandler.getItem("extracells:storage.fluid", 6);
        IItemStack iItemStack28 = ItemBracketHandler.getItem("extracells:storage.casing", 0);
        IItemStack iItemStack29 = ItemBracketHandler.getItem("extracells:storage.casing", 1);
        IOreDictEntry iOreDictEntry = OreBracketHandler.getOre("circuitPrimitive");
        IOreDictEntry iOreDictEntry2 = OreBracketHandler.getOre("circuitBasic");
        IOreDictEntry iOreDictEntry3 = OreBracketHandler.getOre("circuitGood");
        IOreDictEntry iOreDictEntry4 = OreBracketHandler.getOre("circuitAdvanced");
        IOreDictEntry iOreDictEntry5 = OreBracketHandler.getOre("circuitData");
        IOreDictEntry iOreDictEntry6 = OreBracketHandler.getOre("circuitElite");
        IOreDictEntry iOreDictEntry7 = OreBracketHandler.getOre("circuitMaster");
        IOreDictEntry iOreDictEntry9 = OreBracketHandler.getOre("circuitSuperconductor");
        IOreDictEntry iOreDictEntry12 = OreBracketHandler.getOre("screwCertusQuartz");
        IItemStack iItemStack35 = ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 17516);
        IOreDictEntry iOreDictEntry15 = OreBracketHandler.getOre("plateTitanium");
        IOreDictEntry iOreDictEntry17 = OreBracketHandler.getOre("plateChrome");
        IItemStack iItemStack37 = ItemBracketHandler.getItem("TConstruct:GlassPane", 0);
        IOreDictEntry iOreDictEntry21 = OreBracketHandler.getOre("craftingToolScrewdriver");
        IOreDictEntry iOreDictEntry23 = OreBracketHandler.getOre("craftingToolHardHammer");
        MineTweakerAPI.recipes.remove(iItemStack16);
        MineTweakerAPI.recipes.remove(iItemStack17);
        MineTweakerAPI.recipes.remove(iItemStack18);
        MineTweakerAPI.recipes.remove(iItemStack19);
        MineTweakerAPI.recipes.remove(iItemStack5);
        MineTweakerAPI.recipes.remove(iItemStack6);
        MineTweakerAPI.recipes.remove(iItemStack7);
        MineTweakerAPI.recipes.remove(iItemStack8);
        MineTweakerAPI.recipes.remove(iItemStack28);
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("extracells:certustank", 0));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("extracells:fluidcrafter", 0));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("extracells:pattern.fluid", 0));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("extracells:part.base", 0));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("extracells:part.base", 1));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("extracells:part.base", 2));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("extracells:part.base", 3));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("extracells:part.base", 4));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("extracells:part.base", 5));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("extracells:part.base", 6));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("extracells:part.base", 7));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("extracells:part.base", 8));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("extracells:part.base", 10));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("extracells:part.base", 11));
        MineTweakerAPI.recipes.remove(iItemStack20);
        MineTweakerAPI.recipes.remove(iItemStack21);
        MineTweakerAPI.recipes.remove(iItemStack22);
        MineTweakerAPI.recipes.remove(iItemStack23);
        MineTweakerAPI.recipes.remove(iItemStack24);
        MineTweakerAPI.recipes.remove(iItemStack25);
        MineTweakerAPI.recipes.remove(iItemStack26);
        MineTweakerAPI.recipes.remove(iItemStack9);
        MineTweakerAPI.recipes.remove(iItemStack10);
        MineTweakerAPI.recipes.remove(iItemStack11);
        MineTweakerAPI.recipes.remove(iItemStack12);
        MineTweakerAPI.recipes.remove(iItemStack13);
        MineTweakerAPI.recipes.remove(iItemStack14);
        MineTweakerAPI.recipes.remove(iItemStack15);
        MineTweakerAPI.recipes.remove(iItemStack29);
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("extracells:ecbaseblock", 0));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("extracells:ecbaseblock", 1));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("extracells:hardmedrive", 0));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("extracells:vibrantchamberfluid", 0));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("extracells:storage.physical", 4));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("extracells:storage.fluid.portable", 0));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("extracells:terminal.fluid.wireless", 0));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("extracells:oc.upgrade", 2));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("extracells:oc.upgrade", 1));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("extracells:oc.upgrade", 0));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("extracells:part.base", 13));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("extracells:part.base", 14));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("extracells:part.base", 15));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("extracells:storage.gas", 0));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("extracells:storage.gas", 1));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("extracells:storage.gas", 2));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("extracells:storage.gas", 3));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("extracells:storage.gas", 4));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("extracells:storage.gas", 5));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("extracells:storage.gas", 6));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("extracells:storage.component", 11));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("extracells:storage.component", 12));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("extracells:storage.component", 13));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("extracells:storage.component", 14));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("extracells:storage.component", 15));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("extracells:storage.component", 16));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("extracells:storage.component", 17));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("extracells:storage.casing", 2));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("extracells:craftingstorage", 0));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("extracells:craftingstorage", 1));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("extracells:craftingstorage", 2));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("extracells:craftingstorage", 3));
        MineTweakerAPI.recipes.addShaped(iItemStack16, new IIngredient[][]{{iOreDictEntry23, iItemStack35, iOreDictEntry12}, {iOreDictEntry17, iItemStack5, iOreDictEntry17}, {iOreDictEntry12, iOreDictEntry17, iOreDictEntry21}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack16, new IIngredient[][]{{iOreDictEntry23, iItemStack35, iOreDictEntry12}, {iOreDictEntry17, iItemStack5, iOreDictEntry17}, {iOreDictEntry12, iOreDictEntry17, iOreDictEntry21}}, null);
        MineTweakerAPI.recipes.addShapeless(ItemBracketHandler.getItem("extracells:storage.physical", 0), new IIngredient[]{ItemBracketHandler.getItem("extracells:storage.component", 0), ItemBracketHandler.getItem("extracells:storage.casing", 0)}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack17, new IIngredient[][]{{iOreDictEntry23, iItemStack35, iOreDictEntry12}, {iOreDictEntry17, iItemStack6, iOreDictEntry17}, {iOreDictEntry12, iOreDictEntry17, iOreDictEntry21}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack17, new IIngredient[][]{{iOreDictEntry23, iItemStack35, iOreDictEntry12}, {iOreDictEntry17, iItemStack6, iOreDictEntry17}, {iOreDictEntry12, iOreDictEntry17, iOreDictEntry21}}, null);
        MineTweakerAPI.recipes.addShapeless(ItemBracketHandler.getItem("extracells:storage.physical", 1), new IIngredient[]{ItemBracketHandler.getItem("extracells:storage.component", 1), ItemBracketHandler.getItem("extracells:storage.casing", 0)}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack18, new IIngredient[][]{{iOreDictEntry23, iItemStack35, iOreDictEntry12}, {iOreDictEntry17, iItemStack7, iOreDictEntry17}, {iOreDictEntry12, iOreDictEntry17, iOreDictEntry21}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack18, new IIngredient[][]{{iOreDictEntry23, iItemStack35, iOreDictEntry12}, {iOreDictEntry17, iItemStack7, iOreDictEntry17}, {iOreDictEntry12, iOreDictEntry17, iOreDictEntry21}}, null);
        MineTweakerAPI.recipes.addShapeless(ItemBracketHandler.getItem("extracells:storage.physical", 2), new IIngredient[]{ItemBracketHandler.getItem("extracells:storage.component", 2), ItemBracketHandler.getItem("extracells:storage.casing", 0)}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack19, new IIngredient[][]{{iOreDictEntry23, iItemStack35, iOreDictEntry12}, {iOreDictEntry17, iItemStack8, iOreDictEntry17}, {iOreDictEntry12, iOreDictEntry17, iOreDictEntry21}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack19, new IIngredient[][]{{iOreDictEntry23, iItemStack35, iOreDictEntry12}, {iOreDictEntry17, iItemStack8, iOreDictEntry17}, {iOreDictEntry12, iOreDictEntry17, iOreDictEntry21}}, null);
        MineTweakerAPI.recipes.addShapeless(ItemBracketHandler.getItem("extracells:storage.physical", 3), new IIngredient[]{ItemBracketHandler.getItem("extracells:storage.component", 3), ItemBracketHandler.getItem("extracells:storage.casing", 0)}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack5, new IIngredient[][]{{iOreDictEntry5, iItemStack4, iOreDictEntry5}, {iItemStack4, ItemBracketHandler.getItem("dreamcraft:item.EngineeringProcessorItemEmeraldCore", 0), iItemStack4}, {iOreDictEntry5, iItemStack4, iOreDictEntry5}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack6, new IIngredient[][]{{iOreDictEntry6, iItemStack5, iOreDictEntry6}, {iItemStack5, ItemBracketHandler.getItem("dreamcraft:item.EngineeringProcessorItemEmeraldCore", 0), iItemStack5}, {iOreDictEntry6, iItemStack5, iOreDictEntry6}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack7, new IIngredient[][]{{iOreDictEntry7, iItemStack6, iOreDictEntry7}, {iItemStack6, ItemBracketHandler.getItem("dreamcraft:item.EngineeringProcessorItemAdvEmeraldCore", 0), iItemStack6}, {iOreDictEntry7, iItemStack6, iOreDictEntry7}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack8, new IIngredient[][]{{iOreDictEntry9, iItemStack7, iOreDictEntry9}, {iItemStack7, ItemBracketHandler.getItem("dreamcraft:item.EngineeringProcessorItemAdvEmeraldCore", 0), iItemStack7}, {iOreDictEntry9, iItemStack7, iOreDictEntry9}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack28, new IIngredient[][]{{iOreDictEntry23, iItemStack35, iOreDictEntry12}, {iOreDictEntry17, iItemStack37, iOreDictEntry17}, {iOreDictEntry12, iOreDictEntry17, iOreDictEntry21}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack28, new IIngredient[][]{{iOreDictEntry21, iItemStack35, iOreDictEntry12}, {iOreDictEntry17, iItemStack37, iOreDictEntry17}, {iOreDictEntry12, iOreDictEntry17, iOreDictEntry23}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack20, new IIngredient[][]{{iOreDictEntry23, iItemStack35, iOreDictEntry12}, {iOreDictEntry15, iItemStack9, iOreDictEntry15}, {iOreDictEntry12, iOreDictEntry15, iOreDictEntry21}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack20, new IIngredient[][]{{iOreDictEntry21, iItemStack35, iOreDictEntry12}, {iOreDictEntry15, iItemStack9, iOreDictEntry15}, {iOreDictEntry12, iOreDictEntry15, iOreDictEntry23}}, null);
        MineTweakerAPI.recipes.addShapeless(ItemBracketHandler.getItem("extracells:storage.fluid", 0), new IIngredient[]{ItemBracketHandler.getItem("extracells:storage.component", 4), ItemBracketHandler.getItem("extracells:storage.casing", 1)}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack21, new IIngredient[][]{{iOreDictEntry23, iItemStack35, iOreDictEntry12}, {iOreDictEntry15, iItemStack10, iOreDictEntry15}, {iOreDictEntry12, iOreDictEntry15, iOreDictEntry21}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack21, new IIngredient[][]{{iOreDictEntry21, iItemStack35, iOreDictEntry12}, {iOreDictEntry15, iItemStack10, iOreDictEntry15}, {iOreDictEntry12, iOreDictEntry15, iOreDictEntry23}}, null);
        MineTweakerAPI.recipes.addShapeless(ItemBracketHandler.getItem("extracells:storage.fluid", 1), new IIngredient[]{ItemBracketHandler.getItem("extracells:storage.component", 5), ItemBracketHandler.getItem("extracells:storage.casing", 1)}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack22, new IIngredient[][]{{iOreDictEntry23, iItemStack35, iOreDictEntry12}, {iOreDictEntry15, iItemStack11, iOreDictEntry15}, {iOreDictEntry12, iOreDictEntry15, iOreDictEntry21}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack22, new IIngredient[][]{{iOreDictEntry21, iItemStack35, iOreDictEntry12}, {iOreDictEntry15, iItemStack11, iOreDictEntry15}, {iOreDictEntry12, iOreDictEntry15, iOreDictEntry23}}, null);
        MineTweakerAPI.recipes.addShapeless(ItemBracketHandler.getItem("extracells:storage.fluid", 2), new IIngredient[]{ItemBracketHandler.getItem("extracells:storage.component", 6), ItemBracketHandler.getItem("extracells:storage.casing", 1)}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack23, new IIngredient[][]{{iOreDictEntry23, iItemStack35, iOreDictEntry12}, {iOreDictEntry15, iItemStack12, iOreDictEntry15}, {iOreDictEntry12, iOreDictEntry15, iOreDictEntry21}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack23, new IIngredient[][]{{iOreDictEntry23, iItemStack35, iOreDictEntry12}, {iOreDictEntry15, iItemStack12, iOreDictEntry15}, {iOreDictEntry12, iOreDictEntry15, iOreDictEntry21}}, null);
        MineTweakerAPI.recipes.addShapeless(ItemBracketHandler.getItem("extracells:storage.fluid", 3), new IIngredient[]{ItemBracketHandler.getItem("extracells:storage.component", 7), ItemBracketHandler.getItem("extracells:storage.casing", 1)}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack24, new IIngredient[][]{{iOreDictEntry23, iItemStack35, iOreDictEntry12}, {iOreDictEntry15, iItemStack13, iOreDictEntry15}, {iOreDictEntry12, iOreDictEntry15, iOreDictEntry21}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack24, new IIngredient[][]{{iOreDictEntry23, iItemStack35, iOreDictEntry12}, {iOreDictEntry15, iItemStack13, iOreDictEntry15}, {iOreDictEntry12, iOreDictEntry15, iOreDictEntry21}}, null);
        MineTweakerAPI.recipes.addShapeless(ItemBracketHandler.getItem("extracells:storage.fluid", 4), new IIngredient[]{ItemBracketHandler.getItem("extracells:storage.component", 8), ItemBracketHandler.getItem("extracells:storage.casing", 1)}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack25, new IIngredient[][]{{iOreDictEntry23, iItemStack35, iOreDictEntry12}, {iOreDictEntry15, iItemStack14, iOreDictEntry15}, {iOreDictEntry12, iOreDictEntry15, iOreDictEntry21}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack25, new IIngredient[][]{{iOreDictEntry23, iItemStack35, iOreDictEntry12}, {iOreDictEntry15, iItemStack14, iOreDictEntry15}, {iOreDictEntry12, iOreDictEntry15, iOreDictEntry21}}, null);
        MineTweakerAPI.recipes.addShapeless(ItemBracketHandler.getItem("extracells:storage.fluid", 5), new IIngredient[]{ItemBracketHandler.getItem("extracells:storage.component", 9), ItemBracketHandler.getItem("extracells:storage.casing", 1)}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack26, new IIngredient[][]{{iOreDictEntry23, iItemStack35, iOreDictEntry12}, {iOreDictEntry15, iItemStack15, iOreDictEntry15}, {iOreDictEntry12, iOreDictEntry15, iOreDictEntry21}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack26, new IIngredient[][]{{iOreDictEntry23, iItemStack35, iOreDictEntry12}, {iOreDictEntry15, iItemStack15, iOreDictEntry15}, {iOreDictEntry12, iOreDictEntry15, iOreDictEntry21}}, null);
        MineTweakerAPI.recipes.addShapeless(ItemBracketHandler.getItem("extracells:storage.fluid", 6), new IIngredient[]{ItemBracketHandler.getItem("extracells:storage.component", 10), ItemBracketHandler.getItem("extracells:storage.casing", 1)}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack9, new IIngredient[][]{{iOreDictEntry, ItemBracketHandler.getItem("appliedenergistics2:item.ItemMultiMaterial", 8), iOreDictEntry}, {ItemBracketHandler.getItem("appliedenergistics2:item.ItemMultiMaterial", 8), ItemBracketHandler.getItem("dreamcraft:item.EngineeringProcessorFluidDiamondCore", 0), ItemBracketHandler.getItem("appliedenergistics2:item.ItemMultiMaterial", 8)}, {iOreDictEntry, ItemBracketHandler.getItem("appliedenergistics2:item.ItemMultiMaterial", 8), iOreDictEntry}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack10, new IIngredient[][]{{iOreDictEntry2, iItemStack9, iOreDictEntry2}, {iItemStack9, ItemBracketHandler.getItem("dreamcraft:item.EngineeringProcessorFluidDiamondCore", 0), iItemStack9}, {iOreDictEntry2, iItemStack9, iOreDictEntry2}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack11, new IIngredient[][]{{iOreDictEntry3, iItemStack10, iOreDictEntry3}, {iItemStack10, ItemBracketHandler.getItem("dreamcraft:item.EngineeringProcessorFluidDiamondCore", 0), iItemStack10}, {iOreDictEntry3, iItemStack10, iOreDictEntry3}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack12, new IIngredient[][]{{iOreDictEntry4, iItemStack11, iOreDictEntry4}, {iItemStack11, ItemBracketHandler.getItem("dreamcraft:item.EngineeringProcessorFluidDiamondCore", 0), iItemStack11}, {iOreDictEntry4, iItemStack11, iOreDictEntry4}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack13, new IIngredient[][]{{iOreDictEntry5, iItemStack12, iOreDictEntry5}, {iItemStack12, ItemBracketHandler.getItem("dreamcraft:item.EngineeringProcessorFluidEmeraldCore", 0), iItemStack12}, {iOreDictEntry5, iItemStack12, iOreDictEntry5}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack14, new IIngredient[][]{{iOreDictEntry6, iItemStack13, iOreDictEntry6}, {iItemStack13, ItemBracketHandler.getItem("dreamcraft:item.EngineeringProcessorFluidEmeraldCore", 0), iItemStack13}, {iOreDictEntry6, iItemStack13, iOreDictEntry6}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack15, new IIngredient[][]{{iOreDictEntry7, iItemStack14, iOreDictEntry7}, {iItemStack14, ItemBracketHandler.getItem("dreamcraft:item.EngineeringProcessorFluidEmeraldCore", 0), iItemStack14}, {iOreDictEntry7, iItemStack14, iOreDictEntry7}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack29, new IIngredient[][]{{iOreDictEntry23, iItemStack35, iOreDictEntry12}, {iOreDictEntry15, iItemStack37, iOreDictEntry15}, {iOreDictEntry12, iOreDictEntry15, iOreDictEntry21}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack29, new IIngredient[][]{{iOreDictEntry21, iItemStack35, iOreDictEntry12}, {iOreDictEntry15, iItemStack37, iOreDictEntry15}, {iOreDictEntry12, iOreDictEntry15, iOreDictEntry23}}, null);
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("extracells:part.base", 3), new IIngredient[][]{{OreBracketHandler.getOre("plateLapis"), ItemBracketHandler.getItem("appliedenergistics2:item.ItemMultiPart", 16), OreBracketHandler.getOre("plateLapis")}, {ItemBracketHandler.getItem("appliedenergistics2:item.ItemMultiMaterial", 43), ItemBracketHandler.getItem("appliedenergistics2:item.ItemMultiPart", 380), ItemBracketHandler.getItem("appliedenergistics2:item.ItemMultiMaterial", 44)}, {OreBracketHandler.getOre("plateLapis"), ItemBracketHandler.getItem("appliedenergistics2:item.ItemMultiPart", 16), OreBracketHandler.getOre("plateLapis")}}, null);
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("extracells:fluidcrafter", 0), new IIngredient[][]{{OreBracketHandler.getOre("plateLapis"), ItemBracketHandler.getItem("appliedenergistics2:item.ItemMultiPart", 16), OreBracketHandler.getOre("plateLapis")}, {ItemBracketHandler.getItem("extracells:storage.component", 4), ItemBracketHandler.getItem("appliedenergistics2:tile.BlockMolecularAssembler", 0), ItemBracketHandler.getItem("extracells:storage.component", 4)}, {OreBracketHandler.getOre("plateLapis"), ItemBracketHandler.getItem("appliedenergistics2:item.ItemMultiPart", 16), OreBracketHandler.getOre("plateLapis")}}, null);
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("extracells:ecbaseblock", 0), new IIngredient[][]{{OreBracketHandler.getOre("plateLapis"), ItemBracketHandler.getItem("appliedenergistics2:item.ItemMultiPart", 16), OreBracketHandler.getOre("plateLapis")}, {ItemBracketHandler.getItem("extracells:storage.component", 4), ItemBracketHandler.getItem("appliedenergistics2:tile.BlockInterface", 0), ItemBracketHandler.getItem("extracells:storage.component", 4)}, {OreBracketHandler.getOre("plateLapis"), ItemBracketHandler.getItem("appliedenergistics2:item.ItemMultiPart", 16), OreBracketHandler.getOre("plateLapis")}}, null);
        MineTweakerAPI.recipes.addShapeless(ItemBracketHandler.getItem("extracells:ecbaseblock", 0), new IIngredient[]{ItemBracketHandler.getItem("extracells:part.base", 9)}, null);
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("extracells:ecbaseblock", 1), new IIngredient[][]{{OreBracketHandler.getOre("plateLapis"), ItemBracketHandler.getItem("extracells:part.base", 3), OreBracketHandler.getOre("plateLapis")}, {ItemBracketHandler.getItem("appliedenergistics2:item.ItemMultiPart", 16), ItemBracketHandler.getItem("extracells:fluidcrafter", 0), ItemBracketHandler.getItem("appliedenergistics2:item.ItemMultiPart", 16)}, {OreBracketHandler.getOre("plateLapis"), ItemBracketHandler.getItem("extracells:part.base", 4), OreBracketHandler.getOre("plateLapis")}}, null);
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("extracells:hardmedrive", 0), new IIngredient[][]{{OreBracketHandler.getOre("plateDenseObsidian"), ItemBracketHandler.getItem("appliedenergistics2:item.ItemMultiPart", 76), OreBracketHandler.getOre("plateDenseObsidian")}, {OreBracketHandler.getOre("plateDenseObsidian"), ItemBracketHandler.getItem("appliedenergistics2:tile.BlockDrive", 0), OreBracketHandler.getOre("plateDenseObsidian")}, {OreBracketHandler.getOre("plateDenseLead"), OreBracketHandler.getOre("plateDenseLead"), OreBracketHandler.getOre("plateDenseLead")}}, null);
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("extracells:vibrantchamberfluid", 0), new IIngredient[][]{{OreBracketHandler.getOre("plateLapis"), ItemBracketHandler.getItem("extracells:part.base", 3), OreBracketHandler.getOre("plateLapis")}, {ItemBracketHandler.getItem("appliedenergistics2:item.ItemMultiPart", 16), ItemBracketHandler.getItem("appliedenergistics2:tile.BlockVibrationChamber", 0), ItemBracketHandler.getItem("appliedenergistics2:item.ItemMultiPart", 16)}, {OreBracketHandler.getOre("plateLapis"), ItemBracketHandler.getItem("extracells:certustank", 0), OreBracketHandler.getOre("plateLapis")}}, null);
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("extracells:storage.physical", 4), new IIngredient[][]{{null, ItemBracketHandler.getItem("appliedenergistics2:item.ItemMultiMaterial", 35), null}, {OreBracketHandler.getOre("screwTitanium"), ItemBracketHandler.getItem("appliedenergistics2:tile.BlockChest", 0), OreBracketHandler.getOre("screwTitanium")}, {OreBracketHandler.getOre("craftingToolScrewdriver"), ItemBracketHandler.getItem("appliedenergistics2:item.ItemMultiMaterial", 39), OreBracketHandler.getOre("craftingToolWrench")}}, null);
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("extracells:storage.fluid.portable", 0), new IIngredient[][]{{null, ItemBracketHandler.getItem("extracells:storage.component", 4), null}, {OreBracketHandler.getOre("screwTitanium"), ItemBracketHandler.getItem("appliedenergistics2:tile.BlockChest", 0), OreBracketHandler.getOre("screwTitanium")}, {OreBracketHandler.getOre("craftingToolScrewdriver"), ItemBracketHandler.getItem("appliedenergistics2:tile.BlockEnergyCell", 0), OreBracketHandler.getOre("craftingToolWrench")}}, null);
        Assembler.addRecipe(ItemBracketHandler.getItem("extracells:certustank", 0), ItemBracketHandler.getItem("appliedenergistics2:tile.BlockQuartzGlass", 0).amount(8), ItemBracketHandler.getItem("gregtech:gt.integrated_circuit", 8).amount(0), 800,LV);
      Assembler.addRecipe(ItemBracketHandler.getItem("extracells:part.base", 0), ItemBracketHandler.getItem("appliedenergistics2:item.ItemMultiPart", 260), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 17526).amount(3), 300, MV);

        Assembler.addRecipe(ItemBracketHandler.getItem("extracells:part.base", 1), ItemBracketHandler.getItem("appliedenergistics2:item.ItemMultiPart", 240), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 17526).amount(3), 300, MV);

        Assembler.addRecipe(ItemBracketHandler.getItem("extracells:part.base", 2), ItemBracketHandler.getItem("appliedenergistics2:item.ItemMultiPart", 220), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 17526).amount(3), 300, MV);

        Assembler.addRecipe(ItemBracketHandler.getItem("extracells:part.base", 4), ItemBracketHandler.getItem("appliedenergistics2:item.ItemMultiPart", 280), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 17526), 100, MV);

        Assembler.addRecipe(ItemBracketHandler.getItem("extracells:part.base", 5), ItemBracketHandler.getItem("appliedenergistics2:item.ItemMultiPart", 300), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 17526).amount(3), 300, MV);

        Assembler.addRecipe(ItemBracketHandler.getItem("extracells:part.base", 6), ItemBracketHandler.getItem("appliedenergistics2:item.ItemMultiPart", 320), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 17526).amount(3), 300, MV);

        Assembler.addRecipe(ItemBracketHandler.getItem("extracells:part.base", 7), ItemBracketHandler.getItem("appliedenergistics2:tile.BlockDrive", 0), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 17306).amount(3), 300, MV);

        Assembler.addRecipe(ItemBracketHandler.getItem("extracells:part.base", 8), ItemBracketHandler.getItem("appliedenergistics2:tile.BlockEnergyCell", 0), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 17306).amount(3), 300, MV);

        Assembler.addRecipe(ItemBracketHandler.getItem("extracells:part.base", 10), ItemBracketHandler.getItem("appliedenergistics2:item.ItemMultiPart", 400), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 17526).amount(3), 300, MV);

        Assembler.addRecipe(ItemBracketHandler.getItem("extracells:part.base", 11), ItemBracketHandler.getItem("appliedenergistics2:item.ItemMultiPart", 420), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 17526).amount(3), 300, MV);

        Assembler.addRecipe(ItemBracketHandler.getItem("extracells:pattern.fluid", 0), ItemBracketHandler.getItem("extracells:storage.casing", 1), ItemBracketHandler.getItem("minecraft:bucket", 0), 100, MV);

        Assembler.addRecipe(ItemBracketHandler.getItem("extracells:terminal.fluid.wireless", 0), ItemBracketHandler.getItem("appliedenergistics2:item.ToolWirelessTerminal", 32767), ItemBracketHandler.getItem("extracells:part.base", 3), 600, MV);

        Assembler.addRecipe(ItemBracketHandler.getItem("extracells:craftingstorage", 0), ItemBracketHandler.getItem("appliedenergistics2:tile.BlockCraftingUnit", 0), ItemBracketHandler.getItem("extracells:storage.component", 0), 400, EV);
        Assembler.addRecipe(ItemBracketHandler.getItem("extracells:craftingstorage", 1), ItemBracketHandler.getItem("appliedenergistics2:tile.BlockCraftingUnit", 0), ItemBracketHandler.getItem("extracells:storage.component", 1), 400, EV);
        Assembler.addRecipe(ItemBracketHandler.getItem("extracells:craftingstorage", 2), ItemBracketHandler.getItem("appliedenergistics2:tile.BlockCraftingUnit", 0), ItemBracketHandler.getItem("extracells:storage.component", 2), 400, EV);
        Assembler.addRecipe(ItemBracketHandler.getItem("extracells:craftingstorage", 3), ItemBracketHandler.getItem("appliedenergistics2:tile.BlockCraftingUnit", 0), ItemBracketHandler.getItem("extracells:storage.component", 3), 400, EV);
        Assembler.addRecipe(ItemBracketHandler.getItem("appliedenergistics2:tile.BlockCraftingStorage", 3), ItemBracketHandler.getItem("appliedenergistics2:tile.BlockCraftingUnit", 0), ItemBracketHandler.getItem("appliedenergistics2:item.ItemMultiMaterial", 38), 400, HV);

    }
}

