package com.github.GTNH2Mega.fromScripts;

import com.github.GTNH2Mega.ZenHelperClasses.ZenClass0;
import com.github.GTNH2Mega.ZenHelperClasses.ZenClass1;
import com.github.GTNH2Mega.ZenHelperClasses.ZenClass2;
import com.github.GTNH2Mega.ZenHelperClasses.ZenClass3;
import gttweaker.mods.gregtech.machines.AlloySmelter;
import gttweaker.mods.gregtech.machines.Assembler;
import minetweaker.MineTweakerAPI;
import minetweaker.api.item.IIngredient;
import minetweaker.api.item.IItemStack;
import minetweaker.api.item.IngredientAny;
import minetweaker.api.oredict.IOreDictEntry;
import minetweaker.mc1710.brackets.ItemBracketHandler;
import minetweaker.mc1710.brackets.LiquidBracketHandler;
import minetweaker.mc1710.brackets.OreBracketHandler;
import minetweaker.mods.ic2.machines.Compressor;
import minetweaker.mods.ic2.machines.Extractor;
import modtweaker2.mods.extraUtils.handlers.QED;
import modtweaker2.mods.tconstruct.handlers.Casting;

public class ExtraUtilities
implements Runnable {
    public void run() {
        IItemStack iItemStack = ItemBracketHandler.getItem("ExtraUtilities:enderThermicPump", 0);
        IItemStack iItemStack2 = ItemBracketHandler.getItem("ExtraUtilities:decorativeBlock1", 1);
        IItemStack iItemStack3 = ItemBracketHandler.getItem("ExtraUtilities:decorativeBlock1", 11);
        IItemStack iItemStack4 = ItemBracketHandler.getItem("ExtraUtilities:decorativeBlock1", 8);
        IItemStack iItemStack5 = ItemBracketHandler.getItem("ExtraUtilities:decorativeBlock1", 12);
        IItemStack iItemStack6 = ItemBracketHandler.getItem("ExtraUtilities:decorativeBlock1", 2);
        IItemStack iItemStack7 = ItemBracketHandler.getItem("ExtraUtilities:enderQuarryUpgrade", 0);
        IItemStack iItemStack8 = ItemBracketHandler.getItem("ExtraUtilities:cobblestone_compressed", 6);
        IItemStack iItemStack9 = ItemBracketHandler.getItem("ExtraUtilities:cobblestone_compressed", 11);
        IOreDictEntry iOreDictEntry3 = OreBracketHandler.getOre("pipeSmallStainlessSteel");
        IItemStack iItemStack10 = ItemBracketHandler.getItem("ExtraUtilities:paintbrush", 0);
        IItemStack iItemStack11 = ItemBracketHandler.getItem("harvestcraft:wovencottonItem", 0);
        IItemStack iItemStack12 = ItemBracketHandler.getItem("TConstruct:materials", 26);
        IItemStack iItemStack13 = ItemBracketHandler.getItem("ExtraUtilities:timer", 0);
        IItemStack iItemStack14 = ItemBracketHandler.getItem("minecraft:clock", 0);
        IItemStack iItemStack15 = ItemBracketHandler.getItem("ExtraUtilities:drum", 0);
        IItemStack iItemStack16 = ItemBracketHandler.getItem("ExtraUtilities:drum", 1);
        IItemStack iItemStack18 = ItemBracketHandler.getItem("ExtraUtilities:bedrockiumIngot", 0);
        IItemStack iItemStack19 = ItemBracketHandler.getItem("ExtraUtilities:block_bedrockium", 0);
        IItemStack iItemStack21 = ItemBracketHandler.getItem("ExtraUtilities:angelBlock", 0);
        IItemStack iItemStack22 = ItemBracketHandler.getItem("ExtraUtilities:conveyor", 0);
        IItemStack iItemStack25 = ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32641);
        IItemStack iItemStack26 = ItemBracketHandler.getItem("minecraft:iron_bars", 0);
        IItemStack iItemStack27 = ItemBracketHandler.getItem("dreamcraft:item.SteelBars", 0);
        IItemStack iItemStack28 = ItemBracketHandler.getItem("ExtraUtilities:filing", 0);
        IItemStack iItemStack29 = ItemBracketHandler.getItem("ExtraUtilities:filing", 1);
        IItemStack iItemStack30 = ItemBracketHandler.getItem("ExtraUtilities:watering_can", 1);
        IItemStack iItemStack31 = ItemBracketHandler.getItem("IC2:blockMachine2", 11);
        IOreDictEntry iOreDictEntry4 = OreBracketHandler.getOre("gearStainlessSteel");
        IItemStack iItemStack35 = ItemBracketHandler.getItem("ExtraUtilities:sound_muffler", 0);
        IItemStack iItemStack36 = ItemBracketHandler.getItem("ExtraUtilities:sound_muffler", 1);
        IOreDictEntry iOreDictEntry5 = OreBracketHandler.getOre("blockWool");
        IItemStack iItemStack37 = ItemBracketHandler.getItem("minecraft:noteblock", 0);
        IItemStack iItemStack38 = ItemBracketHandler.getItem("ExtraUtilities:budoff", 0);
        IItemStack iItemStack39 = ItemBracketHandler.getItem("minecraft:water_bucket", 0);
        IItemStack iItemStack40 = ItemBracketHandler.getItem("gregtech:gt.blockmachines", 9271);
        IItemStack iItemStack41 = ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32675);
        IItemStack iItemStack42 = ItemBracketHandler.getItem("gregtech:gt.blockmachines", 11102);
        IItemStack iItemStack43 = ItemBracketHandler.getItem("gregtech:gt.blockmachines", 11103);
        IItemStack iItemStack44 = ItemBracketHandler.getItem("gregtech:gt.blockmachines", 11104);
        IItemStack iItemStack45 = ItemBracketHandler.getItem("ExtraUtilities:nodeUpgrade", 0);
        IItemStack iItemStack46 = ItemBracketHandler.getItem("ExtraUtilities:nodeUpgrade", 1);
        IItemStack iItemStack47 = ItemBracketHandler.getItem("ExtraUtilities:nodeUpgrade", 2);
        IItemStack iItemStack48 = ItemBracketHandler.getItem("ExtraUtilities:nodeUpgrade", 3);
        IItemStack iItemStack49 = ItemBracketHandler.getItem("ExtraUtilities:nodeUpgrade", 5);
        IItemStack iItemStack50 = ItemBracketHandler.getItem("ExtraUtilities:nodeUpgrade", 6);
        IItemStack iItemStack51 = ItemBracketHandler.getItem("ExtraUtilities:nodeUpgrade", 7);
        IItemStack iItemStack52 = ItemBracketHandler.getItem("ExtraUtilities:nodeUpgrade", 8);
        IItemStack iItemStack53 = ItemBracketHandler.getItem("ExtraUtilities:nodeUpgrade", 9);
        IOreDictEntry iOreDictEntry6 = OreBracketHandler.getOre("stickRedAlloy");
        IOreDictEntry iOreDictEntry8 = OreBracketHandler.getOre("plateWood");
        IOreDictEntry iOreDictEntry9 = OreBracketHandler.getOre("plateAnyIron");
        IOreDictEntry iOreDictEntry10 = OreBracketHandler.getOre("plateGold");
        IOreDictEntry iOreDictEntry11 = OreBracketHandler.getOre("plateDiamond");
        IOreDictEntry iOreDictEntry12 = OreBracketHandler.getOre("ringSteel");
        IOreDictEntry iOreDictEntry13 = OreBracketHandler.getOre("gearStainlessSteel");
        IOreDictEntry iOreDictEntry14 = OreBracketHandler.getOre("stickAnyIron");
        IOreDictEntry iOreDictEntry15 = OreBracketHandler.getOre("plateSteel");
        IOreDictEntry iOreDictEntry17 = OreBracketHandler.getOre("gearDiamond");
        IOreDictEntry iOreDictEntry19 = OreBracketHandler.getOre("foilSteel");
        IOreDictEntry iOreDictEntry20 = OreBracketHandler.getOre("screwSteel");
        IOreDictEntry iOreDictEntry21 = OreBracketHandler.getOre("plateRedAlloy");
        IOreDictEntry iOreDictEntry22 = OreBracketHandler.getOre("foilRedAlloy");
        IOreDictEntry iOreDictEntry23 = OreBracketHandler.getOre("plateElectrum");
        IOreDictEntry iOreDictEntry24 = OreBracketHandler.getOre("plateEuropium");
        IOreDictEntry iOreDictEntry25 = OreBracketHandler.getOre("foilElectrum");
        IOreDictEntry iOreDictEntry26 = OreBracketHandler.getOre("plateEnderPearl");
        IOreDictEntry iOreDictEntry27 = OreBracketHandler.getOre("plateEnderEye");
        IOreDictEntry iOreDictEntry28 = OreBracketHandler.getOre("plateNetherStar");
        IOreDictEntry iOreDictEntry33 = OreBracketHandler.getOre("circuitBasic");
        IOreDictEntry iOreDictEntry34 = OreBracketHandler.getOre("circuitGood");
        IOreDictEntry iOreDictEntry35 = OreBracketHandler.getOre("circuitAdvanced");
        IOreDictEntry iOreDictEntry36 = OreBracketHandler.getOre("circuitData");
        IItemStack iItemStack55 = ItemBracketHandler.getItem("gregtech:gt.blockmachines", 9231);
        IItemStack iItemStack56 = ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32610);
        IOreDictEntry iOreDictEntry39 = OreBracketHandler.getOre("pipeMediumBrass");
        IItemStack iItemStack59 = ItemBracketHandler.getItem("BuildCraft|Factory:tankBlock", 0);
        IItemStack iItemStack60 = ItemBracketHandler.getItem("minecraft:diamond_pickaxe", 0);
        IItemStack iItemStack61 = ItemBracketHandler.getItem("minecraft:iron_pickaxe", 0);
        IItemStack iItemStack62 = ItemBracketHandler.getItem("IronChest:BlockIronChest", 0);
        IOreDictEntry iOreDictEntry44 = OreBracketHandler.getOre("gearWood");
        IOreDictEntry iOreDictEntry47 = OreBracketHandler.getOre("plateLapis");
        IItemStack iItemStack63 = ItemBracketHandler.getItem("ExtraUtilities:pipes", 0);
        IItemStack iItemStack64 = ItemBracketHandler.getItem("ExtraUtilities:pipes", 8);
        IItemStack iItemStack65 = ItemBracketHandler.getItem("ExtraUtilities:pipes", 9);
        IItemStack iItemStack66 = ItemBracketHandler.getItem("ExtraUtilities:pipes", 10);
        IItemStack iItemStack67 = ItemBracketHandler.getItem("ExtraUtilities:pipes.1", 0);
        IItemStack iItemStack68 = ItemBracketHandler.getItem("ExtraUtilities:pipes", 11);
        IItemStack iItemStack69 = ItemBracketHandler.getItem("ExtraUtilities:pipes", 12);
        IItemStack iItemStack70 = ItemBracketHandler.getItem("ExtraUtilities:pipes", 13);
        IItemStack iItemStack71 = ItemBracketHandler.getItem("ExtraUtilities:pipes", 14);
        IItemStack iItemStack72 = ItemBracketHandler.getItem("ExtraUtilities:pipes", 32767);
        IItemStack iItemStack73 = ItemBracketHandler.getItem("ExtraUtilities:extractor_base_remote", 0);
        IItemStack iItemStack74 = ItemBracketHandler.getItem("ExtraUtilities:extractor_base_remote", 6);
        IItemStack iItemStack75 = ItemBracketHandler.getItem("ExtraUtilities:extractor_base", 0);
        IItemStack iItemStack76 = ItemBracketHandler.getItem("ExtraUtilities:extractor_base", 6);
        IItemStack iItemStack77 = ItemBracketHandler.getItem("ExtraUtilities:extractor_base", 12);
        IItemStack iItemStack78 = ItemBracketHandler.getItem("ExtraUtilities:extractor_base", 13);
        IItemStack iItemStack79 = ItemBracketHandler.getItem("ExtraUtilities:magnumTorch", 0);
        IItemStack iItemStack80 = ItemBracketHandler.getItem("ExtraUtilities:chandelier", 0);
        IItemStack iItemStack81 = ItemBracketHandler.getItem("Thaumcraft:ItemResource", 1);
        IItemStack iItemStack84 = ItemBracketHandler.getItem("gregtech:gt.blockmachines", 5132);
        IItemStack iItemStack85 = ItemBracketHandler.getItem("gregtech:gt.metaitem.02", 20305);
        IItemStack iItemStack86 = ItemBracketHandler.getItem("BuildCraft|Transport:item.buildcraftPipe.pipepowerdiamond", 0);
        IOreDictEntry iOreDictEntry50 = OreBracketHandler.getOre("logWood");
        IOreDictEntry iOreDictEntry52 = OreBracketHandler.getOre("screwWood");
        IOreDictEntry iOreDictEntry53 = OreBracketHandler.getOre("blockIron");
        IOreDictEntry iOreDictEntry55 = OreBracketHandler.getOre("screwIron");
        IOreDictEntry iOreDictEntry56 = OreBracketHandler.getOre("blockGold");
        IOreDictEntry iOreDictEntry58 = OreBracketHandler.getOre("screwGold");
        IOreDictEntry iOreDictEntry59 = OreBracketHandler.getOre("blockDiamond");
        IOreDictEntry iOreDictEntry61 = OreBracketHandler.getOre("screwDiamond");
        IOreDictEntry iOreDictEntry62 = OreBracketHandler.getOre("craftingToolHardHammer");
        IOreDictEntry iOreDictEntry63 = OreBracketHandler.getOre("craftingToolWrench");
        IOreDictEntry iOreDictEntry64 = OreBracketHandler.getOre("craftingToolScrewdriver");
        IOreDictEntry iOreDictEntry65 = OreBracketHandler.getOre("craftingToolSaw");
        IItemStack iItemStack87 = ItemBracketHandler.getItem("minecraft:shears", 0);
        QED.removeRecipe(IngredientAny.INSTANCE);
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:enderQuarry", 0));
        MineTweakerAPI.recipes.remove(iItemStack);
        MineTweakerAPI.furnace.remove(iItemStack6, null);
        MineTweakerAPI.recipes.remove(iItemStack2);
        MineTweakerAPI.recipes.remove(iItemStack4);
        MineTweakerAPI.recipes.remove(iItemStack3);
        MineTweakerAPI.recipes.remove(iItemStack5);
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:curtains", 0));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:timer", 0));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:decorativeBlock2", 7));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:decorativeBlock2", 5));
        MineTweakerAPI.recipes.remove(iItemStack7);
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:enderQuarryUpgrade", 1));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:enderQuarryUpgrade", 2));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:enderQuarryUpgrade", 3));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:enderQuarryUpgrade", 4));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:enderQuarryUpgrade", 5));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:enderQuarryUpgrade", 6));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:enderQuarryUpgrade", 7));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:enderQuarryUpgrade", 8));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:enderQuarryUpgrade", 9));
        MineTweakerAPI.recipes.remove(iItemStack45);
        MineTweakerAPI.recipes.remove(iItemStack46);
        MineTweakerAPI.recipes.remove(iItemStack47);
        MineTweakerAPI.recipes.remove(iItemStack48);
        MineTweakerAPI.recipes.remove(iItemStack49);
        MineTweakerAPI.recipes.remove(iItemStack50);
        MineTweakerAPI.recipes.remove(iItemStack51);
        MineTweakerAPI.recipes.remove(iItemStack52);
        MineTweakerAPI.recipes.remove(iItemStack53);
        MineTweakerAPI.recipes.remove(iItemStack10);
        MineTweakerAPI.recipes.remove(iItemStack15);
        MineTweakerAPI.recipes.remove(iItemStack16);
        MineTweakerAPI.recipes.remove(iItemStack18);
        Casting.removeTableRecipe(ItemBracketHandler.getItem("ExtraUtilities:bedrockiumIngot", 0), null, null);
        MineTweakerAPI.recipes.remove(iItemStack19);
        MineTweakerAPI.furnace.remove(iItemStack19, null);
        Casting.removeBasinRecipe(ItemBracketHandler.getItem("ExtraUtilities:block_bedrockium", 0), null, null);
        MineTweakerAPI.recipes.remove(iItemStack21);
        MineTweakerAPI.recipes.remove(iItemStack22);
        MineTweakerAPI.recipes.remove(iItemStack28);
        MineTweakerAPI.recipes.remove(iItemStack29);
        MineTweakerAPI.recipes.remove(iItemStack30);
        MineTweakerAPI.recipes.remove(iItemStack79);
        MineTweakerAPI.recipes.remove(iItemStack35);
        MineTweakerAPI.recipes.remove(iItemStack36);
        MineTweakerAPI.recipes.remove(iItemStack63);
        MineTweakerAPI.recipes.remove(iItemStack64);
        MineTweakerAPI.recipes.remove(iItemStack65);
        MineTweakerAPI.recipes.remove(iItemStack66);
        MineTweakerAPI.recipes.remove(iItemStack67);
        MineTweakerAPI.recipes.remove(iItemStack68);
        MineTweakerAPI.recipes.remove(iItemStack69);
        MineTweakerAPI.recipes.remove(iItemStack70);
        MineTweakerAPI.recipes.remove(iItemStack71);
        MineTweakerAPI.recipes.remove(iItemStack73);
        MineTweakerAPI.recipes.remove(iItemStack74);
        MineTweakerAPI.recipes.remove(iItemStack75);
        MineTweakerAPI.recipes.remove(iItemStack76);
        MineTweakerAPI.recipes.remove(iItemStack77);
        MineTweakerAPI.recipes.remove(iItemStack78);
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:cobblestone_compressed", 0));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:cobblestone_compressed", 1));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:cobblestone_compressed", 2));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:cobblestone_compressed", 3));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:cobblestone_compressed", 4));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:cobblestone_compressed", 5));
        MineTweakerAPI.recipes.remove(iItemStack8);
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:cobblestone_compressed", 7));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:cobblestone_compressed", 8));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:cobblestone_compressed", 9));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:cobblestone_compressed", 10));
        MineTweakerAPI.recipes.remove(iItemStack9);
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:cobblestone_compressed", 12));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:cobblestone_compressed", 13));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:cobblestone_compressed", 14));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:cobblestone_compressed", 15));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:trashcan", 0));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:trashcan", 1));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:trashcan", 2));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:decorativeBlock2", 0));
        MineTweakerAPI.furnace.remove(ItemBracketHandler.getItem("ExtraUtilities:decorativeBlock2", 0), null);
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:decorativeBlock1", 9));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:decorativeBlock2", 4));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:decorativeBlock2", 1));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:decorativeBlock2", 2));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:decorativeBlock2", 3));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:decorativeBlock2", 6));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:decorativeBlock2", 8));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:decorativeBlock2", 9));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:decorativeBlock2", 10));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:decorativeBlock2", 11));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:decorativeBlock1", 14));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:dark_portal", 2));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:dark_portal", 0));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:chestFull", 0));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:chestMini", 0));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:enderCollector", 0));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:endConstructor", 0));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:endConstructor", 2));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:budoff", 0));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:budoff", 3));
        MineTweakerAPI.recipes.remove(iItemStack80);
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:decorativeBlock1", 0));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:decorativeBlock1", 4));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:decorativeBlock1", 7));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:decorativeBlock1", 6));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:decorativeBlock1", 3));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:decorativeBlock1", 13));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:decorativeBlock1", 10));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:trading_post", 0));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:spike_base_wood", 0));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:spike_base", 0));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:spike_base_gold", 0));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:spike_base_diamond", 0));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:generator", 32767));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:generator.8", 32767));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:generator.64", 32767));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:heatingElement", 0));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:nodeUpgrade", 10));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:golden_lasso", 0));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:scanner", 0));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:builderswand", 0));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:creativebuilderswand", 0));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:shears", 0));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:ethericsword", 0));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:lawSword", 0));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:erosionShovel", 0));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:destructionpickaxe", 0));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:defoliageAxe", 0));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("ExtraUtilities:temporalHoe", 0));
        Casting.removeBasinRecipe(ItemBracketHandler.getItem("ExtraUtilities:decorativeBlock1", 5), null, null);
        QED.addShapedRecipe(ItemBracketHandler.getItem("AdvancedSolarPanel:BlockMolecularTransformer", 0), new IIngredient[][]{{ItemBracketHandler.getItem("IC2:blockMachine", 12), ItemBracketHandler.getItem("IC2:blockElectric", 5), ItemBracketHandler.getItem("IC2:blockMachine", 12)}, {OreBracketHandler.getOre("circuitAdvanced"), ItemBracketHandler.getItem("AdvancedSolarPanel:asp_crafting_items", 12), OreBracketHandler.getOre("circuitAdvanced")}, {ItemBracketHandler.getItem("IC2:blockMachine", 12), ItemBracketHandler.getItem("IC2:blockElectric", 5), ItemBracketHandler.getItem("IC2:blockMachine", 12)}});
        QED.addShapedRecipe(ItemBracketHandler.getItem("ExtraUtilities:enderQuarry", 0), new IIngredient[][]{{iOreDictEntry24, iItemStack41, iOreDictEntry24}, {iItemStack, iItemStack5, iItemStack}, {iItemStack3, iItemStack31, iItemStack3}});
        QED.addShapedRecipe(iItemStack, new IIngredient[][]{{iItemStack2, OreBracketHandler.getOre("circuitData"), iItemStack2}, {ItemBracketHandler.getItem("BuildCraft|Factory:tankBlock", 0), iItemStack3, ItemBracketHandler.getItem("BuildCraft|Factory:tankBlock", 0)}, {iItemStack2, ItemBracketHandler.getItem("gregtech:gt.blockmachines", 1143), iItemStack2}});
        MineTweakerAPI.recipes.addShaped(iItemStack5, new IIngredient[][]{{iItemStack3, OreBracketHandler.getOre("plateDiamond"), iItemStack3}, {OreBracketHandler.getOre("plateTitanium"), OreBracketHandler.getOre("circuitData"), OreBracketHandler.getOre("plateTitanium")}, {iItemStack3, OreBracketHandler.getOre("plateDiamond"), iItemStack3}}, null);
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("ExtraUtilities:curtains", 0), new IIngredient[][]{{ItemBracketHandler.getItem("minecraft:carpet", 15), ItemBracketHandler.getItem("minecraft:carpet", 15), null}, {ItemBracketHandler.getItem("minecraft:carpet", 15), ItemBracketHandler.getItem("minecraft:carpet", 15), null}, {ItemBracketHandler.getItem("minecraft:carpet", 15), ItemBracketHandler.getItem("minecraft:carpet", 15), null}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack13, new IIngredient[][]{{iOreDictEntry21, iOreDictEntry44, iOreDictEntry21}, {iOreDictEntry44, iItemStack14, iOreDictEntry44}, {iOreDictEntry21, iOreDictEntry6, iOreDictEntry21}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack7, new IIngredient[][]{{iItemStack2, OreBracketHandler.getOre("plateStainlessSteel"), iItemStack2}, {OreBracketHandler.getOre("plateStainlessSteel"), OreBracketHandler.getOre("gemEnderEye"), OreBracketHandler.getOre("plateStainlessSteel")}, {iItemStack2, OreBracketHandler.getOre("plateStainlessSteel"), iItemStack2}}, null);
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("ExtraUtilities:enderQuarryUpgrade", 1), new IIngredient[][]{{iItemStack7, ItemBracketHandler.getItem("ExtraUtilities:cobblestone_compressed", 4), iItemStack7}, {iItemStack9, iOreDictEntry17, iItemStack9}, {iItemStack7, ItemBracketHandler.getItem("ExtraUtilities:cobblestone_compressed", 4), iItemStack7}}, null);
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("ExtraUtilities:enderQuarryUpgrade", 2), new IIngredient[][]{{iItemStack7, iItemStack12, iItemStack7}, {OreBracketHandler.getOre("plateTitanium"), iOreDictEntry17, OreBracketHandler.getOre("plateTitanium")}, {iItemStack7, iItemStack12, iItemStack7}}, null);
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("ExtraUtilities:enderQuarryUpgrade", 3), new IIngredient[][]{{iItemStack7, OreBracketHandler.getOre("plateTitanium"), iItemStack7}, {OreBracketHandler.getOre("plateTitanium"), iOreDictEntry17, OreBracketHandler.getOre("plateTitanium")}, {iItemStack7, OreBracketHandler.getOre("plateTitanium"), iItemStack7}}, null);
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("ExtraUtilities:enderQuarryUpgrade", 4), new IIngredient[][]{{iItemStack7, OreBracketHandler.getOre("plateTungstenSteel"), iItemStack7}, {OreBracketHandler.getOre("plateTungstenSteel"), ItemBracketHandler.getItem("ExtraUtilities:enderQuarryUpgrade", 3), OreBracketHandler.getOre("plateTungstenSteel")}, {iItemStack7, OreBracketHandler.getOre("plateTungstenSteel"), iItemStack7}}, null);
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("ExtraUtilities:enderQuarryUpgrade", 5), new IIngredient[][]{{iItemStack7, OreBracketHandler.getOre("plateChrome"), iItemStack7}, {OreBracketHandler.getOre("plateChrome"), ItemBracketHandler.getItem("ExtraUtilities:enderQuarryUpgrade", 4), OreBracketHandler.getOre("plateChrome")}, {iItemStack7, OreBracketHandler.getOre("plateChrome"), iItemStack7}}, null);
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("ExtraUtilities:enderQuarryUpgrade", 6), new IIngredient[][]{{iItemStack42, OreBracketHandler.getOre("gearTitanium"), iItemStack42}, {iItemStack45, OreBracketHandler.getOre("gearDiamond"), iItemStack45}, {iItemStack42, OreBracketHandler.getOre("gearTitanium"), iItemStack42}}, null);
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("ExtraUtilities:enderQuarryUpgrade", 7), new IIngredient[][]{{iItemStack43, OreBracketHandler.getOre("gearTungstenSteel"), iItemStack43}, {OreBracketHandler.getOre("gearTungstenSteel"), ItemBracketHandler.getItem("ExtraUtilities:enderQuarryUpgrade", 6), OreBracketHandler.getOre("gearTungstenSteel")}, {iItemStack43, OreBracketHandler.getOre("gearTungstenSteel"), iItemStack43}}, null);
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("ExtraUtilities:enderQuarryUpgrade", 8), new IIngredient[][]{{iItemStack44, OreBracketHandler.getOre("gearChrome"), iItemStack44}, {OreBracketHandler.getOre("gearChrome"), ItemBracketHandler.getItem("ExtraUtilities:enderQuarryUpgrade", 7), OreBracketHandler.getOre("gearChrome")}, {iItemStack44, OreBracketHandler.getOre("gearChrome"), iItemStack44}}, null);
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("ExtraUtilities:enderQuarryUpgrade", 9), new IIngredient[][]{{iItemStack7, iItemStack, iItemStack7}, {OreBracketHandler.getOre("pipeLargeTungstenSteel"), iOreDictEntry3, OreBracketHandler.getOre("pipeLargeTungstenSteel")}, {iItemStack7, iItemStack, iItemStack7}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack45, new IIngredient[][]{{iOreDictEntry21, iOreDictEntry11, iOreDictEntry21}, {iOreDictEntry11, iOreDictEntry4, iOreDictEntry11}, {iOreDictEntry21, iOreDictEntry11, iOreDictEntry21}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack46, new IIngredient[][]{{iOreDictEntry21, iItemStack26, iOreDictEntry21}, {iItemStack26, iOreDictEntry13, iItemStack26}, {iOreDictEntry21, iItemStack26, iOreDictEntry21}}, null);
        MineTweakerAPI.recipes.addShapeless(iItemStack46, new IIngredient[]{iItemStack46}, null);
        MineTweakerAPI.recipes.addShapeless(iItemStack46, new IIngredient[]{iItemStack46.marked("ItemFilterUp"), OreBracketHandler.getOre("craftingRedstoneTorch")}, new ZenClass0());
        MineTweakerAPI.recipes.addShapeless(iItemStack46, new IIngredient[]{iItemStack46.marked("ItemFilterUp"), OreBracketHandler.getOre("blockWool")}, new ZenClass1());
        MineTweakerAPI.recipes.addShapeless(iItemStack46, new IIngredient[]{iItemStack46.marked("ItemFilterUp"), OreBracketHandler.getOre("stickWood")}, new ZenClass2());
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("ExtraUtilities:nodeUpgrade", 10), new IIngredient[][]{{iOreDictEntry47, iItemStack27, iOreDictEntry47}, {iItemStack27, iItemStack46, iItemStack27}, {iOreDictEntry47, iItemStack27, iOreDictEntry47}}, null);
        MineTweakerAPI.recipes.addShapeless(ItemBracketHandler.getItem("ExtraUtilities:nodeUpgrade", 10), new IIngredient[]{ItemBracketHandler.getItem("ExtraUtilities:nodeUpgrade", 10)}, null);
        MineTweakerAPI.recipes.addShapeless(ItemBracketHandler.getItem("ExtraUtilities:nodeUpgrade", 10), new IIngredient[]{ItemBracketHandler.getItem("ExtraUtilities:nodeUpgrade", 10).marked("AdvItemFilterUp"), OreBracketHandler.getOre("craftingRedstoneTorch")}, new ZenClass3());
        MineTweakerAPI.recipes.addShaped(iItemStack47, new IIngredient[][]{{iOreDictEntry47, iItemStack60, iOreDictEntry47}, {iItemStack61, iOreDictEntry17, iItemStack61}, {iOreDictEntry47, iItemStack60, iOreDictEntry47}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack49, new IIngredient[][]{{iOreDictEntry27, iItemStack47, iOreDictEntry27}, {OreBracketHandler.getOre("gearIridium"), ItemBracketHandler.getItem("WR-CBE|Logic:wirelessLogic", 0), OreBracketHandler.getOre("gearIridium")}, {iOreDictEntry27, iOreDictEntry28, iOreDictEntry27}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack50, new IIngredient[][]{{iOreDictEntry27, iItemStack47, iOreDictEntry27}, {OreBracketHandler.getOre("gearIridium"), ItemBracketHandler.getItem("WR-CBE|Core:recieverDish", 0), OreBracketHandler.getOre("gearIridium")}, {iOreDictEntry27, iOreDictEntry28, iOreDictEntry27}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack51, new IIngredient[][]{{iOreDictEntry21, iItemStack45, iOreDictEntry21}, {iOreDictEntry63, iOreDictEntry17, iItemStack45}, {iOreDictEntry21, iItemStack45, iOreDictEntry21}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack52, new IIngredient[][]{{iOreDictEntry21, iOreDictEntry63, iOreDictEntry21}, {iItemStack45, iOreDictEntry17, iItemStack45}, {iOreDictEntry21, null, iOreDictEntry21}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack52, new IIngredient[][]{{iOreDictEntry21, null, iOreDictEntry21}, {iItemStack45, iOreDictEntry17, iItemStack45}, {iOreDictEntry21, iOreDictEntry63, iOreDictEntry21}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack53, new IIngredient[][]{{iOreDictEntry21, iItemStack45, iOreDictEntry21}, {iItemStack45, iOreDictEntry17, iOreDictEntry63}, {iOreDictEntry21, iItemStack45, iOreDictEntry21}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack48, new IIngredient[][]{{iOreDictEntry21, iItemStack45, iOreDictEntry21}, {iOreDictEntry63, iOreDictEntry17, iItemStack25}, {iOreDictEntry21, iItemStack45, iOreDictEntry21}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack10, new IIngredient[][]{{null, iItemStack11, iItemStack11}, {null, OreBracketHandler.getOre("stickWood"), iItemStack11}, {OreBracketHandler.getOre("stickWood"), null, null}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack15, new IIngredient[][]{{iOreDictEntry15, OreBracketHandler.getOre("ringMeteoricSteel"), iOreDictEntry15}, {iOreDictEntry15, OreBracketHandler.getOre("pipeHugeSteel"), iOreDictEntry15}, {iOreDictEntry15, OreBracketHandler.getOre("ringMeteoricSteel"), iOreDictEntry15}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack16, new IIngredient[][]{{OreBracketHandler.getOre("plateBedrockium"), OreBracketHandler.getOre("ringTungstenSteel"), OreBracketHandler.getOre("plateBedrockium")}, {OreBracketHandler.getOre("plateBedrockium"), ItemBracketHandler.getItem("ExtraUtilities:drum", 0), OreBracketHandler.getOre("plateBedrockium")}, {OreBracketHandler.getOre("plateBedrockium"), OreBracketHandler.getOre("ringTungstenSteel"), OreBracketHandler.getOre("plateBedrockium")}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack22, new IIngredient[][]{{iOreDictEntry62, ItemBracketHandler.getItem("minecraft:rail", 0), iOreDictEntry63}, {ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32630), OreBracketHandler.getOre("frameGtSteel"), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32630)}, {OreBracketHandler.getOre("gearGtSmallSteel"), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32600), OreBracketHandler.getOre("gearGtSmallSteel")}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack28, new IIngredient[][]{{iOreDictEntry15, OreBracketHandler.getOre("chestWood"), iOreDictEntry15}, {iOreDictEntry20, iItemStack62, iOreDictEntry20}, {iOreDictEntry15, OreBracketHandler.getOre("chestWood"), iOreDictEntry15}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack29, new IIngredient[][]{{iItemStack4, iItemStack28, iItemStack4}, {iOreDictEntry20, iItemStack28, iOreDictEntry20}, {iItemStack4, iItemStack28, iItemStack4}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack30, new IIngredient[][]{{iOreDictEntry62, iOreDictEntry12, iOreDictEntry64}, {iOreDictEntry9, iOreDictEntry9, iOreDictEntry14}, {iOreDictEntry9, iOreDictEntry9, iOreDictEntry20}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack30, new IIngredient[][]{{iOreDictEntry64, iOreDictEntry12, iOreDictEntry62}, {iOreDictEntry9, iOreDictEntry9, iOreDictEntry14}, {iOreDictEntry9, iOreDictEntry9, iOreDictEntry20}}, null);
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("ExtraUtilities:watering_can", 3), new IIngredient[][]{{iOreDictEntry62, OreBracketHandler.getOre("ringNeutronium"), iOreDictEntry64}, {OreBracketHandler.getOre("plateBedrockium"), OreBracketHandler.getOre("plateBedrockium"), OreBracketHandler.getOre("plateBedrockium")}, {OreBracketHandler.getOre("plateBedrockium"), OreBracketHandler.getOre("plateBedrockium"), OreBracketHandler.getOre("screwNeutronium")}}, null);
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("ExtraUtilities:watering_can", 3), new IIngredient[][]{{iOreDictEntry64, OreBracketHandler.getOre("ringNeutronium"), iOreDictEntry62}, {OreBracketHandler.getOre("plateBedrockium"), OreBracketHandler.getOre("plateBedrockium"), OreBracketHandler.getOre("plateBedrockium")}, {OreBracketHandler.getOre("plateBedrockium"), OreBracketHandler.getOre("plateBedrockium"), OreBracketHandler.getOre("screwNeutronium")}}, null);
        QED.addShapedRecipe(iItemStack79, new IIngredient[][]{{ItemBracketHandler.getItem("minecraft:potion", 8225), iItemStack81, ItemBracketHandler.getItem("minecraft:potion", 8229)}, {iItemStack80, ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 23306), iItemStack80}, {iItemStack80, ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 23306), iItemStack80}});
        MineTweakerAPI.recipes.addShaped(iItemStack35, new IIngredient[][]{{iOreDictEntry5, iOreDictEntry5, iOreDictEntry5}, {iOreDictEntry5, iItemStack37, iOreDictEntry5}, {iOreDictEntry5, iItemStack38, iOreDictEntry5}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack36, new IIngredient[][]{{iOreDictEntry5, iItemStack35, iOreDictEntry5}, {iItemStack35, iItemStack39, iItemStack35}, {iItemStack35, iItemStack38, iItemStack35}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack63, new IIngredient[][]{{iOreDictEntry19, iOreDictEntry15, iOreDictEntry19}, {iOreDictEntry63, iOreDictEntry6, iOreDictEntry62}, {iOreDictEntry19, iOreDictEntry15, iOreDictEntry19}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack64, new IIngredient[][]{{iOreDictEntry19, iOreDictEntry33, iOreDictEntry19}, {iOreDictEntry63, iItemStack63, iOreDictEntry62}, {iOreDictEntry19, iOreDictEntry33, iOreDictEntry19}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack65, new IIngredient[][]{{iOreDictEntry19, iOreDictEntry34, iOreDictEntry19}, {iOreDictEntry63, iItemStack63, iOreDictEntry62}, {iOreDictEntry19, iOreDictEntry34, iOreDictEntry19}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack66, new IIngredient[][]{{iOreDictEntry19, iOreDictEntry35, iOreDictEntry19}, {iOreDictEntry63, iItemStack64, iOreDictEntry62}, {iOreDictEntry19, iOreDictEntry35, iOreDictEntry19}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack67, new IIngredient[][]{{iOreDictEntry19, iOreDictEntry36, iOreDictEntry19}, {iOreDictEntry63, iItemStack66, iOreDictEntry62}, {iOreDictEntry19, iOreDictEntry36, iOreDictEntry19}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack68, new IIngredient[][]{{iOreDictEntry22, iOreDictEntry21, iOreDictEntry22}, {iOreDictEntry63, iItemStack63, iOreDictEntry62}, {iOreDictEntry22, iOreDictEntry21, iOreDictEntry22}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack69, new IIngredient[][]{{iOreDictEntry62, iItemStack63, iOreDictEntry20}, {iItemStack63, iItemStack63, iItemStack63}, {iOreDictEntry20, iItemStack63, iOreDictEntry64}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack69, new IIngredient[][]{{iOreDictEntry64, iItemStack63, iOreDictEntry20}, {iItemStack63, iItemStack63, iItemStack63}, {iOreDictEntry20, iItemStack63, iOreDictEntry62}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack70, new IIngredient[][]{{iOreDictEntry19, iOreDictEntry33, iOreDictEntry19}, {iOreDictEntry63, iItemStack64, iOreDictEntry62}, {iOreDictEntry19, iOreDictEntry33, iOreDictEntry19}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack71, new IIngredient[][]{{iOreDictEntry25, iOreDictEntry23, iOreDictEntry25}, {iOreDictEntry63, iItemStack68, iOreDictEntry62}, {iOreDictEntry25, iOreDictEntry23, iOreDictEntry25}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack73, new IIngredient[][]{{iOreDictEntry63, iItemStack72, iOreDictEntry62}, {iOreDictEntry26, iItemStack40, iOreDictEntry26}, {iItemStack75, iItemStack75, iItemStack75}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack73, new IIngredient[][]{{iOreDictEntry62, iItemStack72, iOreDictEntry63}, {iOreDictEntry26, iItemStack40, iOreDictEntry26}, {iItemStack75, iItemStack75, iItemStack75}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack74, new IIngredient[][]{{iOreDictEntry63, iItemStack72, iOreDictEntry62}, {iOreDictEntry26, iItemStack40, iOreDictEntry26}, {iItemStack76, iItemStack76, iItemStack76}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack74, new IIngredient[][]{{iOreDictEntry62, iItemStack72, iOreDictEntry63}, {iOreDictEntry26, iItemStack40, iOreDictEntry26}, {iItemStack76, iItemStack76, iItemStack76}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack75, new IIngredient[][]{{iOreDictEntry62, iItemStack72, iOreDictEntry63}, {iOreDictEntry26, iItemStack55, iOreDictEntry26}, {iItemStack85, iOreDictEntry39, iItemStack85}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack75, new IIngredient[][]{{iOreDictEntry63, iItemStack72, iOreDictEntry62}, {iOreDictEntry26, iItemStack55, iOreDictEntry26}, {iItemStack85, iOreDictEntry39, iItemStack85}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack76, new IIngredient[][]{{iOreDictEntry62, iItemStack72, iOreDictEntry63}, {iOreDictEntry26, iItemStack59, iOreDictEntry26}, {iItemStack84, iItemStack56, iItemStack84}}, null);
        MineTweakerAPI.recipes.addShaped(iItemStack76, new IIngredient[][]{{iOreDictEntry63, iItemStack72, iOreDictEntry62}, {iOreDictEntry26, iItemStack59, iOreDictEntry26}, {iItemStack84, iItemStack56, iItemStack84}}, null);
        QED.addShapedRecipe(iItemStack77, new IIngredient[][]{{iItemStack75, iItemStack86, iItemStack75}, {ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 17533), ItemBracketHandler.getItem("ExtraUtilities:nodeUpgrade", 8), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 17533)}, {iItemStack75, iItemStack86, iItemStack75}});
        QED.addShapedRecipe(iItemStack78, new IIngredient[][]{{iItemStack77, ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 17533), iItemStack77}, {ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 17533), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 11395), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 17533)}, {iItemStack77, iItemStack77, iItemStack77}});
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("ExtraUtilities:trashcan", 0), new IIngredient[][]{{OreBracketHandler.getOre("plateIron"), OreBracketHandler.getOre("craftingToolHardHammer"), OreBracketHandler.getOre("plateIron")}, {OreBracketHandler.getOre("plateIron"), OreBracketHandler.getOre("gemEnderPearl"), OreBracketHandler.getOre("plateIron")}, {OreBracketHandler.getOre("plateIron"), OreBracketHandler.getOre("plateIron"), OreBracketHandler.getOre("plateIron")}}, null);
        MineTweakerAPI.recipes.addShapeless(ItemBracketHandler.getItem("ExtraUtilities:decorativeBlock2", 0), new IIngredient[]{ItemBracketHandler.getItem("TConstruct:GlassBlock", 0)}, null);
        MineTweakerAPI.recipes.addShapeless(ItemBracketHandler.getItem("ExtraUtilities:unstableingot", 0), new IIngredient[]{ItemBracketHandler.getItem("ExtraUtilities:unstableingot", 2)}, null);
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("ExtraUtilities:chestFull", 0), new IIngredient[][]{{OreBracketHandler.getOre("craftingToolHardHammer"), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 17809), OreBracketHandler.getOre("craftingToolSaw")}, {ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 17809), OreBracketHandler.getOre("chestWood"), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 17809)}, {null, ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 17809), null}}, null);
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("ExtraUtilities:chestMini", 0), new IIngredient[][]{{OreBracketHandler.getOre("craftingToolHardHammer"), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 17809), OreBracketHandler.getOre("craftingToolSaw")}, {ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 17809), OreBracketHandler.getOre("itemFlint"), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 17809)}, {null, ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 17809), null}}, null);
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("ExtraUtilities:enderCollector", 0), new IIngredient[][]{{OreBracketHandler.getOre("lensEnderPearl"), OreBracketHandler.getOre("blockEnderObsidian"), OreBracketHandler.getOre("lensEnderPearl")}, {OreBracketHandler.getOre("craftingToolHardHammer"), OreBracketHandler.getOre("blockEnderObsidian"), OreBracketHandler.getOre("craftingToolWrench")}, {OreBracketHandler.getOre("stoneObsidian"), OreBracketHandler.getOre("stoneObsidian"), OreBracketHandler.getOre("stoneObsidian")}}, null);
        MineTweakerAPI.recipes.addShapeless(ItemBracketHandler.getItem("ExtraUtilities:enderCollector", 0), new IIngredient[]{ItemBracketHandler.getItem("RandomThings:advancedItemCollector", 0)}, null);
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("ExtraUtilities:endConstructor", 0), new IIngredient[][]{{OreBracketHandler.getOre("plateEnderEye"), ItemBracketHandler.getItem("HardcoreEnderExpansion:altar_nexus", 0), OreBracketHandler.getOre("plateEnderEye")}, {OreBracketHandler.getOre("blockEnderObsidian"), ItemBracketHandler.getItem("Thaumcraft:blockStoneDevice", 2), OreBracketHandler.getOre("blockEnderObsidian")}, {OreBracketHandler.getOre("plateTitanium"), ItemBracketHandler.getItem("ExtraUtilities:decorativeBlock1", 12), OreBracketHandler.getOre("plateTitanium")}}, null);
        QED.addShapedRecipe(ItemBracketHandler.getItem("ExtraUtilities:endMarker", 0), new IIngredient[][]{{null, ItemBracketHandler.getItem("minecraft:ender_eye", 0), null}, {null, ItemBracketHandler.getItem("ExtraUtilities:decorativeBlock1", 1), null}, {null, ItemBracketHandler.getItem("ExtraUtilities:decorativeBlock1", 1), null}});
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("ExtraUtilities:spike_base_wood", 0).amount(2), new IIngredient[][]{{iOreDictEntry65, ItemBracketHandler.getItem("minecraft:wooden_sword", 0), iOreDictEntry64}, {iOreDictEntry52, iOreDictEntry8, iOreDictEntry52}, {iOreDictEntry8, iOreDictEntry50, iOreDictEntry8}}, null);
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("ExtraUtilities:spike_base", 0).amount(2), new IIngredient[][]{{iOreDictEntry65, ItemBracketHandler.getItem("minecraft:iron_sword", 0), iOreDictEntry64}, {iOreDictEntry55, iOreDictEntry9, iOreDictEntry55}, {iOreDictEntry9, iOreDictEntry53, iOreDictEntry9}}, null);
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("ExtraUtilities:spike_base_gold", 0).amount(2), new IIngredient[][]{{iOreDictEntry65, ItemBracketHandler.getItem("minecraft:golden_sword", 0), iOreDictEntry64}, {iOreDictEntry58, iOreDictEntry10, iOreDictEntry58}, {iOreDictEntry10, iOreDictEntry56, iOreDictEntry10}}, null);
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("ExtraUtilities:spike_base_diamond", 0).amount(2), new IIngredient[][]{{iOreDictEntry65, ItemBracketHandler.getItem("minecraft:diamond_sword", 0), iOreDictEntry64}, {iOreDictEntry61, iOreDictEntry11, iOreDictEntry61}, {iOreDictEntry11, iOreDictEntry59, iOreDictEntry11}}, null);
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("ExtraUtilities:builderswand", 0), new IIngredient[][]{{null, null, OreBracketHandler.getOre("ingotUnstable")}, {null, OreBracketHandler.getOre("ingotUnstable"), null}, {ItemBracketHandler.getItem("RandomThings:ingredient", 1), null, null}}, null);
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("ExtraUtilities:creativebuilderswand", 0), new IIngredient[][]{{null, OreBracketHandler.getOre("ingotUnstable"), OreBracketHandler.getOre("ingotUnstable")}, {null, OreBracketHandler.getOre("ingotUnstable"), OreBracketHandler.getOre("ingotUnstable")}, {ItemBracketHandler.getItem("RandomThings:ingredient", 1), null, null}}, null);
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("ExtraUtilities:shears", 0), new IIngredient[][]{{OreBracketHandler.getOre("ingotUnstable"), null, OreBracketHandler.getOre("ingotUnstable")}, {iItemStack21, iItemStack87, iItemStack21}}, null);
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("ExtraUtilities:ethericsword", 0), new IIngredient[][]{{null, OreBracketHandler.getOre("ingotUnstable"), null}, {null, OreBracketHandler.getOre("ingotUnstable"), null}, {null, ItemBracketHandler.getItem("RandomThings:ingredient", 1), null}}, null);
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("ExtraUtilities:lawSword", 0), new IIngredient[][]{{null, ItemBracketHandler.getItem("TConstruct:largeSwordBlade", 314), null}, {null, OreBracketHandler.getOre("ingotUnstable"), null}, {null, ItemBracketHandler.getItem("RandomThings:ingredient", 1), null}}, null);
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("ExtraUtilities:erosionShovel", 0), new IIngredient[][]{{null, OreBracketHandler.getOre("ingotUnstable"), null}, {null, ItemBracketHandler.getItem("RandomThings:ingredient", 1), null}, {null, ItemBracketHandler.getItem("RandomThings:ingredient", 1), null}}, null);
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("ExtraUtilities:destructionpickaxe", 0), new IIngredient[][]{{OreBracketHandler.getOre("ingotUnstable"), OreBracketHandler.getOre("ingotUnstable"), OreBracketHandler.getOre("ingotUnstable")}, {null, ItemBracketHandler.getItem("RandomThings:ingredient", 1), null}, {null, ItemBracketHandler.getItem("RandomThings:ingredient", 1), null}}, null);
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("ExtraUtilities:defoliageAxe", 0), new IIngredient[][]{{OreBracketHandler.getOre("ingotUnstable"), OreBracketHandler.getOre("ingotUnstable"), null}, {OreBracketHandler.getOre("ingotUnstable"), ItemBracketHandler.getItem("RandomThings:ingredient", 1), null}, {null, ItemBracketHandler.getItem("RandomThings:ingredient", 1), null}}, null);
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("ExtraUtilities:temporalHoe", 0), new IIngredient[][]{{OreBracketHandler.getOre("ingotUnstable"), OreBracketHandler.getOre("ingotUnstable"), null}, {null, ItemBracketHandler.getItem("RandomThings:ingredient", 1), null}, {null, ItemBracketHandler.getItem("RandomThings:ingredient", 1), null}}, null);
        AlloySmelter.addRecipe(iItemStack6, ItemBracketHandler.getItem("minecraft:quartz_block", 0), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 2816), 80, 64);
        AlloySmelter.addRecipe(ItemBracketHandler.getItem("ExtraUtilities:decorativeBlock2", 5), ItemBracketHandler.getItem("ExtraUtilities:decorativeBlock2", 0), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 2804).amount(4), 200, 8);
        AlloySmelter.addRecipe(ItemBracketHandler.getItem("ExtraUtilities:decorativeBlock2", 4), ItemBracketHandler.getItem("ExtraUtilities:decorativeBlock2", 0), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 2086), 200, 8);
        AlloySmelter.addRecipe(ItemBracketHandler.getItem("ExtraUtilities:decorativeBlock2", 3), ItemBracketHandler.getItem("ExtraUtilities:decorativeBlock2", 0), ItemBracketHandler.getItem("minecraft:gunpowder", 0), 200, 8);
        AlloySmelter.addRecipe(ItemBracketHandler.getItem("ExtraUtilities:decorativeBlock2", 7), ItemBracketHandler.getItem("ExtraUtilities:decorativeBlock2", 0), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 17811).amount(4), 400, 16);
        AlloySmelter.addRecipe(ItemBracketHandler.getItem("ExtraUtilities:decorativeBlock2", 8), ItemBracketHandler.getItem("ExtraUtilities:decorativeBlock2", 0), ItemBracketHandler.getItem("minecraft:dye", 9), 200, 8);
        Assembler.addRecipe(iItemStack18, ItemBracketHandler.getItem("ExtraUtilities:cobblestone_compressed", 3).amount(4), ItemBracketHandler.getItem("minecraft:diamond_block", 0), 600, 256);
        Assembler.addRecipe(ItemBracketHandler.getItem("ExtraUtilities:decorativeBlock2", 1), ItemBracketHandler.getItem("ExtraUtilities:decorativeBlock2", 0), ItemBracketHandler.getItem("gregtech:gt.integrated_circuit", 1).amount(0), 100, 8);
        Assembler.addRecipe(ItemBracketHandler.getItem("ExtraUtilities:decorativeBlock2", 2), ItemBracketHandler.getItem("ExtraUtilities:decorativeBlock2", 0), ItemBracketHandler.getItem("gregtech:gt.integrated_circuit", 4).amount(0), 100, 8);
        Assembler.addRecipe(ItemBracketHandler.getItem("ExtraUtilities:decorativeBlock2", 6), ItemBracketHandler.getItem("ExtraUtilities:decorativeBlock2", 0), ItemBracketHandler.getItem("gregtech:gt.integrated_circuit", 5).amount(0), 100, 8);
        Assembler.addRecipe(ItemBracketHandler.getItem("ExtraUtilities:decorativeBlock2", 9), ItemBracketHandler.getItem("ExtraUtilities:decorativeBlock2", 0), ItemBracketHandler.getItem("gregtech:gt.integrated_circuit", 2).amount(0), 100, 8);
        Assembler.addRecipe(ItemBracketHandler.getItem("ExtraUtilities:decorativeBlock2", 10), ItemBracketHandler.getItem("ExtraUtilities:decorativeBlock2", 0), ItemBracketHandler.getItem("ExtraUtilities:curtains", 0), 200, 16);
        Assembler.addRecipe(ItemBracketHandler.getItem("ExtraUtilities:decorativeBlock2", 11), ItemBracketHandler.getItem("ExtraUtilities:decorativeBlock2", 10), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 2804).amount(4), 400, 30);
        Assembler.addRecipe(ItemBracketHandler.getItem("ExtraUtilities:chestFull", 0), ItemBracketHandler.getItem("minecraft:chest", 0), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 17809).amount(2), 100, 30);
        Assembler.addRecipe(ItemBracketHandler.getItem("ExtraUtilities:chestMini", 0), ItemBracketHandler.getItem("minecraft:flint", 0), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 17809).amount(2), 50, 30);
        Assembler.addRecipe(iItemStack2, iItemStack6.amount(4), ItemBracketHandler.getItem("IC2:itemDensePlates", 7).amount(4), LiquidBracketHandler.getLiquid("ender").withAmount(500), 600, 120);
        Assembler.addRecipe(ItemBracketHandler.getItem("ExtraUtilities:endConstructor", 2), ItemBracketHandler.getItem("ExtraUtilities:decorativeBlock1", 1).amount(4), ItemBracketHandler.getItem("minecraft:ender_eye", 0).amount(3), LiquidBracketHandler.getLiquid("ender").withAmount(1000), 400, 120);
        Assembler.addRecipe(ItemBracketHandler.getItem("ExtraUtilities:budoff", 0), ItemBracketHandler.getItem("Railcraft:detector", 2), ItemBracketHandler.getItem("minecraft:sticky_piston", 0), 200, 30);
        Assembler.addRecipe(ItemBracketHandler.getItem("ExtraUtilities:budoff", 3), ItemBracketHandler.getItem("ExtraUtilities:budoff", 0), ItemBracketHandler.getItem("minecraft:redstone_block", 0).amount(4), 200, 120);
        Assembler.addRecipe(iItemStack80, ItemBracketHandler.getItem("minecraft:torch", 0).amount(5), ItemBracketHandler.getItem("gregtech:gt.metaitem.02", 28500), LiquidBracketHandler.getLiquid("molten.tin").withAmount(1440), 600, 30);
        Assembler.addRecipe(ItemBracketHandler.getItem("ExtraUtilities:decorativeBlock1", 0).amount(9), ItemBracketHandler.getItem("minecraft:stone", 0).amount(4), ItemBracketHandler.getItem("minecraft:stonebrick", 0).amount(5), 180, 4);
        Assembler.addRecipe(ItemBracketHandler.getItem("ExtraUtilities:decorativeBlock1", 4), ItemBracketHandler.getItem("ExtraUtilities:decorativeBlock1", 0), ItemBracketHandler.getItem("gregtech:gt.integrated_circuit", 4).amount(0), 20, 4);
        Assembler.addRecipe(ItemBracketHandler.getItem("ExtraUtilities:decorativeBlock1", 7), ItemBracketHandler.getItem("ExtraUtilities:decorativeBlock1", 4), ItemBracketHandler.getItem("gregtech:gt.integrated_circuit", 4).amount(0), 20, 4);
        Assembler.addRecipe(ItemBracketHandler.getItem("ExtraUtilities:decorativeBlock1", 6), ItemBracketHandler.getItem("minecraft:gravel", 0), ItemBracketHandler.getItem("gregtech:gt.integrated_circuit", 2).amount(0), 20, 4);
        Assembler.addRecipe(ItemBracketHandler.getItem("ExtraUtilities:decorativeBlock1", 3).amount(4), ItemBracketHandler.getItem("minecraft:stone", 0), ItemBracketHandler.getItem("minecraft:ice", 0).amount(4), 80, 4);
        Assembler.addRecipe(ItemBracketHandler.getItem("ExtraUtilities:decorativeBlock1", 9).amount(2), ItemBracketHandler.getItem("minecraft:sand", 0), ItemBracketHandler.getItem("minecraft:glass", 0), 40, 4);
        Assembler.addRecipe(ItemBracketHandler.getItem("ExtraUtilities:decorativeBlock1", 13).amount(2), ItemBracketHandler.getItem("minecraft:sandstone", 0), ItemBracketHandler.getItem("minecraft:end_stone", 0), 40, 4);
        Assembler.addRecipe(ItemBracketHandler.getItem("ExtraUtilities:decorativeBlock1", 10).amount(5), ItemBracketHandler.getItem("ExtraUtilities:decorativeBlock1", 6).amount(5), ItemBracketHandler.getItem("minecraft:stone_slab", 5).amount(5), 100, 4);
        Assembler.addRecipe(iItemStack3, ItemBracketHandler.getItem("ExtraUtilities:decorativeBlock1", 1).amount(4), iItemStack4.amount(4), LiquidBracketHandler.getLiquid("ender").withAmount(1000), 1200, 120);
        Assembler.addRecipe(ItemBracketHandler.getItem("ExtraUtilities:trading_post", 0), ItemBracketHandler.getItem("Railcraft:machine.alpha", 6), ItemBracketHandler.getItem("gregtech:gt.metaitem.02", 32470).amount(4), 300, 30);
        Assembler.addRecipe(iItemStack63, ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 17305).amount(2), ItemBracketHandler.getItem("gregtech:gt.integrated_circuit", 2).amount(0), LiquidBracketHandler.getLiquid("molten.redalloy").withAmount(36), 100, 64);
        Assembler.addRecipe(iItemStack64, iItemStack63, ItemBracketHandler.getItem("IC2:itemPartCircuit", 0), 200, 64);
        Assembler.addRecipe(iItemStack68, iItemStack63, ItemBracketHandler.getItem("gregtech:gt.integrated_circuit", 1).amount(0), LiquidBracketHandler.getLiquid("molten.redalloy").withAmount(216), 200, 64);
        Assembler.addRecipe(iItemStack69, iItemStack63.amount(4), ItemBracketHandler.getItem("gregtech:gt.integrated_circuit", 4).amount(0), 200, 64);
        Assembler.addRecipe(iItemStack70, iItemStack64, ItemBracketHandler.getItem("IC2:itemPartCircuit", 0), 300, 64);
        Assembler.addRecipe(iItemStack65, iItemStack63, ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32702), 200, 64);
        Assembler.addRecipe(iItemStack65, iItemStack63, ItemBracketHandler.getItem("gregtech:gt.metaitem.03", 32079), 200, 64);
        Assembler.addRecipe(iItemStack65, iItemStack63, ItemBracketHandler.getItem("gregtech:gt.metaitem.03", 32080), 200, 64);
        Assembler.addRecipe(iItemStack66, iItemStack64, ItemBracketHandler.getItem("IC2:itemPartCircuitAdv", 0), 300, 64);
        Assembler.addRecipe(iItemStack71, ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 17303).amount(2), iItemStack68, 300, 64);
        Assembler.addRecipe(iItemStack67, iItemStack66, ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32708), 400, 64);
        Assembler.addRecipe(iItemStack67, iItemStack66, ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32704), 200, 64);
        Assembler.addRecipe(ItemBracketHandler.getItem("ExtraUtilities:trashcan", 0), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 17032).amount(4), ItemBracketHandler.getItem("minecraft:ender_pearl", 0), 200, 30);
        Assembler.addRecipe(ItemBracketHandler.getItem("ExtraUtilities:trashcan", 1), ItemBracketHandler.getItem("ExtraUtilities:trashcan", 0), ItemBracketHandler.getItem("BuildCraft|Factory:tankBlock", 0), 200, 30);
        Assembler.addRecipe(ItemBracketHandler.getItem("ExtraUtilities:trashcan", 2), ItemBracketHandler.getItem("ExtraUtilities:trashcan", 0), ItemBracketHandler.getItem("BuildCraft|Transport:item.buildcraftPipe.pipepowergold", 0), 200, 30);
        Assembler.addRecipe(ItemBracketHandler.getItem("ExtraUtilities:heatingElement", 0), ItemBracketHandler.getItem("IC2:itemRecipePart", 0).amount(2), ItemBracketHandler.getItem("gregtech:gt.metaitem.02", 19032).amount(4), LiquidBracketHandler.getLiquid("molten.tin").withAmount(144), 400, 30);
        Assembler.addRecipe(ItemBracketHandler.getItem("ExtraUtilities:heatingElement", 0), ItemBracketHandler.getItem("IC2:itemRecipePart", 0).amount(2), ItemBracketHandler.getItem("gregtech:gt.metaitem.02", 19032).amount(4), LiquidBracketHandler.getLiquid("molten.lead").withAmount(288), 400, 30);
        Assembler.addRecipe(ItemBracketHandler.getItem("ExtraUtilities:heatingElement", 0), ItemBracketHandler.getItem("IC2:itemRecipePart", 0).amount(2), ItemBracketHandler.getItem("gregtech:gt.metaitem.02", 19032).amount(4), LiquidBracketHandler.getLiquid("molten.solderingalloy").withAmount(72), 400, 30);
        Assembler.addRecipe(ItemBracketHandler.getItem("ExtraUtilities:golden_lasso", 0), ItemBracketHandler.getItem("minecraft:ender_pearl", 0), ItemBracketHandler.getItem("gregtech:gt.metaitem.02", 19086).amount(4), 200, 30);
        Assembler.addRecipe(ItemBracketHandler.getItem("ExtraUtilities:scanner", 0), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32762), ItemBracketHandler.getItem("minecraft:ender_eye", 0), 600, 120);
        Assembler.addRecipe(ItemBracketHandler.getItem("ExtraUtilities:cobblestone_compressed", 0), ItemBracketHandler.getItem("gregtech:gt.integrated_circuit", 1).amount(0), ItemBracketHandler.getItem("minecraft:cobblestone", 0).amount(9), 100, 16);
        Assembler.addRecipe(ItemBracketHandler.getItem("ExtraUtilities:cobblestone_compressed", 8), ItemBracketHandler.getItem("minecraft:dirt", 0).amount(9), ItemBracketHandler.getItem("gregtech:gt.integrated_circuit", 1).amount(0), 100, 16);
        Assembler.addRecipe(ItemBracketHandler.getItem("ExtraUtilities:cobblestone_compressed", 12), ItemBracketHandler.getItem("minecraft:gravel", 0).amount(9), ItemBracketHandler.getItem("gregtech:gt.integrated_circuit", 1).amount(0), 100, 16);
        Assembler.addRecipe(ItemBracketHandler.getItem("ExtraUtilities:cobblestone_compressed", 14), ItemBracketHandler.getItem("minecraft:sand", 0).amount(9), ItemBracketHandler.getItem("gregtech:gt.integrated_circuit", 1).amount(0), 100, 16);
        Compressor.addRecipe(ItemBracketHandler.getItem("ExtraUtilities:decorativeBlock1", 5), ItemBracketHandler.getItem("ExtraUtilities:unstableingot", 2).amount(9));
        Compressor.addRecipe(ItemBracketHandler.getItem("ExtraUtilities:decorativeBlock1", 5), ItemBracketHandler.getItem("ExtraUtilities:unstableingot", 0).amount(9));
        Extractor.addRecipe(ItemBracketHandler.getItem("minecraft:cobblestone", 0).amount(9), ItemBracketHandler.getItem("ExtraUtilities:cobblestone_compressed", 0));
        Extractor.addRecipe(ItemBracketHandler.getItem("ExtraUtilities:cobblestone_compressed", 0).amount(9), ItemBracketHandler.getItem("ExtraUtilities:cobblestone_compressed", 1));
        Extractor.addRecipe(ItemBracketHandler.getItem("ExtraUtilities:cobblestone_compressed", 1).amount(9), ItemBracketHandler.getItem("ExtraUtilities:cobblestone_compressed", 2));
        Extractor.addRecipe(ItemBracketHandler.getItem("ExtraUtilities:cobblestone_compressed", 2).amount(9), ItemBracketHandler.getItem("ExtraUtilities:cobblestone_compressed", 3));
        Extractor.addRecipe(ItemBracketHandler.getItem("ExtraUtilities:cobblestone_compressed", 3).amount(9), ItemBracketHandler.getItem("ExtraUtilities:cobblestone_compressed", 4));
        Extractor.addRecipe(ItemBracketHandler.getItem("ExtraUtilities:cobblestone_compressed", 4).amount(9), ItemBracketHandler.getItem("ExtraUtilities:cobblestone_compressed", 5));
        Extractor.addRecipe(ItemBracketHandler.getItem("ExtraUtilities:cobblestone_compressed", 5).amount(9), ItemBracketHandler.getItem("ExtraUtilities:cobblestone_compressed", 6));
        Extractor.addRecipe(ItemBracketHandler.getItem("ExtraUtilities:cobblestone_compressed", 6).amount(9), ItemBracketHandler.getItem("ExtraUtilities:cobblestone_compressed", 7));
        Extractor.addRecipe(ItemBracketHandler.getItem("minecraft:dirt", 0).amount(9), ItemBracketHandler.getItem("ExtraUtilities:cobblestone_compressed", 8));
        Extractor.addRecipe(ItemBracketHandler.getItem("ExtraUtilities:cobblestone_compressed", 8).amount(9), ItemBracketHandler.getItem("ExtraUtilities:cobblestone_compressed", 9));
        Extractor.addRecipe(ItemBracketHandler.getItem("ExtraUtilities:cobblestone_compressed", 9).amount(9), ItemBracketHandler.getItem("ExtraUtilities:cobblestone_compressed", 10));
        Extractor.addRecipe(ItemBracketHandler.getItem("ExtraUtilities:cobblestone_compressed", 10).amount(9), iItemStack9);
        Extractor.addRecipe(ItemBracketHandler.getItem("minecraft:gravel", 0).amount(9), ItemBracketHandler.getItem("ExtraUtilities:cobblestone_compressed", 12));
        Extractor.addRecipe(ItemBracketHandler.getItem("ExtraUtilities:cobblestone_compressed", 12).amount(9), ItemBracketHandler.getItem("ExtraUtilities:cobblestone_compressed", 13));
        Extractor.addRecipe(ItemBracketHandler.getItem("minecraft:sand", 0).amount(9), ItemBracketHandler.getItem("ExtraUtilities:cobblestone_compressed", 14));
        Extractor.addRecipe(ItemBracketHandler.getItem("ExtraUtilities:cobblestone_compressed", 14).amount(9), ItemBracketHandler.getItem("ExtraUtilities:cobblestone_compressed", 15));
    }
}

