package com.github.GTNH2Mega.fromScripts;
import minetweaker.MineTweakerAPI;
import minetweaker.api.item.IIngredient;
import minetweaker.api.item.IItemStack;
import minetweaker.mc1710.brackets.ItemBracketHandler;
import minetweaker.mc1710.brackets.OreBracketHandler;
import modtweaker2.mods.thaumcraft.handlers.Arcane;
import modtweaker2.mods.thaumcraft.handlers.Crucible;
import modtweaker2.mods.thaumcraft.handlers.Infusion;
import modtweaker2.mods.thaumcraft.handlers.Research;
import modtweaker2.mods.thaumcraft.handlers.Warp;
import static com.github.GTNH2Mega.VoltageLevels.*;
public class ForbiddenMagic01Wands
implements Runnable {
    public void run() {
        IItemStack iItemStack = ItemBracketHandler.getItem((String)"thaumicbases:resource", (int)2);
        IItemStack iItemStack2 = ItemBracketHandler.getItem((String)"ForbiddenMagic:WandCaps", (int)3);
        IItemStack iItemStack3 = ItemBracketHandler.getItem((String)"ForbiddenMagic:WandCaps", (int)2);
        IItemStack iItemStack4 = ItemBracketHandler.getItem((String)"ForbiddenMagic:WandCaps", (int)1);
        IItemStack iItemStack5 = ItemBracketHandler.getItem((String)"ForbiddenMagic:WandCaps", (int)5);
        IItemStack iItemStack6 = ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)15);
        Arcane.addShaped((String)"CAP_elementium", (IItemStack)ItemBracketHandler.getItem((String)"ForbiddenMagic:WandCaps", (int)6), (String)"aer 60, terra 60, ignis 60, aqua 60, ordo 60, perditio 60", (IIngredient[][])new IIngredient[][]{{OreBracketHandler.getOre((String)"screwTungstenSteel"), OreBracketHandler.getOre((String)"plateInfusedAir"), OreBracketHandler.getOre((String)"screwTungstenSteel")}, {OreBracketHandler.getOre((String)"plateInfusedWater"), iItemStack2, OreBracketHandler.getOre((String)"plateInfusedFire")}, {OreBracketHandler.getOre((String)"screwTungstenSteel"), OreBracketHandler.getOre((String)"plateInfusedEarth"), OreBracketHandler.getOre((String)"screwTungstenSteel")}});
        Arcane.addShaped((String)"CAP_vinteum", (IItemStack)iItemStack4, (String)"aer 40, terra 40, ignis 40, aqua 40, ordo 40, perditio 40", (IIngredient[][])new IIngredient[][]{{OreBracketHandler.getOre((String)"screwTitanium"), OreBracketHandler.getOre((String)"foilVinteum"), OreBracketHandler.getOre((String)"screwTitanium")}, {OreBracketHandler.getOre((String)"foilVinteum"), OreBracketHandler.getOre((String)"ringVinteum"), OreBracketHandler.getOre((String)"foilVinteum")}, {OreBracketHandler.getOre((String)"screwTitanium"), OreBracketHandler.getOre((String)"foilVinteum"), OreBracketHandler.getOre((String)"screwTitanium")}});
        Arcane.addShaped((String)"ROD_witchwood_staff", (IItemStack)ItemBracketHandler.getItem((String)"ForbiddenMagic:WandCores", (int)10), (String)"aer 125, terra 125, ignis 125, aqua 125, ordo 125, perditio 125", (IIngredient[][])new IIngredient[][]{{ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)1), iItemStack6}, {ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)2), ItemBracketHandler.getItem((String)"ForbiddenMagic:WandCores", (int)4), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)3)}, {ItemBracketHandler.getItem((String)"ForbiddenMagic:WandCores", (int)4), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)4), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)5)}});
        Arcane.addShaped((String)"ROD_dreamwood_staff", (IItemStack)ItemBracketHandler.getItem((String)"ForbiddenMagic:WandCores", (int)13), (String)"aer 125, terra 125, ignis 125, aqua 125, ordo 125, perditio 125", (IIngredient[][])new IIngredient[][]{{ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)1), iItemStack6}, {ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)2), ItemBracketHandler.getItem((String)"ForbiddenMagic:WandCores", (int)11), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)3)}, {ItemBracketHandler.getItem((String)"ForbiddenMagic:WandCores", (int)11), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)4), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)5)}});
        Arcane.addShaped((String)"ROD_witchwood_staff", (IItemStack)ItemBracketHandler.getItem((String)"ForbiddenMagic:WandCaps", (int)10), (String)"aer 40, terra 40, ignis 40, aqua 40, ordo 40, perditio 40", (IIngredient[][])new IIngredient[][]{{OreBracketHandler.getOre((String)"screwTitanium"), OreBracketHandler.getOre((String)"foilVinteum"), OreBracketHandler.getOre((String)"screwTitanium")}, {OreBracketHandler.getOre((String)"foilVinteum"), OreBracketHandler.getOre((String)"ringVinteum"), OreBracketHandler.getOre((String)"foilVinteum")}, {OreBracketHandler.getOre((String)"screwTitanium"), OreBracketHandler.getOre((String)"foilVinteum"), OreBracketHandler.getOre((String)"screwTitanium")}});
        Crucible.addRecipe((String)"VINTEUM", (IItemStack)ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)9529), (IIngredient)ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)9330), (String)"permutatio 4, ordo 2, vitreus 2");
        Infusion.addRecipe((String)"ROD_livingwood", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:WandRod", (int)0), (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"AWWayofTime:bucketLife", (int)0), ItemBracketHandler.getItem((String)"TConstruct:materials", (int)6), ItemBracketHandler.getItem((String)"Thaumcraft:blockMagicalLog", (int)0), ItemBracketHandler.getItem((String)"AWWayofTime:bucketLife", (int)0), ItemBracketHandler.getItem((String)"TConstruct:materials", (int)6), ItemBracketHandler.getItem((String)"Thaumcraft:blockMagicalLog", (int)0), ItemBracketHandler.getItem((String)"AWWayofTime:bucketLife", (int)0), ItemBracketHandler.getItem((String)"TConstruct:materials", (int)6), ItemBracketHandler.getItem((String)"Thaumcraft:blockMagicalLog", (int)0)}, (String)"victus 64, herba 32, arbor 32, praecantatio 24, instrumentum 24", (IItemStack)ItemBracketHandler.getItem((String)"ForbiddenMagic:WandCores", (int)7), (int)6);
        Infusion.addRecipe((String)"ROD_dreamwood", (IItemStack)ItemBracketHandler.getItem((String)"ForbiddenMagic:WandCores", (int)7), (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"Thaumcraft:blockMagicalLog", (int)1), ItemBracketHandler.getItem((String)"EnderIO:itemMaterial", (int)5), ItemBracketHandler.getItem((String)"EnderIO:itemMaterial", (int)6), ItemBracketHandler.getItem((String)"Thaumcraft:blockMagicalLog", (int)1), ItemBracketHandler.getItem((String)"EnderIO:itemMaterial", (int)5), ItemBracketHandler.getItem((String)"EnderIO:itemMaterial", (int)6)}, (String)"auram 64, praecantatio 48, tempestas 32, instrumentum 24, lux 24", (IItemStack)ItemBracketHandler.getItem((String)"ForbiddenMagic:WandCores", (int)11), (int)7);
        Infusion.addRecipe((String)"ROD_witchwood", (IItemStack)ItemBracketHandler.getItem((String)"witchery:ingredient", (int)82), (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)8529), ItemBracketHandler.getItem((String)"witchery:witchsapling", (int)0), ItemBracketHandler.getItem((String)"witchery:ingredient", (int)34), ItemBracketHandler.getItem((String)"witchery:witchsapling", (int)1), ItemBracketHandler.getItem((String)"witchery:ingredient", (int)36), ItemBracketHandler.getItem((String)"witchery:witchsapling", (int)2), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)8529), ItemBracketHandler.getItem((String)"witchery:witchsapling", (int)0), ItemBracketHandler.getItem((String)"witchery:ingredient", (int)34), ItemBracketHandler.getItem((String)"witchery:witchsapling", (int)1), ItemBracketHandler.getItem((String)"witchery:ingredient", (int)36), ItemBracketHandler.getItem((String)"witchery:witchsapling", (int)2)}, (String)"arbor 64, praecantatio 48, herba 32, instrumentum 24,vacuos 24", (IItemStack)ItemBracketHandler.getItem((String)"ForbiddenMagic:WandCores", (int)4), (int)6);
        Infusion.addRecipe((String)"CAP_manasteel", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:WandCap", (int)4), (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)2333), ItemBracketHandler.getItem((String)"ProjRed|Core:projectred.core.part", (int)56), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)2333), ItemBracketHandler.getItem((String)"ProjRed|Core:projectred.core.part", (int)56), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)2333), ItemBracketHandler.getItem((String)"ProjRed|Core:projectred.core.part", (int)56), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)2333), ItemBracketHandler.getItem((String)"ProjRed|Core:projectred.core.part", (int)56), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)2333), ItemBracketHandler.getItem((String)"ProjRed|Core:projectred.core.part", (int)56)}, (String)"potentia 64, praecantatio 48, electrum 32, instrumentum 24, machina 24", (IItemStack)iItemStack2, (int)6);
        Infusion.addRecipe((String)"CAP_terrasteel", (IItemStack)iItemStack2, (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.02", (int)30501), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)3), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)17339), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)3), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.02", (int)30501), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)3), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)17339), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)3)}, (String)"praecantatio 256, ordo 64, metallum 64, superbia 20, strontio 10", (IItemStack)iItemStack3, (int)6);
        Infusion.addRecipe((String)"CAP_elementium", (IItemStack)ItemBracketHandler.getItem((String)"ForbiddenMagic:WandCaps", (int)6), (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)6), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)14), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)14), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)1), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)14), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)6), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)14), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)2), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)14), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)3), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)14)}, (String)"ignis 32, aqua 32 , aer 32, terra 32, ordo 32 , perditio 32, praecantatio 32, potentia 24", (IItemStack)iItemStack5, (int)7);
        Research.addResearch((String)"JOURNEY", (String)"FORBIDDEN", (String)"iter 5, praecantatio 10, instrumentum 3", (int)-3, (int)1, (int)8, (IItemStack)ItemBracketHandler.getItem((String)"BiomesOPlenty:food", (int)7));
        MineTweakerAPI.game.setLocalization("en_US", "tc.research_name.JOURNEY", "A long Journey");
        MineTweakerAPI.game.setLocalization("en_US", "tc.research_text.JOURNEY", "[FM] There must be more Magic!");
        Research.addPage((String)"JOURNEY", (String)"derp.research_page.JOURNEY");
        MineTweakerAPI.game.setLocalization("en_US", "derp.research_page.JOURNEY", "The Thaumonomicon told you about purple trees with white leaves and about colorful sparkeling flowers, but you simple were unable to find them in the world, it seems that they don't exist.<BR> You decited to create these Objects yourself. You're a Thaumaturge, you don't care if things exist or not, you can simpley create them on your own, but it will take further investigation to do so.");
        Research.addPrereq((String)"JOURNEY", (String)"SCHOOLS", (boolean)false);
        Research.setRound((String)"JOURNEY", (boolean)true);
        Research.setStub((String)"JOURNEY", (boolean)true);
        Research.setAutoUnlock((String)"JOURNEY", (boolean)true);
        Research.addResearch((String)"ROD_livingwood", (String)"FORBIDDEN", (String)"victus 5, praecantatio 10, herba 3,instrumentum 4, arbor 5", (int)-1, (int)3, (int)8, (IItemStack)ItemBracketHandler.getItem((String)"ForbiddenMagic:WandCores", (int)7));
        MineTweakerAPI.game.setLocalization("en_US", "tc.research_name.ROD_livingwood", "Livingwood Rod");
        MineTweakerAPI.game.setLocalization("en_US", "tc.research_text.ROD_livingwood", "[FM] A living Wand Rod?");
        Research.addPage((String)"ROD_livingwood", (String)"derp.research_page.ROD_livingwood");
        MineTweakerAPI.game.setLocalization("en_US", "derp.research_page.ROD_livingwood", "You know you could do it! Livingwood could only be created by a flower, until now. By infusing a mundane greatwood rod with, the essence of life, some moss and victus essentia, you were able to create a wandrod out of Livingwood, that can store up to 100 vis. That result is astounding, but you think that you can do better.");
        Research.addInfusionPage((String)"ROD_livingwood", (IItemStack)ItemBracketHandler.getItem((String)"ForbiddenMagic:WandCores", (int)7));
        Research.setConcealed((String)"ROD_livingwood", (boolean)true);
        Research.addPrereq((String)"ROD_livingwood", (String)"JOURNEY", (boolean)false);
        Research.addPrereq((String)"ROD_livingwood", (String)"BLOODALTAR", (boolean)false);
        Research.addPrereq((String)"ROD_livingwood", (String)"BALLOFMOSS", (boolean)false);
        Research.addPrereq((String)"ROD_livingwood", (String)"ROD_greatwood", (boolean)false);
        Warp.addToResearch((String)"ROD_livingwood", (int)2);
        Research.addResearch((String)"ROD_dreamwood", (String)"FORBIDDEN", (String)"auram 5, praecantatio 10, herba 3,instrumentum 4, arbor 5", (int)1, (int)4, (int)8, (IItemStack)ItemBracketHandler.getItem((String)"ForbiddenMagic:WandCores", (int)11));
        MineTweakerAPI.game.setLocalization("en_US", "tc.research_name.ROD_dreamwood", "Dreamwood Rod");
        MineTweakerAPI.game.setLocalization("en_US", "tc.research_text.ROD_dreamwood", "[FM] Sweet dreams are made of these");
        Research.addPage((String)"ROD_dreamwood", (String)"derp.research_page.ROD_dreamwood");
        MineTweakerAPI.game.setLocalization("en_US", "derp.research_page.ROD_dreamwood", "Livingwood is quite useful, but it can't be turned into a staff, it's just to unstable. You heard about dreamwood, which is quite stable, but requires elven magic and you have no idea where you can get an elve from. Maybe it is possible to just stabalize your livingwood rod with some magical crystals and a bit of Silverwood. The thaumonomicon told you that this has to be done in the elven world, but you simply tried to use more auram, which seemed to work aswell. <BR> You new rod now holds exact the same amount of vis than the old one, but it can be turnd into a staff and looks much more stylish.");
        Research.addInfusionPage((String)"ROD_dreamwood", (IItemStack)ItemBracketHandler.getItem((String)"ForbiddenMagic:WandCores", (int)11));
        Research.setConcealed((String)"ROD_dreamwood", (boolean)true);
        Research.addPrereq((String)"ROD_dreamwood", (String)"ROD_livingwood", (boolean)false);
        Research.addPrereq((String)"ROD_dreamwood", (String)"ROD_silverwood", (boolean)false);
        Research.addResearch((String)"ROD_dreamwood_staff", (String)"FORBIDDEN", (String)"auram 5, praecantatio 10, herba 3,instrumentum 4, arbor 5", (int)3, (int)4, (int)8, (IItemStack)ItemBracketHandler.getItem((String)"ForbiddenMagic:WandCores", (int)13));
        MineTweakerAPI.game.setLocalization("en_US", "tc.research_name.ROD_dreamwood_staff", "Dreamwood Staff");
        MineTweakerAPI.game.setLocalization("en_US", "tc.research_text.ROD_dreamwood_staff", "[FM] Oh, fantasy free me!");
        Research.addPage((String)"ROD_dreamwood_staff", (String)"derp.research_page.ROD_dreamwood_staff");
        MineTweakerAPI.game.setLocalization("en_US", "derp.research_page.ROD_dreamwood_staff", "You finally are able to build a staff out of dreamwood, just add a primal charm, some crystal clusters and two rods together and you've got you new staff, that holds up to 250 vis of each type.");
        Research.addPrereq((String)"ROD_dreamwood_staff", (String)"ROD_dreamwood", (boolean)false);
        Research.addArcanePage((String)"ROD_dreamwood_staff", (IItemStack)ItemBracketHandler.getItem((String)"ForbiddenMagic:WandCores", (int)13));
        Research.setSpikey((String)"ROD_dreamwood_staff", (boolean)true);
        Research.setConcealed((String)"ROD_dreamwood_staff", (boolean)true);
        Research.addPrereq((String)"ROD_dreamwood_staff", (String)"ROD_silverwood_staff", (boolean)false);
        Warp.addToResearch((String)"ROD_dreamwood_staff", (int)3);
        Research.addResearch((String)"CAP_manasteel", (String)"FORBIDDEN", (String)"metallum 5, praecantatio 10, lucrum 3,instrumentum 4, auram 5", (int)1, (int)2, (int)8, (IItemStack)iItemStack2);
        MineTweakerAPI.game.setLocalization("en_US", "tc.research_name.CAP_manasteel", "Manasteel Caps");
        MineTweakerAPI.game.setLocalization("en_US", "tc.research_text.CAP_manasteel", "[FM] The secret of Mana");
        Research.addPage((String)"CAP_manasteel", (String)"derp.research_page.CAP_manasteel");
        MineTweakerAPI.game.setLocalization("en_US", "derp.research_page.CAP_manasteel", "Manasteel is the Botanical equivalent to Thaumium, so it should be possible to create caps out of it, by infusing some silver caps with some electrotine and astral silver you were able to create a cap with the strength of blue alloy and a higher magical conductivity than mundane silver. The vis discount is the same as Thaumium, you think thats the reason why it is call Botanical Thaumium.");
        Research.addInfusionPage((String)"CAP_manasteel", (IItemStack)iItemStack2);
        Research.setConcealed((String)"CAP_manasteel", (boolean)true);
        Research.addPrereq((String)"CAP_manasteel", (String)"ROD_livingwood", (boolean)false);
        Research.addPrereq((String)"CAP_manasteel", (String)"CAP_silver", (boolean)false);
        Research.addPrereq((String)"CAP_manasteel", (String)"THAUMIUM", (boolean)false);
        Warp.addToResearch((String)"CAP_manasteel", (int)2);
        Research.addResearch((String)"CAP_terrasteel", (String)"FORBIDDEN", (String)"terra 5, praecantatio 10, superbia 3,instrumentum 4,strontio 2, vitreus 5", (int)3, (int)2, (int)8, (IItemStack)iItemStack3);
        MineTweakerAPI.game.setLocalization("en_US", "tc.research_name.CAP_terrasteel", "Terrasteel Wand Caps");
        MineTweakerAPI.game.setLocalization("en_US", "tc.research_text.CAP_terrasteel", "[FM] Completion!");
        Research.addPage((String)"CAP_terrasteel", (String)"derp.research_page.CAP_terrasteel");
        MineTweakerAPI.game.setLocalization("en_US", "derp.research_page.CAP_terrasteel", "You've read about a metal, that's completely charged with magical energies that it could even summon demons, you don't think that's true, but it's worth a try. Just infuse you manasteel caps again with some steel leafs, crystal clusters and add a few jars of praecantatio essentia and see what happens, maybe it will be the best wand cap existing in this world.");
        Research.addInfusionPage((String)"CAP_terrasteel", (IItemStack)iItemStack3);
        Research.setConcealed((String)"CAP_terrasteel", (boolean)true);
        Research.addPrereq((String)"CAP_terrasteel", (String)"CAP_manasteel", (boolean)false);
        Research.addPrereq((String)"CAP_terrasteel", (String)"TRANSEMERALD", (boolean)true);
        Warp.addToResearch((String)"CAP_terrasteel", (int)4);
        Research.addResearch((String)"CAP_elementium", (String)"FORBIDDEN", (String)"auram 5, praecantatio 10, victus 3,instrumentum 4, humanus 5", (int)3, (int)1, (int)8, (IItemStack)iItemStack5);
        MineTweakerAPI.game.setLocalization("en_US", "tc.research_name.CAP_elementium", "Elementium Wand Caps");
        MineTweakerAPI.game.setLocalization("en_US", "tc.research_text.CAP_elementium", "[FM] Eco Friendly Wand Caps");
        Research.addPage((String)"CAP_elementium", (String)"derp.research_page.CAP_elementium");
        MineTweakerAPI.game.setLocalization("en_US", "derp.research_page.CAP_elementium", "What would happen if you combine you Manasteel caps with power of elemental shards? Instead of thinking about what could happen, you simply tried it, since the shards seem to resist the cap you decided to use some tungstensteel screws to bind it all together. The result is a metal, that has a higher vis discount than thaumium. Sadly it has to be reinfused, due to it's new non magical components.");
        Research.addPrereq((String)"CAP_elementium", (String)"CAP_manasteel", (boolean)false);
        Research.addArcanePage((String)"CAP_elementium", (IItemStack)ItemBracketHandler.getItem((String)"ForbiddenMagic:WandCaps", (int)6));
        Research.addInfusionPage((String)"CAP_elementium", (IItemStack)iItemStack5);
        Research.setConcealed((String)"CAP_elementium", (boolean)true);
        Research.addResearch((String)"VINTEUM", (String)"FORBIDDEN", (String)"metallum 5, permutatio 10, praecantatio 3, lucrum 2", (int)-4, (int)2, (int)8, (IItemStack)ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)8529));
        MineTweakerAPI.game.setLocalization("en_US", "tc.research_name.VINTEUM", "Vinteum");
        MineTweakerAPI.game.setLocalization("en_US", "tc.research_text.VINTEUM", "[FM] Thaumium's smaller brother");
        Research.addPage((String)"VINTEUM", (String)"derp.research_page.VINTEUM");
        MineTweakerAPI.game.setLocalization("en_US", "derp.research_page.VINTEUM", "Every Thaumaturge knows about Thaumium, it is fairly easy to produce and is a great magical conductor. More skilled Thaumaturges prefer using vinteum instead. Vintum is similar to Thaumium, but can also be turned into gems, due to it's more ordered molecular structure. You just have to reorganize some Thaumium to turn it into vinteum, just throw it into a cauldron with some Permutatio and Ordo in it, that should be enough.");
        Research.addCruciblePage((String)"VINTEUM", (IItemStack)ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)9529));
        Research.setConcealed((String)"VINTEUM", (boolean)true);
        Research.addPrereq((String)"VINTEUM", (String)"JOURNEY", (boolean)false);
        Research.addPrereq((String)"VINTEUM", (String)"THAUMIUM", (boolean)false);
        Research.addPrereq((String)"VINTEUM", (String)"GT_ADVANCEDMETALLURGY", (boolean)false);
        Warp.addToResearch((String)"VINTEUM", (int)1);
        Research.addResearch((String)"CAP_vinteum", (String)"FORBIDDEN", (String)"permutatio 5, praecantatio 10,lucrum 3,instrumentum 4, metallum 5", (int)-5, (int)3, (int)8, (IItemStack)iItemStack4);
        MineTweakerAPI.game.setLocalization("en_US", "tc.research_name.CAP_vinteum", "Vinteum Caps");
        MineTweakerAPI.game.setLocalization("en_US", "tc.research_text.CAP_vinteum", "[FM] They're blue!");
        Research.addPage((String)"CAP_vinteum", (String)"derp.research_page.CAP_vinteum");
        MineTweakerAPI.game.setLocalization("en_US", "derp.research_page.CAP_vinteum", "Since vinteum is just reorganized Thaumium, you can't expect that it gives you a higher vis discount, but since it is much more ordered you can directly use it's full magical potential, which means no infusion required");
        Research.addArcanePage((String)"CAP_vinteum", (IItemStack)iItemStack4);
        Research.setConcealed((String)"CAP_vinteum", (boolean)true);
        Research.addPrereq((String)"CAP_vinteum", (String)"VINTEUM", (boolean)false);
        Research.addPrereq((String)"CAP_vinteum", (String)"CAP_thaumium", (boolean)false);
        Warp.addToResearch((String)"CAP_vinteum", (int)3);
        Research.addResearch((String)"ROD_witchwood", (String)"FORBIDDEN", (String)"victus 5, praecantatio 10, herba 3,instrumentum 4, arbor 5", (int)-4, (int)0, (int)8, (IItemStack)ItemBracketHandler.getItem((String)"ForbiddenMagic:WandCores", (int)4));
        MineTweakerAPI.game.setLocalization("en_US", "tc.research_name.ROD_witchwood", "Witchwood Rod");
        MineTweakerAPI.game.setLocalization("en_US", "tc.research_text.ROD_witchwood", "[FM] That's witchcraft");
        Research.addPage((String)"ROD_witchwood", (String)"derp.research_page.ROD_witchwood");
        MineTweakerAPI.game.setLocalization("en_US", "derp.research_page.ROD_witchwood", "You had no luck finding a purple tree to make a wand of, now it's time to create it on your own. With the twig of a mighty tree creature, you should have the best possible starting material. Combined with some of the most magical trees you know it should make a pretty good wand rod. <BR> This Wand is able to store 100 vis of each type, quite a nice result.");
        Research.addInfusionPage((String)"ROD_witchwood", (IItemStack)ItemBracketHandler.getItem((String)"ForbiddenMagic:WandCores", (int)4));
        Research.setConcealed((String)"ROD_witchwood", (boolean)true);
        Research.addPrereq((String)"ROD_witchwood", (String)"VINTEUM", (boolean)false);
        Research.addPrereq((String)"ROD_witchwood", (String)"ANOINTINGPASTE", (boolean)false);
        Research.addPrereq((String)"ROD_witchwood", (String)"OVEN", (boolean)false);
        Warp.addToResearch((String)"ROD_witchwood", (int)2);
        Research.addResearch((String)"ROD_witchwood_staff", (String)"FORBIDDEN", (String)"victus 5, praecantatio 10, herba 3,instrumentum 4, arbor 5", (int)-2, (int)0, (int)8, (IItemStack)ItemBracketHandler.getItem((String)"ForbiddenMagic:WandCores", (int)10));
        MineTweakerAPI.game.setLocalization("en_US", "tc.research_name.ROD_witchwood_staff", "Witchwood Staff");
        MineTweakerAPI.game.setLocalization("en_US", "tc.research_text.ROD_witchwood_staff", "[FM] Without Circle Magic");
        Research.addPage((String)"ROD_witchwood_staff", (String)"derp.research_page.ROD_witchwood_staff");
        MineTweakerAPI.game.setLocalization("en_US", "derp.research_page.ROD_witchwood_staff", "Witchwood doesn't like Elemental shards, that's interesting, but a fundamental problem when it comes to create a staff out of it. It loses some capacity when doing so, but it works.");
        Research.addArcanePage((String)"ROD_witchwood_staff", (IItemStack)ItemBracketHandler.getItem((String)"ForbiddenMagic:WandCores", (int)10));
        Research.setSpikey((String)"ROD_witchwood_staff", (boolean)true);
        Research.setConcealed((String)"ROD_witchwood_staff", (boolean)true);
        Research.addPrereq((String)"ROD_witchwood_staff", (String)"ROD_witchwood", (boolean)false);
        Research.addPrereq((String)"ROD_witchwood_staff", (String)"ROD_silverwood_staff", (boolean)false);
        Warp.addToResearch((String)"ROD_witchwood_staff", (int)4);
    }
}

