package com.github.GTNH2Mega.fromScripts

import com.github.GTNH2Mega.VoltageLevels.IV
import java.lang.Runnable
import minetweaker.api.item.IItemStack
import minetweaker.mc1710.brackets.ItemBracketHandler
import minetweaker.api.oredict.IOreDictEntry
import minetweaker.mc1710.brackets.OreBracketHandler
import minetweaker.MineTweakerAPI
import fox.spiteful.avaritia.compat.minetweaker.ExtremeCrafting
import minetweaker.api.item.IIngredient
import gttweaker.mods.gregtech.machines.Assembler
import minetweaker.mc1710.brackets.LiquidBracketHandler

class Gendustry : Runnable {
    override fun run() {
        val iItemStack = ItemBracketHandler.getItem("gendustry:IndustrialApiary", 0)
        val iItemStack2 = ItemBracketHandler.getItem("gendustry:MutagenProducer", 0)
        val iItemStack3 = ItemBracketHandler.getItem("gendustry:Mutatron", 0)
        val iItemStack4 = ItemBracketHandler.getItem("gendustry:Imprinter", 0)
        val iItemStack5 = ItemBracketHandler.getItem("gendustry:Sampler", 0)
        val iItemStack6 = ItemBracketHandler.getItem("gendustry:MutatronAdv", 0)
        val iItemStack7 = ItemBracketHandler.getItem("gendustry:Liquifier", 0)
        val iItemStack8 = ItemBracketHandler.getItem("gendustry:Extractor", 0)
        val iItemStack9 = ItemBracketHandler.getItem("gendustry:Transposer", 0)
        val iItemStack10 = ItemBracketHandler.getItem("gendustry:Replicator", 0)
        val iItemStack11 = ItemBracketHandler.getItem("gendustry:GeneSampleBlank", 0)
        val iItemStack12 = ItemBracketHandler.getItem("gendustry:GeneTemplate", 0)
        val iItemStack13 = ItemBracketHandler.getItem("gendustry:Labware", 0)
        val iItemStack14 = ItemBracketHandler.getItem("gendustry:BeeReceptacle", 0)
        val iItemStack15 = ItemBracketHandler.getItem("gendustry:PowerModule", 0)
        val iItemStack16 = ItemBracketHandler.getItem("gendustry:MutagenTank", 0)
        val iItemStack17 = ItemBracketHandler.getItem("gendustry:GeneticsProcessor", 0)
        val iItemStack18 = ItemBracketHandler.getItem("gendustry:EnvProcessor", 0)
        val iItemStack19 = ItemBracketHandler.getItem("gendustry:UpgradeFrame", 0)
        val iItemStack20 = ItemBracketHandler.getItem("gendustry:ClimateModule", 0)
        val iItemStack27 = ItemBracketHandler.getItem("Forestry:hardenedMachine", 0)
        val iItemStack28 = ItemBracketHandler.getItem("Forestry:craftingMaterial", 3)
        val iItemStack29 = ItemBracketHandler.getItem("Forestry:royalJelly", 0)
        val iItemStack30 = ItemBracketHandler.getItem("Forestry:grafter", 0)
        val iItemStack31 = ItemBracketHandler.getItem("TConstruct:GlassPane", 0)
        val iOreDictEntry3 = OreBracketHandler.getOre("gearTitanium")
        val iOreDictEntry5 = OreBracketHandler.getOre("gearNaquadahAlloy")
        val iOreDictEntry7 = OreBracketHandler.getOre("gearGtSmallPalladium")
        val iOreDictEntry9 = OreBracketHandler.getOre("gearOsmium")
        val iOreDictEntry10 = OreBracketHandler.getOre("gearGtSmallOsmium")
        val iOreDictEntry11 = OreBracketHandler.getOre("rotorOsmium")
        val iOreDictEntry14 = OreBracketHandler.getOre("plateRedAlloy")
        val iOreDictEntry21 = OreBracketHandler.getOre("plateEnderPearl")
        val iItemStack32 = ItemBracketHandler.getItem("dreamcraft:item.EngravedDiamondCrystalChip", 0)
        val iOreDictEntry23 = OreBracketHandler.getOre("plateIron")
        val iItemStack33 = ItemBracketHandler.getItem("dreamcraft:item.IridiumAlloyItemCasing", 0)
        val iOreDictEntry26 = OreBracketHandler.getOre("cableGt01VanadiumGallium")
        val iOreDictEntry31 = OreBracketHandler.getOre("screwHSSS")
        val iOreDictEntry35 = OreBracketHandler.getOre("stickPalladium")
        val iItemStack36 = ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32643)
        val iItemStack37 = ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32645)
        val iItemStack40 = ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32606)
        val iItemStack44 = ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32655)
        val iOreDictEntry38 = OreBracketHandler.getOre("craftingToolScoop")
        val iOreDictEntry39 = OreBracketHandler.getOre("craftingToolScrewdriver")
        val iOreDictEntry41 = OreBracketHandler.getOre("blockHopper")
        val iItemStack47 = ItemBracketHandler.getItem("minecraft:grass", 0)
        val iItemStack48 = ItemBracketHandler.getItem("ExtraUtilities:decorativeBlock2", 7)
        val iItemStack50 = ItemBracketHandler.getItem("minecraft:sand", 32767)
        val iItemStack51 = ItemBracketHandler.getItem("minecraft:cactus", 0)
        val iItemStack52 = ItemBracketHandler.getItem("minecraft:water_bucket", 0)
        val iItemStack53 = ItemBracketHandler.getItem("minecraft:lava_bucket", 0)
        val iItemStack54 = ItemBracketHandler.getItem("minecraft:blaze_rod", 0)
        val iItemStack55 = ItemBracketHandler.getItem("minecraft:ghast_tear", 0)
        val iItemStack56 = ItemBracketHandler.getItem("minecraft:snow", 0)
        val iItemStack57 = ItemBracketHandler.getItem("BiomesOPlenty:hardIce", 0)
        val iOreDictEntry42 = OreBracketHandler.getOre("plateAnyRubber")
        val iOreDictEntry43 = OreBracketHandler.getOre("itemBeeswax")
        val iItemStack58 = ItemBracketHandler.getItem("minecraft:vine", 0)
        val iItemStack59 = ItemBracketHandler.getItem("minecraft:netherrack", 0)
        val iItemStack60 = ItemBracketHandler.getItem("dreamcraft:item.SteelBars", 0)
        val iItemStack61 = ItemBracketHandler.getItem("dreamcraft:item.OsmiumBars", 0)
        val iItemStack62 = ItemBracketHandler.getItem("gregtech:gt.metaitem.02", 21028)
        val iItemStack63 = ItemBracketHandler.getItem("minecraft:sugar", 0)
        val iItemStack67 = ItemBracketHandler.getItem("irontank:diamondTank", 0)
        val iItemStack68 = ItemBracketHandler.getItem("IC2:itemRecipePart", 0)
        MineTweakerAPI.recipes.remove(iItemStack)
        MineTweakerAPI.recipes.remove(iItemStack2)
        MineTweakerAPI.recipes.remove(iItemStack3)
        MineTweakerAPI.recipes.remove(iItemStack4)
        MineTweakerAPI.recipes.remove(iItemStack5)
        MineTweakerAPI.recipes.remove(iItemStack6)
        MineTweakerAPI.recipes.remove(iItemStack7)
        MineTweakerAPI.recipes.remove(iItemStack8)
        MineTweakerAPI.recipes.remove(iItemStack9)
        MineTweakerAPI.recipes.remove(iItemStack10)
        MineTweakerAPI.recipes.remove(iItemStack19)
        MineTweakerAPI.recipes.remove(iItemStack13)
        MineTweakerAPI.recipes.removeShaped(iItemStack11, null)
        MineTweakerAPI.recipes.removeShaped(iItemStack12, null)
        MineTweakerAPI.recipes.remove(iItemStack16)
        MineTweakerAPI.recipes.remove(iItemStack14)
        MineTweakerAPI.recipes.remove(iItemStack15)
        MineTweakerAPI.recipes.remove(iItemStack17)
        MineTweakerAPI.recipes.remove(iItemStack18)
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("gendustry:ApiaryUpgrade", 32767))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("gendustry:IndustrialGrafter", 32767))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("gendustry:IndustrialScoop", 32767))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("gendustry:MutagenTank", 0))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("gendustry:BeeReceptacle", 0))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("gendustry:PowerModule", 0))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("gendustry:ClimateModule", 0))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("gendustry:GeneticsProcessor", 0))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("gendustry:EnvProcessor", 0))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("gendustry:UpgradeFrame", 0))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("gendustry:EjectCover", 0))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("gendustry:ImportCover", 0))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("gendustry:ErrorSensorCover", 0))
        ExtremeCrafting.addShaped(iItemStack2, arrayOf(arrayOfNulls(9), arrayOfNulls(9), arrayOf(null, null, iItemStack16, OreBracketHandler.getOre("plateBlackPlutonium"), iItemStack15, OreBracketHandler.getOre("plateBlackPlutonium"), iItemStack16, null, null), arrayOf<IIngredient?>(null, null, ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32617), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32657), iItemStack17, ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32657), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32617), null, null), arrayOf(null, null, iItemStack14, iOreDictEntry9, iItemStack27, iOreDictEntry9, iItemStack14, null, null), arrayOf<IIngredient?>(null, null, ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32617), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32608), iItemStack17, ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32608), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32617), null, null), arrayOf(null, null, iItemStack16, OreBracketHandler.getOre("plateBlackPlutonium"), iItemStack15, OreBracketHandler.getOre("plateBlackPlutonium"), iItemStack16, null, null), arrayOfNulls(9), arrayOfNulls(9)))
        ExtremeCrafting.addShaped(iItemStack, arrayOf(arrayOfNulls(9), arrayOfNulls(9), arrayOf(null, null, OreBracketHandler.getOre("gearTungstenSteel"), ItemBracketHandler.getItem("Forestry:alveary", 6), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32606), ItemBracketHandler.getItem("Forestry:alveary", 6), OreBracketHandler.getOre("gearTungstenSteel"), null, null), arrayOf<IIngredient?>(null, null, ItemBracketHandler.getItem("Forestry:alveary", 5), ItemBracketHandler.getItem("Forestry:alveary", 0), ItemBracketHandler.getItem("Forestry:alveary", 7), ItemBracketHandler.getItem("Forestry:alveary", 0), ItemBracketHandler.getItem("Forestry:alveary", 4), null, null), arrayOf<IIngredient?>(null, null, ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32606), ItemBracketHandler.getItem("Forestry:alveary", 2), ItemBracketHandler.getItem("Forestry:apiculture", 0), ItemBracketHandler.getItem("Forestry:alveary", 2), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32606), null, null), arrayOf<IIngredient?>(null, null, ItemBracketHandler.getItem("Forestry:alveary", 5), ItemBracketHandler.getItem("Forestry:alveary", 0), ItemBracketHandler.getItem("Forestry:alveary", 7), ItemBracketHandler.getItem("Forestry:alveary", 0), ItemBracketHandler.getItem("Forestry:alveary", 4), null, null), arrayOf(null, null, OreBracketHandler.getOre("gearTungstenSteel"), ItemBracketHandler.getItem("Forestry:alveary", 3), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32675), ItemBracketHandler.getItem("Forestry:alveary", 3), OreBracketHandler.getOre("gearTungstenSteel"), null, null), arrayOfNulls(9), arrayOfNulls(9)))
        ExtremeCrafting.addShaped(iItemStack3, arrayOf(arrayOfNulls(9), arrayOfNulls(9), arrayOf(null, null, iItemStack16, OreBracketHandler.getOre("plateMysteriousCrystal"), iItemStack17, OreBracketHandler.getOre("plateMysteriousCrystal"), iItemStack16, null, null), arrayOf(null, null, iOreDictEntry9, iItemStack14, ItemBracketHandler.getItem("gregtech:gt.comb", 79), iItemStack14, iOreDictEntry9, null, null), arrayOf<IIngredient?>(null, null, ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32656), iItemStack15, iItemStack27, iItemStack15, ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32656), null, null), arrayOf(null, null, iOreDictEntry9, iItemStack14, ItemBracketHandler.getItem("gregtech:gt.comb", 79), iItemStack14, iOreDictEntry9, null, null), arrayOf(null, null, iItemStack16, OreBracketHandler.getOre("plateMysteriousCrystal"), iItemStack17, OreBracketHandler.getOre("plateMysteriousCrystal"), iItemStack16, null, null), arrayOfNulls(9), arrayOfNulls(9)))
        MineTweakerAPI.recipes.addShaped(iItemStack4, arrayOf(arrayOf(iItemStack17, iOreDictEntry9, iItemStack17), arrayOf<IIngredient>(iItemStack14, iItemStack27, iItemStack14), arrayOf(iOreDictEntry9, iItemStack15, iOreDictEntry9)), null)
        MineTweakerAPI.recipes.addShaped(iItemStack5, arrayOf(arrayOf<IIngredient>(iItemStack17, iItemStack14, iItemStack17), arrayOf<IIngredient>(iItemStack32, iItemStack27, iItemStack32), arrayOf(iOreDictEntry9, iItemStack15, iOreDictEntry9)), null)
        ExtremeCrafting.addShaped(iItemStack6, arrayOf(arrayOfNulls(9), arrayOfNulls(9), arrayOf(null, null, iOreDictEntry5, OreBracketHandler.getOre("plateCosmicNeutronium"), iItemStack15, OreBracketHandler.getOre("plateCosmicNeutronium"), iOreDictEntry5, null, null), arrayOf(null, null, OreBracketHandler.getOre("plateCosmicNeutronium"), ItemBracketHandler.getItem("gregtech:gt.comb", 85), iItemStack17, ItemBracketHandler.getItem("gregtech:gt.comb", 85), OreBracketHandler.getOre("plateCosmicNeutronium"), null, null), arrayOf<IIngredient?>(null, null, ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32657), iItemStack17, iItemStack3, iItemStack17, ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32657), null, null), arrayOf(null, null, OreBracketHandler.getOre("plateCosmicNeutronium"), ItemBracketHandler.getItem("gregtech:gt.comb", 85), iItemStack17, ItemBracketHandler.getItem("gregtech:gt.comb", 85), OreBracketHandler.getOre("plateCosmicNeutronium"), null, null), arrayOf(null, null, iOreDictEntry5, OreBracketHandler.getOre("plateCosmicNeutronium"), iItemStack15, OreBracketHandler.getOre("plateCosmicNeutronium"), iOreDictEntry5, null, null), arrayOfNulls(9), arrayOfNulls(9)))
        MineTweakerAPI.recipes.addShaped(iItemStack7, arrayOf(arrayOf<IIngredient>(iOreDictEntry9, iOreDictEntry41, iOreDictEntry9), arrayOf<IIngredient>(iItemStack37, iItemStack27, iItemStack37), arrayOf(iOreDictEntry9, iItemStack15, iOreDictEntry9)), null)
        MineTweakerAPI.recipes.addShaped(iItemStack8, arrayOf(arrayOf<IIngredient>(iItemStack37, iItemStack14, iItemStack37), arrayOf<IIngredient>(iItemStack17, iItemStack27, iItemStack17), arrayOf(iOreDictEntry9, iItemStack15, iOreDictEntry9)), null)
        MineTweakerAPI.recipes.addShaped(iItemStack9, arrayOf(arrayOf(iItemStack44, iOreDictEntry9, iItemStack44), arrayOf<IIngredient>(iItemStack17, iItemStack27, iItemStack17), arrayOf(iOreDictEntry9, iItemStack15, iOreDictEntry9)), null)
        MineTweakerAPI.recipes.addShaped(iItemStack10, arrayOf(arrayOf<IIngredient>(iItemStack44, iItemStack17, iItemStack44), arrayOf<IIngredient>(iItemStack15, iItemStack27, iItemStack15), arrayOf(iOreDictEntry9, iItemStack17, iOreDictEntry9)), null)
        MineTweakerAPI.recipes.addShaped(iItemStack14, arrayOf(arrayOf(iOreDictEntry31, ItemBracketHandler.getItem("gregtech:gt.comb", 78), iOreDictEntry31), arrayOf<IIngredient>(iItemStack33, iItemStack61, iItemStack33), arrayOf<IIngredient>(iOreDictEntry31, iOreDictEntry39, iOreDictEntry31)), null)
        MineTweakerAPI.recipes.addShaped(iItemStack15, arrayOf(arrayOf(iOreDictEntry26, ItemBracketHandler.getItem("gregtech:gt.comb", 79), iOreDictEntry26), arrayOf(iItemStack33, OreBracketHandler.getOre("circuitMaster"), iItemStack33), arrayOf(iOreDictEntry10, iItemStack40, iOreDictEntry10)), null)
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("gendustry:ApiaryUpgrade", 17), arrayOf(arrayOf(iOreDictEntry7, iItemStack20, iOreDictEntry7), arrayOf<IIngredient>(iItemStack47, iItemStack19, iItemStack47), arrayOf(iOreDictEntry10, iItemStack18, iOreDictEntry10)), null)
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("gendustry:ApiaryUpgrade", 11), arrayOf(arrayOf(iOreDictEntry7, iItemStack48, iOreDictEntry7), arrayOf<IIngredient>(iItemStack48, iItemStack19, iItemStack48), arrayOf(iOreDictEntry10, iItemStack48, iOreDictEntry10)), null)
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("gendustry:ApiaryUpgrade", 2), arrayOf(arrayOf(iOreDictEntry7, ItemBracketHandler.getItem("minecraft:red_flower", 0), iOreDictEntry7), arrayOf<IIngredient>(ItemBracketHandler.getItem("Botany:pollen", 32767), iItemStack19, ItemBracketHandler.getItem("Botany:pollen", 32767)), arrayOf(iOreDictEntry10, ItemBracketHandler.getItem("minecraft:yellow_flower", 0), iOreDictEntry10)), null)
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("gendustry:ApiaryUpgrade", 20), arrayOf(arrayOf(iOreDictEntry7, iItemStack20, iOreDictEntry7), arrayOf<IIngredient>(iItemStack57, iItemStack19, iItemStack57), arrayOf(iOreDictEntry10, iItemStack18, iOreDictEntry10)), null)
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("gendustry:ApiaryUpgrade", 5), arrayOf(arrayOf(iOreDictEntry7, iItemStack20, iOreDictEntry7), arrayOf<IIngredient>(iItemStack50, iItemStack19, iItemStack50), arrayOf(iOreDictEntry10, iItemStack53, iOreDictEntry10)), null)
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("gendustry:ApiaryUpgrade", 14), arrayOf(arrayOf<IIngredient>(iOreDictEntry7, iOreDictEntry3, iOreDictEntry7), arrayOf<IIngredient>(ItemBracketHandler.getItem("minecraft:redstone_torch", 0), iItemStack19, ItemBracketHandler.getItem("minecraft:redstone_torch", 0)), arrayOf(iOreDictEntry10, iItemStack36, iOreDictEntry10)), null)
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("gendustry:ApiaryUpgrade", 4), arrayOf(arrayOf(iOreDictEntry7, iItemStack20, iOreDictEntry7), arrayOf<IIngredient>(iItemStack51, iItemStack19, iItemStack51), arrayOf(iOreDictEntry10, iItemStack52, iOreDictEntry10)), null)
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("gendustry:ApiaryUpgrade", 13), arrayOf(arrayOf(iOreDictEntry7, iItemStack20, iOreDictEntry7), arrayOf<IIngredient>(iItemStack54, iItemStack19, iItemStack55), arrayOf(iOreDictEntry10, iItemStack18, iOreDictEntry10)), null)
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("gendustry:ApiaryUpgrade", 22), arrayOf(arrayOf(iOreDictEntry7, iItemStack60, iOreDictEntry7), arrayOf<IIngredient>(iItemStack62, iItemStack19, iItemStack62), arrayOf(iOreDictEntry10, iItemStack60, iOreDictEntry10)), null)
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("gendustry:ApiaryUpgrade", 16), arrayOf(arrayOf(iOreDictEntry7, iItemStack20, iOreDictEntry7), arrayOf<IIngredient>(iItemStack50, iItemStack19, iItemStack50), arrayOf(iOreDictEntry10, iItemStack18, iOreDictEntry10)), null)
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("gendustry:ApiaryUpgrade", 7), arrayOf(arrayOf(iOreDictEntry7, iItemStack20, iOreDictEntry7), arrayOf<IIngredient>(iItemStack56, iItemStack19, iItemStack56), arrayOf(iOreDictEntry10, iItemStack57, iOreDictEntry10)), null)
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("gendustry:ApiaryUpgrade", 1), arrayOf(arrayOf(iOreDictEntry7, ItemBracketHandler.getItem("minecraft:fermented_spider_eye", 0), iOreDictEntry7), arrayOf<IIngredient>(ItemBracketHandler.getItem("BiomesOPlenty:jarFilled", 1), iItemStack19, ItemBracketHandler.getItem("BiomesOPlenty:jarFilled", 1)), arrayOf(iOreDictEntry10, ItemBracketHandler.getItem("minecraft:fermented_spider_eye", 0), iOreDictEntry10)), null)
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("gendustry:ApiaryUpgrade", 10), arrayOf(arrayOf<IIngredient>(iOreDictEntry7, iOreDictEntry42, iOreDictEntry7), arrayOf(iOreDictEntry43, iItemStack19, iOreDictEntry43), arrayOf<IIngredient>(iOreDictEntry10, iOreDictEntry42, iOreDictEntry10)), null)
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("gendustry:ApiaryUpgrade", 19), arrayOf(arrayOf(iOreDictEntry7, iItemStack17, iOreDictEntry7), arrayOf(iOreDictEntry14, iItemStack19, iOreDictEntry14), arrayOf(iOreDictEntry10, iItemStack17, iOreDictEntry10)), null)
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("gendustry:ApiaryUpgrade", 18), arrayOf(arrayOf(iOreDictEntry7, iItemStack20, iOreDictEntry7), arrayOf<IIngredient>(iItemStack58, iItemStack19, iItemStack58), arrayOf(iOreDictEntry10, iItemStack18, iOreDictEntry10)), null)
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("gendustry:ApiaryUpgrade", 3), arrayOf(arrayOf<IIngredient>(iOreDictEntry7, iOreDictEntry23, iOreDictEntry7), arrayOf(iOreDictEntry21, iItemStack19, iOreDictEntry21), arrayOf<IIngredient>(iOreDictEntry10, iOreDictEntry23, iOreDictEntry10)), null)
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("gendustry:ApiaryUpgrade", 21), arrayOf(arrayOf(iOreDictEntry7, iItemStack20, iOreDictEntry7), arrayOf<IIngredient>(iItemStack52, iItemStack19, iItemStack52), arrayOf(iOreDictEntry10, iItemStack18, iOreDictEntry10)), null)
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("gendustry:ApiaryUpgrade", 12), arrayOf(arrayOf(iOreDictEntry7, ItemBracketHandler.getItem("ProjRed|Illumination:projectred.illumination.lamp", 27), iOreDictEntry7), arrayOf<IIngredient>(iItemStack31, iItemStack19, iItemStack31), arrayOf(iOreDictEntry10, iItemStack31, iOreDictEntry10)), null)
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("gendustry:ApiaryUpgrade", 6), arrayOf(arrayOf(iOreDictEntry7, iItemStack20, iOreDictEntry7), arrayOf<IIngredient>(iItemStack59, iItemStack19, iItemStack59), arrayOf(iOreDictEntry10, iItemStack53, iOreDictEntry10)), null)
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("gendustry:ApiaryUpgrade", 15), arrayOf(arrayOf(iOreDictEntry7, iItemStack28, iOreDictEntry7), arrayOf<IIngredient>(iItemStack60, iItemStack19, iItemStack60), arrayOf(iOreDictEntry10, iItemStack28, iOreDictEntry10)), null)
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("gendustry:ApiaryUpgrade", 0), arrayOf(arrayOf(iOreDictEntry7, iItemStack63, iOreDictEntry7), arrayOf<IIngredient>(iItemStack29, iItemStack19, iItemStack29), arrayOf(iOreDictEntry10, iItemStack63, iOreDictEntry10)), null)
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("gendustry:IndustrialGrafter", 100), arrayOf(arrayOf(OreBracketHandler.getOre("screwStainlessSteel"), iItemStack30, OreBracketHandler.getOre("screwStainlessSteel")), arrayOf(OreBracketHandler.getOre("gearGtSmallStainlessSteel"), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32600), OreBracketHandler.getOre("gearGtSmallStainlessSteel")), arrayOf<IIngredient>(OreBracketHandler.getOre("plateStainlessSteel"), OreBracketHandler.getOre("batteryBasic"), OreBracketHandler.getOre("plateStainlessSteel"))), null)
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("gendustry:IndustrialScoop", 100), arrayOf(arrayOf<IIngredient>(OreBracketHandler.getOre("screwStainlessSteel"), iOreDictEntry38, OreBracketHandler.getOre("screwStainlessSteel")), arrayOf(OreBracketHandler.getOre("gearGtSmallStainlessSteel"), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32600), OreBracketHandler.getOre("gearGtSmallStainlessSteel")), arrayOf<IIngredient>(OreBracketHandler.getOre("plateStainlessSteel"), OreBracketHandler.getOre("batteryBasic"), OreBracketHandler.getOre("plateStainlessSteel"))), null)
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("gendustry:ClimateModule", 0), arrayOf(arrayOf<IIngredient>(ItemBracketHandler.getItem("gregtech:gt.comb", 70), iItemStack68, ItemBracketHandler.getItem("gregtech:gt.comb", 77)), arrayOf<IIngredient>(iOreDictEntry35, iOreDictEntry11, iOreDictEntry35), arrayOf<IIngredient>(iItemStack33, iItemStack40, iItemStack33)), null)
        MineTweakerAPI.furnace.addRecipe(ItemBracketHandler.getItem("gendustry:GeneSampleBlank", 0), ItemBracketHandler.getItem("gendustry:GeneSample", 0), 0.0)
        MineTweakerAPI.furnace.addRecipe(ItemBracketHandler.getItem("gendustry:GeneTemplate", 0), ItemBracketHandler.getItem("gendustry:GeneTemplate", 0), 0.0)
        Assembler.addRecipe(iItemStack13.amount(2), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 17500), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 28305), LiquidBracketHandler.getLiquid("molten.glass").withAmount(576), 200, IV)
        Assembler.addRecipe(iItemStack11, ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 17057).amount(4), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 2308), LiquidBracketHandler.getLiquid("molten.glass").withAmount(144), 100, IV)
        Assembler.addRecipe(ItemBracketHandler.getItem("gendustry:GeneTemplate", 0), ItemBracketHandler.getItem("gendustry:GeneSampleBlank", 0).amount(4), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 17500), LiquidBracketHandler.getLiquid("molten.redstone").withAmount(576), 400, IV)
        Assembler.addRecipe(iItemStack16, iItemStack67, ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 18052), LiquidBracketHandler.getLiquid("molten.plutonium").withAmount(576), 300, IV)
        Assembler.addRecipe(iItemStack17, ItemBracketHandler.getItem("dreamcraft:item.GeneticCircuit", 0), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32705), LiquidBracketHandler.getLiquid("mutagen").withAmount(500), 400, IV)
        Assembler.addRecipe(iItemStack17, ItemBracketHandler.getItem("dreamcraft:item.GeneticCircuit", 0), ItemBracketHandler.getItem("gregtech:gt.metaitem.03", 32084), LiquidBracketHandler.getLiquid("mutagen").withAmount(500), 400, IV)
        Assembler.addRecipe(iItemStack17, ItemBracketHandler.getItem("dreamcraft:item.GeneticCircuit", 0), ItemBracketHandler.getItem("gregtech:gt.metaitem.03", 32086), LiquidBracketHandler.getLiquid("mutagen").withAmount(500), 400, IV)
        Assembler.addRecipe(iItemStack17, ItemBracketHandler.getItem("dreamcraft:item.GeneticCircuit", 0), ItemBracketHandler.getItem("gregtech:gt.metaitem.03", 32089), LiquidBracketHandler.getLiquid("mutagen").withAmount(500), 400, IV)
        Assembler.addRecipe(iItemStack18, ItemBracketHandler.getItem("dreamcraft:item.EnvironmentalCircuit", 0), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32705), LiquidBracketHandler.getLiquid("liquiddna").withAmount(500), 400, IV)
        Assembler.addRecipe(iItemStack18, ItemBracketHandler.getItem("dreamcraft:item.EnvironmentalCircuit", 0), ItemBracketHandler.getItem("gregtech:gt.metaitem.03", 32084), LiquidBracketHandler.getLiquid("liquiddna").withAmount(500), 400, IV)
        Assembler.addRecipe(iItemStack18, ItemBracketHandler.getItem("dreamcraft:item.EnvironmentalCircuit", 0), ItemBracketHandler.getItem("gregtech:gt.metaitem.03", 32086), LiquidBracketHandler.getLiquid("liquiddna").withAmount(500), 400, IV)
        Assembler.addRecipe(iItemStack18, ItemBracketHandler.getItem("dreamcraft:item.EnvironmentalCircuit", 0), ItemBracketHandler.getItem("gregtech:gt.metaitem.03", 32089), LiquidBracketHandler.getLiquid("liquiddna").withAmount(500), 400, IV)
        Assembler.addRecipe(iItemStack19, ItemBracketHandler.getItem("dreamcraft:item.IndustryFrame", 0), ItemBracketHandler.getItem("gregtech:gt.metaitem.03", 32087), LiquidBracketHandler.getLiquid("mutagen").withAmount(100), 400, IV)
        Assembler.addRecipe(iItemStack19, ItemBracketHandler.getItem("dreamcraft:item.IndustryFrame", 0), ItemBracketHandler.getItem("gregtech:gt.metaitem.03", 32092), LiquidBracketHandler.getLiquid("mutagen").withAmount(100), 400, IV)
        Assembler.addRecipe(iItemStack19, ItemBracketHandler.getItem("dreamcraft:item.IndustryFrame", 0), ItemBracketHandler.getItem("gregtech:gt.metaitem.03", 32096), LiquidBracketHandler.getLiquid("mutagen").withAmount(100), 400, IV)
        Assembler.addRecipe(iItemStack19, ItemBracketHandler.getItem("dreamcraft:item.IndustryFrame", 0), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32706), LiquidBracketHandler.getLiquid("mutagen").withAmount(100), 400, IV)
        Assembler.addRecipe(ItemBracketHandler.getItem("gendustry:EjectCover", 0), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 17052), ItemBracketHandler.getItem("IC2:upgradeModule", 3), 200, IV)
        Assembler.addRecipe(ItemBracketHandler.getItem("gendustry:ImportCover", 0), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 17052), ItemBracketHandler.getItem("IC2:upgradeModule", 6), 200, IV)
        Assembler.addRecipe(ItemBracketHandler.getItem("gendustry:ErrorSensorCover", 0), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 17052), ItemBracketHandler.getItem("IC2:upgradeModule", 5), 200, IV)
    }
}