package com.github.GTNH2Mega.fromScripts

import fox.spiteful.avaritia.compat.minetweaker.ExtremeCrafting
import minetweaker.MineTweakerAPI
import minetweaker.api.item.IIngredient
import minetweaker.mc1710.brackets.ItemBracketHandler
import minetweaker.mc1710.brackets.OreBracketHandler
import net.minecraftforge.oredict.OreDictionary
import com.github.GTNH2Mega.VoltageLevels

class OpenComputers : Runnable {
    override fun run() {
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("openglasses:openglassesterminal", 0))
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("openglasses:openglasses", OreDictionary.WILDCARD_VALUE))
        ExtremeCrafting.addShaped(ItemBracketHandler.getItem("OpenComputers:item", 69),
                arrayOf(arrayOfNulls(9), arrayOfNulls(9),
                        arrayOf<IIngredient?>(null, null, OreBracketHandler.getOre("circuitMaster"),
                                OreBracketHandler.getOre("circuitMaster"), OreBracketHandler.getOre("circuitMaster"),
                                OreBracketHandler.getOre("circuitMaster"), OreBracketHandler.getOre("circuitMaster"),
                                null, null),
                        arrayOf<IIngredient?>(null, null, OreBracketHandler.getOre("circuitMaster"),
                                OreBracketHandler.getOre("circuitElite"),
                                OreBracketHandler.getOre("circuitSuperconductor"),
                                OreBracketHandler.getOre("circuitElite"), OreBracketHandler.getOre("circuitMaster"),
                                null, null), arrayOf(null, null, OreBracketHandler.getOre("circuitMaster"),
                        ItemBracketHandler.getItem("OpenComputers:item", 103),
                        ItemBracketHandler.getItem("OpenComputers:case3", 0),
                        ItemBracketHandler.getItem("OpenComputers:item", 103),
                        OreBracketHandler.getOre("circuitMaster"), null, null),
                        arrayOf<IIngredient?>(null, null, OreBracketHandler.getOre("circuitMaster"),
                                OreBracketHandler.getOre("circuitElite"),
                                OreBracketHandler.getOre("circuitSuperconductor"),
                                OreBracketHandler.getOre("circuitElite"), OreBracketHandler.getOre("circuitMaster"),
                                null, null),
                        arrayOf<IIngredient?>(null, null, OreBracketHandler.getOre("circuitMaster"),
                                OreBracketHandler.getOre("circuitMaster"), OreBracketHandler.getOre("circuitMaster"),
                                OreBracketHandler.getOre("circuitMaster"), OreBracketHandler.getOre("circuitMaster"),
                                null, null), arrayOfNulls(9), arrayOfNulls(9)))
        ExtremeCrafting.addShaped(ItemBracketHandler.getItem("OpenComputers:item", 103),
                arrayOf(arrayOfNulls(9), arrayOfNulls(9),
                        arrayOf<IIngredient?>(null, null, OreBracketHandler.getOre("circuitElite"),
                                OreBracketHandler.getOre("circuitElite"), OreBracketHandler.getOre("circuitElite"),
                                OreBracketHandler.getOre("circuitElite"), OreBracketHandler.getOre("circuitElite"),
                                null, null), arrayOf<IIngredient?>(null, null, OreBracketHandler.getOre("circuitElite"),
                        OreBracketHandler.getOre("circuitMaster"), OreBracketHandler.getOre("circuitSuperconductor"),
                        OreBracketHandler.getOre("circuitMaster"), OreBracketHandler.getOre("circuitElite"), null,
                        null), arrayOf(null, null, OreBracketHandler.getOre("circuitElite"),
                        ItemBracketHandler.getItem("OpenComputers:item", 10),
                        ItemBracketHandler.getItem("OpenComputers:item", 102),
                        ItemBracketHandler.getItem("OpenComputers:item", 43), OreBracketHandler.getOre("circuitElite"),
                        null, null), arrayOf<IIngredient?>(null, null, OreBracketHandler.getOre("circuitElite"),
                        OreBracketHandler.getOre("circuitMaster"), OreBracketHandler.getOre("circuitSuperconductor"),
                        OreBracketHandler.getOre("circuitMaster"), OreBracketHandler.getOre("circuitElite"), null,
                        null), arrayOf<IIngredient?>(null, null, OreBracketHandler.getOre("circuitElite"),
                        OreBracketHandler.getOre("circuitElite"), OreBracketHandler.getOre("circuitElite"),
                        OreBracketHandler.getOre("circuitElite"), OreBracketHandler.getOre("circuitElite"), null, null),
                        arrayOfNulls(9), arrayOfNulls(9)))
        ExtremeCrafting.addShaped(ItemBracketHandler.getItem("OpenComputers:item", 90),
                arrayOf(arrayOfNulls(9), arrayOfNulls(9),
                        arrayOf<IIngredient?>(null, null, OreBracketHandler.getOre("wireGt16Electrum"),
                                OreBracketHandler.getOre("circuitMaster"),
                                OreBracketHandler.getOre("circuitSuperconductor"),
                                OreBracketHandler.getOre("circuitMaster"), OreBracketHandler.getOre("circuitElite"),
                                null, null),
                        arrayOf<IIngredient?>(null, null, OreBracketHandler.getOre("plateDenseObsidian"),
                                OreBracketHandler.getOre("plateDenseObsidian"),
                                OreBracketHandler.getOre("plateDenseObsidian"),
                                OreBracketHandler.getOre("plateDenseObsidian"),
                                OreBracketHandler.getOre("plateDenseObsidian"), null, null),
                        arrayOf(null, null, OreBracketHandler.getOre("plateDenseObsidian"),
                                ItemBracketHandler.getItem("IC2:itemRTGPellet", 0),
                                ItemBracketHandler.getItem("IC2:blockGenerator", 6),
                                ItemBracketHandler.getItem("IC2:itemRTGPellet", 0),
                                OreBracketHandler.getOre("plateDenseObsidian"), null, null),
                        arrayOf<IIngredient?>(null, null, OreBracketHandler.getOre("plateDenseObsidian"),
                                OreBracketHandler.getOre("plateDenseObsidian"),
                                OreBracketHandler.getOre("plateDenseObsidian"),
                                OreBracketHandler.getOre("plateDenseObsidian"),
                                OreBracketHandler.getOre("plateDenseObsidian"), null, null),
                        arrayOf<IIngredient?>(null, null, OreBracketHandler.getOre("circuitElite"),
                                OreBracketHandler.getOre("circuitMaster"),
                                OreBracketHandler.getOre("circuitSuperconductor"),
                                OreBracketHandler.getOre("circuitMaster"), OreBracketHandler.getOre("wireGt16Electrum"),
                                null, null), arrayOfNulls(9), arrayOfNulls(9)))
        ExtremeCrafting.addShaped(ItemBracketHandler.getItem("OpenComputers:item", 93),
                arrayOf(arrayOfNulls(9), arrayOfNulls(9),
                        arrayOf<IIngredient?>(null, null, OreBracketHandler.getOre("circuitMaster"),
                                OreBracketHandler.getOre("circuitElite"),
                                OreBracketHandler.getOre("circuitSuperconductor"),
                                OreBracketHandler.getOre("circuitElite"), OreBracketHandler.getOre("circuitMaster"),
                                null, null), arrayOf(null, null, OreBracketHandler.getOre("plateDenseChrome"),
                        OreBracketHandler.getOre("plateDenseChrome"),
                        ItemBracketHandler.getItem("OpenComputers:screen3", 0),
                        OreBracketHandler.getOre("plateDenseChrome"), OreBracketHandler.getOre("plateDenseChrome"),
                        null, null), arrayOf(null, null, OreBracketHandler.getOre("plateDenseChrome"),
                        ItemBracketHandler.getItem("IC2:itemRTGPellet", 0),
                        ItemBracketHandler.getItem("IC2:blockGenerator", 6),
                        ItemBracketHandler.getItem("IC2:itemRTGPellet", 0),
                        OreBracketHandler.getOre("plateDenseChrome"), null, null),
                        arrayOf<IIngredient?>(null, null, OreBracketHandler.getOre("plateDenseChrome"),
                                OreBracketHandler.getOre("plateDenseChrome"),
                                OreBracketHandler.getOre("plateDenseChrome"),
                                OreBracketHandler.getOre("plateDenseChrome"),
                                OreBracketHandler.getOre("plateDenseChrome"), null, null),
                        arrayOf<IIngredient?>(null, null, OreBracketHandler.getOre("circuitMaster"),
                                OreBracketHandler.getOre("circuitElite"),
                                OreBracketHandler.getOre("circuitSuperconductor"),
                                OreBracketHandler.getOre("circuitElite"), OreBracketHandler.getOre("circuitMaster"),
                                null, null), arrayOfNulls(9), arrayOfNulls(9)))
        ExtremeCrafting.addShaped(ItemBracketHandler.getItem("OpenComputers:item", 91),
                arrayOf(arrayOfNulls(9), arrayOfNulls(9), arrayOf(null, null, OreBracketHandler.getOre("circuitMaster"),
                        ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32606),
                        OreBracketHandler.getOre("circuitMaster"),
                        ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32606),
                        OreBracketHandler.getOre("circuitMaster"), null, null),
                        arrayOf<IIngredient?>(null, null, OreBracketHandler.getOre("circuitElite"),
                                OreBracketHandler.getOre("turbineBladeChrome"),
                                OreBracketHandler.getOre("circuitSuperconductor"),
                                OreBracketHandler.getOre("turbineBladeChrome"),
                                OreBracketHandler.getOre("circuitElite"), null, null),
                        arrayOf(null, null, ItemBracketHandler.getItem("HardcoreEnderExpansion:biome_compass", 0),
                                OreBracketHandler.getOre("turbineBladeChrome"),
                                ItemBracketHandler.getItem("OpenComputers:item", 90),
                                OreBracketHandler.getOre("turbineBladeChrome"),
                                ItemBracketHandler.getItem("HardcoreEnderExpansion:biome_compass", 0), null, null),
                        arrayOf<IIngredient?>(null, null, OreBracketHandler.getOre("circuitElite"),
                                OreBracketHandler.getOre("turbineBladeChrome"),
                                OreBracketHandler.getOre("circuitSuperconductor"),
                                OreBracketHandler.getOre("turbineBladeChrome"),
                                OreBracketHandler.getOre("circuitElite"), null, null),
                        arrayOf(null, null, OreBracketHandler.getOre("circuitMaster"),
                                ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32606),
                                OreBracketHandler.getOre("circuitMaster"),
                                ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32606),
                                OreBracketHandler.getOre("circuitMaster"), null, null), arrayOfNulls(9),
                        arrayOfNulls(9)))
        ExtremeCrafting.addShaped(ItemBracketHandler.getItem("OpenComputers:item", 114),
                arrayOf(arrayOf<IIngredient>(ItemBracketHandler.getItem("OpenComputers:item", 72),
                        ItemBracketHandler.getItem("OpenComputers:item", 72),
                        ItemBracketHandler.getItem("OpenComputers:item", 72),
                        ItemBracketHandler.getItem("OpenComputers:item", 72),
                        ItemBracketHandler.getItem("OpenComputers:item", 72),
                        ItemBracketHandler.getItem("OpenComputers:item", 72),
                        ItemBracketHandler.getItem("OpenComputers:item", 72),
                        ItemBracketHandler.getItem("OpenComputers:item", 72),
                        ItemBracketHandler.getItem("OpenComputers:item", 72)),
                        arrayOf<IIngredient>(ItemBracketHandler.getItem("OpenComputers:item", 72),
                                ItemBracketHandler.getItem("OpenComputers:item", 39),
                                ItemBracketHandler.getItem("OpenComputers:item", 72),
                                ItemBracketHandler.getItem("OpenComputers:item", 26),
                                ItemBracketHandler.getItem("OpenComputers:item", 106),
                                ItemBracketHandler.getItem("OpenComputers:item", 26),
                                ItemBracketHandler.getItem("OpenComputers:item", 72),
                                ItemBracketHandler.getItem("OpenComputers:item", 39),
                                ItemBracketHandler.getItem("OpenComputers:item", 72)),
                        arrayOf<IIngredient>(ItemBracketHandler.getItem("OpenComputers:item", 72),
                                ItemBracketHandler.getItem("OpenComputers:item", 72),
                                ItemBracketHandler.getItem("OpenComputers:item", 72),
                                ItemBracketHandler.getItem("OpenComputers:item", 72),
                                ItemBracketHandler.getItem("OpenComputers:item", 72),
                                ItemBracketHandler.getItem("OpenComputers:item", 72),
                                ItemBracketHandler.getItem("OpenComputers:item", 72),
                                ItemBracketHandler.getItem("OpenComputers:item", 72),
                                ItemBracketHandler.getItem("OpenComputers:item", 72)),
                        arrayOf(ItemBracketHandler.getItem("OpenComputers:item", 72),
                                ItemBracketHandler.getItem("OpenComputers:item", 39),
                                ItemBracketHandler.getItem("OpenComputers:item", 72),
                                ItemBracketHandler.getItem("gregtech:gt.metaitem.03", 32105),
                                OreBracketHandler.getOre("circuitSuperconductor"),
                                ItemBracketHandler.getItem("gregtech:gt.metaitem.03", 32105),
                                ItemBracketHandler.getItem("OpenComputers:item", 72),
                                ItemBracketHandler.getItem("OpenComputers:item", 39),
                                ItemBracketHandler.getItem("OpenComputers:item", 72)),
                        arrayOf<IIngredient>(ItemBracketHandler.getItem("OpenComputers:item", 72),
                                ItemBracketHandler.getItem("OpenComputers:item", 72),
                                ItemBracketHandler.getItem("OpenComputers:item", 72),
                                ItemBracketHandler.getItem("OpenComputers:item", 72),
                                ItemBracketHandler.getItem("OpenComputers:item", 7),
                                ItemBracketHandler.getItem("OpenComputers:item", 72),
                                ItemBracketHandler.getItem("OpenComputers:item", 72),
                                ItemBracketHandler.getItem("OpenComputers:item", 72),
                                ItemBracketHandler.getItem("OpenComputers:item", 72)),
                        arrayOf(ItemBracketHandler.getItem("OpenComputers:item", 72),
                                ItemBracketHandler.getItem("OpenComputers:item", 39),
                                ItemBracketHandler.getItem("OpenComputers:item", 72),
                                ItemBracketHandler.getItem("gregtech:gt.metaitem.03", 32105),
                                OreBracketHandler.getOre("circuitSuperconductor"),
                                ItemBracketHandler.getItem("gregtech:gt.metaitem.03", 32105),
                                ItemBracketHandler.getItem("OpenComputers:item", 72),
                                ItemBracketHandler.getItem("OpenComputers:item", 39),
                                ItemBracketHandler.getItem("OpenComputers:item", 72)),
                        arrayOf<IIngredient>(ItemBracketHandler.getItem("OpenComputers:item", 72),
                                ItemBracketHandler.getItem("OpenComputers:item", 72),
                                ItemBracketHandler.getItem("OpenComputers:item", 72),
                                ItemBracketHandler.getItem("OpenComputers:item", 72),
                                ItemBracketHandler.getItem("OpenComputers:item", 72),
                                ItemBracketHandler.getItem("OpenComputers:item", 72),
                                ItemBracketHandler.getItem("OpenComputers:item", 72),
                                ItemBracketHandler.getItem("OpenComputers:item", 72),
                                ItemBracketHandler.getItem("OpenComputers:item", 72)),
                        arrayOf<IIngredient>(ItemBracketHandler.getItem("OpenComputers:item", 72),
                                ItemBracketHandler.getItem("OpenComputers:item", 39),
                                ItemBracketHandler.getItem("OpenComputers:item", 72),
                                ItemBracketHandler.getItem("OpenComputers:item", 26),
                                ItemBracketHandler.getItem("OpenComputers:item", 106),
                                ItemBracketHandler.getItem("OpenComputers:item", 26),
                                ItemBracketHandler.getItem("OpenComputers:item", 72),
                                ItemBracketHandler.getItem("OpenComputers:item", 39),
                                ItemBracketHandler.getItem("OpenComputers:item", 72)),
                        arrayOf<IIngredient>(ItemBracketHandler.getItem("OpenComputers:item", 72),
                                ItemBracketHandler.getItem("OpenComputers:item", 72),
                                ItemBracketHandler.getItem("OpenComputers:item", 72),
                                ItemBracketHandler.getItem("OpenComputers:item", 72),
                                ItemBracketHandler.getItem("OpenComputers:item", 72),
                                ItemBracketHandler.getItem("OpenComputers:item", 72),
                                ItemBracketHandler.getItem("OpenComputers:item", 72),
                                ItemBracketHandler.getItem("OpenComputers:item", 72),
                                ItemBracketHandler.getItem("OpenComputers:item", 72))))
    }
}