package com.github.GTNH2Mega.fromScripts;
import java.util.HashMap;
import minetweaker.MineTweakerAPI;
import minetweaker.api.data.IData;
import minetweaker.api.item.IIngredient;
import minetweaker.api.item.IItemStack;
import minetweaker.expand.ExpandAnyArray;
import minetweaker.expand.ExpandAnyDict;
import minetweaker.expand.ExpandByte;
import minetweaker.mc1710.brackets.ItemBracketHandler;
import minetweaker.mc1710.brackets.OreBracketHandler;
import minetweaker.mods.ic2.machines.Compressor;
import modtweaker2.mods.thaumcraft.handlers.Arcane;
import modtweaker2.mods.thaumcraft.handlers.Crucible;
import modtweaker2.mods.thaumcraft.handlers.Infusion;
import modtweaker2.mods.thaumcraft.handlers.Research;
import modtweaker2.mods.thaumcraft.handlers.Warp;
import static com.github.GTNH2Mega.VoltageLevels.*;
public class Thaumcraft05Golemancy
implements Runnable {
    public void run() {
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:blockChestHungry", (int)0));
        Infusion.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:TrunkSpawner", (int)0));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:blockCosmeticSolid", (int)9));
        Crucible.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemPlacer", (int)32767));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemCore", (int)100));
        Crucible.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemCore", (int)2));
        Crucible.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemCore", (int)1));
        Crucible.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemCore", (int)0));
        Crucible.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemCore", (int)3));
        Crucible.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemCore", (int)4));
        Infusion.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemCore", (int)8));
        Infusion.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemCore", (int)10));
        Crucible.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemCore", (int)5));
        Infusion.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemCore", (int)6));
        Crucible.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemCore", (int)9));
        Infusion.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemCore", (int)11));
        Infusion.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemCore", (int)7));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemUpgrade", (int)0));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemUpgrade", (int)1));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemUpgrade", (int)2));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemUpgrade", (int)3));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemUpgrade", (int)4));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemUpgrade", (int)5));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemDecoration", (int)0));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemDecoration", (int)1));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemDecoration", (int)2));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemDecoration", (int)3));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemDecoration", (int)4));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemDecoration", (int)5));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemDecoration", (int)6));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemDecoration", (int)7));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:blockTaint", (int)2));
        Arcane.addShaped((String)"HUNGRYCHEST", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:blockChestHungry", (int)0), (String)"aer 10, terra 10, ordo 5, perditio 5", (IIngredient[][])new IIngredient[][]{{OreBracketHandler.getOre((String)"screwThaumium"), ItemBracketHandler.getItem((String)"Thaumcraft:blockMetalDevice", (int)5), OreBracketHandler.getOre((String)"screwThaumium")}, {ItemBracketHandler.getItem((String)"Thaumcraft:ItemZombieBrain", (int)0), OreBracketHandler.getOre((String)"chestWood"), ItemBracketHandler.getItem((String)"Thaumcraft:ItemZombieBrain", (int)0)}, {OreBracketHandler.getOre((String)"screwThaumium"), OreBracketHandler.getOre((String)"craftingToolScrewdriver"), OreBracketHandler.getOre((String)"screwThaumium")}});
        Research.setAspects((String)"HUNGRYCHEST", (String)"fames 9, vacuos 6, iter 3");
        Research.setComplexity((String)"HUNGRYCHEST", (int)1);
        Infusion.addRecipe((String)"TRAVELTRUNK", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:blockChestHungry", (int)0), (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)17306), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)28306), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)27306), ItemBracketHandler.getItem((String)"Thaumcraft:blockWoodenDevice", (int)6), ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemPlacer", (int)1), ItemBracketHandler.getItem((String)"Thaumcraft:blockWoodenDevice", (int)6), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)27306), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)28306)}, (String)"iter 16, motus 16, spiritus 16, vacuos 32", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:TrunkSpawner", (int)0), (int)4);
        Research.setAspects((String)"TRAVELTRUNK", (String)"spiritus 12, vacuos 12, arbor 9, iter 6, terra 3");
        Research.setComplexity((String)"TRAVELTRUNK", (int)3);
        Arcane.addShaped((String)"GOLEMFETTER", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:blockCosmeticSolid", (int)9), (String)"terra 15, ordo 15", (IIngredient[][])new IIngredient[][]{{ItemBracketHandler.getItem((String)"Thaumcraft:blockCosmeticSolid", (int)6), ItemBracketHandler.getItem((String)"Thaumcraft:blockCosmeticSolid", (int)6), ItemBracketHandler.getItem((String)"Thaumcraft:blockCosmeticSolid", (int)6)}, {OreBracketHandler.getOre((String)"plateThaumium"), OreBracketHandler.getOre((String)"blockRedstone"), OreBracketHandler.getOre((String)"plateThaumium")}, {ItemBracketHandler.getItem((String)"Thaumcraft:blockCosmeticSolid", (int)6), ItemBracketHandler.getItem((String)"Thaumcraft:blockCosmeticSolid", (int)7), ItemBracketHandler.getItem((String)"Thaumcraft:blockCosmeticSolid", (int)6)}});
        Research.setAspects((String)"GOLEMFETTER", (String)"vinculum 9, machina 9, cognitio 6, praecantatio 3");
        Research.setComplexity((String)"GOLEMFETTER", (int)2);
        Crucible.addRecipe((String)"GOLEMSTRAW", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemPlacer", (int)0), (IIngredient)ItemBracketHandler.getItem((String)"minecraft:hay_block", (int)0), (String)"humanus 10, motus 10, spiritus 10");
        Research.setAspects((String)"GOLEMSTRAW", (String)"messis 9, permutatio 9, spiritus 9, motus 6, praecantatio 3");
        Research.setComplexity((String)"GOLEMSTRAW", (int)2);
        Crucible.addRecipe((String)"GOLEMWOOD", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemPlacer", (int)1), (IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:blockMagicalLog", (int)0), (String)"humanus 14, motus 14, spiritus 14");
        Research.setAspects((String)"GOLEMWOOD", (String)"arbor 12, permutatio 12, spiritus 9, motus 6, praecantatio 3");
        Research.setComplexity((String)"GOLEMWOOD", (int)3);
        Research.clearPages((String)"GOLEMTALLOW");
        Research.addPage((String)"GOLEMTALLOW", (String)"tc.research_page.GOLEMTALLOW.1");
        Crucible.addRecipe((String)"GOLEMTALLOW", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemPlacer", (int)2), (IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:blockCosmeticSolid", (int)5), (String)"humanus 26, mortuus 26, spiritus 26");
        Research.addCruciblePage((String)"GOLEMTALLOW", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemPlacer", (int)2));
        Research.setAspects((String)"GOLEMTALLOW", (String)"spiritus 12, permutatio 12, corpus 12, motus 9, praecantatio 6, corpus 3");
        Research.setComplexity((String)"GOLEMTALLOW", (int)3);
        Crucible.addRecipe((String)"GOLEMCLAY", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemPlacer", (int)3), (IIngredient)ItemBracketHandler.getItem((String)"minecraft:clay", (int)0), (String)"humanus 20, motus 20, spiritus 20");
        Research.setAspects((String)"GOLEMCLAY", (String)"spiritus 12, permutatio 12, motus 12, terra 9, praecantatio 6, aqua 3");
        Research.setComplexity((String)"GOLEMCLAY", (int)3);
        Research.clearPages((String)"GOLEMFLESH");
        Research.addPage((String)"GOLEMFLESH", (String)"tc.research_page.GOLEMFLESH.1");
        Crucible.addRecipe((String)"GOLEMFLESH", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemPlacer", (int)4), (IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:blockTaint", (int)2), (String)"humanus 20, motus 20, spiritus 20");
        Research.addCruciblePage((String)"GOLEMFLESH", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemPlacer", (int)4));
        Research.setAspects((String)"GOLEMFLESH", (String)"corpus 12, permutatio 12, spiritus 12, motus 9, praecantatio 6, mortuus 3");
        Research.setComplexity((String)"GOLEMFLESH", (int)3);
        Crucible.addRecipe((String)"GOLEMSTONE", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemPlacer", (int)5), (IIngredient)ItemBracketHandler.getItem((String)"ExtraUtilities:cobblestone_compressed", (int)0), (String)"humanus 26, mortuus 26, spiritus 26");
        Research.setAspects((String)"GOLEMSTONE", (String)"spiritus 12, permutatio 12, motus 12, terra 9, praecantatio 6, perditio 3");
        Research.setComplexity((String)"GOLEMSTONE", (int)3);
        Crucible.addRecipe((String)"GOLEMIRON", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemPlacer", (int)6), (IIngredient)ItemBracketHandler.getItem((String)"minecraft:iron_block", (int)0), (String)"humanus 32, mortuus 32, spiritus 32");
        Research.setAspects((String)"GOLEMIRON", (String)"permutatio 12, spiritus 12, motus 12, metallum 9, praecantatio 9, terra 6, humanus 3");
        Research.setComplexity((String)"GOLEMIRON", (int)3);
        Research.clearPages((String)"GOLEMTHAUMIUM");
        Research.addPage((String)"GOLEMTHAUMIUM", (String)"tc.research_page.GOLEMTHAUMIUM.1");
        Crucible.addRecipe((String)"GOLEMTHAUMIUM", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemPlacer", (int)7), (IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:blockCosmeticSolid", (int)4), (String)"humanus 40, mortuus 40, spiritus 40");
        Research.addCruciblePage((String)"GOLEMTHAUMIUM", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemPlacer", (int)7));
        Research.setAspects((String)"GOLEMTHAUMIUM", (String)"permutatio 12, spiritus 12, metallum 12, motus 9, praecantatio 9, terra 9, humanus 6, alienis 3");
        Research.setComplexity((String)"GOLEMTHAUMIUM", (int)3);
        Research.setAspects((String)"ADVANCEDGOLEM", (String)"sensus 15, victus 15, cognitio 12, potentia 12, praecantatio 12, alienis 9, motus 6, terra 3");
        Research.setComplexity((String)"ADVANCEDGOLEM", (int)4);
        Arcane.addShaped((String)"COREGATHER", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemCore", (int)100), (String)"ordo 5, ignis 5, terra 5", (IIngredient[][])new IIngredient[][]{{OreBracketHandler.getOre((String)"plateThaumium"), OreBracketHandler.getOre((String)"ingotBrickNether"), OreBracketHandler.getOre((String)"plateThaumium")}, {OreBracketHandler.getOre((String)"ingotBrick"), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)1), OreBracketHandler.getOre((String)"ingotBrick")}, {OreBracketHandler.getOre((String)"plateNetherQuartz"), OreBracketHandler.getOre((String)"ingotBrickNether"), OreBracketHandler.getOre((String)"plateNetherQuartz")}});
        Crucible.addRecipe((String)"COREGATHER", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemCore", (int)2), (IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemCore", (int)100), (String)"lucrum 10, terra 10");
        Crucible.addRecipe((String)"COREEMPTY", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemCore", (int)1), (IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemCore", (int)100), (String)"lucrum 10, vacuos 10");
        Research.setAspects((String)"COREEMPTY", (String)"lucrum 9, vacuos 9, permutatio 6, motus 6, praecantatio 3");
        Research.setComplexity((String)"COREEMPTY", (int)2);
        Crucible.addRecipe((String)"COREFILL", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemCore", (int)0), (IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemCore", (int)100), (String)"fames 10, vacuos 10");
        Research.setAspects((String)"COREFILL", (String)"fames 9, vacuos 9, permutatio 9, motus 6, praecantatio 3");
        Research.setComplexity((String)"COREFILL", (int)2);
        Research.clearPages((String)"COREHARVEST");
        Research.addPage((String)"COREHARVEST", (String)"tc.research_page.COREHARVEST.1");
        Infusion.addRecipe((String)"COREHARVEST", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemCore", (int)100), (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"minecraft:nether_star", (int)0), ItemBracketHandler.getItem((String)"minecraft:wheat_seeds", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:ItemHoeThaumium", (int)0), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)17086)}, (String)"messis 10, meto 10, herba 20", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemCore", (int)3), (int)4);
        Research.addInfusionPage((String)"COREHARVEST", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemCore", (int)3));
        Research.addPage((String)"COREHARVEST", (String)"tc.research_page.COREHARVEST.2");
        Research.setAspects((String)"COREHARVEST", (String)"meto 12, messis 12, iter 9, permutatio 9, motus 6, praecantatio 3");
        Research.setComplexity((String)"COREHARVEST", (int)3);
        Research.clearPages((String)"COREGUARD");
        Research.addPage((String)"COREGUARD", (String)"tc.research_page.COREGUARD.1");
        Infusion.addRecipe((String)"COREGUARD", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemCore", (int)100), (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"minecraft:nether_star", (int)0), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)17804), ItemBracketHandler.getItem((String)"Thaumcraft:ItemSwordThaumium", (int)0), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)17086)}, (String)"telum 20, vinculum 20, tutamen 20", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemCore", (int)4), (int)4);
        Research.addInfusionPage((String)"COREGUARD", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemCore", (int)4));
        Research.addPage((String)"COREGUARD", (String)"tc.research_page.COREGUARD.2");
        Research.setAspects((String)"COREGUARD", (String)"sensus 12, telum 12, vinculum 12, permutatio 9, motus 6, praecantatio 3");
        Research.setComplexity((String)"COREGUARD", (int)3);
        Infusion.addRecipe((String)"COREUSE", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemCore", (int)1), (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"minecraft:nether_star", (int)0), ItemBracketHandler.getItem((String)"ProjRed|Integration:projectred.integration.gate", (int)26), ItemBracketHandler.getItem((String)"minecraft:lever", (int)0), ItemBracketHandler.getItem((String)"minecraft:flint_and_steel", (int)32767), ItemBracketHandler.getItem((String)"minecraft:stone_pressure_plate", (int)0), ItemBracketHandler.getItem((String)"minecraft:shears", (int)0)}, (String)"humanus 20, instrumentum 20, machina 20, lucrum 20", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemCore", (int)8), (int)4);
        Research.setAspects((String)"COREUSE", (String)"humanus 12, instrumentum 12, machina 9, permutatio 9, motus 6, praecantatio 3");
        Research.setComplexity((String)"COREUSE", (int)3);
        Infusion.addRecipe((String)"CORESORTING", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemCore", (int)100), (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"minecraft:nether_star", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemCore", (int)1), ItemBracketHandler.getItem((String)"minecraft:paper", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:ItemZombieBrain", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemCore", (int)0), ItemBracketHandler.getItem((String)"ProjRed|Integration:projectred.integration.gate", (int)26)}, (String)"lucrum 20, fames 20, permutatio 20, vacuos 20", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemCore", (int)10), (int)4);
        Research.setAspects((String)"CORESORTING", (String)"fames 12, vacuos 12, lucrum 12, permutatio 9, motus 6, praecantatio 3");
        Research.setComplexity((String)"CORESORTING", (int)3);
        Research.clearPages((String)"CORELIQUID");
        Research.addPage((String)"CORELIQUID", (String)"tc.research_page.CORELIQUID.1");
        Infusion.addRecipe((String)"CORELIQUID", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemCore", (int)0), (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"minecraft:nether_star", (int)0), ItemBracketHandler.getItem((String)"BuildCraft|Factory:tankBlock", (int)0), ItemBracketHandler.getItem((String)"IguanaTweaksTConstruct:clayBucketFired", (int)0), ItemBracketHandler.getItem((String)"minecraft:bucket", (int)0), ItemBracketHandler.getItem((String)"Forestry:canEmpty", (int)0), ItemBracketHandler.getItem((String)"IC2:itemFluidCell", (int)0)}, (String)"aqua 20, vacuos 20, metallum 20, iter 20", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemCore", (int)5), (int)4);
        Research.addInfusionPage((String)"CORELIQUID", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemCore", (int)5));
        Research.addPage((String)"CORELIQUID", (String)"tc.research_page.CORELIQUID.2");
        Research.setAspects((String)"CORELIQUID", (String)"iter 12, aqua 12, metallum 9, permutatio 9, motus 6, praecantatio 3");
        Research.setComplexity((String)"CORELIQUID", (int)3);
        Infusion.addRecipe((String)"COREALCHEMY", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemCore", (int)5), (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"minecraft:nether_star", (int)0), ItemBracketHandler.getItem((String)"minecraft:potion", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:blockJar", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:ItemEssence", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:ItemZombieBrain", (int)0), ItemBracketHandler.getItem((String)"minecraft:potion", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:ItemEssence", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:blockJar", (int)0)}, (String)"aqua 32, motus 32, praecantatio 32, permutatio 32", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemCore", (int)6), (int)7);
        Research.setAspects((String)"COREALCHEMY", (String)"potentia 12, aqua 12, iter 12, praecantatio 9, motus 6, alienis 3");
        Research.setComplexity((String)"COREALCHEMY", (int)3);
        Research.clearPages((String)"COREBUTCHER");
        Research.addPage((String)"COREBUTCHER", (String)"tc.research_page.COREBUTCHER.1");
        Infusion.addRecipe((String)"COREBUTCHER", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemCore", (int)3), (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"minecraft:nether_star", (int)0), ItemBracketHandler.getItem((String)"gregtech:gt.metatool.01", (int)36), ItemBracketHandler.getItem((String)"minecraft:iron_sword", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:ItemZombieBrain", (int)0), ItemBracketHandler.getItem((String)"minecraft:bow", (int)0), ItemBracketHandler.getItem((String)"minecraft:arrow", (int)0)}, (String)"bestia 32, corpus 32, mortuus 32, telum 32", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemCore", (int)9), (int)7);
        Research.addInfusionPage((String)"COREBUTCHER", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemCore", (int)9));
        Research.setAspects((String)"COREBUTCHER", (String)"meto 12, telum 12, bestia 9, sensus 12, motus 6, praecantatio 3");
        Research.setComplexity((String)"COREBUTCHER", (int)3);
        Warp.addToResearch((String)"COREBUTCHER", (int)2);
        Infusion.addRecipe((String)"COREFISHING", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemCore", (int)3), (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"minecraft:nether_star", (int)0), ItemBracketHandler.getItem((String)"minecraft:fish", (int)0), ItemBracketHandler.getItem((String)"minecraft:fish", (int)2), ItemBracketHandler.getItem((String)"minecraft:fish", (int)3), ItemBracketHandler.getItem((String)"minecraft:fishing_rod", (int)0), ItemBracketHandler.getItem((String)"gregtech:gt.metatool.01", (int)34)}, (String)"aqua 32, meto 20, bestia 32, fames 32", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemCore", (int)11), (int)7);
        Research.setAspects((String)"COREFISHING", (String)"fames 12, aqua 12, bestia 12, meto 9, motus 6, praecantatio 3");
        Research.setComplexity((String)"COREFISHING", (int)3);
        Infusion.addRecipe((String)"CORELUMBER", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemCore", (int)3), (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"minecraft:nether_star", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:ItemAxeThaumium", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:ItemAxeElemental", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:ItemZombieBrain", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:ItemAxeThaumium", (int)0)}, (String)"arbor 32, instrumentum 32, meto 20, potentia 32", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemCore", (int)7), (int)7);
        Research.setAspects((String)"CORELUMBER", (String)"potentia 12, arbor 12, instrumentum 9, meto 12, motus 6, praecantatio 3");
        Research.setComplexity((String)"CORELUMBER", (int)3);
        Research.clearPages((String)"GOLEMBELL");
        Research.addPage((String)"GOLEMBELL", (String)"tc.research_page.GOLEMBELL.1");
        Research.addPage((String)"GOLEMBELL", (String)"tc.research_page.GOLEMBELL.2");
        IItemStack iItemStack = ItemBracketHandler.getItem((String)"Thaumcraft:GolemBell", (int)0);
        HashMap<String, IData> hashMap = new HashMap<String, IData>();
        IData[] arriData = new IData[1];
        HashMap<String, IData> hashMap2 = new HashMap<String, IData>();
        hashMap2.put("side", ExpandByte.asData((byte)1));
        arriData[0] = ExpandAnyDict.asData(hashMap2);
        hashMap.put("markers", ExpandAnyArray.asData((IData[])arriData));
        Arcane.addShaped((String)"GOLEMBELL", (IItemStack)iItemStack.withTag(ExpandAnyDict.asData(hashMap)), (String)"ordo 10, aer 5", (IIngredient[][])new IIngredient[][]{{OreBracketHandler.getOre((String)"craftingToolScrewdriver"), OreBracketHandler.getOre((String)"plateNetherQuartz"), OreBracketHandler.getOre((String)"boltNetherQuartz")}, {OreBracketHandler.getOre((String)"screwIron"), OreBracketHandler.getOre((String)"plateNetherQuartz"), OreBracketHandler.getOre((String)"plateNetherQuartz")}, {OreBracketHandler.getOre((String)"stickWoodSealed"), OreBracketHandler.getOre((String)"screwIron"), OreBracketHandler.getOre((String)"craftingToolFile")}});
        IItemStack iItemStack2 = ItemBracketHandler.getItem((String)"Thaumcraft:GolemBell", (int)0);
        HashMap<String, IData> hashMap3 = new HashMap<String, IData>();
        IData[] arriData2 = new IData[1];
        HashMap<String, IData> hashMap4 = new HashMap<String, IData>();
        hashMap4.put("side", ExpandByte.asData((byte)1));
        arriData2[0] = ExpandAnyDict.asData(hashMap4);
        hashMap3.put("markers", ExpandAnyArray.asData((IData[])arriData2));
        Research.addArcanePage((String)"GOLEMBELL", (IItemStack)iItemStack2.withTag(ExpandAnyDict.asData(hashMap3)));
        Arcane.addShaped((String)"UPGRADEAIR", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemUpgrade", (int)0), (String)"aer 15, ordo 5", (IIngredient[][])new IIngredient[][]{{OreBracketHandler.getOre((String)"nuggetGold"), ItemBracketHandler.getItem((String)"Thaumcraft:ItemNugget", (int)5), OreBracketHandler.getOre((String)"nuggetGold")}, {OreBracketHandler.getOre((String)"nuggetThaumium"), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)0), OreBracketHandler.getOre((String)"nuggetThaumium")}, {OreBracketHandler.getOre((String)"nuggetGold"), ItemBracketHandler.getItem((String)"Thaumcraft:ItemNugget", (int)5), OreBracketHandler.getOre((String)"nuggetGold")}});
        Research.setAspects((String)"UPGRADEAIR", (String)"motus 9, aer 6, praecantatio 3");
        Research.setComplexity((String)"UPGRADEAIR", (int)2);
        Arcane.addShaped((String)"UPGRADEEARTH", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemUpgrade", (int)1), (String)"terra 15, ordo 5", (IIngredient[][])new IIngredient[][]{{OreBracketHandler.getOre((String)"nuggetGold"), ItemBracketHandler.getItem((String)"Thaumcraft:ItemNugget", (int)5), OreBracketHandler.getOre((String)"nuggetGold")}, {OreBracketHandler.getOre((String)"nuggetThaumium"), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)3), OreBracketHandler.getOre((String)"nuggetThaumium")}, {OreBracketHandler.getOre((String)"nuggetGold"), ItemBracketHandler.getItem((String)"Thaumcraft:ItemNugget", (int)5), OreBracketHandler.getOre((String)"nuggetGold")}});
        Research.setAspects((String)"UPGRADEEARTH", (String)"victus 9, terra 6, praecantatio 3");
        Research.setComplexity((String)"UPGRADEEARTH", (int)2);
        Arcane.addShaped((String)"UPGRADEFIRE", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemUpgrade", (int)2), (String)"ignis 15, ordo 5", (IIngredient[][])new IIngredient[][]{{OreBracketHandler.getOre((String)"nuggetGold"), ItemBracketHandler.getItem((String)"Thaumcraft:ItemNugget", (int)5), OreBracketHandler.getOre((String)"nuggetGold")}, {OreBracketHandler.getOre((String)"nuggetThaumium"), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)1), OreBracketHandler.getOre((String)"nuggetThaumium")}, {OreBracketHandler.getOre((String)"nuggetGold"), ItemBracketHandler.getItem((String)"Thaumcraft:ItemNugget", (int)5), OreBracketHandler.getOre((String)"nuggetGold")}});
        Research.setAspects((String)"UPGRADEFIRE", (String)"potentia 9, ignis 6, praecantatio 3");
        Research.setComplexity((String)"UPGRADEFIRE", (int)2);
        Arcane.addShaped((String)"UPGRADEWATER", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemUpgrade", (int)3), (String)"aqua 15, ordo 5", (IIngredient[][])new IIngredient[][]{{OreBracketHandler.getOre((String)"nuggetGold"), ItemBracketHandler.getItem((String)"Thaumcraft:ItemNugget", (int)5), OreBracketHandler.getOre((String)"nuggetGold")}, {OreBracketHandler.getOre((String)"nuggetThaumium"), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)2), OreBracketHandler.getOre((String)"nuggetThaumium")}, {OreBracketHandler.getOre((String)"nuggetGold"), ItemBracketHandler.getItem((String)"Thaumcraft:ItemNugget", (int)5), OreBracketHandler.getOre((String)"nuggetGold")}});
        Research.setAspects((String)"UPGRADEWATER", (String)"sensus 9, aqua 6, praecantatio 3");
        Research.setComplexity((String)"UPGRADEWATER", (int)2);
        Arcane.addShaped((String)"UPGRADEORDER", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemUpgrade", (int)4), (String)"ordo 20", (IIngredient[][])new IIngredient[][]{{OreBracketHandler.getOre((String)"nuggetGold"), ItemBracketHandler.getItem((String)"Thaumcraft:ItemNugget", (int)5), OreBracketHandler.getOre((String)"nuggetGold")}, {OreBracketHandler.getOre((String)"nuggetThaumium"), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)4), OreBracketHandler.getOre((String)"nuggetThaumium")}, {OreBracketHandler.getOre((String)"nuggetGold"), ItemBracketHandler.getItem((String)"Thaumcraft:ItemNugget", (int)5), OreBracketHandler.getOre((String)"nuggetGold")}});
        Research.setAspects((String)"UPGRADEORDER", (String)"cognitio 6, ordo 9, praecantatio 3");
        Research.setComplexity((String)"UPGRADEORDER", (int)2);
        Arcane.addShaped((String)"UPGRADEENTROPY", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemUpgrade", (int)5), (String)"perditio 15, ordo 5", (IIngredient[][])new IIngredient[][]{{OreBracketHandler.getOre((String)"nuggetGold"), ItemBracketHandler.getItem((String)"Thaumcraft:ItemNugget", (int)5), OreBracketHandler.getOre((String)"nuggetGold")}, {OreBracketHandler.getOre((String)"nuggetThaumium"), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)5), OreBracketHandler.getOre((String)"nuggetThaumium")}, {OreBracketHandler.getOre((String)"nuggetGold"), ItemBracketHandler.getItem((String)"Thaumcraft:ItemNugget", (int)5), OreBracketHandler.getOre((String)"nuggetGold")}});
        Research.setAspects((String)"UPGRADEENTROPY", (String)"cognitio 6, perditio 9, praecantatio 3");
        Research.setComplexity((String)"UPGRADEENTROPY", (int)2);
        Arcane.addShaped((String)"TINYHAT", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemDecoration", (int)0), (String)"ordo 10, ignis 10, terra 5", (IIngredient[][])new IIngredient[][]{{null, OreBracketHandler.getOre((String)"blockWoolBlack"), null}, {OreBracketHandler.getOre((String)"foilGold"), OreBracketHandler.getOre((String)"foilGold"), OreBracketHandler.getOre((String)"foilGold")}, {OreBracketHandler.getOre((String)"blockWoolBlack"), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)7), OreBracketHandler.getOre((String)"blockWoolBlack")}});
        Research.setAspects((String)"TINYHAT", (String)"lucrum 9, pannus 9, victus 6, sano 3");
        Research.setComplexity((String)"TINYHAT", (int)2);
        Arcane.addShaped((String)"TINYGLASSES", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemDecoration", (int)1), (String)"aer 5, aqua 5, ordo 5", (IIngredient[][])new IIngredient[][]{{OreBracketHandler.getOre((String)"stickIron"), null, OreBracketHandler.getOre((String)"stickIron")}, {OreBracketHandler.getOre((String)"screwIron"), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)7), OreBracketHandler.getOre((String)"screwIron")}, {OreBracketHandler.getOre((String)"lensGlass"), OreBracketHandler.getOre((String)"boltIron"), OreBracketHandler.getOre((String)"lensGlass")}});
        Research.setAspects((String)"TINYGLASSES", (String)"lucrum 9, pannus 6, sensus 6, ordo 3");
        Research.setComplexity((String)"TINYGLASSES", (int)2);
        Arcane.addShaped((String)"TINYBOWTIE", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemDecoration", (int)2), (String)"ordo 5, aer 5, terra 5", (IIngredient[][])new IIngredient[][]{{null, null, null}, {OreBracketHandler.getOre((String)"blockWoolBlack"), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)7), OreBracketHandler.getOre((String)"blockWoolBlack")}, {OreBracketHandler.getOre((String)"blockWoolBlack"), null, OreBracketHandler.getOre((String)"blockWoolBlack")}});
        Research.setAspects((String)"TINYBOWTIE", (String)"lucrum 9, pannus 9, iter 6, potentia 3");
        Research.setComplexity((String)"TINYBOWTIE", (int)2);
        Arcane.addShaped((String)"TINYFEZ", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemDecoration", (int)3), (String)"aer 5, aqua 5, terra 5", (IIngredient[][])new IIngredient[][]{{OreBracketHandler.getOre((String)"blockWoolRed"), OreBracketHandler.getOre((String)"blockWoolRed"), ItemBracketHandler.getItem((String)"minecraft:string", (int)0)}, {OreBracketHandler.getOre((String)"blockWoolRed"), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)7), ItemBracketHandler.getItem((String)"minecraft:string", (int)0)}, {OreBracketHandler.getOre((String)"blockWoolRed"), OreBracketHandler.getOre((String)"blockWoolRed"), ItemBracketHandler.getItem((String)"minecraft:string", (int)0)}});
        Research.setAspects((String)"TINYFEZ", (String)"lucrum 9, pannus 9, potentia 6, sano 3");
        Research.setComplexity((String)"TINYFEZ", (int)2);
        Arcane.addShaped((String)"TINYDART", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemDecoration", (int)4), (String)"aer 5, ignis 5, terra 5", (IIngredient[][])new IIngredient[][]{{ItemBracketHandler.getItem((String)"minecraft:arrow", (int)0), OreBracketHandler.getOre((String)"springSmallSteel"), ItemBracketHandler.getItem((String)"minecraft:arrow", (int)0)}, {ItemBracketHandler.getItem((String)"minecraft:arrow", (int)0), ItemBracketHandler.getItem((String)"minecraft:dropper", (int)0), ItemBracketHandler.getItem((String)"minecraft:arrow", (int)0)}, {ItemBracketHandler.getItem((String)"minecraft:arrow", (int)0), OreBracketHandler.getOre((String)"springSmallSteel"), ItemBracketHandler.getItem((String)"minecraft:arrow", (int)0)}});
        Research.setAspects((String)"TINYDART", (String)"lucrum 9, volatus 9, telum 6, potentia 3");
        Research.setComplexity((String)"TINYDART", (int)2);
        Arcane.addShaped((String)"TINYVISOR", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemDecoration", (int)5), (String)"aqua 5, ignis 5, terra 5", (IIngredient[][])new IIngredient[][]{{ItemBracketHandler.getItem((String)"dreamcraft:item.SteelBars", (int)0), ItemBracketHandler.getItem((String)"minecraft:iron_helmet", (int)0), ItemBracketHandler.getItem((String)"dreamcraft:item.SteelBars", (int)0)}, {OreBracketHandler.getOre((String)"plateSteel"), OreBracketHandler.getOre((String)"plateSteel"), OreBracketHandler.getOre((String)"plateSteel")}, {null, null, null}});
        Research.setAspects((String)"TINYVISOR", (String)"lucrum 9, sensus 9, tutamen 6, cognitio 3");
        Research.setComplexity((String)"TINYVISOR", (int)2);
        Arcane.addShaped((String)"TINYARMOR", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemDecoration", (int)6), (String)"ordo 5, ignis 5, terra 10", (IIngredient[][])new IIngredient[][]{{null, null, null}, {OreBracketHandler.getOre((String)"plateSteel"), ItemBracketHandler.getItem((String)"minecraft:iron_chestplate", (int)0), OreBracketHandler.getOre((String)"plateSteel")}, {OreBracketHandler.getOre((String)"plateSteel"), OreBracketHandler.getOre((String)"plateSteel"), OreBracketHandler.getOre((String)"plateSteel")}});
        Research.setAspects((String)"TINYARMOR", (String)"lucrum 9, metallum 9, tutamen 6, cognitio 3");
        Research.setComplexity((String)"TINYARMOR", (int)2);
        Arcane.addShaped((String)"TINYHAMMER", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemDecoration", (int)7), (String)"ordo 5, ignis 5, terra 10", (IIngredient[][])new IIngredient[][]{{OreBracketHandler.getOre((String)"plateSteel"), OreBracketHandler.getOre((String)"plateSteel"), OreBracketHandler.getOre((String)"plateSteel")}, {OreBracketHandler.getOre((String)"plateSteel"), OreBracketHandler.getOre((String)"plateSteel"), OreBracketHandler.getOre((String)"plateSteel")}, {null, OreBracketHandler.getOre((String)"stickWood"), null}});
        Research.setAspects((String)"TINYHAMMER", (String)"lucrum 9, metallum 9, telum 6, vinculum 3");
        Research.setComplexity((String)"TINYHAMMER", (int)2);
        Compressor.addRecipe((IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:blockTaint", (int)2), (IIngredient)ItemBracketHandler.getItem((String)"minecraft:rotten_flesh", (int)0).amount(9));
        Research.refreshResearchRecipe((String)"HUNGRYCHEST");
        Research.refreshResearchRecipe((String)"TRAVELTRUNK");
        Research.refreshResearchRecipe((String)"GOLEMFETTER");
        Research.refreshResearchRecipe((String)"GOLEMSTRAW");
        Research.refreshResearchRecipe((String)"GOLEMWOOD");
        Research.refreshResearchRecipe((String)"GOLEMTALLOW");
        Research.refreshResearchRecipe((String)"GOLEMCLAY");
        Research.refreshResearchRecipe((String)"GOLEMFLESH");
        Research.refreshResearchRecipe((String)"GOLEMSTONE");
        Research.refreshResearchRecipe((String)"GOLEMIRON");
        Research.refreshResearchRecipe((String)"GOLEMTHAUMIUM");
        Research.refreshResearchRecipe((String)"ADVANCEDGOLEM");
        Research.refreshResearchRecipe((String)"COREGATHER");
        Research.refreshResearchRecipe((String)"COREEMPTY");
        Research.refreshResearchRecipe((String)"COREFILL");
        Research.refreshResearchRecipe((String)"COREHARVEST");
        Research.refreshResearchRecipe((String)"COREGUARD");
        Research.refreshResearchRecipe((String)"COREUSE");
        Research.refreshResearchRecipe((String)"CORESORTING");
        Research.refreshResearchRecipe((String)"CORELIQUID");
        Research.refreshResearchRecipe((String)"COREALCHEMY");
        Research.refreshResearchRecipe((String)"COREBUTCHER");
        Research.refreshResearchRecipe((String)"COREFISHING");
        Research.refreshResearchRecipe((String)"CORELUMBER");
        Research.refreshResearchRecipe((String)"GOLEMBELL");
        Research.refreshResearchRecipe((String)"UPGRADEAIR");
        Research.refreshResearchRecipe((String)"UPGRADEEARTH");
        Research.refreshResearchRecipe((String)"UPGRADEFIRE");
        Research.refreshResearchRecipe((String)"UPGRADEWATER");
        Research.refreshResearchRecipe((String)"UPGRADEORDER");
        Research.refreshResearchRecipe((String)"UPGRADEENTROPY");
        Research.refreshResearchRecipe((String)"TINYHAT");
        Research.refreshResearchRecipe((String)"TINYGLASSES");
        Research.refreshResearchRecipe((String)"TINYBOWTIE");
        Research.refreshResearchRecipe((String)"TINYFEZ");
        Research.refreshResearchRecipe((String)"TINYDART");
        Research.refreshResearchRecipe((String)"TINYVISOR");
        Research.refreshResearchRecipe((String)"TINYARMOR");
        Research.refreshResearchRecipe((String)"TINYHAMMER");
    }
}

