package com.github.GTNH2Mega.fromScripts;
import gttweaker.mods.gregtech.machines.Assembler;
import gttweaker.mods.gregtech.machines.Autoclave;
import minetweaker.MineTweakerAPI;
import minetweaker.api.item.IIngredient;
import minetweaker.api.item.IItemStack;
import minetweaker.api.liquid.ILiquidStack;
import minetweaker.mc1710.brackets.ItemBracketHandler;
import minetweaker.mc1710.brackets.LiquidBracketHandler;
import minetweaker.mc1710.brackets.OreBracketHandler;
import modtweaker2.mods.chisel.handlers.Groups;
import modtweaker2.mods.thaumcraft.handlers.Arcane;
import modtweaker2.mods.thaumcraft.handlers.Research;
import static com.github.GTNH2Mega.VoltageLevels.*;
public class Thaumcraft01Basic
implements Runnable {
    public void run() {
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)32767));
        MineTweakerAPI.recipes.removeShapeless((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)6), null, false);
        MineTweakerAPI.furnace.remove((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)6), null);
        MineTweakerAPI.recipes.removeShaped((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)6), (IIngredient[][])new IIngredient[][]{{ItemBracketHandler.getItem((String)"Thaumcraft:blockCosmeticOpaque", (int)0)}});
        MineTweakerAPI.recipes.removeShaped((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)6), (IIngredient[][])new IIngredient[][]{{ItemBracketHandler.getItem((String)"Thaumcraft:blockCosmeticOpaque", (int)1)}});
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:blockCosmeticOpaque", (int)0));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:blockCosmeticOpaque", (int)1));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:blockTable", (int)14));
        Research.clearPages((String)"PLANTS");
        Research.addPage((String)"PLANTS", (String)"tc.research_page.PLANTS.1");
        Research.addCraftingPage((String)"PLANTS", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:blockWoodenDevice", (int)6));
        Research.addPage((String)"PLANTS", (String)"tc.research_page.PLANTS.2");
        Research.addCraftingPage((String)"PLANTS", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:blockWoodenDevice", (int)7));
        Research.addPage((String)"PLANTS", (String)"tc.research_page.PLANTS.3");
        Research.addPage((String)"PLANTS", (String)"tc.research_page.PLANTS.4");
        Research.addPage((String)"PLANTS", (String)"tc.research_page.PLANTS.5");
        Research.addPage((String)"PLANTS", (String)"tc.research_page.PLANTS.6");
        Arcane.addShaped((String)"ASPECTS", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)0), (String)"aer 10, terra 5, ignis 5, aqua 5, ordo 5, perditio 5", (IIngredient[][])new IIngredient[][]{{ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)0)}, {null, ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)0), null}, {ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)0)}});
        Arcane.addShaped((String)"ASPECTS", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)1), (String)"aer 5, terra 5, ignis 10, aqua 5, ordo 5, perditio 5", (IIngredient[][])new IIngredient[][]{{ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)1), ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)1), ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)1)}, {null, ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)1), null}, {ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)1), ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)1), ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)1)}});
        Arcane.addShaped((String)"ASPECTS", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)2), (String)"aer 5, terra 5, ignis 5, aqua 10, ordo 5, perditio 5", (IIngredient[][])new IIngredient[][]{{ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)2), ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)2), ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)2)}, {null, ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)2), null}, {ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)2), ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)2), ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)2)}});
        Arcane.addShaped((String)"ASPECTS", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)3), (String)"aer 5, terra 10, ignis 5, aqua 5, ordo 5, perditio 5", (IIngredient[][])new IIngredient[][]{{ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)3), ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)3), ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)3)}, {null, ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)3), null}, {ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)3), ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)3), ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)3)}});
        Arcane.addShaped((String)"ASPECTS", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)4), (String)"aer 5, terra 5, ignis 5, aqua 5, ordo 10, perditio 5", (IIngredient[][])new IIngredient[][]{{ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)4), ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)4), ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)4)}, {null, ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)4), null}, {ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)4), ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)4), ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)4)}});
        Arcane.addShaped((String)"ASPECTS", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)5), (String)"aer 5, terra 5, ignis 5, aqua 5, ordo 5, perditio 10", (IIngredient[][])new IIngredient[][]{{ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)5), ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)5), ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)5)}, {null, ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)5), null}, {ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)5), ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)5), ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)5)}});
        Arcane.addShaped((String)"ASPECTS", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)6), (String)"aer 10, terra 10, ignis 10, aqua 10, ordo 10, perditio 10", (IIngredient[][])new IIngredient[][]{{ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)1), ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)2)}, {ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)6), ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)6), ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)6)}, {ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)3), ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)4), ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)5)}});
        Research.clearPages((String)"ORE");
        Research.addPage((String)"ORE", (String)"tc.research_page.ORE.1");
        Research.addPage((String)"ORE", (String)"tc.research_page.ORE.2");
        Research.addArcanePage((String)"ORE", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)0));
        Research.addArcanePage((String)"ORE", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)1));
        Research.addArcanePage((String)"ORE", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)2));
        Research.addArcanePage((String)"ORE", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)3));
        Research.addArcanePage((String)"ORE", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)4));
        Research.addArcanePage((String)"ORE", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)5));
        Research.addArcanePage((String)"ORE", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)6));
        Research.addPage((String)"ORE", (String)"tc.research_page.ORE.3");
        Research.addPage((String)"ORE", (String)"tc.research_page.ORE.4");
        Research.setAspects((String)"RESEARCHER1", (String)"cognitio 6, sensus 6, ordo 6, lux 3");
        Research.setComplexity((String)"RESEARCHER1", (int)1);
        Research.setAspects((String)"RESEARCHER2", (String)"cognitio 9, sensus 9, ordo 6, lux 6, permutatio 3");
        Research.setComplexity((String)"RESEARCHER2", (int)2);
        Research.setAspects((String)"NODETAPPER1", (String)"permutatio 9, auram 9, praecantatio 6, motus 3");
        Research.setComplexity((String)"NODETAPPER1", (int)2);
        Research.setAspects((String)"NODETAPPER2", (String)"permutatio 12, auram 12, praecantatio 9, motus 6, potentia 3");
        Research.setComplexity((String)"NODETAPPER2", (int)3);
        Research.setAspects((String)"NODEPRESERVE", (String)"perditio 9, cognitio 9, fabrico 6, instrumentum 3");
        Research.setComplexity((String)"NODEPRESERVE", (int)2);
        Arcane.addShaped((String)"DECONSTRUCTOR", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:blockTable", (int)14), (String)"ordo 20, perditio 20", (IIngredient[][])new IIngredient[][]{{OreBracketHandler.getOre((String)"screwThaumium"), ItemBracketHandler.getItem((String)"Thaumcraft:ItemThaumometer", (int)0), OreBracketHandler.getOre((String)"screwThaumium")}, {ItemBracketHandler.getItem((String)"Thaumcraft:ItemPickThaumium", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:blockTable", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:ItemAxeThaumium", (int)0)}, {OreBracketHandler.getOre((String)"plateThaumium"), OreBracketHandler.getOre((String)"craftingToolScrewdriver"), OreBracketHandler.getOre((String)"plateThaumium")}});
        Research.setAspects((String)"DECONSTRUCTOR", (String)"sensus 9, auram 9, lucrum 6, fames 3");
        Research.setComplexity((String)"DECONSTRUCTOR", (int)2);
        Research.setAspects((String)"NODEJAR", (String)"auram 12, motus 12, lucrum 9, permutatio 6, vitreus 3");
        Research.setComplexity((String)"NODEJAR", (int)3);
        Research.setAspects((String)"RESEARCHDUPE", (String)"sensus 12, cognitio 12, fabrico 12, lucrum 9, perditio 6, potentia 3");
        Research.setComplexity((String)"RESEARCHDUPE", (int)3);
        Groups.addVariation((String)"thaumium", (IItemStack)ItemBracketHandler.getItem((String)"gregtech:gt.blockmetal7", (int)4));
        Autoclave.addRecipe((IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)6), (IIngredient)ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)2514), (ILiquidStack)LiquidBracketHandler.getLiquid((String)"water").withAmount(200), (int)7000, (int)2000, (int)24);
        Autoclave.addRecipe((IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)6), (IIngredient)ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)2514), (ILiquidStack)LiquidBracketHandler.getLiquid((String)"ic2distilledwater").withAmount(100), (int)9000, (int)1500, (int)24);
        Autoclave.addRecipe((IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)6), (IIngredient)ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)2514), (ILiquidStack)LiquidBracketHandler.getLiquid((String)"molten.void").withAmount(36), (int)10000, (int)1000, (int)24);
        Assembler.addRecipe((IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:blockCustomPlant", (int)3), (IIngredient)ItemBracketHandler.getItem((String)"harvestthenether:glowflowerseedItem", (int)0), (IIngredient)ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)801).amount(8), (int)600, (int)30);
        Assembler.addRecipe((IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:blockCustomPlant", (int)2), (IIngredient)ItemBracketHandler.getItem((String)"harvestthenether:glowflowerseedItem", (int)0), (IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:ItemNugget", (int)5).amount(8), (int)600, (int)30);
        Research.refreshResearchRecipe((String)"DECONSTRUCTOR");
        Research.addResearch((String)"WARPWARNING", (String)"BASICS", (String)"null", (int)1, (int)1, (int)1, (IItemStack)ItemBracketHandler.getItem((String)"minecraft:skull", (int)1));
        Research.addSibling((String)"WARP", (String)"WARPWARNING");
        Research.addSibling((String)"RESEARCH", (String)"WARPWARNING");
        MineTweakerAPI.game.setLocalization("tc.research_name.WARPWARNING", "Warp Warnings");
        MineTweakerAPI.game.setLocalization("tc.research_text.WARPWARNING", "[WT] Wither in the Overworld");
        Research.setAutoUnlock((String)"WARPWARNING", (boolean)true);
        Research.setSpikey((String)"WARPWARNING", (boolean)true);
        Research.addPage((String)"WARPWARNING", (String)"WARPTHEORY.research_page.WARPWARNING.1");
        MineTweakerAPI.game.setLocalization("WARPTHEORY.research_page.WARPWARNING.1", "Thaumcraft offers considerable power from its devices and tools. But power comes with a price.... As of version 4.2, that price is represented by Warp: A corruption of the characters mind and soul, inflicting progressively more dire effects upon them. While the effects of warp can range from annoying to deadly, accumulating enough of it can also grant you access to greater power... at the cost of increasing madness, and attention from dark powers. At least, others may call it madness... but is it truly insanity, when the voices in your head grant useful knowledge, and the monsters that appear before you leave remains behind?");
        Research.addPage((String)"WARPWARNING", (String)"WARPTHEORY.research_page.WARPWARNING.2");
        MineTweakerAPI.game.setLocalization("WARPTHEORY.research_page.WARPWARNING.2", "Warp Theory add a bunch of new Warp Effects to the Player. Be very carful because you don't want autospawning an Wither in or bside you Base<BR>Warp Effects are Trickert by Warp Level<BR>Fake explosion warp effect can happen with 10 Warp<BR>Fake creeper warp effect can happen with 10 Warp<BR>Spawn bats can happen with 15 Warp<BR>Poison warp effect can happen with 16 Warp<BR>Jump boost warp effect can happen with 18 Warp");
        Research.addPage((String)"WARPWARNING", (String)"WARPTHEORY.research_page.WARPWARNING.3");
        MineTweakerAPI.game.setLocalization("WARPTHEORY.research_page.WARPWARNING.3", "Rain warp effect can happen with 25 Warp<BR>Blood warp effect can happen with 25 Warp<BR>Nausea warp effect can happen with 25 Warp<BR>Friendly creeper warp effect can happen with 26 Warp<BR>Lightning warp effect can happen with 30 Warp<BR>Livestock rain warp effect can happen with 32 Warp<BR>Wind warp effect can happen with 38 Warp<BR>Blindness warp effect can happen with 43 Warp");
        Research.addPage((String)"WARPWARNING", (String)"WARPTHEORY.research_page.WARPWARNING.4");
        MineTweakerAPI.game.setLocalization("WARPTHEORY.research_page.WARPWARNING.4", "Random teleport can happen with 45 Warp<BR>Acceleration warp effect can happen with 50 Warp<BR>Decay warp effect can happen with 50 Warp<BR>Random trees effect can happen with 50 Warp<BR>Chest scramble warp effect can happen with 80 Warp<BR>Spawn wither warp effect can happen with Warp 80");
    }
}

