package com.github.GTNH2Mega.fromScripts;
import minetweaker.MineTweakerAPI;
import minetweaker.api.item.IIngredient;
import minetweaker.api.item.IItemStack;
import minetweaker.mc1710.brackets.ItemBracketHandler;
import minetweaker.mc1710.brackets.OreBracketHandler;
import modtweaker2.mods.thaumcraft.handlers.Arcane;
import modtweaker2.mods.thaumcraft.handlers.Crucible;
import modtweaker2.mods.thaumcraft.handlers.Infusion;
import modtweaker2.mods.thaumcraft.handlers.Research;
import modtweaker2.mods.thaumcraft.handlers.Warp;
import static com.github.GTNH2Mega.VoltageLevels.*;
public class Thaumcraft06Eldritch
implements Runnable {
    public void run() {
        Infusion.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:WandRod", (int)100));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)16));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:ItemNugget", (int)7));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:ItemAxeVoid", (int)0));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:ItemSwordVoid", (int)0));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:ItemPickVoid", (int)0));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:ItemShovelVoid", (int)0));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:ItemHoeVoid", (int)0));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:ItemHelmetVoid", (int)0));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:ItemChestplateVoid", (int)0));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:ItemLeggingsVoid", (int)0));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:ItemBootsVoid", (int)0));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"thaumicbases:voidFAS", (int)0));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"thaumicbases:voidShears", (int)0));
        Infusion.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:blockEssentiaReservoir", (int)0));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:FocusPrimal", (int)0));
        Infusion.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:ItemHelmetVoidFortress", (int)0));
        Infusion.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:ItemChestplateVoidFortress", (int)0));
        Infusion.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:ItemLeggingsVoidFortress", (int)0));
        Infusion.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:ItemSanityChecker", (int)0));
        Infusion.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:ItemEldritchObject", (int)0));
        Infusion.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:ItemPrimalCrusher", (int)0));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:blockMetalDevice", (int)3));
        Research.clearPages((String)"ELDRITCHMINOR");
        Research.addPage((String)"ELDRITCHMINOR", (String)"tc.research_page.ELDRITCHMINOR.1");
        Crucible.addRecipe((String)"ELDRITCHMINOR", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)17), (IIngredient)OreBracketHandler.getOre((String)"listAllseed"), (String)"alienis 8, tenebrae 8, vacuos 8");
        Research.addCruciblePage((String)"ELDRITCHMINOR", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)17));
        Research.clearPages((String)"VOIDMETAL");
        Research.addPage((String)"VOIDMETAL", (String)"tc.research_page.VOIDMETAL.1");
        Crucible.addRecipe((String)"VOIDMETAL", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)16), (IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)17), (String)"metallum 16");
        Research.addCruciblePage((String)"VOIDMETAL", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)16));
        Research.addPage((String)"VOIDMETAL", (String)"tc.research_page.VOIDMETAL.2");
        Research.setAspects((String)"VOIDMETAL", (String)"vacuos 12, metallum 12, tenebrae 9, alienis 9, gelum 6, terra 3");
        Research.setComplexity((String)"VOIDMETAL", (int)3);
        Warp.addToResearch((String)"VOIDMETAL", (int)1);
        Arcane.addShaped((String)"VOIDMETAL", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemAxeVoid", (int)0), (String)"perditio 30, terra 15", (IIngredient[][])new IIngredient[][]{{OreBracketHandler.getOre((String)"plateVoid"), OreBracketHandler.getOre((String)"ingotVoid"), OreBracketHandler.getOre((String)"craftingToolHardHammer")}, {OreBracketHandler.getOre((String)"plateVoid"), OreBracketHandler.getOre((String)"stickWood"), null}, {OreBracketHandler.getOre((String)"craftingToolFile"), OreBracketHandler.getOre((String)"stickVoid"), null}});
        Research.addArcanePage((String)"VOIDMETAL", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemAxeVoid", (int)0));
        Arcane.addShaped((String)"VOIDMETAL", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemSwordVoid", (int)0), (String)"perditio 30, terra 15", (IIngredient[][])new IIngredient[][]{{null, OreBracketHandler.getOre((String)"plateVoid"), null}, {OreBracketHandler.getOre((String)"craftingToolFile"), OreBracketHandler.getOre((String)"plateVoid"), OreBracketHandler.getOre((String)"craftingToolHardHammer")}, {null, OreBracketHandler.getOre((String)"stickVoid"), null}});
        Research.addArcanePage((String)"VOIDMETAL", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemSwordVoid", (int)0));
        Arcane.addShaped((String)"VOIDMETAL", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemPickVoid", (int)0), (String)"perditio 30, terra 15", (IIngredient[][])new IIngredient[][]{{OreBracketHandler.getOre((String)"plateVoid"), OreBracketHandler.getOre((String)"ingotVoid"), OreBracketHandler.getOre((String)"ingotVoid")}, {OreBracketHandler.getOre((String)"craftingToolFile"), OreBracketHandler.getOre((String)"stickWood"), OreBracketHandler.getOre((String)"craftingToolHardHammer")}, {null, OreBracketHandler.getOre((String)"stickVoid"), null}});
        Research.addArcanePage((String)"VOIDMETAL", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemPickVoid", (int)0));
        Arcane.addShaped((String)"VOIDMETAL", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemShovelVoid", (int)0), (String)"perditio 30, terra 15", (IIngredient[][])new IIngredient[][]{{OreBracketHandler.getOre((String)"craftingToolFile"), OreBracketHandler.getOre((String)"ingotVoid"), OreBracketHandler.getOre((String)"craftingToolHardHammer")}, {null, OreBracketHandler.getOre((String)"stickWood"), null}, {null, OreBracketHandler.getOre((String)"stickVoid"), null}});
        Research.addArcanePage((String)"VOIDMETAL", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemShovelVoid", (int)0));
        Arcane.addShaped((String)"VOIDMETAL", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemHoeVoid", (int)0), (String)"perditio 30, terra 15", (IIngredient[][])new IIngredient[][]{{OreBracketHandler.getOre((String)"plateVoid"), OreBracketHandler.getOre((String)"ingotVoid"), OreBracketHandler.getOre((String)"craftingToolHardHammer")}, {OreBracketHandler.getOre((String)"craftingToolFile"), OreBracketHandler.getOre((String)"stickWood"), null}, {null, OreBracketHandler.getOre((String)"stickVoid"), null}});
        Research.addArcanePage((String)"VOIDMETAL", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemHoeVoid", (int)0));
        Arcane.addShaped((String)"VOIDMETAL", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemHelmetVoid", (int)0), (String)"perditio 40, terra 20", (IIngredient[][])new IIngredient[][]{{OreBracketHandler.getOre((String)"plateVoid"), OreBracketHandler.getOre((String)"plateVoid"), OreBracketHandler.getOre((String)"plateVoid")}, {OreBracketHandler.getOre((String)"plateVoid"), OreBracketHandler.getOre((String)"craftingToolHardHammer"), OreBracketHandler.getOre((String)"plateVoid")}, {null, null, null}});
        Research.addArcanePage((String)"VOIDMETAL", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemHelmetVoid", (int)0));
        Arcane.addShaped((String)"VOIDMETAL", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemChestplateVoid", (int)0), (String)"perditio 40, terra 20", (IIngredient[][])new IIngredient[][]{{OreBracketHandler.getOre((String)"plateVoid"), OreBracketHandler.getOre((String)"craftingToolHardHammer"), OreBracketHandler.getOre((String)"plateVoid")}, {OreBracketHandler.getOre((String)"plateVoid"), OreBracketHandler.getOre((String)"plateVoid"), OreBracketHandler.getOre((String)"plateVoid")}, {OreBracketHandler.getOre((String)"plateVoid"), OreBracketHandler.getOre((String)"plateVoid"), OreBracketHandler.getOre((String)"plateVoid")}});
        Research.addArcanePage((String)"VOIDMETAL", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemChestplateVoid", (int)0));
        Arcane.addShaped((String)"VOIDMETAL", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemLeggingsVoid", (int)0), (String)"perditio 40, terra 20", (IIngredient[][])new IIngredient[][]{{OreBracketHandler.getOre((String)"plateVoid"), OreBracketHandler.getOre((String)"plateVoid"), OreBracketHandler.getOre((String)"plateVoid")}, {OreBracketHandler.getOre((String)"plateVoid"), OreBracketHandler.getOre((String)"craftingToolHardHammer"), OreBracketHandler.getOre((String)"plateVoid")}, {OreBracketHandler.getOre((String)"plateVoid"), null, OreBracketHandler.getOre((String)"plateVoid")}});
        Research.addArcanePage((String)"VOIDMETAL", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemLeggingsVoid", (int)0));
        Arcane.addShaped((String)"VOIDMETAL", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemBootsVoid", (int)0), (String)"perditio 40, terra 20", (IIngredient[][])new IIngredient[][]{{OreBracketHandler.getOre((String)"plateVoid"), null, OreBracketHandler.getOre((String)"plateVoid")}, {OreBracketHandler.getOre((String)"plateVoid"), OreBracketHandler.getOre((String)"craftingToolHardHammer"), OreBracketHandler.getOre((String)"plateVoid")}, {null, null, null}});
        Research.addArcanePage((String)"VOIDMETAL", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemBootsVoid", (int)0));
        Arcane.addShaped((String)"VOIDMETAL", (IItemStack)ItemBracketHandler.getItem((String)"thaumicbases:voidFAS", (int)0), (String)"perditio 40, terra 20", (IIngredient[][])new IIngredient[][]{{null, OreBracketHandler.getOre((String)"plateVoid"), null}, {null, ItemBracketHandler.getItem((String)"minecraft:flint_and_steel", (int)0), null}, {null, OreBracketHandler.getOre((String)"plateVoid"), null}});
        Research.addArcanePage((String)"VOIDMETAL", (IItemStack)ItemBracketHandler.getItem((String)"thaumicbases:voidFAS", (int)0));
        Arcane.addShaped((String)"VOIDMETAL", (IItemStack)ItemBracketHandler.getItem((String)"thaumicbases:voidShears", (int)0), (String)"perditio 40, terra 20", (IIngredient[][])new IIngredient[][]{{null, OreBracketHandler.getOre((String)"plateVoid"), null}, {OreBracketHandler.getOre((String)"plateVoid"), ItemBracketHandler.getItem((String)"minecraft:shears", (int)0), OreBracketHandler.getOre((String)"plateVoid")}, {null, OreBracketHandler.getOre((String)"plateVoid"), null}});
        Research.addArcanePage((String)"VOIDMETAL", (IItemStack)ItemBracketHandler.getItem((String)"thaumicbases:voidShears", (int)0));
        Research.clearPages((String)"CAP_void");
        Research.addPage((String)"CAP_void", (String)"tc.research_page.CAP_void.1");
        Arcane.addShaped((String)"CAP_void", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:WandCap", (int)8), (String)"ordo 40, ignis 40, aer 40, perditio 40", (IIngredient[][])new IIngredient[][]{{OreBracketHandler.getOre((String)"screwTungstenSteel"), OreBracketHandler.getOre((String)"foilVoid"), OreBracketHandler.getOre((String)"screwTungstenSteel")}, {OreBracketHandler.getOre((String)"foilVoid"), OreBracketHandler.getOre((String)"ringVoid"), OreBracketHandler.getOre((String)"foilVoid")}, {OreBracketHandler.getOre((String)"screwTungstenSteel"), OreBracketHandler.getOre((String)"foilVoid"), OreBracketHandler.getOre((String)"screwTungstenSteel")}});
        Research.addArcanePage((String)"CAP_void", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:WandCap", (int)8));
        Infusion.addRecipe((String)"CAP_void", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:WandCap", (int)8), (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)14), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)17), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)14), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)17), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)14), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)17)}, (String)"alienis 32, auram 32, potentia 32, vacuos 32", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:WandCap", (int)7), (int)8);
        Research.addInfusionPage((String)"CAP_void", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:WandCap", (int)7));
        Research.setAspects((String)"CAP_void", (String)"auram 12, vacuos 12, alienis 9, praecantatio 9, instrumentum 6, terra 6, tenebrae 3");
        Research.setComplexity((String)"CAP_void", (int)3);
        Infusion.addRecipe((String)"ESSENTIARESERVOIR", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:blockTube", (int)4), (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)17970), ItemBracketHandler.getItem((String)"Thaumcraft:blockJar", (int)0), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)17970), ItemBracketHandler.getItem((String)"Thaumcraft:blockJar", (int)0), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)17970), ItemBracketHandler.getItem((String)"Thaumcraft:blockJar", (int)0), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)17970), ItemBracketHandler.getItem((String)"Thaumcraft:blockJar", (int)0)}, (String)"aqua 16, permutatio 16, praecantatio 16, vacuos 16", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:blockEssentiaReservoir", (int)0), (int)8);
        Research.setAspects((String)"ESSENTIARESERVOIR", (String)"aqua 12, permutatio 12, praecantatio 9, vacuos 9, alienis 6, tenebrae 3");
        Research.setComplexity((String)"ESSENTIARESERVOIR", (int)3);
        Arcane.addShaped((String)"FOCUSPRIMAL", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:FocusPrimal", (int)0), (String)"aqua 75, terra 75, ignis 75, aer 75, ordo 75, perditio 75", (IIngredient[][])new IIngredient[][]{{OreBracketHandler.getOre((String)"gemExquisiteDiamond"), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)1)}, {ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)2), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)15), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)3)}, {ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)4), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)5), OreBracketHandler.getOre((String)"gemExquisiteDiamond")}});
        Research.setAspects((String)"FOCUSPRIMAL", (String)"aqua 12, ignis 12, aer 12, terra 9, ordo 9, perditio 9, praecantatio 6, alienis 3");
        Research.setComplexity((String)"FOCUSPRIMAL", (int)4);
        Infusion.addRecipe((String)"ROD_primal_staff", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:WandRod", (int)2), (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)15), ItemBracketHandler.getItem((String)"Thaumcraft:WandRod", (int)1), ItemBracketHandler.getItem((String)"Thaumcraft:WandRod", (int)3), ItemBracketHandler.getItem((String)"Thaumcraft:WandRod", (int)4), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)15), ItemBracketHandler.getItem((String)"Thaumcraft:WandRod", (int)5), ItemBracketHandler.getItem((String)"Thaumcraft:WandRod", (int)6), ItemBracketHandler.getItem((String)"Thaumcraft:WandRod", (int)7)}, (String)"aer 64, aqua 64, terra 64, ignis 64, ordo 64, perditio 64, praecantatio 128", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:WandRod", (int)100), (int)10);
        Research.setAspects((String)"ROD_primal_staff", (String)"aqua 15, ignis 15, aer 12, terra 12, ordo 12, perditio 9, praecantatio 9, instrumentum 6, alienis 3");
        Research.setComplexity((String)"ROD_primal_staff", (int)4);
        Infusion.addRecipe((String)"ARMORVOIDFORTRESS", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemHelmetVoid", (int)0), (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"Thaumcraft:ItemGoggles", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)7), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)17970), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)7), ItemBracketHandler.getItem((String)"harvestcraft:hardenedleatherItem", (int)0), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)17330), ItemBracketHandler.getItem((String)"harvestcraft:hardenedleatherItem", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)7), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)17970), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)7)}, (String)"alienis 24, metallum 24, pannus 24, sensus 24, tutamen 24, vacuos 24, praecantatio 24", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemHelmetVoidFortress", (int)0), (int)8);
        Research.setAspects((String)"ARMORVOIDFORTRESS", (String)"vacuos 15, tenebrae 15, tutamen 12, pannus 12, alienis 9, praecantatio 9, sensus 6, metallum 3");
        Research.setComplexity((String)"ARMORVOIDFORTRESS", (int)4);
        Infusion.addRecipe((String)"ARMORVOIDFORTRESS", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemChestplateVoid", (int)0), (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"Thaumcraft:ItemChestplateRobe", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)7), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)17970), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)7), ItemBracketHandler.getItem((String)"harvestcraft:hardenedleatherItem", (int)0), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)17330), ItemBracketHandler.getItem((String)"harvestcraft:hardenedleatherItem", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)7), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)17970), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)7)}, (String)"alienis 32, metallum 32, pannus 32, sensus 32, tutamen 32, vacuos 32, praecantatio 32", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemChestplateVoidFortress", (int)0), (int)8);
        Infusion.addRecipe((String)"ARMORVOIDFORTRESS", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemLeggingsVoid", (int)0), (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"Thaumcraft:ItemLeggingsRobe", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)7), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)17970), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)7), ItemBracketHandler.getItem((String)"harvestcraft:hardenedleatherItem", (int)0), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)17330), ItemBracketHandler.getItem((String)"harvestcraft:hardenedleatherItem", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)7), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)17970), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)7)}, (String)"alienis 28, metallum 28, pannus 28, sensus 28, tutamen 28, vacuos 28, praecantatio 28", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemLeggingsVoidFortress", (int)0), (int)8);
        Infusion.addRecipe((String)"SANITYCHECK", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemThaumometer", (int)0), (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"Thaumcraft:blockMirror", (int)0), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)27330), ItemBracketHandler.getItem((String)"Thaumcraft:ItemZombieBrain", (int)0), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)27330), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.02", (int)29500), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)27330), ItemBracketHandler.getItem((String)"Thaumcraft:ItemZombieBrain", (int)0), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)27330)}, (String)"alienis 16, cognitio 32, sensus 24, sano 16", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemSanityChecker", (int)0), (int)5);
        Research.setAspects((String)"SANITYCHECK", (String)"sensus 12, cognitio 12, alienis 12, praecantatio 9, sano 6, victus 3");
        Research.setComplexity((String)"SANITYCHECK", (int)3);
        Infusion.addRecipe((String)"OCULUS", (IItemStack)ItemBracketHandler.getItem((String)"StevesCarts:ModuleComponents", (int)45), (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"minecraft:ender_eye", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)17), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)17086), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)17), ItemBracketHandler.getItem((String)"minecraft:ender_eye", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)17), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)17086), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)17)}, (String)"alienis 64, iter 32, tenebrae 32, vacuos 32", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemEldritchObject", (int)0), (int)7);
        Research.setAspects((String)"OCULUS", (String)"alienis 12, cognitio 12, tenebrae 9, iter 9, permutatio 9, vitium 6, praecantatio 3");
        Research.setComplexity((String)"OCULUS", (int)3);
        Infusion.addRecipe((String)"PRIMALCRUSHER", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)15), (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"Thaumcraft:ItemEldritchObject", (int)3), ItemBracketHandler.getItem((String)"Thaumcraft:ItemPickVoid", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:ItemShovelVoid", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)15), ItemBracketHandler.getItem((String)"Thaumcraft:ItemPickaxeElemental", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:ItemShovelElemental", (int)0)}, (String)"alienis 24, instrumentum 24, lucrum 24, perditio 24, perfodio 24, telum 24, vacuos 24", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemPrimalCrusher", (int)0), (int)10);
        Research.setAspects((String)"PRIMALCRUSHER", (String)"praecantatio 12, alienis 12, instrumentum 12, lucrum 9, perditio 9, perfodio 9, telum 6, vacuos 3");
        Research.setComplexity((String)"PRIMALCRUSHER", (int)3);
        Arcane.addShaped((String)"ADVALCHEMYFURNACE", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:blockMetalDevice", (int)3).amount(4), (String)"aqua 32, terra 32, aer 32, ordo 32", (IIngredient[][])new IIngredient[][]{{OreBracketHandler.getOre((String)"plateVoid"), ItemBracketHandler.getItem((String)"Thaumcraft:blockMetalDevice", (int)9), OreBracketHandler.getOre((String)"plateVoid")}, {ItemBracketHandler.getItem((String)"Thaumcraft:blockMetalDevice", (int)9), ItemBracketHandler.getItem((String)"Thaumcraft:ItemEldritchObject", (int)3), ItemBracketHandler.getItem((String)"Thaumcraft:blockMetalDevice", (int)9)}, {OreBracketHandler.getOre((String)"plateVoid"), ItemBracketHandler.getItem((String)"Thaumcraft:blockMetalDevice", (int)9), OreBracketHandler.getOre((String)"plateVoid")}});
        Research.setAspects((String)"ADVALCHEMYFURNACE", (String)"perditio 12, auram 12, aer 9, ordo 9, praecantatio 6, alienis 3");
        Research.setComplexity((String)"ADVALCHEMYFURNACE", (int)3);
        Research.refreshResearchRecipe((String)"ELDRITCHMINOR");
        Research.refreshResearchRecipe((String)"VOIDMETAL");
        Research.refreshResearchRecipe((String)"CAP_void");
        Research.refreshResearchRecipe((String)"ESSENTIARESERVOIR");
        Research.refreshResearchRecipe((String)"FOCUSPRIMAL");
        Research.refreshResearchRecipe((String)"ROD_primal_staff");
        Research.refreshResearchRecipe((String)"ARMORVOIDFORTRESS");
        Research.refreshResearchRecipe((String)"SANITYCHECK");
        Research.refreshResearchRecipe((String)"OCULUS");
        Research.refreshResearchRecipe((String)"PRIMALCRUSHER");
        Research.refreshResearchRecipe((String)"ADVALCHEMYFURNACE");
        Research.refreshResearchRecipe((String)"ROD_silverwood");
        Research.refreshResearchRecipe((String)"ROD_greatwood_staff");
        Research.refreshResearchRecipe((String)"ROD_reed_staff");
        Research.refreshResearchRecipe((String)"ROD_blaze_staff");
        Research.refreshResearchRecipe((String)"ROD_obsidian_staff");
        Research.refreshResearchRecipe((String)"ROD_ice_staff");
        Research.refreshResearchRecipe((String)"ROD_quartz_staff");
        Research.refreshResearchRecipe((String)"ROD_bone_staff");
        Research.refreshResearchRecipe((String)"ROD_silverwood_staff");
        Research.refreshResearchRecipe((String)"SCEPTRE");
        Research.refreshResearchRecipe((String)"ROD_greatwood");
        Research.refreshResearchRecipe((String)"ROD_reed");
        Research.refreshResearchRecipe((String)"ROD_blaze");
        Research.refreshResearchRecipe((String)"ROD_obsidian");
        Research.refreshResearchRecipe((String)"ROD_ice");
        Research.refreshResearchRecipe((String)"ROD_quartz");
        Research.refreshResearchRecipe((String)"ROD_bone");
    }
}

