package com.github.GTNH2Mega.fromScripts;
import gttweaker.mods.gregtech.machines.Pulverizer;
import minetweaker.MineTweakerAPI;
import minetweaker.api.item.IIngredient;
import minetweaker.api.item.IItemStack;
import minetweaker.mc1710.brackets.ItemBracketHandler;
import minetweaker.mc1710.brackets.OreBracketHandler;
import minetweaker.mods.ic2.machines.Compressor;
import modtweaker2.mods.thaumcraft.handlers.Arcane;
import modtweaker2.mods.thaumcraft.handlers.Crucible;
import modtweaker2.mods.thaumcraft.handlers.Infusion;
import modtweaker2.mods.thaumcraft.handlers.Research;
import modtweaker2.mods.thaumcraft.handlers.Warp;
import static com.github.GTNH2Mega.VoltageLevels.*;
public class Thaumcraft03Alchemy
implements Runnable {
    public void run() {
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:ItemEssence", (int)0));
        MineTweakerAPI.furnace.remove((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)14), null);
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)4));
        Crucible.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)4));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:blockCosmeticSolid", (int)5));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:blockCandle", (int)0));
        Crucible.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)32767));
        MineTweakerAPI.recipes.removeShaped((IIngredient)OreBracketHandler.getOre((String)"ingotThaumium"), (IIngredient[][])new IIngredient[][]{{OreBracketHandler.getOre((String)"nuggetThaumium"), OreBracketHandler.getOre((String)"nuggetThaumium"), OreBracketHandler.getOre((String)"nuggetThaumium")}, {OreBracketHandler.getOre((String)"nuggetThaumium"), OreBracketHandler.getOre((String)"nuggetThaumium"), OreBracketHandler.getOre((String)"nuggetThaumium")}, {OreBracketHandler.getOre((String)"nuggetThaumium"), OreBracketHandler.getOre((String)"nuggetThaumium"), OreBracketHandler.getOre((String)"nuggetThaumium")}});
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:ItemNugget", (int)6));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:blockStoneDevice", (int)0));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)8));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:blockMetalDevice", (int)1));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:blockMetalDevice", (int)9));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:blockTube", (int)0));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:blockTube", (int)1));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:blockTube", (int)3));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:blockTube", (int)5));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:blockTube", (int)6));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:blockTube", (int)2));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:blockTube", (int)4));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:ItemResonator", (int)0));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:blockTube", (int)7));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:blockMetalDevice", (int)12));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:blockJar", (int)0));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:blockJar", (int)3));
        Crucible.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:ItemBathSalts", (int)0));
        Crucible.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:ItemSanitySoap", (int)0));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:blockStoneDevice", (int)12));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)3));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:ItemNugget", (int)5));
        MineTweakerAPI.recipes.addShapeless(ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)14), new IIngredient[]{OreBracketHandler.getOre((String)"craftingToolMortar"), ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)6)}, null);
        Research.clearPages((String)"PHIAL");
        Research.addPage((String)"PHIAL", (String)"tc.research_page.PHIAL.1");
        MineTweakerAPI.recipes.addShapeless(ItemBracketHandler.getItem((String)"Thaumcraft:ItemEssence", (int)0), new IIngredient[]{ItemBracketHandler.getItem((String)"minecraft:glass_bottle", (int)0), OreBracketHandler.getOre((String)"roundAnyRubber")}, null);
        Research.addCraftingPage((String)"PHIAL", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemEssence", (int)0));
        Crucible.addRecipe((String)"TALLOW", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)4), (IIngredient)ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)2877), (String)"praecantatio 2, corpus 4, mortuus 2");
        Research.setAspects((String)"TALLOW", (String)"corpus 6, praecantatio 6, motus 3");
        Research.setComplexity((String)"TALLOW", (int)1);
        Research.clearPages((String)"TALLOW");
        Research.addPage((String)"TALLOW", (String)"tc.research_page.TALLOW.1");
        Arcane.addShaped((String)"TALLOW", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:blockCandle", (int)0), (String)"ignis 3, ordo 1, perditio 1, aer 3", (IIngredient[][])new IIngredient[][]{{null, ItemBracketHandler.getItem((String)"minecraft:string", (int)0), null}, {null, ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)4), null}, {null, ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)4), null}});
        Research.addCruciblePage((String)"TALLOW", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)4));
        Research.addArcanePage((String)"TALLOW", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:blockCandle", (int)0));
        Crucible.addRecipe((String)"NITOR", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)1), (IIngredient)ItemBracketHandler.getItem((String)"minecraft:glowstone_dust", (int)0), (String)"ignis 4, lux 4, potentia 4");
        Research.setAspects((String)"NITOR", (String)"lux 6, ignis 3, praecantatio 3");
        Research.setComplexity((String)"NITOR", (int)1);
        Crucible.addRecipe((String)"ALUMENTUM", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)0), (IIngredient)ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)2535), (String)"ignis 6, perditio 3, potentia 6");
        Crucible.addRecipe((String)"ALUMENTUM", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)0), (IIngredient)ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)2536), (String)"ignis 6, perditio 3, potentia 6");
        Crucible.addRecipe((String)"ALUMENTUM", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)0), (IIngredient)ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)2538), (String)"ignis 6, perditio 3, potentia 6");
        Research.setAspects((String)"ALUMENTUM", (String)"ignis 3, praecantatio 3, perditio 6");
        Research.setComplexity((String)"ALUMENTUM", (int)1);
        Research.addPage((String)"ALUMENTUM", (String)"tc.research_page.ALUMENTUM.2");
        MineTweakerAPI.game.setLocalization("tc.research_page.ALUMENTUM.2", "Charcoal dust and Lignite dust works well too. They are not shown in the recipe because of Mod Tweaker");
        Research.setAspects((String)"ALCHEMICALDUPLICATION", (String)"fabrico 9, praecantatio 6, lucrum 9, permutatio 3");
        Research.setComplexity((String)"ALCHEMICALDUPLICATION", (int)2);
        Research.setAspects((String)"ALCHEMICALMANUFACTURE", (String)"fabrico 9, praecantatio 9, lucrum 6, permutatio 3");
        Research.setComplexity((String)"ALCHEMICALMANUFACTURE", (int)2);
        Research.setAspects((String)"ENTROPICPROCESSING", (String)"fabrico 9, praecantatio 9, lucrum 6, perditio 3");
        Research.setComplexity((String)"ENTROPICPROCESSING", (int)2);
        Arcane.addShaped((String)"DISTILESSENTIA", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:blockStoneDevice", (int)0), (String)"ignis 15, aer 10, ordo 5", (IIngredient[][])new IIngredient[][]{{ItemBracketHandler.getItem((String)"Thaumcraft:blockCosmeticSolid", (int)7), ItemBracketHandler.getItem((String)"Railcraft:machine.beta", (int)3), ItemBracketHandler.getItem((String)"Thaumcraft:blockCosmeticSolid", (int)7)}, {OreBracketHandler.getOre((String)"plateThaumium"), OreBracketHandler.getOre((String)"craftingIronFurnace"), OreBracketHandler.getOre((String)"plateThaumium")}, {ItemBracketHandler.getItem((String)"Thaumcraft:blockCosmeticSolid", (int)7), ItemBracketHandler.getItem((String)"Thaumcraft:blockMetalDevice", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:blockCosmeticSolid", (int)7)}});
        Research.setAspects((String)"DISTILESSENTIA", (String)"limus 9, praecantatio 6, ignis 3, aqua 9");
        Research.setComplexity((String)"DISTILESSENTIA", (int)2);
        Arcane.addShaped((String)"DISTILESSENTIA", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)8).amount(3), (String)"ordo 10, aqua 5", (IIngredient[][])new IIngredient[][]{{OreBracketHandler.getOre((String)"springSmallGold"), OreBracketHandler.getOre((String)"plateGold"), OreBracketHandler.getOre((String)"springSmallGold")}, {ItemBracketHandler.getItem((String)"Thaumcraft:blockWoodenDevice", (int)7), ItemBracketHandler.getItem((String)"Thaumcraft:blockWoodenDevice", (int)7), ItemBracketHandler.getItem((String)"Thaumcraft:blockWoodenDevice", (int)7)}, {OreBracketHandler.getOre((String)"springSmallGold"), OreBracketHandler.getOre((String)"plateGold"), OreBracketHandler.getOre((String)"springSmallGold")}});
        Arcane.addShaped((String)"DISTILESSENTIA", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:blockMetalDevice", (int)1), (String)"aer 5, aqua 10, ignis 5", (IIngredient[][])new IIngredient[][]{{OreBracketHandler.getOre((String)"plateThaumium"), OreBracketHandler.getOre((String)"pipeMediumSteel"), OreBracketHandler.getOre((String)"plateThaumium")}, {ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)8), ItemBracketHandler.getItem((String)"Railcraft:machine.beta", (int)3), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)8)}, {OreBracketHandler.getOre((String)"plateThaumium"), OreBracketHandler.getOre((String)"pipeMediumSteel"), OreBracketHandler.getOre((String)"plateThaumium")}});
        Arcane.addShaped((String)"DISTILESSENTIA", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:blockMetalDevice", (int)9), (String)"ordo 10, aqua 5, ignis 5", (IIngredient[][])new IIngredient[][]{{ItemBracketHandler.getItem((String)"Thaumcraft:blockTube", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)8), ItemBracketHandler.getItem((String)"Thaumcraft:blockTube", (int)0)}, {ItemBracketHandler.getItem((String)"Thaumcraft:blockTube", (int)1), OreBracketHandler.getOre((String)"blockThaumium"), ItemBracketHandler.getItem((String)"Thaumcraft:blockTube", (int)1)}, {ItemBracketHandler.getItem((String)"Thaumcraft:blockTube", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)8), ItemBracketHandler.getItem((String)"Thaumcraft:blockTube", (int)0)}});
        Arcane.addShaped((String)"TUBES", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:blockTube", (int)0).amount(4), (String)"ordo 8, aqua 8", (IIngredient[][])new IIngredient[][]{{OreBracketHandler.getOre((String)"screwThaumium"), OreBracketHandler.getOre((String)"nuggetGold"), OreBracketHandler.getOre((String)"screwThaumium")}, {ItemBracketHandler.getItem((String)"Thaumcraft:ItemNugget", (int)5), OreBracketHandler.getOre((String)"pipeSmallSteel"), ItemBracketHandler.getItem((String)"Thaumcraft:ItemNugget", (int)5)}, {OreBracketHandler.getOre((String)"screwThaumium"), OreBracketHandler.getOre((String)"nuggetGold"), OreBracketHandler.getOre((String)"screwThaumium")}});
        Research.setAspects((String)"TUBES", (String)"praecantatio 9, permutatio 6, aqua 9, ordo 3");
        Research.setComplexity((String)"TUBES", (int)2);
        Arcane.addShaped((String)"TUBES", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:blockTube", (int)1), (String)"ordo 8, aqua 8", (IIngredient[][])new IIngredient[][]{{OreBracketHandler.getOre((String)"screwThaumium"), ItemBracketHandler.getItem((String)"minecraft:lever", (int)0), OreBracketHandler.getOre((String)"screwThaumium")}, {OreBracketHandler.getOre((String)"plateAnyRubber"), ItemBracketHandler.getItem((String)"Thaumcraft:blockTube", (int)0), OreBracketHandler.getOre((String)"gearGtSmallThaumium")}, {null, null, null}});
        Arcane.addShaped((String)"TUBES", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemResonator", (int)0), (String)"aer 8, aqua 8", (IIngredient[][])new IIngredient[][]{{OreBracketHandler.getOre((String)"craftingToolScrewdriver"), OreBracketHandler.getOre((String)"stickThaumium"), null}, {OreBracketHandler.getOre((String)"screwThaumium"), ItemBracketHandler.getItem((String)"Thaumcraft:ItemNugget", (int)5), OreBracketHandler.getOre((String)"stickThaumium")}, {OreBracketHandler.getOre((String)"stickWood"), OreBracketHandler.getOre((String)"screwThaumium"), OreBracketHandler.getOre((String)"craftingToolFile")}});
        Arcane.addShaped((String)"TUBEFILTER", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:blockTube", (int)3), (String)"ordo 16, aqua 16", (IIngredient[][])new IIngredient[][]{{OreBracketHandler.getOre((String)"craftingToolScrewdriver"), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)8), OreBracketHandler.getOre((String)"craftingToolFile")}, {OreBracketHandler.getOre((String)"screwThaumium"), ItemBracketHandler.getItem((String)"Thaumcraft:blockTube", (int)0), OreBracketHandler.getOre((String)"screwThaumium")}, {null, ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)8), null}});
        Research.setAspects((String)"TUBEFILTER", (String)"praecantatio 12, permutatio 9, aqua 12, ordo 6, limus 3");
        Research.setComplexity((String)"TUBEFILTER", (int)3);
        Arcane.addShaped((String)"TUBEFILTER", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:blockTube", (int)5), (String)"terra 16, aqua 16", (IIngredient[][])new IIngredient[][]{{null, null, null}, {OreBracketHandler.getOre((String)"ringAnyRubber"), ItemBracketHandler.getItem((String)"Thaumcraft:blockTube", (int)0), OreBracketHandler.getOre((String)"ringAnyRubber")}, {null, null, null}});
        Arcane.addShaped((String)"TUBEFILTER", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:blockTube", (int)6), (String)"ordo 16, perditio 8, aqua 8", (IIngredient[][])new IIngredient[][]{{null, null, null}, {OreBracketHandler.getOre((String)"dyeBlue"), ItemBracketHandler.getItem((String)"Thaumcraft:blockTube", (int)0), OreBracketHandler.getOre((String)"screwThaumium")}, {null, null, null}});
        Arcane.addShaped((String)"CENTRIFUGE", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:blockTube", (int)2), (String)"ordo 32, perditio 16, aqua 16", (IIngredient[][])new IIngredient[][]{{OreBracketHandler.getOre((String)"screwThaumium"), ItemBracketHandler.getItem((String)"Thaumcraft:blockTube", (int)0), OreBracketHandler.getOre((String)"screwThaumium")}, {ItemBracketHandler.getItem((String)"Thaumcraft:blockMetalDevice", (int)1), ItemBracketHandler.getItem((String)"Thaumcraft:blockMetalDevice", (int)9), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)32641)}, {OreBracketHandler.getOre((String)"screwThaumium"), ItemBracketHandler.getItem((String)"Thaumcraft:blockTube", (int)0), OreBracketHandler.getOre((String)"screwThaumium")}});
        Research.setAspects((String)"CENTRIFUGE", (String)"fabrico 12, perditio 9, permutatio 12, praecantatio 6, machina 3");
        Research.setComplexity((String)"CENTRIFUGE", (int)3);
        Arcane.addShaped((String)"CENTRIFUGE", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:blockTube", (int)4).amount(4), (String)"ordo 20, aqua 20", (IIngredient[][])new IIngredient[][]{{ItemBracketHandler.getItem((String)"Thaumcraft:ItemEssence", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:blockTube", (int)1), ItemBracketHandler.getItem((String)"Thaumcraft:ItemEssence", (int)0)}, {ItemBracketHandler.getItem((String)"Thaumcraft:blockTube", (int)0), OreBracketHandler.getOre((String)"screwThaumium"), ItemBracketHandler.getItem((String)"Thaumcraft:blockTube", (int)0)}, {ItemBracketHandler.getItem((String)"Thaumcraft:ItemEssence", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:blockTube", (int)5), ItemBracketHandler.getItem((String)"Thaumcraft:ItemEssence", (int)0)}});
        Arcane.addShaped((String)"ESSENTIACRYSTAL", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:blockTube", (int)7), (String)"terra 20, ordo 15, aqua 10", (IIngredient[][])new IIngredient[][]{{OreBracketHandler.getOre((String)"plateThaumium"), ItemBracketHandler.getItem((String)"minecraft:dispenser", (int)0), OreBracketHandler.getOre((String)"plateThaumium")}, {ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)6), ItemBracketHandler.getItem((String)"Thaumcraft:blockMetalDevice", (int)9), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)6)}, {OreBracketHandler.getOre((String)"screwThaumium"), ItemBracketHandler.getItem((String)"Thaumcraft:blockTube", (int)0), OreBracketHandler.getOre((String)"screwThaumium")}});
        Research.setAspects((String)"ESSENTIACRYSTAL", (String)"aqua 12, praecantatio 9, permutatio 12, vitreus 6, terra 3");
        Research.setComplexity((String)"ESSENTIACRYSTAL", (int)3);
        Arcane.addShaped((String)"THAUMATORIUM", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:blockMetalDevice", (int)12), (String)"ignis 10, ordo 10, aqua 10", (IIngredient[][])new IIngredient[][]{{OreBracketHandler.getOre((String)"plateThaumium"), OreBracketHandler.getOre((String)"gemFlawlessAmber"), OreBracketHandler.getOre((String)"plateThaumium")}, {OreBracketHandler.getOre((String)"gemFlawlessAmber"), ItemBracketHandler.getItem((String)"Thaumcraft:ItemZombieBrain", (int)0), OreBracketHandler.getOre((String)"gemFlawlessAmber")}, {OreBracketHandler.getOre((String)"plateThaumium"), OreBracketHandler.getOre((String)"gemFlawlessAmber"), OreBracketHandler.getOre((String)"plateThaumium")}});
        Research.setAspects((String)"THAUMATORIUM", (String)"fabrico 12, aqua 9, permutatio 12, praecantatio 6, cognitio 3");
        Research.setComplexity((String)"THAUMATORIUM", (int)3);
        Research.setAspects((String)"TRANSIRON", (String)"metallum 6, ordo 3, permutatio 3");
        Research.setComplexity((String)"TRANSIRON", (int)1);
        Research.setAspects((String)"TRANSGOLD", (String)"metallum 9, lucrum 6, permutatio 3");
        Research.setComplexity((String)"TRANSGOLD", (int)2);
        Research.setAspects((String)"TRANSCOPPER", (String)"metallum 9, ordo 6, permutatio 3");
        Research.setComplexity((String)"TRANSCOPPER", (int)2);
        Research.setAspects((String)"TRANSTIN", (String)"metallum 9, vitreus 6, permutatio 3");
        Research.setComplexity((String)"TRANSTIN", (int)2);
        Research.setAspects((String)"TRANSLEAD", (String)"metallum 9, ordo 6, permutatio 3");
        Research.setComplexity((String)"TRANSLEAD", (int)2);
        Research.setAspects((String)"TRANSSLV);R", (String)"metallum 9, lucrum 6, permutatio 3");
        Research.setComplexity((String)"TRANSSLV);R", (int)2);
        Research.setAspects((String)"PUREIRON", (String)"metallum 6, ordo 6, vitreus 3");
        Research.setComplexity((String)"PUREIRON", (int)1);
        Research.setAspects((String)"PUREGOLD", (String)"metallum 9, lucrum 9, ordo 6, praecantatio 3");
        Research.setComplexity((String)"PUREGOLD", (int)2);
        Research.setAspects((String)"PURECOPPER", (String)"metallum 9, ordo 9, ordo 6, praecantatio 3");
        Research.setComplexity((String)"PURECOPPER", (int)2);
        Research.setAspects((String)"PURETIN", (String)"metallum 9, vitreus 9, ordo 6, praecantatio 3");
        Research.setComplexity((String)"PURETIN", (int)2);
        Research.setAspects((String)"PURELEAD", (String)"metallum 9, permutatio 9, ordo 6, praecantatio 3");
        Research.setComplexity((String)"PURELEAD", (int)2);
        Research.setAspects((String)"PURESLV);R", (String)"metallum 9, lucrum 9, ordo 6, praecantatio 3");
        Research.setComplexity((String)"PURESLV);R", (int)2);
        Arcane.addShaped((String)"JARLABEL", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:blockJar", (int)0), (String)"aqua 2", (IIngredient[][])new IIngredient[][]{{OreBracketHandler.getOre((String)"paneGlassColorless"), OreBracketHandler.getOre((String)"plateAnyRubber"), OreBracketHandler.getOre((String)"paneGlassColorless")}, {OreBracketHandler.getOre((String)"paneGlassColorless"), null, OreBracketHandler.getOre((String)"paneGlassColorless")}, {OreBracketHandler.getOre((String)"paneGlassColorless"), OreBracketHandler.getOre((String)"paneGlassColorless"), OreBracketHandler.getOre((String)"paneGlassColorless")}});
        Research.clearPages((String)"JARVOID");
        Research.addPage((String)"JARVOID", (String)"tc.research_page.JARVOID.1");
        Infusion.addRecipe((String)"JARVOID", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:blockJar", (int)0), (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)17804), ItemBracketHandler.getItem((String)"minecraft:blaze_powder", (int)0), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)17533), ItemBracketHandler.getItem((String)"Thaumcraft:ItemNugget", (int)5)}, (String)"vacuos 7, praecantatio 7, perditio 7, aqua 7", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:blockJar", (int)3), (int)2);
        Research.addInfusionPage((String)"JARVOID", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:blockJar", (int)3));
        Research.setAspects((String)"JARVOID", (String)"vacuos 6, perditio 6, praecantatio 6, perditio 3");
        Research.setComplexity((String)"JARVOID", (int)1);
        Crucible.addRecipe((String)"BATHSALTS", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemBathSalts", (int)0).amount(2), (IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)14), (String)"sano 10, cognitio 10, auram 10, ordo 10");
        Research.setAspects((String)"BATHSALTS", (String)"sano 9, cognitio 6, auram 9, ordo 6, praecantatio 3");
        Research.setComplexity((String)"BATHSALTS", (int)2);
        Crucible.addRecipe((String)"SANESOAP", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemSanitySoap", (int)0).amount(2), (IIngredient)ItemBracketHandler.getItem((String)"chisel:tallow", (int)0), (String)"alienis 20, cognitio 20, sano 20, ordo 20");
        Research.setAspects((String)"SANESOAP", (String)"sano 12, alienis 12, cognitio 9, ordo 6, praecantatio 3");
        Research.setComplexity((String)"SANESOAP", (int)3);
        Research.clearPages((String)"ARCANESPA");
        Research.addPage((String)"ARCANESPA", (String)"tc.research_page.ARCANESPA.1");
        Infusion.addRecipe((String)"ARCANESPA", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:blockJar", (int)0), (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"dreamcraft:item.StainlessSteelBars", (int)0), ItemBracketHandler.getItem((String)"minecraft:quartz_block", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:blockCosmeticSolid", (int)6), ItemBracketHandler.getItem((String)"Thaumcraft:blockCosmeticSolid", (int)7), ItemBracketHandler.getItem((String)"Thaumcraft:ItemBathSalts", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:blockCosmeticSolid", (int)7), ItemBracketHandler.getItem((String)"Thaumcraft:blockCosmeticSolid", (int)6), ItemBracketHandler.getItem((String)"minecraft:quartz_block", (int)0)}, (String)"ordo 24, praecantatio 16, sano 16, aqua 32, machina 8", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:blockStoneDevice", (int)12), (int)4);
        Research.addInfusionPage((String)"ARCANESPA", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:blockStoneDevice", (int)12));
        Research.setAspects((String)"ARCANESPA", (String)"ordo 9, aqua 9, machina 6, sano 6, praecantatio 3");
        Research.setComplexity((String)"ARCANESPA", (int)3);
        Research.setAspects((String)"LIQUIDDEATH", (String)"aqua 9, mortuus 9, perditio 6, venenum 6, tenebrae 3");
        Research.setComplexity((String)"LIQUIDDEATH", (int)3);
        Research.setAspects((String)"ETHEREALBLOOM", (String)"vitium 9, praecantatio 9, sano 6, herba 6, lux 3, terra 3");
        Research.setComplexity((String)"ETHEREALBLOOM", (int)3);
        Research.setAspects((String)"BOTTLETAINT", (String)"vitium 12, praecantatio 12, aqua 12, perditio 9, tenebrae 9, venenum 6, strontio 3");
        Research.setComplexity((String)"BOTTLETAINT", (int)3);
        Warp.addToResearch((String)"BOTTLETAINT", (int)5);
        Warp.addToItem((IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemBottleTaint", (int)0), (int)1);
        Crucible.addRecipe((String)"THAUMIUM", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)2), (IIngredient)ItemBracketHandler.getItem((String)"minecraft:iron_ingot", (int)0), (String)"praecantatio 4");
        Compressor.addRecipe((IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:blockCosmeticSolid", (int)5), (IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)4).amount(9));
        Pulverizer.addRecipe((IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)14)}, (IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)6), (int[])new int[]{10000}, (int)300, (int)2);
        Pulverizer.addRecipe((IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)4).amount(9)}, (IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:blockCosmeticSolid", (int)5), (int[])new int[]{10000}, (int)300, (int)2);
        Research.refreshResearchRecipe((String)"CRUCIBLE");
        Research.refreshResearchRecipe((String)"TALLOW");
        Research.refreshResearchRecipe((String)"NITOR");
        Research.refreshResearchRecipe((String)"ALUMENTUM");
        Research.refreshResearchRecipe((String)"THAUMIUM");
        Research.refreshResearchRecipe((String)"DISTILESSENTIA");
        Research.refreshResearchRecipe((String)"JARLABEL");
        Research.refreshResearchRecipe((String)"JARVOID");
        Research.refreshResearchRecipe((String)"ALCHEMICALDUPLICATION");
        Research.refreshResearchRecipe((String)"ALCHEMICALMANUFACTURE");
        Research.refreshResearchRecipe((String)"THAUMATORIUM");
        Research.refreshResearchRecipe((String)"ENTROPICPROCESSING");
        Research.refreshResearchRecipe((String)"BATHSALTS");
        Research.refreshResearchRecipe((String)"SANESOAP");
        Research.refreshResearchRecipe((String)"ARCANESPA");
        Research.refreshResearchRecipe((String)"TUBES");
        Research.refreshResearchRecipe((String)"TUBEFILTER");
        Research.refreshResearchRecipe((String)"CENTRIFUGE");
        Research.refreshResearchRecipe((String)"ESSENTIACRYSTAL");
        Research.refreshResearchRecipe((String)"TRANSIRON");
        Research.refreshResearchRecipe((String)"TRANSGOLD");
        Research.refreshResearchRecipe((String)"TRANSCOPPER");
        Research.refreshResearchRecipe((String)"TRANSTIN");
        Research.refreshResearchRecipe((String)"TRANSLEAD");
        Research.refreshResearchRecipe((String)"TRANSSLV);R");
        Research.refreshResearchRecipe((String)"PUREIRON");
        Research.refreshResearchRecipe((String)"PUREGOLD");
        Research.refreshResearchRecipe((String)"PURECOPPER");
        Research.refreshResearchRecipe((String)"PURETIN");
        Research.refreshResearchRecipe((String)"PURELEAD");
        Research.refreshResearchRecipe((String)"PURESLV);R");
        Research.refreshResearchRecipe((String)"LIQUIDDEATH");
    }
}

