package com.github.GTNH2Mega.fromScripts;
import java.util.HashMap;
import minetweaker.MineTweakerAPI;
import minetweaker.api.data.IData;
import minetweaker.api.item.IIngredient;
import minetweaker.api.item.IItemStack;
import minetweaker.expand.ExpandAnyDict;
import minetweaker.expand.ExpandByte;
import minetweaker.expand.ExpandInt;
import minetweaker.expand.ExpandString;
import minetweaker.mc1710.brackets.ItemBracketHandler;
import minetweaker.mc1710.brackets.OreBracketHandler;
import modtweaker2.mods.thaumcraft.handlers.Arcane;
import modtweaker2.mods.thaumcraft.handlers.Infusion;
import modtweaker2.mods.thaumcraft.handlers.Research;
import modtweaker2.mods.thaumcraft.handlers.Warp;
import stanhebben.zenscript.value.IAny;
import static com.github.GTNH2Mega.VoltageLevels.*;

public class Thaumcraft02Thaumaturgy1
implements Runnable {
    public void run() {
        IItemStack iItemStack = ItemBracketHandler.getItem("thaumicbases:resource", 2);
        Arcane.removeRecipe(iItemStack);
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("Thaumcraft:WandCap", 0));
        MineTweakerAPI.recipes.remove(ItemBracketHandler.getItem("Thaumcraft:WandCasting", 0));
        Arcane.removeRecipe(ItemBracketHandler.getItem("Thaumcraft:WandCap", 32767));
        Infusion.removeRecipe(ItemBracketHandler.getItem("Thaumcraft:WandCap", 32767));
        Arcane.removeRecipe(ItemBracketHandler.getItem("Thaumcraft:WandRod", 0));
        Infusion.removeRecipe(ItemBracketHandler.getItem("Thaumcraft:WandRod", 1));
        Infusion.removeRecipe(ItemBracketHandler.getItem("Thaumcraft:WandRod", 3));
        Infusion.removeRecipe(ItemBracketHandler.getItem("Thaumcraft:WandRod", 4));
        Infusion.removeRecipe(ItemBracketHandler.getItem("Thaumcraft:WandRod", 5));
        Infusion.removeRecipe(ItemBracketHandler.getItem("Thaumcraft:WandRod", 6));
        Infusion.removeRecipe(ItemBracketHandler.getItem("Thaumcraft:WandRod", 7));
        Infusion.removeRecipe(ItemBracketHandler.getItem("Thaumcraft:WandRod", 2));
        Arcane.removeRecipe(ItemBracketHandler.getItem("Thaumcraft:WandRod", 50));
        Arcane.removeRecipe(ItemBracketHandler.getItem("Thaumcraft:WandRod", 51));
        Arcane.removeRecipe(ItemBracketHandler.getItem("Thaumcraft:WandRod", 52));
        Arcane.removeRecipe(ItemBracketHandler.getItem("Thaumcraft:WandRod", 53));
        Arcane.removeRecipe(ItemBracketHandler.getItem("Thaumcraft:WandRod", 54));
        Arcane.removeRecipe(ItemBracketHandler.getItem("Thaumcraft:WandRod", 55));
        Arcane.removeRecipe(ItemBracketHandler.getItem("Thaumcraft:WandRod", 56));
        Arcane.removeRecipe(ItemBracketHandler.getItem("Thaumcraft:WandRod", 57));
        Arcane.removeRecipe(ItemBracketHandler.getItem("Thaumcraft:FocusFire", 0));
        Arcane.removeRecipe(ItemBracketHandler.getItem("Thaumcraft:FocusExcavation", 0));
        Arcane.removeRecipe(ItemBracketHandler.getItem("Thaumcraft:FocusFrost", 0));
        Arcane.removeRecipe(ItemBracketHandler.getItem("Thaumcraft:FocusShock", 0));
        Arcane.removeRecipe(ItemBracketHandler.getItem("Thaumcraft:FocusTrade", 0));
        Arcane.removeRecipe(ItemBracketHandler.getItem("Thaumcraft:FocusPouch", 0));
        Arcane.removeRecipe(ItemBracketHandler.getItem("Thaumcraft:blockStoneDevice", 9));
        Infusion.removeRecipe(ItemBracketHandler.getItem("Thaumcraft:blockStoneDevice", 10));
        Arcane.removeRecipe(ItemBracketHandler.getItem("Thaumcraft:blockStoneDevice", 11));
        Arcane.removeRecipe(ItemBracketHandler.getItem("Thaumcraft:blockMetalDevice", 14));
        Infusion.removeRecipe(ItemBracketHandler.getItem("Thaumcraft:blockStoneDevice", 5));
        Infusion.removeRecipe(ItemBracketHandler.getItem("Thaumcraft:FocusWarding", 0));
        Infusion.removeRecipe(ItemBracketHandler.getItem("Thaumcraft:FocusPortableHole", 0));
        Infusion.removeRecipe(ItemBracketHandler.getItem("Thaumcraft:FocusHellbat", 0));
        Infusion.removeRecipe(ItemBracketHandler.getItem("Thaumcraft:ItemAmuletVis", 1));
        Infusion.removeRecipe(ItemBracketHandler.getItem("Thaumcraft:blockStoneDevice", 8));
        Arcane.removeRecipe(ItemBracketHandler.getItem("Thaumcraft:blockMetalDevice", 2));
        Arcane.removeRecipe(ItemBracketHandler.getItem("Thaumcraft:blockStoneDevice", 13));
        Research.clearPages("BASICTHAUMATURGY");
        Research.addPage("BASICTHAUMATURGY", "tc.research_page.BASICTHAUMATURGY.1");
        Research.addPage("BASICTHAUMATURGY", "tc.research_page.BASICTHAUMATURGY.2");
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem("Thaumcraft:WandCap", 0), new IIngredient[][]{{OreBracketHandler.getOre("screwIron"), OreBracketHandler.getOre("foilIron"), OreBracketHandler.getOre("screwIron")}, {OreBracketHandler.getOre("foilIron"), OreBracketHandler.getOre("ringIron"), OreBracketHandler.getOre("foilIron")}, {OreBracketHandler.getOre("screwIron"), OreBracketHandler.getOre("foilIron"), OreBracketHandler.getOre("screwIron")}}, null);
        Research.addCraftingPage("BASICTHAUMATURGY", ItemBracketHandler.getItem("Thaumcraft:WandCap", 0));
        IItemStack iItemStack2 = ItemBracketHandler.getItem("Thaumcraft:WandCasting", 0);
        HashMap<String, IData> hashMap = new HashMap<String, IData>();
        hashMap.put("aqua", ExpandInt.toData(0));
        hashMap.put("terra", ExpandInt.toData(0));
        hashMap.put("ignis", ExpandInt.toData(0));
        hashMap.put("ordo", ExpandInt.toData(0));
        hashMap.put("perditio", ExpandInt.toData(0));
        hashMap.put("aer", ExpandInt.toData(0));
        MineTweakerAPI.recipes.addShaped(iItemStack2.withTag(ExpandAnyDict.asData(hashMap)), new IIngredient[][]{{ItemBracketHandler.getItem("TwilightForest:item.nagaScale", 0), OreBracketHandler.getOre("screwAluminium"), ItemBracketHandler.getItem("Thaumcraft:WandCap", 0)}, {OreBracketHandler.getOre("screwAluminium"), ItemBracketHandler.getItem("Forestry:oakStick", 0), OreBracketHandler.getOre("screwAluminium")}, {ItemBracketHandler.getItem("Thaumcraft:WandCap", 0), OreBracketHandler.getOre("screwAluminium"), ItemBracketHandler.getItem("TwilightForest:item.nagaScale", 0)}}, null);
        Research.addCraftingPage("BASICTHAUMATURGY", ItemBracketHandler.getItem("Thaumcraft:WandCasting", 0));
        Research.clearPages("CAP_copper");
        Research.addPage("CAP_copper", "tc.research_page.CAP_copper.1");
        Arcane.addShaped("CAP_copper", ItemBracketHandler.getItem("Thaumcraft:WandCap", 3), "ordo 15, ignis 15, aer 15", new IIngredient[][]{{OreBracketHandler.getOre("screwSteel"), OreBracketHandler.getOre("foilCopper"), OreBracketHandler.getOre("screwSteel")}, {OreBracketHandler.getOre("foilCopper"), OreBracketHandler.getOre("ringCopper"), OreBracketHandler.getOre("foilCopper")}, {OreBracketHandler.getOre("screwSteel"), OreBracketHandler.getOre("foilCopper"), OreBracketHandler.getOre("screwSteel")}});
        Research.addArcanePage("CAP_copper", ItemBracketHandler.getItem("Thaumcraft:WandCap", 3));
        Research.setAspects("CAP_copper", "instrumentum 3, metallum 6, permutatio 6");
        Research.setComplexity("CAP_copper", 1);
        Research.addPage("SCEPTRE", "tc.research_page.RESEARCH.1");
        IItemStack iItemStack3 = ItemBracketHandler.getItem("Thaumcraft:WandCasting", 2);
        HashMap<String, IData> hashMap2 = new HashMap<String, IData>();
        hashMap2.put("cap", ExpandString.asData("copper"));
        hashMap2.put("rod", ExpandString.asData("wood"));
        Research.addArcanePage("CAP_copper", iItemStack3.withTag(ExpandAnyDict.asData(hashMap2)));
        Research.clearPages("CAP_gold");
        Research.addPage("CAP_gold", "tc.research_page.CAP_gold.1");
        Arcane.addShaped("CAP_gold", ItemBracketHandler.getItem("Thaumcraft:WandCap", 1), "ordo 20, ignis 20, aer 20", new IIngredient[][]{{OreBracketHandler.getOre("screwAluminium"), OreBracketHandler.getOre("foilGold"), OreBracketHandler.getOre("screwAluminium")}, {OreBracketHandler.getOre("foilGold"), OreBracketHandler.getOre("ringGold"), OreBracketHandler.getOre("foilGold")}, {OreBracketHandler.getOre("screwAluminium"), OreBracketHandler.getOre("foilGold"), OreBracketHandler.getOre("screwAluminium")}});
        Research.addArcanePage("CAP_gold", ItemBracketHandler.getItem("Thaumcraft:WandCap", 1));
        Research.setAspects("CAP_gold", "instrumentum 9, metallum 6, lucrum 3");
        Research.setComplexity("CAP_gold", 2);
        IItemStack iItemStack4 = ItemBracketHandler.getItem("Thaumcraft:WandCasting", 3);
        HashMap<String, IData> hashMap3 = new HashMap<String, IData>();
        hashMap3.put("cap", ExpandString.asData("gold"));
        hashMap3.put("rod", ExpandString.asData("wood"));
        Research.addArcanePage("CAP_gold", iItemStack4.withTag(ExpandAnyDict.asData(hashMap3)));
        Research.clearPages("CAP_silver");
        Research.addPage("CAP_silver", "tc.research_page.CAP_silver.1");
        Arcane.addShaped("CAP_silver", ItemBracketHandler.getItem("Thaumcraft:WandCap", 5), "ordo 25, ignis 25, aer 25", new IIngredient[][]{{OreBracketHandler.getOre("screwStainlessSteel"), OreBracketHandler.getOre("foilSilver"), OreBracketHandler.getOre("screwStainlessSteel")}, {OreBracketHandler.getOre("foilSilver"), OreBracketHandler.getOre("ringSilver"), OreBracketHandler.getOre("foilSilver")}, {OreBracketHandler.getOre("screwStainlessSteel"), OreBracketHandler.getOre("foilSilver"), OreBracketHandler.getOre("screwStainlessSteel")}});
        Research.addArcanePage("CAP_silver", ItemBracketHandler.getItem("Thaumcraft:WandCap", 5));
        Infusion.addRecipe("CAP_silver", ItemBracketHandler.getItem("Thaumcraft:WandCap", 5), new IItemStack[]{ItemBracketHandler.getItem("Thaumcraft:ItemResource", 14), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 2054), ItemBracketHandler.getItem("Thaumcraft:ItemResource", 14), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 2054), ItemBracketHandler.getItem("Thaumcraft:ItemResource", 14), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 2054)}, "auram 18, potentia 30, praecantatio 18", ItemBracketHandler.getItem("Thaumcraft:WandCap", 4), 5);
        Research.addInfusionPage("CAP_silver", ItemBracketHandler.getItem("Thaumcraft:WandCap", 4));
        IItemStack iItemStack5 = ItemBracketHandler.getItem("Thaumcraft:WandCasting", 4);
        HashMap<String, IData> hashMap4 = new HashMap<String, IData>();
        hashMap4.put("cap", ExpandString.asData("silver"));
        hashMap4.put("rod", ExpandString.asData("wood"));
        Research.addArcanePage("CAP_silver", iItemStack5.withTag(ExpandAnyDict.asData(hashMap4)));
        Research.clearPages("CAP_thaumium");
        Research.addPage("CAP_thaumium", "tc.research_page.CAP_thaumium.1");
        Arcane.addShaped("CAP_thaumium", ItemBracketHandler.getItem("Thaumcraft:WandCap", 6), "ordo 30, ignis 30, aer 30", new IIngredient[][]{{OreBracketHandler.getOre("screwTitanium"), OreBracketHandler.getOre("foilThaumium"), OreBracketHandler.getOre("screwTitanium")}, {OreBracketHandler.getOre("foilThaumium"), OreBracketHandler.getOre("ringThaumium"), OreBracketHandler.getOre("foilThaumium")}, {OreBracketHandler.getOre("screwTitanium"), OreBracketHandler.getOre("foilThaumium"), OreBracketHandler.getOre("screwTitanium")}});
        Research.addArcanePage("CAP_thaumium", ItemBracketHandler.getItem("Thaumcraft:WandCap", 6));
        Infusion.addRecipe("CAP_thaumium", ItemBracketHandler.getItem("Thaumcraft:WandCap", 6), new IItemStack[]{ItemBracketHandler.getItem("Thaumcraft:ItemResource", 14), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 2330), ItemBracketHandler.getItem("Thaumcraft:ItemResource", 14), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 2330), ItemBracketHandler.getItem("Thaumcraft:ItemResource", 14), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 2330)}, "auram 25, potentia 40, praecantatio 25", ItemBracketHandler.getItem("Thaumcraft:WandCap", 2), 5);
        Research.addInfusionPage("CAP_thaumium", ItemBracketHandler.getItem("Thaumcraft:WandCap", 2));
        Research.setAspects("CAP_thaumium", "instrumentum 6, auram 9, metallum 12, praecantatio 3");
        Research.setComplexity("CAP_thaumium", 3);
        IItemStack iItemStack6 = ItemBracketHandler.getItem("Thaumcraft:WandCasting", 6);
        HashMap<String, IData> hashMap5 = new HashMap<String, IData>();
        hashMap5.put("cap", ExpandString.asData("thaumium"));
        hashMap5.put("rod", ExpandString.asData("wood"));
        Research.addArcanePage("CAP_thaumium", iItemStack6.withTag(ExpandAnyDict.asData(hashMap5)));
        Research.clearPages("SCEPTRE");
        Research.addPage("SCEPTRE", "tc.research_page.SCEPTRE.1");
        IItemStack iItemStack7 = ItemBracketHandler.getItem("Thaumcraft:WandCasting", 1);
        HashMap<String, IData> hashMap6 = new HashMap<String, IData>();
        hashMap6.put("cap", ExpandString.asData("iron"));
        hashMap6.put("rod", ExpandString.asData("wood"));
        hashMap6.put("sceptre", ExpandInt.toData(1));
        Research.addArcanePage("SCEPTRE", iItemStack7.withTag(ExpandAnyDict.asData(hashMap6)));
        Research.setAspects("SCEPTRE", "instrumentum 12, fabrico 12, arbor 9, praecantatio 6, cognitio 3");
        Research.setComplexity("SCEPTRE", 3);
        IItemStack iItemStack8 = ItemBracketHandler.getItem("Thaumcraft:WandCasting", 9);
        HashMap<String, IData> hashMap7 = new HashMap<String, IData>();
        hashMap7.put("cap", ExpandString.asData("thaumium"));
        hashMap7.put("rod", ExpandString.asData("wood"));
        Research.addArcanePage("SCEPTRE", iItemStack8.withTag(ExpandAnyDict.asData(hashMap7)));
        Research.clearPages("ROD_greatwood");
        Research.addPage("ROD_greatwood", "tc.research_page.ROD_greatwood.1");
        Arcane.addShaped("ROD_greatwood", ItemBracketHandler.getItem("Thaumcraft:WandRod", 0), "aer 20, terra 20, ignis 20, aqua 20, ordo 20, perditio 20", new IIngredient[][]{{null, null, ItemBracketHandler.getItem("Thaumcraft:blockMagicalLog", 0)}, {null, ItemBracketHandler.getItem("Thaumcraft:blockMagicalLog", 0), null}, {ItemBracketHandler.getItem("Thaumcraft:blockMagicalLog", 0), null, null}});
        Research.addArcanePage("ROD_greatwood", ItemBracketHandler.getItem("Thaumcraft:WandRod", 0));
        Research.setAspects("ROD_greatwood", "instrumentum 9, praecantatio 6, arbor 3");
        Research.setComplexity("ROD_greatwood", 2);
        IItemStack iItemStack9 = ItemBracketHandler.getItem("Thaumcraft:WandCasting", 9);
        HashMap<String, IData> hashMap8 = new HashMap<String, IData>();
        hashMap8.put("cap", ExpandString.asData("gold"));
        hashMap8.put("rod", ExpandString.asData("greatwood"));
        Research.addArcanePage("ROD_greatwood", iItemStack9.withTag(ExpandAnyDict.asData(hashMap8)));
        IItemStack iItemStack10 = ItemBracketHandler.getItem("Thaumcraft:WandCasting", 13);
        HashMap<String, IData> hashMap9 = new HashMap<String, IData>();
        hashMap9.put("cap", ExpandString.asData("gold"));
        hashMap9.put("rod", ExpandString.asData("greatwood"));
        hashMap9.put("sceptre", ExpandByte.asData((byte)1));
        Research.addArcanePage("SCEPTRE", iItemStack10.withTag(ExpandAnyDict.asData(hashMap9)));
        Infusion.addRecipe("ROD_reed", ItemBracketHandler.getItem("TConstruct:trap.punji", 0), new IItemStack[]{ItemBracketHandler.getItem("Thaumcraft:ItemShard", 6), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 0), ItemBracketHandler.getItem("Thaumcraft:ItemShard", 6), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 0)}, "aer 24, motus 12, praecantatio 12, vitreus 6", ItemBracketHandler.getItem("Thaumcraft:WandRod", 5), 2);
        Research.setAspects("ROD_reed", "instrumentum 9, praecantatio 9, aer 6, herba 6, arbor 3");
        Research.setComplexity("ROD_reed", 2);
        IItemStack iItemStack11 = ItemBracketHandler.getItem("Thaumcraft:WandCasting", 24);
        HashMap<String, IData> hashMap10 = new HashMap<String, IData>();
        hashMap10.put("cap", ExpandString.asData("silver"));
        hashMap10.put("rod", ExpandString.asData("reed"));
        Research.addArcanePage("ROD_reed", iItemStack11.withTag(ExpandAnyDict.asData(hashMap10)));
        IItemStack iItemStack12 = ItemBracketHandler.getItem("Thaumcraft:WandCasting", 45);
        HashMap<String, IData> hashMap11 = new HashMap<String, IData>();
        hashMap11.put("cap", ExpandString.asData("thaumium"));
        hashMap11.put("rod", ExpandString.asData("reed"));
        hashMap11.put("sceptre", ExpandByte.asData((byte)1));
        Research.addArcanePage("SCEPTRE", iItemStack12.withTag(ExpandAnyDict.asData(hashMap11)));
        Infusion.addRecipe("ROD_blaze", ItemBracketHandler.getItem("minecraft:blaze_rod", 0), new IItemStack[]{ItemBracketHandler.getItem("Thaumcraft:ItemShard", 6), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 1), ItemBracketHandler.getItem("Thaumcraft:ItemShard", 6), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 1)}, "bestia 12, ignis 24, praecantatio 12, vitreus 6", ItemBracketHandler.getItem("Thaumcraft:WandRod", 6), 2);
        Research.setAspects("ROD_blaze", "instrumentum 9, praecantatio 9, aer 6, herba 6, arbor 3");
        Research.setComplexity("ROD_blaze", 2);
        IItemStack iItemStack13 = ItemBracketHandler.getItem("Thaumcraft:WandCasting", 24);
        HashMap<String, IData> hashMap12 = new HashMap<String, IData>();
        hashMap12.put("cap", ExpandString.asData("thaumium"));
        hashMap12.put("rod", ExpandString.asData("blaze"));
        Research.addArcanePage("ROD_blaze", iItemStack13.withTag(ExpandAnyDict.asData(hashMap12)));
        Infusion.addRecipe("ROD_obsidian", ItemBracketHandler.getItem("RandomThings:ingredient", 1), new IItemStack[]{ItemBracketHandler.getItem("Thaumcraft:ItemShard", 6), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 3), ItemBracketHandler.getItem("Thaumcraft:ItemShard", 6), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 3)}, " praecantatio 12, tenebrae 12, terra 24, vitreus 6", ItemBracketHandler.getItem("Thaumcraft:WandRod", 1), 2);
        Research.setAspects("ROD_obsidian", "instrumentum 9, praecantatio 9, ignis 6, potentia 6, arbor 3");
        Research.setComplexity("ROD_obsidian", 2);
        IItemStack iItemStack14 = ItemBracketHandler.getItem("Thaumcraft:WandCasting", 36);
        HashMap<String, IData> hashMap13 = new HashMap<String, IData>();
        hashMap13.put("cap", ExpandString.asData("thaumium"));
        hashMap13.put("rod", ExpandString.asData("obsidian"));
        Research.addArcanePage("ROD_obsidian", iItemStack14.withTag(ExpandAnyDict.asData(hashMap13)));
        Infusion.addRecipe("ROD_ice", ItemBracketHandler.getItem("BiomesOPlenty:hardIce", 0), new IItemStack[]{ItemBracketHandler.getItem("Thaumcraft:ItemShard", 6), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 2), ItemBracketHandler.getItem("Thaumcraft:ItemShard", 6), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 2)}, " aqua 24, gelum 12, praecantatio 12, vitreus 6", ItemBracketHandler.getItem("Thaumcraft:WandRod", 3), 2);
        Research.setAspects("ROD_ice", "instrumentum 9, praecantatio 9, aqua 6, gelum 6, arbor 3");
        Research.setComplexity("ROD_ice", 2);
        IItemStack iItemStack15 = ItemBracketHandler.getItem("Thaumcraft:WandCasting", 36);
        HashMap<String, IData> hashMap14 = new HashMap<String, IData>();
        hashMap14.put("cap", ExpandString.asData("thaumium"));
        hashMap14.put("rod", ExpandString.asData("ice"));
        Research.addArcanePage("ROD_ice", iItemStack15.withTag(ExpandAnyDict.asData(hashMap14)));
        Infusion.addRecipe("ROD_quartz", ItemBracketHandler.getItem("dreamcraft:item.ChargedCertusQuartzRod", 0), new IItemStack[]{ItemBracketHandler.getItem("Thaumcraft:ItemShard", 6), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 4), ItemBracketHandler.getItem("Thaumcraft:ItemShard", 6), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 4)}, " ordo 24, praecantatio 12, potentia 12, vitreus 6", ItemBracketHandler.getItem("Thaumcraft:WandRod", 4), 2);
        Research.setAspects("ROD_quartz", "instrumentum 9, praecantatio 9, terra 6, ordo 6, arbor 3");
        Research.setComplexity("ROD_quartz", 2);
        IItemStack iItemStack16 = ItemBracketHandler.getItem("Thaumcraft:WandCasting", 36);
        HashMap<String, IData> hashMap15 = new HashMap<String, IData>();
        hashMap15.put("cap", ExpandString.asData("thaumium"));
        hashMap15.put("rod", ExpandString.asData("quartz"));
        Research.addArcanePage("ROD_quartz", iItemStack16.withTag(ExpandAnyDict.asData(hashMap15)));
        Infusion.addRecipe("ROD_bone", ItemBracketHandler.getItem("TConstruct:toolRod", 5), new IItemStack[]{ItemBracketHandler.getItem("Thaumcraft:ItemShard", 6), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 5), ItemBracketHandler.getItem("Thaumcraft:ItemShard", 6), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 5)}, " exanimis 12, perditio 24, praecantatio 12, vitreus 6", ItemBracketHandler.getItem("Thaumcraft:WandRod", 7), 3);
        Research.setAspects("ROD_bone", "instrumentum 9, praecantatio 9, exanimis 6, perditio 6, arbor 3");
        Research.setComplexity("ROD_bone", 2);
        Warp.addToResearch("ROD_bone", 1);
        IItemStack iItemStack17 = ItemBracketHandler.getItem("Thaumcraft:WandCasting", 36);
        HashMap<String, IData> hashMap16 = new HashMap<String, IData>();
        hashMap16.put("cap", ExpandString.asData("thaumium"));
        hashMap16.put("rod", ExpandString.asData("bone"));
        Research.addArcanePage("ROD_bone", iItemStack17.withTag(ExpandAnyDict.asData(hashMap16)));
        Infusion.addRecipe("ROD_silverwood", ItemBracketHandler.getItem("Thaumcraft:blockMagicalLog", 1), new IItemStack[]{ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 0), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 1), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 2), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 3), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 4), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 5), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 6)}, " aer 48, aqua 48, ignis 48, ordo 48, perditio 48, praecantatio 48, terra 48", ItemBracketHandler.getItem("Thaumcraft:WandRod", 2), 5);
        Research.setAspects("ROD_silverwood", "instrumentum 12, praecantatio 12, cognitio 9, herba 6, arbor 3");
        Research.setComplexity("ROD_silverwood", 3);
        IItemStack iItemStack18 = ItemBracketHandler.getItem("Thaumcraft:WandCasting", 36);
        HashMap<String, IData> hashMap17 = new HashMap<String, IData>();
        hashMap17.put("cap", ExpandString.asData("thaumium"));
        hashMap17.put("rod", ExpandString.asData("silverwood"));
        Research.addArcanePage("ROD_silverwood", iItemStack18.withTag(ExpandAnyDict.asData(hashMap17)));
        Arcane.addShaped("ROD_greatwood_staff", ItemBracketHandler.getItem("Thaumcraft:WandRod", 50), "aer 50, terra 50, ignis 50, aqua 50, ordo 50, perditio 50", new IIngredient[][]{{ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 0), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 1), ItemBracketHandler.getItem("Thaumcraft:ItemResource", 15)}, {ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 2), ItemBracketHandler.getItem("Thaumcraft:WandRod", 0), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 3)}, {ItemBracketHandler.getItem("Thaumcraft:WandRod", 0), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 4), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 5)}});
        Research.setAspects("ROD_greatwood_staff", "instrumentum 12, praecantatio 12, arbor 9, ignis 6, aer 6, terra 3");
        Research.setComplexity("ROD_greatwood_staff", 3);
        IItemStack iItemStack19 = ItemBracketHandler.getItem("Thaumcraft:WandCasting", 48);
        HashMap<String, IData> hashMap18 = new HashMap<String, IData>();
        hashMap18.put("cap", ExpandString.asData("thaumium"));
        hashMap18.put("rod", ExpandString.asData("greatwood_staff"));
        Research.addArcanePage("ROD_greatwood_staff", iItemStack19.withTag(ExpandAnyDict.asData(hashMap18)));
        Arcane.addShaped("ROD_reed_staff", ItemBracketHandler.getItem("Thaumcraft:WandRod", 55), "aer 75, terra 75, ignis 75, aqua 75, ordo 75, perditio 75", new IIngredient[][]{{ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 0), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 1), ItemBracketHandler.getItem("Thaumcraft:ItemResource", 15)}, {ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 2), ItemBracketHandler.getItem("Thaumcraft:WandRod", 5), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 3)}, {ItemBracketHandler.getItem("Thaumcraft:WandRod", 5), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 4), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 5)}});
        Research.setAspects("ROD_reed_staff", "instrumentum 12, praecantatio 12, herba 9, aer 6, ignis 6, terra 3");
        Research.setComplexity("ROD_reed_staff", 3);
        IItemStack iItemStack20 = ItemBracketHandler.getItem("Thaumcraft:WandCasting", 42);
        HashMap<String, IData> hashMap19 = new HashMap<String, IData>();
        hashMap19.put("cap", ExpandString.asData("gold"));
        hashMap19.put("rod", ExpandString.asData("reed_staff"));
        Research.addArcanePage("ROD_reed_staff", iItemStack20.withTag(ExpandAnyDict.asData(hashMap19)));
        Arcane.addShaped("ROD_blaze_staff", ItemBracketHandler.getItem("Thaumcraft:WandRod", 56), "aer 75, terra 75, ignis 75, aqua 75, ordo 75, perditio 75", new IIngredient[][]{{ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 0), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 1), ItemBracketHandler.getItem("Thaumcraft:ItemResource", 15)}, {ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 2), ItemBracketHandler.getItem("Thaumcraft:WandRod", 6), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 3)}, {ItemBracketHandler.getItem("Thaumcraft:WandRod", 6), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 4), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 5)}});
        Research.setAspects("ROD_blaze_staff", "instrumentum 12, praecantatio 12, ignis 9, potentia 6, aer 6, terra 3");
        Research.setComplexity("ROD_blaze_staff", 3);
        IItemStack iItemStack21 = ItemBracketHandler.getItem("Thaumcraft:WandCasting", 56);
        HashMap<String, IData> hashMap20 = new HashMap<String, IData>();
        hashMap20.put("cap", ExpandString.asData("silver"));
        hashMap20.put("rod", ExpandString.asData("blaze_staff"));
        Research.addArcanePage("ROD_blaze_staff", iItemStack21.withTag(ExpandAnyDict.asData(hashMap20)));
        Arcane.addShaped("ROD_obsidian_staff", ItemBracketHandler.getItem("Thaumcraft:WandRod", 51), "aer 75, terra 75, ignis 75, aqua 75, ordo 75, perditio 75", new IIngredient[][]{{ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 0), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 1), ItemBracketHandler.getItem("Thaumcraft:ItemResource", 15)}, {ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 2), ItemBracketHandler.getItem("Thaumcraft:WandRod", 1), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 3)}, {ItemBracketHandler.getItem("Thaumcraft:WandRod", 1), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 4), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 5)}});
        Research.setAspects("ROD_obsidian_staff", "instrumentum 12, praecantatio 12, terra 9, ignis 6, aer 6, potentia 3");
        Research.setComplexity("ROD_obsidian_staff", 3);
        IItemStack iItemStack22 = ItemBracketHandler.getItem("Thaumcraft:WandCasting", 84);
        HashMap<String, IData> hashMap21 = new HashMap<String, IData>();
        hashMap21.put("cap", ExpandString.asData("thaumium"));
        hashMap21.put("rod", ExpandString.asData("obsidian_staff"));
        Research.addArcanePage("ROD_obsidian_staff", iItemStack22.withTag(ExpandAnyDict.asData(hashMap21)));
        Arcane.addShaped("ROD_ice_staff", ItemBracketHandler.getItem("Thaumcraft:WandRod", 53), "aer 75, terra 75, ignis 75, aqua 75, ordo 75, perditio 75", new IIngredient[][]{{ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 0), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 1), ItemBracketHandler.getItem("Thaumcraft:ItemResource", 15)}, {ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 2), ItemBracketHandler.getItem("Thaumcraft:WandRod", 3), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 3)}, {ItemBracketHandler.getItem("Thaumcraft:WandRod", 3), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 4), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 5)}});
        Research.setAspects("ROD_ice_staff", "instrumentum 12, praecantatio 12, gelum 9, aqua 6, aer 6, terra 3");
        Research.setComplexity("ROD_ice_staff", 3);
        Arcane.addShaped("ROD_quartz_staff", ItemBracketHandler.getItem("Thaumcraft:WandRod", 54), "aer 75, terra 75, ignis 75, aqua 75, ordo 75, perditio 75", new IIngredient[][]{{ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 0), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 1), ItemBracketHandler.getItem("Thaumcraft:ItemResource", 15)}, {ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 2), ItemBracketHandler.getItem("Thaumcraft:WandRod", 4), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 3)}, {ItemBracketHandler.getItem("Thaumcraft:WandRod", 4), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 4), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 5)}});
        Research.setAspects("ROD_quartz_staff", "instrumentum 12, praecantatio 12, vitreus 9, ordo 6, aer 6, terra 3");
        Research.setComplexity("ROD_quartz_staff", 3);
        Arcane.addShaped("ROD_bone_staff", ItemBracketHandler.getItem("Thaumcraft:WandRod", 57), "aer 75, terra 75, ignis 75, aqua 75, ordo 75, perditio 75", new IIngredient[][]{{ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 0), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 1), ItemBracketHandler.getItem("Thaumcraft:ItemResource", 15)}, {ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 2), ItemBracketHandler.getItem("Thaumcraft:WandRod", 7), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 3)}, {ItemBracketHandler.getItem("Thaumcraft:WandRod", 7), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 4), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 5)}});
        Research.setAspects("ROD_bone_staff", "instrumentum 12, praecantatio 12, exanimis 9, perditio 6, aer 6, terra 3");
        Research.setComplexity("ROD_bone_staff", 3);
        Warp.addToResearch("ROD_bone_staff", 3);
        Arcane.addShaped("ROD_silverwood_staff", ItemBracketHandler.getItem("Thaumcraft:WandRod", 52), "aer 125, terra 125, ignis 125, aqua 125, ordo 125, perditio 125", new IIngredient[][]{{ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 0), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 1), ItemBracketHandler.getItem("Thaumcraft:ItemResource", 15)}, {ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 2), ItemBracketHandler.getItem("Thaumcraft:WandRod", 2), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 3)}, {ItemBracketHandler.getItem("Thaumcraft:WandRod", 2), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 4), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 5)}});
        Research.setAspects("ROD_silverwood_staff", "instrumentum 15, praecantatio 15, arbor 12, ordo 9, aer 6, terra 3");
        Research.setComplexity("ROD_silverwood_staff", 4);
        IItemStack iItemStack23 = ItemBracketHandler.getItem("Thaumcraft:WandCasting", 144);
        HashMap<String, IData> hashMap22 = new HashMap<String, IData>();
        hashMap22.put("cap", ExpandString.asData("thaumium"));
        hashMap22.put("rod", ExpandString.asData("silverwood_staff"));
        Research.addArcanePage("ROD_silverwood_staff", iItemStack23.withTag(ExpandAnyDict.asData(hashMap22)));
        IItemStack iItemStack24 = ItemBracketHandler.getItem("Thaumcraft:WandCasting", 216);
        HashMap<String, IData> hashMap23 = new HashMap<String, IData>();
        hashMap23.put("cap", ExpandString.asData("thaumium"));
        hashMap23.put("rod", ExpandString.asData("silverwood_staff"));
        hashMap23.put("sceptre", ExpandByte.asData((byte)1));
        Research.addArcanePage("SCEPTRE", iItemStack24.withTag(ExpandAnyDict.asData(hashMap23)));
        Arcane.addShaped("FOCUSFIRE", ItemBracketHandler.getItem("Thaumcraft:FocusFire", 0), "ignis 20, perditio 20, ordo 20", new IIngredient[][]{{ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 1), OreBracketHandler.getOre("gemQuartz"), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 1)}, {OreBracketHandler.getOre("gemQuartz"), OreBracketHandler.getOre("lensRuby"), OreBracketHandler.getOre("gemQuartz")}, {ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 1), OreBracketHandler.getOre("gemQuartz"), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 1)}});
        Research.setAspects("FOCUSFIRE", "ignis 6, praecantatio 6, motus 3");
        Research.setComplexity("FOCUSFIRE", 1);
        Arcane.addShaped("FOCUSEXCAVATION", ItemBracketHandler.getItem("Thaumcraft:FocusExcavation", 0), "terra 30, perditio 20, ordo 20", new IIngredient[][]{{ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 3), OreBracketHandler.getOre("gemQuartz"), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 3)}, {OreBracketHandler.getOre("gemQuartz"), OreBracketHandler.getOre("lensEmerald"), OreBracketHandler.getOre("gemQuartz")}, {ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 3), OreBracketHandler.getOre("gemQuartz"), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 3)}});
        Research.setAspects("FOCUSEXCAVATION", "terra 9, praecantatio 9, perditio 6, motus 3");
        Research.setComplexity("FOCUSEXCAVATION", 2);
        Arcane.addShaped("FOCUSFROST", ItemBracketHandler.getItem("Thaumcraft:FocusFrost", 0), "aqua 30, perditio 20, ordo 20", new IIngredient[][]{{ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 2), OreBracketHandler.getOre("gemQuartz"), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 2)}, {OreBracketHandler.getOre("gemQuartz"), OreBracketHandler.getOre("lensDiamond"), OreBracketHandler.getOre("gemQuartz")}, {ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 2), OreBracketHandler.getOre("gemQuartz"), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 2)}});
        Research.setAspects("FOCUSFROST", "aqua 9, gelum 9, praecantatio 6, motus 3");
        Research.setComplexity("FOCUSFROST", 2);
        Arcane.addShaped("FOCUSSHOCK", ItemBracketHandler.getItem("Thaumcraft:FocusShock", 0), "aer 30, perditio 20, ordo 20", new IIngredient[][]{{ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 0), OreBracketHandler.getOre("gemQuartz"), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 0)}, {OreBracketHandler.getOre("gemQuartz"), OreBracketHandler.getOre("lensGarnetYellow"), OreBracketHandler.getOre("gemQuartz")}, {ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 0), OreBracketHandler.getOre("gemQuartz"), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 0)}});
        Research.setAspects("FOCUSSHOCK", "aer 9, praecantatio 6, potentia 9, motus 3");
        Research.setComplexity("FOCUSSHOCK", 2);
        Arcane.addShaped("FOCUSTRADE", ItemBracketHandler.getItem("Thaumcraft:FocusTrade", 0), "aer 20, terra 20, perditio 30, ordo 30", new IIngredient[][]{{ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 6), OreBracketHandler.getOre("gemQuartz"), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 6)}, {OreBracketHandler.getOre("gemQuartz"), ItemBracketHandler.getItem("dreamcraft:item.ReinforcedGlassLense", 0), OreBracketHandler.getOre("gemQuartz")}, {ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 6), OreBracketHandler.getOre("gemQuartz"), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 6)}});
        Research.setAspects("FOCUSTRADE", "permutatio 9, praecantatio 9, terra 6, motus 3");
        Research.setComplexity("FOCUSTRADE", 2);
        Infusion.addRecipe("FOCUSWARDING", ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 24506), new IItemStack[]{ItemBracketHandler.getItem("Thaumcraft:ItemResource", 3), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 3), ItemBracketHandler.getItem("minecraft:quartz", 0), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 4), ItemBracketHandler.getItem("Thaumcraft:ItemResource", 3), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 3), ItemBracketHandler.getItem("minecraft:quartz", 0), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 4)}, "cognitio 15, ordo 25, terra 30, tutamen 25, praecantatio 10", ItemBracketHandler.getItem("Thaumcraft:FocusWarding", 0), 5);
        Research.setAspects("FOCUSWARDING", "terra 12, cognitio 12, ordo 9, tutamen 6, praecantatio 3");
        Research.setComplexity("FOCUSWARDING", 3);
        Infusion.addRecipe("FOCUSPORTABLEHOLE", ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 24532), new IItemStack[]{ItemBracketHandler.getItem("minecraft:quartz", 0), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 3), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 5), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 0), ItemBracketHandler.getItem("minecraft:quartz", 0), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 0), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 5), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 3)}, "alienis 40, iter 30, perditio 20, permutatio 10, praecantatio 5", ItemBracketHandler.getItem("Thaumcraft:FocusPortableHole", 0), 6);
        Research.setAspects("FOCUSPORTABLEHOLE", "aer 12, iter 12, alienis 9, perditio 6, praecantatio 3");
        Research.setComplexity("FOCUSPORTABLEHOLE", 3);
        Warp.addToResearch("NODESTABILIZERADV", 1);
        Infusion.addRecipe("FOCUSHELLBAT", ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 24347), new IItemStack[]{ItemBracketHandler.getItem("minecraft:quartz", 0), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 0), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 1), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 5), ItemBracketHandler.getItem("minecraft:quartz", 0), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 5), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 1), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 0)}, "aer 30, ignis 40, bestia 20, perditio 10, praecantatio 5", ItemBracketHandler.getItem("Thaumcraft:FocusHellbat", 0), 7);
        Research.setAspects("FOCUSHELLBAT", "praecantatio 12, iter 9, ignis 9, bestia 6, motus 3");
        Research.setComplexity("FOCUSHELLBAT", 3);
        Warp.addToResearch("NODESTABILIZERADV", 2);
        Warp.addToItem(ItemBracketHandler.getItem("Thaumcraft:FocusHellbat", 0), 2);
        Arcane.addShaped("FOCUSPOUCH", ItemBracketHandler.getItem("Thaumcraft:FocusPouch", 0), "terra 20, perditio 20, ordo 20", new IIngredient[][]{{OreBracketHandler.getOre("boltGold"), OreBracketHandler.getOre("ringGold"), OreBracketHandler.getOre("boltGold")}, {ItemBracketHandler.getItem("harvestcraft:hardenedleatherItem", 0), ItemBracketHandler.getItem("Thaumcraft:ItemBaubleBlanks", 2), ItemBracketHandler.getItem("harvestcraft:hardenedleatherItem", 0)}, {ItemBracketHandler.getItem("harvestcraft:hardenedleatherItem", 0), ItemBracketHandler.getItem("harvestcraft:hardenedleatherItem", 0), ItemBracketHandler.getItem("harvestcraft:hardenedleatherItem", 0)}});
        Research.setAspects("FOCUSPOUCH", "instrumentum 9, vacuos 9, praecantatio 6, pannus 3");
        Research.setComplexity("FOCUSPOUCH", 2);
        Arcane.addShaped("NODESTABILIZER", ItemBracketHandler.getItem("Thaumcraft:blockStoneDevice", 9), "aqua 35, terra 35, ordo 25", new IIngredient[][]{{OreBracketHandler.getOre("plateThaumium"), OreBracketHandler.getOre("springGold"), OreBracketHandler.getOre("plateThaumium")}, {OreBracketHandler.getOre("blockQuartz"), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32640), OreBracketHandler.getOre("blockQuartz")}, {ItemBracketHandler.getItem("Thaumcraft:blockCosmeticSolid", 7), ItemBracketHandler.getItem("Thaumcraft:ItemResource", 1), ItemBracketHandler.getItem("Thaumcraft:blockCosmeticSolid", 7)}});
        Research.setAspects("NODESTABILIZER", "auram 9, potentia 9, praecantatio 6, ordo 3");
        Research.setComplexity("NODESTABILIZER", 2);
        Infusion.addRecipe("NODESTABILIZERADV", ItemBracketHandler.getItem("Thaumcraft:blockStoneDevice", 9), new IItemStack[]{ItemBracketHandler.getItem("minecraft:redstone_block", 0), ItemBracketHandler.getItem("Thaumcraft:ItemResource", 1), ItemBracketHandler.getItem("minecraft:redstone_block", 0), ItemBracketHandler.getItem("Thaumcraft:ItemResource", 0), ItemBracketHandler.getItem("minecraft:glowstone", 0), ItemBracketHandler.getItem("minecraft:redstone_block", 0), ItemBracketHandler.getItem("Thaumcraft:ItemResource", 1), ItemBracketHandler.getItem("minecraft:redstone_block", 0), ItemBracketHandler.getItem("Thaumcraft:ItemResource", 0), ItemBracketHandler.getItem("minecraft:glowstone", 0)}, "auram 32, ordo 32, potentia 32, praecantatio 32", ItemBracketHandler.getItem("Thaumcraft:blockStoneDevice", 10), 10);
        Research.setAspects("NODESTABILIZERADV", "auram 12, potentia 9, praecantatio 9, ordo 6, alienis 3");
        Research.setComplexity("NODESTABILIZERADV", 3);
        Warp.addToResearch("NODESTABILIZERADV", 2);
        Arcane.addShaped("VISPOWER", ItemBracketHandler.getItem("Thaumcraft:blockStoneDevice", 11), "ignis 32, aer 32, perditio 32, ordo 32", new IIngredient[][]{{OreBracketHandler.getOre("blockRedstone"), ItemBracketHandler.getItem("ProjRed|Integration:projectred.integration.gate", 26), OreBracketHandler.getOre("blockRedstone")}, {OreBracketHandler.getOre("plateThaumium"), ItemBracketHandler.getItem("Thaumcraft:blockStoneDevice", 9), OreBracketHandler.getOre("plateThaumium")}, {OreBracketHandler.getOre("blockRedstone"), ItemBracketHandler.getItem("Thaumcraft:ItemResource", 1), OreBracketHandler.getOre("blockRedstone")}});
        Arcane.addShaped("VISPOWER", ItemBracketHandler.getItem("Thaumcraft:blockMetalDevice", 14), "ignis 10, ordo 10", new IIngredient[][]{{OreBracketHandler.getOre("screwSteel"), OreBracketHandler.getOre("lensDiamond"), OreBracketHandler.getOre("screwSteel")}, {OreBracketHandler.getOre("ringThaumium"), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 6), OreBracketHandler.getOre("ringThaumium")}, {OreBracketHandler.getOre("screwSteel"), OreBracketHandler.getOre("lensDiamond"), OreBracketHandler.getOre("screwSteel")}});
        Research.setAspects("VISPOWER", "auram 12, potentia 9, praecantatio 3, machina 6");
        Research.setComplexity("VISPOWER", 3);
        Infusion.addRecipe("WANDPED", ItemBracketHandler.getItem("Thaumcraft:blockStoneDevice", 1), new IItemStack[]{ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 17086), ItemBracketHandler.getItem("gregtech:gt.metaitem.02", 29500), ItemBracketHandler.getItem("Thaumcraft:ItemResource", 15), ItemBracketHandler.getItem("gregtech:gt.metaitem.02", 29500)}, "auram 10, permutatio 15, praecantatio 20, ordo 5", ItemBracketHandler.getItem("Thaumcraft:blockStoneDevice", 5), 2);
        Research.setAspects("WANDPED", "auram 12, potentia 9, praecantatio 3, permutatio 6");
        Research.setComplexity("WANDPED", 3);
        Infusion.addRecipe("VISAMULET", ItemBracketHandler.getItem("Thaumcraft:ItemBaubleBlanks", 0), new IItemStack[]{ItemBracketHandler.getItem("Thaumcraft:ItemResource", 15), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 6), ItemBracketHandler.getItem("gregtech:gt.metaitem.02", 30500), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 6), ItemBracketHandler.getItem("Thaumcraft:ItemResource", 15), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 6), ItemBracketHandler.getItem("gregtech:gt.metaitem.02", 30500), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 6)}, "vacuos 48, auram 48, potentia 88, praecantatio 88, vitreus 24", ItemBracketHandler.getItem("Thaumcraft:ItemAmuletVis", 1), 7);
        Research.setAspects("VISAMULET", "vacuos 15, auram 15, praecantatio 9, potentia 12, vitreus 6, tempus 3");
        Research.setComplexity("VISAMULET", 4);
        Infusion.addRecipe("WANDPEDFOC", ItemBracketHandler.getItem("ProjRed|Integration:projectred.integration.gate", 26), new IItemStack[]{ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 6), ItemBracketHandler.getItem("Thaumcraft:ItemResource", 8), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 6), ItemBracketHandler.getItem("Thaumcraft:ItemResource", 8), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 6), ItemBracketHandler.getItem("Thaumcraft:ItemResource", 8), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 6), ItemBracketHandler.getItem("Thaumcraft:ItemResource", 8)}, "ordo 25, permutatio 25, praecantatio 30, potentia 15, cognitio 15", ItemBracketHandler.getItem("Thaumcraft:blockStoneDevice", 8), 5);
        Research.setAspects("WANDPEDFOC", "instrumentum 15, auram 15, praecantatio 12, potentia 12, permutatio 9, cognitio 6, lucrum 3");
        Research.setComplexity("WANDPEDFOC", 4);
        Arcane.addShaped("VISCHARGERELAY", ItemBracketHandler.getItem("Thaumcraft:blockMetalDevice", 2), "ignis 20, ordo 20, aer 20, terra 10", new IIngredient[][]{{OreBracketHandler.getOre("screwThaumium"), ItemBracketHandler.getItem("Thaumcraft:blockMetalDevice", 14), OreBracketHandler.getOre("screwThaumium")}, {ItemBracketHandler.getItem("Thaumcraft:WandRod", 2), OreBracketHandler.getOre("plateThaumium"), ItemBracketHandler.getItem("Thaumcraft:WandRod", 2)}, {ItemBracketHandler.getItem("Thaumcraft:WandRod", 0), OreBracketHandler.getOre("craftingToolScrewdriver"), ItemBracketHandler.getItem("Thaumcraft:WandRod", 0)}});
        Research.setAspects("VISCHARGERELAY", "potentia 12, praecantatio 12, machina 9, auram 9, ignis 6, aer 3");
        Research.setComplexity("VISCHARGERELAY", 3);
        Arcane.addShaped("FOCALMANIPULATION", ItemBracketHandler.getItem("Thaumcraft:blockStoneDevice", 13), "ignis 64, ordo 64, aer 64, terra 64, aqua 64, perditio 64", new IIngredient[][]{{ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 6), ItemBracketHandler.getItem("Thaumcraft:blockCosmeticSlabStone", 0), ItemBracketHandler.getItem("Thaumcraft:blockCrystal", 6)}, {ItemBracketHandler.getItem("Thaumcraft:blockCosmeticSolid", 7), ItemBracketHandler.getItem("Thaumcraft:ItemResource", 15), ItemBracketHandler.getItem("Thaumcraft:blockCosmeticSolid", 7)}, {OreBracketHandler.getOre("plateThaumium"), ItemBracketHandler.getItem("Thaumcraft:blockTable", 0), OreBracketHandler.getOre("plateThaumium")}});
        Research.setAspects("FOCALMANIPULATION", "potentia 15, praecantatio 12, instrumentum 12, vitreus 9, fabrico 9, alienis 3, cognitio 5");
        Research.setComplexity("FOCALMANIPULATION", 4);
        Research.setAspects("VAMPBAT", "fames 15, praecantatio 15, victus 12, exanimis 12, cognitio 9, ira 3, alienis 6");
        Research.setComplexity("VAMPBAT", 4);
        Warp.addToResearch("VAMPBAT", 4);
        Research.refreshResearchRecipe("CAP_copper");
        Research.refreshResearchRecipe("CAP_gold");
        Research.refreshResearchRecipe("CAP_silver");
        Research.refreshResearchRecipe("CAP_thaumium");
        Research.refreshResearchRecipe("ROD_silverwood");
        Research.refreshResearchRecipe("ROD_greatwood_staff");
        Research.refreshResearchRecipe("FOCUSFIRE");
        Research.refreshResearchRecipe("FOCUSEXCAVATION");
        Research.refreshResearchRecipe("FOCUSFROST");
        Research.refreshResearchRecipe("FOCUSSHOCK");
        Research.refreshResearchRecipe("FOCUSTRADE");
        Research.refreshResearchRecipe("FOCUSWARDING");
        Research.refreshResearchRecipe("FOCUSPORTABLEHOLE");
        Research.refreshResearchRecipe("FOCUSHELLBAT");
        Research.refreshResearchRecipe("FOCUSPOUCH");
        Research.refreshResearchRecipe("NODESTABILIZER");
        Research.refreshResearchRecipe("NODESTABILIZERADV");
        Research.refreshResearchRecipe("VISPOWER");
        Research.refreshResearchRecipe("WANDPED");
        Research.refreshResearchRecipe("VISAMULET");
        Research.refreshResearchRecipe("WANDPEDFOC");
        Research.refreshResearchRecipe("VISCHARGERELAY");
        Research.refreshResearchRecipe("FOCALMANIPULATION");
        Research.refreshResearchRecipe("VAMPBAT");
    }
}

