package com.github.GTNH2Mega.fromScripts;
import gttweaker.mods.gregtech.machines.CuttingSaw;
import gttweaker.mods.gregtech.machines.PrecisionLaser;
import java.util.HashMap;
import minetweaker.MineTweakerAPI;
import minetweaker.api.data.IData;
import minetweaker.api.item.IIngredient;
import minetweaker.api.item.IItemStack;
import minetweaker.api.liquid.ILiquidStack;
import minetweaker.expand.ExpandAnyArray;
import minetweaker.expand.ExpandAnyDict;
import minetweaker.expand.ExpandInt;
import minetweaker.expand.ExpandString;
import minetweaker.mc1710.brackets.ItemBracketHandler;
import minetweaker.mc1710.brackets.LiquidBracketHandler;
import minetweaker.mc1710.brackets.OreBracketHandler;
import minetweaker.mods.ic2.machines.Compressor;
import modtweaker2.mods.thaumcraft.handlers.Arcane;
import modtweaker2.mods.thaumcraft.handlers.Crucible;
import modtweaker2.mods.thaumcraft.handlers.Infusion;
import modtweaker2.mods.thaumcraft.handlers.Research;
import modtweaker2.mods.thaumcraft.handlers.Warp;
import static com.github.GTNH2Mega.VoltageLevels.*;
public class ThaumicTinkerer01
implements Runnable {
    public void run() {
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:shareBook", (int)0));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:darkQuartzItem", (int)0));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:darkQuartz", (int)0));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:darkQuartz", (int)1));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:darkQuartz", (int)3));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:darkQuartzSlab", (int)0));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:interface", (int)0));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:connector", (int)0));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:dislocator", (int)0));
        Crucible.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:gaseousLightItem", (int)0));
        Crucible.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:gaseousShadowItem", (int)0));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:gasRemover", (int)0));
        Crucible.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:brightNitor", (int)0));
        Crucible.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:fireFire", (int)0));
        Crucible.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:fireWater", (int)0));
        Crucible.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:fireEarth", (int)0));
        Crucible.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:fireOrder", (int)0));
        Crucible.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:fireAir", (int)0));
        Crucible.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:fireChaos", (int)0));
        Infusion.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:infusedSeeds", (int)0));
        Crucible.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:infusedPotion", (int)0));
        Crucible.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:infusedPotion", (int)1));
        Crucible.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:infusedPotion", (int)2));
        Crucible.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:infusedPotion", (int)3));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:funnel", (int)0));
        Infusion.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:repairer", (int)0));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:magnet", (int)0));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:magnet", (int)1));
        Crucible.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:soulMould", (int)0));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:animationTablet", (int)0));
        Infusion.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:LevitationalLocomotive", (int)0));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:LevitationalLocomotiveRelay", (int)0));
        Infusion.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:cleansingTalisman", (int)0));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:platform", (int)0));
        Infusion.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:bloodSword", (int)0));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:spawner", (int)0));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:focusSmelt", (int)0));
        Infusion.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:focusFlight", (int)0));
        Infusion.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:focusDeflect", (int)0));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:focusEnderChest", (int)0));
        Infusion.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:focusTelekinesis", (int)0));
        Infusion.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:focusDislocation", (int)0));
        Infusion.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:focusHeal", (int)0));
        Infusion.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:enchanter", (int)0));
        Crucible.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:spellCloth", (int)0));
        Infusion.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:xpTalisman", (int)0));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:revealingHelm", (int)0));
        Research.orphanResearch((String)"SHARE_TOME");
        Research.removeResearch((String)"SHARE_TOME");
        Research.addResearch((String)"SHARETOME", (String)"TT_CATEGORY", (String)"cognitio 15, praecantatio 12, permutatio 9, instrumentum 6, terra 3", (int)0, (int)-1, (int)3, (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:shareBook", (int)0));
        MineTweakerAPI.game.setLocalization("tc.research_name.SHARETOME", "Tome of Knowledge Sharing");
        MineTweakerAPI.game.setLocalization("tc.research_text.SHARETOME", "[TT] A Goldfish's Diary");
        Research.addPrereq((String)"SHARETOME", (String)"INFUSION", (boolean)false);
        Research.setConcealed((String)"SHARETOME", (boolean)false);
        Research.addPage((String)"SHARETOME", (String)"ttresearch.page.SHARE_TOME.0");
        Infusion.addRecipe((String)"SHARETOME", (IItemStack)ItemBracketHandler.getItem((String)"minecraft:skull", (int)3), (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"minecraft:nether_star", (int)0), ItemBracketHandler.getItem((String)"minecraft:paper", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:ItemInkwell", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:ItemThaumonomicon", (int)0), ItemBracketHandler.getItem((String)"minecraft:paper", (int)0)}, (String)"cognitio 32, praecantatio 16, permutatio 32, pannus 16", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:shareBook", (int)0), (int)6);
        Research.addInfusionPage((String)"SHARETOME", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:shareBook", (int)0));
        Research.orphanResearch((String)"DARK_QUARTZ");
        Research.removeResearch((String)"DARK_QUARTZ");
        Research.addResearch((String)"DARKQUARTZ", (String)"TT_CATEGORY", (String)"null", (int)-2, (int)2, (int)1, (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:darkQuartzItem", (int)0));
        Research.setRound((String)"DARKQUARTZ", (boolean)true);
        Research.setAutoUnlock((String)"DARKQUARTZ", (boolean)true);
        MineTweakerAPI.game.setLocalization("tc.research_name.DARKQUARTZ", "Smokey Quartz");
        MineTweakerAPI.game.setLocalization("tc.research_text.DARKQUARTZ", "[TT] Shadow of the Day");
        Research.addPage((String)"DARKQUARTZ", (String)"ttresearch.page.DARK_QUARTZ.0");
        Arcane.addShaped((String)"DARKQUARTZ", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:darkQuartzItem", (int)0), (String)"perditio 8", (IIngredient[][])new IIngredient[][]{{OreBracketHandler.getOre((String)"gemQuartz"), OreBracketHandler.getOre((String)"gemQuartz"), OreBracketHandler.getOre((String)"gemQuartz")}, {OreBracketHandler.getOre((String)"gemQuartz"), OreBracketHandler.getOre((String)"coal"), OreBracketHandler.getOre((String)"gemQuartz")}, {OreBracketHandler.getOre((String)"gemQuartz"), OreBracketHandler.getOre((String)"gemQuartz"), OreBracketHandler.getOre((String)"gemQuartz")}});
        Arcane.addShaped((String)"DARKQUARTZ", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:darkQuartzItem", (int)0), (String)"perditio 8", (IIngredient[][])new IIngredient[][]{{OreBracketHandler.getOre((String)"gemQuartz"), OreBracketHandler.getOre((String)"gemQuartz"), OreBracketHandler.getOre((String)"gemQuartz")}, {OreBracketHandler.getOre((String)"gemQuartz"), OreBracketHandler.getOre((String)"charcoal"), OreBracketHandler.getOre((String)"gemQuartz")}, {OreBracketHandler.getOre((String)"gemQuartz"), OreBracketHandler.getOre((String)"gemQuartz"), OreBracketHandler.getOre((String)"gemQuartz")}});
        Research.addArcanePage((String)"DARKQUARTZ", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:darkQuartzItem", (int)0));
        Research.addCraftingPage((String)"DARKQUARTZ", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:darkQuartz", (int)2));
        Research.addCraftingPage((String)"DARKQUARTZ", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:darkQuartzSlab", (int)0));
        Research.addCraftingPage((String)"DARKQUARTZ", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:darkQuartzStairs", (int)0));
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem((String)"ThaumicTinkerer:darkQuartzSlab", (int)0).amount(2), (IIngredient[][])new IIngredient[][]{{OreBracketHandler.getOre((String)"craftingToolSaw"), ItemBracketHandler.getItem((String)"ThaumicTinkerer:darkQuartz", (int)0)}}, null);
        Research.addPrereq((String)"INTERFACE", (String)"INFUSION", (boolean)false);
        Research.addPrereq((String)"INTERFACE", (String)"DARKQUARTZ", (boolean)false);
        Research.setConcealed((String)"INTERFACE", (boolean)true);
        Arcane.addShaped((String)"INTERFACE", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:interface", (int)0), (String)"ordo 32, perditio 32, terra 16", (IIngredient[][])new IIngredient[][]{{ItemBracketHandler.getItem((String)"Thaumcraft:blockCosmeticSolid", (int)6), OreBracketHandler.getOre((String)"pipeLargeSteel"), ItemBracketHandler.getItem((String)"Thaumcraft:blockCosmeticSolid", (int)6)}, {OreBracketHandler.getOre((String)"pipeLargeElectrum"), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)32670), OreBracketHandler.getOre((String)"pipeLargeElectrum")}, {ItemBracketHandler.getItem((String)"Thaumcraft:blockCosmeticSolid", (int)6), OreBracketHandler.getOre((String)"pipeLargeSteel"), ItemBracketHandler.getItem((String)"Thaumcraft:blockCosmeticSolid", (int)6)}});
        Arcane.addShaped((String)"INTERFACE", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:connector", (int)0), (String)"ordo 16", (IIngredient[][])new IIngredient[][]{{ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)1), OreBracketHandler.getOre((String)"screwThaumium"), ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)2)}, {null, ItemBracketHandler.getItem((String)"Forestry:oakStick", (int)0), OreBracketHandler.getOre((String)"screwThaumium")}, {ItemBracketHandler.getItem((String)"Forestry:oakStick", (int)0), null, ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)3)}});
        Research.setAspects((String)"INTERFACE", (String)"ordo 12, perditio 9, potentia 6, aqua 3");
        Research.setComplexity((String)"INTERFACE", (int)3);
        Arcane.addShaped((String)"DISLOCATOR", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:dislocator", (int)0), (String)"ordo 48, perditio 48, terra 24", (IIngredient[][])new IIngredient[][]{{OreBracketHandler.getOre((String)"screwThaumium"), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)10), OreBracketHandler.getOre((String)"plateEnderPearl")}, {OreBracketHandler.getOre((String)"circuitBasic"), ItemBracketHandler.getItem((String)"ThaumicTinkerer:interface", (int)0), OreBracketHandler.getOre((String)"circuitBasic")}, {OreBracketHandler.getOre((String)"plateEnderPearl"), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)10), OreBracketHandler.getOre((String)"screwThaumium")}});
        Research.setAspects((String)"DISLOCATOR", (String)"cognitio 15, ordo 12, perditio 9, potentia 6, aqua 3");
        Research.setComplexity((String)"DISLOCATOR", (int)4);
        Crucible.addRecipe((String)"GASEOUS_LIGHT", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:gaseousLightItem", (int)0), (IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:ItemEssence", (int)0), (String)"lux 16, aer 12, motus 10");
        Research.setAspects((String)"GASEOUS_LIGHT", (String)"lux 9, aer 6, motus 3, praecantatio 3");
        Research.setComplexity((String)"GASEOUS_LIGHT", (int)2);
        Research.setConcealed((String)"GASEOUS_SHADOW", (boolean)true);
        Crucible.addRecipe((String)"GASEOUS_SHADOW", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:gaseousShadowItem", (int)0), (IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:ItemEssence", (int)0), (String)"tenebrae 16, aer 12, motus 10");
        Research.setAspects((String)"GASEOUS_SHADOW", (String)"tenebrae 9, aer 6, motus 3, praecantatio 3");
        Research.setComplexity((String)"GASEOUS_SHADOW", (int)2);
        Research.setConcealed((String)"GAS_REMOVER", (boolean)true);
        Arcane.addShaped((String)"GAS_REMOVER", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:gasRemover", (int)0), (String)"ordo 16, aer 12, perditio 8", (IIngredient[][])new IIngredient[][]{{OreBracketHandler.getOre((String)"gemQuartz"), OreBracketHandler.getOre((String)"screwThaumium"), OreBracketHandler.getOre((String)"gemQuartz")}, {ItemBracketHandler.getItem((String)"ThaumicTinkerer:gaseousLightItem", (int)0), ItemBracketHandler.getItem((String)"ThaumicTinkerer:interface", (int)0), ItemBracketHandler.getItem((String)"ThaumicTinkerer:gaseousShadowItem", (int)0)}, {ItemBracketHandler.getItem((String)"ThaumicTinkerer:darkQuartzItem", (int)0), OreBracketHandler.getOre((String)"screwThaumium"), ItemBracketHandler.getItem((String)"ThaumicTinkerer:darkQuartzItem", (int)0)}});
        Research.setAspects((String)"GASEOUS_SHADOW", (String)"ignis 12, tenebrae 12, aer 9, motus 6, praecantatio 3");
        Research.setComplexity((String)"GASEOUS_SHADOW", (int)3);
        Research.addPrereq((String)"BRIGHT_NITOR", (String)"INFUSION", (boolean)false);
        Crucible.addRecipe((String)"BRIGHT_NITOR", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:brightNitor", (int)0), (IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)1), (String)"ignis 16, aer 16, potentia 32, lux 32");
        Research.setAspects((String)"BRIGHT_NITOR", (String)"ignis 15, lux 12, aer 9, potentia 6, praecantatio 3");
        Research.setComplexity((String)"BRIGHT_NITOR", (int)3);
        Research.orphanResearch((String)"FIRE_IGNIS");
        Research.removeResearch((String)"FIRE_IGNIS");
        Research.addResearch((String)"FIREIGNIS", (String)"TT_CATEGORY", (String)"ignis 15, lux 12, aer 9, praecantatio 3", (int)4, (int)-4, (int)3, (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:fireFire", (int)0));
        Research.addPrereq((String)"FIREIGNIS", (String)"INFUSION", (boolean)false);
        Research.addPrereq((String)"FIREIGNIS", (String)"BRIGHT_NITOR", (boolean)false);
        Research.addPrereq((String)"FIREIGNIS", (String)"ELDRITCHMINOR", (boolean)false);
        Research.setConcealed((String)"FIREIGNIS", (boolean)true);
        MineTweakerAPI.game.setLocalization("tc.research_name.FIREIGNIS", "Elemental Fire: Ignis");
        MineTweakerAPI.game.setLocalization("tc.research_text.FIREIGNIS", "[TT] Fire infused with.....more fire!");
        Research.addPage((String)"FIREIGNIS", (String)"ttresearch.page.FIRE_IGNIS.0");
        IItemStack iItemStack = ItemBracketHandler.getItem((String)"Thaumcraft:ItemEssence", (int)1);
        HashMap<String, IData> hashMap = new HashMap<String, IData>();
        IData[] arriData = new IData[1];
        HashMap<String, IData> hashMap2 = new HashMap<String, IData>();
        hashMap2.put("amount", ExpandInt.toData((int)8));
        hashMap2.put("key", ExpandString.asData((String)"ignis"));
        arriData[0] = ExpandAnyDict.asData(hashMap2);
        hashMap.put("Aspects", ExpandAnyArray.asData((IData[])arriData));
        Infusion.addRecipe((String)"FIREIGNIS", (IItemStack)iItemStack.withTag(ExpandAnyDict.asData(hashMap)), (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"minecraft:glowstone_dust", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)1), ItemBracketHandler.getItem((String)"minecraft:redstone", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)1)}, (String)"ignis 10, lux 10, aer 10, praecantatio 10", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:fireFire", (int)0), (int)16);
        Research.addInfusionPage((String)"FIREIGNIS", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:fireFire", (int)0));
        Warp.addToResearch((String)"FIREIGNIS", (int)10);
        Research.orphanResearch((String)"FIRE_AQUA");
        Research.removeResearch((String)"FIRE_AQUA");
        Research.addResearch((String)"FIREAQUA", (String)"TT_CATEGORY", (String)"aqua 15, lux 12, aer 9, praecantatio 3", (int)2, (int)-2, (int)3, (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:fireWater", (int)0));
        Research.addPrereq((String)"FIREAQUA", (String)"INFUSION", (boolean)false);
        Research.addPrereq((String)"FIREAQUA", (String)"BRIGHT_NITOR", (boolean)false);
        Research.addPrereq((String)"FIREAQUA", (String)"ELDRITCHMINOR", (boolean)false);
        Research.setConcealed((String)"FIREAQUA", (boolean)true);
        MineTweakerAPI.game.setLocalization("tc.research_name.FIREAQUA", "Elemental Fire: Aqua");
        MineTweakerAPI.game.setLocalization("tc.research_text.FIREAQUA", "[TT] Water plus Fire. This should end well.");
        Research.addPage((String)"FIREAQUA", (String)"ttresearch.page.FIRE_AQUA.0");
        IItemStack iItemStack2 = ItemBracketHandler.getItem((String)"Thaumcraft:ItemEssence", (int)1);
        HashMap<String, IData> hashMap3 = new HashMap<String, IData>();
        IData[] arriData2 = new IData[1];
        HashMap<String, IData> hashMap4 = new HashMap<String, IData>();
        hashMap4.put("amount", ExpandInt.toData((int)8));
        hashMap4.put("key", ExpandString.asData((String)"aqua"));
        arriData2[0] = ExpandAnyDict.asData(hashMap4);
        hashMap3.put("Aspects", ExpandAnyArray.asData((IData[])arriData2));
        Infusion.addRecipe((String)"FIREAQUA", (IItemStack)iItemStack2.withTag(ExpandAnyDict.asData(hashMap3)), (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"minecraft:glowstone_dust", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)2), ItemBracketHandler.getItem((String)"minecraft:redstone", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)2)}, (String)"aqua 10, lux 10, aer 10, praecantatio 10", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:fireWater", (int)0), (int)16);
        Research.addInfusionPage((String)"FIREAQUA", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:fireWater", (int)0));
        Warp.addToResearch((String)"FIREAQUA", (int)10);
        Research.orphanResearch((String)"FIRE_TERRA");
        Research.removeResearch((String)"FIRE_TERRA");
        Research.addResearch((String)"FIRETERRA", (String)"TT_CATEGORY", (String)"terra 15, lux 12, aer 9, praecantatio 3", (int)4, (int)-6, (int)3, (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:fireEarth", (int)0));
        Research.addPrereq((String)"FIRETERRA", (String)"INFUSION", (boolean)false);
        Research.addPrereq((String)"FIRETERRA", (String)"BRIGHT_NITOR", (boolean)false);
        Research.addPrereq((String)"FIRETERRA", (String)"ELDRITCHMINOR", (boolean)false);
        Research.setConcealed((String)"FIRETERRA", (boolean)true);
        MineTweakerAPI.game.setLocalization("tc.research_name.FIRETERRA", "Elemental Fire: Terra");
        MineTweakerAPI.game.setLocalization("tc.research_text.FIRETERRA", "[TT] Enough dirt to ... do whatever one does with dirt");
        Research.addPage((String)"FIRETERRA", (String)"ttresearch.page.FIRE_TERRA.0");
        IItemStack iItemStack3 = ItemBracketHandler.getItem((String)"Thaumcraft:ItemEssence", (int)1);
        HashMap<String, IData> hashMap5 = new HashMap<String, IData>();
        IData[] arriData3 = new IData[1];
        HashMap<String, IData> hashMap6 = new HashMap<String, IData>();
        hashMap6.put("amount", ExpandInt.toData((int)8));
        hashMap6.put("key", ExpandString.asData((String)"terra"));
        arriData3[0] = ExpandAnyDict.asData(hashMap6);
        hashMap5.put("Aspects", ExpandAnyArray.asData((IData[])arriData3));
        Infusion.addRecipe((String)"FIRETERRA", (IItemStack)iItemStack3.withTag(ExpandAnyDict.asData(hashMap5)), (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"minecraft:glowstone_dust", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)3), ItemBracketHandler.getItem((String)"minecraft:redstone", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)3)}, (String)"terra 10, lux 10, aer 10, praecantatio 10", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:fireEarth", (int)0), (int)16);
        Research.addInfusionPage((String)"FIRETERRA", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:fireEarth", (int)0));
        Warp.addToResearch((String)"FIRETERRA", (int)10);
        Research.orphanResearch((String)"FIRE_ORDO");
        Research.removeResearch((String)"FIRE_ORDO");
        Research.addResearch((String)"FIREORDO", (String)"TT_CATEGORY", (String)"ordo 15, lux 12, aer 9, praecantatio 3", (int)3, (int)-3, (int)3, (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:fireOrder", (int)0));
        Research.addPrereq((String)"FIREORDO", (String)"INFUSION", (boolean)false);
        Research.addPrereq((String)"FIREORDO", (String)"BRIGHT_NITOR", (boolean)false);
        Research.addPrereq((String)"FIREORDO", (String)"ELDRITCHMINOR", (boolean)false);
        Research.setConcealed((String)"FIREORDO", (boolean)true);
        MineTweakerAPI.game.setLocalization("tc.research_name.FIREORDO", "Elemental Fire: Ordo");
        MineTweakerAPI.game.setLocalization("tc.research_text.FIREORDO", "[TT] More ingots for your ore");
        Research.addPage((String)"FIREORDO", (String)"ttresearch.page.FIRE_ORDO.0");
        IItemStack iItemStack4 = ItemBracketHandler.getItem((String)"Thaumcraft:ItemEssence", (int)1);
        HashMap<String, IData> hashMap7 = new HashMap<String, IData>();
        IData[] arriData4 = new IData[1];
        HashMap<String, IData> hashMap8 = new HashMap<String, IData>();
        hashMap8.put("amount", ExpandInt.toData((int)8));
        hashMap8.put("key", ExpandString.asData((String)"ordo"));
        arriData4[0] = ExpandAnyDict.asData(hashMap8);
        hashMap7.put("Aspects", ExpandAnyArray.asData((IData[])arriData4));
        Infusion.addRecipe((String)"FIREORDO", (IItemStack)iItemStack4.withTag(ExpandAnyDict.asData(hashMap7)), (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"minecraft:glowstone_dust", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)4), ItemBracketHandler.getItem((String)"minecraft:redstone", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)4)}, (String)"ordo 10, lux 10, aer 10, praecantatio 10", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:fireOrder", (int)0), (int)16);
        Research.addInfusionPage((String)"FIREORDO", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:fireOrder", (int)0));
        Warp.addToResearch((String)"FIREORDO", (int)10);
        Research.orphanResearch((String)"FIRE_AER");
        Research.removeResearch((String)"FIRE_AER");
        Research.addResearch((String)"FIREAER", (String)"TT_CATEGORY", (String)"aer 15, lux 12, motus 9, praecantatio 3", (int)3, (int)-7, (int)3, (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:fireAir", (int)0));
        Research.addPrereq((String)"FIREAER", (String)"INFUSION", (boolean)false);
        Research.addPrereq((String)"FIREAER", (String)"BRIGHT_NITOR", (boolean)false);
        Research.addPrereq((String)"FIREAER", (String)"ELDRITCHMINOR", (boolean)false);
        Research.setConcealed((String)"FIREAER", (boolean)true);
        MineTweakerAPI.game.setLocalization("tc.research_name.FIREAER", "Elemental Fire: Aer");
        MineTweakerAPI.game.setLocalization("tc.research_text.FIREAER", "[TT] Suspension of disbelief is a useful skill");
        Research.addPage((String)"FIREAER", (String)"ttresearch.page.FIRE_AER.0");
        IItemStack iItemStack5 = ItemBracketHandler.getItem((String)"Thaumcraft:ItemEssence", (int)1);
        HashMap<String, IData> hashMap9 = new HashMap<String, IData>();
        IData[] arriData5 = new IData[1];
        HashMap<String, IData> hashMap10 = new HashMap<String, IData>();
        hashMap10.put("amount", ExpandInt.toData((int)8));
        hashMap10.put("key", ExpandString.asData((String)"aer"));
        arriData5[0] = ExpandAnyDict.asData(hashMap10);
        hashMap9.put("Aspects", ExpandAnyArray.asData((IData[])arriData5));
        Infusion.addRecipe((String)"FIREAER", (IItemStack)iItemStack5.withTag(ExpandAnyDict.asData(hashMap9)), (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"minecraft:glowstone_dust", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)0), ItemBracketHandler.getItem((String)"minecraft:redstone", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)0)}, (String)"aer 10, lux 10, motus 10, praecantatio 10", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:fireAir", (int)0), (int)16);
        Research.addInfusionPage((String)"FIREAER", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:fireAir", (int)0));
        Warp.addToResearch((String)"FIREAER", (int)10);
        Research.orphanResearch((String)"FIRE_PERDITIO");
        Research.removeResearch((String)"FIRE_PERDITIO");
        Research.addResearch((String)"FIREPERDITIO", (String)"TT_CATEGORY", (String)"perditio 15, lux 12, aer 9, praecantatio 3", (int)2, (int)-8, (int)3, (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:fireChaos", (int)0));
        Research.addPrereq((String)"FIREPERDITIO", (String)"INFUSION", (boolean)false);
        Research.addPrereq((String)"FIREPERDITIO", (String)"BRIGHT_NITOR", (boolean)false);
        Research.addPrereq((String)"FIREPERDITIO", (String)"ELDRITCHMINOR", (boolean)false);
        Research.setConcealed((String)"FIREPERDITIO", (boolean)true);
        MineTweakerAPI.game.setLocalization("tc.research_name.FIREPERDITIO", "Elemental Fire: Perditio");
        MineTweakerAPI.game.setLocalization("tc.research_text.FIREPERDITIO", "[TT] Cleanup time");
        Research.addPage((String)"FIREPERDITIO", (String)"ttresearch.page.FIRE_PERDITIO.0");
        IItemStack iItemStack6 = ItemBracketHandler.getItem((String)"Thaumcraft:ItemEssence", (int)1);
        HashMap<String, IData> hashMap11 = new HashMap<String, IData>();
        IData[] arriData6 = new IData[1];
        HashMap<String, IData> hashMap12 = new HashMap<String, IData>();
        hashMap12.put("amount", ExpandInt.toData((int)8));
        hashMap12.put("key", ExpandString.asData((String)"perditio"));
        arriData6[0] = ExpandAnyDict.asData(hashMap12);
        hashMap11.put("Aspects", ExpandAnyArray.asData((IData[])arriData6));
        Infusion.addRecipe((String)"FIREPERDITIO", (IItemStack)iItemStack6.withTag(ExpandAnyDict.asData(hashMap11)), (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"minecraft:glowstone_dust", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)5), ItemBracketHandler.getItem((String)"minecraft:redstone", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)5)}, (String)"perditio 10, lux 10, aer 10, praecantatio 10", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:fireChaos", (int)0), (int)16);
        Research.addInfusionPage((String)"FIREPERDITIO", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:fireChaos", (int)0));
        Warp.addToResearch((String)"FIREPERDITIO", (int)10);
        Research.orphanResearch((String)"INFUSED_POTIONS");
        Research.removeResearch((String)"INFUSED_POTIONS");
        IItemStack iItemStack7 = ItemBracketHandler.getItem((String)"ThaumicTinkerer:infusedSeeds", (int)0);
        HashMap<String, IData> hashMap13 = new HashMap<String, IData>();
        HashMap<String, IData> hashMap14 = new HashMap<String, IData>();
        IData[] arriData7 = new IData[1];
        HashMap<String, IData> hashMap15 = new HashMap<String, IData>();
        hashMap15.put("amount", ExpandInt.toData((int)1));
        hashMap15.put("key", ExpandString.asData((String)"ignis"));
        arriData7[0] = ExpandAnyDict.asData(hashMap15);
        hashMap14.put("Aspects", ExpandAnyArray.asData((IData[])arriData7));
        hashMap13.put("mainAspect", ExpandAnyDict.asData(hashMap14));
        HashMap<String, IData> hashMap16 = new HashMap<String, IData>();
        hashMap16.put("Aspects", ExpandAnyArray.asData((IData[])new IData[0]));
        hashMap13.put("aspectTendencies", ExpandAnyDict.asData(hashMap16));
        Research.addResearch((String)"INFUSEDSEED", (String)"TT_CATEGORY", (String)"perditio 15, lux 12, aer 9, praecantatio 3", (int)7, (int)-5, (int)3, (IItemStack)iItemStack7.withTag(ExpandAnyDict.asData(hashMap13)));
        Research.addPrereq((String)"INFUSEDSEED", (String)"INFUSION", (boolean)false);
        Research.addPrereq((String)"INFUSEDSEED", (String)"FIREIGNIS", (boolean)false);
        Research.addPrereq((String)"INFUSEDSEED", (String)"FIREAQUA", (boolean)false);
        Research.addPrereq((String)"INFUSEDSEED", (String)"FIRETERRA", (boolean)false);
        Research.addPrereq((String)"INFUSEDSEED", (String)"FIREAER", (boolean)false);
        Research.addPrereq((String)"INFUSEDSEED", (String)"FIREORDO", (boolean)false);
        Research.addPrereq((String)"INFUSEDSEED", (String)"FIREPERDITIO", (boolean)false);
        Research.setConcealed((String)"INFUSEDSEED", (boolean)true);
        MineTweakerAPI.game.setLocalization("tc.research_name.INFUSEDSEED", "Infused Crops");
        MineTweakerAPI.game.setLocalization("tc.research_text.INFUSEDSEED", "[TT] Who said bees? No one said bees.");
        Research.addPage((String)"INFUSEDSEED", (String)"ttresearch.page.INFUSED_POTIONS.0");
        Research.addPage((String)"INFUSEDSEED", (String)"ttresearch.page.INFUSED_POTIONS.1");
        Research.addPage((String)"INFUSEDSEED", (String)"ttresearch.page.INFUSED_POTIONS.2");
        Research.addPage((String)"INFUSEDSEED", (String)"ttresearch.page.INFUSED_POTIONS.3");
        IItemStack iItemStack8 = ItemBracketHandler.getItem((String)"minecraft:wheat_seeds", (int)0);
        IItemStack[] arriItemStack = new IItemStack[]{ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)0)};
        IItemStack iItemStack9 = ItemBracketHandler.getItem((String)"ThaumicTinkerer:infusedSeeds", (int)0);
        HashMap<String, IData> hashMap17 = new HashMap<String, IData>();
        HashMap<String, IData> hashMap18 = new HashMap<String, IData>();
        IData[] arriData8 = new IData[1];
        HashMap<String, IData> hashMap19 = new HashMap<String, IData>();
        hashMap19.put("amount", ExpandInt.toData((int)1));
        hashMap19.put("key", ExpandString.asData((String)"aer"));
        arriData8[0] = ExpandAnyDict.asData(hashMap19);
        hashMap18.put("Aspects", ExpandAnyArray.asData((IData[])arriData8));
        hashMap17.put("mainAspect", ExpandAnyDict.asData(hashMap18));
        HashMap<String, IData> hashMap20 = new HashMap<String, IData>();
        hashMap20.put("Aspects", ExpandAnyArray.asData((IData[])new IData[0]));
        hashMap17.put("aspectTendencies", ExpandAnyDict.asData(hashMap20));
        Infusion.addRecipe((String)"INFUSEDSEED", (IItemStack)iItemStack8, (IItemStack[])arriItemStack, (String)"messis 32, meto 32, aer 16", (IItemStack)iItemStack9.withTag(ExpandAnyDict.asData(hashMap17)), (int)4);
        IItemStack iItemStack10 = ItemBracketHandler.getItem((String)"ThaumicTinkerer:infusedSeeds", (int)0);
        HashMap<String, IData> hashMap21 = new HashMap<String, IData>();
        HashMap<String, IData> hashMap22 = new HashMap<String, IData>();
        IData[] arriData9 = new IData[1];
        HashMap<String, IData> hashMap23 = new HashMap<String, IData>();
        hashMap23.put("amount", ExpandInt.toData((int)1));
        hashMap23.put("key", ExpandString.asData((String)"aer"));
        arriData9[0] = ExpandAnyDict.asData(hashMap23);
        hashMap22.put("Aspects", ExpandAnyArray.asData((IData[])arriData9));
        hashMap21.put("mainAspect", ExpandAnyDict.asData(hashMap22));
        HashMap<String, IData> hashMap24 = new HashMap<String, IData>();
        hashMap24.put("Aspects", ExpandAnyArray.asData((IData[])new IData[0]));
        hashMap21.put("aspectTendencies", ExpandAnyDict.asData(hashMap24));
        Research.addInfusionPage((String)"INFUSEDSEED", (IItemStack)iItemStack10.withTag(ExpandAnyDict.asData(hashMap21)));
        IItemStack iItemStack11 = ItemBracketHandler.getItem((String)"minecraft:wheat_seeds", (int)0);
        IItemStack[] arriItemStack2 = new IItemStack[]{ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)1), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)1), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)1), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)1)};
        IItemStack iItemStack12 = ItemBracketHandler.getItem((String)"ThaumicTinkerer:infusedSeeds", (int)0);
        HashMap<String, IData> hashMap25 = new HashMap<String, IData>();
        HashMap<String, IData> hashMap26 = new HashMap<String, IData>();
        IData[] arriData10 = new IData[1];
        HashMap<String, IData> hashMap27 = new HashMap<String, IData>();
        hashMap27.put("amount", ExpandInt.toData((int)1));
        hashMap27.put("key", ExpandString.asData((String)"ignis"));
        arriData10[0] = ExpandAnyDict.asData(hashMap27);
        hashMap26.put("Aspects", ExpandAnyArray.asData((IData[])arriData10));
        hashMap25.put("mainAspect", ExpandAnyDict.asData(hashMap26));
        HashMap<String, IData> hashMap28 = new HashMap<String, IData>();
        hashMap28.put("Aspects", ExpandAnyArray.asData((IData[])new IData[0]));
        hashMap25.put("aspectTendencies", ExpandAnyDict.asData(hashMap28));
        Infusion.addRecipe((String)"INFUSEDSEED", (IItemStack)iItemStack11, (IItemStack[])arriItemStack2, (String)"messis 32, meto 32, ignis 16", (IItemStack)iItemStack12.withTag(ExpandAnyDict.asData(hashMap25)), (int)4);
        IItemStack iItemStack13 = ItemBracketHandler.getItem((String)"minecraft:wheat_seeds", (int)0);
        IItemStack[] arriItemStack3 = new IItemStack[]{ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)2), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)2), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)2), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)2)};
        IItemStack iItemStack14 = ItemBracketHandler.getItem((String)"ThaumicTinkerer:infusedSeeds", (int)0);
        HashMap<String, IData> hashMap29 = new HashMap<String, IData>();
        HashMap<String, IData> hashMap30 = new HashMap<String, IData>();
        IData[] arriData11 = new IData[1];
        HashMap<String, IData> hashMap31 = new HashMap<String, IData>();
        hashMap31.put("amount", ExpandInt.toData((int)1));
        hashMap31.put("key", ExpandString.asData((String)"aqua"));
        arriData11[0] = ExpandAnyDict.asData(hashMap31);
        hashMap30.put("Aspects", ExpandAnyArray.asData((IData[])arriData11));
        hashMap29.put("mainAspect", ExpandAnyDict.asData(hashMap30));
        HashMap<String, IData> hashMap32 = new HashMap<String, IData>();
        hashMap32.put("Aspects", ExpandAnyArray.asData((IData[])new IData[0]));
        hashMap29.put("aspectTendencies", ExpandAnyDict.asData(hashMap32));
        Infusion.addRecipe((String)"INFUSEDSEED", (IItemStack)iItemStack13, (IItemStack[])arriItemStack3, (String)"messis 32, meto 32, aqua 16", (IItemStack)iItemStack14.withTag(ExpandAnyDict.asData(hashMap29)), (int)4);
        IItemStack iItemStack15 = ItemBracketHandler.getItem((String)"minecraft:wheat_seeds", (int)0);
        IItemStack[] arriItemStack4 = new IItemStack[]{ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)3), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)3), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)3), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)3)};
        IItemStack iItemStack16 = ItemBracketHandler.getItem((String)"ThaumicTinkerer:infusedSeeds", (int)0);
        HashMap<String, IData> hashMap33 = new HashMap<String, IData>();
        HashMap<String, IData> hashMap34 = new HashMap<String, IData>();
        IData[] arriData12 = new IData[1];
        HashMap<String, IData> hashMap35 = new HashMap<String, IData>();
        hashMap35.put("amount", ExpandInt.toData((int)1));
        hashMap35.put("key", ExpandString.asData((String)"terra"));
        arriData12[0] = ExpandAnyDict.asData(hashMap35);
        hashMap34.put("Aspects", ExpandAnyArray.asData((IData[])arriData12));
        hashMap33.put("mainAspect", ExpandAnyDict.asData(hashMap34));
        HashMap<String, IData> hashMap36 = new HashMap<String, IData>();
        hashMap36.put("Aspects", ExpandAnyArray.asData((IData[])new IData[0]));
        hashMap33.put("aspectTendencies", ExpandAnyDict.asData(hashMap36));
        Infusion.addRecipe((String)"INFUSEDSEED", (IItemStack)iItemStack15, (IItemStack[])arriItemStack4, (String)"messis 32, meto 32, terra 16", (IItemStack)iItemStack16.withTag(ExpandAnyDict.asData(hashMap33)), (int)4);
        IItemStack iItemStack17 = ItemBracketHandler.getItem((String)"minecraft:wheat_seeds", (int)0);
        IItemStack[] arriItemStack5 = new IItemStack[]{ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)4), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)4), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)4), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)4)};
        IItemStack iItemStack18 = ItemBracketHandler.getItem((String)"ThaumicTinkerer:infusedSeeds", (int)0);
        HashMap<String, IData> hashMap37 = new HashMap<String, IData>();
        HashMap<String, IData> hashMap38 = new HashMap<String, IData>();
        IData[] arriData13 = new IData[1];
        HashMap<String, IData> hashMap39 = new HashMap<String, IData>();
        hashMap39.put("amount", ExpandInt.toData((int)1));
        hashMap39.put("key", ExpandString.asData((String)"ordo"));
        arriData13[0] = ExpandAnyDict.asData(hashMap39);
        hashMap38.put("Aspects", ExpandAnyArray.asData((IData[])arriData13));
        hashMap37.put("mainAspect", ExpandAnyDict.asData(hashMap38));
        HashMap<String, IData> hashMap40 = new HashMap<String, IData>();
        hashMap40.put("Aspects", ExpandAnyArray.asData((IData[])new IData[0]));
        hashMap37.put("aspectTendencies", ExpandAnyDict.asData(hashMap40));
        Infusion.addRecipe((String)"INFUSEDSEED", (IItemStack)iItemStack17, (IItemStack[])arriItemStack5, (String)"messis 32, meto 32, ordo 16", (IItemStack)iItemStack18.withTag(ExpandAnyDict.asData(hashMap37)), (int)4);
        IItemStack iItemStack19 = ItemBracketHandler.getItem((String)"minecraft:wheat_seeds", (int)0);
        IItemStack[] arriItemStack6 = new IItemStack[]{ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)5), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)5), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)5), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)5)};
        IItemStack iItemStack20 = ItemBracketHandler.getItem((String)"ThaumicTinkerer:infusedSeeds", (int)0);
        HashMap<String, IData> hashMap41 = new HashMap<String, IData>();
        HashMap<String, IData> hashMap42 = new HashMap<String, IData>();
        IData[] arriData14 = new IData[1];
        HashMap<String, IData> hashMap43 = new HashMap<String, IData>();
        hashMap43.put("amount", ExpandInt.toData((int)1));
        hashMap43.put("key", ExpandString.asData((String)"perditio"));
        arriData14[0] = ExpandAnyDict.asData(hashMap43);
        hashMap42.put("Aspects", ExpandAnyArray.asData((IData[])arriData14));
        hashMap41.put("mainAspect", ExpandAnyDict.asData(hashMap42));
        HashMap<String, IData> hashMap44 = new HashMap<String, IData>();
        hashMap44.put("Aspects", ExpandAnyArray.asData((IData[])new IData[0]));
        hashMap41.put("aspectTendencies", ExpandAnyDict.asData(hashMap44));
        Infusion.addRecipe((String)"INFUSEDSEED", (IItemStack)iItemStack19, (IItemStack[])arriItemStack6, (String)"messis 32, meto 32, perditio 16", (IItemStack)iItemStack20.withTag(ExpandAnyDict.asData(hashMap41)), (int)4);
        Research.addPage((String)"INFUSEDSEED", (String)"tt.research.page.INFUSEDSEED.3");
        MineTweakerAPI.game.setLocalization("tt.research.page.INFUSEDSEED.3", "The other recipes are not shown but you can infuse Seeds with all the other Primal Aspect Crystals.<BR>Seeds infuse Ignis with Ignis Cluster and 16 ignis Aspect instead of Air, Seeds infuse Aqua with Aqua Crystals and 16 aqua Aspect instead of Air...");
        Warp.addToResearch((String)"INFUSEDSEED", (int)2);
        Research.addResearch((String)"INFUSEDPOTIONS", (String)"TT_CATEGORY", (String)"auram 15, ignis 12, aer 9, aqua 9, terra 9", (int)9, (int)-5, (int)3, (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:infusedPotion", (int)1));
        Research.addPrereq((String)"INFUSEDPOTIONS", (String)"INFUSION", (boolean)false);
        Research.addPrereq((String)"INFUSEDPOTIONS", (String)"INFUSEDSEED", (boolean)false);
        Research.setConcealed((String)"INFUSEDPOTIONS", (boolean)true);
        MineTweakerAPI.game.setLocalization("tc.research_name.INFUSEDPOTIONS", "Infused Potions");
        MineTweakerAPI.game.setLocalization("tc.research_text.INFUSEDPOTIONS", "[TT] Growing your Potions.");
        Research.addPage((String)"INFUSEDPOTIONS", (String)"ttresearch.page.INFUSED_POTIONS.4");
        Research.addPage((String)"INFUSEDPOTIONS", (String)"ttresearch.page.INFUSED_POTIONS.5");
        Crucible.addRecipe((String)"INFUSEDPOTIONS", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:infusedPotion", (int)0), (IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:infusedGrain", (int)0), (String)"auram 16, aer 16, praecantatio 8");
        Research.addCruciblePage((String)"INFUSEDPOTIONS", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:infusedPotion", (int)0));
        Crucible.addRecipe((String)"INFUSEDPOTIONS", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:infusedPotion", (int)1), (IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:infusedGrain", (int)1), (String)"auram 16, ignis 16, praecantatio 8");
        Research.addCruciblePage((String)"INFUSEDPOTIONS", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:infusedPotion", (int)1));
        Crucible.addRecipe((String)"INFUSEDPOTIONS", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:infusedPotion", (int)2), (IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:infusedGrain", (int)2), (String)"auram 16, terra 16, praecantatio 8");
        Research.addCruciblePage((String)"INFUSEDPOTIONS", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:infusedPotion", (int)2));
        Crucible.addRecipe((String)"INFUSEDPOTIONS", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:infusedPotion", (int)3), (IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:infusedGrain", (int)3), (String)"auram 16, aqua 16, praecantatio 8");
        Research.addCruciblePage((String)"INFUSEDPOTIONS", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:infusedPotion", (int)3));
        Warp.addToResearch((String)"INFUSEDPOTIONS", (int)2);
        Research.addPrereq((String)"FUNNEL", (String)"INFUSION", (boolean)false);
        Arcane.addShaped((String)"FUNNEL", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:funnel", (int)0), (String)"ordo 8, perditio 8, aqua 8", (IIngredient[][])new IIngredient[][]{{OreBracketHandler.getOre((String)"screwThaumium"), OreBracketHandler.getOre((String)"craftingToolScrewdriver"), OreBracketHandler.getOre((String)"screwThaumium")}, {OreBracketHandler.getOre((String)"plateThaumium"), OreBracketHandler.getOre((String)"pipeMediumStainlessSteel"), OreBracketHandler.getOre((String)"plateThaumium")}});
        Research.setAspects((String)"FUNNEL", (String)"iter 15, instrumentum 12, aqua 9, metallum 6, praecantatio 3");
        Research.setComplexity((String)"FUNNEL", (int)3);
        Research.addPrereq((String)"REPAIRER", (String)"INFUSION", (boolean)false);
        Infusion.addRecipe((String)"REPAIRER", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:blockCosmeticSolid", (int)4), (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)17330), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)17032), ItemBracketHandler.getItem((String)"dreamcraft:item.ReinforcedGlassPlate", (int)0), ItemBracketHandler.getItem((String)"harvestcraft:hardenedleatherItem", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)7), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)17500), ItemBracketHandler.getItem((String)"dreamcraft:item.ReinforcedGlassPlate", (int)0), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)17086)}, (String)"fabrico 32, instrumentum 32, ordo 16, praecantatio 16, potentia 8", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:repairer", (int)0), (int)8);
        Research.setAspects((String)"REPAIRER", (String)"instrumentum 15, fabrico 12, ordo 9, potentia 6, praecantatio 3");
        Research.setComplexity((String)"REPAIRER", (int)4);
        Arcane.addShaped((String)"MAGNETS", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:magnet", (int)0), (String)"aer 30, terra 25, ordo 20, perditio 15", (IIngredient[][])new IIngredient[][]{{OreBracketHandler.getOre((String)"screwThaumium"), OreBracketHandler.getOre((String)"plateSteelMagnetic"), OreBracketHandler.getOre((String)"screwThaumium")}, {ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)3), OreBracketHandler.getOre((String)"plateThaumium"), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)0)}, {ItemBracketHandler.getItem((String)"Thaumcraft:blockMagicalLog", (int)0), ItemBracketHandler.getItem((String)"ThaumicTinkerer:focusTelekinesis", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:blockMagicalLog", (int)0)}});
        Research.setAspects((String)"MAGNETS", (String)"bestia 15, machina 15, motus 12, sensus 9, ordo 6, spiritus 3");
        Research.setComplexity((String)"MAGNETS", (int)4);
        Warp.addToResearch((String)"MAGNETS", (int)2);
        Arcane.addShaped((String)"MAGNETS", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:magnet", (int)1), (String)"aer 25, terra 30, ordo 15, perditio 20", (IIngredient[][])new IIngredient[][]{{OreBracketHandler.getOre((String)"screwThaumium"), OreBracketHandler.getOre((String)"plateThaumium"), OreBracketHandler.getOre((String)"screwThaumium")}, {ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)3), OreBracketHandler.getOre((String)"plateSteelMagnetic"), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)0)}, {ItemBracketHandler.getItem((String)"Thaumcraft:blockMagicalLog", (int)1), ItemBracketHandler.getItem((String)"ThaumicTinkerer:focusTelekinesis", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:blockMagicalLog", (int)1)}});
        Crucible.addRecipe((String)"MAGNETS", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:soulMould", (int)0), (IIngredient)ItemBracketHandler.getItem((String)"minecraft:ender_eye", (int)0), (String)"bestia 8, cognitio 8, sensus 8, spiritus 8");
        Research.setConcealed((String)"ANIMATION_TABLET", (boolean)true);
        Arcane.addShaped((String)"ANIMATION_TABLET", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:animationTablet", (int)0), (String)"aer 35, ignis 30, ordo 20", (IIngredient[][])new IIngredient[][]{{OreBracketHandler.getOre((String)"plateRoseGold"), OreBracketHandler.getOre((String)"plateThaumium"), OreBracketHandler.getOre((String)"plateRoseGold")}, {OreBracketHandler.getOre((String)"plateElectrum"), OreBracketHandler.getOre((String)"plateThaumium"), OreBracketHandler.getOre((String)"plateElectrum")}, {OreBracketHandler.getOre((String)"screwThaumium"), ItemBracketHandler.getItem((String)"Thaumcraft:ItemGolemCore", (int)100), OreBracketHandler.getOre((String)"screwThaumium")}});
        Research.setAspects((String)"ANIMATION_TABLET", (String)"machina 15, metallum 15, motus 12, potentia 9, ordo 6, exanimis 3");
        Research.setComplexity((String)"ANIMATION_TABLET", (int)4);
        Warp.addToResearch((String)"ANIMATION_TABLET", (int)3);
        Research.setConcealed((String)"LEVITATOR_LOCOMOTIVE", (boolean)true);
        Infusion.addRecipe((String)"LEVITATOR_LOCOMOTIVE", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:blockLifter", (int)0), (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)17804), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)27032), ItemBracketHandler.getItem((String)"EMT:EMTItems", (int)7), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)27032), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)17804), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)27032), ItemBracketHandler.getItem((String)"EMT:EMTItems", (int)7), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)27032)}, (String)"motus 30, ordo 20, praecantatio 15, aer 25, potentia 10", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:LevitationalLocomotive", (int)0), (int)4);
        Research.setAspects((String)"LEVITATOR_LOCOMOTIVE", (String)"motus 15, ordo 15, machina 12, aer 9, potentia 6, praecantatio 3");
        Research.setComplexity((String)"LEVITATOR_LOCOMOTIVE", (int)3);
        Arcane.addShaped((String)"LEVITATOR_LOCOMOTIVE", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:LevitationalLocomotiveRelay", (int)0), (String)"aer 30, terra 20, ordo 10", (IIngredient[][])new IIngredient[][]{{OreBracketHandler.getOre((String)"paneGlassColorless"), OreBracketHandler.getOre((String)"lensInfusedWater"), OreBracketHandler.getOre((String)"paneGlassColorless")}, {OreBracketHandler.getOre((String)"lensInfusedWater"), ItemBracketHandler.getItem((String)"Thaumcraft:blockMagicalLog", (int)0), OreBracketHandler.getOre((String)"lensInfusedWater")}, {OreBracketHandler.getOre((String)"paneGlassColorless"), OreBracketHandler.getOre((String)"lensInfusedWater"), OreBracketHandler.getOre((String)"paneGlassColorless")}});
        Research.addPrereq((String)"CLEANSING_TALISMAN", (String)"DARKQUARTZ", (boolean)false);
        Research.addPrereq((String)"CLEANSING_TALISMAN", (String)"INFUSION", (boolean)false);
        Research.addPrereq((String)"CLEANSING_TALISMAN", (String)"RUNICARMOR", (boolean)false);
        Research.setConcealed((String)"INFUSEDPOTIONS", (boolean)true);
        Infusion.addRecipe((String)"CLEANSING_TALISMAN", (IItemStack)ItemBracketHandler.getItem((String)"minecraft:ender_eye", (int)0), (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"ThaumicTinkerer:darkQuartzItem", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)1), ItemBracketHandler.getItem((String)"ThaumicTinkerer:darkQuartzItem", (int)0), ItemBracketHandler.getItem((String)"minecraft:ghast_tear", (int)0), ItemBracketHandler.getItem((String)"ThaumicTinkerer:darkQuartzItem", (int)0), ItemBracketHandler.getItem((String)"minecraft:ghast_tear", (int)0), ItemBracketHandler.getItem((String)"ThaumicTinkerer:darkQuartzItem", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)1)}, (String)"humanus 32, instrumentum 24, sano 16, victus 16", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:cleansingTalisman", (int)0), (int)4);
        Research.setAspects((String)"CLEANSING_TALISMAN", (String)"sano 15, ordo 12, mortuus 9, victus 6, praecantatio 3");
        Research.setComplexity((String)"CLEANSING_TALISMAN", (int)3);
        Research.setConcealed((String)"INFUSEDPOTIONS", (boolean)true);
        Arcane.addShaped((String)"PLATFORM", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:platform", (int)0).amount(2), (String)"aer 10, perditio 10", (IIngredient[][])new IIngredient[][]{{OreBracketHandler.getOre((String)"screwThaumium"), OreBracketHandler.getOre((String)"craftingToolScrewdriver"), OreBracketHandler.getOre((String)"screwThaumium")}, {ItemBracketHandler.getItem((String)"Thaumcraft:blockWoodenDevice", (int)6), ItemBracketHandler.getItem((String)"Thaumcraft:blockWoodenDevice", (int)7), ItemBracketHandler.getItem((String)"Thaumcraft:blockWoodenDevice", (int)6)}});
        Research.setAspects((String)"PLATFORM", (String)"sensus 12, arbor 9, motus 6, iter 3, praecantatio 3");
        Research.setComplexity((String)"PLATFORM", (int)3);
        Research.setConcealed((String)"BLOOD_SWORD", (boolean)true);
        Infusion.addRecipe((String)"BLOOD_SWORD", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemSwordThaumium", (int)0), (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.02", (int)29500), ItemBracketHandler.getItem((String)"minecraft:ghast_tear", (int)0), ItemBracketHandler.getItem((String)"minecraft:rotten_flesh", (int)0), ItemBracketHandler.getItem((String)"minecraft:porkchop", (int)0), ItemBracketHandler.getItem((String)"minecraft:fish", (int)0), ItemBracketHandler.getItem((String)"minecraft:nether_wart", (int)0), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.02", (int)29500), ItemBracketHandler.getItem((String)"minecraft:bone", (int)0), ItemBracketHandler.getItem((String)"minecraft:beef", (int)0), ItemBracketHandler.getItem((String)"minecraft:blaze_powder", (int)0), ItemBracketHandler.getItem((String)"minecraft:spider_eye", (int)0), ItemBracketHandler.getItem((String)"minecraft:chicken", (int)0)}, (String)"fames 32, humanus 8, spiritus 16, tenebrae 24, telum 16", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:bloodSword", (int)0), (int)8);
        Research.setAspects((String)"BLOOD_SWORD", (String)"fames 15, telum 12, corpus 9, spiritus 6, tenebrae 3");
        Research.setComplexity((String)"BLOOD_SWORD", (int)4);
        Warp.addToResearch((String)"BLOOD_SWORD", (int)3);
        Research.setConcealed((String)"SUMMON", (boolean)true);
        Arcane.addShaped((String)"SUMMON", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:spawner", (int)0), (String)"ordo 75, perditio 75, terra 50", (IIngredient[][])new IIngredient[][]{{OreBracketHandler.getOre((String)"gemFlawlessRuby"), ItemBracketHandler.getItem((String)"Thaumcraft:blockMetalDevice", (int)5), OreBracketHandler.getOre((String)"gemFlawlessRuby")}, {ItemBracketHandler.getItem((String)"Thaumcraft:blockCosmeticSolid", (int)0), OreBracketHandler.getOre((String)"plateDenseObsidian"), ItemBracketHandler.getItem((String)"Thaumcraft:blockCosmeticSolid", (int)0)}, {OreBracketHandler.getOre((String)"screwThaumium"), OreBracketHandler.getOre((String)"craftingToolScrewdriver"), OreBracketHandler.getOre((String)"screwThaumium")}});
        Research.setAspects((String)"SUMMON", (String)"telum 15, bestia 12, praecantatio 9, spiritus 6, terra 3");
        Research.setComplexity((String)"SUMMON", (int)4);
        Warp.addToResearch((String)"SUMMON", (int)5);
        Arcane.addShaped((String)"FOCUS_SMELT", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:focusSmelt", (int)0), (String)"ignis 16, perditio 12, ordo 12, aer 8", (IIngredient[][])new IIngredient[][]{{ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)14), ItemBracketHandler.getItem((String)"Thaumcraft:FocusExcavation", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)14)}, {ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)1), ItemBracketHandler.getItem((String)"minecraft:furnace", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)1)}, {ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)14), ItemBracketHandler.getItem((String)"Thaumcraft:FocusFire", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)14)}});
        Research.setAspects((String)"FOCUS_SMELT", (String)"ignis 15, potentia 12, praecantatio 9, aer 6, terra 3");
        Research.setComplexity((String)"FOCUS_SMELT", (int)3);
        Research.addPrereq((String)"FOCUS_FLIGHT", (String)"FOCUSFIRE", (boolean)false);
        Infusion.addRecipe((String)"FOCUS_FLIGHT", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemSwordElemental", (int)0), (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.02", (int)21330), ItemBracketHandler.getItem((String)"EMT:EMTItems", (int)7), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)2532), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.02", (int)21330), ItemBracketHandler.getItem((String)"EMT:EMTItems", (int)7), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)2532)}, (String)"aer 32, iter 24, motus 32, volatus 24, aer 16", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:focusFlight", (int)0), (int)6);
        Research.setAspects((String)"FOCUS_FLIGHT", (String)"motus 15, aer 12, praecantatio 9, volatus 6, iter 3");
        Research.setComplexity((String)"FOCUS_FLIGHT", (int)4);
        Research.addPrereq((String)"FOCUS_DEFLECT", (String)"FOCUS_FLIGHT", (boolean)false);
        Infusion.addRecipe((String)"FOCUS_DEFLECT", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:focusFlight", (int)0), (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)10), ItemBracketHandler.getItem((String)"Thaumcraft:blockCosmeticSolid", (int)3), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)4), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)10), ItemBracketHandler.getItem((String)"Thaumcraft:blockCosmeticSolid", (int)3), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)4)}, (String)"aer 32, ordo 24, tutamen 32, auram 24, alienis 16", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:focusDeflect", (int)0), (int)6);
        Research.setAspects((String)"FOCUS_DEFLECT", (String)"alienis 15, praecantatio 12, permutatio 9, auram 6, aer 3");
        Research.setComplexity((String)"FOCUS_DEFLECT", (int)4);
        Research.addPrereq((String)"FOCUS_ENDER_CHEST", (String)"ENDERCHEST", (boolean)false);
        Arcane.addShaped((String)"FOCUS_ENDER_CHEST", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:focusEnderChest", (int)0), (String)"perditio 50, ordo 50", (IIngredient[][])new IIngredient[][]{{ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)14), ItemBracketHandler.getItem((String)"Thaumcraft:blockMirror", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)14)}, {OreBracketHandler.getOre((String)"plateEnderium"), ItemBracketHandler.getItem((String)"Thaumcraft:FocusPortableHole", (int)0), OreBracketHandler.getOre((String)"plateEnderium")}, {ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)14), OreBracketHandler.getOre((String)"plateNetherStar"), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)14)}});
        Research.setAspects((String)"FOCUS_ENDER_CHEST", (String)"alienis 15, vacuos 12, praecantatio 9, tenebrae 6, terra 3");
        Research.setComplexity((String)"FOCUS_ENDER_CHEST", (int)4);
        Warp.addToResearch((String)"ANIMATION_TABLET", (int)3);
        Infusion.addRecipe((String)"FOCUS_TELEKINESIS", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:focusFlight", (int)0), (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)0), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)17522), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)17355), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)17522), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)0), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)17522), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)17355), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)17522)}, (String)"aer 24, cognitio 32, motus 32, perditio 24, lucrum 16", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:focusTelekinesis", (int)0), (int)10);
        Research.setAspects((String)"FOCUS_TELEKINESIS", (String)"alienis 15, motus 15, praecantatio 12, cognitio 9, lucrum 6");
        Research.setComplexity((String)"FOCUS_TELEKINESIS", (int)4);
        Research.addPrereq((String)"FOCUS_DISLOCATION", (String)"FOCUSTRADE", (boolean)false);
        Infusion.addRecipe((String)"FOCUS_DISLOCATION", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:FocusTrade", (int)0), (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.02", (int)29500), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)17522), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.02", (int)29514), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)17522), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.02", (int)29500), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)17522), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.02", (int)29514), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)17522)}, (String)"alienis 64, praecantatio 32, tenebrae 32, vacuos 32, vitium 16, permutatio 16 ", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:focusDislocation", (int)0), (int)10);
        Research.setAspects((String)"FOCUS_DISLOCATION", (String)"alienis 15, permutatio 15, praecantatio 12, tenebrae 9, vacuos 6, vitium 3");
        Research.setComplexity((String)"FOCUS_DISLOCATION", (int)4);
        Warp.addToResearch((String)"FOCUS_DISLOCATION", (int)3);
        Infusion.addRecipe((String)"FOCUS_HEAL", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:FocusPech", (int)0), (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"minecraft:golden_apple", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)14), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)17351), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)14), ItemBracketHandler.getItem((String)"minecraft:golden_carrot", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)14), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)17351), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)14)}, (String)"sano 24, spiritus 32, praecantatio 32, victus 24", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:focusHeal", (int)0), (int)10);
        Research.setAspects((String)"FOCUS_HEAL", (String)"sano 15, victus 15, praecantatio 12, spiritus 9, cognitio 6");
        Research.setComplexity((String)"FOCUS_HEAL", (int)4);
        Research.addPrereq((String)"ENCHANTER", (String)"ENCHANTINGTABLE", (boolean)false);
        Research.addPrereq((String)"ENCHANTER", (String)"INFUSION", (boolean)false);
        Research.setConcealed((String)"ENCHANTER", (boolean)true);
        Infusion.addRecipe((String)"ENCHANTER", (IItemStack)ItemBracketHandler.getItem((String)"minecraft:enchanting_table", (int)0), (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"Thaumcraft:blockCosmeticSolid", (int)0), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)17330), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)17330), ItemBracketHandler.getItem((String)"ThaumicTinkerer:spellCloth", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:blockCosmeticSolid", (int)0), ItemBracketHandler.getItem((String)"ThaumicTinkerer:spellCloth", (int)0), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)17330), ItemBracketHandler.getItem((String)"ThaumicTinkerer:spellCloth", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:blockCosmeticSolid", (int)0), ItemBracketHandler.getItem((String)"ThaumicTinkerer:spellCloth", (int)0), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)17330), ItemBracketHandler.getItem((String)"Thaumcraft:blockCosmeticSolid", (int)0)}, (String)"alienis 64, cognitio 64, potentia 64, praecantatio 64, auram 64, vacuos 64 ", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:enchanter", (int)0), (int)12);
        Research.setAspects((String)"ENCHANTER", (String)"alienis 15, praecantatio 15, auram 12, tenebrae 12, vacuos 9, cognitio 6, terra 3");
        Research.setComplexity((String)"ENCHANTER", (int)4);
        Warp.addToResearch((String)"ENCHANTER", (int)3);
        Research.addPrereq((String)"SPELL_CLOTH", (String)"INFUSION", (boolean)false);
        Research.setConcealed((String)"SPELL_CLOTH", (boolean)true);
        Crucible.addRecipe((String)"SPELL_CLOTH", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:spellCloth", (int)0), (IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)7), (String)"perditio 16, praecantatio 16, permutatio 8, alienis 8");
        Research.setAspects((String)"SPELL_CLOTH", (String)"praecantatio 12, pannus 9, auram 6, alienis 3");
        Research.setComplexity((String)"SPELL_CLOTH", (int)3);
        Infusion.addRecipe((String)"XP_TALISMAN", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemBaubleBlanks", (int)0), (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"Thaumcraft:ItemZombieBrain", (int)0), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)17522), ItemBracketHandler.getItem((String)"Thaumcraft:ItemZombieBrain", (int)0), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)17086), ItemBracketHandler.getItem((String)"Thaumcraft:ItemZombieBrain", (int)0), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)17522), ItemBracketHandler.getItem((String)"Thaumcraft:ItemZombieBrain", (int)0), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)17500)}, (String)"bestia 24, lucrum 32, machina 16, permutatio 16, humanus 8", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:xpTalisman", (int)0), (int)8);
        Research.setAspects((String)"XP_TALISMAN", (String)"lucrum 15, praecantatio 12, humanus 9, auram 6, machina 3");
        Research.setComplexity((String)"XP_TALISMAN", (int)4);
        Arcane.addShaped((String)"REVEALING_HELM", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:revealingHelm", (int)0), (String)"aer 35, aqua 35, terra 35, ignis 35, ordo 35, perditio 35", (IIngredient[][])new IIngredient[][]{{OreBracketHandler.getOre((String)"screwThaumium"), OreBracketHandler.getOre((String)"craftingToolScrewdriver"), OreBracketHandler.getOre((String)"screwThaumium")}, {OreBracketHandler.getOre((String)"plateThaumium"), ItemBracketHandler.getItem((String)"Thaumcraft:ItemGoggles", (int)0), OreBracketHandler.getOre((String)"plateThaumium")}, {null, ItemBracketHandler.getItem((String)"Thaumcraft:ItemHelmetThaumium", (int)0), null}});
        Research.setAspects((String)"REVEALING_HELM", (String)"tutamen 15, auram 12, praecantatio 9, metallum 6, sensus 3");
        Research.setComplexity((String)"REVEALING_HELM", (int)4);
        Research.setConcealed((String)"TTENCH_ASCENT_BOOST", (boolean)true);
        Research.setAspects((String)"TTENCH_ASCENT_BOOST", (String)"aer 15, motus 12, praecantatio 9, auram 6, tempus 3");
        Research.setComplexity((String)"TTENCH_ASCENT_BOOST", (int)3);
        Research.setConcealed((String)"TTENCH_SLOW_FALL", (boolean)true);
        Research.setAspects((String)"TTENCH_SLOW_FALL", (String)"aer 15, motus 12, praecantatio 9, auram 6, tempus 3");
        Research.setComplexity((String)"TTENCH_SLOW_FALL", (int)3);
        Research.setConcealed((String)"TTENCH_AUTO_SMELT", (boolean)true);
        Research.setAspects((String)"TTENCH_AUTO_SMELT", (String)"ignis 15, perditio 12, praecantatio 9, auram 6, metallum 3");
        Research.setComplexity((String)"TTENCH_AUTO_SMELT", (int)3);
        Research.setConcealed((String)"TTENCH_DESINTEGRATE", (boolean)true);
        Research.setAspects((String)"TTENCH_DESINTEGRATE", (String)"vacuos 15, perditio 12, praecantatio 9, auram 6, tempus 3");
        Research.setComplexity((String)"TTENCH_DESINTEGRATE", (int)3);
        Research.setConcealed((String)"TTENCH_QUICK_DRAW", (boolean)true);
        Research.setAspects((String)"TTENCH_QUICK_DRAW", (String)"telum 15, sensus 12, praecantatio 9, auram 6, motus 3");
        Research.setComplexity((String)"TTENCH_QUICK_DRAW", (int)3);
        Research.setConcealed((String)"TTENCH_VAMPIRISM", (boolean)true);
        Research.setAspects((String)"TTENCH_VAMPIRISM", (String)"fames 15, telum 12, praecantatio 9, auram 6, lucrum 3");
        Research.setComplexity((String)"TTENCH_VAMPIRISM", (int)3);
        Research.setConcealed((String)"TTENCH_POUNCE", (boolean)true);
        Research.setAspects((String)"TTENCH_POUNCE", (String)"aer 15, ordo 15, tutamen 12, praecantatio 9, auram 6, volatus 3");
        Research.setComplexity((String)"TTENCH_POUNCE", (int)4);
        Research.setConcealed((String)"TTENCH_SHOCKWAVE", (boolean)true);
        Research.setAspects((String)"TTENCH_SHOCKWAVE", (String)"aer 15, perditio 15, tutamen 12, praecantatio 9, auram 6, volatus 3");
        Research.setComplexity((String)"TTENCH_SHOCKWAVE", (int)4);
        Research.setConcealed((String)"TTENCH_TUNNEL", (boolean)true);
        Research.setAspects((String)"TTENCH_TUNNEL", (String)"terra 15, ordo 15, instrumentum 12, praecantatio 9, auram 6, perfodio 3");
        Research.setComplexity((String)"TTENCH_TUNNEL", (int)4);
        Research.setConcealed((String)"TTENCH_SHATTER", (boolean)true);
        Research.setAspects((String)"TTENCH_SHATTER", (String)"terra 15, perditio 15, instrumentum 12, praecantatio 9, auram 6, perfodio 3");
        Research.setComplexity((String)"TTENCH_SHATTER", (int)4);
        Research.setConcealed((String)"TTENCH_FOCUSED", (boolean)true);
        Research.setAspects((String)"TTENCH_FOCUSED", (String)"ordo 15, telum 15, praecantatio 12, alienis 9, auram 6, bestia 3");
        Research.setComplexity((String)"TTENCH_FOCUSED", (int)4);
        Research.setConcealed((String)"TTENCH_DISPERSED", (boolean)true);
        Research.setAspects((String)"TTENCH_DISPERSED", (String)"perditio 15, telum 15, praecantatio 12, alienis 9, auram 6, bestia 3");
        Research.setComplexity((String)"TTENCH_DISPERSED", (int)4);
        Research.setConcealed((String)"TTENCH_VALIANCE", (boolean)true);
        Research.setAspects((String)"TTENCH_VALIANCE", (String)"sano 15, telum 15, praecantatio 12, alienis 9, auram 6, bestia 3");
        Research.setComplexity((String)"TTENCH_VALIANCE", (int)4);
        Research.setConcealed((String)"TTENCH_FINAL", (boolean)true);
        Research.setAspects((String)"TTENCH_FINAL", (String)"ordo 15, perditio 15, telum 15, praecantatio 12, alienis 9, auram 6, superbia 3");
        Research.setComplexity((String)"TTENCH_FINAL", (int)4);
        Compressor.addRecipe((IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:darkQuartz", (int)0), (IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:darkQuartzItem", (int)0).amount(4));
        CuttingSaw.addRecipe((IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:darkQuartzSlab", (int)0).amount(2), null, (IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:darkQuartz", (int)0), (ILiquidStack)LiquidBracketHandler.getLiquid((String)"water").withAmount(5), (int)100, (int)8);
        CuttingSaw.addRecipe((IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:darkQuartzSlab", (int)0).amount(2), null, (IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:darkQuartz", (int)0), (ILiquidStack)LiquidBracketHandler.getLiquid((String)"ic2distilledwater").withAmount(4), (int)100, (int)8);
        CuttingSaw.addRecipe((IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:darkQuartzSlab", (int)0).amount(2), null, (IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:darkQuartz", (int)0), (ILiquidStack)LiquidBracketHandler.getLiquid((String)"lubricant").withAmount(1), (int)50, (int)8);
        PrecisionLaser.addRecipe((IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:darkQuartz", (int)1), (IIngredient)ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)24506), (IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:darkQuartz", (int)0), (int)50, (int)16);
        PrecisionLaser.addRecipe((IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:darkQuartz", (int)1), (IIngredient)ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)24515), (IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:darkQuartz", (int)0), (int)50, (int)16);
        PrecisionLaser.addRecipe((IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:darkQuartz", (int)1), (IIngredient)ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)24545), (IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:darkQuartz", (int)0), (int)50, (int)16);
        PrecisionLaser.addRecipe((IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:darkQuartz", (int)1), (IIngredient)ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)24890), (IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:darkQuartz", (int)0), (int)50, (int)16);
        Research.refreshResearchRecipe((String)"INTERFACE");
        Research.refreshResearchRecipe((String)"DISLOCATOR");
        Research.refreshResearchRecipe((String)"GASEOUS_LIGHT");
        Research.refreshResearchRecipe((String)"GASEOUS_SHADOW");
        Research.refreshResearchRecipe((String)"GAS_REMOVER");
        Research.refreshResearchRecipe((String)"BRIGHT_NITOR");
        Research.refreshResearchRecipe((String)"FIRE_IGNIS");
        Research.refreshResearchRecipe((String)"FIRE_AQUA");
        Research.refreshResearchRecipe((String)"FIRE_TERRA");
        Research.refreshResearchRecipe((String)"FIRE_ORDO");
        Research.refreshResearchRecipe((String)"FIRE_AER");
        Research.refreshResearchRecipe((String)"FIRE_PERDITIO");
        Research.refreshResearchRecipe((String)"FUNNEL");
        Research.refreshResearchRecipe((String)"REPAIRER");
        Research.refreshResearchRecipe((String)"MAGNETS");
        Research.refreshResearchRecipe((String)"ANIMATION_TABLET");
        Research.refreshResearchRecipe((String)"LEVITATOR_LOCOMOTIVE");
        Research.refreshResearchRecipe((String)"CLEANSING_TALISMAN");
        Research.refreshResearchRecipe((String)"PLATFORM");
        Research.refreshResearchRecipe((String)"BLOOD_SWORD");
        Research.refreshResearchRecipe((String)"SUMMON");
        Research.refreshResearchRecipe((String)"FOCUS_SMELT");
        Research.refreshResearchRecipe((String)"FOCUS_FLIGHT");
        Research.refreshResearchRecipe((String)"FOCUS_DEFLECT");
        Research.refreshResearchRecipe((String)"FOCUS_ENDER_CHEST");
        Research.refreshResearchRecipe((String)"FOCUS_TELEKINESIS");
        Research.refreshResearchRecipe((String)"FOCUS_DISLOCATION");
        Research.refreshResearchRecipe((String)"FOCUS_HEAL");
        Research.refreshResearchRecipe((String)"ENCHANTER");
        Research.refreshResearchRecipe((String)"SPELL_CLOTH");
        Research.refreshResearchRecipe((String)"XP_TALISMAN");
        Research.refreshResearchRecipe((String)"REVEALING_HELM");
        Research.refreshResearchRecipe((String)"TTENCH_ASCENT_BOOST");
        Research.refreshResearchRecipe((String)"TTENCH_SLOW_FALL");
        Research.refreshResearchRecipe((String)"TTENCH_AUTO_SMELT");
        Research.refreshResearchRecipe((String)"TTENCH_DESINTEGRATE");
        Research.refreshResearchRecipe((String)"TTENCH_QUICK_DRAW");
        Research.refreshResearchRecipe((String)"TTENCH_VAMPIRISM");
        Research.refreshResearchRecipe((String)"TTENCH_POUNCE");
        Research.refreshResearchRecipe((String)"TTENCH_SHOCKWAVE");
        Research.refreshResearchRecipe((String)"TTENCH_TUNNEL");
        Research.refreshResearchRecipe((String)"TTENCH_SHATTER");
        Research.refreshResearchRecipe((String)"TTENCH_FOCUSED");
        Research.refreshResearchRecipe((String)"TTENCH_DISPERSED");
        Research.refreshResearchRecipe((String)"TTENCH_VALIANCE");
        Research.refreshResearchRecipe((String)"TTENCH_FINAL");
    }
}

