package com.github.GTNH2Mega.fromScripts;
import minetweaker.api.item.IItemStack;
import minetweaker.mc1710.brackets.ItemBracketHandler;
import modtweaker2.mods.thaumcraft.handlers.Aspects;
import static com.github.GTNH2Mega.VoltageLevels.*;
public class Thaumcraft07AspectAdds
implements Runnable {
    public void run() {
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"BiomesOPlenty:bones", (int)0), (String)"corpus 1, exanimis 3, mortuus 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"BiomesOPlenty:bones", (int)1), (String)"corpus 2, exanimis 6, mortuus 4");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"BiomesOPlenty:bones", (int)2), (String)"corpus 3, exanimis 9, mortuus 6");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"ForbiddenMagic:WandCores", (int)5), (String)"terra 32, praecantatio 24, vitreus 16, infernus 8, tenebrae 4,");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"GalacticraftCore:tile.moonBlock", (int)3), (String)"alienis 2, vacuos 2, tenebrae 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"GalacticraftCore:tile.moonBlock", (int)4), (String)"alienis 2, vacuos 3, tenebrae 3");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"GalacticraftCore:tile.moonBlock", (int)5), (String)"alienis 1, vacuos 1, tenebrae 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"GalacticraftCore:tile.moonBlock", (int)14), (String)"alienis 4, ira 1, superbia 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"dreamcraft:item.MoonStoneDust", (int)0), (String)"alienis 1, perditio 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"GalacticraftMars:tile.mars", (int)4), (String)"alienis 1, perditio 1, ignis 1, terra 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"GalacticraftMars:tile.mars", (int)5), (String)"alienis 1, metallum 1, ignis 2, terra 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"GalacticraftMars:tile.mars", (int)6), (String)"alienis 2, metallum 2, ignis 2, terra 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"GalacticraftMars:tile.mars", (int)7), (String)"alienis 1, metallum 1, ira 2, superbia 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"GalacticraftMars:tile.mars", (int)9), (String)"alienis 2, metallum 3, ignis 3, terra 3");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"dreamcraft:item.MarsStoneDust", (int)0), (String)"alienis 1, perditio 1, terra 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"GalacticraftMars:tile.asteroidsBlock", (int)0), (String)"alienis 1, tenebrae 1, vacuos 1, gelum 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"GalacticraftMars:tile.asteroidsBlock", (int)1), (String)"alienis 2, tenebrae 2, vacuos 2, gelum 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"GalacticraftMars:tile.asteroidsBlock", (int)2), (String)"alienis 3, tenebrae 3, vacuos 3, gelum 3");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"dreamcraft:item.AsteroidsStoneDust", (int)0), (String)"alienis 1, perditio 1, gelum 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"GalacticraftCore:tile.landingPad", (int)1), (String)"metallum 5, ordo 5");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"GalacticraftCore:item.basicItem", (int)6), (String)"metallum 4, fabrico 2, permutatio 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"GalacticraftCore:item.basicItem", (int)7), (String)"metallum 4, fabrico 2, vitreus 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"GalacticraftCore:item.basicItem", (int)8), (String)"metallum 6, volatus 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"GalacticraftCore:item.basicItem", (int)9), (String)"metallum 6, ordo 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"GalacticraftCore:item.basicItem", (int)10), (String)"metallum 6, instrumentum 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"GalacticraftCore:item.basicItem", (int)11), (String)"metallum 8");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"GalacticraftCore:item.meteoricIronIngot", (int)1), (String)"metallum 4, magneto 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"GalacticraftMars:item.null", (int)5), (String)"metallum 4, vacuos 2, tenebrae 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"GalacticraftMars:item.itemBasicAsteroids", (int)6), (String)"metallum 4, tutamen 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"GalacticraftCore:item.basicItem", (int)13), (String)"fabrico 6, ordo 5, machina 4, instrumentum 3, metallum 3");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"GalacticraftCore:item.basicItem", (int)14), (String)"fabrico 9, ordo 7, machina 6, instrumentum 5, metallum 5, lux 4");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"dreamcraft:item.WaferTier3", (int)0), (String)"fabrico 12, ordo 10, machina 9, instrumentum 8, metallum 7, lux 6, alienis 4");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"GalacticraftCore:tile.aluminumWire", (int)0), (String)"metallum 4, volatus 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"GalacticraftCore:tile.oxygenPipe", (int)0), (String)"metallum 1, gelum 1, vitreus 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"GalacticraftCore:tile.glowstoneTorch", (int)0), (String)"potentia 1, machina 1, lux 1, sensus 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"GalacticraftCore:tile.arclamp", (int)0), (String)"potentia 5, machina 2, lux 5, tenebrae 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"GalacticraftCore:item.basicItem", (int)0), (String)"potentia 2, electrum 2, tenebrae 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"GalacticraftCore:item.canister", (int)0), (String)"metallum 1, vitreus 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"GalacticraftCore:item.canister", (int)1), (String)"metallum 1, permutatio 1, fabrico 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"GalacticraftCore:item.steelPole", (int)0), (String)"metallum 5, ordo 5");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"GalacticraftCore:item.heavyPlating", (int)0), (String)"metallum 6, ordo 2, volatus 2, instrumentum 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"GalacticraftMars:item.null", (int)3), (String)"metallum 8, ordo 2, volatus 2, instrumentum 1, magneto 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"GalacticraftMars:item.itemBasicAsteroids", (int)0), (String)"metallum 10, ordo 2, volatus 2, instrumentum 1, magneto 2, vacuos 2, tenebrae 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"GalacticraftCore:item.oxygenMask", (int)0), (String)"tutamen 2, gelum 1, vitreus 1, metallum 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"GalacticraftCore:item.battery", (int)0), (String)"electrum 6, metallum 2, vacuos 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"GalacticraftCore:item.basicItem", (int)15), (String)"metallum 1, vitreus 1, messis 3");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"GalacticraftCore:item.basicItem", (int)16), (String)"metallum 1, vitreus 1, messis 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"GalacticraftCore:item.basicItem", (int)17), (String)"metallum 1, vitreus 1, messis 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"GalacticraftCore:item.basicItem", (int)18), (String)"metallum 1, vitreus 1, messis 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"GalacticraftCore:item.meteoricIronRaw", (int)0), (String)"magneto 2, metallum 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"GalacticraftMars:item.thermalPadding", (int)0), (String)"pannus 12, bestia 6, fabrico 3, aqua 2, ordo 2, perditio 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"GalacticraftMars:item.thermalPadding", (int)1), (String)"pannus 18, bestia 9, fabrico 5, aqua 3, ordo 3, perditio 3");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"GalacticraftMars:item.thermalPadding", (int)2), (String)"pannus 15, bestia 7, fabrico 4, aqua 3, ordo 3, perditio 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"GalacticraftMars:item.thermalPadding", (int)3), (String)"pannus 9, bestia 5, fabrico 2, aqua 1, ordo 1, perditio 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"GalacticraftMars:item.null", (int)0), (String)"metallum 1, tenebrae 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"GalacticraftMars:tile.hydrogenPipe", (int)0), (String)"metallum 1, gelum 1, vitreus 1, permutatio 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"GalacticraftMars:item.bucketSludge", (int)0), (String)"venenum 4, aqua 2, alienis 2, metallum 3");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"GalacticraftCore:item.oilCanisterPartial", (int)1001), (String)"metallum 4, ordo 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"GalacticraftMars:item.methaneCanisterPartial", (int)1), (String)"metallum 4, ordo 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"GalacticraftMars:item.canisterPartialLOX", (int)1), (String)"metallum 4, ordo 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"GalacticraftMars:item.canisterPartialLN2", (int)1), (String)"metallum 4, ordo 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"GalacticraftCore:item.fuelCanisterPartial", (int)1), (String)"metallum 4, ordo 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"GalacticraftMars:tile.creeperEgg", (int)0), (String)"alienis 10, perditio 5");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"GalacticraftMars:tile.denseIce", (int)0), (String)"alienis 5, gelum 5");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:blockMetal", (int)5), (String)"metallum 18, ordo 5");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemPartCircuitAdv", (int)0), (String)"fabrico 9, ordo 7, machina 6, instrumentum 5, metallum 5, lux 4");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemPartAlloy", (int)0), (String)"metallum 4, vacuos 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemIngot", (int)4), (String)"metallum 3");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"dreamcraft:item.ReinforcedGlassPlate", (int)0), (String)"metallum 1, gelum 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"dreamcraft:item.ReinforcedGlassPlate", (int)0), (String)"metallum 1, gelum 1, vitreus 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:blockAlloy", (int)0), (String)"metallum 4, ordo 3, terra 2, fabrico 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:blockMetal", (int)0), (String)"metallum 6, permutatio 3");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:blockMetal", (int)1), (String)"metallum 6, vitreus 3");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:blockMetal", (int)2), (String)"metallum 6, instrumentum 3");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:blockMetal", (int)4), (String)"metallum 6, ordo 3");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:blockMetal", (int)3), (String)"metallum 4, venenum 2, potentia 2, radio 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:blockGenerator", (int)6), (String)"metallum 40, fabrico 30, ordo 15, tutamen 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:blockHeatGenerator", (int)2), (String)"metallum 30, fabrico 18, ordo 8, permutatio 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:blockreactorvessel", (int)0), (String)"metallum 5, fabrico 3, ordo 3, terra 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:blockReactorFluidPort", (int)0), (String)"metallum 5, fabrico 3, iter 3, aqua 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:blockReactorAccessHatch", (int)0), (String)"metallum 5, fabrico 3, iter 3, machina 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:blockReactorRedstonePort", (int)0), (String)"metallum 5, fabrico 3, sensus 2, machina 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:blockElectric", (int)3), (String)"metallum 11, fabrico 4, ordo 4, motus 3");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:blockElectric", (int)4), (String)"metallum 11, fabrico 4, volatus 3");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:blockElectric", (int)5), (String)"fabrico 5, machina 4, metallum 4, ignis 4");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:blockElectric", (int)6), (String)"metallum 7, fabrico 4, tutamen 3, motus 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:blockMachine", (int)6), (String)"metallum 64, fabrico 64, ordo 64, instrumentum 50");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemPartCarbonPlate", (int)0), (String)"metallum 4, ignis 4, vitreus 4");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:blockMachine", (int)12), (String)"metallum 32, fabrico 8, vacuos 4, ignis 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemHarz", (int)0), (String)"limus 2, motus 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:blockMiningPipe", (int)0), (String)"metallum 4");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:blockLuminatorDark", (int)0), (String)"lux 4, ignis 2, tenebrae 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:blockITNT", (int)0), (String)"ignis 4, perditio 8, potentia 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemRecipePart", (int)11), (String)"metallum 27");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemRecipePart", (int)12), (String)"metallum 18, ordo 5");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemRecipePart", (int)0), (String)"metallum 17, fabrico 3, instrumentum 2, magneto 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemRecipePart", (int)1), (String)"machina 1, electrum 1, motus 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemRecipePart", (int)1), (String)"sensus 1, fabrico 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemRecipePart", (int)1), (String)"fabrico 2, metallum 1, sano 1, tenebrae 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemUran", (int)0), (String)"vitreus 14, gelum 6, radio 3, permutatio 6");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemMOX", (int)0), (String)"radio 3, metallum 3, permutatio 6, vitreus 10");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemPlutonium", (int)0), (String)"radio 3, metallum 3");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemPlutoniumSmall", (int)0), (String)"metallum 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemDust2", (int)2), (String)"lucrum 4, potentia 3, machina 2, vitreus 3");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemUran235", (int)0), (String)"metallum 3, radio 3");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemContainmentbox", (int)0), (String)"fabrico 3, instrumentum 3, ordo 3, metallum 3");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemRTGPellet", (int)0), (String)"metallum 15, fabrico 6, radio 15");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemFuelRod", (int)0), (String)"metallum 4, fabrico 4, instrumentum 2, ordo 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemPartCarbonFibre", (int)0), (String)"metallum 3, ignis 3, vitreus 3");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemPartCarbonMesh", (int)0), (String)"metallum 2, ignis 2, vitreus 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemToolbox", (int)0), (String)"fabrico 3, metallum 3, instrumentum 2, ordo 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemShardIridium", (int)0), (String)"metallum 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemPartIridium", (int)0), (String)"metallum 8, fabrico 4, machina 4, vitreus 4");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemToolMEter", (int)0), (String)"fabrico 15, instrumentum 6, cognitio 2, lux 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemScanner", (int)0), (String)"fabrico 18, instrumentum 8, cognitio 4, lux 4");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemScannerAdv", (int)0), (String)"fabrico 10, instrumentum 10, cognitio 6, lux 6");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:obscurator", (int)0), (String)"instrumentum 6, lux 4, machina 4, tenebrae 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemFreq", (int)0), (String)"metallum 6, instrumentum 4, sensus 4, electrum 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemBatREDischarged", (int)0), (String)"metallum 1, electrum 1, vacuos 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemBatCrystal", (int)0), (String)"lucrum 6, potentia 5, vitreus 4, potentia 4");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemBatLamaCrystal", (int)0), (String)"lucrum 8, potentia 6, sensus 5, potentia 5");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemAdvBat", (int)0), (String)"electrum 2, metallum 2, vacuos 2, potentia 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemBatChargeRE", (int)0), (String)"metallum 2, electrum 2, vacuos 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemBatChargeAdv", (int)0), (String)"electrum 3, metallum 3, vacuos 3, potentia 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemBatChargeCrystal", (int)0), (String)"lucrum 10, potentia 8, sensus 6, potentia 6");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemBatChargeLamaCrystal", (int)0), (String)"lucrum 12, potentia 9, sensus 7, potentia 7");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemGrinPowder", (int)0), (String)"venenum 3, messis 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemFuelPlantBall", (int)0), (String)"herba 4");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemBiochaff", (int)0), (String)"herba 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemFertilizer", (int)0), (String)"ignis 2, sano 2, ignis 1, herba 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemWeed", (int)0), (String)"herba 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemPartCoalBall", (int)0), (String)"potentia 2, ignis 2, terra 1, instrumentum 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemPartCoalBlock", (int)0), (String)"potentia 4, ignis 4, terra 2, instrumentum 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemPartCoalBlock", (int)0), (String)"perditio 2, terra 2, tenebrae 1, lux 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemScrap", (int)0), (String)"strontio 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemScrapbox", (int)0), (String)"strontio 4");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemToolPainterBlack", (int)0), (String)"pannus 10, fabrico 4, ordo 4, instrumentum 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemToolPainterCloud", (int)0), (String)"pannus 10, fabrico 4, ordo 4, instrumentum 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemToolPainterMagenta", (int)0), (String)"pannus 10, fabrico 4, ordo 4, instrumentum 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemToolPainterOrange", (int)0), (String)"pannus 10, fabrico 4, ordo 4, instrumentum 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemToolPainterWhite", (int)0), (String)"pannus 10, fabrico 4, ordo 4, instrumentum 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemToolPainterRed", (int)0), (String)"pannus 10, fabrico 4, ordo 4, instrumentum 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemToolPainterGreen", (int)0), (String)"pannus 10, fabrico 4, ordo 4, instrumentum 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemToolPainterBrown", (int)0), (String)"pannus 10, fabrico 4, ordo 4, instrumentum 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemToolPainterBlue", (int)0), (String)"pannus 10, fabrico 4, ordo 4, instrumentum 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemToolPainterLime", (int)0), (String)"pannus 10, fabrico 4, ordo 4, instrumentum 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemToolPainterYellow", (int)0), (String)"pannus 10, fabrico 4, ordo 4, instrumentum 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemToolPainterPink", (int)0), (String)"pannus 10, fabrico 4, ordo 4, instrumentum 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemToolPainterDarkGrey", (int)0), (String)"pannus 10, fabrico 4, ordo 4, instrumentum 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemToolPainterLightGrey", (int)0), (String)"pannus 10, fabrico 4, ordo 4, instrumentum 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemToolPainterCyan", (int)0), (String)"pannus 10, fabrico 4, ordo 4, instrumentum 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemToolPainterPurple", (int)0), (String)"pannus 10, fabrico 4, ordo 4, instrumentum 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:reactorVent", (int)1), (String)"metallum 12, fabrico 4, volatus 4, gelum 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:reactorVentCore", (int)1), (String)"metallum 20, fabrico 8, lucrum 4, gelum 4");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:reactorVentGold", (int)1), (String)"metallum 24, fabrico 12, lucrum 9, gelum 6");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:reactorVentDiamond", (int)1), (String)"metallum 26, fabrico 14, lucrum 10, gelum 7");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:reactorHeatSwitch", (int)1), (String)"metallum 12, fabrico 4, permutatio 4, gelum 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:reactorHeatSwitchCore", (int)1), (String)"metallum 20, fabrico 8, permutatio 4, gelum 4");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:reactorHeatSwitchSpread", (int)1), (String)"metallum 24, fabrico 12, permutatio 9, gelum 6");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:reactorHeatSwitchDiamond", (int)1), (String)"metallum 26, fabrico 14, permutatio 10, gelum 7");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemwoodrotor", (int)1), (String)"tempestas 2, arbor 4, metallum 2, permutatio 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemironrotor", (int)1), (String)"tempestas 4, metallum 4, instrumentum 2, permutatio 4");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemsteelrotor", (int)1), (String)"tempestas 6, metallum 6, instrumentum 4, permutatio 6");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemwcarbonrotor", (int)1), (String)"tempestas 8, metallum 8, instrumentum 6, permutatio 8");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:reactorReflector", (int)1), (String)"metallum 4, ignis 4, vitreus 2, fabrico 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:reactorReflectorThick", (int)1), (String)"metallum 8, ignis 4, lucrum 4, fabrico 4");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:reactorCondensator", (int)1), (String)"metallum 24, fabrico 16, permutatio 8, gelum 8");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:reactorCondensatorLap", (int)1), (String)"metallum 24, fabrico 16, permutatio 16, gelum 16");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:upgradeModule", (int)0), (String)"instrumentum 4, fabrico 4, metallum 4, motus 4");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:upgradeModule", (int)1), (String)"instrumentum 4, fabrico 4, metallum 4, electrum 4");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:upgradeModule", (int)2), (String)"instrumentum 4, fabrico 4, metallum 4, lucrum 4");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:upgradeModule", (int)3), (String)"instrumentum 4, fabrico 4, metallum 4, permutatio 4");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:upgradeModule", (int)4), (String)"instrumentum 4, fabrico 4, metallum 4, aqua 4");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:upgradeModule", (int)5), (String)"instrumentum 4, fabrico 4, metallum 4, cognitio 4");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:upgradeModule", (int)6), (String)"instrumentum 4, fabrico 4, metallum 4, ignis 4");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemBoat", (int)0), (String)"metallum 8, ignis 8, vitreus 8");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemBoat", (int)2), (String)"fabrico 1, limus 1, motus 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemCoin", (int)0), (String)"metallum 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemCropnalyzer", (int)1), (String)"cognitio 8, lux 2, metallum 4, instrumentum 4");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemHops", (int)0), (String)"herba 4");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemCofeeBeans", (int)0), (String)"sensus 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemDynamite", (int)0), (String)"perditio 8, strontio 4");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemDynamiteSticky", (int)0), (String)"perditio 8, limus 2, strontio 4");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemMugCoffee", (int)1), (String)"sensus 2, tenebrae 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemMugCoffee", (int)2), (String)"sensus 4");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemRemote", (int)0), (String)"metallum 6, instrumentum 4, sensus 4, perditio 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemWeedEx", (int)0), (String)"venenum 8, cognitio 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemTerraWart", (int)0), (String)"auram 8, praecantatio 4, victus 4");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemCellEmpty", (int)0), (String)"fabrico 2, metallum 2, vitreus 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemTinCan", (int)0), (String)"fabrico 1, metallum 1, vitreus 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemTinCanFilled", (int)0), (String)"fabrico 2, metallum 2, vitreus 2, victus 4");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:itemCellHydrant", (int)1), (String)"aqua 8, metallum 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:reactorCoolantSimple", (int)1), (String)"gelum 4, metallum 2, vitreus 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:reactorCoolantTriple", (int)1), (String)"gelum 8, metallum 4, vitreus 4");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"IC2:reactorCoolantSix", (int)1), (String)"gelum 16, metallum 8, vitreus 8");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"malisisdoors:trapdoor_acacia", (int)0), (String)"arbor 2, motus 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"malisisdoors:trapdoor_birch", (int)0), (String)"arbor 2, motus 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"malisisdoors:trapdoor_dark_oak", (int)0), (String)"arbor 2, motus 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"malisisdoors:trapdoor_jungle", (int)0), (String)"arbor 2, motus 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"malisisdoors:trapdoor_spruce", (int)0), (String)"arbor 2, motus 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"minecraft:blaze_powder", (int)0), (String)"ignis 6, praecantatio 4, instrumentum 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"minecraft:blaze_rod", (int)0), (String)"ignis 10, praecantatio 4");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"minecraft:paper", (int)0), (String)"cognitio 4, aqua 2, arbor 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"minecraft:book", (int)0), (String)"pannus 1, cognitio 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"minecraft:enchanted_book", (int)0), (String)"pannus 1, cognitio 1, metallum 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"minecraft:hopper", (int)0), (String)"metallum 15, arbor 4, vacuos 3, machina 1, permutatio 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"minecraft:furnace", (int)0), (String)"terra 6, perditio 6, ignis 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"minecraft:stone_pressure_plate", (int)0), (String)"terra 3, machina 1, sensus 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"minecraft:redstone_torch", (int)0), (String)"potentia 1, machina 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"Natura:trapdoor.eucalyptus", (int)0), (String)"arbor 2, motus 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"Natura:trapdoor.sakura", (int)0), (String)"arbor 2, motus 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"Natura:trapdoor.ghostwood", (int)0), (String)"arbor 2, motus 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"Natura:trapdoor.redwood", (int)0), (String)"arbor 2, motus 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"Natura:trapdoor.bloodwood", (int)0), (String)"arbor 2, motus 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"Natura:trapdoor.hopseed", (int)0), (String)"arbor 2, motus 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"Natura:trapdoor.maple", (int)0), (String)"arbor 2, motus 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"Natura:trapdoor.amaranth", (int)0), (String)"arbor 2, motus 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"Natura:trapdoor.silverbell", (int)0), (String)"arbor 2, motus 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"Natura:trapdoor.willow", (int)0), (String)"arbor 2, motus 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"Natura:trapdoor.darkwood", (int)0), (String)"arbor 2, motus 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"Natura:trapdoor.fusewood", (int)0), (String)"arbor 2, motus 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)4), (String)"corpus 4, praecantatio 2, mortuus 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:blockCandle", (int)0), (String)"lux 5, praecantatio 2, pannus 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.TFRoots", (int)0), (String)"arbor 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.TFRoots", (int)1), (String)"arbor 2, praecantatio 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:item.liveRoot", (int)0), (String)"arbor 1, praecantatio 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.TFFirefly", (int)0), (String)"victus 1, volatus 1, lux 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.TFCicada", (int)0), (String)"victus 1, volatus 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.TFPortal", (int)0), (String)"tempus 4, praecantatio 4, iter 4");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.TFMazestone", (int)0), (String)"terra 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.TFMazestone", (int)1), (String)"terra 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.TFMazestone", (int)2), (String)"terra 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.TFMazestone", (int)3), (String)"terra 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.TFMazestone", (int)4), (String)"terra 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.TFMazestone", (int)5), (String)"terra 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.TFMazestone", (int)6), (String)"terra 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.TFMazestone", (int)7), (String)"terra 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.TFHedge", (int)0), (String)"herba 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.TFFireflyJar", (int)0), (String)"vitreus 2, arbor 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.TFPlant", (int)3), (String)"herba 2, victus 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.TFPlant", (int)4), (String)"herba 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.TFPlant", (int)8), (String)"herba 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.TFPlant", (int)9), (String)"herba 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.TFPlant", (int)10), (String)"herba 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.TFPlant", (int)11), (String)"herba 1, perditio 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.TFPlant", (int)13), (String)"herba 1, lux 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.TFPlant", (int)14), (String)"arbor 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.TFFireJet", (int)0), (String)"ignis 2, aer 2, machina 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.TFFireJet", (int)8), (String)"ignis 6, motus 2, machina 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.TFNagastone", (int)1), (String)"terra 3");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.TFNagastone", (int)13), (String)"terra 3");
        Aspects.add((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.TFSapling", (int)5), (String)"tempus 1");
        Aspects.add((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.TFSapling", (int)6), (String)"praecantatio 1");
        Aspects.add((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.TFSapling", (int)7), (String)"perfodio 1");
        Aspects.add((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.TFSapling", (int)9), (String)"sensus 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.TFMoonworm", (int)0), (String)"victus 1, lux 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.TFMagicLogSpecial", (int)0), (String)"arbor 4, praecantatio 2, tempus 2, herba 2, lux 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.TFMagicLogSpecial", (int)1), (String)"arbor 4, praecantatio 2, aer 2, herba 2, invidia 1, lux 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.TFMagicLogSpecial", (int)2), (String)"arbor 4, praecantatio 2, perfodio 2, herba 2, lucrum 1, lux 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.TFMagicLogSpecial", (int)3), (String)"arbor 4, praecantatio 2, motus 2, herba 2, cognitio 1, lux 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.TFTowerDevice", (int)2), (String)"arbor 1, machina 1, potentia 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.TFTowerDevice", (int)4), (String)"arbor 1, machina 1, potentia 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.TFTowerDevice", (int)5), (String)"arbor 1, machina 1, potentia 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.TFTowerDevice", (int)6), (String)"arbor 1, machina 1, potentia 2, iter 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.TFTowerDevice", (int)9), (String)"arbor 1, machina 2, potentia 4, perditio 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.TFTowerDevice", (int)10), (String)"arbor 1, machina 2, potentia 4, vinculum 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.TFShield", (int)0), (String)"terra 4, machina 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.TFTrophyPedestal", (int)0), (String)"terra 7, ordo 4, lucrum 4, instrumentum 4");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.TFTrophyPedestal", (int)15), (String)"terra 7, ordo 12, lucrum 12, instrumentum 4");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.TFAuroraBrick", (int)0), (String)"terra 4, sensus 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.TFUnderBrick", (int)0), (String)"terra 3, ignis 3");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.TFUnderBrick", (int)1), (String)"terra 3, ignis 3");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.TFUnderBrick", (int)2), (String)"terra 3, ignis 3, perditio 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.TFThorns", (int)0), (String)"arbor 2, fabrico 1, telum 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.TFThorns", (int)1), (String)"herba 3, fabrico 1, telum 1, aqua 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.TFBurntThorns", (int)0), (String)"arbor 2, perditio 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.TFThornRose", (int)0), (String)"herba 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.TFLeaves3", (int)0), (String)"herba 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.TFLeaves3", (int)1), (String)"herba 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.TFDeadrock", (int)0), (String)"terra 8, ignis 6");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.TFDeadrock", (int)1), (String)"terra 8, ignis 6");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.TFDeadrock", (int)2), (String)"terra 8, ignis 6");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.DarkLeaves", (int)0), (String)"herba 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.AuroraPillar", (int)0), (String)"terra 4, sensus 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.AuroraSlab", (int)0), (String)"terra 2, sensus 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.AuroraDoubleSlab", (int)0), (String)"terra 4, sensus 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.TrollSteinn", (int)0), (String)"terra 4, potentia 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.WispyCloud", (int)0), (String)"aer 1, volatus 1, aqua 1, tempestas 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.FluffyCloud", (int)0), (String)"aer 1, volatus 1, pannus 1, tempestas 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.HugeStalk", (int)0), (String)"herba 4");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.GiantCobble", (int)0), (String)"terra 16, perditio 16");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.GiantLog", (int)0), (String)"arbor 16");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.GiantLeaves", (int)0), (String)"herba 16");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.GiantObsidian", (int)0), (String)"terra 16, ignis 16, tenebrae 8");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.UberousSoil", (int)0), (String)"terra 4, aqua 4, herba 4, victus 10");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.HugeGloomBlock", (int)0), (String)"terra 4, tenebrae 2, herba 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.KnightmetalBlock", (int)0), (String)"metallum 18, lucrum 9");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.UnripeTrollBer", (int)0), (String)"herba 1, terra 1, perditio 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.TrollBer", (int)0), (String)"herba 1, terra 1, lux 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.HugeLilyPad", (int)0), (String)"herba 8, aqua 4");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.HugeWaterLily", (int)0), (String)"herba 3");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.Slider", (int)0), (String)"arbor 2 vinculum 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.CastleBrick", (int)0), (String)"terra 3, ignis 3");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.CastleBrick", (int)1), (String)"terra 3, ignis 3, perditio 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.CastleBrick", (int)2), (String)"terra 3, ignis 3, perditio 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.CastleBrick", (int)3), (String)"terra 3, ignis 3, tenebrae 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.CastleMagic", (int)0), (String)"terra 3, ignis 3, praecantatio 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.CastleMagic", (int)1), (String)"terra 3, ignis 3, praecantatio 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.CastleMagic", (int)2), (String)"terra 3, ignis 3, praecantatio 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:tile.CastleMagic", (int)3), (String)"terra 3, ignis 3, praecantatio 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:item.nagaScale", (int)0), (String)"pannus 3, tutamen 2, bestia 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:item.plateNaga", (int)0), (String)"pannus 24, tutamen 16, bestia 16, superbia 4");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:item.legsNaga", (int)0), (String)"pannus 21, tutamen 14, bestia 14, superbia 3");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:item.scepterTwilight", (int)0), (String)"alienis 40, iter 35, praecantatio 25, mortuus 20, corpus 10");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:item.scepterLifeDrain", (int)0), (String)"alienis 40, victus 15, gula 20, praecantatio 25, mortuus 20, corpus 10");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:item.scepterZombie", (int)0), (String)"alienis 40, exanimis 35, praecantatio 25, mortuus 20, corpus 10");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:item.scepterTwilight", (int)32767), (String)"alienis 40, iter 35, praecantatio 25, mortuus 20, corpus 10");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:item.scepterLifeDrain", (int)32767), (String)"alienis 40, victus 15, gula 20, praecantatio 25, mortuus 20, corpus 10");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:item.scepterZombie", (int)32767), (String)"alienis 40, exanimis 35, praecantatio 25, mortuus 20, corpus 10");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:item.tfFeather", (int)0), (String)"volatus 2, aer 1, tenebrae 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:item.magicMapFocus", (int)0), (String)"volatus 2, aer 1, tenebrae 1, lux 1, praecantatio 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:item.venisonRaw", (int)0), (String)"mortuus 3, victus 2, bestia 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:item.venisonCooked", (int)0), (String)"mortuus 4, fames 3, fabrico 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:item.hydraChop", (int)0), (String)"mortuus 9, victus 6, bestia 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:item.fieryBlood", (int)0), (String)"vacuos 1, victus 4, aqua 3");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:item.trophy", (int)0), (String)"lucrum 10, luxuria 1, superbia 2, fabrico 4, ignis 8");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:item.trophy", (int)1), (String)"lucrum 10, luxuria 1, superbia 2, fabrico 4, terra 8");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:item.trophy", (int)2), (String)"lucrum 10, luxuria 1, superbia 2, fabrico 4, exanimis 8");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:item.trophy", (int)3), (String)"lucrum 10, luxuria 1, superbia 2, fabrico 4, infernus 8");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:item.trophy", (int)4), (String)"lucrum 10, luxuria 1, superbia 2, fabrico 4, gelum 8");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:item.minotaurAxe", (int)0), (String)"metallum 10, fabrico 4, telum 8, instrumentum 8, superbia 4");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:item.transformPowder", (int)0), (String)"mortuus 4, fames 3, fabrico 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:item.meefRaw", (int)0), (String)"mortuus 3, victus 2, bestia 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:item.meefSteak", (int)0), (String)"mortuus 4, fames 3, fabrico 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:item.meefStroganoff", (int)0), (String)"mortuus 4, fames 4, fabrico 2, arbor 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:item.mazeWafer", (int)0), (String)"messis 4, fames 3, fabrico 1, sano 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:item.oreMagnet", (int)0), (String)"metallum 6, magneto 4, perfodio 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:item.oreMagnet", (int)32767), (String)"metallum 6, magneto 4, perfodio 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:item.crumbleHorn", (int)0), (String)"arbor 18, praecantatio 14, ordo 12, auram 8");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:item.crumbleHorn", (int)32767), (String)"arbor 18, praecantatio 14, ordo 12, auram 8");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:item.peacockFan", (int)0), (String)"aer 18, volatus 10, motus 10, praecantatio 6, arbor 4");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:item.peacockFan", (int)32767), (String)"aer 18, volatus 10, motus 10, praecantatio 6, arbor 4");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:item.moonwormQueen", (int)0), (String)"victus 10, lux 10, motus 4");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:item.moonwormQueen", (int)32767), (String)"victus 10, lux 10, motus 4");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:item.charmOfLife1", (int)0), (String)"sano 16, ordo 16, praecantatio 8, victus 8, lucrum 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:item.charmOfLife2", (int)0), (String)"sano 64, ordo 64, praecantatio 32, victus 32, lucrum 4");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:item.charmOfKeeping1", (int)0), (String)"instrumentum 4, ordo 4, praecantatio 3, tutamen 3, lucrum 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:item.charmOfKeeping2", (int)0), (String)"instrumentum 16, ordo 16, praecantatio 8, tutamen 8, lucrum 4");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:item.charmOfKeeping3", (int)0), (String)"instrumentum 64, ordo 64, praecantatio 32, tutamen 32, lucrum 16");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:item.towerKey", (int)0), (String)"metallum 2, lucrum 2, lux 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:item.borerEssence", (int)0), (String)"praecantatio 2, lucrum 2, ordo 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:item.experiment115", (int)0), (String)"messis 5, fames 4, fabrico 2, alienis 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:item.phantomHelm", (int)0), (String)"tutanem 5, fabrico 3, metallum 7, spiritus 5, instrumentum 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:item.phantomPlate", (int)0), (String)"tutanem 8, fabrico 5, metallum 11, spiritus 8, instrumentum 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:item.lampOfCinders", (int)0), (String)"lucrum 16, ignis 10, fabrico 6, praecantatio 8, instrumentum 4, luxuria 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:item.fieryTears", (int)0), (String)"vacuos 1, ira 4, exanimis 4, spiritus 4, praecantatio 2, aqua 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:item.alphaFur", (int)0), (String)"pannus 6, gelum 3, bestia 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:item.arcticFur", (int)0), (String)"pannus 2, gelum 1, bestia 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:item.iceBomb", (int)0), (String)"gelum 8, motus 8, fabrico 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:item.arcticHelm", (int)0), (String)"tutanem 3, fabrico 2, pannus 6, gelum 2, instrumentum 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:item.arcticPlate", (int)0), (String)"tutanem 7, fabrico 4, pannus 14, gelum 4, instrumentum 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:item.arcticLegs", (int)0), (String)"tutanem 5, fabrico 3, pannus 10, gelum 3, instrumentum 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:item.arcticBoots", (int)0), (String)"tutanem 2, fabrico 2, pannus 4, gelum 2, instrumentum 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:item.yetiHelm", (int)0), (String)"tutanem 4, fabrico 2, pannus 12, gelum 4, instrumentum 1, praecantatio 3");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:item.yetiPlate", (int)0), (String)"tutanem 8, fabrico 4, pannus 24, gelum 8, instrumentum 1, praecantatio 4");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:item.yetiLegs", (int)0), (String)"tutanem 6, fabrico 3, pannus 18, gelum 6, instrumentum 1, praecantatio 3");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:item.yetiBoots", (int)0), (String)"tutanem 3, fabrico 2, pannus 9, gelum 3, instrumentum 1, praecantatio 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:item.magicBeans", (int)0), (String)"herba 16, praecantatio 8, sensus 4");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:item.giantPick", (int)0), (String)"perfodio 32, terra 16, perditio 16, arbor 8");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:item.giantSword", (int)0), (String)"telum 32, terra 16, perditio 16, arbor 8");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:item.enderBow", (int)0), (String)"telum 3, volatus 1, pannus 2, bestia 2, alienis 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:item.iceBow", (int)0), (String)"telum 3, volatus 1, pannus 2, bestia 2, gelum 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:item.tripleBow", (int)0), (String)"telum 6, volatus 1, pannus 2, bestia 2, arbor 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:item.seekerBow", (int)0), (String)"telum 3, volatus 1, pannus 2, bestia 2, iter 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:item.iceSword", (int)0), (String)"telum 4, lucrum 2, praecantatio 2, gelum 6");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:item.glassSword", (int)0), (String)"telum 14, vitreus 20, lucrum 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:item.giantPick", (int)32767), (String)"perfodio 32, terra 16, perditio 16, arbor 8");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:item.giantSword", (int)32767), (String)"telum 32, terra 16, perditio 16, arbor 8");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:item.enderBow", (int)32767), (String)"telum 3, volatus 1, pannus 2, bestia 2, alienis 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:item.iceBow", (int)32767), (String)"telum 3, volatus 1, pannus 2, bestia 2, gelum 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:item.tripleBow", (int)32767), (String)"telum 6, volatus 1, pannus 2, bestia 2, arbor 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:item.seekerBow", (int)32767), (String)"telum 3, volatus 1, pannus 2, bestia 2, iter 2");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:item.iceSword", (int)32767), (String)"telum 4, lucrum 2, praecantatio 2, gelum 6");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:item.glassSword", (int)32767), (String)"telum 14, vitreus 20, lucrum 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:item.knightmetalRing", (int)0), (String)"instrumentum 3, ordo 3, fabrico 3");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:item.chainBlock", (int)0), (String)"telum 10, metallum 20, motus 4, lucrum 8, instrumentum 10");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"TwilightForest:item.chainBlock", (int)32767), (String)"telum 10, metallum 20, motus 4, lucrum 8, instrumentum 10");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"Forestry:grafter", (int)0), (String)"metallum 2, arbor 1, instrumentum 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"Forestry:scoop", (int)0), (String)"arbor 4, pannus 3, instrumentum 1");
        Aspects.set((IItemStack)ItemBracketHandler.getItem((String)"thaumicbases:tobaccoPowder", (int)0), (String)"herba 1, humanus 1, perditio 1");
    }
}

