package com.github.GTNH2Mega.fromScripts;
import java.util.HashMap;
import minetweaker.MineTweakerAPI;
import minetweaker.api.data.IData;
import minetweaker.api.item.IIngredient;
import minetweaker.api.item.IItemStack;
import minetweaker.expand.ExpandAnyArray;
import minetweaker.expand.ExpandAnyDict;
import minetweaker.expand.ExpandByte;
import minetweaker.expand.ExpandInt;
import minetweaker.expand.ExpandShort;
import minetweaker.expand.ExpandString;
import minetweaker.mc1710.brackets.ItemBracketHandler;
import minetweaker.mc1710.brackets.OreBracketHandler;
import modtweaker2.mods.thaumcraft.handlers.Arcane;
import modtweaker2.mods.thaumcraft.handlers.Infusion;
import modtweaker2.mods.thaumcraft.handlers.Research;
import modtweaker2.mods.thaumcraft.handlers.Warp;
import static com.github.GTNH2Mega.VoltageLevels.*;
public class ThaumicTinkerer02Kami
implements Runnable {
    public void run() {
        Infusion.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:kamiResource", (int)0));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:kamiResource", (int)1));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:kamiResource", (int)2));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:kamiResource", (int)3));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:kamiResource", (int)4));
        Infusion.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:catAmulet", (int)0));
        Infusion.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:ichorPouch", (int)0));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:ichorclothHelm", (int)0));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:ichorclothChest", (int)0));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:ichorclothLegs", (int)0));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:ichorclothBoots", (int)0));
        Infusion.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:kamiResource", (int)5));
        Infusion.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:focusShadowbeam", (int)0));
        Infusion.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:focusXPDrain", (int)0));
        Infusion.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:ichorclothHelmGem", (int)0));
        Infusion.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:ichorclothChestGem", (int)0));
        Infusion.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:ichorclothLegsGem", (int)0));
        Infusion.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:ichorclothBootsGem", (int)0));
        Infusion.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:warpGate", (int)0));
        Infusion.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:skyPearl", (int)0));
        Infusion.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:focusRecall", (int)0));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:ichorPick", (int)0));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:ichorShovel", (int)0));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:ichorAxe", (int)0));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:ichorSword", (int)0));
        Infusion.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:ichorPickGem", (int)0));
        Infusion.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:ichorShovelGem", (int)0));
        Infusion.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:ichorAxeGem", (int)0));
        Infusion.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:ichorSwordGem", (int)0));
        Infusion.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:protoclay", (int)0));
        Infusion.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:blockTalisman", (int)0));
        Infusion.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"ThaumicTinkerer:placementMirror", (int)0));
        Research.removeResearch((String)"DIMENSION_SHARDS");
        Research.addResearch((String)"DIMENSIONSHARDS", (String)"TT_CATEGORY", (String)"infernus 15, luxuria 15, superbia 15, gula 12, invidia 9, desidia 6, ira 3", (int)7, (int)8, (int)3, (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:kamiResource", (int)7));
        MineTweakerAPI.game.setLocalization("tc.research_name.DIMENSIONSHARDS", "Dimensional Shards");
        MineTweakerAPI.game.setLocalization("tc.research_text.DIMENSIONSHARDS", "[TT] Rarities of the Otherworld");
        Research.addPrereq((String)"DIMENSIONSHARDS", (String)"INFUSION", (boolean)false);
        Research.setConcealed((String)"DIMENSIONSHARDS", (boolean)false);
        Research.addPage((String)"DIMENSIONSHARDS", (String)"tt.research.page.DIMENSIONSHARDS");
        MineTweakerAPI.game.setLocalization("tt.research.page.DIMENSIONSHARDS", "Similarly to the overworld, the Nether and the End also have their specific shards, these are rarely held by either Zombie Pigmen living in the Nether or Endermen living in the End.<BR> You find a way to get this Shards with a Infusion recipe also.<BR><BR><IMG>ttinkerer:textures/items/netherShard.png:0:0:255:255:0.0625</IMG><IMG>ttinkerer:textures/items/enderShard.png:0:0:255:255:0.0625</IMG>");
        Infusion.addRecipe((String)"DIMENSIONSHARDS", (IItemStack)ItemBracketHandler.getItem((String)"minecraft:blaze_rod", (int)0), (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"ForbiddenMagic:NetherShard", (int)0), ItemBracketHandler.getItem((String)"ForbiddenMagic:NetherShard", (int)1), ItemBracketHandler.getItem((String)"ForbiddenMagic:NetherShard", (int)2), ItemBracketHandler.getItem((String)"ForbiddenMagic:NetherShard", (int)3), ItemBracketHandler.getItem((String)"ForbiddenMagic:NetherShard", (int)4), ItemBracketHandler.getItem((String)"ForbiddenMagic:NetherShard", (int)5), ItemBracketHandler.getItem((String)"ForbiddenMagic:NetherShard", (int)6), ItemBracketHandler.getItem((String)"ForbiddenMagic:GluttonyShard", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)1), ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)2), ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)3), ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)4), ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)5), ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)6)}, (String)"infernus 8, praecantatio 8, vitreus 8, vitium 8, luxuria 8, superbia 8, gula 8, invidia 8, desidia 8, ira 8, alienis 8", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:kamiResource", (int)6), (int)8);
        Infusion.addRecipe((String)"DIMENSIONSHARDS", (IItemStack)ItemBracketHandler.getItem((String)"minecraft:ender_eye", (int)0), (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"ForbiddenMagic:NetherShard", (int)0), ItemBracketHandler.getItem((String)"ForbiddenMagic:NetherShard", (int)1), ItemBracketHandler.getItem((String)"ForbiddenMagic:NetherShard", (int)2), ItemBracketHandler.getItem((String)"ForbiddenMagic:NetherShard", (int)3), ItemBracketHandler.getItem((String)"ForbiddenMagic:NetherShard", (int)4), ItemBracketHandler.getItem((String)"ForbiddenMagic:NetherShard", (int)5), ItemBracketHandler.getItem((String)"ForbiddenMagic:NetherShard", (int)6), ItemBracketHandler.getItem((String)"ForbiddenMagic:GluttonyShard", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)1), ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)2), ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)3), ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)4), ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)5), ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)6)}, (String)"infernus 8, praecantatio 8, vitreus 8, vitium 8, luxuria 8, superbia 8, gula 8, invidia 8, desidia 8, ira 8, alienis 8", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:kamiResource", (int)7), (int)8);
        Research.addInfusionPage((String)"DIMENSIONSHARDS", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:kamiResource", (int)6));
        Research.addInfusionPage((String)"DIMENSIONSHARDS", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:kamiResource", (int)7));
        Research.addPrereq((String)"ICHOR", (String)"DIMENSIONSHARDS", (boolean)false);
        Infusion.addRecipe((String)"ICHOR", (IItemStack)ItemBracketHandler.getItem((String)"minecraft:nether_star", (int)0), (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.02", (int)29500), ItemBracketHandler.getItem((String)"ThaumicTinkerer:kamiResource", (int)6), ItemBracketHandler.getItem((String)"minecraft:ender_eye", (int)0), ItemBracketHandler.getItem((String)"ThaumicTinkerer:kamiResource", (int)7)}, (String)"humanus 32, lux 32, spiritus 64, alienis 16, ordo 16", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:kamiResource", (int)0).amount(2), (int)10);
        Research.setAspects((String)"ICHOR", (String)"humanus 15, spiritus 15, ordo 15, praecantatio 15, vitium 12, lux 9, infernus 6, alienis 3");
        Research.setComplexity((String)"ICHOR", (int)4);
        Warp.addToResearch((String)"ICHOR", (int)5);
        Arcane.addShaped((String)"ICHOR_CLOTH", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:kamiResource", (int)1).amount(2), (String)"aer 125, aqua 125, ignis 125, terra 125, ordo 125, perditio 125", (IIngredient[][])new IIngredient[][]{{ItemBracketHandler.getItem((String)"ThaumicTinkerer:kamiResource", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)7), ItemBracketHandler.getItem((String)"ThaumicTinkerer:kamiResource", (int)0)}, {OreBracketHandler.getOre((String)"gemFlawlessDiamond"), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)7), OreBracketHandler.getOre((String)"gemFlawlessDiamond")}, {OreBracketHandler.getOre((String)"screwOsmiridium"), OreBracketHandler.getOre((String)"craftingToolScrewdriver"), OreBracketHandler.getOre((String)"screwOsmiridium")}});
        Research.setAspects((String)"ICHOR_CLOTH", (String)"pannus 15, fabrico 15, praecantatio 12, sensus 9, lux 6, alienis 3");
        Research.setComplexity((String)"ICHOR_CLOTH", (int)4);
        Warp.addToResearch((String)"ICHOR_CLOTH", (int)1);
        Research.clearPages((String)"ICHORIUM");
        Research.addPage((String)"ICHORIUM", (String)"ttresearch.page.ICHORIUM.0");
        Arcane.addShaped((String)"ICHORIUM", (IItemStack)ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)11978), (String)"aer 125, aqua 125, ignis 125, terra 125, ordo 125, perditio 125", (IIngredient[][])new IIngredient[][]{{OreBracketHandler.getOre((String)"ingotVoid"), ItemBracketHandler.getItem((String)"ThaumicTinkerer:kamiResource", (int)0), OreBracketHandler.getOre((String)"ingotVoid")}, {ItemBracketHandler.getItem((String)"ThaumicTinkerer:kamiResource", (int)0), OreBracketHandler.getOre((String)"ingotOsmiridium"), ItemBracketHandler.getItem((String)"ThaumicTinkerer:kamiResource", (int)0)}, {OreBracketHandler.getOre((String)"gemFlawlessDiamond"), ItemBracketHandler.getItem((String)"ThaumicTinkerer:kamiResource", (int)0), OreBracketHandler.getOre((String)"gemFlawlessDiamond")}});
        Research.addArcanePage((String)"ICHORIUM", (IItemStack)ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)11978));
        Research.setAspects((String)"ICHORIUM", (String)"metallum 15, fabrico 15, instrumentum 12, praecantatio 9, lux 6, alienis 3");
        Research.setComplexity((String)"ICHORIUM", (int)4);
        Warp.addToResearch((String)"ICHORIUM", (int)2);
        MineTweakerAPI.furnace.addRecipe(ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)9978).amount(9), (IIngredient)ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)11978), 0.0);
        Research.orphanResearch((String)"CAP_ICHOR");
        Research.removeResearch((String)"CAP_ICHOR");
        Research.addResearch((String)"CAP_ICHOR", (String)"TT_CATEGORY", (String)"cognitio 15, praecantatio 12, permutatio 9, instrumentum 6, terra 3", (int)11, (int)11, (int)4, (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:kamiResource", (int)4));
        MineTweakerAPI.game.setLocalization("tc.research_name.CAP_ICHOR", "Ichorium Wand Caps");
        MineTweakerAPI.game.setLocalization("tc.research_text.CAP_ICHOR", "[TT] Somewhat like a Steam Sale");
        Research.addPrereq((String)"CAP_ICHOR", (String)"ICHORIUM", (boolean)false);
        Research.setConcealed((String)"CAP_ICHOR", (boolean)true);
        Research.addPage((String)"CAP_ICHOR", (String)"ttresearch.page.CAP_ICHOR.0");
        Arcane.addShaped((String)"CAP_ICHOR", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:kamiResource", (int)4).amount(2), (String)"aer 150, aqua 150, ignis 150, terra 150, ordo 150, perditio 150", (IIngredient[][])new IIngredient[][]{{ItemBracketHandler.getItem((String)"ThaumicTinkerer:kamiResource", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:WandCap", (int)7), ItemBracketHandler.getItem((String)"ThaumicTinkerer:kamiResource", (int)0)}, {OreBracketHandler.getOre((String)"ringVoid"), OreBracketHandler.getOre((String)"ingotIchorium"), OreBracketHandler.getOre((String)"ringVoid")}, {ItemBracketHandler.getItem((String)"ThaumicTinkerer:kamiResource", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:WandCap", (int)7), ItemBracketHandler.getItem((String)"ThaumicTinkerer:kamiResource", (int)0)}});
        Research.addArcanePage((String)"CAP_ICHOR", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:kamiResource", (int)4));
        Research.setAspects((String)"CAP_ICHOR", (String)"metallum 15, instrumentum 15, tenebrae 12, praecantatio 9, lux 6, alienis 3");
        Research.setComplexity((String)"CAP_ICHOR", (int)4);
        Warp.addToResearch((String)"CAP_ICHOR", (int)3);
        Infusion.addRecipe((String)"CAT_AMULET", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:kamiResource", (int)0), (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"appliedenergistics2:item.ItemMultiMaterial", (int)10), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)28086), ItemBracketHandler.getItem((String)"ThaumicTinkerer:kamiResource", (int)1), ItemBracketHandler.getItem((String)"minecraft:fish", (int)0), ItemBracketHandler.getItem((String)"minecraft:dye", (int)3), ItemBracketHandler.getItem((String)"minecraft:leaves", (int)3), ItemBracketHandler.getItem((String)"ThaumicTinkerer:kamiResource", (int)1), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)28086)}, (String)"cognitio 16, ordo 32, tenebrae 16, mortuus 16", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:catAmulet", (int)0), (int)8);
        Research.setAspects((String)"CAT_AMULET", (String)"cognitio 15, ordo 15, tenebrae 12, mortuus 9, motus 6, alienis 3");
        Research.setComplexity((String)"CAT_AMULET", (int)4);
        Infusion.addRecipe((String)"ICHOR_POUCH", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:FocusPouch", (int)0), (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"Thaumcraft:blockJar", (int)3), ItemBracketHandler.getItem((String)"ThaumicTinkerer:kamiResource", (int)1), ItemBracketHandler.getItem((String)"ThaumicTinkerer:kamiResource", (int)1), ItemBracketHandler.getItem((String)"Thaumcraft:FocusPortableHole", (int)0), ItemBracketHandler.getItem((String)"ThaumicTinkerer:kamiResource", (int)1), ItemBracketHandler.getItem((String)"Thaumcraft:TrunkSpawner", (int)0), ItemBracketHandler.getItem((String)"ThaumicTinkerer:kamiResource", (int)1), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.02", (int)30500)}, (String)"vacuos 64, humanus 48, pannus 48, alienis 48, aer 64", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:ichorPouch", (int)0), (int)10);
        Research.setAspects((String)"ICHOR_POUCH", (String)"vacuos 15, pannus 15, alienis 12, humanus 9, motus 6, aer 3");
        Research.setComplexity((String)"ICHOR_POUCH", (int)4);
        Warp.addToResearch((String)"ICHOR_POUCH", (int)3);
        Arcane.addShaped((String)"ICHORCLOTH_ARMOR", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:ichorclothHelm", (int)0), (String)"aqua 75, perditio 50, ordo 25", (IIngredient[][])new IIngredient[][]{{ItemBracketHandler.getItem((String)"ThaumicTinkerer:kamiResource", (int)1), ItemBracketHandler.getItem((String)"ThaumicTinkerer:kamiResource", (int)1), ItemBracketHandler.getItem((String)"ThaumicTinkerer:kamiResource", (int)1)}, {ItemBracketHandler.getItem((String)"ThaumicTinkerer:kamiResource", (int)1), OreBracketHandler.getOre((String)"plateOsmiridium"), ItemBracketHandler.getItem((String)"ThaumicTinkerer:kamiResource", (int)1)}, {null, OreBracketHandler.getOre((String)"screwOsmiridium"), null}});
        Arcane.addShaped((String)"ICHORCLOTH_ARMOR", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:ichorclothChest", (int)0), (String)"aer 75, perditio 50, ordo 25", (IIngredient[][])new IIngredient[][]{{ItemBracketHandler.getItem((String)"ThaumicTinkerer:kamiResource", (int)1), OreBracketHandler.getOre((String)"screwOsmiridium"), ItemBracketHandler.getItem((String)"ThaumicTinkerer:kamiResource", (int)1)}, {ItemBracketHandler.getItem((String)"ThaumicTinkerer:kamiResource", (int)1), ItemBracketHandler.getItem((String)"ThaumicTinkerer:kamiResource", (int)1), ItemBracketHandler.getItem((String)"ThaumicTinkerer:kamiResource", (int)1)}, {ItemBracketHandler.getItem((String)"ThaumicTinkerer:kamiResource", (int)1), ItemBracketHandler.getItem((String)"ThaumicTinkerer:kamiResource", (int)1), ItemBracketHandler.getItem((String)"ThaumicTinkerer:kamiResource", (int)1)}});
        Arcane.addShaped((String)"ICHORCLOTH_ARMOR", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:ichorclothLegs", (int)0), (String)"ignis 75, perditio 50, ordo 25", (IIngredient[][])new IIngredient[][]{{ItemBracketHandler.getItem((String)"ThaumicTinkerer:kamiResource", (int)1), ItemBracketHandler.getItem((String)"ThaumicTinkerer:kamiResource", (int)1), ItemBracketHandler.getItem((String)"ThaumicTinkerer:kamiResource", (int)1)}, {ItemBracketHandler.getItem((String)"ThaumicTinkerer:kamiResource", (int)1), OreBracketHandler.getOre((String)"plateOsmiridium"), ItemBracketHandler.getItem((String)"ThaumicTinkerer:kamiResource", (int)1)}, {ItemBracketHandler.getItem((String)"ThaumicTinkerer:kamiResource", (int)1), OreBracketHandler.getOre((String)"screwOsmiridium"), ItemBracketHandler.getItem((String)"ThaumicTinkerer:kamiResource", (int)1)}});
        Arcane.addShaped((String)"ICHORCLOTH_ARMOR", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:ichorclothBoots", (int)0), (String)"terra 75, perditio 50, ordo 25", (IIngredient[][])new IIngredient[][]{{null, null, null}, {ItemBracketHandler.getItem((String)"ThaumicTinkerer:kamiResource", (int)1), OreBracketHandler.getOre((String)"plateOsmiridium"), ItemBracketHandler.getItem((String)"ThaumicTinkerer:kamiResource", (int)1)}, {ItemBracketHandler.getItem((String)"ThaumicTinkerer:kamiResource", (int)1), OreBracketHandler.getOre((String)"screwOsmiridium"), ItemBracketHandler.getItem((String)"ThaumicTinkerer:kamiResource", (int)1)}});
        Research.setAspects((String)"ICHORCLOTH_ARMOR", (String)"tutamen 15, pannus 15, lux 12, perfodio 9, motus 6, alienis 3");
        Research.setComplexity((String)"ICHORCLOTH_ARMOR", (int)4);
        Warp.addToResearch((String)"ICHORCLOTH_ARMOR", (int)3);
        Infusion.addRecipe((String)"ROD_ICHORCLOTH", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:WandRod", (int)2), (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"ThaumicTinkerer:kamiResource", (int)0), ItemBracketHandler.getItem((String)"ThaumicTinkerer:kamiResource", (int)1), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)14), ItemBracketHandler.getItem((String)"minecraft:ghast_tear", (int)0), ItemBracketHandler.getItem((String)"minecraft:ghast_tear", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)14), ItemBracketHandler.getItem((String)"ThaumicTinkerer:kamiResource", (int)1), ItemBracketHandler.getItem((String)"ThaumicTinkerer:kamiResource", (int)0)}, (String)"praecantatio 150, lux 100, instrumentum 100, arbor 75, alienis 50", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:kamiResource", (int)5), (int)10);
        Research.setAspects((String)"ROD_ICHORCLOTH", (String)"instrumentum 15, pannus 15, lux 12, praecantatio 9, arbor 6, alienis 3");
        Research.setComplexity((String)"ROD_ICHORCLOTH", (int)4);
        Warp.addToResearch((String)"ROD_ICHORCLOTH", (int)3);
        IItemStack iItemStack = ItemBracketHandler.getItem((String)"Thaumcraft:FocusShock", (int)0);
        IItemStack[] arriItemStack = new IItemStack[7];
        arriItemStack[0] = ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)11978);
        arriItemStack[1] = ItemBracketHandler.getItem((String)"ThaumicTinkerer:focusDeflect", (int)0);
        arriItemStack[2] = ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.02", (int)29501);
        IItemStack iItemStack2 = ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.02", (int)25543);
        HashMap<String, IData> hashMap = new HashMap<String, IData>();
        IData[] arriData = new IData[1];
        HashMap<String, IData> hashMap2 = new HashMap<String, IData>();
        hashMap2.put("lvl", ExpandShort.asNBT((short)3));
        hashMap2.put("id", ExpandShort.asNBT((short)21));
        arriData[0] = ExpandAnyDict.asData(hashMap2);
        hashMap.put("ench", ExpandAnyArray.asData((IData[])arriData));
        hashMap.put("GT.HasBeenUpdated", ExpandByte.asData((byte)1));
        arriItemStack[3] = iItemStack2.withTag(ExpandAnyDict.asData(hashMap));
        IItemStack iItemStack3 = ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.02", (int)25543);
        HashMap<String, IData> hashMap3 = new HashMap<String, IData>();
        IData[] arriData2 = new IData[1];
        HashMap<String, IData> hashMap4 = new HashMap<String, IData>();
        hashMap4.put("lvl", ExpandShort.asNBT((short)3));
        hashMap4.put("id", ExpandShort.asNBT((short)21));
        arriData2[0] = ExpandAnyDict.asData(hashMap4);
        hashMap3.put("ench", ExpandAnyArray.asData((IData[])arriData2));
        hashMap3.put("GT.HasBeenUpdated", ExpandByte.asData((byte)1));
        arriItemStack[4] = iItemStack3.withTag(ExpandAnyDict.asData(hashMap3));
        arriItemStack[5] = ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.02", (int)29500);
        arriItemStack[6] = ItemBracketHandler.getItem((String)"Thaumcraft:FocusExcavation", (int)0);
        Infusion.addRecipe((String)"FOCUS_SHADOWBEAM", (IItemStack)iItemStack, (IItemStack[])arriItemStack, (String)"alienis 64, praecantatio 64, telum 64, tenebrae 64, tempestas 32", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:focusShadowbeam", (int)0), (int)12);
        Research.setAspects((String)"FOCUS_SHADOWBEAM", (String)"tenebrae 15, praecantatio 15, alienis 12, telum 9, tempestas 6, motus 3");
        Research.setComplexity((String)"FOCUS_SHADOWBEAM", (int)4);
        Warp.addToResearch((String)"FOCUS_SHADOWBEAM", (int)4);
        Infusion.addRecipe((String)"FOCUS_XP_DRAIN", (IItemStack)ItemBracketHandler.getItem((String)"minecraft:experience_bottle", (int)0), (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)11978), ItemBracketHandler.getItem((String)"ThaumicTinkerer:enchanter", (int)0), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.02", (int)29500), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)24532), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.02", (int)29501), ItemBracketHandler.getItem((String)"ThaumicTinkerer:xpTalisman", (int)0)}, (String)"auram 64, cognitio 64, praecantatio 64, vitium 32", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:focusXPDrain", (int)0), (int)12);
        Research.setAspects((String)"FOCUS_XP_DRAIN", (String)"cognitio 15, praecantatio 15, auram 12, humanus 9, lucrum 6, alienis 3");
        Research.setComplexity((String)"FOCUS_XP_DRAIN", (int)4);
        Warp.addToResearch((String)"FOCUS_XP_DRAIN", (int)4);
        Infusion.addRecipe((String)"ICHORCLOTH_HELM_GEM", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:ichorclothHelm", (int)0), (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)11978), ItemBracketHandler.getItem((String)"Thaumcraft:ItemHelmetThaumium", (int)0), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)24533), ItemBracketHandler.getItem((String)"Thaumcraft:ItemThaumonomicon", (int)0), ItemBracketHandler.getItem((String)"minecraft:potion", (int)8262), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.02", (int)30500), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)11978), ItemBracketHandler.getItem((String)"minecraft:ghast_tear", (int)0), ItemBracketHandler.getItem((String)"minecraft:fish", (int)32767), ItemBracketHandler.getItem((String)"minecraft:cake", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:FocusPrimal", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:ItemGoggles", (int)0)}, (String)"aqua 64, auram 64, cognitio 64, corpus 64, fames 64, lux 64, tutamen 64", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:ichorclothHelmGem", (int)0), (int)16);
        Research.setAspects((String)"ICHORCLOTH_HELM_GEM", (String)"aqua 24, sano 21, fames 18, auram 15, cognitio 12, corpus 9, lux 6, tutamen 3");
        Research.setComplexity((String)"ICHORCLOTH_HELM_GEM", (int)4);
        Warp.addToResearch((String)"ICHORCLOTH_HELM_GEM", (int)4);
        IItemStack iItemStack4 = ItemBracketHandler.getItem((String)"ThaumicTinkerer:ichorclothChest", (int)0);
        IItemStack[] arriItemStack2 = new IItemStack[12];
        arriItemStack2[0] = ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)11978);
        arriItemStack2[1] = ItemBracketHandler.getItem((String)"Thaumcraft:ItemChestplateThaumium", (int)0);
        arriItemStack2[2] = ItemBracketHandler.getItem((String)"ThaumicTinkerer:focusFlight", (int)0);
        arriItemStack2[3] = ItemBracketHandler.getItem((String)"Thaumcraft:ItemThaumonomicon", (int)0);
        IItemStack iItemStack5 = ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.02", (int)25330);
        HashMap<String, IData> hashMap5 = new HashMap<String, IData>();
        IData[] arriData3 = new IData[1];
        HashMap<String, IData> hashMap6 = new HashMap<String, IData>();
        hashMap6.put("lvl", ExpandShort.asNBT((short)2));
        hashMap6.put("id", ExpandShort.asNBT((short)21));
        arriData3[0] = ExpandAnyDict.asData(hashMap6);
        hashMap5.put("ench", ExpandAnyArray.asData((IData[])arriData3));
        hashMap5.put("GT.HasBeenUpdated", ExpandByte.asData((byte)1));
        arriItemStack2[4] = iItemStack5.withTag(ExpandAnyDict.asData(hashMap5));
        arriItemStack2[5] = ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.02", (int)30500);
        arriItemStack2[6] = ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)11978);
        arriItemStack2[7] = ItemBracketHandler.getItem((String)"minecraft:ghast_tear", (int)0);
        IItemStack iItemStack6 = ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.02", (int)25330);
        HashMap<String, IData> hashMap7 = new HashMap<String, IData>();
        IData[] arriData4 = new IData[1];
        HashMap<String, IData> hashMap8 = new HashMap<String, IData>();
        hashMap8.put("lvl", ExpandShort.asNBT((short)2));
        hashMap8.put("id", ExpandShort.asNBT((short)21));
        arriData4[0] = ExpandAnyDict.asData(hashMap8);
        hashMap7.put("ench", ExpandAnyArray.asData((IData[])arriData4));
        hashMap7.put("GT.HasBeenUpdated", ExpandByte.asData((byte)1));
        arriItemStack2[8] = iItemStack6.withTag(ExpandAnyDict.asData(hashMap7));
        arriItemStack2[9] = ItemBracketHandler.getItem((String)"EMT:EMTItems", (int)7);
        arriItemStack2[10] = ItemBracketHandler.getItem((String)"ThaumicTinkerer:focusDeflect", (int)0);
        arriItemStack2[11] = ItemBracketHandler.getItem((String)"Thaumcraft:HoverHarness", (int)0);
        Infusion.addRecipe((String)"ICHORCLOTH_CHEST_GEM", (IItemStack)iItemStack4, (IItemStack[])arriItemStack2, (String)"aer 64, alienis 64, lux 64, ordo 64, sensus 64, tutamen 64, volatus 64", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:ichorclothChestGem", (int)0), (int)16);
        Research.setAspects((String)"ICHORCLOTH_CHEST_GEM", (String)"aer 24, motus 21, volatus 18, alienis 15, lux 12, sensus 9, ordo 6, tutamen 3");
        Research.setComplexity((String)"ICHORCLOTH_CHEST_GEM", (int)4);
        Warp.addToResearch((String)"ICHORCLOTH_CHEST_GEM", (int)4);
        Infusion.addRecipe((String)"ICHORCLOTH_LEGS_GEM", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:ichorclothLegs", (int)0), (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)11978), ItemBracketHandler.getItem((String)"Thaumcraft:ItemLeggingsThaumium", (int)0), ItemBracketHandler.getItem((String)"ThaumicTinkerer:focusSmelt", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:ItemThaumonomicon", (int)0), ItemBracketHandler.getItem((String)"minecraft:potion", (int)8259), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.02", (int)30500), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)11978), ItemBracketHandler.getItem((String)"ThaumicTinkerer:brightNitor", (int)0), ItemBracketHandler.getItem((String)"minecraft:fire_charge", (int)0), ItemBracketHandler.getItem((String)"minecraft:blaze_rod", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:FocusPrimal", (int)0), ItemBracketHandler.getItem((String)"minecraft:lava_bucket", (int)0)}, (String)"alienis 64, ignis 64, lucrum 64, lux 64, potentia 64, sano 64, tutamen 64", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:ichorclothLegsGem", (int)0), (int)16);
        Research.setAspects((String)"ICHORCLOTH_LEGS_GEM", (String)"ignis 24, sano 21, lucrum 18, potentia 15, alienis 12, aer 9, lux 6, tutamen 3");
        Research.setComplexity((String)"ICHORCLOTH_LEGS_GEM", (int)4);
        Warp.addToResearch((String)"ICHORCLOTH_LEGS_GEM", (int)4);
        IItemStack iItemStack7 = ItemBracketHandler.getItem((String)"ThaumicTinkerer:ichorclothBoots", (int)0);
        IItemStack[] arriItemStack3 = new IItemStack[12];
        arriItemStack3[0] = ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)11978);
        arriItemStack3[1] = ItemBracketHandler.getItem((String)"Thaumcraft:ItemBootsThaumium", (int)0);
        IItemStack iItemStack8 = ItemBracketHandler.getItem((String)"ThaumicTinkerer:infusedSeeds", (int)0);
        HashMap<String, IData> hashMap9 = new HashMap<String, IData>();
        HashMap<String, IData> hashMap10 = new HashMap<String, IData>();
        IData[] arriData5 = new IData[1];
        HashMap<String, IData> hashMap11 = new HashMap<String, IData>();
        hashMap11.put("amount", ExpandInt.toData((int)1));
        hashMap11.put("key", ExpandString.asData((String)"terra"));
        arriData5[0] = ExpandAnyDict.asData(hashMap11);
        hashMap10.put("Aspects", ExpandAnyArray.asData((IData[])arriData5));
        hashMap9.put("mainAspect", ExpandAnyDict.asData(hashMap10));
        arriItemStack3[2] = iItemStack8.withTag(ExpandAnyDict.asData(hashMap9));
        arriItemStack3[3] = ItemBracketHandler.getItem((String)"Thaumcraft:ItemThaumonomicon", (int)0);
        arriItemStack3[4] = ItemBracketHandler.getItem((String)"harvestcraft:wovencottonItem", (int)0);
        arriItemStack3[5] = ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.02", (int)30500);
        arriItemStack3[6] = ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)11978);
        arriItemStack3[7] = ItemBracketHandler.getItem((String)"Thaumcraft:blockMetalDevice", (int)8);
        arriItemStack3[8] = ItemBracketHandler.getItem((String)"Thaumcraft:blockWoodenDevice", (int)5);
        arriItemStack3[9] = ItemBracketHandler.getItem((String)"minecraft:lead", (int)0);
        arriItemStack3[10] = ItemBracketHandler.getItem((String)"Thaumcraft:FocusPrimal", (int)0);
        arriItemStack3[11] = ItemBracketHandler.getItem((String)"minecraft:grass", (int)0);
        Infusion.addRecipe((String)"ICHORCLOTH_BOOTS_GEM", (IItemStack)iItemStack7, (IItemStack[])arriItemStack3, (String)"herba 64, iter 64, lux 64, motus 64, perfodio 64, terra 64, tutamen 64", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:ichorclothBootsGem", (int)0), (int)16);
        Research.setAspects((String)"ICHORCLOTH_BOOTS_GEM", (String)"terra 24, iter 21, perfodio 18, herba 15, lux 12, motus 9, cognitio 6, tutamen 3");
        Research.setComplexity((String)"ICHORCLOTH_BOOTS_GEM", (int)4);
        Warp.addToResearch((String)"ICHORCLOTH_BOOTS_GEM", (int)4);
        Infusion.addRecipe((String)"WARP_GATE", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:blockCosmeticSolid", (int)2), (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"ThaumicTinkerer:dislocator", (int)0), ItemBracketHandler.getItem((String)"ThaumicTinkerer:kamiResource", (int)7), ItemBracketHandler.getItem((String)"EMT:EMTItems", (int)7), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)11978), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.02", (int)30500), ItemBracketHandler.getItem((String)"ThaumicTinkerer:kamiResource", (int)6)}, (String)"alienis 64, iter 72, volatus 64, terra 32, aer 32", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:warpGate", (int)0), (int)10);
        Infusion.addRecipe((String)"WARP_GATE", (IItemStack)ItemBracketHandler.getItem((String)"minecraft:ender_pearl", (int)0), (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"IC2:itemDensePlates", (int)8), ItemBracketHandler.getItem((String)"ThaumicTinkerer:kamiResource", (int)7), ItemBracketHandler.getItem((String)"EMT:EMTItems", (int)7), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)11978), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.02", (int)30500), ItemBracketHandler.getItem((String)"ThaumicTinkerer:kamiResource", (int)6)}, (String)"aer 24, alienis 32, volatus 32, iter 32, vitreus 24", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:skyPearl", (int)0), (int)10);
        Research.setAspects((String)"WARP_GATE", (String)"iter 18, volatus 15, alienis 12, machina 9, vitreus 6, aer 3");
        Research.setComplexity((String)"WARP_GATE", (int)4);
        Warp.addToResearch((String)"WARP_GATE", (int)4);
        Infusion.addRecipe((String)"FOCUS_RECALL", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:focusEnderChest", (int)0), (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)11978), ItemBracketHandler.getItem((String)"ThaumicTinkerer:skyPearl", (int)0), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.02", (int)30500), ItemBracketHandler.getItem((String)"ThaumicTinkerer:skyPearl", (int)0)}, (String)"alienis 64, iter 128, praecantatio 96, volatus 48, aer 32", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:focusRecall", (int)0), (int)14);
        Research.setAspects((String)"FOCUS_RECALL", (String)"iter 18, alienis 15, volatus 12, praecantatio 9, aer 6, cognitio 3");
        Research.setComplexity((String)"FOCUS_RECALL", (int)4);
        Warp.addToResearch((String)"FOCUS_RECALL", (int)4);
        Arcane.addShaped((String)"ICHOR_TOOLS", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:ichorPick", (int)0), (String)"ignis 75, perditio 50, ordo 25", (IIngredient[][])new IIngredient[][]{{OreBracketHandler.getOre((String)"ingotIchorium"), OreBracketHandler.getOre((String)"ingotIchorium"), OreBracketHandler.getOre((String)"ingotIchorium")}, {OreBracketHandler.getOre((String)"plateOsmiridium"), ItemBracketHandler.getItem((String)"Thaumcraft:WandRod", (int)2), OreBracketHandler.getOre((String)"plateOsmiridium")}, {OreBracketHandler.getOre((String)"screwOsmiridium"), ItemBracketHandler.getItem((String)"Thaumcraft:WandRod", (int)2), OreBracketHandler.getOre((String)"screwOsmiridium")}});
        Arcane.addShaped((String)"ICHOR_TOOLS", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:ichorShovel", (int)0), (String)"terra 75, perditio 50, ordo 25", (IIngredient[][])new IIngredient[][]{{null, OreBracketHandler.getOre((String)"ingotIchorium"), null}, {OreBracketHandler.getOre((String)"plateOsmiridium"), ItemBracketHandler.getItem((String)"Thaumcraft:WandRod", (int)2), OreBracketHandler.getOre((String)"plateOsmiridium")}, {OreBracketHandler.getOre((String)"screwOsmiridium"), ItemBracketHandler.getItem((String)"Thaumcraft:WandRod", (int)2), OreBracketHandler.getOre((String)"screwOsmiridium")}});
        Arcane.addShaped((String)"ICHOR_TOOLS", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:ichorAxe", (int)0), (String)"aqua 75, perditio 50, ordo 25", (IIngredient[][])new IIngredient[][]{{OreBracketHandler.getOre((String)"ingotIchorium"), OreBracketHandler.getOre((String)"ingotIchorium"), OreBracketHandler.getOre((String)"plateOsmiridium")}, {OreBracketHandler.getOre((String)"ingotIchorium"), ItemBracketHandler.getItem((String)"Thaumcraft:WandRod", (int)2), OreBracketHandler.getOre((String)"screwOsmiridium")}, {OreBracketHandler.getOre((String)"plateOsmiridium"), ItemBracketHandler.getItem((String)"Thaumcraft:WandRod", (int)2), OreBracketHandler.getOre((String)"screwOsmiridium")}});
        Arcane.addShaped((String)"ICHOR_TOOLS", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:ichorSword", (int)0), (String)"aer 75, perditio 50, ordo 25", (IIngredient[][])new IIngredient[][]{{null, OreBracketHandler.getOre((String)"ingotIchorium"), null}, {OreBracketHandler.getOre((String)"plateOsmiridium"), OreBracketHandler.getOre((String)"ingotIchorium"), OreBracketHandler.getOre((String)"plateOsmiridium")}, {OreBracketHandler.getOre((String)"screwOsmiridium"), ItemBracketHandler.getItem((String)"Thaumcraft:WandRod", (int)2), OreBracketHandler.getOre((String)"screwOsmiridium")}});
        Research.setAspects((String)"ICHOR_TOOLS", (String)"instrumentum 18, telum 15, metallum 12, fabrico 9, praecantatio 6, alienis 3");
        Research.setComplexity((String)"ICHOR_TOOLS", (int)4);
        Warp.addToResearch((String)"ICHOR_TOOLS", (int)3);
        Infusion.addRecipe((String)"ICHOR_PICK_GEM", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:ichorPick", (int)0), (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)11978), ItemBracketHandler.getItem((String)"Thaumcraft:ItemPickaxeElemental", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:FocusFire", (int)0), ItemBracketHandler.getItem((String)"StevesCarts:CartModule", (int)9), ItemBracketHandler.getItem((String)"ThaumicTinkerer:kamiResource", (int)1), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.02", (int)30501), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)11978), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.02", (int)30500), ItemBracketHandler.getItem((String)"IC2:blockITNT", (int)0), ItemBracketHandler.getItem((String)"StevesCarts:CartModule", (int)9), ItemBracketHandler.getItem((String)"Thaumcraft:FocusFire", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:ItemPickaxeElemental", (int)0)}, (String)"ignis 64, lucrum 64, metallum 64, meto 64, messis 64, perfodio 64, terra 64, sensus 64", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:ichorPickGem", (int)0), (int)18);
        Research.setAspects((String)"ICHOR_PICK_GEM", (String)"ignis 24, lucrum 21, metallum 18, meto 15, messis 12, perfodio 9, terra 6, sensus 3");
        Research.setComplexity((String)"ICHOR_PICK_GEM", (int)4);
        Warp.addToResearch((String)"ICHOR_PICK_GEM", (int)3);
        Infusion.addRecipe((String)"ICHOR_SHOVEL_GEM", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:ichorShovel", (int)0), (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)11978), ItemBracketHandler.getItem((String)"Thaumcraft:ItemShovelElemental", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:FocusExcavation", (int)0), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)32642), ItemBracketHandler.getItem((String)"ThaumicTinkerer:kamiResource", (int)1), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.02", (int)30501), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)11978), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.02", (int)30500), ItemBracketHandler.getItem((String)"IC2:blockITNT", (int)0), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)32642), ItemBracketHandler.getItem((String)"Thaumcraft:FocusExcavation", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:ItemShovelElemental", (int)0)}, (String)"instrumentum 64, meto 64, perfodio 64, sensus 64, terra 64, vinculum 64, ordo 64", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:ichorShovelGem", (int)0), (int)18);
        Research.setAspects((String)"ICHOR_SHOVEL_GEM", (String)"instrumentum 21, meto 18, perfodio 15, sensus 12, terra 9, vinculum 6, ordo 3");
        Research.setComplexity((String)"ICHOR_SHOVEL_GEM", (int)4);
        Warp.addToResearch((String)"ICHOR_SHOVEL_GEM", (int)3);
        Infusion.addRecipe((String)"ICHOR_AXE_GEM", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:ichorAxe", (int)0), (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)11978), ItemBracketHandler.getItem((String)"Thaumcraft:ItemAxeElemental", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:FocusExcavation", (int)0), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)32721), ItemBracketHandler.getItem((String)"ThaumicTinkerer:kamiResource", (int)1), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.02", (int)30501), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)11978), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.02", (int)30500), ItemBracketHandler.getItem((String)"IC2:blockITNT", (int)0), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)32721), ItemBracketHandler.getItem((String)"Thaumcraft:FocusExcavation", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:ItemAxeElemental", (int)0)}, (String)"aqua 64, arbor 64, instrumentum 64, messis 64, meto 64, perfodio 64, sensus 64", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:ichorAxeGem", (int)0), (int)18);
        Research.setAspects((String)"ICHOR_AXE_GEM", (String)"aqua 21, arbor 18, instrumentum 15, messis 12, meto 9, perfodio 6, sensus 3");
        Research.setComplexity((String)"ICHOR_AXE_GEM", (int)4);
        Warp.addToResearch((String)"ICHOR_AXE_GEM", (int)3);
        Infusion.addRecipe((String)"ICHOR_SWORD_GEM", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:ichorSword", (int)0), (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)11978), ItemBracketHandler.getItem((String)"Thaumcraft:ItemSwordElemental", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:FocusFrost", (int)0), ItemBracketHandler.getItem((String)"ExtraUtilities:spike_base_diamond", (int)0), ItemBracketHandler.getItem((String)"ThaumicTinkerer:kamiResource", (int)1), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.02", (int)30501), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)11978), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.02", (int)30500), ItemBracketHandler.getItem((String)"IC2:blockITNT", (int)0), ItemBracketHandler.getItem((String)"ExtraUtilities:spike_base_diamond", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:FocusFrost", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:ItemSwordElemental", (int)0)}, (String)"aer 64, fames 64, ordo 64, potentia 64, spiritus 64, telum 64, vitreus 64", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:ichorSwordGem", (int)0), (int)18);
        Research.setAspects((String)"ICHOR_SWORD_GEM", (String)"aer 21, fames 18, ordo 15, potentia 12, spiritus 9, telum 6, vitreus 3");
        Research.setComplexity((String)"ICHOR_SWORD_GEM", (int)4);
        Warp.addToResearch((String)"ICHOR_SWORD_GEM", (int)3);
        Infusion.addRecipe((String)"PROTOCLAY", (IItemStack)ItemBracketHandler.getItem((String)"minecraft:clay_ball", (int)0), (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"minecraft:stone", (int)0), ItemBracketHandler.getItem((String)"minecraft:dirt", (int)0), ItemBracketHandler.getItem((String)"ThaumicTinkerer:kamiResource", (int)7), ItemBracketHandler.getItem((String)"minecraft:sand", (int)32767), ItemBracketHandler.getItem((String)"minecraft:cobblestone", (int)0), ItemBracketHandler.getItem((String)"minecraft:log", (int)32767), ItemBracketHandler.getItem((String)"ThaumicTinkerer:kamiResource", (int)6), ItemBracketHandler.getItem((String)"minecraft:grass", (int)0)}, (String)"instrumentum 32, perfodio 32, terra 16, aer 16", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:protoclay", (int)0), (int)5);
        Research.setAspects((String)"PROTOCLAY", (String)"instrumentum 18, humanus 15, machina 12, perfodio 9, terra 6, aer 3");
        Research.setComplexity((String)"PROTOCLAY", (int)4);
        Warp.addToResearch((String)"PROTOCLAY", (int)1);
        Infusion.addRecipe((String)"BLOCK_TALISMAN", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:FocusPortableHole", (int)0), (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)11978), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.02", (int)30500), ItemBracketHandler.getItem((String)"EnderStorage:enderChest", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)11), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)11978), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)11), ItemBracketHandler.getItem((String)"Thaumcraft:blockJar", (int)3), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.02", (int)30501)}, (String)"alienis 64, praecantatio 64, vacuos 72, tenebrae 48, spiritus 32", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:blockTalisman", (int)0), (int)10);
        Research.setAspects((String)"BLOCK_TALISMAN", (String)"vacuos 15, tenebrae 12, alienis 9, praecantatio 6, spiritus 3");
        Research.setComplexity((String)"BLOCK_TALISMAN", (int)4);
        Warp.addToResearch((String)"BLOCK_TALISMAN", (int)6);
        Infusion.addRecipe((String)"PLACEMENT_MIRROR", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:blockTalisman", (int)0), (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)11978), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.02", (int)30500), ItemBracketHandler.getItem((String)"minecraft:dropper", (int)0), ItemBracketHandler.getItem((String)"minecraft:blaze_rod", (int)0), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)11978), ItemBracketHandler.getItem((String)"minecraft:blaze_rod", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:blockMirror", (int)0), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.02", (int)30501)}, (String)"cognitio 64, fabrico 72, praecantatio 64, vitreus 48, alienis 32", (IItemStack)ItemBracketHandler.getItem((String)"ThaumicTinkerer:placementMirror", (int)0), (int)16);
        Research.setAspects((String)"PLACEMENT_MIRROR", (String)"cognitio 15, fabrico 12, praecantatio 9, vitreus 6, alienis 3");
        Research.setComplexity((String)"PLACEMENT_MIRROR", (int)4);
        Warp.addToResearch((String)"PLACEMENT_MIRROR", (int)8);
        MineTweakerAPI.furnace.addRecipe(ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)11978).amount(2), (IIngredient)ItemBracketHandler.getItem((String)"gregtech:gt.blockmetal8", (int)13), 0.0);
        Research.refreshResearchRecipe((String)"DIMENSION_SHARDS");
        Research.refreshResearchRecipe((String)"ICHOR");
        Research.refreshResearchRecipe((String)"ICHOR_CLOTH");
        Research.refreshResearchRecipe((String)"ICHORIUM");
        Research.refreshResearchRecipe((String)"CAT_AMULET");
        Research.refreshResearchRecipe((String)"ICHOR_POUCH");
        Research.refreshResearchRecipe((String)"ICHORCLOTH_ARMOR");
        Research.refreshResearchRecipe((String)"ROD_ICHORCLOTH");
        Research.refreshResearchRecipe((String)"FOCUS_SHADOWBEAM");
        Research.refreshResearchRecipe((String)"FOCUS_XP_DRAIN");
        Research.refreshResearchRecipe((String)"ICHORCLOTH_HELM_GEM");
        Research.refreshResearchRecipe((String)"ICHORCLOTH_CHEST_GEM");
        Research.refreshResearchRecipe((String)"ICHORCLOTH_LEGS_GEM");
        Research.refreshResearchRecipe((String)"ICHORCLOTH_BOOTS_GEM");
        Research.refreshResearchRecipe((String)"WARP_GATE");
        Research.refreshResearchRecipe((String)"FOCUS_RECALL");
        Research.refreshResearchRecipe((String)"ICHOR_TOOLS");
        Research.refreshResearchRecipe((String)"ICHOR_PICK_GEM");
        Research.refreshResearchRecipe((String)"ICHOR_SHOVEL_GEM");
        Research.refreshResearchRecipe((String)"ICHOR_AXE_GEM");
        Research.refreshResearchRecipe((String)"ICHOR_SWORD_GEM");
        Research.refreshResearchRecipe((String)"PROTOCLAY");
        Research.refreshResearchRecipe((String)"BLOCK_TALISMAN");
        Research.refreshResearchRecipe((String)"PLACEMENT_MIRROR");
    }
}

