package com.github.GTNH2Mega.fromScripts;
import java.util.HashMap;
import minetweaker.MineTweakerAPI;
import minetweaker.api.data.IData;
import minetweaker.api.item.IIngredient;
import minetweaker.api.item.IItemStack;
import minetweaker.expand.ExpandAnyDict;
import minetweaker.expand.ExpandByte;
import minetweaker.expand.ExpandInt;
import minetweaker.expand.ExpandString;
import minetweaker.mc1710.brackets.ItemBracketHandler;
import minetweaker.mc1710.brackets.OreBracketHandler;
import modtweaker2.mods.thaumcraft.handlers.Arcane;
import modtweaker2.mods.thaumcraft.handlers.Infusion;
import modtweaker2.mods.thaumcraft.handlers.Research;
import modtweaker2.mods.thaumcraft.handlers.Warp;
import stanhebben.zenscript.value.IAny;
import static com.github.GTNH2Mega.VoltageLevels.*;

public class Thaumcraft02Thaumaturgy1
implements Runnable {
    public static IAny remove_TC_Infusion(IItemStack iItemStack) {
        Infusion.removeRecipe((IIngredient)iItemStack);
        return null;
    }

    public static IAny remove_TC_Arcane(IItemStack iItemStack) {
        Arcane.removeRecipe((IIngredient)iItemStack);
        return null;
    }

    public void run() {
        IItemStack iItemStack = ItemBracketHandler.getItem((String)"thaumicbases:resource", (int)2);
        Thaumcraft02Thaumaturgy1.remove_TC_Arcane((IItemStack)iItemStack);
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:WandCap", (int)0));
        MineTweakerAPI.recipes.remove((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:WandCasting", (int)0));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:WandCap", (int)32767));
        Infusion.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:WandCap", (int)32767));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:WandRod", (int)0));
        Infusion.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:WandRod", (int)1));
        Infusion.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:WandRod", (int)3));
        Infusion.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:WandRod", (int)4));
        Infusion.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:WandRod", (int)5));
        Infusion.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:WandRod", (int)6));
        Infusion.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:WandRod", (int)7));
        Infusion.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:WandRod", (int)2));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:WandRod", (int)50));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:WandRod", (int)51));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:WandRod", (int)52));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:WandRod", (int)53));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:WandRod", (int)54));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:WandRod", (int)55));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:WandRod", (int)56));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:WandRod", (int)57));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:FocusFire", (int)0));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:FocusExcavation", (int)0));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:FocusFrost", (int)0));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:FocusShock", (int)0));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:FocusTrade", (int)0));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:FocusPouch", (int)0));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:blockStoneDevice", (int)9));
        Infusion.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:blockStoneDevice", (int)10));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:blockStoneDevice", (int)11));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:blockMetalDevice", (int)14));
        Infusion.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:blockStoneDevice", (int)5));
        Infusion.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:FocusWarding", (int)0));
        Infusion.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:FocusPortableHole", (int)0));
        Infusion.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:FocusHellbat", (int)0));
        Infusion.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:ItemAmuletVis", (int)1));
        Infusion.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:blockStoneDevice", (int)8));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:blockMetalDevice", (int)2));
        Arcane.removeRecipe((IIngredient)ItemBracketHandler.getItem((String)"Thaumcraft:blockStoneDevice", (int)13));
        Research.clearPages((String)"BASICTHAUMATURGY");
        Research.addPage((String)"BASICTHAUMATURGY", (String)"tc.research_page.BASICTHAUMATURGY.1");
        Research.addPage((String)"BASICTHAUMATURGY", (String)"tc.research_page.BASICTHAUMATURGY.2");
        MineTweakerAPI.recipes.addShaped(ItemBracketHandler.getItem((String)"Thaumcraft:WandCap", (int)0), (IIngredient[][])new IIngredient[][]{{OreBracketHandler.getOre((String)"screwIron"), OreBracketHandler.getOre((String)"foilIron"), OreBracketHandler.getOre((String)"screwIron")}, {OreBracketHandler.getOre((String)"foilIron"), OreBracketHandler.getOre((String)"ringIron"), OreBracketHandler.getOre((String)"foilIron")}, {OreBracketHandler.getOre((String)"screwIron"), OreBracketHandler.getOre((String)"foilIron"), OreBracketHandler.getOre((String)"screwIron")}}, null);
        Research.addCraftingPage((String)"BASICTHAUMATURGY", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:WandCap", (int)0));
        IItemStack iItemStack2 = ItemBracketHandler.getItem((String)"Thaumcraft:WandCasting", (int)0);
        HashMap<String, IData> hashMap = new HashMap<String, IData>();
        hashMap.put("aqua", ExpandInt.toData((int)0));
        hashMap.put("terra", ExpandInt.toData((int)0));
        hashMap.put("ignis", ExpandInt.toData((int)0));
        hashMap.put("ordo", ExpandInt.toData((int)0));
        hashMap.put("perditio", ExpandInt.toData((int)0));
        hashMap.put("aer", ExpandInt.toData((int)0));
        MineTweakerAPI.recipes.addShaped(iItemStack2.withTag(ExpandAnyDict.asData(hashMap)), (IIngredient[][])new IIngredient[][]{{ItemBracketHandler.getItem((String)"TwilightForest:item.nagaScale", (int)0), OreBracketHandler.getOre((String)"screwAluminium"), ItemBracketHandler.getItem((String)"Thaumcraft:WandCap", (int)0)}, {OreBracketHandler.getOre((String)"screwAluminium"), ItemBracketHandler.getItem((String)"Forestry:oakStick", (int)0), OreBracketHandler.getOre((String)"screwAluminium")}, {ItemBracketHandler.getItem((String)"Thaumcraft:WandCap", (int)0), OreBracketHandler.getOre((String)"screwAluminium"), ItemBracketHandler.getItem((String)"TwilightForest:item.nagaScale", (int)0)}}, null);
        Research.addCraftingPage((String)"BASICTHAUMATURGY", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:WandCasting", (int)0));
        Research.clearPages((String)"CAP_copper");
        Research.addPage((String)"CAP_copper", (String)"tc.research_page.CAP_copper.1");
        Arcane.addShaped((String)"CAP_copper", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:WandCap", (int)3), (String)"ordo 15, ignis 15, aer 15", (IIngredient[][])new IIngredient[][]{{OreBracketHandler.getOre((String)"screwSteel"), OreBracketHandler.getOre((String)"foilCopper"), OreBracketHandler.getOre((String)"screwSteel")}, {OreBracketHandler.getOre((String)"foilCopper"), OreBracketHandler.getOre((String)"ringCopper"), OreBracketHandler.getOre((String)"foilCopper")}, {OreBracketHandler.getOre((String)"screwSteel"), OreBracketHandler.getOre((String)"foilCopper"), OreBracketHandler.getOre((String)"screwSteel")}});
        Research.addArcanePage((String)"CAP_copper", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:WandCap", (int)3));
        Research.setAspects((String)"CAP_copper", (String)"instrumentum 3, metallum 6, permutatio 6");
        Research.setComplexity((String)"CAP_copper", (int)1);
        Research.addPage((String)"SCEPTRE", (String)"tc.research_page.RESEARCH.1");
        IItemStack iItemStack3 = ItemBracketHandler.getItem((String)"Thaumcraft:WandCasting", (int)2);
        HashMap<String, IData> hashMap2 = new HashMap<String, IData>();
        hashMap2.put("cap", ExpandString.asData((String)"copper"));
        hashMap2.put("rod", ExpandString.asData((String)"wood"));
        Research.addArcanePage((String)"CAP_copper", (IItemStack)iItemStack3.withTag(ExpandAnyDict.asData(hashMap2)));
        Research.clearPages((String)"CAP_gold");
        Research.addPage((String)"CAP_gold", (String)"tc.research_page.CAP_gold.1");
        Arcane.addShaped((String)"CAP_gold", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:WandCap", (int)1), (String)"ordo 20, ignis 20, aer 20", (IIngredient[][])new IIngredient[][]{{OreBracketHandler.getOre((String)"screwAluminium"), OreBracketHandler.getOre((String)"foilGold"), OreBracketHandler.getOre((String)"screwAluminium")}, {OreBracketHandler.getOre((String)"foilGold"), OreBracketHandler.getOre((String)"ringGold"), OreBracketHandler.getOre((String)"foilGold")}, {OreBracketHandler.getOre((String)"screwAluminium"), OreBracketHandler.getOre((String)"foilGold"), OreBracketHandler.getOre((String)"screwAluminium")}});
        Research.addArcanePage((String)"CAP_gold", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:WandCap", (int)1));
        Research.setAspects((String)"CAP_gold", (String)"instrumentum 9, metallum 6, lucrum 3");
        Research.setComplexity((String)"CAP_gold", (int)2);
        IItemStack iItemStack4 = ItemBracketHandler.getItem((String)"Thaumcraft:WandCasting", (int)3);
        HashMap<String, IData> hashMap3 = new HashMap<String, IData>();
        hashMap3.put("cap", ExpandString.asData((String)"gold"));
        hashMap3.put("rod", ExpandString.asData((String)"wood"));
        Research.addArcanePage((String)"CAP_gold", (IItemStack)iItemStack4.withTag(ExpandAnyDict.asData(hashMap3)));
        Research.clearPages((String)"CAP_silver");
        Research.addPage((String)"CAP_silver", (String)"tc.research_page.CAP_silver.1");
        Arcane.addShaped((String)"CAP_silver", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:WandCap", (int)5), (String)"ordo 25, ignis 25, aer 25", (IIngredient[][])new IIngredient[][]{{OreBracketHandler.getOre((String)"screwStainlessSteel"), OreBracketHandler.getOre((String)"foilSilver"), OreBracketHandler.getOre((String)"screwStainlessSteel")}, {OreBracketHandler.getOre((String)"foilSilver"), OreBracketHandler.getOre((String)"ringSilver"), OreBracketHandler.getOre((String)"foilSilver")}, {OreBracketHandler.getOre((String)"screwStainlessSteel"), OreBracketHandler.getOre((String)"foilSilver"), OreBracketHandler.getOre((String)"screwStainlessSteel")}});
        Research.addArcanePage((String)"CAP_silver", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:WandCap", (int)5));
        Infusion.addRecipe((String)"CAP_silver", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:WandCap", (int)5), (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)14), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)2054), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)14), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)2054), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)14), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)2054)}, (String)"auram 18, potentia 30, praecantatio 18", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:WandCap", (int)4), (int)5);
        Research.addInfusionPage((String)"CAP_silver", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:WandCap", (int)4));
        IItemStack iItemStack5 = ItemBracketHandler.getItem((String)"Thaumcraft:WandCasting", (int)4);
        HashMap<String, IData> hashMap4 = new HashMap<String, IData>();
        hashMap4.put("cap", ExpandString.asData((String)"silver"));
        hashMap4.put("rod", ExpandString.asData((String)"wood"));
        Research.addArcanePage((String)"CAP_silver", (IItemStack)iItemStack5.withTag(ExpandAnyDict.asData(hashMap4)));
        Research.clearPages((String)"CAP_thaumium");
        Research.addPage((String)"CAP_thaumium", (String)"tc.research_page.CAP_thaumium.1");
        Arcane.addShaped((String)"CAP_thaumium", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:WandCap", (int)6), (String)"ordo 30, ignis 30, aer 30", (IIngredient[][])new IIngredient[][]{{OreBracketHandler.getOre((String)"screwTitanium"), OreBracketHandler.getOre((String)"foilThaumium"), OreBracketHandler.getOre((String)"screwTitanium")}, {OreBracketHandler.getOre((String)"foilThaumium"), OreBracketHandler.getOre((String)"ringThaumium"), OreBracketHandler.getOre((String)"foilThaumium")}, {OreBracketHandler.getOre((String)"screwTitanium"), OreBracketHandler.getOre((String)"foilThaumium"), OreBracketHandler.getOre((String)"screwTitanium")}});
        Research.addArcanePage((String)"CAP_thaumium", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:WandCap", (int)6));
        Infusion.addRecipe((String)"CAP_thaumium", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:WandCap", (int)6), (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)14), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)2330), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)14), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)2330), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)14), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)2330)}, (String)"auram 25, potentia 40, praecantatio 25", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:WandCap", (int)2), (int)5);
        Research.addInfusionPage((String)"CAP_thaumium", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:WandCap", (int)2));
        Research.setAspects((String)"CAP_thaumium", (String)"instrumentum 6, auram 9, metallum 12, praecantatio 3");
        Research.setComplexity((String)"CAP_thaumium", (int)3);
        IItemStack iItemStack6 = ItemBracketHandler.getItem((String)"Thaumcraft:WandCasting", (int)6);
        HashMap<String, IData> hashMap5 = new HashMap<String, IData>();
        hashMap5.put("cap", ExpandString.asData((String)"thaumium"));
        hashMap5.put("rod", ExpandString.asData((String)"wood"));
        Research.addArcanePage((String)"CAP_thaumium", (IItemStack)iItemStack6.withTag(ExpandAnyDict.asData(hashMap5)));
        Research.clearPages((String)"SCEPTRE");
        Research.addPage((String)"SCEPTRE", (String)"tc.research_page.SCEPTRE.1");
        IItemStack iItemStack7 = ItemBracketHandler.getItem((String)"Thaumcraft:WandCasting", (int)1);
        HashMap<String, IData> hashMap6 = new HashMap<String, IData>();
        hashMap6.put("cap", ExpandString.asData((String)"iron"));
        hashMap6.put("rod", ExpandString.asData((String)"wood"));
        hashMap6.put("sceptre", ExpandInt.toData((int)1));
        Research.addArcanePage((String)"SCEPTRE", (IItemStack)iItemStack7.withTag(ExpandAnyDict.asData(hashMap6)));
        Research.setAspects((String)"SCEPTRE", (String)"instrumentum 12, fabrico 12, arbor 9, praecantatio 6, cognitio 3");
        Research.setComplexity((String)"SCEPTRE", (int)3);
        IItemStack iItemStack8 = ItemBracketHandler.getItem((String)"Thaumcraft:WandCasting", (int)9);
        HashMap<String, IData> hashMap7 = new HashMap<String, IData>();
        hashMap7.put("cap", ExpandString.asData((String)"thaumium"));
        hashMap7.put("rod", ExpandString.asData((String)"wood"));
        Research.addArcanePage((String)"SCEPTRE", (IItemStack)iItemStack8.withTag(ExpandAnyDict.asData(hashMap7)));
        Research.clearPages((String)"ROD_greatwood");
        Research.addPage((String)"ROD_greatwood", (String)"tc.research_page.ROD_greatwood.1");
        Arcane.addShaped((String)"ROD_greatwood", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:WandRod", (int)0), (String)"aer 20, terra 20, ignis 20, aqua 20, ordo 20, perditio 20", (IIngredient[][])new IIngredient[][]{{null, null, ItemBracketHandler.getItem((String)"Thaumcraft:blockMagicalLog", (int)0)}, {null, ItemBracketHandler.getItem((String)"Thaumcraft:blockMagicalLog", (int)0), null}, {ItemBracketHandler.getItem((String)"Thaumcraft:blockMagicalLog", (int)0), null, null}});
        Research.addArcanePage((String)"ROD_greatwood", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:WandRod", (int)0));
        Research.setAspects((String)"ROD_greatwood", (String)"instrumentum 9, praecantatio 6, arbor 3");
        Research.setComplexity((String)"ROD_greatwood", (int)2);
        IItemStack iItemStack9 = ItemBracketHandler.getItem((String)"Thaumcraft:WandCasting", (int)9);
        HashMap<String, IData> hashMap8 = new HashMap<String, IData>();
        hashMap8.put("cap", ExpandString.asData((String)"gold"));
        hashMap8.put("rod", ExpandString.asData((String)"greatwood"));
        Research.addArcanePage((String)"ROD_greatwood", (IItemStack)iItemStack9.withTag(ExpandAnyDict.asData(hashMap8)));
        IItemStack iItemStack10 = ItemBracketHandler.getItem((String)"Thaumcraft:WandCasting", (int)13);
        HashMap<String, IData> hashMap9 = new HashMap<String, IData>();
        hashMap9.put("cap", ExpandString.asData((String)"gold"));
        hashMap9.put("rod", ExpandString.asData((String)"greatwood"));
        hashMap9.put("sceptre", ExpandByte.asData((byte)1));
        Research.addArcanePage((String)"SCEPTRE", (IItemStack)iItemStack10.withTag(ExpandAnyDict.asData(hashMap9)));
        Infusion.addRecipe((String)"ROD_reed", (IItemStack)ItemBracketHandler.getItem((String)"TConstruct:trap.punji", (int)0), (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)6), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)6), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)0)}, (String)"aer 24, motus 12, praecantatio 12, vitreus 6", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:WandRod", (int)5), (int)2);
        Research.setAspects((String)"ROD_reed", (String)"instrumentum 9, praecantatio 9, aer 6, herba 6, arbor 3");
        Research.setComplexity((String)"ROD_reed", (int)2);
        IItemStack iItemStack11 = ItemBracketHandler.getItem((String)"Thaumcraft:WandCasting", (int)24);
        HashMap<String, IData> hashMap10 = new HashMap<String, IData>();
        hashMap10.put("cap", ExpandString.asData((String)"silver"));
        hashMap10.put("rod", ExpandString.asData((String)"reed"));
        Research.addArcanePage((String)"ROD_reed", (IItemStack)iItemStack11.withTag(ExpandAnyDict.asData(hashMap10)));
        IItemStack iItemStack12 = ItemBracketHandler.getItem((String)"Thaumcraft:WandCasting", (int)45);
        HashMap<String, IData> hashMap11 = new HashMap<String, IData>();
        hashMap11.put("cap", ExpandString.asData((String)"thaumium"));
        hashMap11.put("rod", ExpandString.asData((String)"reed"));
        hashMap11.put("sceptre", ExpandByte.asData((byte)1));
        Research.addArcanePage((String)"SCEPTRE", (IItemStack)iItemStack12.withTag(ExpandAnyDict.asData(hashMap11)));
        Infusion.addRecipe((String)"ROD_blaze", (IItemStack)ItemBracketHandler.getItem((String)"minecraft:blaze_rod", (int)0), (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)6), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)1), ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)6), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)1)}, (String)"bestia 12, ignis 24, praecantatio 12, vitreus 6", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:WandRod", (int)6), (int)2);
        Research.setAspects((String)"ROD_blaze", (String)"instrumentum 9, praecantatio 9, aer 6, herba 6, arbor 3");
        Research.setComplexity((String)"ROD_blaze", (int)2);
        IItemStack iItemStack13 = ItemBracketHandler.getItem((String)"Thaumcraft:WandCasting", (int)24);
        HashMap<String, IData> hashMap12 = new HashMap<String, IData>();
        hashMap12.put("cap", ExpandString.asData((String)"thaumium"));
        hashMap12.put("rod", ExpandString.asData((String)"blaze"));
        Research.addArcanePage((String)"ROD_blaze", (IItemStack)iItemStack13.withTag(ExpandAnyDict.asData(hashMap12)));
        Infusion.addRecipe((String)"ROD_obsidian", (IItemStack)ItemBracketHandler.getItem((String)"RandomThings:ingredient", (int)1), (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)6), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)3), ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)6), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)3)}, (String)" praecantatio 12, tenebrae 12, terra 24, vitreus 6", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:WandRod", (int)1), (int)2);
        Research.setAspects((String)"ROD_obsidian", (String)"instrumentum 9, praecantatio 9, ignis 6, potentia 6, arbor 3");
        Research.setComplexity((String)"ROD_obsidian", (int)2);
        IItemStack iItemStack14 = ItemBracketHandler.getItem((String)"Thaumcraft:WandCasting", (int)36);
        HashMap<String, IData> hashMap13 = new HashMap<String, IData>();
        hashMap13.put("cap", ExpandString.asData((String)"thaumium"));
        hashMap13.put("rod", ExpandString.asData((String)"obsidian"));
        Research.addArcanePage((String)"ROD_obsidian", (IItemStack)iItemStack14.withTag(ExpandAnyDict.asData(hashMap13)));
        Infusion.addRecipe((String)"ROD_ice", (IItemStack)ItemBracketHandler.getItem((String)"BiomesOPlenty:hardIce", (int)0), (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)6), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)2), ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)6), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)2)}, (String)" aqua 24, gelum 12, praecantatio 12, vitreus 6", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:WandRod", (int)3), (int)2);
        Research.setAspects((String)"ROD_ice", (String)"instrumentum 9, praecantatio 9, aqua 6, gelum 6, arbor 3");
        Research.setComplexity((String)"ROD_ice", (int)2);
        IItemStack iItemStack15 = ItemBracketHandler.getItem((String)"Thaumcraft:WandCasting", (int)36);
        HashMap<String, IData> hashMap14 = new HashMap<String, IData>();
        hashMap14.put("cap", ExpandString.asData((String)"thaumium"));
        hashMap14.put("rod", ExpandString.asData((String)"ice"));
        Research.addArcanePage((String)"ROD_ice", (IItemStack)iItemStack15.withTag(ExpandAnyDict.asData(hashMap14)));
        Infusion.addRecipe((String)"ROD_quartz", (IItemStack)ItemBracketHandler.getItem((String)"dreamcraft:item.ChargedCertusQuartzRod", (int)0), (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)6), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)4), ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)6), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)4)}, (String)" ordo 24, praecantatio 12, potentia 12, vitreus 6", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:WandRod", (int)4), (int)2);
        Research.setAspects((String)"ROD_quartz", (String)"instrumentum 9, praecantatio 9, terra 6, ordo 6, arbor 3");
        Research.setComplexity((String)"ROD_quartz", (int)2);
        IItemStack iItemStack16 = ItemBracketHandler.getItem((String)"Thaumcraft:WandCasting", (int)36);
        HashMap<String, IData> hashMap15 = new HashMap<String, IData>();
        hashMap15.put("cap", ExpandString.asData((String)"thaumium"));
        hashMap15.put("rod", ExpandString.asData((String)"quartz"));
        Research.addArcanePage((String)"ROD_quartz", (IItemStack)iItemStack16.withTag(ExpandAnyDict.asData(hashMap15)));
        Infusion.addRecipe((String)"ROD_bone", (IItemStack)ItemBracketHandler.getItem((String)"TConstruct:toolRod", (int)5), (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)6), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)5), ItemBracketHandler.getItem((String)"Thaumcraft:ItemShard", (int)6), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)5)}, (String)" exanimis 12, perditio 24, praecantatio 12, vitreus 6", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:WandRod", (int)7), (int)3);
        Research.setAspects((String)"ROD_bone", (String)"instrumentum 9, praecantatio 9, exanimis 6, perditio 6, arbor 3");
        Research.setComplexity((String)"ROD_bone", (int)2);
        Warp.addToResearch((String)"ROD_bone", (int)1);
        IItemStack iItemStack17 = ItemBracketHandler.getItem((String)"Thaumcraft:WandCasting", (int)36);
        HashMap<String, IData> hashMap16 = new HashMap<String, IData>();
        hashMap16.put("cap", ExpandString.asData((String)"thaumium"));
        hashMap16.put("rod", ExpandString.asData((String)"bone"));
        Research.addArcanePage((String)"ROD_bone", (IItemStack)iItemStack17.withTag(ExpandAnyDict.asData(hashMap16)));
        Infusion.addRecipe((String)"ROD_silverwood", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:blockMagicalLog", (int)1), (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)1), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)2), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)3), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)4), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)5), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)6)}, (String)" aer 48, aqua 48, ignis 48, ordo 48, perditio 48, praecantatio 48, terra 48", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:WandRod", (int)2), (int)5);
        Research.setAspects((String)"ROD_silverwood", (String)"instrumentum 12, praecantatio 12, cognitio 9, herba 6, arbor 3");
        Research.setComplexity((String)"ROD_silverwood", (int)3);
        IItemStack iItemStack18 = ItemBracketHandler.getItem((String)"Thaumcraft:WandCasting", (int)36);
        HashMap<String, IData> hashMap17 = new HashMap<String, IData>();
        hashMap17.put("cap", ExpandString.asData((String)"thaumium"));
        hashMap17.put("rod", ExpandString.asData((String)"silverwood"));
        Research.addArcanePage((String)"ROD_silverwood", (IItemStack)iItemStack18.withTag(ExpandAnyDict.asData(hashMap17)));
        Arcane.addShaped((String)"ROD_greatwood_staff", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:WandRod", (int)50), (String)"aer 50, terra 50, ignis 50, aqua 50, ordo 50, perditio 50", (IIngredient[][])new IIngredient[][]{{ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)1), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)15)}, {ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)2), ItemBracketHandler.getItem((String)"Thaumcraft:WandRod", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)3)}, {ItemBracketHandler.getItem((String)"Thaumcraft:WandRod", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)4), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)5)}});
        Research.setAspects((String)"ROD_greatwood_staff", (String)"instrumentum 12, praecantatio 12, arbor 9, ignis 6, aer 6, terra 3");
        Research.setComplexity((String)"ROD_greatwood_staff", (int)3);
        IItemStack iItemStack19 = ItemBracketHandler.getItem((String)"Thaumcraft:WandCasting", (int)48);
        HashMap<String, IData> hashMap18 = new HashMap<String, IData>();
        hashMap18.put("cap", ExpandString.asData((String)"thaumium"));
        hashMap18.put("rod", ExpandString.asData((String)"greatwood_staff"));
        Research.addArcanePage((String)"ROD_greatwood_staff", (IItemStack)iItemStack19.withTag(ExpandAnyDict.asData(hashMap18)));
        Arcane.addShaped((String)"ROD_reed_staff", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:WandRod", (int)55), (String)"aer 75, terra 75, ignis 75, aqua 75, ordo 75, perditio 75", (IIngredient[][])new IIngredient[][]{{ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)1), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)15)}, {ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)2), ItemBracketHandler.getItem((String)"Thaumcraft:WandRod", (int)5), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)3)}, {ItemBracketHandler.getItem((String)"Thaumcraft:WandRod", (int)5), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)4), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)5)}});
        Research.setAspects((String)"ROD_reed_staff", (String)"instrumentum 12, praecantatio 12, herba 9, aer 6, ignis 6, terra 3");
        Research.setComplexity((String)"ROD_reed_staff", (int)3);
        IItemStack iItemStack20 = ItemBracketHandler.getItem((String)"Thaumcraft:WandCasting", (int)42);
        HashMap<String, IData> hashMap19 = new HashMap<String, IData>();
        hashMap19.put("cap", ExpandString.asData((String)"gold"));
        hashMap19.put("rod", ExpandString.asData((String)"reed_staff"));
        Research.addArcanePage((String)"ROD_reed_staff", (IItemStack)iItemStack20.withTag(ExpandAnyDict.asData(hashMap19)));
        Arcane.addShaped((String)"ROD_blaze_staff", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:WandRod", (int)56), (String)"aer 75, terra 75, ignis 75, aqua 75, ordo 75, perditio 75", (IIngredient[][])new IIngredient[][]{{ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)1), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)15)}, {ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)2), ItemBracketHandler.getItem((String)"Thaumcraft:WandRod", (int)6), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)3)}, {ItemBracketHandler.getItem((String)"Thaumcraft:WandRod", (int)6), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)4), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)5)}});
        Research.setAspects((String)"ROD_blaze_staff", (String)"instrumentum 12, praecantatio 12, ignis 9, potentia 6, aer 6, terra 3");
        Research.setComplexity((String)"ROD_blaze_staff", (int)3);
        IItemStack iItemStack21 = ItemBracketHandler.getItem((String)"Thaumcraft:WandCasting", (int)56);
        HashMap<String, IData> hashMap20 = new HashMap<String, IData>();
        hashMap20.put("cap", ExpandString.asData((String)"silver"));
        hashMap20.put("rod", ExpandString.asData((String)"blaze_staff"));
        Research.addArcanePage((String)"ROD_blaze_staff", (IItemStack)iItemStack21.withTag(ExpandAnyDict.asData(hashMap20)));
        Arcane.addShaped((String)"ROD_obsidian_staff", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:WandRod", (int)51), (String)"aer 75, terra 75, ignis 75, aqua 75, ordo 75, perditio 75", (IIngredient[][])new IIngredient[][]{{ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)1), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)15)}, {ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)2), ItemBracketHandler.getItem((String)"Thaumcraft:WandRod", (int)1), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)3)}, {ItemBracketHandler.getItem((String)"Thaumcraft:WandRod", (int)1), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)4), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)5)}});
        Research.setAspects((String)"ROD_obsidian_staff", (String)"instrumentum 12, praecantatio 12, terra 9, ignis 6, aer 6, potentia 3");
        Research.setComplexity((String)"ROD_obsidian_staff", (int)3);
        IItemStack iItemStack22 = ItemBracketHandler.getItem((String)"Thaumcraft:WandCasting", (int)84);
        HashMap<String, IData> hashMap21 = new HashMap<String, IData>();
        hashMap21.put("cap", ExpandString.asData((String)"thaumium"));
        hashMap21.put("rod", ExpandString.asData((String)"obsidian_staff"));
        Research.addArcanePage((String)"ROD_obsidian_staff", (IItemStack)iItemStack22.withTag(ExpandAnyDict.asData(hashMap21)));
        Arcane.addShaped((String)"ROD_ice_staff", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:WandRod", (int)53), (String)"aer 75, terra 75, ignis 75, aqua 75, ordo 75, perditio 75", (IIngredient[][])new IIngredient[][]{{ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)1), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)15)}, {ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)2), ItemBracketHandler.getItem((String)"Thaumcraft:WandRod", (int)3), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)3)}, {ItemBracketHandler.getItem((String)"Thaumcraft:WandRod", (int)3), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)4), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)5)}});
        Research.setAspects((String)"ROD_ice_staff", (String)"instrumentum 12, praecantatio 12, gelum 9, aqua 6, aer 6, terra 3");
        Research.setComplexity((String)"ROD_ice_staff", (int)3);
        Arcane.addShaped((String)"ROD_quartz_staff", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:WandRod", (int)54), (String)"aer 75, terra 75, ignis 75, aqua 75, ordo 75, perditio 75", (IIngredient[][])new IIngredient[][]{{ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)1), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)15)}, {ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)2), ItemBracketHandler.getItem((String)"Thaumcraft:WandRod", (int)4), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)3)}, {ItemBracketHandler.getItem((String)"Thaumcraft:WandRod", (int)4), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)4), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)5)}});
        Research.setAspects((String)"ROD_quartz_staff", (String)"instrumentum 12, praecantatio 12, vitreus 9, ordo 6, aer 6, terra 3");
        Research.setComplexity((String)"ROD_quartz_staff", (int)3);
        Arcane.addShaped((String)"ROD_bone_staff", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:WandRod", (int)57), (String)"aer 75, terra 75, ignis 75, aqua 75, ordo 75, perditio 75", (IIngredient[][])new IIngredient[][]{{ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)1), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)15)}, {ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)2), ItemBracketHandler.getItem((String)"Thaumcraft:WandRod", (int)7), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)3)}, {ItemBracketHandler.getItem((String)"Thaumcraft:WandRod", (int)7), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)4), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)5)}});
        Research.setAspects((String)"ROD_bone_staff", (String)"instrumentum 12, praecantatio 12, exanimis 9, perditio 6, aer 6, terra 3");
        Research.setComplexity((String)"ROD_bone_staff", (int)3);
        Warp.addToResearch((String)"ROD_bone_staff", (int)3);
        Arcane.addShaped((String)"ROD_silverwood_staff", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:WandRod", (int)52), (String)"aer 125, terra 125, ignis 125, aqua 125, ordo 125, perditio 125", (IIngredient[][])new IIngredient[][]{{ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)1), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)15)}, {ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)2), ItemBracketHandler.getItem((String)"Thaumcraft:WandRod", (int)2), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)3)}, {ItemBracketHandler.getItem((String)"Thaumcraft:WandRod", (int)2), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)4), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)5)}});
        Research.setAspects((String)"ROD_silverwood_staff", (String)"instrumentum 15, praecantatio 15, arbor 12, ordo 9, aer 6, terra 3");
        Research.setComplexity((String)"ROD_silverwood_staff", (int)4);
        IItemStack iItemStack23 = ItemBracketHandler.getItem((String)"Thaumcraft:WandCasting", (int)144);
        HashMap<String, IData> hashMap22 = new HashMap<String, IData>();
        hashMap22.put("cap", ExpandString.asData((String)"thaumium"));
        hashMap22.put("rod", ExpandString.asData((String)"silverwood_staff"));
        Research.addArcanePage((String)"ROD_silverwood_staff", (IItemStack)iItemStack23.withTag(ExpandAnyDict.asData(hashMap22)));
        IItemStack iItemStack24 = ItemBracketHandler.getItem((String)"Thaumcraft:WandCasting", (int)216);
        HashMap<String, IData> hashMap23 = new HashMap<String, IData>();
        hashMap23.put("cap", ExpandString.asData((String)"thaumium"));
        hashMap23.put("rod", ExpandString.asData((String)"silverwood_staff"));
        hashMap23.put("sceptre", ExpandByte.asData((byte)1));
        Research.addArcanePage((String)"SCEPTRE", (IItemStack)iItemStack24.withTag(ExpandAnyDict.asData(hashMap23)));
        Arcane.addShaped((String)"FOCUSFIRE", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:FocusFire", (int)0), (String)"ignis 20, perditio 20, ordo 20", (IIngredient[][])new IIngredient[][]{{ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)1), OreBracketHandler.getOre((String)"gemQuartz"), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)1)}, {OreBracketHandler.getOre((String)"gemQuartz"), OreBracketHandler.getOre((String)"lensRuby"), OreBracketHandler.getOre((String)"gemQuartz")}, {ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)1), OreBracketHandler.getOre((String)"gemQuartz"), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)1)}});
        Research.setAspects((String)"FOCUSFIRE", (String)"ignis 6, praecantatio 6, motus 3");
        Research.setComplexity((String)"FOCUSFIRE", (int)1);
        Arcane.addShaped((String)"FOCUSEXCAVATION", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:FocusExcavation", (int)0), (String)"terra 30, perditio 20, ordo 20", (IIngredient[][])new IIngredient[][]{{ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)3), OreBracketHandler.getOre((String)"gemQuartz"), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)3)}, {OreBracketHandler.getOre((String)"gemQuartz"), OreBracketHandler.getOre((String)"lensEmerald"), OreBracketHandler.getOre((String)"gemQuartz")}, {ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)3), OreBracketHandler.getOre((String)"gemQuartz"), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)3)}});
        Research.setAspects((String)"FOCUSEXCAVATION", (String)"terra 9, praecantatio 9, perditio 6, motus 3");
        Research.setComplexity((String)"FOCUSEXCAVATION", (int)2);
        Arcane.addShaped((String)"FOCUSFROST", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:FocusFrost", (int)0), (String)"aqua 30, perditio 20, ordo 20", (IIngredient[][])new IIngredient[][]{{ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)2), OreBracketHandler.getOre((String)"gemQuartz"), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)2)}, {OreBracketHandler.getOre((String)"gemQuartz"), OreBracketHandler.getOre((String)"lensDiamond"), OreBracketHandler.getOre((String)"gemQuartz")}, {ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)2), OreBracketHandler.getOre((String)"gemQuartz"), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)2)}});
        Research.setAspects((String)"FOCUSFROST", (String)"aqua 9, gelum 9, praecantatio 6, motus 3");
        Research.setComplexity((String)"FOCUSFROST", (int)2);
        Arcane.addShaped((String)"FOCUSSHOCK", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:FocusShock", (int)0), (String)"aer 30, perditio 20, ordo 20", (IIngredient[][])new IIngredient[][]{{ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)0), OreBracketHandler.getOre((String)"gemQuartz"), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)0)}, {OreBracketHandler.getOre((String)"gemQuartz"), OreBracketHandler.getOre((String)"lensGarnetYellow"), OreBracketHandler.getOre((String)"gemQuartz")}, {ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)0), OreBracketHandler.getOre((String)"gemQuartz"), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)0)}});
        Research.setAspects((String)"FOCUSSHOCK", (String)"aer 9, praecantatio 6, potentia 9, motus 3");
        Research.setComplexity((String)"FOCUSSHOCK", (int)2);
        Arcane.addShaped((String)"FOCUSTRADE", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:FocusTrade", (int)0), (String)"aer 20, terra 20, perditio 30, ordo 30", (IIngredient[][])new IIngredient[][]{{ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)6), OreBracketHandler.getOre((String)"gemQuartz"), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)6)}, {OreBracketHandler.getOre((String)"gemQuartz"), ItemBracketHandler.getItem((String)"dreamcraft:item.ReinforcedGlassLense", (int)0), OreBracketHandler.getOre((String)"gemQuartz")}, {ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)6), OreBracketHandler.getOre((String)"gemQuartz"), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)6)}});
        Research.setAspects((String)"FOCUSTRADE", (String)"permutatio 9, praecantatio 9, terra 6, motus 3");
        Research.setComplexity((String)"FOCUSTRADE", (int)2);
        Infusion.addRecipe((String)"FOCUSWARDING", (IItemStack)ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)24506), (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)3), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)3), ItemBracketHandler.getItem((String)"minecraft:quartz", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)4), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)3), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)3), ItemBracketHandler.getItem((String)"minecraft:quartz", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)4)}, (String)"cognitio 15, ordo 25, terra 30, tutamen 25, praecantatio 10", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:FocusWarding", (int)0), (int)5);
        Research.setAspects((String)"FOCUSWARDING", (String)"terra 12, cognitio 12, ordo 9, tutamen 6, praecantatio 3");
        Research.setComplexity((String)"FOCUSWARDING", (int)3);
        Infusion.addRecipe((String)"FOCUSPORTABLEHOLE", (IItemStack)ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)24532), (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"minecraft:quartz", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)3), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)5), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)0), ItemBracketHandler.getItem((String)"minecraft:quartz", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)5), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)3)}, (String)"alienis 40, iter 30, perditio 20, permutatio 10, praecantatio 5", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:FocusPortableHole", (int)0), (int)6);
        Research.setAspects((String)"FOCUSPORTABLEHOLE", (String)"aer 12, iter 12, alienis 9, perditio 6, praecantatio 3");
        Research.setComplexity((String)"FOCUSPORTABLEHOLE", (int)3);
        Warp.addToResearch((String)"NODESTABILIZERADV", (int)1);
        Infusion.addRecipe((String)"FOCUSHELLBAT", (IItemStack)ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)24347), (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"minecraft:quartz", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)1), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)5), ItemBracketHandler.getItem((String)"minecraft:quartz", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)5), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)1), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)0)}, (String)"aer 30, ignis 40, bestia 20, perditio 10, praecantatio 5", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:FocusHellbat", (int)0), (int)7);
        Research.setAspects((String)"FOCUSHELLBAT", (String)"praecantatio 12, iter 9, ignis 9, bestia 6, motus 3");
        Research.setComplexity((String)"FOCUSHELLBAT", (int)3);
        Warp.addToResearch((String)"NODESTABILIZERADV", (int)2);
        Warp.addToItem((IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:FocusHellbat", (int)0), (int)2);
        Arcane.addShaped((String)"FOCUSPOUCH", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:FocusPouch", (int)0), (String)"terra 20, perditio 20, ordo 20", (IIngredient[][])new IIngredient[][]{{OreBracketHandler.getOre((String)"boltGold"), OreBracketHandler.getOre((String)"ringGold"), OreBracketHandler.getOre((String)"boltGold")}, {ItemBracketHandler.getItem((String)"harvestcraft:hardenedleatherItem", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:ItemBaubleBlanks", (int)2), ItemBracketHandler.getItem((String)"harvestcraft:hardenedleatherItem", (int)0)}, {ItemBracketHandler.getItem((String)"harvestcraft:hardenedleatherItem", (int)0), ItemBracketHandler.getItem((String)"harvestcraft:hardenedleatherItem", (int)0), ItemBracketHandler.getItem((String)"harvestcraft:hardenedleatherItem", (int)0)}});
        Research.setAspects((String)"FOCUSPOUCH", (String)"instrumentum 9, vacuos 9, praecantatio 6, pannus 3");
        Research.setComplexity((String)"FOCUSPOUCH", (int)2);
        Arcane.addShaped((String)"NODESTABILIZER", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:blockStoneDevice", (int)9), (String)"aqua 35, terra 35, ordo 25", (IIngredient[][])new IIngredient[][]{{OreBracketHandler.getOre((String)"plateThaumium"), OreBracketHandler.getOre((String)"springGold"), OreBracketHandler.getOre((String)"plateThaumium")}, {OreBracketHandler.getOre((String)"blockQuartz"), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)32640), OreBracketHandler.getOre((String)"blockQuartz")}, {ItemBracketHandler.getItem((String)"Thaumcraft:blockCosmeticSolid", (int)7), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)1), ItemBracketHandler.getItem((String)"Thaumcraft:blockCosmeticSolid", (int)7)}});
        Research.setAspects((String)"NODESTABILIZER", (String)"auram 9, potentia 9, praecantatio 6, ordo 3");
        Research.setComplexity((String)"NODESTABILIZER", (int)2);
        Infusion.addRecipe((String)"NODESTABILIZERADV", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:blockStoneDevice", (int)9), (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"minecraft:redstone_block", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)1), ItemBracketHandler.getItem((String)"minecraft:redstone_block", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)0), ItemBracketHandler.getItem((String)"minecraft:glowstone", (int)0), ItemBracketHandler.getItem((String)"minecraft:redstone_block", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)1), ItemBracketHandler.getItem((String)"minecraft:redstone_block", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)0), ItemBracketHandler.getItem((String)"minecraft:glowstone", (int)0)}, (String)"auram 32, ordo 32, potentia 32, praecantatio 32", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:blockStoneDevice", (int)10), (int)10);
        Research.setAspects((String)"NODESTABILIZERADV", (String)"auram 12, potentia 9, praecantatio 9, ordo 6, alienis 3");
        Research.setComplexity((String)"NODESTABILIZERADV", (int)3);
        Warp.addToResearch((String)"NODESTABILIZERADV", (int)2);
        Arcane.addShaped((String)"VISPOWER", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:blockStoneDevice", (int)11), (String)"ignis 32, aer 32, perditio 32, ordo 32", (IIngredient[][])new IIngredient[][]{{OreBracketHandler.getOre((String)"blockRedstone"), ItemBracketHandler.getItem((String)"ProjRed|Integration:projectred.integration.gate", (int)26), OreBracketHandler.getOre((String)"blockRedstone")}, {OreBracketHandler.getOre((String)"plateThaumium"), ItemBracketHandler.getItem((String)"Thaumcraft:blockStoneDevice", (int)9), OreBracketHandler.getOre((String)"plateThaumium")}, {OreBracketHandler.getOre((String)"blockRedstone"), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)1), OreBracketHandler.getOre((String)"blockRedstone")}});
        Arcane.addShaped((String)"VISPOWER", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:blockMetalDevice", (int)14), (String)"ignis 10, ordo 10", (IIngredient[][])new IIngredient[][]{{OreBracketHandler.getOre((String)"screwSteel"), OreBracketHandler.getOre((String)"lensDiamond"), OreBracketHandler.getOre((String)"screwSteel")}, {OreBracketHandler.getOre((String)"ringThaumium"), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)6), OreBracketHandler.getOre((String)"ringThaumium")}, {OreBracketHandler.getOre((String)"screwSteel"), OreBracketHandler.getOre((String)"lensDiamond"), OreBracketHandler.getOre((String)"screwSteel")}});
        Research.setAspects((String)"VISPOWER", (String)"auram 12, potentia 9, praecantatio 3, machina 6");
        Research.setComplexity((String)"VISPOWER", (int)3);
        Infusion.addRecipe((String)"WANDPED", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:blockStoneDevice", (int)1), (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.01", (int)17086), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.02", (int)29500), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)15), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.02", (int)29500)}, (String)"auram 10, permutatio 15, praecantatio 20, ordo 5", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:blockStoneDevice", (int)5), (int)2);
        Research.setAspects((String)"WANDPED", (String)"auram 12, potentia 9, praecantatio 3, permutatio 6");
        Research.setComplexity((String)"WANDPED", (int)3);
        Infusion.addRecipe((String)"VISAMULET", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemBaubleBlanks", (int)0), (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)15), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)6), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.02", (int)30500), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)6), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)15), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)6), ItemBracketHandler.getItem((String)"gregtech:gt.metaitem.02", (int)30500), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)6)}, (String)"vacuos 48, auram 48, potentia 88, praecantatio 88, vitreus 24", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:ItemAmuletVis", (int)1), (int)7);
        Research.setAspects((String)"VISAMULET", (String)"vacuos 15, auram 15, praecantatio 9, potentia 12, vitreus 6, tempus 3");
        Research.setComplexity((String)"VISAMULET", (int)4);
        Infusion.addRecipe((String)"WANDPEDFOC", (IItemStack)ItemBracketHandler.getItem((String)"ProjRed|Integration:projectred.integration.gate", (int)26), (IItemStack[])new IItemStack[]{ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)6), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)8), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)6), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)8), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)6), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)8), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)6), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)8)}, (String)"ordo 25, permutatio 25, praecantatio 30, potentia 15, cognitio 15", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:blockStoneDevice", (int)8), (int)5);
        Research.setAspects((String)"WANDPEDFOC", (String)"instrumentum 15, auram 15, praecantatio 12, potentia 12, permutatio 9, cognitio 6, lucrum 3");
        Research.setComplexity((String)"WANDPEDFOC", (int)4);
        Arcane.addShaped((String)"VISCHARGERELAY", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:blockMetalDevice", (int)2), (String)"ignis 20, ordo 20, aer 20, terra 10", (IIngredient[][])new IIngredient[][]{{OreBracketHandler.getOre((String)"screwThaumium"), ItemBracketHandler.getItem((String)"Thaumcraft:blockMetalDevice", (int)14), OreBracketHandler.getOre((String)"screwThaumium")}, {ItemBracketHandler.getItem((String)"Thaumcraft:WandRod", (int)2), OreBracketHandler.getOre((String)"plateThaumium"), ItemBracketHandler.getItem((String)"Thaumcraft:WandRod", (int)2)}, {ItemBracketHandler.getItem((String)"Thaumcraft:WandRod", (int)0), OreBracketHandler.getOre((String)"craftingToolScrewdriver"), ItemBracketHandler.getItem((String)"Thaumcraft:WandRod", (int)0)}});
        Research.setAspects((String)"VISCHARGERELAY", (String)"potentia 12, praecantatio 12, machina 9, auram 9, ignis 6, aer 3");
        Research.setComplexity((String)"VISCHARGERELAY", (int)3);
        Arcane.addShaped((String)"FOCALMANIPULATION", (IItemStack)ItemBracketHandler.getItem((String)"Thaumcraft:blockStoneDevice", (int)13), (String)"ignis 64, ordo 64, aer 64, terra 64, aqua 64, perditio 64", (IIngredient[][])new IIngredient[][]{{ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)6), ItemBracketHandler.getItem((String)"Thaumcraft:blockCosmeticSlabStone", (int)0), ItemBracketHandler.getItem((String)"Thaumcraft:blockCrystal", (int)6)}, {ItemBracketHandler.getItem((String)"Thaumcraft:blockCosmeticSolid", (int)7), ItemBracketHandler.getItem((String)"Thaumcraft:ItemResource", (int)15), ItemBracketHandler.getItem((String)"Thaumcraft:blockCosmeticSolid", (int)7)}, {OreBracketHandler.getOre((String)"plateThaumium"), ItemBracketHandler.getItem((String)"Thaumcraft:blockTable", (int)0), OreBracketHandler.getOre((String)"plateThaumium")}});
        Research.setAspects((String)"FOCALMANIPULATION", (String)"potentia 15, praecantatio 12, instrumentum 12, vitreus 9, fabrico 9, alienis 3, cognitio 5");
        Research.setComplexity((String)"FOCALMANIPULATION", (int)4);
        Research.setAspects((String)"VAMPBAT", (String)"fames 15, praecantatio 15, victus 12, exanimis 12, cognitio 9, ira 3, alienis 6");
        Research.setComplexity((String)"VAMPBAT", (int)4);
        Warp.addToResearch((String)"VAMPBAT", (int)4);
        Research.refreshResearchRecipe((String)"CAP_copper");
        Research.refreshResearchRecipe((String)"CAP_gold");
        Research.refreshResearchRecipe((String)"CAP_silver");
        Research.refreshResearchRecipe((String)"CAP_thaumium");
        Research.refreshResearchRecipe((String)"ROD_silverwood");
        Research.refreshResearchRecipe((String)"ROD_greatwood_staff");
        Research.refreshResearchRecipe((String)"FOCUSFIRE");
        Research.refreshResearchRecipe((String)"FOCUSEXCAVATION");
        Research.refreshResearchRecipe((String)"FOCUSFROST");
        Research.refreshResearchRecipe((String)"FOCUSSHOCK");
        Research.refreshResearchRecipe((String)"FOCUSTRADE");
        Research.refreshResearchRecipe((String)"FOCUSWARDING");
        Research.refreshResearchRecipe((String)"FOCUSPORTABLEHOLE");
        Research.refreshResearchRecipe((String)"FOCUSHELLBAT");
        Research.refreshResearchRecipe((String)"FOCUSPOUCH");
        Research.refreshResearchRecipe((String)"NODESTABILIZER");
        Research.refreshResearchRecipe((String)"NODESTABILIZERADV");
        Research.refreshResearchRecipe((String)"VISPOWER");
        Research.refreshResearchRecipe((String)"WANDPED");
        Research.refreshResearchRecipe((String)"VISAMULET");
        Research.refreshResearchRecipe((String)"WANDPEDFOC");
        Research.refreshResearchRecipe((String)"VISCHARGERELAY");
        Research.refreshResearchRecipe((String)"FOCALMANIPULATION");
        Research.refreshResearchRecipe((String)"VAMPBAT");
    }
}

