package com.github.GTNH2Mega

import com.github.GTNH2Mega.VoltageLevels.EV
import com.github.GTNH2Mega.VoltageLevels.HV
import com.github.GTNH2Mega.VoltageLevels.IV
import com.github.GTNH2Mega.VoltageLevels.LUV
import com.github.GTNH2Mega.VoltageLevels.MV
import minetweaker.mc1710.brackets.ItemBracketHandler
import modtweaker2.mods.forestry.handlers.Carpenter
import minetweaker.mc1710.brackets.LiquidBracketHandler
import gttweaker.mods.gregtech.machines.Assembler

object ZZClientOnly {
    fun script() {
        ItemBracketHandler.getItem("BiblioWoodsBoP:BiblioWoodcase", 4).displayName = "Hellbark Case"
        Carpenter.addRecipe(10, LiquidBracketHandler.getLiquid("seedoil").withAmount(100), arrayOf(ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32000), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32000), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32000), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32000), null, ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32000), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32000), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32000), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32000)), ItemBracketHandler.getItem("minecraft:paper", 0), ItemBracketHandler.getItem("Forestry:stamps", 0))
        Carpenter.addRecipe(10, LiquidBracketHandler.getLiquid("seedoil").withAmount(100), arrayOf(null, null, null, null, ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32001), null, null, null, null), ItemBracketHandler.getItem("minecraft:paper", 0), ItemBracketHandler.getItem("Forestry:stamps", 0))
        Carpenter.addRecipe(10, LiquidBracketHandler.getLiquid("seedoil").withAmount(100), arrayOf(ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32011), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32011), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32011), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32011), null, ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32011), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32011), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32011), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32011)), ItemBracketHandler.getItem("minecraft:paper", 0), ItemBracketHandler.getItem("Forestry:stamps", 0))
        Carpenter.addRecipe(10, LiquidBracketHandler.getLiquid("seedoil").withAmount(100), arrayOf(null, null, null, null, ItemBracketHandler.getItem("IC2:itemCoin", 0), null, null, null, null), ItemBracketHandler.getItem("minecraft:paper", 0), ItemBracketHandler.getItem("Forestry:stamps", 0))
        Carpenter.addRecipe(10, LiquidBracketHandler.getLiquid("seedoil").withAmount(100), arrayOf(null, null, null, null, ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32001), null, null, ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32001), null), ItemBracketHandler.getItem("minecraft:paper", 0), ItemBracketHandler.getItem("Forestry:stamps", 1))
        Carpenter.addRecipe(10, LiquidBracketHandler.getLiquid("seedoil").withAmount(100), arrayOf(null, null, null, null, ItemBracketHandler.getItem("IC2:itemCoin", 0), null, null, ItemBracketHandler.getItem("IC2:itemCoin", 0), null), ItemBracketHandler.getItem("minecraft:paper", 0), ItemBracketHandler.getItem("Forestry:stamps", 1))
        Carpenter.addRecipe(10, LiquidBracketHandler.getLiquid("seedoil").withAmount(100), arrayOf(ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32001), null, ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32001), null, ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32001), null, ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32001), null, ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32001)), ItemBracketHandler.getItem("minecraft:paper", 0), ItemBracketHandler.getItem("Forestry:stamps", 2))
        Carpenter.addRecipe(10, LiquidBracketHandler.getLiquid("seedoil").withAmount(100), arrayOf(ItemBracketHandler.getItem("IC2:itemCoin", 0), null, ItemBracketHandler.getItem("IC2:itemCoin", 0), null, ItemBracketHandler.getItem("IC2:itemCoin", 0), null, ItemBracketHandler.getItem("IC2:itemCoin", 0), null, ItemBracketHandler.getItem("IC2:itemCoin", 0)), ItemBracketHandler.getItem("minecraft:paper", 0), ItemBracketHandler.getItem("Forestry:stamps", 2))
        Carpenter.addRecipe(10, LiquidBracketHandler.getLiquid("seedoil").withAmount(100), arrayOf(null, null, null, ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32001), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32002), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32001), null, null, null), ItemBracketHandler.getItem("minecraft:paper", 0), ItemBracketHandler.getItem("Forestry:stamps", 3))
        Carpenter.addRecipe(10, LiquidBracketHandler.getLiquid("seedoil").withAmount(100), arrayOf(null, null, null, ItemBracketHandler.getItem("IC2:itemCoin", 0), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32013), ItemBracketHandler.getItem("IC2:itemCoin", 0), null, null, null), ItemBracketHandler.getItem("minecraft:paper", 0), ItemBracketHandler.getItem("Forestry:stamps", 3))
        Carpenter.addRecipe(10, LiquidBracketHandler.getLiquid("seedoil").withAmount(100), arrayOf(ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32001), null, ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32001), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32002), null, ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32002), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32001), null, ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32001)), ItemBracketHandler.getItem("minecraft:paper", 0), ItemBracketHandler.getItem("Forestry:stamps", 4))
        Carpenter.addRecipe(10, LiquidBracketHandler.getLiquid("seedoil").withAmount(100), arrayOf(ItemBracketHandler.getItem("IC2:itemCoin", 0), null, ItemBracketHandler.getItem("IC2:itemCoin", 0), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32013), null, ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32013), ItemBracketHandler.getItem("IC2:itemCoin", 0), null, ItemBracketHandler.getItem("IC2:itemCoin", 0)), ItemBracketHandler.getItem("minecraft:paper", 0), ItemBracketHandler.getItem("Forestry:stamps", 4))
        Carpenter.addRecipe(10, LiquidBracketHandler.getLiquid("seedoil").withAmount(100), arrayOf(ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32002), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32001), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32002), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32002), null, ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32002), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32002), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32001), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32002)), ItemBracketHandler.getItem("minecraft:paper", 0), ItemBracketHandler.getItem("Forestry:stamps", 5))
        Carpenter.addRecipe(10, LiquidBracketHandler.getLiquid("seedoil").withAmount(100), arrayOf(ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32013), ItemBracketHandler.getItem("IC2:itemCoin", 0), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32013), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32013), null, ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32013), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32013), ItemBracketHandler.getItem("IC2:itemCoin", 0), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32013)), ItemBracketHandler.getItem("minecraft:paper", 0), ItemBracketHandler.getItem("Forestry:stamps", 5))
        Carpenter.addRecipe(10, LiquidBracketHandler.getLiquid("seedoil").withAmount(100), arrayOf(ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32002), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32001), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32002), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32001), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32003), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32001), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32002), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32001), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32002)), ItemBracketHandler.getItem("minecraft:paper", 0), ItemBracketHandler.getItem("Forestry:stamps", 6))
        Carpenter.addRecipe(10, LiquidBracketHandler.getLiquid("seedoil").withAmount(100), arrayOf(ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32013), ItemBracketHandler.getItem("IC2:itemCoin", 0), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32013), ItemBracketHandler.getItem("IC2:itemCoin", 0), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32014), ItemBracketHandler.getItem("IC2:itemCoin", 0), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32013), ItemBracketHandler.getItem("IC2:itemCoin", 0), ItemBracketHandler.getItem("gregtech:gt.metaitem.01", 32013)), ItemBracketHandler.getItem("minecraft:paper", 0), ItemBracketHandler.getItem("Forestry:stamps", 6))
        Assembler.addRecipe(ItemBracketHandler.getItem("dreamcraft:item.CoinChunkloaderTierI", 0), ItemBracketHandler.getItem("dreamcraft:item.CoinBlank", 0), ItemBracketHandler.getItem("gregtech:gt.integrated_circuit", 1).amount(0), LiquidBracketHandler.getLiquid("ender").withAmount(3000), 600, MV)
        Assembler.addRecipe(ItemBracketHandler.getItem("dreamcraft:item.CoinChunkloaderTierII", 0), ItemBracketHandler.getItem("dreamcraft:item.CoinBlank", 0), ItemBracketHandler.getItem("gregtech:gt.integrated_circuit", 2).amount(0), LiquidBracketHandler.getLiquid("ender").withAmount(6000), 600, HV)
        Assembler.addRecipe(ItemBracketHandler.getItem("dreamcraft:item.CoinChunkloaderTierIII", 0), ItemBracketHandler.getItem("dreamcraft:item.CoinBlank", 0), ItemBracketHandler.getItem("gregtech:gt.integrated_circuit", 3).amount(0), LiquidBracketHandler.getLiquid("ender").withAmount(12000), 600, EV)
        Assembler.addRecipe(ItemBracketHandler.getItem("dreamcraft:item.CoinChunkloaderTierIV", 0), ItemBracketHandler.getItem("dreamcraft:item.CoinBlank", 0), ItemBracketHandler.getItem("gregtech:gt.integrated_circuit", 4).amount(0), LiquidBracketHandler.getLiquid("ender").withAmount(24000), 600, IV)
        Assembler.addRecipe(ItemBracketHandler.getItem("dreamcraft:item.CoinChunkloaderTierV", 0), ItemBracketHandler.getItem("dreamcraft:item.CoinBlank", 0), ItemBracketHandler.getItem("gregtech:gt.integrated_circuit", 5).amount(0), LiquidBracketHandler.getLiquid("ender").withAmount(48000), 600, LUV)
    }
}